### ISSUE TITLE
CT 0.99.4-1 file-picker in KDE / xdg-desktop-portal-kde 

### ISSUE THREAD

**Issue by ciranus** [giuspen/cherrytree#1000]
The KDE file-picker is better than the gtk file-picker.
This is why **xdg-desktop-portal-kde** is available (Debian/Ubuntu & all).

Expected behaviour in KDE with 'xdg-desktop-portal-kde' installed:

`GTK_USE_PORTAL=1 /usr/bin/firefox`

will use KDE file-picker in Firefox (or any other gtk apps).

'GTK_USE_PORTAL=1' has no effect on CT 0.99.4-1

Enhancement proposal:
- enable 'GTK_USE_PORTAL=1' 

-------------
_cherrytree_0.99.4-1_amd64.deb / Debian_

**Comment by txe** [comment]
I thought it should work out the box, but turns out `Gtk::FileChooserDialog` should be replaced by `Gtk::FileChooserNative`.
I wonder if is there any drawbacks to use `native` dialog?

**Comment by ForeverRainbow** [comment]
@txe You can't customise `Gtk::FileChooserNative`, so can't add buttons, actions, etc (it inherits from `NativeDialog` instead of `Dialog`)

**Comment by ciranus** [comment]
@txe
I don't know the technics behind it. So much history on it.
What I know is that using a gtk file-picker is a nightmare when used to KDE one.
It took more than 10 years to have a correct file-picker for gtk apps in KDE.
It works perfectly for Firefox, Thunderbird.
I use very few gtk apps (less as possible), and don't exactly know what happen with others.

Not a major issue, but CT-gtk3 is may be an opportunity to implement this xdg-desktop-portal tweak.

**Comment by txe** [comment]
Don't worry, I'm working on it.

**Comment by txe** [comment]
Done, now it should work
