### ISSUE TITLE
Building Cherrytree on Windows (Future)

### ISSUE THREAD

**Issue by metal450** [giuspen/cherrytree#1003]
I'm following the instructions here: https://github.com/giuspen/cherrytree/tree/master/future#building-cherrytree-on-windows

...In an attempt to build "future" on Windows.  However, the step ./autogen.sh yielded:

     ./autogen.sh: line 7: autoreconf: command not found

Adding this in the setup instructions fixed it:

    pacman -S --needed --noconfirm base-devel

...However, the configure command then failed:

     ./configure --disable-memory-leak-detection
     configure: loading site script /etc/config.site
     checking for a BSD-compatible install... /usr/bin/install -c
     checking whether build environment is sane... yes
     checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
     checking for gawk... gawk
     checking whether make sets $(MAKE)... yes
     checking whether make supports nested variables... yes
     checking build system type... x86_64-pc-msys
     checking host system type... x86_64-pc-msys
     checking how to print strings... printf
     checking for style of include used by make... GNU
     checking for gcc... no
     checking for cc... no
     checking for cl.exe... no
     configure: error: in /home/Metal450/cpputest-3.8:
     configure: error: no acceptable C compiler found in $PATH
     See config.log for more details

Thus, also needed in the instructions:

    pacman -S --needed --noconfirm gcc

**Comment by metal450** [comment]
Also cmake was missing

**Comment by metal450** [comment]
...However, unfortunately it still won't build - and now I'm stuck.  It says gtkmm3 is missing, though I definitely did install mingw-w64-x86_64-gtkmm3 per the instructions.  Here's what it shows:

     $ ./build.sh Release
     CMAKE_BUILD_TYPE=Release
     Tests are ON
     -- Checking for module 'gtkmm-3.0'
     --   No package 'gtkmm-3.0' found
     CMake Error at /usr/share/cmake-3.17.3/Modules/FindPkgConfig.cmake:497 (message):
       A required package was not found
     Call Stack (most recent call first):
       /usr/share/cmake-3.17.3/Modules/FindPkgConfig.cmake:681 (_pkg_check_modules_internal)
       CMakeLists.txt:92 (pkg_check_modules)

**Comment by ForeverRainbow** [comment]
@metal450 The steps I use to sucessfully build on windows (not quite the same as the readme)

- Install mingw (`pacman -S mingw-w64-x86_64-gcc`) not sure if you have, but the `gcc` package is msys2 gcc not mingw64-gcc
- Install `ninja` (`pacman -S ninja`)
- Install mingw version of cmake (`pacman -S mingw-w64-x86_64-cmake`) (It has a different path and can find mingw packages)
- Install autoconf (`pacman -S autoconf`)

1. Download and install cppputest, skip `./autogen.sh` and run just `./configure` and then `make install`
2. Download cherrytree sources, create a build directory, cd into it and then run `cmake -GNinja <path to cherrytree/future>`

Using ninja was needed for me because otherwise it defaulted it msvc.

**Comment by txe** [comment]
@metal450, make sure you start 64 bit console - "MSYS2 MinGW 64-bit".

**Comment by metal450** [comment]
> @metal450, make sure you start 64 bit console - "MSYS2 MinGW 64-bit".

Ahh, now I see that in the instructions. I wasn't clear that it actually installed 3 completely different shortcuts and you have to launch it with that explicit shortcut.  I thought that was just referring to having installed MSYS2 64-bit, which I had.

Still tho, no go. If I quit msys and re-run msys with that different shortcut, perform all the listed steps, now the error is:

     $ ./build.sh Release
     CMAKE_BUILD_TYPE=Release
     CMake Error: The current CMakeCache.txt directory C:/msys64/home/Metal450/cherrytree/future/build/CMakeCache.txt is different than the directory /home/Metal450/cherrytree/future/build where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
     CMake Error: The source "C:/msys64/home/Metal450/cherrytree/future/CMakeLists.txt" does not match the source "/home/Metal450/cherrytree/future/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.

**Comment by metal450** [comment]
> @metal450 The steps I use to sucessfully build on windows (not quite the same as the readme)

Thanks for the ideas.  Trying it this way, it fails at:

     Make Error at C:/msys64/mingw64/share/cmake-3.17/Modules/CMakeTestCCompiler.cmake:60 (message):
       The C compiler

    "C:/msys64/mingw64/bin/cc.exe"

    is not able to compile a simple test program.

    It fails with the following output:

    Change Dir: C:/msys64/home/Metal450/cherrytree/future/CMakeFiles/CMakeTmp

    Run Build Command(s):C:/msys64/usr/bin/ninja.exe cmTC_a097c && [1/2] Building C object CMakeFiles/cmTC_a097c.dir/testCCompiler.c.obj
    FAILED: CMakeFiles/cmTC_a097c.dir/testCCompiler.c.obj
    C:\msys64\mingw64\bin\cc.exe    -o CMakeFiles/cmTC_a097c.dir/testCCompiler.c.obj   -c testCCompiler.c
    /bin/sh: C:msys64mingw64bincc.exe: command not found
    ninja: build stopped: subcommand failed.

Notice: C:msys64mingw64bincc.exe. It's missing the slashes - something screwy with forwards slashes vs backslashes...?

**Comment by ForeverRainbow** [comment]
@metal450 Thats... weird looks like the paths havnt been escaped properly. But your first error with cmake should be a trivial fix. Just run `rm build/CMakeCache.txt` and it should work

**Comment by metal450** [comment]
Fixed!  Next errors:

```
...
[100%] Linking CXX executable run_tests.exe
[100%] Built target cherrytree
[100%] Built target run_tests
.............................ERROR: Data Error in encrypted file. Wrong password? : 7zr.ctd
...................
(run_tests.exe:3108): glibmm-CRITICAL **: 12:18:18.886: Class::register_derived_type(): base_query.type_name is NULL.
[2020-07-10 12:18:18.886] [warning] C:\Users\Metal450\AppData\Local\cherrytree\config.cfg missing

(run_tests.exe:3108): glibmm-CRITICAL **: 12:18:19.261:
unhandled exception (type Glib::Error) in signal handler:
domain: gtk-icon-theme-error-quark
code  : 0
what  : Icon 'cherrytree' not present in theme Adwaita
...
```

**Comment by giuspen** [comment]
Don't worry about those errors running the unit tests. In particular if you still seeing at the end:

OK (49 tests, 49 ran, 6243 checks, 0 ignored, 0 filtered out, 5758 ms)

**Comment by metal450** [comment]
Yeah, it shows that at the end.  However, cherrytree fails to run reporting a whole bunch of missing DLLs, so I figured it might be related to all the reported build errors.

**Comment by giuspen** [comment]
well you either have to run cherrytree from the msys2 mingw64 terminal or it won't work. you cannot just double click on cherrytree.exe. In order to create a standalone working package with all the dependencies out of the msys2 mingw64 terminal there is a script: scripts/msys2_prepare_standalone.sh

**Comment by txe** [comment]
yeah, maybe better README is needed )

**Comment by metal450** [comment]
@giuspen: Ah - Yup, that does it!  All up and running :)

@txe: Yea - hopefully the above experiences from a first-time, from-scratch builder could be inform for some potential clarifications, to avoid confusion for other first-timers :)

**Comment by ForeverRainbow** [comment]
Maybe just a link to this issue like with the macos?

**Comment by giuspen** [comment]
It makes sense to improve the README

**Comment by txe** [comment]
I updated the readme, thanks everyone for help!

**Comment by giuspen** [comment]
thanks @txe !
