### ISSUE TITLE
CT 0.99.4-1 / Help » About » Website link [KDE]

### ISSUE THREAD

**Issue by ciranus** [giuspen/cherrytree#1004]
Clicking “Help » About » **Website**” will not open in KDE default browser, but will request a program to be selected in a pop-up calling “Discover” application. [ see [illustration](https://reho.st/self/dcee40fe1e9f3353160cf461723124e28d1e2993.png) ].

I've never used "Discover" in KDE because totally optional, and request 25MB unnecessary extra packages.

`appstream apt-config-icons libglib2.0-bin libglib2.0-data libpackagekit-glib2-18 packagekit plasma-discover plasma-discover-common`

Why a GTK application is requesting this “Discover” to open a web link is a mystery to me.
With
```
$ xdg-settings get default-web-browser 
firefox.desktop
```

`$ xdg-open https://www.giuspen.com/cherrytree/`

should be enough to open this web link, especially because all other links in notes do not require at all something specific.

Proposal: make it simple
-  either use **xdg-open** by default to open this link ;
-  or use the web application selected in the preferences to open links.

---
_Cherrytree_0.99.4-1 / Debian / plasmashell 5.18.5_

**Comment by Thmyris** [comment]
Hi, just here to lyk, the illustration gives a 403.

**Comment by ciranus** [comment]
403 ? Strange. Works for me. Another one: 
https://nsa40.casimages.com/img/2020/07/13/200713050149885915.png

**Comment by Thmyris** [comment]
Yep this 2nd one works, but the link in OP is still 403 Forbidden. It probably works with your login.

**Comment by ciranus** [comment]
No login used.
Still work in a "normal" browser window, but does not work in a "private" window. 
Don't know why, because the top site is OK in normal&private mode: https://reho.st/

**Comment by txe** [comment]
What the output the following command?
```
cat /usr/share/applications/defaults.list | grep x-scheme-handler/http
```

**Comment by ciranus** [comment]
Good question.
/usr/share/applications/defaults.list does not exist in my system.

**Comment by ciranus** [comment]
For info, bug precisely described in first post ("Clicking “Help » **About » Website**” will not open in KDE default browser,") is still open for 0.99.**6**-1.deb.
(_minor issue, may be only in my light KDE environment_).

**Comment by txe** [comment]
I'm surprised, it's using `xdg-open` so it should work fine.
I will trying it on KDE.

**Comment by ciranus** [comment]
To be even more precise, what is really really strange is that the link "Help > **Online Manual**" works perfectly.

**Comment by txe** [comment]
Ah, I got it, thanks.
This part is handled by Gtk, but the behavior can be overridden, I'll fix it right now.
