### ISSUE TITLE
CT 0.99.4-1 - Link markdown paste problem

### ISSUE THREAD

**Issue by ciranus** [giuspen/cherrytree#1007]
After trying different Markdown copy firefox addons, thinking they were buggy, I came to the conclusion the bug is in CT.

Steps to reproduce:

1. Install [ [Copy Markdown link](https://addons.mozilla.org/fr/firefox/addon/copy-markdown-link/) 7kB ] firefox addon
2. visit https://www.giuspen.com/cherrytree/
3. right-click > "Copy Markdown link"

In a text editor, it will give :
`[cherrytree – giuspen](https://www.giuspen.com/cherrytree/)`

The link pasted in CT will be
` https://www.giuspen.com/cherrytree/)`
 which is not correct (the parenthesis should not be part on the link).

**Comment by txe** [comment]
What OS do you use?

**Comment by ciranus** [comment]
Now Debian, or can be ubuntu (other partition).
But KDE on both (without any gnome at all: ie pure basic KDE).
The text editor result in OP is kate with markdown hightlighter activated.

**Comment by ciranus** [comment]
Not a big one, but still alive in 0.99.11.
(_seems to be an easy one, but I probably underestimate_).
