### ISSUE TITLE
Glib-Error gmem.c:239 failed to allocate 13107 bytes aborting

### ISSUE THREAD

**Issue by saeed662** [giuspen/cherrytree#1008]
Cherrytree v0.39.4 
When exporting to PDF it crashes with the following error:
Glib-Error gmem.c:239 failed to allocate 13107 bytes aborting

the total file size of cherrytree .cbt file is 2.4MB (has a lot of screenshots)

It also hangs on linux when trying to export to PDF,  just tested it, very strange!

**Comment by saeed662** [comment]
I figured out what was going on after tracing back my steps,
The issue seemed to be a file corruption of some sort. 

To reproduce the error this is what I had done, I had used a codeblock and pasted a long encoded string (I am writing an infosec report) the string was a powercat encoded shell,  after removing that encoded long string from the codeblock and re-saving the file I was able to export PDF files again without the Glib memory error.

I will leave this issue open if you feel it should be closed please feel free to close it.  
Thank you devs for all your hard work.

**Comment by txe** [comment]
I cannot reproduce the issue, I tried to put a content of `https://github.com/besimorhino/powercat/blob/master/powercat.ps1` into codebox, and creating pdf was just fine.
I think C++ version (0.99 alfa) shouldn't have that issue, but thanks to the big codebox, I found others to fix.
