### ISSUE TITLE
Hi  How to adjust the background color to white ?

### ISSUE THREAD

**Issue by Xietaiy** [giuspen/cherrytree#1009]
Hi  How to adjust the background color to white ?

![image](https://user-images.githubusercontent.com/31933126/87268464-05b8f980-c4fd-11ea-982a-27e8124feaff.png)

**Comment by Thmyris** [comment]
Hey you can do this with rich text nodes. Its under Rich text settings in preferences.

**Comment by Xietaiy** [comment]
@Thmyris thank you very much
