### ISSUE TITLE
[Feature Request] Double toolbar

### ISSUE THREAD

**Issue by sevazre** [giuspen/cherrytree#1010]
It'd be nice having this feature, since one of my monitors is not large enough to hold all the tool icons I want to have easy access to.

![Toolbar](https://user-images.githubusercontent.com/43146889/87295682-d8247e00-c505-11ea-8b6d-64dc1d00ddeb.png)

**Comment by giuspen** [comment]
you can decrease the size of the toolbar icons, have you tried that? View--Decrease Toolbar Icons Size

**Comment by sevazre** [comment]
Yes I know, thanks. I've already done that, but there are so many icons that they look tiny once I've zoom them out. 
 I would rather have just more than one toolbar so as not to have all those icons altogether in an untidy way.

**Comment by txe** [comment]
I added a new toolbar element to split toolbars. You can find it in Preferences dialog, Toolbar, button Add

**Comment by txe** [comment]
I notice that you're using pygtk (0.39) version. I made changes in c++ (0.99) version. You can download it from https://www.giuspen.com/cherrytree/#downl, the next version will be 0.99.6

@giuspen , maybe we need more direct link to C++ version instead of saying "at the end of  download section"?

**Comment by giuspen** [comment]
@txe yes I'll add dedicated anchor

**Comment by txe** [comment]
Thanks!

**Comment by giuspen** [comment]
@txe https://www.giuspen.com/cherrytree/#testing the last packaged version 0.99.5 does not include yet the double toolbar which will be in 0.99.6
