### ISSUE TITLE
Certain files, when attached, fail to display file names.

### ISSUE THREAD

**Issue by DiagonalArg** [giuspen/cherrytree#1016]
I've got an attachment named:

	GnuPG Key security generating & using SubKeys (blog.bravi.org).pdf

The name does not appear next to the paperclip icon, not even in some truncated or modified form

CT: 0.39.4, Ubuntu 16.04, SQLite backend.

**Comment by ciranus** [comment]
And without spaces, is it OK ?
`GnuPG_Key_security_generating_&_using_SubKeys_(blog.bravi.org).pdf`

**Comment by DiagonalArg** [comment]
Sure.  Just as long as there's something recognizable there.  Is that the issue?

**Comment by DiagonalArg** [comment]
Actually, it's not the spaces.  It's the "&" that's the problem.

**Comment by ciranus** [comment]
I never use spaces in filenames, and especially no '&' which is a very specific character 
 (too ambiguous in command line).
If only '&' is your problem, is avoiding and replacing '&' by 'and' a problem ?

**Comment by txe** [comment]
@ciranus, it's still good idea to fix small things that break users workflow or make them confuse.
