### ISSUE TITLE
Node syntax highlighting for C++ version

### ISSUE THREAD

**Issue by ForeverRainbow** [giuspen/cherrytree#1021]
Hi
When selecting syntax highlighting for a node in the C++ version, most languages seem not to have an implementation (they are set to `ct_code` no matter what). Only ones with an icon actually work. This is weird because they seem to work in code boxes (have only tried `json` and `css`) so the implementation is there, just doesn't seem to have been connected to the nodes.

I am guessing this is just a case of forgetting to connect nodes after the backend for syntax highlighting was done.

**Comment by giuspen** [comment]
I can see the issue, I'll have a look thanks @ForeverRainbow
