### ISSUE TITLE
File Attachment Type-Based Icons

### ISSUE THREAD

**Issue by metal450** [giuspen/cherrytree#1027]
Currently, all file attachments show as a "paperclip" icon.  In OneNote, I find it very handy that the attachment icon reflects the system icon for that filetype - for notes that contain many attachments, it makes it much easier to tell at a glance which is which.  Here's an example:

![2020-07-21 13 12 31](https://user-images.githubusercontent.com/1877409/88102156-f3216e80-cb53-11ea-9a4d-665a7e8953db.png)

Note that implementation-wise, it seems to just be taking the icon at the moment you attach the file (i.e. once the file is embedded, its icon remains the same - even if the system icon later changes, if the note is viewed on another platform that has different icons, etc).  So basically, it seems to be extracting the icon once & sticking that image into the note itself - something like attaching an image.

Would be awesome to do something similar in CT :)

**Comment by txe** [comment]
It's pretty simple to get a file-type icon, an example from python
```python
from gi.repository import Gtk, Gio

def get_icon_path(mimetype, size=32):
    icon = Gio.content_type_get_icon(mimetype)
    theme = Gtk.IconTheme.get_default()
    info = theme.choose_icon(icon.get_names(), size, 0)
    if info:
        print(info.get_filename())
```

The small issue, we don't save  a "paperclip" icon in db/xml, so we need to change db/xml format to support that feature.

**Comment by metal450** [comment]
Well, if the file format would need to be changed - perhaps an easier alternative would actually be to just display the icon from the current system?  I can't really think of any downside, except for maybe once there's an Android client it wouldn't be able to figure out icons for PC filetypes

**Comment by metal450** [comment]
Got a rough draft of this working :)

![2020-07-22 02 09 25](https://user-images.githubusercontent.com/1877409/88158071-6d87d800-cbc0-11ea-81d6-8cb17376af57.png)

**Comment by txe** [comment]
Yeah, it can be done.
