### ISSUE TITLE
Links in Russian do not work, files in Russian do not open

### ISSUE THREAD

**Issue by ivan-vasilich** [giuspen/cherrytree#1029]
Sorry for the bad english, i use google translator (i am russian)

CherryTree is a great product. Thanks to the developers.

I switched to C ++ version 0.99 because there were copy and paste issues with hotkeys [802](https://github.com/giuspen/cherrytree/issues/802)
Thank you! Copy and paste with hotkeys works fine.

### In version C ++ 0.99, the following problems were found that prevent it from working fully:

1) Links in the note do not open if the address uses Russian characters. Example:
![1](https://user-images.githubusercontent.com/65276008/88169537-4d026100-cc46-11ea-8900-70e6a89f9c77.png)

2) Files attached to a note with names in Russian cannot be opened. Example:
![2](https://user-images.githubusercontent.com/65276008/88169572-5db2d700-cc46-11ea-8023-1186568e7722.png)

3) I indicate the title of the note in Russian. When saving, some characters from the name disappear (at the beginning and at the end).

![1](https://user-images.githubusercontent.com/65276008/88367144-3c242d80-cdb5-11ea-8f4e-4a9db52d7a48.png)
![2](https://user-images.githubusercontent.com/65276008/88367147-3fb7b480-cdb5-11ea-80e2-7e38cc4af51d.png)

**Comment by txe** [comment]
Thanks for the issues!
I only cannot reproduce the last issue. I created nodes as on the screenshot and they are OK. Can you try it again with a fresh file or a default config file (keep the copy of old ones just in case)?

@giuspen , looks like C++ streams don't understand unicode filenames on Windows. Changing locale doesn't help at all. So options are to convert unicode into something else (I don't like that) or just to remove streams for good.

**Comment by giuspen** [comment]
I don't like streams @txe

**Comment by ForeverRainbow** [comment]
@txe std::ifstream on windows has an overload for `wchar_t*` as its input file which will handle these properly. `std::ifstream` has an overload for `std::filesystem::path::value_type*` which is `wchar_t*` on windows. So another option would be to either use `std::filesystem` (or another standard conforming implementation) or change `fs::path` to return `std::wstring` on windows (which has an overload for `std::ifstream`). I am not sure if mingw has this overload though since it is non-standard and is just a workaround for windows not having proper UTF8 support in paths

**Comment by ivan-vasilich** [comment]
On issue 3 (in response to "I just can't reproduce the latest episode.")

1) In response to "Can you try again with a new file ...?"
Made: "File - New Window". For the experiment, I created 5 notes in Russian. The result of the experiment in the table
![1](https://user-images.githubusercontent.com/65276008/88452967-2c781800-ce8d-11ea-9bfd-9ec980028225.PNG)
![2](https://user-images.githubusercontent.com/65276008/88452969-300b9f00-ce8d-11ea-9713-e951cccfba5d.PNG)

2) In response to "Can you try with the default config file?"
I don't know how to do this. Help with instructions.

**Comment by txe** [comment]
Oh, now I can reproduce it, thanks!

**Comment by txe** [comment]
Fixed, thanks for the issue again!

**Comment by ivan-vasilich** [comment]
Dear @txe, I am very happy.

How soon is the hotfix version available?

Thank you.

**Comment by txe** [comment]
@giuspen mentioned that he would do the next release on weekends.

**Comment by giuspen** [comment]
Yes definitely the next weekend I'm going to package 0.99.7
