### ISSUE TITLE
Exporting from Dark theme to PDF

### ISSUE THREAD

**Issue by MessyKookie** [giuspen/cherrytree#103]
When exporting from a dark theme to PDF if the colour of the text has been set to white instead of being white by default the text is displayed as white. This means that the text is not visible at all.

This does not occur if the text is the default white colour but does occur if a light colour is chosen to fit in with the dark background.

I know I can just as easily select the light theme but using a darker screen is much easier on the eyes when using the program for long periods of time.

**Comment by giuspen** [comment]
I also use the dark background and find the white background dazzling.
I understand the problem but don't really know how to fix it.
Since the PDF background is white I can check for the text that is exactly
white (RGB = FF FF FF) and forcing to black (RGB = 00 00 00) but for other
light colors I'm afraid to do more damage than benefit trying to correct
them.
If you have ideas about how you would handle this let me know.

**Comment by MessyKookie** [comment]
It is hard.

I have done a bit of thinking and research and have come up with something I think will work.
For all colours which do not have a defined background colour, convert to HSL:
```
newL = 100 - oldL
```

With the colours I have tested this works quite well. You can get formulas to do this conversion online but if you use python you can simply use:
```
colorsys.rgb_to_hls(r, g, b)
colorsys.hls_to_rgb(h, l, s)
```

**Comment by giuspen** [comment]
Are you available to test a version? If yes, what operative system are you
on?

**Comment by MessyKookie** [comment]
Hey sorry, Haven't been on for awhile.

I am more than happy to test. I am currently using Kubuntu but can test on Windows as well.

**Comment by giuspen** [comment]
Hi, please try
http://www.giuspen.com/software/cherrytree_0.36.4+r1792-1_all.deb

**Comment by MessyKookie** [comment]
Hey, Just tested it on Kubuntu and on Mint. It is working great.

Thank you so much.

If you ever want help with anything send me an email (kyleb.166@gmail.com) I would love to help out. :)
