### ISSUE TITLE
msys2_prepare_standalone only works in hardcoded path

### ISSUE THREAD

**Issue by metal450** [giuspen/cherrytree#1032]
It looks like future/scripts/msys2_prepare_standalone.sh only works if you move your cherrytree into the hardcoded path:  `~/git/cherrytree`. Otherwise, it fails (cannot find files).

As I'm building on a shared drive (from within a VM), this requires moving the files back & forth to that location each time I want to build.  Better if the script just worked relative to whichever path it's run from? :)

**Comment by metal450** [comment]
Also: after moving it to ~/git/cherrytree & building, it did complete without any errors & produce a cherrytree__win64_portable folder on the desktop - however, cherrytree.exe fails to run.  Double-clicking it doesn't show an error, just nothing happens.  i.e. it seems like maybe it just launches & immediately terminates without showing a UI.

**Comment by ForeverRainbow** [comment]
@metal450 Looking at the script its a hardcoded path:
<https://github.com/giuspen/cherrytree/blob/b6ad426cbabda9004e4ce8a67f90d0420a1d8ad8/future/scripts/msys2_prepare_standalone.sh#L7>
and then cd into it (which is the part I assume fails): <https://github.com/giuspen/cherrytree/blob/b6ad426cbabda9004e4ce8a67f90d0420a1d8ad8/future/scripts/msys2_prepare_standalone.sh#L27>

Should be pretty easy to modify the script to take optionally take working directory arg which should fix this

**Comment by metal450** [comment]
Yup, was just submitting it as a suggestion for the authors - so it will also be easier/clearer for others to build in the future :)

**Comment by giuspen** [comment]
cherrytree__win64_portable is because of an issue, I'll fix this and also see at the hard coded path

**Comment by metal450** [comment]
I saw that there was a commit related this, but the behavior seems the same on my end - I get that folder on the desktop where launching Desktop\cherrytree_0.99.6_win64_portable\mingw64\bin\cherrytree.exe has no response (aka nothing happens / nothing launches).  Or was that a different fix to the script, & it hasn't been addressed yet?

**Comment by giuspen** [comment]
@metal450 if you run ./build.sh from inside the msys2 terminal does it build properly? If you then run ./build/cherrytree.exe still from the msys2 terminal is it opening correctly?

**Comment by ForeverRainbow** [comment]
@giuspen this: https://github.com/giuspen/cherrytree/blob/582df01d2d2d6a323848213b36e6060e71e29002/future/scripts/msys2_prepare_standalone.sh#L6 is the problem I think. Its hardcoded to expect cherrytree to be at `~/git/cherrytree` which is why it fails when its not

**Comment by metal450** [comment]
> @metal450 if you run ./build.sh from inside the msys2 terminal does it build properly? If you then run ./build/cherrytree.exe still from the msys2 terminal is it opening correctly?

Yup, that builds & runs fine.  I was trying to produce a standalone build, to run from outside the terminal, which is what I couldn't get to happen.

**Comment by giuspen** [comment]
@ForeverRainbow that is only a building location issue, I'll fix anyway
@metal450 it is really strange, could it be your antivirus?

**Comment by metal450** [comment]
Nope, I actually did try disabling it.  And it's the built-in Windows Defender anyway, not 3rd party.  It is strange, as the .7z downloaded from giuspen.com works fine.

**Comment by giuspen** [comment]
@metal450 there is an option -mwindows somewhere in a CMakeLists.txt for Windows only builds, if you comment that out then your cherrytree.exe will start with a windows terminal and print out, or your can run it from a windows terminal and see some feedback

**Comment by metal450** [comment]
I don't see any occurrence of "mwindows" in "C:\msys64\home\Metal450\git\cherrytree\future\CMakeLists.txt"

**Comment by giuspen** [comment]
https://github.com/giuspen/cherrytree/blob/master/future/src/ct/CMakeLists.txt line 90

**Comment by metal450** [comment]
Alright, built it with that commented out & then ran from cmd.  It does indeed start & immediately terminate; here's the errors:

```
C:\Users\Metal450\Desktop\cherrytree_0.99.6_win64_portable\mingw64\bin>cherrytree.exe
[2020-07-24 16:26:28.651] [GTK Logger] [critical] Class::register_derived_type(): base_query.type_name is NULL.
[2020-07-24 16:26:28.651] [debug] C:\Users\Metal450\AppData\Local\cherrytree\config.cfg parsed

(cherrytree.exe:5976): Gtk-WARNING **: 16:26:29.121: Found an icon but could not load it. Most likely gdk-pixbuf does not provide SVG support.

(cherrytree.exe:5976): Gtk-WARNING **: 16:26:29.135: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../gtk+-3.24.20/gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load C:\Users\Metal450\Desktop\cherrytree_0.99.6_win64_portable\mingw64\share\icons\Adwaita\16x16/status\image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Bail out! Gtk:ERROR:../gtk+-3.24.20/gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load C:\Users\Metal450\Desktop\cherrytree_0.99.6_win64_portable\mingw64\share\icons\Adwaita\16x16/status\image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
```

I tried deleting those icon files, but the same error would just pop up for a different icon file.

**Comment by metal450** [comment]
Note: I also tried the build in another copy of Windows; it exited with the same error.

**Comment by giuspen** [comment]
"Most likely gdk-pixbuf does not provide SVG support" - Our icons are ALL SVGs. Very strange, I'll check if there is a particular package that you may be missing for the SVG support.

**Comment by giuspen** [comment]
@metal450 if you copy cherrytree.exe built by you into the portable bundle downloaded does it work? If yes, can you compare with https://sourceforge.net/projects/kdiff3/files/latest/download the bundles generated by you and downloaded to see if any file exists in one and not in the other?

**Comment by metal450** [comment]
> if you copy cherrytree.exe built by you into the portable bundle downloaded does it work?

Yup, that works

> If yes, can you compare with https://sourceforge.net/projects/kdiff3/files/latest/download the bundles generated by you and downloaded to see if any file exists in one and not in the other?

There are a whole bunch of diffs (note: I use BeyondCompare as my recursive diff app, but same deal).  If I ignore any files ending in .cache and only look for non-existence (i.e. not differences of content), the biggest thing missing is mingw64/share/mime.  Downloaded on right, built on left: https://lnk2.tk/snaps/2020-07-27_14.13.32.png

**Comment by metal450** [comment]
Also mingw64/etc/xml/ is missing

**Comment by metal450** [comment]
Incidentally: fwiw, the only reason I'm kinda struggling with this is to try & get a Windows build with indentation running, but I think 0.99.7 is about up today? In which cases I wouldn't have an immediate need to build in Windows, could continue testing in Linux.  Just trying to get a Windows build w/ indentation, & that's about it ;)

**Comment by giuspen** [comment]
Ok, 0.99.7 will come likely in the next weekend

**Comment by metal450** [comment]
With the current master, it now produces an empty cherrytree_0.99.6_win64_portable dir on the desktop (and the same cherrytree-msys2 as before, which doesn't seem to contain the actual cherrytree build).  Where is it now putting its full output bundle?

**Comment by giuspen** [comment]
This will surely be sorted out before the start of next week

**Comment by metal450** [comment]
Incidentally - as of today, this script still isn't producing a bundle I can run.  I still need to build with the script, then take the generated .exe and add it to my previous bundle directory that I got from downloading giuspen.com.
