### ISSUE TITLE
C++: Crash When Pasting HTML

### ISSUE THREAD

**Issue by metal450** [giuspen/cherrytree#1033]
Testing out 0.99.6-1 on Kubuntu 20.04, I was able to make CherryTree crash by pasting some HTML to the UI.

The Html is attached.  It's useless content - I was having some other copy/paste issue, so I just grabbed some random text from the GMail page I had open in Firefox & discovered that pasting it caused CT to immediately crash.

To reproduce: open (view) the attached file in Firefox, select-all, then paste into CT.  It happens for me every time.

[test.zip](https://github.com/giuspen/cherrytree/files/4964312/test.zip)

**Comment by ciranus** [comment]
I confirm.
Copy test made from firefox-78esr to CT 0.99-6.1.deb in Debian KDE environment.

**Comment by txe** [comment]
Thanks, I fixed the issue
