### ISSUE TITLE
Add functions for working with tables

### ISSUE THREAD

**Issue by ivan-vasilich** [giuspen/cherrytree#1037]
I'm using C ++ version 0.99

I could not use tables in my work due to the lack of the required minimum of functions.

Required minimum functions:
• Insert a column
• Ability to paste text from the clipboard into a table cell
• Ability to pick up text from a table cell to the clipboard

Additionally:
• Make the column name "click me" without a space (eg ClickMe). So it is more convenient to select with a double click to replace the name with your own
• Formatting text in a column (left, right, center)

**Comment by giuspen** [comment]
You can already insert a column currently right clicking on any cell other than an header cell
You can already ciopy and paste with Ctrl+C/Ctrl+V (there is not a dedicated menu item)
The "click me" with the new implementation of the tables will eventually go.
In my opinion (to agree with @txe) we will allow to right click on any cell without distinction header or not and you will be able to add a column or a row.

**Comment by ivan-vasilich** [comment]
Insert a column by right-clicking in the header cell - yes, it works. It should be done so that the insert is in any cell.

Copy and paste using Ctrl + C / Ctrl + V - doesn't work for me.
Ctrl + C - does not take text from the cell to the clipboard.
Ctrl + V - inserts text not into the cell, but to the right of the table.

**Comment by txe** [comment]
@ivan-vasilich, about Ctrl+C/Ctrl+V issue. I have no idea why it doesn't work in your case.
To be sure, 
to use Ctrl+C: select text in one cell, press Ctrl+C
to use Ctrl+V: put cursor in one cell, press Ctrl+V

I tried it on Linux and Windows and it just works in both cases.

**Comment by ivan-vasilich** [comment]
Dear TXE.

I am sure, since I have been using Ctrl + C / Ctrl + V in my work for more than 20 years, I use them unconsciously. I checked it again in a new window. The result is the same:

* Ctrl + C - does not take the text from the cell into the buffer (I checked it like this: I inserted Ctrl + V into the txt file, there is no value from the table cell in the buffer).
* Ctrl + V - inserts the value from the buffer not into the cell, but to the right of the table.

Ctrl + C / Ctrl + V works fine in other programs.

Please tell me what I need to show or do to provide useful information to solve the problem.

**Comment by ivan-vasilich** [comment]
There seems to be a problem with my settings. Now I'm doing experiments.

**Comment by ivan-vasilich** [comment]
This I created the problem Ctrl + C / Ctrl + V. I set the settings:
* Copy without formatting - Ctrl + C
* Paste without formatting - Ctrl + V.

I replaced the settings with Ctrl + Shift + C and Ctrl + Shift + V respectively. Copy and Paste (Ctrl + C / Ctrl + V) works fine now.

TXE, thank you.

**Comment by txe** [comment]
I did the following things:
- removed "Click Me" in table header
- popup menu is now the same for header or ordinary cell, so adding new columns is possible from any cell

I still don't why Ctrl+C\V don't work in some cases. if I could repeat it, I would fix it.

`Formatting text in a column (left, right, center)` cannot be done for now, though it's possible, it's a lot of work and maybe break backward compatibility with pygtk. There is a bigger issue #194 that covers this feature.
