### ISSUE TITLE
Close window without creating file

### ISSUE THREAD

**Issue by ivan-vasilich** [giuspen/cherrytree#1038]
I'm using C ++ version 0.99.

• Doing: "File - New Window". Create a note
• I don't want to save to a file (I did it for testing)
• I exit "File - Exit" or press X (Close window)

Prevents exit without saving the file.
• Have to make an unnecessary file
• Then exit and delete this file

**Comment by ciranus** [comment]
I have hesitated few days ago to open an issue related to this one, but here is my experience formulated differently.
I wanted to open a new instance just for test purpose, with no intention to save it.
The only way to quit without saving was to **kill** the application, which is not very clean.
I would have expected something like...
"_Do you really want to quit without saving ? yes/no_"

**Comment by ivan-vasilich** [comment]
I created this topic as I created many windows to describe the problem for another topic. I think this needs to be fixed.

Yes, so good: "Do you really want to exit without saving? Yes / No"

**Comment by txe** [comment]
Fixed, it actually worked, just option "AutoSave" caused this issue.
