### ISSUE TITLE
Unicode text from browser is not copied correctly

### ISSUE THREAD

**Issue by Fixer-007** [giuspen/cherrytree#104]
When I try to past this Cyrillic text from a webpage from here http://donbassmineral.blogspot.com/:

```Все-таки не перестают меня удивлять "банальные" известняковые карьеры Новотроицкого, Докучаевска, Стылы и Комсомольского. Вроде бы известняк себе и известняк, да и карьерам этим лет и лет, ста еще нет, но по восьмому десятку каждый из них уже разменял, а первые выработки известняка для своего металлургического завода в нынешнем Докучаевске делал еще сам вседонецкий дедушка Хьюз (кто не знает, его именем назывался городок - Юзовка, нынешний Донецк).```

I get in cherrytree:
```A5-B0:8 =5 ?5@5AB0NB <5=O C482;OBL "10=0;L=K5" 8725AB=O:>2K5 :0@L5@K >2>B@>8F:>3>, >:CG052A:0, !BK;K 8 ><>;LA:>3>. @>45 1K 8725AB=O: A515 8 8725AB=O:, 40 8 :0@L5@0< MB8< ;5B 8 ;5B, AB0 5I5 =5B, => ?> 2>AL<>B:8 8725AB=O:0 4;O A2>53> <5B0;;C@38G5A:>3> 702>40 2 =K=5H=5< >:CG052A:5 45;0; 5I5 A0< 2A54>=5F:89 454CH:0 %LN7 (:B> =5 7=05B, 53> 8<5=5< =07K20;AO 3>@>4>: - .7>2:0, =K=5H=89 >=5F:).```

If i paste this text via Ctrl-Shft-V it is displayed correctly but looses formatting.

0.36.4 / Win7sp1 / Firefox 43, Ukrainian language interface, pasted text is in russian from Unicode page.

**Comment by giuspen** [comment]
What web browser do you use?

2016-01-30 23:18 GMT+00:00 Fixer <notifications@github.com>:

**Comment by Fixer-007** [comment]
Mozilla Firefox 43

**Comment by giuspen** [comment]
Please try http://www.giuspen.com/software/cherrytree_0.36.4+r1785_win32_portable.7z

**Comment by Fixer-007** [comment]
>Please try http://www.giuspen.com/software/cherrytree_0.36.4+r1785_win32_portable.7z

Fixed the issue for me, thank you! Can be closed :) :+1:
