### ISSUE TITLE
C++ Richtext Paste Regression Since 0.99.6

### ISSUE THREAD

**Issue by metal450** [giuspen/cherrytree#1044]
In 0.99.6, I was able to paste formatted text into RichText nodes with the formatting (including size & highlights) preserved.  However, if I build from the current master (on Linux), small text & highlights no longer seem to get pasted through.  Here's a screenshot of some pasted formatted text in 0.99.6:

![2020-07-27 19 54 57](https://user-images.githubusercontent.com/1877409/88613875-52dfb400-d043-11ea-99f9-b89f9473569a.png)

And here's the same text pasted into the current master - you can see that "small" is no longer small, and there's no longer highlight:

![2](https://user-images.githubusercontent.com/1877409/88613889-5d01b280-d043-11ea-82c7-63a5ec9814b7.png)

**Comment by ciranus** [comment]
> In 0.99.6, I was able to paste formatted text into RichText nodes with the formatting (including size & highlights) preserved. **However, if I build from the current master** (on Linux), small text & highlights no longer seem to get pasted through.

For info, I cannot reproduce your problem with [cherrytree_0.99.6-1_amd64.deb](https://www.giuspen.com/software/cherrytree_0.99.6-1_amd64.deb) from giuspen.com.

No problem seen with copy/paste of highlighted or small font text.

**Comment by metal450** [comment]
The issue is in the current master, not the builds on giuspen.com.  You have to build from source.

**Comment by ciranus** [comment]
Yes but first... are you 100% you don't cut or copy as **Plain text** ?

**Comment by metal450** [comment]
Yes.  Bold/italic/strikethrough/large would not come through if it were plaintext.

**Comment by ciranus** [comment]
In which environment are you building ? (Debian / Ubuntu / Release ?).

**Comment by metal450** [comment]
Ubuntu (specifically, Kubuntu).  Just git clone, open "future" in VS Code, build, and run.

**Comment by ciranus** [comment]
Which [k]ubuntu  ? bionic ? eoan ? focal ? groovy ?

**Comment by metal450** [comment]
20.04 Focal

**Comment by ciranus** [comment]
If this feedback can help for investigation, I don't know:

` dpkg -l build-essential libxml2-utils cmake libgtkmm-3.0-dev libgtksourceviewmm-3.0-dev libxml++2.6-dev libsqlite3-dev libcpputest-dev gettext python3-lxml libgspell-1-dev libcurl4-openssl-dev | awk '/^ii/ {print $2,$3}'
 `

**Comment by ForeverRainbow** [comment]
@metal450 What are you pasting from? If I copy text from libreoffice it works fine on the latest (badfaad2dfc2aab15c887f9ebb9992be38e301eb). I am fedora 32 thought so it may be a specific issue on Kubuntu (Gtk and KDE + ubuntu doesn't seem to mix well).

If you could run it from the commandline and post a log that would be great.

**Comment by txe** [comment]
@metal450, thanks for the issue,
For some reason, when  @ForeverRainbow moved code from one place to another, she removed this part.

**Comment by ForeverRainbow** [comment]
@txe I did?... oops sorry

**Comment by ciranus** [comment]
If  metal450  confirms he has no problem with **cherrytree_0.99.6-1_amd64.deb** from giuspen.com, it's not a gtk/KDE problem (I cannot reproduce his problem in KDE).
The problem comes apparently from his build.
It seems that first step requires a library check-up.

**Comment by ForeverRainbow** [comment]
I would be surprised if this was caused by me since I didn't remove anything from inside functions so it shouldn't have compiled. Also I am not experiencing this with my build but @ciranus I did the HTML refractor _after_ the 0.99.6 release so if it broke things then it makes sense that 0.99.6 would work but the latest wouldn't

**Comment by ciranus** [comment]
You then mean a **regression** has been introduced. Ok, understood.

**Comment by txe** [comment]
Do you remember when you moved CtHtml2Xml , and I asked to do it in a separate commit? That commit shows that part of code was deleted and I wonder how it could be done unintentionally? It's just moving bunch of  code from one file to another at one time.

**Comment by ForeverRainbow** [comment]
@txe Could you highlight the line? I assure you I did not intentionally remove a part of the code, I am not trying to mess up lol.

**Comment by ciranus** [comment]
How is it possible that current dev builds are still simply called "**0.99.6"**, although 0.99.**6-1** is dated "July 19th".
No possibility to better clarify **exact** build output version (**date** ? number ?).
_Just a thought..._

**Comment by txe** [comment]
commit 
https://github.com/giuspen/cherrytree/commit/6085214ec4a907889ccfa27e818ac23662b29f45

line there code existed:  future/src/ct/ct_parser.cc  , line 360
line where the code moved: future/src/ct/ct_parser_html.cc , line 204

**Comment by txe** [comment]
Don't know, it's not funny to me

**Comment by ForeverRainbow** [comment]
@txe Ok, honestly no idea how that happened. I must have not copied that chunk properly. Its a mistake, it happens, sorry.

**Comment by ForeverRainbow** [comment]
@txe I will make a pr to fix this in a bit

**Comment by txe** [comment]
@ForeverRainbow , it's actually going on for a while, breaking good code, trying to redesign working code (and as result breaking it) and other stuff. I'm not going to bother with merging  your PR anymore because even simple things turn out to be unreliable.  Users suffer from these mistakes and I don't want it and I don't have time to review again and again your code.

**Comment by ForeverRainbow** [comment]
@txe Well if thats how you feel its a shame but OK.

**Comment by txe** [comment]
Fixed

**Comment by metal450** [comment]
Thanks for the fix!

**Comment by ciranus** [comment]
@metal450 
To clarify the version number or build chronology confusion, can you please give the exact output of this command with your so called "0.99.6" build installed in tour system ?
`dpkg -l cherrytree | awk '/^ii/ {print $2,$3}'`
Tx.

**Comment by metal450** [comment]
Its 99.6-1.  Anyway, this is fixed, I dont think more reason to keep digging.

**Comment by ciranus** [comment]
Comparing different "99.**6-1**" with"99.**6-1**" builds is not that easy.....
This is why precise build identification is important, and help regression tracking.

**Comment by txe** [comment]
@ciranus, we change a version number only during the new release, so trunk contains the last used release version number, in this case it is 0.99.6-1 (I suppose it was always this way) So no wonder, that @metal450 got the same version number of cherrytree from the trunk as in the last release.

We can either keep "dev" prefix in trunk or add "dev" prefix when code built not for release (though how to know it).

**Comment by metal450** [comment]
What I do in my projects for clarity is I have a build step that auto-generates an incremented human-readable number, based on the git commit, which gets appended to the version number.  Thus there's never any ambiguity: for every build, you know precisely if it came from a different commit, and if that commit was before or after any other build.  i.e. 0.99.6.3567, where 3567 is autogenerated from whichever git commit produced the build.  That number always grows, so i.e. even 0.99.7.3568, you know comes from the next commit.  It's not strictly conventional, but effectively eliminates any ambiguity & makes it really easy to tell.

**Comment by ciranus** [comment]
@txe
I think something should be changed/incremented in the build name **as soon as** the "official" dev build is distributed.
If not, we compare apples with apples which are not exactly apples.... with builds made in different environments, different libs and so on, but with exactly the same name.
Where I am disappointed, I cannot find with dpkg command any possibility to extract a precise build date (this is what I was looking for).
I thought build date was in the control file.

@metal450 
I should have asked you your build for test (I use KDE), but first wanted to clarify your environment, as I have seen some requests for bionic builds....
I now see you see why I raise this point.

**Comment by txe** [comment]
@ciranus, I was focused on the other thing and left the version issue without notice. Thanks for keeping up!
We will definitely add a hash tag (or something like that) to have the version number unique.

**Comment by ciranus** [comment]
Just an hash tag (or something like) may be enough at least to make a difference with the official build which should be considered as a milestone without ambiguity.
Hash tag will mean intermediate or non official build, which might be enough.
I don't know in reality how many people are making CT builds, but it might be very few.
I don't personally, because maturity of current dev build are fine to me, and I don't interfere with the code.

Let's consider this regression experience as an opportunity to improve something.
Thanks to consider my remark as something more positive than a criticism.
