### ISSUE TITLE
C++: Html Paste Justification

### ISSUE THREAD

**Issue by metal450** [giuspen/cherrytree#1051]
When pasting formatted text to the new C++ version, "Justification" formatting is lost (i.e. centered text ends up left-justified).

**Comment by metal450** [comment]
Update: in some cases, it is.  I've found that when pasting from MS Word, Justification works; when pasting from OneNote, it doesn't.

If I copy from OneNote, then paste in Word, then copy again & paste to CherryTree, it works.

**Comment by ciranus** [comment]
Do you still confirm this with 0.99.**8** ?
If yes, please show the content of the clipboard html  block.
(_I have other remarks on html paste feature_).

**Comment by txe** [comment]
Fixed
