### ISSUE TITLE
C++: ToDo Checkbox Shows As Invalid Characters

### ISSUE THREAD

**Issue by metal450** [giuspen/cherrytree#1055]
In the new C++ version (current master, built on Windows), the "checkbox" character for ToDo list is displaying as an unknown/invalid character.  Screenshot (showing the old version, & new C++ version):

![2020-07-28_23 51 16](https://user-images.githubusercontent.com/1877409/88766739-68c9a380-d12d-11ea-9b4c-0b9a68758816.png)

(Also, the cursor doesn't change when hovering them, & there's no action when clicking them - though I imagine it's all related).

**Comment by txe** [comment]
What font do you use for the rich text?

**Comment by txe** [comment]
Or I can use it only on win...

**Comment by metal450** [comment]
> 
> 
> What font do you use for the rich text?

Calibri Normal 10 (the same default font as the MS Office suite)

**Comment by metal450** [comment]
Looks like changing the global font back to Sans Normal makes the boxes appear correctly.  So perhaps the solution is to omit those boxes from the global font setting (i.e. regardless of the font the user selects, always display those boxes in the default font)?  That way whatever the user picks, they won't be affected.

**Comment by metal450** [comment]
...Or perhaps an even better generic solution: if it's possible, when a character is displayed that doesn't exist in the current font, then display that character in the default font?

I just noticed another related issue: with the font set to Calibri, Japanese characters also fail to display.  However, I use Calibri as my font for all other software across Windows, and in those cases Japanese does appear correctly.  Thus, I think it must be using Calibri to display roman characters, & falling back on one that supports Japanese just for those characters?

**Comment by txe** [comment]
I took a look at Colibri font and it contains small amount of symbols, so no surprise it doesn't support checkbox symbols (which actually can be changed, but I cannot recommend it) and symbols of other languages.
I like the idea with fallback font, it will help greatly if I can find how to setup it.

**Comment by giuspen** [comment]
@txe so you propose to set the cursor hovering the todo char same as hovering a link? It is fine for me!

**Comment by txe** [comment]
Fixed, add fallback font "Sans"
