### ISSUE TITLE
Spellcheck Custom Dictionary Entries Storage Location?

### ISSUE THREAD

**Issue by metal450** [giuspen/cherrytree#1060]
Question: when you add new words to the spellcheck dictionary, where are those "custom dictionary" entries stored?  It doesn't seem to be in config.cfg - I'd like to include that to my CherryTree backups :)

**Comment by txe** [comment]
We don't store new word ourselves, and, I'm afraid, they are kept only until the app closed.
Could be fix, I suppose.

**Comment by metal450** [comment]
> I'm afraid, they are kept only until the app closed.

I added a word, quit, and re-launched, and the word I added is not underlined any more - so it definitely seems to be behaving as if it's persistent...?

**Comment by txe** [comment]
Docs say "It is typically saved in the user's home directory", but there is nothing concretely.

**Comment by giuspen** [comment]
https://askubuntu.com/questions/41177/how-do-i-remove-ignore-words-from-gedits-spell-checker-dictionary

**Comment by metal450** [comment]
On Windows, I don't see any instances of "enchant" anywhere under the Windows home directory equivalent (C:\Users\Metal450), so I presume this must be in CherryTree's bundle somewhere itself.  However, none of the "enchant" directories (there are a few) within the CherryTree directory have any files with recent modification dates.  So I'm still not really sure how to solve this :/

**Comment by giuspen** [comment]
We don't know either but we'll find out

**Comment by txe** [comment]
You can find the spellcheck dictionary in `C:\Users\user_name\AppData\Local\enchant`

**Comment by metal450** [comment]
That's it!! And for anyone else trying to find this, on Linux it's ~/.config/enchant

However, one issue: although I've selected "English (United States)" in the CT options on both Linux & Windows, Windows is using the file en_US.dic, whereas Linux is using en.dic.

I'd like to get the two copies to share the same dictionary (by symlinking them to the same dir), but the two versions of CT seem to use different naming convention for the file itself.  In fact, on Linux, no matter which version of "English" I select (United States, United Kingdom, Canada, etc) it always uses en.dic - but no matter what I select on Windows, I can't get it to use that filename.

I know I could just symlink the file directly, but it'd be nice to be able to have them share the enchant directory.  Any thoughts on why they're using different naming convention?

**Comment by giuspen** [comment]
Windows is msys2 which has always the latest versions, if you are using a non rolling release on Linux you may have an older version

**Comment by metal450** [comment]
Linux is Kubuntu 20.04.

Is that to say that the difference of CherryTree on Windows using "en_US.dic," whereas CherryTree on Linux using "en.dic," (language only with no region code) is because of the version of Linux I'm running...?
