### ISSUE TITLE
Request: Store Backups In A Separate Folder

### ISSUE THREAD

**Issue by metal450** [giuspen/cherrytree#1061]
Currently, database backups are stored in the same folder as the main database, right alongside (i.e. db.ctb, db.ctb~, db.ctb~~).  This is a bit non-conducive to both syncing and backups, as we really only need to sync the current database - not it and all of its previous versions.

This could be circumvented if the backups were stored in a different location.  Preferably in a user-configurable, but even if not just separating them from the main db itself would make a big difference.

**Comment by metal450** [comment]
Note: I see that this is related to https://github.com/giuspen/cherrytree/issues/329, but thought I should post it separately as it's a more specific request/solution (however it would also solve the issue described there).

**Comment by txe** [comment]
There are issues with keeping backup separately in some specific folder, for example:
In first user case, there are two db with the same name. We do backup for one file, but if we try to back another db with same name, we can rewrite backups from the previous db.
In the second user case, user can move the db in different folder. How we can understand he moved it or he copied it (returning back to the first user case)

Because of these reasons, many notekeeper apps has a fixed place for notes.

**Comment by metal450** [comment]
To solve the first, the backup name could be taken from the full path of the original database - ie. "c-users-metal450-desktop-db.ctb."  I realize that this could result in "orphaned" databases if the user moves the original, but this is a solution I've seen used fairly often, & it would make conflicts more or less impossible. 

Also, of course it needn't be the *default* solution - just an option, so that users who do perform syncs could choose their tradeoff.  One could argue that a user who proactively goes into the settings & configures a different directory for backups should be responsible for knowing that there are backups there.  You could also have a button like "clear backups directory," to wipe any orphaned backups (this is also a very common solution).

**Comment by metal450** [comment]
Another possible solution which is IMO less ideal, but still better than current: have the backups be in a subdirectory next to the current database.  Like:

folder/db.ctb
folder/backups/......

Then the "backups" dir could be replaced with a symlink, and the sync/backup software configured not to follow symlinks.

I think this is less clean & flexible than allowing a user-configured backup directory tho, which is in my experience by far the most common approach (truly almost every software I use that has auto-backup capability does so like this).  But would at least allow a workaround :)

**Comment by txe** [comment]
Ok, if we start talking about backups and syncing data, I had a different idea how to fix it.

About what user can do now.
So far, user can use google drive or dropbox to sync db between computers, but it is really easy to lost data by using them. Like
- db is not yet updated, you open not-updated db, file gets updates by dropbox (it's possible when you use xml), you save your changes and lost the prev. update.
- or you change db here and there (somehow). and how dropbox will update them? dropbox can merge data, but only xml, not sqlite.

Back to backups, backups are only saved per db save, and I think it might not be helpful in some serious cases.

The first idea was to write a next cloud plugin and handle sync and backup without third-party apps (or maybe plugin that can works with dropbox directly). Pro: we can make sure that is everything alright. Cons: it takes time to write it. And not many people want to have a next cloud server.

The second idea is to give users tools to handle sync and backups by themselves.
So, Cherrytree will be able to execute 4 custom scripts: before opening the db, before saving the db, after saving the db, after closing the db. Every time we pass a file path to the scripts.

For example, user wants to handle sync and backup by git and create custom scripts:
- script "before opening the db": pull data from git
- script "before saving the db": make a copy db in some folder for backup. Also it can try to pull data from git again in case there are changes.
- script "after saving the db": can push changes in git
- script "after closing the db": push changes in git.

If user will try to push data in git and actually data in git was updated before, the process will be stopped but no data will be lost.

Also, I think with running custom scripts user can do than I just came up.

**Comment by metal450** [comment]
I totally agree that sync conflicts also an issue, but I think that's very distinct from this.  Your solutions are great, but they solve a much broader problem (and require much more effort) than the simple desire to be able to separate "original" from "backups."

For instance: even for users who don't sync (i.e. who just have scheduled backups to a NAS or external HDD or something) they probably don't want to mirror 5 copies of their database, just the database itself.  So separating backups from originals allows them to add the database folder to their backup profile, but not "auto-backups," so to speak.

Or another common situation might be having the database in their main fast SSD, backups on a different slow/spinning drive, so they can have a bunch of versions without wasting "usable" space.

And so on and so forth.

Your solution of built-in syncing sounds great.  But it's a much larger & more involved solution for a bit of a different problem than I'm trying to describe here.  Simply: the ability to separate backups from database - whether it's for the purpose of syncing, or for system backup profiles, or for separating onto different partitions, or for the desire to have "centralized storage" of all backups, or any other scenario I might not have envisioned.

I wouldn't tag this request under sync\cloud.

**Comment by txe** [comment]
I adjusted the tag)) 
OK, I mentioned my idea because it is really easy to do.
I'll discuss a backup folder with @giuspen , it can be more issues with it than I mentioned before.

**Comment by metal450** [comment]
Sure.

In case you'd like to have a play/look, here are just a few examples off the top of my head of software that works with a separate backup folder (I use each of these & keep my auto-backups from all software centralized in one main "repo"):
* OneNote (user-settable)
* ManicTime (user-settable)
* WPS Office (user-settable)
* Quicken (/Backup subfolder next to the database - so I use a symlink)
* Anki (/backup subfolder next to the database - so I use a symlink)

:)

**Comment by giuspen** [comment]
I think it makes sense to support a custom folder for the backups, selectable by the user, that defaults to the same folder of the document.
Then in case a custom folder path is configured by the user, we can generate yet one more level of folder that is uniquely identifying the folder path where the document lays (algorithm to discuss but a short hash could do). What do you think @txe ?

**Comment by txe** [comment]
Ok, only instead of hashes, we can use full paths, reasons:
- it's easier for users to find backup in case if there are dbs with the same names 
- the backup folder will be easier to clean up when it is littered with temporary dbs.

Because a db can have the same name with different ext and I want to use the db name in path, so there will be only backups for one db per folder, so user can be sure in results when he copies/deletes the folder.

`/home/user/data/notes.ctd` -> `/backups/home_user_data_notes.ctd/notes.ctd~`

Any comments?

**Comment by giuspen** [comment]
It should be OK, only thing in the past there were issues with the maximum length of paths in windows which was something less than 255, I hope it is no longer the case, that is the only reason to shorten the folder name otherwise I agree 100%.

**Comment by metal450** [comment]
Windows does still have a stupid path length limit.  However, I very much agree with txe - paths are better than hashes, as they're human-readable & more maintainable.  I'd suggest having the pat in the filename (rather than duplicating the directory structure), like i.e. C-Users-Metal450-Documents-Db.ctb

Then to deal with the Windows limit, perhaps cap the max length, and stick a very short hash at the end to make them unique.  That way you get the advantage of easy understandability, but preempt the length limit and collisions.

**Comment by metal450** [comment]
...Or rather than a hash, a timestamp.  Perhaps like C-Users-Metal450-Documents-Db-200730193015.ctb (and the path portion can be cut off if it's over some ridiculous limit.  The timestamp prevents resulting collisions.)

**Comment by txe** [comment]
Done, you can read more about it in the PR

**Comment by metal450** [comment]
Perfect!!  Such an improvement, thanks :D
