### ISSUE TITLE
Request: Custom Font Size for Small (Or Allow CSS Override)

### ISSUE THREAD

**Issue by metal450** [giuspen/cherrytree#1063]
Preferences->Fonts lets you set the "main" font size.  It would be nice to also be able to set the size for "small."

I was hoping I might be able to do this by styling with CSS (there was a style3.css file in the cherrytree config directory), but it didn't take - and I believe per https://github.com/giuspen/cherrytree/issues/145, is not currently supported.

For my notes, I've been using the "superscript" format to try and get smaller smalls.  But it would be great to be able to set our own size, so that I could avoid this :)

**Comment by ciranus** [comment]
> I was hoping I might be able to do this by styling with CSS (there was a style3.css file in the cherrytree config directory), but it didn't take - and I believe per #145, is not currently supported.
>> The css is only for the export to html at the moment

style3.**css** is currently used for **html** formatting (then html export files).
The editor code format is not html, but **markdown** (which cannot understand css).
Then apparently not so obvious to customize **markdown** code with an external style sheet .

**Comment by giuspen** [comment]
@ciranus we are not using markdown to define the formatting but rather a proprietary set of tags based on the GTK tags

**Comment by ciranus** [comment]
Ha ok. It can then also explain #1007 .
But I suppose pure markdown or not, even the specific " proprietary set of tags " is not simply compatible with any css external stylesheet.

**Comment by giuspen** [comment]
No as you said css is only for export to html, we're not exposing such interface to the user for cherrytree font settings

**Comment by metal450** [comment]
So then I'll just leave this as a possible request for the future :)

**Comment by JochenHu** [comment]
I found out that it's possible to create my own style sheet under .\cherrytree_portable\mingw64\usr\share\cherrytree\styles\. I was successfull to change the highlighting of the current line or the bracket matching, but I didn't find any way to change the appearance of headings or small.. Is this not possible here or am I doing something wrong?

**Comment by giuspen** [comment]
@JochenHu you cannot change the heading or small sizes from the css

**Comment by JochenHu** [comment]
@Giuspen - thanks for your answer. Is it possible to change color (for-/background)? That's what I wanted to do..

**Comment by giuspen** [comment]
I'm going to allow additional configuration for headings and small but not in the next release

**Comment by giuspen** [comment]
This will be in upcoming 0.99.34. Three new headings h4,h5,h6 have been added and all the headings plus the 'small' can be customised in several properties.
