### ISSUE TITLE
C++ Bug: ToDo Checkbox Click-Zone Misaligned

### ISSUE THREAD

**Issue by metal450** [giuspen/cherrytree#1068]
A subtle bug: in Linux, when clicking on a todo list checkbox, the 'hit zone' for the mouse is not actually aligned with the checkbox - it's to the left.  If you click on the right half of the checkbox, it doesn't register, but if you click to the left but outside of the checkbox, it does.  It looks like it thinks the check is starting at the far left of the panel (ie. it's thinking there's no margin to the left of the checkbox, when there is).

**Comment by txe** [comment]
Yeah, it bothered me too, fixed.
