### ISSUE TITLE
C++ Bug: Copied Text Pastes Apostrophes As "apos;" In MS Office

### ISSUE THREAD

**Issue by metal450** [giuspen/cherrytree#1072]
Using the current C++ master on Windows, built from source: if I copy some note content from CherryTree & paste it in i.e. MS Word, apostrophes are pasted as `&apos;`

**Comment by txe** [comment]
Do you have another example of how to reproduce it? I don't have MS Word, and LibreOffice doesn't have that issue (probably).

**Comment by metal450** [comment]
It looks like I'm only having luck reproducing it when pasting to MS Office applications.  It happens when pasting formatted text in OneNote, Outlook e-mails, Word docs, Excel, etc.

**Comment by txe** [comment]
Fixed
