### ISSUE TITLE
C++ Bug: Search Crashes Or Misses Results

### ISSUE THREAD

**Issue by metal450** [giuspen/cherrytree#1078]
The following happens in both Windows and Linux (current C++ master, built from source):

1) I did a search for the term "G7X", but the result didn't include several nodes that I knew for certain contained that term
2) I manually switched to one of the nodes containing that term, and searched for it again
3) The UI locked up, pegging one of the CPU cores at 100%

I was able to reproduce it repeatedly, but only when searching for that particular term while that particular node is opened.  If I search for that term while any other node is opened, the results are incomplete (but no crash).  If I search for another term in that node, there's no crash & the results are correct.

I tried typing "G7X into some new nodes & searching, and the results were unpredictable/sporadic.  One time it suddenly caused the search results to be *fully* complete (i.e. it suddenly found all the other instances of that term, which it hadn't found before).  Another time it only found the single new instance I just typed.

**Comment by metal450** [comment]
Just had another search miss results, & this time it was a more "normal" word (i.e. not numerals, like G7X).  The search term was "evernote" - I have a node that has many instances of that word, but it was not listed in the results when searching all nodes.

**Comment by tom-i** [comment]
Same for me, I've searched some string which is inside few nodes via "Ctrl" + "Shift" + "F" and result shows me just one result (maybe the first one) and not others.
`Version: 0.99.7`
`OS: Mint 20`

**Comment by txe** [comment]
I found one cause of freezing and fixed it, though maybe there are more.

@tom-i, thanks for describing, it helped to fix it.

@metal450, I'm not sure if you have the same problems as @tom-i,  If you still have the issue then reopen this one.

**Comment by metal450** [comment]
Doesn't look like I have permission to reopen - however, please note that this issue was two-pronged.  Sometimes it froze, but also it would sometimes miss results.  Did the commit also address missing results? :)

**Comment by txe** [comment]
I'm not sure about missing results because it looks like your case differs from @tom-i's case. So, if you have any issue with search, just say it, I'll try again to figure it out

**Comment by metal450** [comment]
Based on what he's describing, it does sound to me like the same thing: in some rare cases, when I search for a term with ctrl+shift+f, it doesn't return results that I know to exist.

**Comment by metal450** [comment]
The original example with g7x still happens in 0.99.8.  Were 'missed results' addressed by this commit?  If so, I'll rebuild from source & test.  If not, I'll see if I can produce a sample ctd that doesn't include the entirety of my notes, but still exhibits the issue.

**Comment by txe** [comment]
The fix was added 30 min ago, 0.99.8 doesn't contain it.

**Comment by metal450** [comment]
Right right, I just didn't know if the fix only addressed crashing, or if it addressed both crashing & mixed results.  In any case, I will rebuild.

**Comment by metal450** [comment]
Ah, great!! It looks like the current master fixes the missing result issue I was observing too...so even if you didn't intentionally fix it, maybe it got fixed as a side effect of this or something else :)

So...I'll re-close after all, & let you know if I ever see it happen again. (I have seen it in a few other cases, but obviously not since your latest commit - so hopefully this got them all!)

**Comment by txe** [comment]
Great!

**Comment by tom-i** [comment]
Hi guys, looks like I'm on older branch or.. for me, fix doesn't work.
I have 0.99.7 even after `git pull` it :-/

**Comment by txe** [comment]
Maybe your current branch is not master, or your repository is not a clone of @giuspen repository.
try `git checkout master && git pull`

**Comment by tom-i** [comment]
```
~/programs/git_cherrytree(master*) » git checkout master
Already on 'master'
Your branch is up to date with 'origin/master'.
---------------------------------------------------------
~/programs/git_cherrytree(master*) » git pull
Already up to date.
---------------------------------------------------------
~/programs/git_cherrytree(master*) » git remote -v
origin	https://github.com/giuspen/cherrytree.git (fetch)
origin	https://github.com/giuspen/cherrytree.git (push)
```

**Comment by txe** [comment]
what git log shows?

**Comment by tom-i** [comment]
haaa.. I had to build it again.. I'm on 0.99.8 now ;)

About issue.. looks better now..
Thx @txe ;)
