### ISSUE TITLE
Keyboard hotkeys stop working (except F1-12 keys)

### ISSUE THREAD

**Issue by Fixer-007** [giuspen/cherrytree#108]
This is very obscure bug when my Ctrl/Shift-whatever hotkeys refuse to work (except F1-12 keys), I've seen it only once, I've tried to change caps-lock or my language but only program restart helped.

If I reproduce it again I will let you know (in that session I did some text pasting from web browser, adding/deleting nodes and text formatting).

**Comment by lobnev** [comment]
Had similar bug.
All hotkeys = Ctrl/Alt/Shift + "letter" dont work, if launch Cherry with not English keyboard layout.
To fix it, you should quit, change layout to English and launch again. Changing layout during work session doesn`t broke hotkeys functionality.

**Comment by giuspen** [comment]
This seems an issue with the library (GTK2). Soon I will try the switch to GTK3 and I hope to see this and other problems fixed.

**Comment by acicovic** [comment]
I am also having this issue on Windows 10. Although I have not found a standard way of reproducing it, it does seem to be related to changing keyboard language or layout.

Thank you giuspen for all the work you've put into this software.

**Comment by jarickkk** [comment]
I reproduce this bug. I have English and Russian keyboard layouts. If CherryTree starts with English one, it works fine. Else keyboard shortcuts doesn't work (except F1-12 keys).

**Comment by txe** [comment]
It was resolved by Gtk3
