### ISSUE TITLE
C++ Linux: Bottom Node Blocked By Overlay Scrollbar

### ISSUE THREAD

**Issue by metal450** [giuspen/cherrytree#1080]
Using the C++ version on Linux (Kubuntu 20.04, KDE Plasma 5.18.5), if the node list is long enough to fill up the height of the window, and wide enough that it has a horizontal scrollbar, the horizontal scrollbar ends up overlapping the bottom node - making it extremely difficult to drag another node onto it (it's blocked by the horizontal scrollbar overlaying it).

Seems like this could be solved by putting a small margin at the bottom of the node list, so that if you scroll all the way down, the horizontal scrollbar would overlap that margin rather than the last node.

**Comment by txe** [comment]
Fixed
