### ISSUE TITLE
C++ - Check Newer Version does nothing

### ISSUE THREAD

**Issue by mahdi1234** [giuspen/cherrytree#1081]
Not sure it should do anything since i'm git head but anyway clicking it does nothing :) below cmd output

`[2020-08-01 21:52:36.767] [debug] fs::download_file: start downloading https://www.giuspen.com/software/version_cherrytree
`

**Comment by giuspen** [comment]
Look at the status bar after clicking

**Comment by mahdi1234** [comment]
Opps haven't noticed it, understood, closing.
