### ISSUE TITLE
Build future on Mac or use the normal 

### ISSUE THREAD

**Issue by Shizzlebix** [giuspen/cherrytree#1088]
Hey there if i would like the future version:

`[ 81%] Building CXX object src/ct/CMakeFiles/cherrytree_shared.dir/ct_actions_edit.cc.o
In file included from /Users/dkovacs/cherrytree/future/src/ct/ct_actions_edit.cc:22:
In file included from /Users/dkovacs/cherrytree/future/src/ct/ct_actions.h:26:
In file included from /Users/dkovacs/cherrytree/future/src/ct/ct_dialogs.h:26:
In file included from /Users/dkovacs/cherrytree/future/src/ct/ct_misc_utils.h:26:
In file included from /Users/dkovacs/cherrytree/future/src/ct/ct_types.h:30:
In file included from /usr/local/Cellar/glibmm/2.64.2/include/glibmm-2.4/glibmm/ustring.h:21:
/usr/local/Cellar/glibmm/2.64.2/include/glibmm-2.4/glibmm/unicode.h:23:10: fatal error: 'glib.h' file not found
#include <glib.h>`

if i would like to use the normal version:

`./cherrytree
Traceback (most recent call last):
  File "./cherrytree", line 114, in <module>
    f_main(args)
  File "./cherrytree", line 78, in f_main
    import main
  File "/Users/dkovacs/cherrytree/modules/main.py", line 22, in <module>
    import gtk
  File "/usr/local/lib/python2.7/site-packages/gtk-2.0/gtk/__init__.py", line 30, in <module>
  File "/usr/local/lib/python2.7/site-packages/gobject/__init__.py", line 26, in <module>
    from glib import spawn_async, idle_add, timeout_add, timeout_add_seconds, \
  File "/usr/local/lib/python2.7/site-packages/glib/__init__.py", line 22, in <module>
    from glib._glib import *
ImportError: dlopen(/usr/local/lib/python2.7/site-packages/glib/_glib.so, 2): Library not loaded: /usr/local/opt/libffi/lib/libffi.6.dylib
  Referenced from: /usr/local/Cellar/pygobject/2.28.7_2/lib/libpyglib-2.0-python.0.dylib
  Reason: image not found`

I use mac os catalina 10.15.6

**Comment by txe** [comment]
Hmm, I just rebuilt the future version and it was ok, maybe you skipped some steps from readme to build mac version.

If you want to try pygtk version, it's better to use mac os port maintained by @kenku:
`sudo port -v install cherrytree`
And you can ask more about that port in https://github.com/giuspen/cherrytree/issues/176

**Comment by Shizzlebix** [comment]
i cant use port on this mac because it is the mac from work.
you rebuild future version? So i can try to delete the directory and then i fetch it new from git... i will test it in few minutes.

**Comment by Shizzlebix** [comment]
kill the directory and clone the hole again:

cd future && mkdir build && cd build && cmake ../

make

`[ 81%] Built target spdlog
Scanning dependencies of target cherrytree_shared
[ 81%] Building CXX object src/ct/CMakeFiles/cherrytree_shared.dir/ct_actions_edit.cc.o
In file included from /Users/dkovacs/cherrytree/future/src/ct/ct_actions_edit.cc:22:
In file included from /Users/dkovacs/cherrytree/future/src/ct/ct_actions.h:26:
In file included from /Users/dkovacs/cherrytree/future/src/ct/ct_dialogs.h:27:
In file included from /Users/dkovacs/cherrytree/future/src/ct/ct_filesystem.h:26:
/Users/dkovacs/cherrytree/future/src/ct/ct_splittable.h:108:5: error: exception specification of explicitly defaulted move constructor does not match the calculated one
    CtSplittable(CtSplittable&&) noexcept = default;
    ^
/Users/dkovacs/cherrytree/future/src/ct/ct_config.h:103:49: note: in instantiation of template class 'CtSplittable<Glib::ustring, std::__1::vector<Glib::ustring, std::__1::allocator<Glib::ustring> >
      (*)(const Glib::ustring &)>' requested here
    CtStringSplittable                          specialChars{CtConst::SPECIAL_CHARS_DEFAULT};
                                                ^
1 error generated.
make[2]: *** [src/ct/CMakeFiles/cherrytree_shared.dir/ct_actions_edit.cc.o] Error 1
make[1]: *** [src/ct/CMakeFiles/cherrytree_shared.dir/all] Error 2
make: *** [all] Error 2`

**Comment by txe** [comment]
can you show the output of  `gcc --version`

**Comment by Shizzlebix** [comment]
gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.0 (clang-1100.0.33.17)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Comment by msgpeek** [comment]
The compiler errors look like glib respectively python2 is missing.



``i cant use port on this mac``

I suppose that is also affects brew. Could you mention how you installed the dependencies mentioned in [readme](https://github.com/giuspen/cherrytree/tree/master/future#building-cherrytree-on-macos) ?

**Comment by Shizzlebix** [comment]
brew can or may I use

**Comment by txe** [comment]
I had macos a bit outdated, after updating it, the compilation is still fine:
```
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.3 (clang-1103.0.32.62)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
Before and after update I have a bit newer clang `11.0.3` maybe it's a reason?

**Comment by Shizzlebix** [comment]
thank i will try.... i think i need xcode, right?

**Comment by msgpeek** [comment]
I think you just need the command line developer tools (I think I typed git in the terminal and a pop-up appeared to install them - osx noob here).  It's a light version without xcode IDE. The [stackoverflow answer](https://stackoverflow.com/questions/59080773/the-git-command-requires-the-command-line-developer-tools-would-you-like-to-i) mentions it.
From there on I just worked with brew.

 My clang version is 12.0.0 (clang-1200.0.26.2) on fully patched catalina, freshly installed. I am, however, not sure if this helps. This looks like generic linking issue with the paths. If glib is not found, a lot of other stuff should not compile.

**Comment by Shizzlebix** [comment]
i installed Xcode from apple store now clang is also the same as txe has.

....
`Scanning dependencies of target cherrytree_shared
[ 81%] Building CXX object src/ct/CMakeFiles/cherrytree_shared.dir/ct_actions_edit.cc.o
[ 82%] Building CXX object src/ct/CMakeFiles/cherrytree_shared.dir/ct_actions_export.cc.o
[ 82%] Building CXX object src/ct/CMakeFiles/cherrytree_shared.dir/ct_actions_file.cc.o
[ 82%] Building CXX object src/ct/CMakeFiles/cherrytree_shared.dir/ct_actions_find.cc.o
[ 83%] Building CXX object src/ct/CMakeFiles/cherrytree_shared.dir/ct_actions_format.cc.o
[ 83%] Building CXX object src/ct/CMakeFiles/cherrytree_shared.dir/ct_actions_others.cc.o
[ 84%] Building CXX object src/ct/CMakeFiles/cherrytree_shared.dir/ct_actions_import.cc.o
[ 84%] Building CXX object src/ct/CMakeFiles/cherrytree_shared.dir/ct_actions_tree.cc.o`
....
/Users/dkovacs/cherrytree/future/src/ct/ct_splittable.h:43:28: warning: function 'split_items' is not needed and will not be emitted [-Wunneeded-internal-declaration]
std::vector<Glib::ustring> split_items(const Glib::ustring& str) {
                           ^
1 warning generated.
[ 99%] Building CXX object tests/CMakeFiles/run_tests.dir/tests_encoding.cpp.o
[100%] Building CXX object tests/CMakeFiles/run_tests.dir/tests_read_write.cpp.o
[100%] Linking CXX executable run_tests
[100%] Built target run_test
....

i think it seems very nice. Thanks.
