### ISSUE TITLE
Enhancement: scrolling more lines than real end of text

### ISSUE THREAD

**Issue by ynoxia** [giuspen/cherrytree#109]
An enhancement in edit/read node content: enabling the scrolling of node content about an half window size below real end of text, in order to read/edit last lines of node more comfortably at center of window/screen.

Thank you.

**Comment by giuspen** [comment]
Hello, I also would like to be able to achive this feature that I'm using
in http://geany.org/, unfortunately geany achieves this using another
library (Scintilla) that I cannot use at the moment. Hopefully when I'll
switch to GTK3 I'll find a way

**Comment by txe** [comment]
Resolved by #1162 for C++ version, Edit->Preferences->Text and Code-> [] Scroll Beyond Last Line
