### ISSUE TITLE
[0.99.7-1][Linux-KDE] Export as CT document

### ISSUE THREAD

**Issue by ciranus** [giuspen/cherrytree#1095]
Instead of one CT instance stored in one database.ctb file, and navigating a big nodes tree, I now prefer to create one instance for each key subject, and reorganize by moving nodes from/to different instances.

I suppose the easiest method to achieve this is export/import nodes as CT document.
Export as CT document has absolutely no effect.
As I have never used this feature in CT-gtk2, I don't know if it worked or not in older releases.

The workaround is to export/import as html. 
Export as html works fine, but re-importing a html tree needs a lot of hard work to get the same original node with its sub-trees.

Then, '**Export as CT document**' bug to be confirmed.
――――
_cherrytree_0.99.7-1_amd64.deb / linux-kde_

**Comment by giuspen** [comment]
Export as CT document not working is definitely a bug, we'll fix for the next release

**Comment by ciranus** [comment]
In order to be consistent with the "**save**" or "**export**" logic, I now really wonder if CT document should be considered as Export.
Why not simply leaving it as a Sqlite saving option ?
Just for your thinking.....

![](https://user-images.githubusercontent.com/61602511/89777954-f6819780-db0c-11ea-9e0e-317dc47b5843.png)  ![08⁄10⁄201737-1737](https://user-images.githubusercontent.com/61602511/89801252-3312ba80-db30-11ea-9902-6afe57720cc9.png)

**Comment by giuspen** [comment]
the export gives you options to do only the selection, only the current node, only the current node and subnodes or the whole tree
