### ISSUE TITLE
Suggestion: Exclude Nodes From Search

### ISSUE THREAD

**Issue by metal450** [giuspen/cherrytree#1096]
To improve the specificity of search a bit, it would be nice to be able to:

* In the Search in All Nodes dialog, limit the search to only the subtree of the current node
* Mark a node as excluded from search (related to #650 - this would make it easier to use a subtree as ie. "trash" or "archive," without having its contents necessarily clutter your regular search results)

**Comment by Kansai53** [comment]
I also would find very useful to be able to exclude nodes from search.

**Comment by metal450** [comment]
Hopefully it's not insulting to ask, but might a donation push this ahead of the queue? :pray:

**Comment by metal450** [comment]
Amazing. Just saw this commit, did a local build & it works great.  I sent over a little over $30 in btc - hopefully that's fair :)

Related, if you feel compelled while you're digging around in the search code, I think this would be extremely helpful & is likely fairly easy - 
https://github.com/giuspen/cherrytree/issues/513.  It's one of the other search-related things I've been wishing for since moving over to CT a little over a year or so ago :)

**Comment by giuspen** [comment]
Thanks for your donation @metal450 and for testing the change. About merging the searches I will see if I can include in the next release too

**Comment by giuspen** [comment]
this will be in the next version
