### ISSUE TITLE
Ubuntu MATE 14.04: AppIndicator too big

### ISSUE THREAD

**Issue by basicmaster** [giuspen/cherrytree#110]
When I enable the systray icon, it is shown as expected, However when I also enable the "Use AppIndicator for Docking" option, the tray icon is too large and partly not visible:
![Screenshot](http://basicmaster.de/test/cherrytree_appindicator_problem.png)
I tried the current Git version.

**Comment by txe** [comment]
AppIndicator is not used anymore
