### ISSUE TITLE
[0.99.7-1][Linux-KDE] New link behaviour / too long clickable zone 

### ISSUE THREAD

**Issue by ciranus** [giuspen/cherrytree#1100]
I've noticed something new since 0.99.7.1.
If a line contains a link with nothing until the end of the line, not only the link is clickable, but the link until the end of the line.
We then easily open links we don"t want to open.

![08⁄09⁄202052-2052](https://user-images.githubusercontent.com/61602511/89739662-e0c79000-da82-11ea-912b-e7ee8c074e4c.png)

Expected behavior: just the link should be clickable

**Comment by metal450** [comment]
I observe the same issue.

**Comment by txe** [comment]
It should be related to the fix of #1068. Another function is now used to determine link symbol range, possible it has some unpleasant quirks

**Comment by txe** [comment]
Fixed, thanks for the issue!
