### ISSUE TITLE
[0.99.7] Export as XML document option

### ISSUE THREAD

**Issue by ciranus** [giuspen/cherrytree#1101]
There is currently no option to export as XML document.

Referring to [cherrytree ctd (XML) document](https://github.com/giuspen/cherrytree/issues/1097#issuecomment-670927147) comment, it is currently difficult to analyze the internal CT code to understand some potential problems (like copy/paste issues).

Proposal: add "**Export as XML document**" (or **ctd** format ? difference not clear to me) 

Or if I missed something, please inform how to view the internal CT code.

**Comment by giuspen** [comment]
You can already export as cherrytree XML document

**Comment by ciranus** [comment]
Then I don't know how !

![08⁄10⁄201323-1323](https://user-images.githubusercontent.com/61602511/89777954-f6819780-db0c-11ea-9e0e-317dc47b5843.png)

**Comment by giuspen** [comment]
Ok either wait for 0.99.8 or file save as and choose XML unencrypted then open the ctd file with a text editor

**Comment by giuspen** [comment]
Export to cherrytree document was not working in 0.99.7,vI implement it but not created new packages 0.99.8 yet

**Comment by ciranus** [comment]
What is not clear to me is the difference between "**Saving** as" and "**Exporting** as".
But ok, understood.

**Comment by giuspen** [comment]
If you export the whole tree there is no difference at all

**Comment by ciranus** [comment]
It was not clear to me the difference between "**Exporting** as XML" or "**Saving** as XML".
I now think I understand. "Save" is more related to the instance creation phase, with formats CT immediately understand, without any conversion.
As I have what I need even with 0.99.7 for my investigations, I propose to close this #1101, unless you prefer to keep it open.
Many thanks.

**Comment by ciranus** [comment]
To clarify this one which is "closed" (may be too early), does it mean there's no plan to add "Export as xml".
It seems that it would have been useful during a dev/testing phase to better analyze what happen behind in the kitchen.

If we need to see what happen in a text block of 3 lines, exporting a complete instance, and then find out where are these 3 lines is not very convenient.
A small clarification is then welcome to confirm yes/no for "Export as xml"!

**Comment by txe** [comment]
The command "Export To CherryTree Document" allows to save either **selected text** or selected node or all tree in ctd document which is essentially xml document. This new document can be opened by any editor and investigated.

If we added a new command "Export as xml", a user would execute the same steps to create an xml document and to open it to investigate it. So, nothing would be changed for a user, but we would have created a new command and would have to maintained it. I think, it is a bit overkill to satisfy curiosity.  

For developers, a new command is irrelevant because there are better tools like logging, debugging, etc. which allow to see changes in real time.

**Comment by ciranus** [comment]
> The command "Export To CherryTree Document" allows to save either **selected text** 

Then I don't see how / see saving options snaphot above.
Or.... it's not as clear as it should be.

**Comment by txe** [comment]
The first dialog after starting "Export To CherryTree Document" has radiobuttons. The top radiobutton is "Selected Text Only".

**Comment by ciranus** [comment]
Ok, understood with **0.99.8,** although I thought that "Export To CherryTree Document" means sqlite format.
=> [[0.99.7-1][Linux-KDE] Export as CT document #1095](https://github.com/giuspen/cherrytree/issues/1095)
A bit hidden, but now I know it, all is fine !
Thanks.
