### ISSUE TITLE
C++: Infinite Loop While Searching

### ISSUE THREAD

**Issue by metal450** [giuspen/cherrytree#1105]
Using 0.99.7 on Windows, occasionally (rarely) when searching in All Nodes, CT appears to get stuck in something like an infinite loop: CPU core is pegged at 100%, application becomes non-responsive & must be force exited.  I left it for >10min just to be absolutely sure it wasn't actually just taking a long time to search.

**Comment by giuspen** [comment]
if you repeat the exact same search starting from the same node focused, will it go to infinite loop again?

**Comment by metal450** [comment]
Nope, it's not consistently reproducible, unfortunately

**Comment by txe** [comment]
I found one cause of freezing and fixed it, though there are more. If you still have the issue then reopen this one.
