### ISSUE TITLE
C++ Bug: Undo 'Nothing'

### ISSUE THREAD

**Issue by metal450** [giuspen/cherrytree#1109]
I observed an interesting bug in the C++ version on Windows (0.99.7):

1) Launch
2) Ctrl-Z

The view jumps around, and the document shows as modified - even though 'Undo' was the very first action taken after launching the app - i.e. I'd expect there to be nothign to undo.  If you keep using Ctrl+Z repeatedly, the display keeps jumping around, seemingly cycling between 3 different/random locations.

**Comment by mahdi1234** [comment]
I'd say it's similar to what I reported #961 you just found another manifestation hopefully this gets some attention :)

**Comment by metal450** [comment]
There's overlap, but a little different; this is partially about the issue of jumping around when you undo (i.e. #961), but also that it seems to try to undo even when there shouldn't be anything in the undo history yet.

**Comment by giuspen** [comment]
The undo machine will surely be improved, exact sequence to reproduce the issue then will get more attention

**Comment by txe** [comment]
Fixed
