### ISSUE TITLE
Highlight Current Line unreadable with Light Background in Rich Texty

### ISSUE THREAD

**Issue by kharaktur** [giuspen/cherrytree#111]
Highlight current line background color needs changed,  maybe to a light yellow or gray. It is unusable with the light theme. v 0.36.4

**Comment by krisko** [comment]
With this version it's the only "issue" I can point out right now. Should not be hard to change the colour. Looking forward for new features.

**Comment by giuspen** [comment]
I will try to fix this issue soon.
A workaround for the rich text dark current line selected over light
background, go to the preferences, tab “Plain Text and Code” and change the
“Style Scheme” to “Classic” (or another white background scheme) then
restart cherrytree and you’ll see the rich text current line selected is
now light.

**Comment by giuspen** [comment]
Can you try the latest github version? Or if you need a package please let
me know what operative system you are on

**Comment by krisko** [comment]
Hi, the color is OK for the light theme but the dark theme is now not very readable.
It looks like you use same color for both themes. In this case I suggest to set a little darker shade of grey (perhaps #AAAAAA), which would be a compromise, or if you have the option (I haven't look into the code) to set different colors for light and dark theme.
-current color (grey) is ok for light theme
-previous color (light blue) was ok for the dark theme

**Comment by giuspen** [comment]
Hi, actually there are 2 different colors, one for light and another for
dark, but when you change the theme you have to move to another node (and
eventually come back immediately) before it works.  I'll fix this. If you
change node after changing the theme, us the correct highlighted line color
used?

**Comment by krisko** [comment]
I see, yes if I switch to another node the line highlight color has changed. If I use light theme, the highlight is grey and for the dark theme it's blue. 
It work as expected (except switching to another node to apply line highlight color, but this is not a killer bug), and the lines are readable.

Thank you.

**Comment by georgeabr** [comment]
Can we have an option to change line highlight colour?
For dark mode, I'd like to change it from blue to some other colour.

**Comment by avariado** [comment]
Hello, Developer! I understand this issue was never a top priority but it still bothers me a lot... The highlight current line becomes unreadable with rich text, "light background, dark text" colour scheme, and the suggested workaround didn't work with me, probably because I use a black high contrast theme. Could you please add this feature? Thanks!

**Comment by txe** [comment]
It was fixed in the current version.
Instead of changing foreground and background colors, you can change any parameter by changing the theme. Themes can be downloaded, and also can be changed in any editor.
