### ISSUE TITLE
Building cherrytree on windows 7 "autoreconf: command not found"

### ISSUE THREAD

**Issue by Thmyris** [giuspen/cherrytree#1112]
I have the latest version of this repo. I am trying to build on windows 7 by following the readme.md on master. I have followed each line meticulously and got stuck at `./autogen.sh` command. My `MSYS64` has the output:
`./autogen.sh: line 7: autoreconf: command not found`
From a quick google search it looks like I need to install something called "autotools" but I don't know how to install it. 

I tried skipping `./autogen.sh` and ran `./configure --disable-memory-leak-detection` but now I can't 'make' as MSYS64 says 'bash: make: command not found'.

Then, on [MSYS2's github wiki](https://github.com/mangband/mangband/wiki/MSYS2#autotools) it says if we are compiling from a source release I can just 'pacman -S automake autoconf' so I did that. But couldn't continue down this path either.

Any tips?

Also for some weird reason I had to input some commands twice due to bash not being able to recognize pacman as a command.

**Comment by giuspen** [comment]
There is no autogen.sh in current version https://github.com/giuspen/cherrytree what are you building

**Comment by txe** [comment]
I think it's cpputest

**Comment by giuspen** [comment]
Ok I'll try myself from scratch and update the README

**Comment by giuspen** [comment]
I updated the README after going through the whole sequence myself from scratch

**Comment by Thmyris** [comment]
Thanks a lot! The build was successful and I launched 0.99.8 successfully!
