### ISSUE TITLE
PDF Export: no hyperlinks

### ISSUE THREAD

**Issue by Bamoka** [giuspen/cherrytree#1113]
Hello,

When exporting to PDF on Windows, the hyperlinks work but they are not highlighted or underlined.
This makes it somewhat troublesome when we need to export procedures for our clients as some of them have pointed out.

Big thanks to the devs for a great product and thank you for reading.

**Comment by txe** [comment]
Hi, I just tried PDF export on Windows, and I agree hyperlinks are not underlined, I'll fix it.
But are you sure that they are not highlighted because in my case, they are highlighted in blue.

**Comment by txe** [comment]
I added underlining for links

**Comment by Bamoka** [comment]
Thank you so much @txe for fixing this issue.
Works as expected now.

I should probably mention that this bug is still affecting version 0.39.4 but we've uninstalled it in favour of the excellent 0.99.8.

**Comment by txe** [comment]
Great.
0.39 doesn't and won't support links.
