### ISSUE TITLE
Unable to open files Mac - no file associations?

### ISSUE THREAD

**Issue by bulbafett** [giuspen/cherrytree#1114]
I did a clone and built for my mac this evening. Everything was successful and the program runs correctly.

I was able to create a sample document and save it. However I cannot open any files

I tested with .ctd and .ctb non password protected. When attempting to open the file the file dialog shows the files but they are un-selectable and the filetype options just says "Cherrytree documents" 

![image](https://user-images.githubusercontent.com/39497402/90327466-79fe1700-df59-11ea-907e-e5ff45bfe706.png)

**Comment by txe** [comment]
Can you update the source again. it was fixed (#1106) a few hours ago.
