### ISSUE TITLE
"Find in all nodes" returns & highlights wrong results

### ISSUE THREAD

**Issue by kettenfett** [giuspen/cherrytree#1115]
I searched with CTRL+SHIFT+F for "cortana" here, and it highlighted a single random "o" in the text. Also the search results box says it's in a code box, but is isn't. There isn't even any codebox in the whole node. There also isn't any occurance of cortana in that particular node, that it might have missed. It doesn't make this error, when I search in just that node via CTRL+F. Just when using CTRL+SHIFT+F.

![grafik](https://user-images.githubusercontent.com/23098362/90340558-55597c00-dff9-11ea-9506-b8e9cd95bce8.png)

All the other search results were correct. just the last one was wrong.

**Comment by giuspen** [comment]
It helps if you can create a test document where we can reproduce the issue following your instructions

**Comment by kettenfett** [comment]
> 
> 
> It helps if you can create a test document where we can reproduce the issue following your instructions

For safety, I sent it to you via the feedback feature on your website.

**Comment by giuspen** [comment]
@kettenfett what version are you running? Can you try 0.99.8 https://www.giuspen.com/cherrytree/#testing

**Comment by kettenfett** [comment]
it seems to be fixed in 0.99.8

I was using 0.99.6 before.

**Comment by kettenfett** [comment]
Do you create a changelog for the testing versions?

**Comment by giuspen** [comment]
I'm not creating a changelog yet, I will close this you can reopen if happens again
