### ISSUE TITLE
Cherry tree file turned to 0kb

### ISSUE THREAD

**Issue by CyberSecSean** [giuspen/cherrytree#1118]
Hi guys I have been working through my uni course over the last 6 months or so including udemy courses and books etc and using cherry tree to take notes (I eventually want to neaten them up and put into github to help people)

But I went to open my cherry tree today and the file says 0kb

![image](https://user-images.githubusercontent.com/66629319/90345648-6070d400-e01a-11ea-9a0f-329cf638925f.png)

I thought I had a backup but can't find it somehow, the CTD files underneath seem to have something on them when I turn it into an XML file but its mostly gibberish and loads of random code

Is there a way to get my notes back !?

I don't seem to remember deleting anything at all, my 9 year old has been on the computer but I cant see her being able to right click and delete the whole lot for no reason, which leads me to believe a bug!

Thanks!

**Comment by CyberSecSean** [comment]
![image](https://user-images.githubusercontent.com/66629319/90345681-a7f76000-e01a-11ea-9a06-5ca440dda3c2.png)

When I open all I have is this when its meant to have lots of nodes and notes all separated into categories!

**Comment by txe** [comment]
Before you're going to do something, copy files ctd~ and others to somewhere else

**Comment by CyberSecSean** [comment]
Yeah I will cheers, I'm pretty sure the information is on those 3 documents but not sure how to open or extract it back into cherry tree!

**Comment by txe** [comment]
You need to change extension from .ctd~ to .ctd then the file can be opened by cherrytree

**Comment by CyberSecSean** [comment]
It worked, I've lost nothing, must have automatically backed up or something, not sure how the main document contents disappeared, strange bug! Thanks again mate you're a star!

**Comment by txe** [comment]
It looks like you added some new data in notes a few days ago, and cherrytree couldn't convert it into xml during saving. The data could be binary output from some programs?

If you remember what you did on 13/08 and can reproduce it, then we can fix it. Also, I can recommend to switch from xml to sqlite, it is more robust.
