### ISSUE TITLE
Rich Text Preference Pane is Empty

### ISSUE THREAD

**Issue by Hamzantal** [giuspen/cherrytree#1119]
![image](https://user-images.githubusercontent.com/29532600/90363339-bd0cd700-e08c-11ea-83ae-819bba93d794.png)
Hey guys, as you can see here, the preference pane is completely empty for rich text. All the other settings pages are completely fine though.

I'm using the (non bin) version of cherry tree on pacman:
![image](https://user-images.githubusercontent.com/29532600/90363405-e463a400-e08c-11ea-8379-5f5d7b4d623a.png)

**Comment by txe** [comment]
Hmm, maybe it's related to spellcheck when dialog is trying to show info about it, it throws exception? 
Can you start cherrytree from console and open Pref dialog. Probably, some information will be shown in console

**Comment by Hamzantal** [comment]
Hmm, restarting my device seemed to fix the issue. Not sure what caused that issue! I'll go ahead and close this for now and reopen if I find more information to reproduce this mysterious bug :ghost:
