### ISSUE TITLE
Garbled special characters

### ISSUE THREAD

**Issue by Suzakura** [giuspen/cherrytree#1133]
Special characters are garbled.
I changed the font, but the symptom did not improve.
Is there a way to improve it?

CherryTree Ver.0.39.4
Windows10 Home 1909
language：Japanese

![2020-08-22 214416](https://user-images.githubusercontent.com/1965971/90956490-0fe9f280-e4c2-11ea-8da4-3e62c01dc880.png)

**Comment by txe** [comment]
The issue was fixed, the fix will be in  0.99.18
