### ISSUE TITLE
Cherrytree program window on 4K monitor

### ISSUE THREAD

**Issue by Dookster** [giuspen/cherrytree#1134]
Hello,
It looks like the program window and especially the icons are not sharp on a 4K 3840x2160 pixel screen?
Can this be improved please? Or is there some other solution?

Regards
Jan

**Comment by txe** [comment]
What cherrytree version and OS do you use?

**Comment by Dookster** [comment]
Hello,
Cherrytree version 0.39.4 (which is the latest version).
Operating system: 64bit Windows 10 Pro, exact build: 2004.19041.450

Regards
Jan

**Comment by txe** [comment]
I see, version 0.39 is based on old gtk2 which is not going to work good on 4k.
There is 0.99 based on gtk3, it should be better, but it is still under testing, it can be taken from https://www.giuspen.com/cherrytree/#testing

**Comment by Dookster** [comment]
Hello,
Thank you very much! This looks much better now.

Regards
Jan

**Comment by txe** [comment]
Cool!
