### ISSUE TITLE
TOC unexpectedly includes content from indexed pages

### ISSUE THREAD

**Issue by datavectors** [giuspen/cherrytree#1143]
I am migrating from Ubuntu 18.04 to Ubuntu 20.04.
In Ubuntu 20.04 I have two CherryTree versions installed for testing.
0.39.4 and 0.99.9

Now I do not know if this is a recent issue I report since I have just started creating TOC 
in both versions.

I observe that some embedded node content is appearing throughout the TOC where I expect to see only links to nodes (as a list of links).

The content **is not** embedded if the node text is unformatted.
The content **is** embedded where the content (a) has been pasted from a web page into a node (i.e. HTML formatted) or (b) is in a codebox.

Is there some preference I am missing? I cannot remember seeing this embedded content embedded in earlier TOC's I created.

I have read here .. but no mention of content being embedded in TOC links ..
http://giuspen.com/cherrytreemanual/#_table_of_contents

**Comment by ciranus** [comment]
> I observe that some embedded node content is appearing throughout the TOC where I expect to see only links to nodes (as a list of links).

Do you mean for both 0.39.4 and 0.99.9 ?

nb: 0.99.10 is available.

**Comment by txe** [comment]
Hi @datavectors ,
The first line in the given documentation:
> This feature inserts an unordered, hierarchical list containing a link for every node and **header**.

So, text that has styles h1 (Header1), h2 (Header2), h3 (Header3) is added in Table Of Content as well.
Codeboxes shouldn't get into TOC, so if you have a reproducible example and can give it to me, I can fix it.

**Comment by datavectors** [comment]
I now understand that also all internal headers are indexed.
I want a TOC which only contains node titles.
But I have found a way of parsing TOC to get this.
I have not reproduced the dumping of codebox content which I referred to.
I will now close this issue.. Thanks
