### ISSUE TITLE
Scroll Past End on Windows Desktop

### ISSUE THREAD

**Issue by plof27** [giuspen/cherrytree#1147]
Hi!

I've read on some forums that cherrytree has the "scoll past end" functionality on the web version, but I haven't found it on the Windows desktop version. Are there any plans to add this feature in the future?

(Currently on Windows 0.39.4)

**Comment by giuspen** [comment]
If feasible with the library in use (GTK3) yes

**Comment by txe** [comment]
Resolved by #1162 for C++ version, Edit->Preferences->Text and Code-> [] Scroll Beyond Last Line
