### ISSUE TITLE
Select text color foreground / background with Enter key

### ISSUE THREAD

**Issue by tom-i** [giuspen/cherrytree#1152]
Info: in previous version of CherryTree, it was possible to change default color of "Text color foreground / background" by hitting enter key.
It's not possible now. Enter key remove previously selected color and choose black one.

Steps to reproduce:
1. Select some text
2. Choose "Text color foreground" or "Text color background".
3. Hit Enter key.
4. Black color has been choose.

Expected behavior - use previously chosen color and uses it.

Version: 0.99.10

**Comment by giuspen** [comment]
Thanks I'll fix this
