### ISSUE TITLE
systray=true reset to systray=false on next run/exit of cherrytree 0.99.10, Mint 20 Cinnamon.

### ISSUE THREAD

**Issue by Joe1962** [giuspen/cherrytree#1153]
If you configure systray=true either manually on ~/.config/cherrytree/config.conf, or in cherrytree preferences cherrytree will disregard the setting on next run and will then reset it to false on exit. Even tried setting owner of config.conf to root and making it read-only, but that didn't work. It seems to delete it and make a new file each time, according to the timestamp.

Running CherryTree 0.99.10 on Linux Mint 20 Cinnamon, but it was happening at least on the previous package version, maybe even 2 versions back, which is when I upgraded to Mint 20, and hence to cherrytree 0.99.x.

BTW, I very much appreciate this great software and have been using it for years now for my structured notes.

**Comment by funnelfiasco** [comment]
I can't reproduce this on Fedora 32 KDE (cherrytree-future-0.99.10.20200908gitecbaada-1)

**Comment by txe** [comment]
@funnelfiasco, it cannot be reproduced with kde
@Joe1962, it is a known issue, gtk doesn't provide a reliable way to detect if systray exists. In your case, it says there is no systray and thus it is turned off. Maybe I add a one more flag to force the systray option being on.

**Comment by Joe1962** [comment]
"gtk doesn't provide a reliable way to detect if systray exists"
The systray icon used to work on Mint 18.x and cherrytree 0.39x though.

" one more flag to force the systray option being on"
That would be good.

Mint now uses XAppStatusIcon, since GtkStatusIcon was deprecated, might this have something todo with it?

**Comment by ciranus** [comment]
> cherrytree will disregard the setting on next run and will then reset it to false on exit.

**Not** confirmed on ubuntu (0.99.10 / KDE ).
Gnome issue ?

**Comment by Joe1962** [comment]
"gtk doesn't provide a reliable way to detect if systray exists"
The systray icon used to work on Mint 18.x and cherrytree 0.39x though.

" one more flag to force the systray option being on"
That would be good.

Mint now uses XAppStatusIcon, since GtkStatusIcon was deprecated, might this have something todo with it?

**Comment by giuspen** [comment]
I tried on Ubuntu 20.04 running the Cinnamon desktop and cannot reproduce the issue; I'm going to try a Mint Cinnamon 20.04 VM in a moment and will sort it out

**Comment by Joe1962** [comment]
Thanks, giuspen,
BTW, I guess this means you could reproduce the issue on your Mint 20 VM?

**Comment by Joe1962** [comment]
Thanks, giuspen,
BTW, I guess this means you could reproduce the issue on your Mint 20 VM?

**Comment by giuspen** [comment]
@Joe1962 yes I did reproduce, thanks for reporting the issue
