### ISSUE TITLE
Percentage when saving file .ctx or .ctb

### ISSUE THREAD

**Issue by rpierluigi** [giuspen/cherrytree#1155]
I am currently using cherrytree version 0.99.10.
I ask if it is possible to have the percentage when saving the .ctx or .ctb file because it would be useful while waiting to know that the pc is working my files are about 200-300 Mb and to save them it takes between 30 and 50 seconds on 2 tb sata hard disk with the portable version. Thanks again to Giuseppe for the excellent product that I have been using for a long time now.

**Comment by txe** [comment]
I think the long saving is not normal, and I'd prefer to fix the cause instead of adding a progress bar, but I'll need your help. I can add timestamps into the log file which can show what exactly makes the saving slow. And Giuseppe or I will provide a binary to you, so you can run it.
What do you say?

**Comment by rpierluigi** [comment]
Ok

See for yourself which solution is simpler for you

I wait for your choice solution to testing save.



Il Dom 13 Set 2020, 12:38 txe <notifications@github.com> ha scritto:

**Comment by txe** [comment]
Are you using Windows?

**Comment by rpierluigi** [comment]
Windows 10

Il Dom 13 Set 2020, 17:35 txe <notifications@github.com> ha scritto:

**Comment by rpierluigi** [comment]
Hi Giuseppe I think I understand what is due to the slowness of saving the
208 Mb file.
Being a password protected .ctx file I believe it transforms and archives
it with .7z
with password this is why it takes a long time.
If, on the other hand, I save the same archive with the .ctb format, it
writes the file in less than two seconds.
Good day

Il giorno dom 13 set 2020 alle ore 17:43 Pierre Pierre <
rpierluigi65@gmail.com> ha scritto:

**Comment by giuspen** [comment]
Thanks @rpierluigi I'll see if I can find an option for lib7zip to compress faster

**Comment by giuspen** [comment]
Ciao @rpierluigi please try latest version

**Comment by rpierluigi** [comment]
Perfect now in a few second save
This problem is solved Thanks
Now I would like to point out that in the cherrytree search when there are
many occurrences
it remains for five minutes without knowing what it is doing, not seeing
the progress bar and
not having the possibility to stop I attach a screen of the found
occurrences.
Thanks for good program.


Il giorno dom 20 set 2020 alle ore 18:13 Giuseppe Penone <
notifications@github.com> ha scritto:

**Comment by giuspen** [comment]
Please @rpierluigi raise a separate issue about the search and describe in detail
