### ISSUE TITLE
reload_doc_last = false will not take effect

### ISSUE THREAD

**Issue by Peterling007** [giuspen/cherrytree#1159]
cherrytree_0.99.11-1_amd64.deb in Linux Mint 20 (live version with persistent memory)

cherrytree always loads the last used ctb file, even if we deactivated "Preferences - Miscellaneous - Reload Document From Last Session".

In addition: If cherrytree is started from the terminal, the following debug info is being displayed in terminal output if the check box "Reload document from last session" will be changed:
"[2020-09-15 13:31:51.159] [gtk] [critical] gtk_notebook_get_tab_label: assertion 'list != NULL' failed"

**Comment by txe** [comment]
Fixed.
About the debug output, I couldn't reproduce it and as result couldn't fix it
