### ISSUE TITLE
[Feature Request] Hide the path of the cherrytree file on title

### ISSUE THREAD

**Issue by userfav** [giuspen/cherrytree#1170]
First, thanks for this great software, I really love it.

My request is about to add a option to hide the path of the file from the title. So, when you switch between instances (I normally have tree or four instances open all the time) it's more clear to identify on what instance you are and where you want to go. I talk about the instance switching with the Alt+Tab or when you have multiple instances grouped on the Windows taskbar.

(my first thought was about to give a each file a name (like a notebook name) and maybe an distinct cherry tree icon color but now I think it can be a overkill)

Thanks again to Giuspen and all the collaborators.

**Comment by Peterling007** [comment]
I can't really understand your problem.
In Linux Mint, the header of the ct-window shows 3 parts separated by a hyphen:
ct-Book-Name (=Filename)  -  Path to the folder in which the file is located  -  Version of the installed Cherrytree

If you give your ct-Book a **meaningful** file name, this name will appear in the first position of the header. This bookname is also displayed in the Alt-Tab-dialog and the bookname is displayed in the Taskbar.

**Comment by Peterling007** [comment]
I can't really understand your problem.
In Linux Mint, the header of the ct-window shows 3 parts separated by a hyphen:
ct-Book-Name (=Filename)  -  Path to the folder in which the file is located  -  Version of the installed Cherrytree

If you give your ct-Book a **meaningful** file name, this name will appear in the first position of the header. This bookname is also displayed in the Alt-Tab-dialog and the bookname is displayed in the Taskbar.

**Comment by giuspen** [comment]
Since other editors are not showing the path and the request was simple I just added the option

**Comment by ciranus** [comment]
![2020-09-20_16-37](https://user-images.githubusercontent.com/61602511/93713962-b4159680-fb5f-11ea-9bcb-b0fefb4201dd.png)
