### ISSUE TITLE
[0.99.11/Lnx-KDE] Export to HTML > tree_panel_toggle_btn special character

### ISSUE THREAD

**Issue by ciranus** [giuspen/cherrytree#1172]
Export to HTML creates two special toggle button characters not understood in my environment:

![2020-09-23_09-56](https://user-images.githubusercontent.com/61602511/93983631-1b5f6080-fd83-11ea-9024-6a9e761bee4c.png)

What are these characters supposed to be ? 
Some specific arrows requesting a special font not UTF-8 compatible ?

**Comment by txe** [comment]
These characters are `&#129090;` and `&#129088;` You can easily google them to find out more information about them. You can replace them by editing 'script3.js' in cherrytree config folder, lines
```
right_arrow_heavy = '&#129090;'
left_arrow_heavy = '&#129088;'
```
After editing, new export to html will use the changed script3.js.

**Comment by ciranus** [comment]
Ha OK; I now know how to change them, but still don't know why these characters are not interpreted in my UTF-8 environment (tested with Firefox or Falkon browser). May be a missing font ? Which one: I don't know.
Said differently, not sure these characters are optimal as default characters.
Not a problem for me, but surprised to be the only one noticing it.
This issue can be then close, if I am the only concerned.
