### ISSUE TITLE
"Full Screen On/Off   (F11)"  only supports On but not Off.

### ISSUE THREAD

**Issue by Peterling007** [giuspen/cherrytree#1173]
Using: cherrytree_0.99.11-1_amd64.deb in Linux Mint 20 Cinnamon (Live-System with persistence)

1. Open a cherrytree-book

2. Press F11  or  go to Menu-View and click "Full Screen On/Off"
⇒ Now you have nice Fullscreen-Cherrytree 

3. Press F11 again  or  go to Menu-View and click "Full Screen On/Off"
⇒ Nothing happend, you stay in Fullscreen-mode forever ;-)

**Comment by ciranus** [comment]
Problem confirmed in Linux-KDE.

**Comment by giuspen** [comment]
Thanks I'll have a look
