### ISSUE TITLE
Using gnome-terminal 

### ISSUE THREAD

**Issue by 4Syno** [giuspen/cherrytree#1176]
General Information:

Distribution: Ubuntu 20.04 
Desktop Environment: Budgie
CherryTree Package Type: Flatpak
CherryTree Version:  0.39.4

Hi,

I am trying to start using CherryTree. Text file import works quite well :)
But I can’t call apps outside the flatpak sandbox.

Error Details:
/bin/sh: xterm: command not found.
/bin/sh: gnome-terminal: command not found.
/bin/sh: firefox command not found.

All binaries are available on my host. I found this, very helpful: [https://docs.flatpak.org/en/latest/flatpak-command-reference.html#flatpak-spawn](url) and I made the following change:
`sudo flatpak override com.giuspen.cherrytree --talk-name=org.freedesktop.Flatpak`

Now I’m able to get links bypass to my local browser by changing the browser settings with the following: 
`flatpak-spawn --host firefox %s &`

This seems to be the right direction, gnome-terminal is now also available but code execution is still buggy. My shell settings:
```
sh /home/4Bob/Temp<tmp_src_path>
flatpak-spawn --directory=/home/4Bob --host /usr/bin/gnome-terminal -- "<command>"
```
# Error: child process »sh /home/4Bob/Temp/tmp/tmp9DlqRG/exec_code.sh« could not be executed (file or directory not found)

I remove the directory, working only with <tmp_src_path> still no luck; 

```
sh <tmp_src_path>
flatpak-spawn --host /usr/bin/gnome-terminal -- "<command>"
```
btw: <tmp_src_path> where is this location? Here: 
/home/4Bob/.var/app/com.giuspen.cherrytree/cache/tmp ?
I was trying to find the temp folder or the exec_code.sh. There is no such a file. 
Do you provide a kind of verbose mode, by command line? 

I really appreciate any help you can provide.

**Comment by giuspen** [comment]
I think the easiest here is switch to 0.99.x https://www.giuspen.com/cherrytree/#testing that will anyway became the next stable in a week

**Comment by 4Syno** [comment]
This version it works great! Thank you.
