### ISSUE TITLE
Suggestion: Small extension for Option "Expand Node at Mouse Click"

### ISSUE THREAD

**Issue by Peterling007** [giuspen/cherrytree#1177]
As you know: If the Option “Expand Node at Mouse Click” in the Preferences is marked, then two things happens when a Node will be clicked:
   1. the node is selected/gets focus
   2. the node will expand

Suggestion: enhance this Option to “Expand/Collapse Node at Mouse Click”

What should happen if the Option is set: 
- click a not-focused node: same behavior as now - choose and expand
- click the focused node:   collapses the node (same as click on the sign at linebegin)

pros:
- quick inspect of available subnodes, first click shows the subnodes, a second click collapse the node again
- it is not necessary to hit the little sign at linebegin with the mouse

What do you think?

**Comment by giuspen** [comment]
You can wheel click to expand/collapse

**Comment by Peterling007** [comment]
Thanks, wheel click s sufficient, i don't have know this possibility.
