### ISSUE TITLE
[Question] Install on Ubuntu Fossa rpi4

### ISSUE THREAD

**Issue by lesar** [giuspen/cherrytree#1180]
I have an Ubuntu 20.04 64bit and ubuntu-desktop on a rpi 4b 8G
I like tu install cherrytree by ppa but cannot list the package.
It is possible to install?
have I to do something?
Have to wait a merge? (aarch64)

best regards,
Leonardo

**Comment by giuspen** [comment]
I'm going to have a look about how to deploy the aarch64 package, don't I know it yet

**Comment by lesar** [comment]
I do not know if is useful but I found this:  
[gcc-aarch64-linux-gnu](https://ubuntu.pkgs.org/20.04/ubuntu-main-amd64/gcc-aarch64-linux-gnu_9.3.0-1ubuntu2_amd64.deb.html)  

sudo apt-get install -y gcc-aarch64-linux-gnu

**Comment by giuspen** [comment]
I should have found how to enable the arm64 build on the PPA, we'll soon find out when I'm going to issue 0.99.13 later today

**Comment by giuspen** [comment]
0.99.13 is currently in the PPA also built for arm64: https://launchpad.net/~giuspen/+archive/ubuntu/ppa/+files/cherrytree_0.99.13-1_arm64.deb

**Comment by lesar** [comment]
Work wery fine.  
thank you.
