### ISSUE TITLE
Crash on deleting first (and only) node in the 0.99.12 version

### ISSUE THREAD

**Issue by Moini** [giuspen/cherrytree#1181]
Hi!

I'm currently moving from Linux Mint 19.3 to 20, and cherrytree is one of my favourite programs, so I'm very happy to see that a version that will work on the new system is in the making.

I've tested the deb package, and there are two bugs that I found with it:

* in a new install, it complains about a non-existant configuration file: 'no config file' (shouldn't it automatically create one?)
* then, after creating an empty node and deleting it again, the program segfaults.

**Comment by Peterling007** [comment]
Hello Moini

If you start Cherrytree from the terminal and not via the Mint Application menu, some information is displayed in the terminal, e.g. when you change a node or when the configuration file is parsed.

When you save a Cherrytree book for the first time, the configuration file is created automatically and the warning regarding the missing file is never issued again.

Yes, deleting the very last and only node will crash cherrytree. Perhaps that is not brilliant, but I cannot imagine a real situation where this procedure will be necessary.

I'm also switching to Mint 20 and I'm happy with how beautiful and stable the newly developed Cherrytree version behave.

**Comment by giuspen** [comment]
thanks should be fixed now, upcoming release 0.99.13 later today

**Comment by Moini** [comment]
Thank you very much, @giuspen!
