### ISSUE TITLE
Picture editor's ratio zoom function prompt is not obvious

### ISSUE THREAD

**Issue by h007** [giuspen/cherrytree#1183]
## As shown below
<p align="center">
  <img src="https://user-images.githubusercontent.com/9456430/94386389-2434a580-017a-11eb-9bde-7f9177eff9ac.png" width='40%' />
  <img src="https://user-images.githubusercontent.com/9456430/94386399-2ac31d00-017a-11eb-845d-20d4ef8044b5.png " width='50%' />
</p>

![wx_picture_editor](https://user-images.githubusercontent.com/9456430/94386399-2ac31d00-017a-11eb-845d-20d4ef8044b5.png )

![cherrytree_picture_editor](https://user-images.githubusercontent.com/9456430/94386389-2434a580-017a-11eb-9bde-7f9177eff9ac.png)

**Comment by kettenfett** [comment]
I'm not a dev here, but please explain. Do you want the existing function to be more visually prominent? Or do you wish for "+" and "-" Buttons?  Do you want the functionality on hover?

**Comment by h007** [comment]
> I'm not a dev here, but please explain. Do you want the existing function to be more visually prominent? Or do you wish for "+" and "-" Buttons? Do you want the functionality to be available on hover?

@kettenfett just add prompt :support  ratio zoom function

**Comment by crogonint** [comment]
I'd rather have fine grained pixel control than a zoom ratio, myself. I suppose you could add zoom buttons. I was going to suggest 90 degree rotation arrows, instead of the 270 degree arrows. THOSE aren't obvious. Pretty sure there are better arows already in GTK, but don't quote me on that. ;)

**Comment by h007** [comment]
ok
