### ISSUE TITLE
[0.99.13 portable, win64] Cherrytree crashes immediatley when pasting text from outside cherrytree

### ISSUE THREAD

**Issue by kettenfett** [giuspen/cherrytree#1186]
Cherrytree crashes when I copy text from somewhere and paste it. 
It doesn't crash, when copy&pasting within cherrytree.

At first I thought, this only extends to characters, that are related to the markdown auto replace feature so I turned markdown auto replace off in preferences. It still crashes. 
I used a new ctb file to test this.

I did not have this issue with the last version of Cherrytree that i used until today, which is 0.99.6. Since I still have it, I opened the same document in it, and everything works fine with or without markdown auto replace.

**Comment by giuspen** [comment]
Thanks for the report, looking at that shortly
