### ISSUE TITLE
Crash while importing from html

### ISSUE THREAD

**Issue by Hoffenbar** [giuspen/cherrytree#1187]
Trying to import the attached html silently crashes the program.

**Comment by Hoffenbar** [comment]
[startwrap.zip](https://github.com/giuspen/cherrytree/files/5295270/startwrap.zip)

**Comment by giuspen** [comment]
@Hoffenbar was it intentional to close this issue?

**Comment by txe** [comment]
Fixed, thanks
You may find that the import is a bit slow because CT is trying to download images in the html file.
