### ISSUE TITLE
Crash when clicking on dead link in TOC

### ISSUE THREAD

**Issue by mhaeusser** [giuspen/cherrytree#1189]
When I create a table of contents (for the active node only), remove an anchor and then click on the (now dead) link in the toc, CherryTree crashes. Besides, an "update toc" would be helpful.

**Comment by txe** [comment]
Thanks for the issue, fixed.
As for update TOC, there is a future request about it (#989)

**Comment by spasche** [comment]
Could you tell in which release this should be fixed?
I'm using version 0.99.14 on Windows and broken links are crashing the application.
Thanks!

**Comment by txe** [comment]
Thanks for the given test case, it was helpful. The new fix will be in 0.99.15

**Comment by spasche** [comment]
Glad to help, thanks for the quick fix!
