### ISSUE TITLE
PDF Export Image size

### ISSUE THREAD

**Issue by bitboy85** [giuspen/cherrytree#119]
If you have a page with multiple images with different sizes and then export the knot to pdf the images within are resized and have a very bad quality. Maybe a dpi setting?

Version is 0.36.5 Windows portable

**Comment by giuspen** [comment]
If you prepare a cherrytree document with such node I can play with it and
see if I can improve the quality of the resulting pdf

**Comment by bitboy85** [comment]
I've made 2 Screenshots from my PDF Viewer because i think it is more obvious. The first example is made with word. Note that the viewer size is set to 100% (Originalgröße = original size). In comparison the original image i took with the snipping tool. The Image in the Word-PDF has the same size as the original. But the CherryTree Image is upscaled and as a result loosing quality. This might be a result of different border sizes.
![cherrytree](https://cloud.githubusercontent.com/assets/6197580/14043879/992456d8-f289-11e5-840b-1c446622ddaf.png)
![word](https://cloud.githubusercontent.com/assets/6197580/14043882/b0453602-f289-11e5-93ca-ba3405ae0da4.png)

**Comment by kiweegie** [comment]
Hey Giuspen

I've also been seeing this issue but in my case it appears that every image shows blurred in the outputted PDF. HTML format appears unaffected.

I've created a cherry tree file with 3 nodes all with the same image but at different image sizes - the medium one shows the difference between PDF and HTML quite clearly.

PDF export:
![image](https://cloud.githubusercontent.com/assets/2896014/16057577/a276b018-3272-11e6-87a4-831902887c3a.png)


HTML export
![image](https://cloud.githubusercontent.com/assets/2896014/16057587/b1dd046c-3272-11e6-84ce-31c5b45150e6.png)

Even with only the medium image in there the file size is too big to upload here so I've uploaded to my Seafile shares folder from which you can access it here:

For ease of download I've left only the single medium sized image in there.

https://seacloud.cc/f/61c865f619/

Note I tested the link and got a fairly scary warning from Google:

The site ahead contains harmful programs

Attackers on seacloud.cc might attempt to trick you into installing programs that harm your browsing experience (for example, by changing your homepage or showing extra ads on sites that you visit)

I can assure you I'm not uploading anything other than the aforementioned cherrytree file but if you prefer me to get to you via another means I quite understand just let me know.

regards Kiweegie.

**Comment by kiweegie** [comment]
Sorry Giuspen I realise I've already logged this issue a while ago on another ticket:

https://github.com/giuspen/cherrytree/issues/60

Feel free to merge. I was searching the buglist before adding a new ticket for something else and spied this one which I thought I should add to.

**Comment by bitboy85** [comment]
This might be related, but i'm not sure.
I've printed a knot and the Image inside was scaled down a lot, text on the Image was impossible to read.

Note that copy and paste to word for example works fine without any scaling.

**Comment by spiceloss** [comment]
I believe the issue is that the images are being processed by default with bi-linear interpolation? At least that is what I believe is happening:

https://github.com/giuspen/cherrytree/blob/72a93315346d3e653407d82ccf090acd650318ce/modules/printing.py#L185
