### ISSUE TITLE
[0.99.13 Windows] Unreadable (tofu) characters in Search dialog

### ISSUE THREAD

**Issue by piyo-gh** [giuspen/cherrytree#1195]
Version: cherrytree 0.99.13
Exe: cherrytree-test2.exe
OS: Windows 10
Locale: Japanese

Select **Search**->**Find in Nodes Names and Tags**. Opened dialog contains unreadable (tofu) characters.
I tried to change UI language to English and to Japanese, but result was the same.

![cherrytree-test2_2020-09-30_11-30-01](https://user-images.githubusercontent.com/18474085/94637248-08fc9e00-0312-11eb-9a55-92c6ef6aa913.png)

**Comment by txe** [comment]
Thanks! It was fixed by  #1197
