### ISSUE TITLE
"paste"-command in context-menu for images in clipboard is greyed-out

### ISSUE THREAD

**Issue by Peterling007** [giuspen/cherrytree#1196]
1. Take any picture to the clipboard:
e.g. choose in webbrowser the contextmenu of a picture "copy image"
or    save a screenshot directly to the clipboard 

2. Go to an open node of cherrytree
⇒  with CTRL + C you can insert the picture from clickboard (that is fine)

3. On old python-Versions of cherrytree you could insert the picture also by doing:
⇒ right click in the textfield of the node and choose inside the contextmenu: "paste"

On new C++-Version (0.99.13) this is not possible, because the "paste"-command is not active/greyed-out.

**Comment by Peterling007** [comment]
Take any picture to the clipboard:
    e.g. choose in webbrowser the contextmenu of a picture "copy image"
    or save a screenshot directly to the clipboard

    Go to an open node of cherrytree
    ⇒ with CTRL + V you can insert the picture from clickboard (that is fine)

    On old python-Versions of cherrytree you could insert the picture also by doing:
    ⇒ right click in the textfield of the node and choose inside the contextmenu: "paste"

On new C++-Version (0.99.13) this is not possible, because the "paste"-command is not active/greyed-out.

**Comment by Peterling007** [comment]
Number 2 -Correct:
Go to an open node of cherrytree
⇒ with CTRL + **V** you can insert the picture from clickboard (that is fine)

**Comment by txe** [comment]
Fixed
