### ISSUE TITLE
Install manual leads to older version Cherrytree on Linux

### ISSUE THREAD

**Issue by Tillke** [giuspen/cherrytree#1198]
I was following instructions in manual " http://giuspen.com/cherrytreemanual/#_installation "

My OS is Linux/Debian. I did first 3 steps successfully but when i
" wget http://www.giuspen.com/software/cherrytree_0.38.9-0_all.deb " 

i get
HTTP request sent, awaiting response... 404 Not Found
2020-10-01 02:39:20 ERROR 404: Not Found.

Later I later realized there is new version. It works when you change version part to "_0.39.4-0_all.deb"

Could you please update the manual for noobs like me?
Thanks

**Comment by ciranus** [comment]
The stable release is currently 0.**99**.14

As root, or with `sudo` before each command, try this:

```
apt install software-properties-common
add-apt-repository ppa:giuspen/ppa
apt update
apt install cherrytree
apt list --installed cherrytree
```

If not working for any reason,
```
wget https://launchpad.net/~giuspen/+archive/ubuntu/ppa/+files/cherrytree_0.99.14-1_amd64.deb
apt install ./cherrytree_0.99.14-1_amd64.deb
```
