### ISSUE TITLE
Code execution blocks cherrytree

### ISSUE THREAD

**Issue by 4Syno** [giuspen/cherrytree#1201]
General Information:

Distribution: Ubuntu 20.04 
Desktop Environment: Budgie
CherryTree Package Type: deb
CherryTree Version:  0.99.14

Code execution blocks cherrytree; It’s pausing in the background..
Closing the script brings it back to life.
I can't reproduce this with your windows version.
![Auswahl_845](https://user-images.githubusercontent.com/31743671/94860423-57a35880-0436-11eb-9f53-9ee5aecc8626.png)
![Auswahl_846](https://user-images.githubusercontent.com/31743671/94860446-5c680c80-0436-11eb-84ec-17d351f83995.png)

Error Details:
Oct  1 21:54:55 NUC-Desk budgie-panel[5854]: wnck_window_is_skip_pager: assertion 'WNCK_IS_WINDOW (window)' failed
Oct  1 21:54:55 NUC-Desk budgie-panel[5854]: wnck_window_is_skip_tasklist: assertion 'WNCK_IS_WINDOW (window)' failed
Oct  1 21:54:55 NUC-Desk budgie-panel[5854]: wnck_window_get_geometry: assertion 'WNCK_IS_WINDOW (window)' failed

**Comment by ciranus** [comment]
Did you check the terminal preferences settings ?
Is xterm command working ?
`xterm -hold -geometry 180x45 -e "ls ~"`

![tmp](https://user-images.githubusercontent.com/61602511/94913264-3def2900-04a9-11eb-9cab-130e785c34a0.png)

**Comment by 4Syno** [comment]
Hi ciranus,
thanks for your feedback.
terminal preferences settings are almost default: `xterm -hold -geometry 180x45 -e "<command>"`
xterm works and sending commands outside of cherrytree have the same behavior. 
![Auswahl_849](https://user-images.githubusercontent.com/31743671/94921842-5f581100-04b9-11eb-8e6d-ee6d358cd1c7.png)
So I extend the command with ‘&’ on the end and this works for me. If someone else facing this problem here my terminal preferences setting:

`xterm -fa 'Monospace' -fs 12 -hold -geometry 140x35 -e "<command>" &`

**Comment by giuspen** [comment]
Maybe I should add the trailing ampersand as default, what's your opinion @txe ?

**Comment by txe** [comment]
It can be convenient for users to run several scripts simultaneously, I don't see drawbacks here.

**Comment by ciranus** [comment]
No drawback for me either.
Maybe also an opportunity to add `-fa 'Monospace'` to improve the readability of default xterm font.

**Comment by giuspen** [comment]
I'll check how the `-fa 'Monospace'` looks thanks, never used before
