### ISSUE TITLE
Unable to paste images into Cherrytree 0.99.14 (Windows 10)

### ISSUE THREAD

**Issue by mamsiir** [giuspen/cherrytree#1203]
OS: Windows 10
Version: Cherry Tree 0.99.14 from the Windows .exe installer

Hello! When I copy an image from Chrome and try to paste it into Cherrytree 0.99.14 nothing happens. I'm unable to copy/paste images from Firefox and Microsoft Edge into Cherrytree 0.99.14 as well.

I'm able to copy/paste images from the Microsoft Snipping Tool and Photos app into Cherrytree 0.99.14. I can insert images from my files by going to Edit > Insert image but it doesn't work when I try to copy an image from file explorer and paste into Cherrytree.

I'm still able to paste images into Cherrytree 0.39.4 so I'm using that version for now.

Thank you so much for all your hard work into this program. Cherrytree helps me a lot with staying organized!

**Comment by ciranus** [comment]
I don't have windows to test, but did you try from keyboard with "Ctrl+V" ?

**Comment by mamsiir** [comment]
> I don't have windows to test, but did you try from keyboard with "Ctrl+V" ?
> ( [#1196](https://github.com/giuspen/cherrytree/issues/1196) to be then clarified ).

Thank you for your reply!
Yes, I was using "Ctrl+V" for all my tests in my original post. After reading #1196, I checked and I think the "right click > greyed out paste" issue is also still present in Cherrytree 0.99.14 (Windows 10).

**Comment by txe** [comment]
Hi @mamsiir, the fix for #1196 was made yesterday after 0.99.14, so it will get into 0.99.15. But your issue is different, I'll take a look at it.

**Comment by mamsiir** [comment]
> Hi @mamsiir, the fix for #1196 was made yesterday after 0.99.14, so it will get into 0.99.15. But your issue is different, I'll take a look at it.

@txe Oh, I see! Thank you kindly for your hard work, I appreciate it!

**Comment by txe** [comment]
I checked, the fix for #1196 also works for your case, so you need to wait 0.99.15

**Comment by mamsiir** [comment]
Hello! I just downloaded [0.99.15] but I'm still unable to paste some images into CT.

right click > copy image from browser or file explorer > ctrl+v into CT > nothing happens.
right click > copy image from browser or file explorer > right click > paste > nothing happens.

Images are able to paste from:  Print screen, Microsoft snipping tool, Microsoft photos app, CT edit > insert image
Images are unable to paste from: Browsers (Chrome, Firefox, Microsoft Edge), Microsoft file explorer

**Comment by giuspen** [comment]
I found that a folder was missing in the distributed portable and installer causing the download of images from the internet to fail, should be ok in upcoming 0.99.16

**Comment by mamsiir** [comment]
@giuspen Downloaded 0.99.16 from the windows installer and can confirm copy pasting images from internet browsers is fixed! Thank you so much for your hard work and for creating Cherrytree!! 🍒
