### ISSUE TITLE
right-click menu font

### ISSUE THREAD

**Issue by ciranus** [giuspen/cherrytree#1209]
The font size and weight of right-click menu text is related to the text font size and weight, or zoom factor of the editor.

![default-font](https://user-images.githubusercontent.com/61602511/95001508-ec3ebf80-05ca-11eb-9704-1c622f720b3f.png) - ![table](https://user-images.githubusercontent.com/61602511/95001514-f6f95480-05ca-11eb-8e7d-aa8b8f2d5885.png)
![big-font](https://user-images.githubusercontent.com/61602511/95001513-f52f9100-05ca-11eb-98e6-a5b155121bb2.png)

If not wrong, it should be fixed (if I compare with kate text editor for example).
[ I've never seen a zoom effect on menu text of any application ]

.  + suggestion: 'Ctrl+0' should reset the zoom to 0.

**Comment by Peterling007** [comment]
CTRL + 0 is unfortunately occupied with "Toggle Small Property of the selected text"

**Comment by ciranus** [comment]
Ha ok.
'CTRL+0' seems to be the default zoom reset shortcut in KDE.
I don't know in gnome or XFCE.

It's not obvious in CT to identify how to change this setting in the shortcut list.

**Comment by txe** [comment]
from #979

About the issue with the font in the context menu.
It's a bug of the installed system theme and all gtk3 apps are affected by it, e.g. gedit, plume and etc. You can read a bit [here](https://bugs.launchpad.net/ubuntu/+source/pluma/+bug/1823550).

There are three ways to fix it:
- create an issue in kubuntu bugzilla (or that they are using)
- change the current theme
- force the different font for context menu by creating a file `~/.config/gtk-3.0/gtk.css` with
```
.context-menu {
    font-size: 10pt;
    font-family: regular;
}
```

**Comment by ciranus** [comment]
Ok thanks. Solved with ~/.config/gtk-3.0/gtk.css.

I forget here the "_suggestion: 'Ctrl+0' should reset the zoom to 0_" which I should not have mixed with font size.
