### ISSUE TITLE
Keyboard bindings

### ISSUE THREAD

**Issue by krisko** [giuspen/cherrytree#121]
Hello,
is it possible to bind Enter to OK button, and Esc for Cancel (e.g. in code box dialog). Currently I have to use Alt+o key to confirm.

Thank you.

**Comment by giuspen** [comment]
Hi, I thought it is already like this. What dialog(s) you found misbehaving?

**Comment by krisko** [comment]
Well, I tested it in xfce (on gentoo), and it does work! :D
So I guess the bindings are working. I just need more recent OS because it does not work on SuSE 11 with traditional gnome 2 (pretty old), so this might be an old library issue perhaps?

**Comment by krisko** [comment]
Well, I tested it in xfce (on gentoo), and it does work! :D
So I guess the bindings are working. I just need more recent OS because it does not work on SuSE 11 with traditional gnome 2 (pretty old), so this might be an old library issue perhaps?

**Comment by krisko** [comment]
Well, I tested it in xfce (on gentoo), and it does work! :D
So I guess the bindings are working. I just need more recent OS because it does not work on SuSE 11 with traditional gnome 2 (pretty old), so this might be an old library issue perhaps?

**Comment by giuspen** [comment]
Yes definitely it may be an old version issue, please verify that the non working version is old (I would say at least a couple of major versions ago)

**Comment by krisko** [comment]
Yes, it's gnome 2.28.2 from year 2009. So I would say archaic DE.
Anyway thank you for your work, I really love cherrytree, it is the best!

**Comment by krisko** [comment]
Yes, it's gnome 2.28.2 from year 2009. So I would say archaic DE.
Anyway thank you for your work, I really love cherrytree, it is the best!
