### ISSUE TITLE
[0.99.14/Windows 7] Settings from old version are not preserved 

### ISSUE THREAD

**Issue by andezr** [giuspen/cherrytree#1212]
Uninstall 0.39.4.
Settings location: `c:\Users\USERNAME\AppData\Roaming\cherrytree\`
Install 0.99.14
Settings location: `c:\Users\USERNAME\AppData\Local\cherrytree\`

Nothing was preserved.

**Comment by giuspen** [comment]
Thanks for detailed report, the fix will be in upcoming 0.99.15
