### ISSUE TITLE
relative Links files/directory (win 0.99.14)

### ISSUE THREAD

**Issue by LittiGit** [giuspen/cherrytree#1213]
While using the setting "relative links" is is not possible  to create a link to a file or directory.
0.99.14 windows portable and installed version
Without this setting it works well.
It work also in 0.39.4 with relative links set.
Does anyone have the same problem?

**Comment by Peterling007** [comment]
i can confirm the Problem in Linux Mint.

**Comment by giuspen** [comment]
Will be ok in 0.99.15 thanks for reporting
