### ISSUE TITLE
Resizing a CodeBox Does Not Allow Saving the Change

### ISSUE THREAD

**Issue by hb20007** [giuspen/cherrytree#1214]
## Environment

Windows 10, CherryTree v0.99.13

## Steps to reproduce

1. Launch CherryTree.
2. Resize a CodeBox.
3. Press <kbd>Ctrl</kbd> + <kbd>S</kbd>.
4. Exit and relaunch CherryTree.

## Current Behavior

On resizing the CodeBox, there is no asterisk in the top left beside the name of the notebook. Therefore, the change cannot be saved before exiting CherryTree. The only way to save the change is to make another unrelated change in the notebook. This will allow saving, which will save both changes.

## Expectation

Resizing a CodeBox should be treated in the same way as making any other change in the notebook.

## Extra Note

Interestingly enough, if I resize a CodeBox, and then press Undo, this action is considered an unsaved change, and I see the asterisk in the top left.

**Comment by giuspen** [comment]
Could you try 0.99.14?

**Comment by hb20007** [comment]
I apolog
