### ISSUE TITLE
[0.99.14/Windows 7] Crash when clicking Website link in Help/About

### ISSUE THREAD

**Issue by andezr** [giuspen/cherrytree#1215]
Same with existing or empty note.

> Faulting application name: cherrytree.exe, version: 0.99.14.0, time stamp: 0x00000000
> Faulting module name: libgio-2.0-0.dll, version: 2.66.0.0, time stamp: 0x00000000
> Exception code: 0xc0000005
> Fault offset: 0x000000000008253a
> Faulting process id: 0x76c
> Faulting application start time: 0x01d69b0523b96c85
> Faulting application path: C:\Program Files\CherryTree\mingw64\bin\cherrytree.exe
> Faulting module path: C:\Program Files\CherryTree\mingw64\bin\libgio-2.0-0.dll
> Report Id: 68a86b24-06f8-11eb-80db-005056c00008

**Comment by txe** [comment]
Do you have the same issue if you press F1?

**Comment by andezr** [comment]
Yes

> Problem signature:
>   Problem Event Name:	APPCRASH
>   Application Name:	cherrytree.exe
>   Application Version:	0.99.14.0
>   Application Timestamp:	00000000
>   Fault Module Name:	libgio-2.0-0.dll
>   Fault Module Version:	2.66.0.0
>   Fault Module Timestamp:	00000000
>   Exception Code:	c0000005
>   Exception Offset:	000000000008253a
>   OS Version:	6.1.7601.2.1.0.256.48
>   Locale ID:	1045
>   Additional Information 1:	c10f
>   Additional Information 2:	c10fcbdff182301b32195ae0983d34a0
>   Additional Information 3:	0ccf
>   Additional Information 4:	0ccff1521611dd8f780bb6f53f52f3a9

**Comment by giuspen** [comment]
Can you reproduce running from the terminal cherrytree_0.99.14_test.exe extracted from https://www.giuspen.com/software/cherrytree_0.99.14_test.exe.7z placing it beside cherrytree.exe in the extracted portable archive

**Comment by andezr** [comment]
1. Powershell:

> PS C:\Program Files\CherryTree\mingw64\bin> .\cherrytree_0.99.14_test.exe
> ** Message: 06:32:42.983: Language overwrite = en (localedir = C:\Program Files\CherryTree\mingw64\share\locale)
> [2020-10-06 06:32:43.503] [gtk] [critical] Class::register_derived_type(): base_query.type_name is NULL.
> [2020-10-06 06:32:43.513] [   ] [debug] C:\Users\username\AppData\Local\cherrytree\config.cfg parsed


- CT opened
- clicked website in Help/About or F1
- CT crashed

> Problem signature:
>   Problem Event Name:	APPCRASH
>   Application Name:	cherrytree_0.99.14_test.exe
>   Application Version:	0.99.14.0
>   Application Timestamp:	5f7b76a0
>   Fault Module Name:	libgio-2.0-0.dll
>   Fault Module Version:	2.66.0.0
>   Fault Module Timestamp:	00000000
>   Exception Code:	c0000005
>   Exception Offset:	000000000008253a
>   OS Version:	6.1.7601.2.1.0.256.48
>   Locale ID:	1045
>   Additional Information 1:	eb0d
>   Additional Information 2:	eb0dcef02a5746c155839f07d8158fe7
>   Additional Information 3:	90b9
>   Additional Information 4:	90b9865a94c414028f80923c887f04c8

- nothing more in PS

2. GitBash

> /c/Program Files/CherryTree/mingw64/bin$ ./cherrytree_0.99.14_test.exe
> ** (process:2820): WARNING **: 06:38:15.971: locale::facet::_S_create_c_locale name not valid
> ** Message: 06:38:15.991: Language overwrite = en (localedir = C:\Program Files\CherryTree\mingw64\share\locale)
> [2020-10-06 06:38:16.591] [gtk] [critical] Class::register_derived_type(): base_query.type_name is NULL.
> [2020-10-06 06:38:16.591] [   ] [debug] C:\Users\username\AppData\Local\cherrytree\config.cfg parsed

- CT opened
- clicked website in Help/About or F1
- CT crashed
- No windows error, CT just closed
- in GitBash
> Segmentation fault

**Comment by txe** [comment]
@giuspen , there is only `g_app_info_launch_default_for_uri` there, I suppose it crashes inside though it shouldn't. But we can try `ShellExecuteW` instead.

 @andezr, do you use any antivirus program?

**Comment by andezr** [comment]
No AV or any other security program. Windows defender/firewall disabled.

In Safe Mode this problem also occurs.

**Comment by txe** [comment]
I think I could fixed it by using ShellExecuteW to open links.
