### ISSUE TITLE
Linux 0.99.14. Can't do anything with search results window open.

### ISSUE THREAD

**Issue by T-2** [giuspen/cherrytree#1224]
When you search for something in all nodes (via magnifying glass from the toolbar) and the search results window comes up you can click on the one you want and it takes you there but you cannot do anything until the search window is exited or hidden. Nothing works. You cannot edit a note. None of the menu items or icons respond at all. I originally thought it locked up Cherrytree when it first happened.
The older version (0.39.4 on Linux Mint 19.3 MATE) did not do that. I can have the results window up and still do anything I want in Cherrytree. 
Linux Mint 20 MATE all up to date.

**Comment by giuspen** [comment]
thanks, will be OK in 0.99.15

**Comment by T-2** [comment]
This is now fixed for me in 0.99.15. Thanks
