### ISSUE TITLE
[0.99.14/Windows 7] How to disable brackets matching?

### ISSUE THREAD

**Issue by andezr** [giuspen/cherrytree#1227]
How to do this for plain text node, rich text node, codebox?

There is an option `codebox_match_bra=false` in config.cfg but it's not working in codebox.
I thought there may be `pt_match_bra=false` and `rt_match_bra=false` but I don't see such options in  cherrytree/src/ct/ct_config.cc 

I'm asking because its hard to recognize where cursor is, as you want to continue typing something without using "left""right" keys before.

Example
![1](https://user-images.githubusercontent.com/12199354/95323115-ecc2a900-089d-11eb-9fb4-167aebde1fc8.JPG)
![2](https://user-images.githubusercontent.com/12199354/95323117-ed5b3f80-089d-11eb-80bf-452b1029559c.JPG)
![3](https://user-images.githubusercontent.com/12199354/95323119-edf3d600-089d-11eb-8247-21c3f4e176c2.JPG)
![4](https://user-images.githubusercontent.com/12199354/95323120-ee8c6c80-089d-11eb-88a6-94ac4f7f0084.JPG)

**Comment by giuspen** [comment]
Ok you will find it configurable in 0.99.15
