### ISSUE TITLE
Column width = 400 on all tables, navigation in tables no longer works, TAB is inconsistent with spacing

### ISSUE THREAD

**Issue by erik-sk** [giuspen/cherrytree#1228]
Updated to 0.99.14 a few days ago.
When I opened app, all columns in tables reformatted to 400 wide. 
It looks like column width affects all columns which isn't great because
I don't need them to all be the same width. Would be nice to be able to
adjust individually. It seems like column width used to adjust as more text
was typed in, but now it is fixed and line breaks occur making the cell
taller rather than wider.

Navigating columns no long works with either TAB or Arrow Keys. 
TAB used to go to next column cell, now it just tabs within the cell.
DOWN Arrow used to go to next cell, UP used to go to previous cell,
now neither work. Having to click on each cell to move around slows
things down quite bit.

TAB is very inconsistent in spacing. In some areas it acts like a full TAB
based on Tab Width in Preferences. In other areas it may only insert one
space, or three spaces. It varies and is apparently random. Tried setting it in 
preferences by checking the box "Insert spaces instead of Tabs" in the Text and Code
section but the behavior is still variable.

Some other possibly relevant setup info:
Kernel: 5.8.13-2-MANJARO
DE: Xfce 4.14

**Comment by T-2** [comment]
Discovered if you right click anywhere in a table and select Edit Table Properties you can set the with of all columns. Unfortunately every column will have that same width.
The old version would auto adjust the width of every column to the width of the longest item in that column. That would work better for me then the fixed width. Maybe if we had it like in spreadsheets - just grab the separator at the top between columns and adjust it to your liking for each column?

**Comment by crogonint** [comment]
Same behavior in Win7 x64, CherryTree v0.99.15. That's going to seriously limit the use of tables.

I agree with T-2. Revert to 1 inch columns, and let the user adjust the column width by dragging, if nothing else. I think Lotus 1,2,3 used to auto-adjust out to about 3 or 4 inches, and then line wrap. That would be awesome. I don't know why everybody doesn't do that.

**Comment by giuspen** [comment]
Yes an improvement in the column width is necessary, both in the ease of adjusting and in allowing each column to have its own width

**Comment by erik-sk** [comment]
So I just installed the flatpak of version 0.39.4 and everything that I expect to work works. You can set min and max column width so that the columns fit the text in them. Tab works to go from cell to cell in columns as a well as using the up and down arrow keys.  And tab in text is consistently spaced. So it seems like it should be a matter of bringing that stuff back over to the new 0.99 version.

**Comment by giuspen** [comment]
About the tab to move between cells I was thinking it would have been better to use it to insert a real tab character and leave only the arrows to move between cells but I realize probably better to restore as an additional way to switch between cells. About the min/max it cannot be exactly like before but more likely it will just shrink when less text than to cover the maximum width

**Comment by crogonint** [comment]
I'm fine with that tab behavior. I think the clearest thing I've seen with
tabs is that when you're navigating the spreadsheet, tab and shift+tab goes
between cells, but if you're in text edit mode, it adds a tab in to the
text. Now personally, I would never intentionally add a tab in to a
spreadsheet, but it was pretty clever.

I don't see a need for it in CherryTree, but I'm only one person.

..that is so long as the arrow keys WORK. I get terribly annoyed when a
spreadsheet has no method to easily navigate it. I recall one example where
the arrows would indeed move you around the spreadsheet, but then if you
wanted to enter or edit text, you had to reach for the mouse to click the
field.. which made the arrows utterly useless, except for bopping the focus
around the page.

**Comment by giuspen** [comment]
Fixed in upcoming 0.99.19
