### ISSUE TITLE
crash by shift+insert 

### ISSUE THREAD

**Issue by hpta** [giuspen/cherrytree#1229]
I was trying to paste something... I use shift+insert in putty a lot, that's why I pressed it.

0.99.13, windows 10

**Comment by giuspen** [comment]
Please upgrade to 0.99.15 and get back

**Comment by hpta** [comment]
I can paste with both ctrl+v and shift+insert now. Thanks! Closing the issue
btw Help->Check newer version doesn't seem to work. "Failed to Retrieve Latest Version Information..." in status bar

**Comment by giuspen** [comment]
Could be a temporary giuspen.com issue, thanks
