### ISSUE TITLE
Extra blank lines above and below Tree Node items when you turn on "Tree Nodes Names Wrapping Width"

### ISSUE THREAD

**Issue by T-2** [giuspen/cherrytree#1230]
I wanted to wrap the Tree node text like the old version did. So I turned that function on in the Preferences and set it to 20 characters and then rebooted Cherrytree.  The Tree node text wrapped as expected but there is about 5 blank lines above and below each Tree node. Makes for a lot of scrolling the get to the node you want.

**Comment by txe** [comment]
There are related bugs in gtk3

https://bugzilla.gnome.org/show_bug.cgi?id=653108#c10
https://gitlab.gnome.org/GNOME/gtk/-/issues/12

**Comment by crogonint** [comment]
Here's a thought: nerf the Wrapping Node Names, and display the full name in a label on hover (if it's too long).

Come to think of it, When I first used the program, I thought it was a little weird that the Node Names didn't highlight on hover. It wouldn't hurt to highlight both types of links on hover as well. :)

**Comment by T-2** [comment]
I just noticed that hovering now works in Cherrytree so I can see the full node name without having to slide the border over and then back again when done.  Thanks for that.
