### ISSUE TITLE
Segmentation fault on using a To-Do List

### ISSUE THREAD

**Issue by kevindoubleu** [giuspen/cherrytree#1237]
I'm running cherrytree 0.99 on kali linux (Debian 9), Idk what caused this, but you can't use to-do lists or it'll throw a segfault, loading an existing cherrytree file with a todo list just makes the todo list unusable, you can't tick it or untick it.
![segfault](https://user-images.githubusercontent.com/54675998/95726232-db650c80-0ca2-11eb-8127-ce9105e1f87c.gif)
I don't really know where the log files are so here's a recording.

**Comment by txe** [comment]
Hi, can you update to version 0.99.15?

**Comment by kevindoubleu** [comment]
Hello, I just updated to 0.99.15, sadly the issue is still there.

**Comment by txe** [comment]
Hmm, I tried to reproduce the issue but couldn't. Btw, do you have any issue with Number List?

**Comment by ciranus** [comment]
> I'm running cherrytree **0.99** on kali linux (Debian **9**)
![2020-10-13_22-14](https://user-images.githubusercontent.com/61602511/95912165-bd7ed100-0da2-11eb-9b6a-56fe93674390.png) - ![2020-10-13_22-16](https://user-images.githubusercontent.com/61602511/95912172-bf489480-0da2-11eb-8f84-0241450d08e4.png)

Maybe to be reminded that Kali is a very very specific distribution, with '**root**' as user... and issue reported on Debian **9** base. The only linux distribution which considers 'root' as a nominal user.
It's not the first time specific issues are reported with Kali.
If this problem cannot be reproduced in Ubuntu or Debian, is this a CT or Kali issue: that is the question.
And why CT 0.99.**9** ?

**Comment by ciranus** [comment]
Maybe solved with next 0.99.17 ? To be confirmed later.
[protect preferences dialog tab special characters from bad settings](https://github.com/giuspen/cherrytree/commit/e0becb3f42387bee069bac503a3d4bb1b0aed1e3) 
([#1261](https://github.com/giuspen/cherrytree/issues/1261))

**Comment by kevindoubleu** [comment]
Resolved in 0.99.20, thank you.
