### ISSUE TITLE
CtDocXmlStorage got exeption: Document not well formed. Line 55057, column 50 (fatal): internal error: Huge input lookup "

### ISSUE THREAD

**Issue by vitovt** [giuspen/cherrytree#1238]
When I try to open cheery tree file I see error:

CtDocXmlStorage got exeption: Document not well formed. Line 55057, column 50 (fatal): internal error: Huge input lookup "

Database type: xml
I've opened cdt file by editor, remove some lines and file opens. After adding some lines and saving - it stops loading again.

Saving to SqLite fomat (ctb) fixed the issue.
Suppose it is file size limitation of xml parser

Os: Ubuntu 20.04
version: cherrytree_0.99.15-1_amd64.deb

**Comment by txe** [comment]
Hi, you are possible right. Fortunately, there is an option for the xml parser to work with big files, I'll try it later.

**Comment by txe** [comment]
I made a fix but don't have a big enough file to test it. 
The fix will be in the next 0.99.16 version
