### ISSUE TITLE
Faild to export to pdf 

### ISSUE THREAD

**Issue by Abdallah-Fouad-X** [giuspen/cherrytree#1239]
As you can see : 
![image](https://user-images.githubusercontent.com/57077590/95778810-e1ed8700-0c96-11eb-9159-ce53e00d2ce7.png)

every node have sub node, when i tried to export it for pdf cherry tree crashed and the output , bad pdf file can't open it with anything .

here is the output 

[test.pdf](https://github.com/giuspen/cherrytree/files/5366899/test.pdf)

**Comment by giuspen** [comment]
can you share the file whose export to pdf causes systematically the crash privately (my email is in help--about dialog) so that I can reproduce the issue?

**Comment by Abdallah-Fouad-X** [comment]
I sent the file throw mail , waiting for the updated

**Comment by giuspen** [comment]
thanks, will be OK in 0.99.16
