### ISSUE TITLE
Crashing on Start :(

### ISSUE THREAD

**Issue by NouGithub** [giuspen/cherrytree#1241]
**Version, Operative system**
0.39.4

**Describe the bug**
Everything was fine, until this morning.  Running Ubuntu 18.04.5, suddenly when I try to run cherrytree, it hangs... "cherrytree is not responding; force quit or wait."

**Screenshots**
Attached

I have tried using a different file (no change)
I have tried uninstalling CT, reinstalling, etc (no change)
I opened the file on another PC with CT and it opens just fine.

The only thing that allows CT to open properly is to delete the config file, but i need all those customisations and can't lose them.

Please help me?

Thank you.

**Comment by NouGithub** [comment]
I was able to sort it by going into the config file and deleting all lines having to do with recent files....  

What happened here?

**Comment by giuspen** [comment]
Please upgrade to 0.99.15
