### ISSUE TITLE
[SOLVED] option to keep scrollbar always visible

### ISSUE THREAD

**Issue by omega3** [giuspen/cherrytree#1244]
Operating System: Manjaro Linux
KDE Plasma Version: 5.19.5
KDE Frameworks Version: 5.74.0
Qt Version: 5.15.1
Kernel Version: 5.4.67-1-MANJARO
OS Type: 64-bit

Please, add option so that scrollbar doesn't hide automatically. It is a terrible feature to me. I prefer to have it always visible. I don't use gnome, so I don't know if it is a permanent feature of gtk3 applications (or gnome) or cherrytree design, but it is a usability issue for me. When note is long and scrollbar is always visible I always do one mouse move to hit scrollbar. If it is not visible I need to move mouse to the screen edge and only after that I see where scrollbar is and need to do second mouse move to hit it.

**Comment by Maxtor1x2** [comment]
Have you tried launching CherryTree like this:
GTK_OVERLAY_SCROLLING=0 cherrytree

**Comment by omega3** [comment]
It works. Thank you. It is enough for me to regarded it as solved.
