### ISSUE TITLE
[0.99.15] Special Characters for bulleted list and TOC still garbled.

### ISSUE THREAD

**Issue by kettenfett** [giuspen/cherrytree#1245]
As of 0.99.15, Special Characters still look garbled. #1133 

I have set **Arial** in Preferences as Rich text font and plain text font.
Also in Preferences under Special Characters I set "•▸•▸•▸" as chars for bulleted list and "▸•◇▪" for TOC.
Then restarted cherrytree  and made a new document.

Result is:
![grafik](https://user-images.githubusercontent.com/23098362/95968295-90b3d380-0e0d-11eb-8a44-f21036e28cf7.png)

Sooo, how is this fallback font thingy coming along?

**Comment by ciranus** [comment]
Which OS ???

**Comment by ciranus** [comment]
Can you confirm with 0.99.**17** ?

> fix visualisation glitches of nodes with anchored widgets (#1205 )

https://www.giuspen.com/cherrytree/#downl

**Comment by kettenfett** [comment]
> 
> 
> Which OS ???
Windows 10 x64




> 
> 
> Can you confirm with 0.99.**17** ?
I tried. It's still the same. Upon extracting the portable archive, rich text font was reset to Cambria Normal, with which chars work. But not any other fonts I tested.

**Comment by txe** [comment]
The issue was fixed, the fix will be in 0.99.18
