### ISSUE TITLE
Timestamp hot key is not working - Ctrl + Alt +M

### ISSUE THREAD

**Issue by jamesraymondroberts** [giuspen/cherrytree#1248]
**Version, Operative system**
This is for CherryTree version 0.99.14 on Windows 10, and on Debian Buster.

**Describe the bug**
I am no longer able to insert a timestamp with Ctrl + Alt + M

**To Reproduce**
If applicable, attach a non-personal document where the issue can be reproduced systematically.

**Screenshots**

**Comment by giuspen** [comment]
It is working fine on my Ubuntu 20.04, I'll test later on Windows 10, in the meantime please try 0.99.15 and report how it goes there. Also are you using the default keyboard shortcuts or have custom ones?

**Comment by jamesraymondroberts** [comment]
The issue was with me. I was running apps on multiple devices that were interfering. I believe it was AutoHot-Key on the Win 10 machine. I would consider this resolved.
