### ISSUE TITLE
Can't select the Custom Background radio button

### ISSUE THREAD

**Issue by FraggleR0ck** [giuspen/cherrytree#1252]
Under Preferences/RichText/Theme I can choose between Light/Dark, but not able to select Custom Background radio button to customize colors.  I can select the Custom Background under Tree 1 however. Any ideas? I migrated this file from another machine which had no issues like this. Currently on version 0.99.9~git20200901-0kali1

Thanks in advance!

**Comment by giuspen** [comment]
Please upgrade to 0.99.15

**Comment by ciranus** [comment]
> 0.99.9~git20200901-0**kali**1 [ from experimental to rolling ]
> Under Preferences/RichText/Theme

You probably mean Preferences/Theme.

And again and again: Kali.
https://pkg.kali.org/pkg/cherrytree

Kali users should maybe wonder why "Sophie Brun" (uploader) needs to make a so specific and not updated experimental 0.99.**9** Cherrytree package, and why Kali issues are not reproduced with Debian.
Is "Sophie Brun" really testing her builds and investigate just a little bit (wrong gtk lib version dependencies ?)
Kali should definitively not be used as a daily environment, with a so huge security hole: '**root**' administrator who is the default user (so amazing for a distribution supposed to test .... "security").

**Comment by FraggleR0ck** [comment]
It isn't used a daily environment, I have notes like anyone else. Secondly root isn't the default user any longer. That has been changed many moons ago. The file was generated from the same version on which it is currently broken. Which is why I asking for assistance.

> > 0.99.9~git20200901-0**kali**1 [ from experimental to rolling ]
> > Under Preferences/RichText/Theme
> 
> You probably mean Preferences/Theme.
> ![2020-10-16_12-34](https://user-images.githubusercontent.com/61602511/96248571-09509680-0fac-11eb-967e-4fb2082ef69d.png)
> 
> And again and again: Kali.
> https://pkg.kali.org/pkg/cherrytree
> 
> Kali users should maybe wonder why "Sophie Brun" (uploader) needs to make a so specific and not updated experimental 0.99.**9** Cherrytree package, and why Kali issues are not reproduced with Debian.
> Is "Sophie Brun" really testing her builds and investigate just a little bit (wrong gtk lib version dependencies ?)
> Kali should definitively not be used as a daily environment, with a so huge security hole: '**root**' administrator who is the default user (so amazing for a distribution supposed to test .... "security").

It isn't used a daily environment, I have notes like anyone else. Secondly root isn't the default user any longer. That has been changed many moons ago. The file was generated from the same version on which it is currently broken. Which is why I asking for assistance.

**Comment by ciranus** [comment]
Do you confirm 0.99.15 is now working fine ? (I understood Kali was based on Debian 9).
If yes, this is the source I use for Debian:
`deb http://ppa.launchpad.net/giuspen/ppa/ubuntu focal main`

from https://launchpad.net/~giuspen/+archive/ubuntu/ppa

**Comment by giuspen** [comment]
Please do raise an issue only after trying the latest version
