### ISSUE TITLE
[0.99.15] Division line state between RichText and Tree is not saved & many old bugs resurfaced

### ISSUE THREAD

**Issue by gregorik** [giuspen/cherrytree#1253]
In 0.99.15 Windows, the division line between the Tree and the main text body is no longer respecting changes as it did in previous versions. It always snaps back to an awkward default. I need to readjust each and every time upon startup.

**Comment by gregorik** [comment]
Also, auto-copy as _plain text_ into body is totally gone, including the option for it.

**Comment by giuspen** [comment]
I'll have a look thanks

**Comment by giuspen** [comment]
the separator between tree and text is saved and restored properly for me, are your other settings such as window size and position being saved and restored?

**Comment by giuspen** [comment]
can you tell me more about this "auto copy as plain text into body" that was there in 0.39.4 but is no longer in 0.99.15?

**Comment by gregorik** [comment]
> can you tell me more about this "auto copy as plain text into body" that was there in 0.39.4 but is no longer in 0.99.15?

Sorry if it seemed vague: so in 0.39.4 when I copied any text from the clipboard, it was pasted in CT as plain text, if I'm not mistaken. (Pasting in plain text was part of my daily workflow.) In 0.99.15 clipboard text is pasted in automatically as _rich text_, and there's no option in Preferences to switch to _plain text_.

**Comment by gregorik** [comment]
> the separator between tree and text is saved and restored properly for me

Everything else is saved properly on my end. So I suppose it must be a local issue on my rig. Thanks very much for investigating!

**Comment by giuspen** [comment]
You can use Ctrl+Shift+V instead of Ctrl+V to paste as plain text or there is a right click menu item as well. About the separator between tree and text it is weird, maybe if you can produce screenshots I can understand better

**Comment by gregorik** [comment]
I always used the Tree on the right side (been using CT for years), the one below used to be an old bug that now seemed to resurface with GTK3:

<img width="1490" alt="cherrytree_WkkRMYrDjJ" src="https://user-images.githubusercontent.com/10176613/96360283-12f90c00-111c-11eb-8d63-943d3b10c145.png">

**Comment by giuspen** [comment]
I tried also with the tree on the right but cannot see the issue. Is anybody else experiencing this?

**Comment by gregorik** [comment]
So I should conclude that this is a local GUI issue due to my setup...

**Comment by gregorik** [comment]
> You can use Ctrl+Shift+V instead of Ctrl+V to paste as plain text or there is a right click menu item as well

I see, but wasn't there an option in 0.39 to automatically copy as plain text though?

**Comment by giuspen** [comment]
There was a request to make the copy as plain text the default [Ctrl+C] and [Ctrl+Shift+C] the full copy supporting rich text but I have never implemented it. If you find the option in 0.39.x which is missing in 0.99.x please tell me where it is

**Comment by gregorik** [comment]
I have no idea, it just worked.

**Comment by giuspen** [comment]
So if it is working for you now are you happy to close the issue?

**Comment by gregorik** [comment]
What I meant is that it _just worked_ in 0.39, and none of this stuff is working in 0.99. Perhaps due to GTK3, perhaps whatever else. 

I can resort to Ctrl+Shift+V but it's a workaround, not a solution.
Same with the separator line bug, it's still there.
I can still close this if you regard these issues unworkable.

**Comment by giuspen** [comment]
You have to explain better the "just worked", you say that it was possible to swap Ctrl+C and Ctrl+Shift+C describe me how you did it because I do not remember it was possible

**Comment by ciranus** [comment]
> so in 0.39.4 when I copied any text from the clipboard, it was pasted in CT as plain text

You can edit the shortcut:
![2020-10-22_10-35](https://user-images.githubusercontent.com/61602511/96846706-8b303c00-1452-11eb-8393-e12b57d0b3e6.png)
