### ISSUE TITLE
"Insert Today’s Node" function and language

### ISSUE THREAD

**Issue by gil390** [giuspen/cherrytree#1258]
Hi,

I am french and i use cherrytree v0.99.15 on Win10 (19041.572).

My computer and cherrytree are configured for french language.
Since rewritten versions, inserted nodes with "Insert Today’s Node" function are not inserted in french language but english one.

any idea ?

Thank you
Gil

**Comment by giuspen** [comment]
thanks, should be OK in upcoming 0.99.16

**Comment by gil390** [comment]
Yes it is.
Thank you again for your work.

Gil
