### ISSUE TITLE
[BUG] Paste not working on macOS

### ISSUE THREAD

**Issue by NSTikhomirov** [giuspen/cherrytree#1259]
**Version, Operative system**
- commit 97e93e890cf1815671ae58e5c63114a5bc218c0c
- macOS Catalina 10.15.7 (19H2)
- MacBook Pro (15-inch, 2019)

**Describe the bug**
Can't paste from clipboard when copying from another node. When pasting, an error occurs: `[error]? No clipboard rich text`. At the same time, the insert works from other applications. 
**Clipboard content**:
`CTD_RICH` => 
```
<?xml version="1.0" encoding="UTF-8"?>
<root><slot><rich_text>asdqwe</rich_text></slot></root>
```
`public.utf8-plain-key` =>
```
asdqwe
```
`text/html` =>
```
<!doctype html><html>
    <head>
      <meta http-equiv="content-type" content="text/html; charset=utf-8">
      <title></title>
      <meta name="generator" content="CherryTree">
      <link rel="stylesheet" href="res/styles3.css" type="text/css" />
    </head>
    <body>
    asdqwe</body></html>
```

**To Reproduce**
1. Create two nodes: `test`, `test2`
2. Write any text into `test` node
3. Copy text from `test` node
4. Try to paste text into `test2` node
5. Paste failed with error `[error] ? no clipboard rich text`

**Screenshots**
![image](https://user-images.githubusercontent.com/22717966/96367484-c54dc500-1156-11eb-8079-563af68b3313.png)

**Comment by txe** [comment]
Fixed
