### ISSUE TITLE
Crash when introducing (') character in rich text

### ISSUE THREAD

**Issue by miguel090** [giuspen/cherrytree#1261]
Version 0.99.15 Ubuntu 20.10
Installed via apt

The cherrytree app closes without saving, everytime i introduce (') character

Possible useful info:
Portuguese Keyboard layout
save mode is SQLite not proteced

**Comment by giuspen** [comment]
there is no PPA for 20.10 yet, I guess you installed the 20.04 package. I'll have a look and add 20.10 to the ppa shortly

**Comment by ciranus** [comment]
For info, I don't see any problem with 0.99.15 in groovy (20.10) I am currently running.

Useful commands to check the keyboard :
```
$ xev
state 0x10, keycode 13 (keysym 0x27, apostrophe)
```

```
$ xmodmap -pk | grep '0x0027'
13  0x0027 (apostrophe)  0x0034 (4)  0x0027 (apostrophe)  0x007b (braceleft)  0x0024 (dollar) 0x007b (braceleft)
```

**Comment by miguel090** [comment]
Ran the commands and have slighly different output, dont't know if it is to be expected.
```
$ xev
state 0x10, keycode 20 (keysym 0x27, apostrophe)
```
```
$ xmodmap -pk | grep '0x0027'
20   	0x0027 (apostrophe)	0x003f (question)	0x002d (minus)	0x005f (underscore)	0x005c (backslash)	0x00bf (questiondown)
48   	0x00ba (masculine)	0x00aa (ordfeminine)	0x0027 (apostrophe)	0x0022 (quotedbl)	0xfe52 (dead_circumflex)	0xfe5a (dead_caron)

**Comment by ciranus** [comment]
Can you check different combinations with these settings ?

![2020-10-19_01-18](https://user-images.githubusercontent.com/61602511/96388451-2605ed80-11a9-11eb-912c-eba7aa374858.png)

**Comment by miguel090** [comment]
crashes

![image](https://user-images.githubusercontent.com/36671818/96475481-f9df8080-122b-11eb-946b-f2ce792d57e4.png)
![image](https://user-images.githubusercontent.com/36671818/96475344-d3b9e080-122b-11eb-869a-c51d72e6ae26.png)

no crash

![image](https://user-images.githubusercontent.com/36671818/96475505-01068e80-122c-11eb-9836-a4b59a14d1a3.png)
![image](https://user-images.githubusercontent.com/36671818/96475512-02d05200-122c-11eb-820c-9586a2961bd1.png)



That's the problem i changed the default smart quotes to the normal ones (could've just disabled the feature didn't know). And it crashes when i put a single quote. I disabled the feature and the problem is solved.
I think the program, should handle what i did, or say an error telling me that i shouldn't do that. So i'm reopening the issue.
Thanks for the help @ciranus

**Comment by miguel090** [comment]
I wanted to know what the error was so i tried to execute it from the terminal. Now i can't replicate the error that i had with the settings as represented above.
The only error that i consistently get is a segmentation fault
![image](https://user-images.githubusercontent.com/36671818/96493763-4aaba500-123d-11eb-8b74-237642da806e.png)
This happens when i put an irrational thing in the "chars for smart single quotes", such as
![image](https://user-images.githubusercontent.com/36671818/96493946-91010400-123d-11eb-8aed-aea1ba245119.png)
or
![image](https://user-images.githubusercontent.com/36671818/96493975-9bbb9900-123d-11eb-89f5-9e4541a48194.png)
or a single anything

**Comment by ciranus** [comment]
Do you have any specific fonts in use ? Just to see:

```
grep font ~/.config/gtk-3.0/gtk.css
grep font ~/.config/cherrytree/config.cfg
```

For info, I disable the quote auto-replacement in my settings, but no crash at all even if enabled.

+ can you test with CT 0.99.16 to confirm your segmentation fault ?
https://www.giuspen.com/cherrytree/#downl
(it should not change anything according to changelog, but who knows....

**Comment by miguel090** [comment]
First command you gave i don't have that file.
Second command
![image](https://user-images.githubusercontent.com/36671818/96624719-0683d780-1305-11eb-99c6-4e74476515f2.png)
I still get the crash in 0.99.16
![image](https://user-images.githubusercontent.com/36671818/96624976-74300380-1305-11eb-87b3-40305d1c5241.png)
![image](https://user-images.githubusercontent.com/36671818/96625031-8742d380-1305-11eb-9de6-693ce1a73156.png)

**Comment by ciranus** [comment]
I don't think this is related to Ubuntu 20.10. Never seen any specific issues with 'Groovy/20.10'.
I suppose what could help to clarify is that you confirm you can also reproduce this seg fault in Ubuntu 20.04.
That's all I can do for investigation.

**Comment by miguel090** [comment]
I was able to reproduce the crash in a vm with ubuntu 20.04 with the same settings previously mentioned. It generated a crash report that was supposedly sent to the developer.

**Comment by giuspen** [comment]
I'm going to enforce the minimum number of characters in those entries thanks
