### ISSUE TITLE
Unwanted Character Markup w/Rich & Plain Text

### ISSUE THREAD

**Issue by JpYarn** [giuspen/cherrytree#1262]
**Version, Operative system**
Windows 10 (Cherry Tree 0.99.16 - Portable)

**Describe the bug**
Created rich text parent node and then created a child node that I selected to use Automatic Language Markup as Python. The Python child node shows all the "space" & "tab" markups but now when I switch back to the rich text nodes it also shows the markup characters.  There is no option to disable the markup on normal text documents and the only way to make it disappear is to close the application and reopen. When it reloads the markup is gone but if you change focus to the python node it reappears and remains when focus shifts back to the rich text node.

**To Reproduce**
If applicable, attach a non-personal document where the issue can be reproduced systematically.
1. Create Rich Text parent node and add several lines of text utilizing spaces and tabs.
2. Create Child Node and select Automatic Syntax Highlighting - python and add several lines of text utilizing spaces and tabs.
3. Change focus back to parent node and observe that the tab & spacing markup still remains from python node.
4. Close & Relaunch application and observe that parent node does not have the markup.
5. Change focus to python node and then back to parent node and see that markup is now back and remains.

**Screenshots**
![Parent_No-Markup](https://user-images.githubusercontent.com/63548465/96469439-3646b880-11fb-11eb-9e20-95620ae2dd52.png)
![Python_Markup](https://user-images.githubusercontent.com/63548465/96469455-3a72d600-11fb-11eb-8891-47f94a9039be.png)
![Parent_Markup](https://user-images.githubusercontent.com/63548465/96469463-3d6dc680-11fb-11eb-94fe-e0e1db486f21.png)

**Comment by giuspen** [comment]
in the preferences dialog, tab plain text and code, untick show white spaces then restart cherrytree (it's currently not changing straight away so you need to restart but I'm going to fix this)

**Comment by JpYarn** [comment]
Thanks for the assist, is the "Show White Spaces" tick box on the Rich Text tab just non-functional then. It was already unchecked for Rich Text but it appears the Plain Text and Code tick box was over-riding it.

**Comment by giuspen** [comment]
It is functional in 0.99.16 but after you toggle exit cherrytree then start it again. Exit completely, no system tray or other windows opened
