### ISSUE TITLE
Monospace and bold

### ISSUE THREAD

**Issue by Hoffenbar** [giuspen/cherrytree#1264]
**v099.16 in Windows**

It's not possible (anymore) to give a text monospace- and bold-attribut _together_.

**To Reproduce**

**Comment by Hoffenbar** [comment]
In v0.39.4, the combi of mono+bold was possible!

**Comment by giuspen** [comment]
That is because monospace comes with its own selectable font in 0.99.x can't you select a bold font for the monospace in preferences/fonts

**Comment by ciranus** [comment]
Selecting a monospace bold font for code has not effect, due to default code font css [to be confirmed for windows].
I found a solution, at least which works for me: 
-> disable code css font-weight in file `/usr/share/cherrytree/data/styles3.css` (for linux)

![2020-10-24_10-15](https://user-images.githubusercontent.com/61602511/97076626-feb48380-15e1-11eb-9d1d-3a65d279546a.png)
![2020-10-24_10-19](https://user-images.githubusercontent.com/61602511/97077251-6539a180-15e2-11eb-99a9-cf9bec03c984.png)

![2020-10-24_10-20](https://user-images.githubusercontent.com/61602511/97077262-81d5d980-15e2-11eb-87c3-50dc9939ac98.png)

Is `font-weight: normal;` really necessary ? I don't know.

**Comment by txe** [comment]
Hi everyone, 
I got feeling you all talk about totally different things))

@Hoffenbar, do you mean 'Toggle Bold Property' and 'Toggle Monospace Property' don't work together?
@giuspen, I just tried to select 'Monospace Bold' font for monospace in Pref dlg on Win and Linux, and monospace text looks bold, though I might be mistaken.
@ciranus , ok, thanks

**Comment by ciranus** [comment]
New test with 0.99.**17**.
And now selecting "Monospace Bold" as monospace font has effect on all default Monospace text,  even with `font-weight: normal;` in style3.css.
Don't know what has changed, but different conclusion compared to 3 days ago.

**Comment by Hoffenbar** [comment]
A text can not be formatted as mono+bold. -- Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 26.10.20, 23:30 schrieb txe <notifications@github.com>:

   
  Hi everyone, I got feeling you all talk about totally different things)) 
  @Hoffenbar, do you mean 'Toggle Bold Property' and 'Toggle Monospace Property' don't work together? @giuspen, I just tried to select 'Monospace Bold' font for monospace in Pref dlg on Win and Linux, and monospace text looks bold, though I might be mistaken. @ciranus , ok, thanks

**Comment by txe** [comment]
@Hoffenbar, I made some research, you are kind of right.

I think that `Monospace` font used by default doesn't have bold property and thus doesn't change its style. 
But you chose different "mono" font like `Noto Mono Normal` then bold property can be applied.
So it is not cherrytree bug, it is how fonts work now.

@giuspen , when I tried zoom by mouse, monospace text didn't change its size while rich text was changed as should. It's a bug or a feature?)

**Comment by giuspen** [comment]
@txe I think it's a bug we should zoom automatically also the monospace font, good that you spotted it!

**Comment by giuspen** [comment]
Maybe we could zoom it only if the cursor is on monospace text

**Comment by txe** [comment]
I don't think someone could figure out how to zoom monospace text then. Just zooming all text should work just fine.

**Comment by giuspen** [comment]
Ok

**Comment by Hoffenbar** [comment]
Hello,there should be no difference between monospace and proportional fonts regarding scalibility, I think. We aren't talking about bitmap fonts or do we?-- Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 27.10.20, 22:51 schrieb txe <notifications@github.com>:

   
  I don't think someone could figure out how to zoom monospace text then. Zooming all text should work just fine.

**Comment by Hoffenbar** [comment]
I used the consolas font which of course has a normal and a bold variant... -- Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 27.10.20, 22:20 schrieb txe <notifications@github.com>:

   
  @Hoffenbar, I made some research, you are kind of right. 
  I think that Monospace font used by default doesn't have bold property and thus doesn't change its style. But you chose different "mono" font like Noto Mono Normal then bold property can be applied. So it is not cherrytree bug, it is how fonts work now. 
  @giuspen , when I tried zoom by mouse, monospace text didn't change its size while rich text was changed as should. It's a bug or a feature?)

**Comment by txe** [comment]
I tried consolas font right now, the bold property worked although it was not much noticeable (I used 20pt font and changed one word in the middle of monospace sentence, 0.99.17 version)

**Comment by giuspen** [comment]
We could make it configurable whether to use a custom font for the monospace, with it disabled then it would work like before where monospace is just a tag so the bold and other tags would work

**Comment by txe** [comment]
I fixed zooming monospace text.
@Hoffenbar , is there anything else what should be done with this issue?

**Comment by Hoffenbar** [comment]
No, as far as i know. Thanks!-- Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 29.10.20, 21:10 schrieb txe <notifications@github.com>:

   
  I fixed zooming monospace text. @Hoffenbar , is there anything else what should be done with this issue?

**Comment by txe** [comment]
Ok, thanks!
