### ISSUE TITLE
Content missing in PDF export

### ISSUE THREAD

**Issue by Hoffenbar** [giuspen/cherrytree#1265]
**v099.16, Windows**

Intented paragraphs do not appear in the output at all!

Big symbols for anchors appear, which didn't look right.

Names of included files. shown in the original page, do not appear in the pdf.

See attached database. Try to mark the only node an export to pdf.
[Anleitungen--Tools--Eigene--startwrap.zip](https://github.com/giuspen/cherrytree/files/5404584/Anleitungen--Tools--Eigene--startwrap.zip)

**Comment by Hoffenbar** [comment]
After opening the page in v0.39.4, the re-opening and re-exporting the page to pdf in v0.99.16,  the intended paragraphs appear in the output, but simply because v.0.39.4 remove the intendation. In other words: the formats are not 100% interchangeable. Something is lost here and then.

**Comment by txe** [comment]
Hi @Hoffenbar, thanks for the document, it was helpful. The fix will be in 0.99.18.
I attached a generated pdf [startwrap.pdf](https://github.com/giuspen/cherrytree/files/5441815/startwrap.pdf), so you can say if the results are still no ok, then I can try to fix them before the next release

**Comment by Hoffenbar** [comment]
Hello,thank you! The output looks good, only the justification of the paragraphs look different (ragged left).-- Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 26.10.20, 23:10 schrieb txe <notifications@github.com>:

   
  Hi @Hoffenbar, thanks for the document, it was helpful. The fix will be in 0.99.18. I attached a generated pdf startwrap.pdf, so you can say if the results are still no ok, then I can try to fix them before the next release
