### ISSUE TITLE
Table Of contents error

### ISSUE THREAD

**Issue by Hoffenbar** [giuspen/cherrytree#1266]
**v099.16, Windows**

Inserting a table of contents for the first time works (only a few ugly characters at the beginning, probably because I've configured a different font.... will report on this separately).
Now deleting the toc.
Then inserting the toc again, what leads to mangeled content. See attached image for an example of how it looks after applying the above mentioned steps against the attached node.
[Anleitungen--Tools--Eigene--startwrap.zip](https://github.com/giuspen/cherrytree/files/5404626/Anleitungen--Tools--Eigene--startwrap.zip)
[2020-10-19 22_51_39-Window.zip](https://github.com/giuspen/cherrytree/files/5404631/2020-10-19.22_51_39-Window.zip)

**Comment by Hoffenbar** [comment]
Addendum: It's not possible to recover from the situation. Quitting CherryTree and starting again gives the same result. I think all anchors have to be removed manually before a Retry makes sense; something I'm absolutely not in the mood for....

**Comment by Hoffenbar** [comment]
After opened the page in v0.39.4, it was possible to insert a new toc.

**Comment by szambonurek** [comment]
Not related but @Hoffenbar  you can edit your first comment instead of posting multiple.

**Comment by giuspen** [comment]
I see it thanks, the TOC works only the first time you generate it, 0.39.4 handled correctly re-generating the TOC, this is a bug in the porting to C++

**Comment by giuspen** [comment]
should be OK in 0.99.17
