### ISSUE TITLE
Wrong bullet characters

### ISSUE THREAD

**Issue by Hoffenbar** [giuspen/cherrytree#1269]
**v099.16, Windows**

After switching to other fonts, the bullets in bulleted lists are wrong, e.g. in the toc. The list of bullet characters in the respective configuration dialog looks right instead.

See attached screenshot.
[2020-10-19 23_24_59-Window.zip](https://github.com/giuspen/cherrytree/files/5404847/2020-10-19.23_24_59-Window.zip)

**Comment by txe** [comment]
The reason is that the fonts don't support some unicode symbols. You can change fonts, or change symbols in Preference dialog, or wait for resolving  #1065.

**Comment by kettenfett** [comment]
#1269

**Comment by txe** [comment]
The issue was fixed, the fix will be in 0.99.18
