### ISSUE TITLE
Printing to PDF erranous

### ISSUE THREAD

**Issue by Hoffenbar** [giuspen/cherrytree#1270]
**v0.99.16, windows**

Because exporting to PDF has some drawbacks (already reported), I tried to make a PDF via Print (Destination _Microsoft PrintoPDF_).
The result looks even worst then:
Text boxes have a width of 10% the page only, as does images.
See attached file.
[testPDFueberDruck.zip](https://github.com/giuspen/cherrytree/files/5404920/testPDFueberDruck.zip)

**Comment by txe** [comment]
Fixed. Caused by high pdf in MS print to pdf (600 vs 72)
The fix will be in 0.99.20
