### ISSUE TITLE
No more updates for Linux Mint 19.3 (Ubuntu 18.04)?

### ISSUE THREAD

**Issue by firepainting** [giuspen/cherrytree#1271]
Hi,

I see the Ubuntu 20.04 package is already out. Thank you! Does this mean development for 18.04 has been stopped?

I've been getting the prompt to update to 0.99.16. I've installed CT through Mint's native Software Manager and also added its PPA via the terminal but it seems I can't get it updated.

Thank you.

**Comment by ciranus** [comment]
`$ apt show cherrytree`
Version: 0.99.16-1
Depends: libgtkmm-3.0-1v5 (**>= 3.24**.0)

Ubuntu 18.04: [libgtkmm-**2.4**-1v5](https://packages.ubuntu.com/bionic/libgtkmm-2.4-1v5)

CT 0.99.xy is then not compatible with Ubuntu 18.04.

Little check-up of your system:
```
find /etc/apt -name '*.list' -exec grep 'giuspen' {} \;
apt-cache policy cherrytree
```

**Comment by giuspen** [comment]
Go distributions older than Ubuntu 20.04 the flatpak will be available soon

**Comment by firepainting** [comment]
Thanks for your replies! CT not supporting Ubuntu 20.04 back then, except the flatpak, was the reason I haven't upgraded my OS. Will have to check my system and I hope I can finally do it!

**Comment by firepainting** [comment]
Hi @giuspen,

I'm planning to stick to my current distro release until its EOL in April 2025. (Mint 20 LTS based off Ubuntu 20.04 LTS.)

I can't find the full changelog for the .deb version for Ubuntu Bionic (18.04) back then but IIRC, its development(?) was paused for about one year. (I didn't watch it closely.)

On this thread you suggested using Flatpak, and Snaps on other threads I believe. But I don't like them both and have none of them installed on my PCs.

Will this be the case for the next major release (Ubuntu 22.04)?

In case the .deb version does not come out for a while again, will it be safe to continue using CT's outdated version?

Thank you.

**Comment by ciranus** [comment]
> I'm planning to stick to my current distro release until its EOL in April 2025. (**Mint 20 LTS based off Ubuntu 20.04 LTS.**)

For info:
https://launchpad.net/~giuspen/+archive/ubuntu/ppa
![2021-12-28_14-30](https://user-images.githubusercontent.com/61602511/147572147-090f44e3-2c00-4611-a314-b7e269ee6131.png)

**Comment by firepainting** [comment]
Thanks and sorry for the late reply.

@ciranus Sorry I did not explain more clearly.

Back in April 2020 I was still on Bionic (18.04 LTS), and the available options for CT for Bionic around that time were only Flatpak and Snap, which I do not like. I prefer the .deb installer.

The last time I checked, it stayed that way (that only Flatpak and Snap installers were available) for about one year before the .deb installer came out for 18.04. But I cannot find the changelog for that anymore. (Correct me if I'm wrong.) This was the time when CT's version was 0.39.xxx.

My question is, now that Ubuntu 22.04 is coming soon, will updates for the .deb installer be "paused" again like what happened to Bionic as I described? Because right now I'm considering staying with the current release (20.04) until its end of life.

Thank you.

**Comment by ciranus** [comment]
The big change for Cherrytree was the jump from **gtk2** to **gtk3** some time ago.
CT 0.99.xy is available for ubuntu:

- bionic (18.04 LTS)
- focal (20.04LTS)
- hirsute (21.04)
- impish (21.10)

CT .deb package will be available for 22.04 LTS without any difficulty.
Then no foreseen problem if "_you are considering staying with the current release (20.04) until its end of life_", unless giuspen decides to drop the 20.04LTS CT package **before** 20.04LTS end of life (I don't see any reason, but he can confirm if necessary).

As far as I know, there is no more CT 0.39->0.99 changelog available (maybe archived somewhere), but don't clearly understand what you are looking for, especially if you already use 0.99 release.

**Comment by firepainting** [comment]
> The big change for Cherrytree was the jump from gtk2 to gtk3 some time ago.

I did not know this.

I was only curious, mostly. Should updates be "paused" again for the .deb package, then I would have to upgrade to 22.04. Otherwise, I would like to use 20.04 until its EOL.

As far as I know, only CT (among the apps I use) had this issue on updates. And I don't really know how these updates go, I'm pretty much just a normal user.

Thank you. I think you've cleared up all my concerns about this.

**Comment by giuspen** [comment]
@ciranus is totally right (thanks for the help), there is no plan in the short term to upgrade to a library that will cause older systems not to build anymore; however sometimes in the future cherrytree will migrate to Gtk4/Gtkmm4 and when that will happen I will have to drop surely 18.04, maybe 20.04, but as I said this won't happen for now as Gtk4 is still unstable and there is no reason to rush.

**Comment by firepainting** [comment]
@giuspen Thank you very much, I appreciate the response!
