### ISSUE TITLE
Classic Style Scheme is missing

### ISSUE THREAD

**Issue by repsorp** [giuspen/cherrytree#1272]
**Version, Operative system**
Ubuntu 20.04
CherryTree 0.99.16

**Describe the bug**
Classic Style Sheme is missing in Preferences/Theme/
amy & cobalt-darkened only are available
Only way to get classic style back is to modify config.cfg

**Screenshots**
![2020-10-21 17-25-14](https://user-images.githubusercontent.com/6297032/96742218-f03c5100-13c2-11eb-94f9-573c254a00bb.png)

**Comment by giuspen** [comment]
This is really strange, are you running a clean Ubuntu 20.04 desktop?

**Comment by repsorp** [comment]
I guess so, juste made a clean install a few days ago

**Comment by repsorp** [comment]
I just uninstalled/reinstalled cherrytree, same problem

**Comment by repsorp** [comment]
Tried to remove config.cfg, no change...

**Comment by giuspen** [comment]
You said that writing 'classic' manually in config.cfg worked, then the problem is only in the drop down menu not showing the styles while the styles are available. Can you try to manually write 'cobalt', is that also available while not shown?

**Comment by repsorp** [comment]
Nope, only works with classic, amy and cobalt-darkened
No change with writing 'cobalt'

**Comment by giuspen** [comment]
thanks, in 0.99.17 classic as long as the bare minimum styles will be bundled with cherrytree so will be present even if for any reason missing in the library

**Comment by repsorp** [comment]
For info...
amy & cobalt-darkened are in usr/share/cherrytree/styles/Amy.xml
classic cobalt, kate, oblivion, tango are in usr/share/gtksourceview-4/styles/

**Comment by ciranus** [comment]
> classic, cobalt, kate, oblivion & tango are in usr/share/gtksourceview-4/styles/

More probably from `/usr/share/gtksourceview-3.0/styles/` from `libgtksourceview-3.0-common`

**Comment by repsorp** [comment]
> More probably from `/usr/share/gtksourceview-3.0/styles/` from `libgtksourceview-3.0-common`

`/usr/share/gtksourceview-4/styles/` is the directory where Gedit 3.38 (text editor for the GNOME desktop) saves its schemes.
It won't find them if they're in `/usr/share/gtksourceview-3.0/styles/`

> libgtksourceviewmm-**3**.0-0v5 is a dependency of Cherrytree.
> `dpkg -L libgtksourceview-3.0-common | grep styles`

It looks like libgtksourceview-4-0 is only available from focal and beyond
https://packages.ubuntu.com/search?lang=en&keywords=libgtksourceview

**Comment by ciranus** [comment]
This is not the key point.
libgtksourceview-4-0 is **not** installed by Cherrytree.

see `apt-cache rdepends libgtksourceview-4-0`

I don't have any ibgtksourceview-4-0 installed in Groovy/KDE, because not needed.
