### ISSUE TITLE
how to debug failed zim import

### ISSUE THREAD

**Issue by tiggerfan** [giuspen/cherrytree#1273]
**Version, Operative system**
0.99.15, fedora fc32

**Describe the bug**
i'm trying to import my Zim notebooks.   2 worked fine. 2 do nothing, no errors, no messages, no nothing.
Is there some switch or setting to enable logging/debug info in cherrytree so i can see where in the import process it is failing and possibly correct/workaround on the Zim side?

thanks.

**Comment by ciranus** [comment]
Could you provide a small and not confidential zim file for test to reproduce ?

**Comment by tiggerfan** [comment]
i'm importing the folder so i've no ideal which file it might be.  Do you always start with the Home.txt?

**Comment by ciranus** [comment]
I don't have zim installed.
I just supposed it would facilitate investigations if one simple zim test file was made available to reproduce your problem.
So let's see if a zim user can reproduce your exact conditions.

**Comment by tiggerfan** [comment]
so there is no logging or tracing debug mode in the program?

**Comment by ciranus** [comment]
```
$ cherrytree --help-all

GTK+ Options
--gdk-debug=FLAGS            GDK debugging flags to set
--gdk-no-debug=FLAGS         GDK debugging flags to unset
--gtk-module=MODULES         Load additional GTK+ modules
--g-fatal-warnings           Make all warnings fatal
--gtk-debug=FLAGS            GTK+ debugging flags to set
--gtk-no-debug=FLAGS         GTK+ debugging flags to unset
```

I did not know you have development skills.

**Comment by tiggerfan** [comment]
thanks.  so that was a big help.  turns out the import doesn't like a bunch of =  which i use to separate sections.    after replacing the line of =============================
wtih ------------------------------
i could import.  here is the error:

[2020-10-24 09:31:25.994] [   ] [error] import exception: [Import Exception]: Parsing error while parsing header data: ================================================================ - Too many '='

**Comment by giuspen** [comment]
Thanks I have not done the import from zim but after your feedback should be an easy fix

**Comment by monotok** [comment]
Probably worth raising these import errors to the GUI as nothing happens. Found this issue with the solution to run cherrytree via terminal which helped me pin the error.
I got this exception to begin with. 

```
[error] import exception: [Import Exception]: Directory: /home/monotok/Notebooks/Notes/ZimTech/SoftwareDev/GIT does not contain a notebook.zim file
```
This has a valid zim note in it, the top level directory of ZimTech has the .zim file. I removed this directory and then got the same as @tiggerfan.
The debug does not indicate which file so used "grep -rc "============="" to search all files in zim directory which contain too many "=".
Then it imported successfully :+1:

**Comment by giuspen** [comment]
I should rather fix the issue, will try before the next release

**Comment by monotok** [comment]
> I should rather fix the issue, will try before the next release

No rush! Enjoy the Christmas break!

**Comment by giuspen** [comment]
should be ok in 0.99.28
