### ISSUE TITLE
Keepnote import not working

### ISSUE THREAD

**Issue by privatier51** [giuspen/cherrytree#1276]
Version 0.99.16 on Mint 20

Starting cherrytree from the command line, then
click on Import
click on From KeepNote Folder
select keepnote directory test
produces core dump: 
[2020-10-24 10:05:08.508] [   ] [debug] /home/.../.config/cherrytree/config.cfg parsed
[2020-10-24 10:05:08.765] [   ] [debug] Node name: more test
[2020-10-24 10:05:08.608] [   ] [debug] autosave is started
cherrytree: /build/cherrytree-oqiioT/cherrytree-0.99.16/src/ct/ct_imports.cc:531: virtual std::unique_ptr<ct_imported_node> CtKeepnoteImport::import_file(const fs::path&): Assertion `fs::is_directory(file)' failed.
Aborted (core dumped)

Keepnote directory I want to import:
[test.tar.gz](https://github.com/giuspen/cherrytree/files/5433391/test.tar.gz)

**Comment by txe** [comment]
Fixed. You see the fix in 0.99.18
