### ISSUE TITLE
Erroneous CT Language - Ignoring installation language of choice

### ISSUE THREAD

**Issue by octoberfestuser** [giuspen/cherrytree#1279]
**Version, Operative system**
OS	Microsoft Windows 10 Pro
Version	10.0.19041 build 19041

**Describe the bug**
On CherryTree installation (from latest stable binary "cherrytree_0.99.17.0_setup.exe") language "ENGLISH" is selected. After the installation is complete, however, the program presents itself in the Italian language (current System language). I did not find any setting in the program to change the language, so I tried reinstalling after complete program removal, but the problem persists.
I also removed all traces of "CherryTree" in the System Registry before attempting a new installation.
**NOTE:** when the installazion wizard moves to the Language installation section, the "Italian" language is pre-selected. My guess is that it ignores my selection of the English language, while in memory the pre-selected language is kept.

**To Reproduce**
Since I suppose all of new users have the program in Italian as no one complains, my guess is that the bug can be replicated if you try selecting a foreign to your system language. For example if your Windows System is in english, then select another language during installation.

**Screenshots**
![pic1](https://user-images.githubusercontent.com/36696355/97173629-c8653880-1788-11eb-8498-ddc855b8ec27.PNG)
![pic2](https://user-images.githubusercontent.com/36696355/97173633-c9966580-1788-11eb-8cc7-709e03519c55.PNG)
![pic3](https://user-images.githubusercontent.com/36696355/97173635-cb602900-1788-11eb-8e99-6971121f60f0.PNG)
![pic4](https://user-images.githubusercontent.com/36696355/97173642-cef3b000-1788-11eb-92f8-0f280a6376e5.PNG)

**Comment by txe** [comment]
FYI, the language can be changed in Preferences/Miscellaneous, language dropbox at the bottom of the dialog

**Comment by octoberfestuser** [comment]
Ok great. It worked. Although this is still a minor bug it's not an issue as changing the language post-installation works. Im closing it.
