### ISSUE TITLE
File window opens blank

### ISSUE THREAD

**Issue by Jaz-z** [giuspen/cherrytree#1284]
CherryTree 0.39.4  {a very useful application}
Operating System: Kubuntu 20.04
KDE Plasma Version: 5.18.5
KDE Frameworks Version: 5.68.0
Qt Version: 5.12.8
Kernel Version: 5.4.0-52-generic
OS Type: 64-bit
Processors: 4 × Intel® Core™ i5 CPU 660 @ 3.33GHz
Memory: 5.7 GiB of RAM

After opening a few instances (a few windows of CherryTree), opening another window (different file) opens as blank. (The file is not blank, it is full of information but it does not display).
Only the title bar (top bar used for moving or minimizing the window) can be seen. The rest of the window is blank (white).  For example four windows have been opened and worked with, but the fifth one opens with this error.
However on another window (file) previously open and working, if you click menu file and quite the application, then click on the cherry icon in the task bar all the files (windows) open correctly including the one that showed a blank window in the previous try.
The error can happen in any condition after the application has been open for a while. For example if you have several windows open, then close them one by one, then try opening a file by double clicking the file icon in a folder, this can happen. 
Normally this happens when you click on a file in a folder to open it.
Please see photo attached

![CherryTree_Bug_BlankWindow_202010271](https://user-images.githubusercontent.com/73505939/97242701-72c27780-17ec-11eb-851a-6e76d2a9a18a.png)

**Comment by ciranus** [comment]
> CherryTree **0.39.4**
> Operating System: Kubuntu 20.04

Try with 0.99.17
https://www.giuspen.com/cherrytree/#downl

**Comment by Jaz-z** [comment]
I uninstalled 0.394, updated  'other software sources' with 
ppa:giuspen/ppa and installed 0.99.17 from software centre (discover).

I can open CherryTree from applications and then open my files from the 
file menu -> open file.

However it does not open files by directly clicking on a file icon in a 
folder. It gives the following error:

'Could not read database property "kexidb_major_ver". Error opening 
database cursor.'

With 0.39.4 it did open files by clicking on them, it just had some 
problems after many files opened as described in the original bug report.

**Comment by ciranus** [comment]
> However it does not open files by directly clicking on a file icon in a folder.

This is a different problem related to file association in KDE, and not CT.
Right-click on any *.ctb ou *.ctd files, choose open with Cherrytree, and then 'remember this action' (or something like this).

**Comment by Jaz-z** [comment]
Thank you it worked. I had done the same with previous version, didn't 
think it needs to be done again.

I will get back if the other problem crops up again.

**Comment by giuspen** [comment]
Thanks @ciranus for solving this

**Comment by ciranus** [comment]
> I uninstalled 0.394
> I had done the same with previous version, didn't think it needs to be done again.

Because you did not upgrade CT, but first uninstalled CT, then cleaned the file association.

##
Maybe an opportunity to review shared cherrytree mime directory, compared to other applications:
Is /usr/share/**mime-info**/ the right place ? 
Apparently only used by Cherrytree: /usr/share/mime-info/cherrytree.mime

/usr/lib/**mime**/packages/ or /usr/share/**mime**/packages/ seem more widely used.

```
$ apt-file search /usr/share/mime/packages/

gfsview:      /usr/share/mime/packages/gfsview.xml
grsync:       /usr/share/mime/packages/grsync.xml
kbackup:      /usr/share/mime/packages/kbackup.xml
libreoffice:  /usr/share/mime/packages/libreoffice.xml
okteta:       /usr/share/mime/packages/okteta.xml
olive-editor: /usr/share/mime/packages/org.olivevideoeditor.Olive.xml
rox-filer:    /usr/share/mime/packages/rox.xml
zim:          /usr/share/mime/packages/zim.xml
```

**Comment by Jaz-z** [comment]
Manually looked at: User/share/mime-info     it includes: cherrytree.keys

cherrytree.mime

libreoffice.keys

libreoffice.mime

openjdk-11-archive.keys

openjdk-11-archive.mime

 From the list you have indicated in mime/packages (libreoffice is noted 
as libreoffice-common in terminal)

Most files that come up in terminal can't be seen manually when I looked 
in the folder

 From terminal the files you have indicated are there:

/usr/lib/*mime*/packages/ include:

gfsview: /usr/share/mime/packages/gfsview.xml

grsync: /usr/share/mime/packages/grsync.xml

||kbackup: /usr/share/mime/packages/kbackup.xml libreoffice-common: 
/usr/share/mime/packages/libreoffice.xml

okteta: /usr/share/mime/packages/okteta.xml

olive-editor: /usr/share/mime/packages/org.olivevideoeditor.Olive.xml

rox-filer: /usr/share/mime/packages/rox.xml

zim: /usr/share/mime/packages/zim.xml

*New Issue*

This time, when Associating the cherrytree file to the application, I 
made a mistake and right clicked on the link to the file (not the file 
itself) choose 'open with' and then associated it to cherrytree. 
Clicking on files or links, the files open. However:

1- previously the cherrytree backup files where always in the original 
folder with the actual (target) file, now in addition to these backups 
along with the actual file, in the folder where the links are, there are 
also three backup files (unwanted).

2- Now if I remove .ctb from the link name, the link does not open the 
target file.

To test if due to associating the link to cherrytree app, the link was 
now a hard link, I removed a previous link and created a new symbolic 
link in the terminal using 'ln -s' command. However this doesn't change 
the behaviour and I still get three extra back up files where the link 
is located.

I wonder if there is something else going on ? or my mistake of 
associating a link to cherrytree file has created this problem and if it 
is from my action, how can I reset it so the link only opens the target 
file?

I have too many links to cherrytree files in one folder to get the extra 
back files with them.

||

|*Crash* today, pasting a few texts from a webpage into a cherrytree 
page it crashed. Auto crash report sent. |

**Comment by ciranus** [comment]
@Jaz-z
Mime association is already really confusing in linux itself (probably due to gnome history), and I am afraid you add some confusion.
I delete my previous message raising the fact I was not sure /user/share/mime-info/ is still the right place to store mime application (because unsure of the current recommended place).
It is a fact that .ctX files are not automatically understood as Cherrytree files in a KDE system, but personally don't consider this as a major issue.
I do not have any problem with CT file association in KDE, or any other file association, even with links to CT files.
You make some mistakes somewhere not related to CT. You should visit a KDE forum to clarify your mistakes.

Complete different subject you raise: backup files. See:
![2020-10-29_09-53](https://user-images.githubusercontent.com/61602511/97546390-ab20ac00-19cc-11eb-9191-074db8508d86.png)



For new problems, new issues !

**Comment by giuspen** [comment]
Thanks again @ciranus for helping on this. @Jaz-z you mentioned a crash pasting content from the web, if you can reproduce it with 0.99.18 raise a new issue helping us to reproduce it. The automatic crash reports are sent to ubuntu but we are not receiving anything about that or I don't know how to access that data at the moment.

**Comment by Jaz-z** [comment]
If I can reproduce it, I will give you more information.

While trying to be helpful, sorry to say I am neither a programmer, nor 
advanced in Linux, so my feed back may be lacking details that you need.
