### ISSUE TITLE
CherryTree freeze/crash when deleting a node

### ISSUE THREAD

**Issue by dardoor** [giuspen/cherrytree#1285]
Steps to reproduce:
1. Open test.ctd in CT. [test.zip (updated - no pictures)](https://github.com/giuspen/cherrytree/files/5445023/test.zip)
2. Click on the third node (test3).
3. Save (Ctrl+S).
4. Exit CT.
5. Start CT and open test.ctd, if it didn't open automatically already.
6. Right click on test2 and select Delete Node.
7. Confirm (Yes).

The result is that CT freezes (not responding), seemingly indefinitely. It happens with both SQLite and XML encoding.

**EDIT:** I can reproduce this on Windows 7 and on Windows 10. (I previously couldn't reproduce it in a W10 VM, because config.cfg was set to Read-only.)

CherryTree 0.99.17, 64 bit.

**Comment by txe** [comment]
Thanks for the issue,
The bug is quite funny, something was freezing inside Gtk and was caused by really innocent code.
The fix will be in 0.99.18
