### ISSUE TITLE
[Cosmetic] Menus have excessive white-space before icons

### ISSUE THREAD

**Issue by neildarlow** [giuspen/cherrytree#1289]
**Version, Operative system**
0.99.17, Linux Mint 20

**Describe the bug**
The drop-down menus exhibit excessive white-space before the icons.

**To Reproduce**
1) Start cherrytree
2) Open a menu

**Screenshots**
Screenshot of File menu attached to illustrate issue.

![cherrytree-menu](https://user-images.githubusercontent.com/6245505/97443898-74428b80-1923-11eb-99a3-7f91cd6529ee.png)

**Comment by ciranus** [comment]
Menu could probably be shrinked a little bit:

![2020-10-28_15-22](https://user-images.githubusercontent.com/61602511/97454020-972a6b00-1936-11eb-814f-abf84b4ae7d0.png)

**Comment by neildarlow** [comment]
The issue is only really the size of the left-side padding. You need to be careful with adjusting the overall width to allow for translated strings which could require more space.

**Comment by txe** [comment]
The fix will be in 0.99.19.
Though there are some issues with this fix. For some reason from time to time, gtk stops drawing images in Menu until you hover mouse over menu item causing redrawing (it happened several times on Linux and Win). I don't know why.
So maybe, we will revert this fix.
