### ISSUE TITLE
Search In Current Node isn't searching in the current node

### ISSUE THREAD

**Issue by metal450** [giuspen/cherrytree#1293]
**Version, Operative system**
Windows 10, CherryTree 0.99.18

**Describe the bug**
In one particular node, whenever I Search in Current Node (Ctrl+F), it searches in a different node.  In other words: let's say I have 2 nodes, NodeA & NodeB.  I view NodeB and Search in Current Node; it immediately jumps to NodeB, & shows results there instead.

This only seems to happen for one particular node, which it will not search in.  Any other node I go to, it properly searches within that node.  Just this one "NodeA," as soon as I search, it jumps to "NodeB" (even if the search has no results, it jumps to NodeB & shows no results).

**Comment by txe** [comment]
Can you make a copy of your document and remove other nodes and important info and provide it? I took a look at the code but I didn't see the issue could happen.

**Comment by metal450** [comment]
Is there a quick way to delete multiple nodes?  I've got hundreds of nodes, but can't seem to multi-select them in the tree, & if I highlight one then press delete, the cursor ends up in the writing area of the next - so it's a bit prohibitively slow to delete them all one at a time, as I have to keep going back with the mouse one at a time.

**Comment by txe** [comment]
There is no way to remove the all at one.
Maybe it will be faster to drag&drop under one node and then delete that node. Or you can try to export these specific nodes in a separate document.

**Comment by metal450** [comment]
Exporting didn't seem to reproduce it.

I've spent the past ~20min slowly trying to delete one at a time; unfortunately, I don't think it's going to be feasible to reproduce at this rate (I'm still barely halfway there).  I think it might be better for me to just wait until after https://github.com/giuspen/cherrytree/issues/75 ...

**Comment by bender270** [comment]
Version, Operative system
Windows 10, CherryTree 0.99.18

Hi, I have  the same problem . Here Is a test tree where you can reproduce the problem.
[test.zip](https://github.com/giuspen/cherrytree/files/5482588/test.zip)



There is a node with instructions Inside to reproduce the problem.

Thank you

**Comment by txe** [comment]
@bender270, thanks a lot, it was helpful
The dialog with results wasn't deleted after hiding, and as result it caused such issues during the next search.

**Comment by bender270** [comment]
@txe you are welcome. I love this software,  congratulations for your job ;)
