### ISSUE TITLE
Source of some of the icons

### ISSUE THREAD

**Issue by merkys** [giuspen/cherrytree#1298]
**Version, Operative system**
CherryTree 0.99.15
Debian unstable

**Describe the bug**
I am working to reintroduce CherryTree in Debian. To do so, I have to list copyrights of all files present in CherryTree download. These files have explicit licenses, but no information on who their copyright holders are:
```
Files:
 icons/ct_zoom-in.svg
 icons/ct_zoom-out.svg
License: LGPL-2.1

Files:
 icons/ct_fmt-indent.svg
 icons/ct_fmt-unindent.svg
License: GPL-2.0
```
A reference from where they have been taken would help a lot!

**Comment by giuspen** [comment]
I reckon grepping Ubuntu Mate for SVG but I will look in detail at the scg you listed and get back to you

**Comment by merkys** [comment]
Thanks, looking forward!

**Comment by giuspen** [comment]
/usr/share/icons/HighContrast/scalable/actions/format-indent-more.svg from https://packages.ubuntu.com/focal/gnome-accessibility-themes - looking at the other now

**Comment by giuspen** [comment]
/usr/share/icons/HighContrast/scalable/actions/zoom-out.svg same package.
I noticed you mentioned version 0.99.15, please package instead the latest available at the moment (right now 0.99.18), as you know 0.99.x is still young and every release if fixing important issues

**Comment by merkys** [comment]
Great, thanks a lot for prompt response! Regarding the version, I will surely update it once it gets past the license review.

**Comment by giuspen** [comment]
Thanks to you 😉
