### ISSUE TITLE
Search with bar in progress as cherrytree portable for windows 0.39.4

### ISSUE THREAD

**Issue by rpierluigi** [giuspen/cherrytree#1302]
In version 0.39.4
there was a bar indicating the percentage during the search
In the new version 0.99.18 portable for windows there isn't
I wonder if it is possible to have that bar in progress with percentage so I know where the search is
above all if there are hundreds of results found.
Also it would be good to have a button to stop the search and not wait for it to end if the search have 
thousands result.
Thanks for new cherrytree program
![SearchWithBarInProgress](https://user-images.githubusercontent.com/15266442/97779719-2d050680-1b80-11eb-929b-ce48c0227883.jpg)

**Comment by giuspen** [comment]
It should be there, the thing is I don't have a document big enough to test it (all my searches are instantaneous) but I'll try and have a look

**Comment by giuspen** [comment]
Thanks, will be ok in 0.99.20
