### ISSUE TITLE
Did something with the caret or insertion cursor by mistake

### ISSUE THREAD

**Issue by britotiago03** [giuspen/cherrytree#1304]
I accidentally changed the caret or insertion cursor by mistake and i don't know how to change it back.

![image](https://user-images.githubusercontent.com/69848652/97787174-d7951d80-1bb0-11eb-9f60-dbf41a3b5ca1.png)

Does anyone know how to change it back to this one? 

![image](https://user-images.githubusercontent.com/69848652/97787188-f693af80-1bb0-11eb-8258-2559a59a7ce6.png)

**Comment by txe** [comment]
What is your OS and cherrytree version?

**Comment by britotiago03** [comment]
> What is your OS and cherrytree version?

Windows 10 and Cherrytree 0.99.15

**Comment by txe** [comment]
If you didn't change in Gtk related (css, etc) files, then just press 'Insert' button.

**Comment by britotiago03** [comment]
> If you didn't change anything in Gtk related (css, etc) files, then just press 'Insert' button.

Where is the Insert button?? Like i was typing and accidentally typed together keys like shift, ctrl, altgr, enter and the arrow keys, then the caret or insertion cursor changed to that one. When i type with this one and use space, it deletes the words that are in front of where i am typing.

**Comment by txe** [comment]
`Insert` button on the keyboard, or you can just close the app and start it again.

**Comment by britotiago03** [comment]
> `Insert` button is on the keyboard, or you can just close the app and start it again.

It just changed back when I pressed the insert button, thank you so much for helping me and replying fast.

**Comment by txe** [comment]
You are welcome
