### ISSUE TITLE
missing uninstall for make

### ISSUE THREAD

**Issue by freddii** [giuspen/cherrytree#1305]
I installed it with "sudo make install" on debian.

But i was not able to remove it with "sudo make uninstall"

**Comment by giuspen** [comment]
We'll add support for uninstall but in the meantime if you install and then uninstall the Debian package it should clean out the installation files

**Comment by freddii** [comment]
Thanks for adding support for uninstall.
Iinstalled it from source cause its not in the repo of debian sid.
https://www.debian.org/devel/wnpp/work_needing.en.html
 orphaned since 76 days.

**Comment by ciranus** [comment]
CT is coming, will come to Debian, but never ask when with Debian.
https://salsa.debian.org/debian/cherrytree
