### ISSUE TITLE
Too many files

### ISSUE THREAD

**Issue by lost2** [giuspen/cherrytree#1307]
I'm using cherrytree_0.99.18.0_win64_portable.7z on windows 10.
While doing a backup of my docs, apps, etc, noticed that cherrytree folder have more then 4700 files over 630 dirs and about 194 MB!
Is it possible to reduce this huge number of files/dirs? Are all these needed to run cherrytree?

Thank you!

**Comment by txe** [comment]
We don't know what files are needed or will be needed. Cherrytree is based on Gtk framework which tugs along other stuff. Maybe some files from 'mingw64\share\icons' can be removed, but generally I don't think the size of the folder can be reduced substantially.
