### ISSUE TITLE
Cherrytree using absurd amounts of memory

### ISSUE THREAD

**Issue by JFiTech** [giuspen/cherrytree#1309]
**Version, Operative system**
Microsoft Windows installer as well as the Windows portable archive, both on version 0.99.18

**Describe the bug**
Upon executing the Cherrytree executable the memory usage skyrockets into the thousands of MBs. I've been having the high memory usage since a previous alpha version, don't recall which version but it had a .3 in it and I installed it on September 28th 2020, the problem with the previous one wasn't when opening the program, it occurred when closing it or while using it would stop responding and the memory usage would rapidly increase. Below I have attached two screenshots taken from the task manager, the first one shows the spike when opening the program and the second one shows the CPU usage on the left and memory on the right, the last one was taken on my phone because the memory usage gets so high that it crashes my PC.

**To Reproduce**
1. Go to wherever in your computer the cherrytree.exe executable or launcher shortcut is located
2. Double click it to start the program
3. Whithin seconds of executing the program (the UI doesn't even show up on screen) it crashes the (my) computer

**Screenshots**
![Bug](https://user-images.githubusercontent.com/12865915/97918233-b453a500-1d4d-11eb-9246-66b38b76a40f.png)

![Cherrytree_error](https://user-images.githubusercontent.com/12865915/97919388-9f781100-1d4f-11eb-8a68-9dbe07ab3e06.png)

**Comment by txe** [comment]
When I start cherrytree without any document, it takes 15 Mb, so I suppose you also open some document. If the document has xml format, cherrytree loads the document into the memory. And if such document is big, then it takes a lot of memory. I suggest to use sqlite format.

**Comment by JFiTech** [comment]
> 
> 
> When I start cherrytree without any document, it takes 15 Mb, so I suppose you also open some document. If the document has xml format, cherrytree loads the document into the memory. And if such document is big, then it takes a lot of memory. I suggest to use sqlite format.

Yes, I am using XML format, but I just tried opening a 1.95 KB file and the memory usage still skyrockets. Even though after reinstalling the program the problem persists. I have no option to open the program without any document because whenever I execute it, it opens the most recent document.

**Comment by giuspen** [comment]
Look at preferences dialog, tab miscellaneous, reload document from last session

**Comment by txe** [comment]
@JFiTech, 

> Yes, I am using XML format, but I just tried opening a 1.95 KB file and the memory usage still skyrockets.

That's really odd. Maybe reinstalling doesn't help because `config.cfg` is still the same. To remove it, you need to close cherrytree and remove `config.cfg` from `C:\Users\your_user_name\AppData\Local\cherrytree`

**Comment by JFiTech** [comment]
> 
> 
> @JFiTech,
> 
> > Yes, I am using XML format, but I just tried opening a 1.95 KB file and the memory usage still skyrockets.
> 
> That's really odd. Maybe reinstalling doesn't help because `config.cfg` is still the same. To remove it, you need to close cherrytree and remove `config.cfg` from `C:\Users\your_user_name\AppData\Local\cherrytree`

Removing the .cfg files fixed the memory usage issue, but now I have a new one, when I run the cherrytree executable the OS suspends the program and doesn't allow me to run it

**Comment by JFiTech** [comment]
> 
> 
> > @JFiTech,
> > > Yes, I am using XML format, but I just tried opening a 1.95 KB file and the memory usage still skyrockets.
> > 
> > 
> > That's really odd. Maybe reinstalling doesn't help because `config.cfg` is still the same. To remove it, you need to close cherrytree and remove `config.cfg` from `C:\Users\your_user_name\AppData\Local\cherrytree`
> 
> Removing the .cfg files fixed the memory usage issue, but now I have a new one, when I run the cherrytree executable the OS suspends the program and doesn't allow me to run it

Solved the suspending issue
