### ISSUE TITLE
[info request] Top points on TODO list

### ISSUE THREAD

**Issue by sklages** [giuspen/cherrytree#131]
Hi,
I love cherrytree, it is really nice to work with and very helpful.

I was wondering if you have a rough idea when you will find some time to implement the first two points on your TODO list. 
I think these are very important ..
- assign custom icons to nodes/sub nodes [..]
- open several cherrytree files (notebooks) at the same time [..]

best,
Sven

**Comment by giuspen** [comment]
Hi Sven, the custom icons are already available please try
http://www.giuspen.com/topic/0-37-beta-0-36-99/ and write feedback.
Greetings,
Giuseppe.

**Comment by sklages** [comment]
Ah, thanks, great.
I'll check out :+1: 
best,
Sven
