### ISSUE TITLE
Disabling "Highlight Current Line" option in Preferences doesn't do anything

### ISSUE THREAD

**Issue by ElnuDev** [giuspen/cherrytree#1310]
**Version, Operative system**
Version: **CherryTree 0.39.4**
Operating System: **Ubuntu 20.04 LTS**

**Describe the bug**
Disabling the **Highlight Current Line** option in **Preferences** doesn't do anything, the current line still highlights. I even tried restarting CherryTree, but that didn't fix the issue. Alternatively, is there some way to change the highlighted line color?

**To Reproduce**
1. Go to **Edit** → **Preferences** → **Plain Text and Code**
2. Uncheck **Highlight Current Line**
3. Exit out of **Preferences**.
4. The current line still gets highlighted.

**Comment by giuspen** [comment]
We are not going to release additional 0.39.x versions, please upgrade to 0.99.x

**Comment by ElnuDev** [comment]
Ah, thanks! I used the version that was available on snap, I guess the version there is out-of-date.

**Comment by giuspen** [comment]
Yes please use the ppa

**Comment by ElnuDev** [comment]
I'm having the same issue with 0.99.18.

**Comment by giuspen** [comment]
There are two of such options, one for rich text and one for plain text and code, are you sure you disabled the right one?

**Comment by ElnuDev** [comment]
Ah, I had only selected the option in **Plain Text and Code**, not the one in **Rich Text**. Thanks! Sorry for the trouble.
