### ISSUE TITLE
Recent Documents not working?

### ISSUE THREAD

**Issue by ElnuDev** [giuspen/cherrytree#1318]
**Version, Operative system**
Version: **CherryTree 0.99.18**
Operating System: **Ubuntu 20.04 LTS**

**Describe the bug**
The **Recent Documents** section of the **File** menu is always empty. Hovering over it reveals a single item, **Remove from list**, which in turn contains just an empty menu with no options. I've opened and saved documents in CherryTree before, but I can never find them again in **Recent Documents**.

**To Reproduce**
Steps to reproduce the behaviour:
1. Ensure that your install of CherryTree has opened documents before.
2. Click on **File**
3. Scroll down to **Recent Documents**
4. The only child of **Recent Documents** should be **Remove from list**, which I'm not quite sure what it is, which in turn only contains an empty menu. There are no recently opened documents to be found in the menu.

**Screenshots**
![recent-documents-bug](https://user-images.githubusercontent.com/9874955/98448334-24f91980-20e0-11eb-83ed-2ae2aaab1658.png)

**Comment by ciranus** [comment]
How many different CT documents did you previously open ?

**Comment by txe** [comment]
@ElnuDev, 
1. from where did you install cherrytree?
2. if you change something in Preferences (e.g. font), will it be kept changed after restarting cherrytree?

**Comment by ElnuDev** [comment]
> How many different CT documents did you previously open ?

@ciranus I opened just one. I tried saving a new document in addition to that, and that fixed it. However, the original document would not show up again until I opened it once more. Seems like a bug? I'm not sure.

**Comment by ElnuDev** [comment]
> @ElnuDev,
> 1. from where did you install cherrytree? 
> 2. if you change something in Preferences (e.g. font), will it be kept changed after restarting cherrytree?

@txe 

1. I compiled CherryTree from source. I'm on Ubuntu 20.04 LTS.
2. Yes, it stays changed after restarting CherryTree.

**Comment by ciranus** [comment]
Can you explain why you need to compile anything ?
https://launchpad.net/~giuspen/+archive/ubuntu/ppa/

Can you try again with 0.99.19 from ppa ?

**Comment by ElnuDev** [comment]
@ciranus Everythings still seems to work fine, although it seems to have remembered my recent documents and settings from my previous install, so I can't say if the bug is there still. Seems to be pretty trivial, opening a second document fixed it in 0.99.18 so I'm going to close the issue. Thanks for the help!

**Comment by ElnuDev** [comment]
@ciranus Everythings still seems to work fine, although it seems to have remembered my recent documents and settings from my previous install, so I can't say if the bug is there still. Seems to be pretty trivial, opening a second document fixed it in 0.99.18 so I'm going to close the issue. Thanks for the help!

**Comment by ciranus** [comment]
@ElnuDev  
For my personal knowledge, I would like to understand why you apparently don't trust the ppa CT builds.
I really don't see any risk using this CT ppa.
Just for curiosity.
