### ISSUE TITLE
possibility of having a number of cards defined in the bar of the nodes 

### ISSUE THREAD

**Issue by rpierluigi** [giuspen/cherrytree#1319]
Product cherrytree 0.99.18 portable for windows 10
Wonder if it is possible to have the
bar of visited nodes even when closing and reopening the database. Today unfortunately it is reset every time you leave

![SchedeRecentiDaTenereMemorizzate](https://user-images.githubusercontent.com/15266442/98448581-4b917180-212d-11eb-928f-8853b6684cb9.jpg)

**Comment by txe** [comment]
Fixed, The fix will be in 0.99.20
