### ISSUE TITLE
Search in all nodes change last visited nodes

### ISSUE THREAD

**Issue by tom-i** [giuspen/cherrytree#132]
Actual result:
When you normaly go through some nodes, you can see last 3 nodes in history (top of the page), but when you search something e.g.by "Ctrl+Shift+F", you can see that your history of visited nodes were rewritten by searching.

Steps to repro:
1. Go through some nodes (e.g. 4) - you can see history of last visited in the top of the page.
2. Search somestring by e.g."Ctrl+Shift+F".

BUG - your last visited nodes has been rewritten.

OS:  Fedora release 22
CherryTree version: git 0.36.99

**Comment by giuspen** [comment]
I just committed a fix to git, could you please verify it?

**Comment by tom-i** [comment]
Verified and fixed ;)
Thanks Giuseppe
