### ISSUE TITLE
Window title displays old version number

### ISSUE THREAD

**Issue by merkys** [giuspen/cherrytree#1323]
**Version, Operative system**
CherryTree: 0.99.18
Debian unstable

**Describe the bug**
Main window title shows old version number: `CherryTree 0.37.6`. This might be Debian-specific bug, but I was unable to find a place in code setting the title for the window in order to debug it.

**To Reproduce**
Open up the application and check the window title.

**Comment by giuspen** [comment]
Can you run cherrytree --version from the terminal?

**Comment by giuspen** [comment]
thanks I figured out looking at https://salsa.debian.org/debian/cherrytree that @ciranus kindly mentioned in another issue

**Comment by merkys** [comment]
> Can you run cherrytree --version from the terminal?

Sure. This results in the same version as in the window title.

Thanks a lot for the prompt fix!
