### ISSUE TITLE
Cannot Save After Editing an Old .ctd File 

### ISSUE THREAD

**Issue by sh3r1n** [giuspen/cherrytree#1331]
**Version, Operative system**
CherryTree 0.99.19
Kubuntu 20.04

**Describe the bug**
I used cherry tree old version and created a  note  before
today installed new version from github 
then i tried to open and edit the note create before
when i edited and tried to save the note
what happens is the application closes and the note was deleted 

**Screenshots**

╰─>$ ls -all
-rw-rw-r--  1 sh3r1n sh3r1n 2896925 Nov 10 20:49  note.ctd

╰─>$ cherrytree note.ctd                                                                                                                      
[2020-11-10 20:48:12.442] [   ] [debug] /home/sh3r1n/.config/cherrytree/config.cfg parsed                                                     
[2020-11-10 20:48:12.788] [   ] [debug] autosave is started                                                                                   
[2020-11-10 20:48:13.167] [   ] [debug] Node name: Django                                                                                     
[2020-11-10 20:48:20.924] [   ] [debug] Node name: 21 Sun                                                                                     
[2020-11-10 20:48:32.168] [   ] [error]  ! cannot found xml buffer in CtStorageXml::get_delayed_text_buffer, node_id: 790                     
[2020-11-10 20:48:32.193] [   ] [error]  ! cannot found xml buffer in CtStorageXml::get_delayed_text_buffer, node_id: 796                     
[2020-11-10 20:48:32.414] [   ] [error]  ! cannot found xml buffer in CtStorageXml::get_delayed_text_buffer, node_id: 790                     
fish: “cherrytree note.ctd” terminated by signal SIGSEGV (Address boundary error)

**Comment by txe** [comment]
Can you say what the previous cherrytree version was? Maybe the backward compatibility are lost, I'd like to check that idea.

**Comment by torresjoj** [comment]
I also have this issue. I do not know what version I was using originally, but the last time I edited the file before using it today was fall 2019.

**Comment by sh3r1n** [comment]
note created with cherrytree version 0.39.3

**Comment by txe** [comment]
@torresjoj @sh3r1n 
Is it possible to share your broken documents with @giuspen , or parts of those documents (if you open the file in any text editor, you can remove any sensitive information). It would be greatly helpful. 
I tried to create a document in older version, but still couldn't reproduce the issue.

**Comment by giuspen** [comment]
@txe the crash log is pointing to CtStorageXml::get_delayed_text_buffer I'll have a look to see if I find vulnerabilities as well when get some time

**Comment by sh3r1n** [comment]
I think the file size is the problem
I was deleting some notes and checked whether problem persists after deleting each note, deleted some notes and when a certain note is deleted the problem doesn't appered, then I undid the delete operation and checked the problem persisted, then I deleted another note then the problem is note appearing
File Sizes
╰─>$ ls -all note*
-rw-rw-r-- 1 sh3r1n sh3r1n 2896925 Nov 13 11:57 note_complete.ctd
-rw-rw-r-- 1 sh3r1n sh3r1n 2504011 Nov 13 11:57 note_has_problem.ctd
-rw-rw-r-- 1 sh3r1n sh3r1n 1569893 Nov 13 11:57 note_removed_another.ctd
-rw-rw-r-- 1 sh3r1n sh3r1n 1913296 Nov 13 11:57 note_remove_one_note.ctd

'note_complete'           is the complete note
'note_has_problem'    removed some notes but has the problem
                                   other two has no problem, different notes deleted from each one

[https://github.com/sh3r1n/CherryTree-Notes](url)

**Comment by giuspen** [comment]
You mean deleting tree nodes? Maybe the issue is rather with some specific node content, if you could send me privately that would help

**Comment by sh3r1n** [comment]
yes tree notes, I included the link to the files previous comment  [Notes] (https://github.com/sh3r1n/CherryTree-Notes)

**Comment by txe** [comment]
I have a filling that issue caused by some nodes that have the same id number. So when one node is loaded, its id is removed from the delayed-loading cache, and the other node cannot be loaded because the delayed-loading cache doesn't have that id.

**Comment by txe** [comment]
Oh, you added files, thanks!

**Comment by torresjoj** [comment]
I'm unable to provide the file (would take hours to strip sensitive information and might not get it all), but I can confirm that importing the old ctd into a new one using the built in import functionality results in everything working fine, so I do not believe it would be anything like length or size related, and would be more likely to be something along the lines of parsing something that was valid in older nodes.

**Comment by txe** [comment]
Thanks to @sh3r1n, the files helped to figure out the issue, it were nodes with the same id.
The fix will be in 0.99.20

**Comment by giuspen** [comment]
Well done thanks @txe
