### ISSUE TITLE
PDF export does not render indented block

### ISSUE THREAD

**Issue by datavectors** [giuspen/cherrytree#1333]
0.99.15 on Ubuntu 20.04

I indent some paragraphs in nodes but they do not show in the exported PDF.

A further point is that the displayed text in an HTML link cannot be edited after its creation.
Only underlying URL can be edited.
I have to copy URL to clipboard, then remove formatting on text, edit the text then
repaste underlying URL

**Comment by giuspen** [comment]
Please upgrade to latest, add the ppa

**Comment by datavectors** [comment]
Since my apt PPA list is a bit corrupted, until I can tidy it I installed the deb. 0.99.19-2 using Gdebi ..
.. and the indent paragraph is now rendered in PDF ..
.. however another _very_ odd quirk ..
.. if I create some test nodes in a new document ..
.. alpha, beta, gamma .. the height of the gamma node is always higher than the other two! .. if I delete gamma and use node name delta all nodes are same height ..
-- the earlier document I was working on with 0.99.15 now has tree node height of about 6 cm .. so my first guess is some issue with tree nodes ..

**Comment by datavectors** [comment]
Moving to report fresh issue .. PDF export of indented block is solved.
