### ISSUE TITLE
[Linux] --new-window option

### ISSUE THREAD

**Issue by ciranus** [giuspen/cherrytree#1339]
If easy to implement, a '`cherrytree --new-window`' option could be useful.

**Comment by txe** [comment]
Done

**Comment by ciranus** [comment]
Thanks.
Some comments for potential improvement / test with CT 0.99.22

`cherrytree --new-window document.ctb` currently opens an empty document
▸ should open document.ctb

`cherrytree --new-window` currently has no effect is cherrytree is not already opened.
▸ should also open cherrytree 

// minor issue, just to avoid specific test in a script like this:
```
pgrep cherrytree && NW='--new-window'
cherrytree $NW test.ctd
```

**Comment by giuspen** [comment]
thanks @ciranus it will be improved in next version

**Comment by ciranus** [comment]
Perfect !
It's now more compliant with common use, and faster to open a test window from a shortcut.
