### ISSUE TITLE
ERROR: Data Error in encrypted file. Wrong password? : 7zr.ctd

### ISSUE THREAD

**Issue by breachr** [giuspen/cherrytree#1340]
**Version, Operative system**
Win 10

**Describe the bug**
When i try to build cherrytree as described by the manual i get the following error:

[ 98%] Building CXX object src/ct/CMakeFiles/cherrytree.dir/ct_main.cc.obj
[ 98%] Building CXX object src/ct/CMakeFiles/cherrytree.dir/icons.gresource.cc.obj
[ 98%] Linking CXX executable run_tests.exe
[ 99%] Linking CXX executable ../../cherrytree.exe
[100%] Built target cherrytree
[100%] Built target run_tests
................................ERROR: Data Error in encrypted file. Wrong password? : 7zr.ctd
..................
...

**To Reproduce**
Follow the manual to build on windows

Help appreciated!

BTW: The only reason i try to build cherrytree is to change some of the node icons :-P

**Comment by giuspen** [comment]
That is not an error in the build, it's just the output when running the unit tests. Be patient after that you should see a print stating that the tests passed

**Comment by txe** [comment]
That test error output will be suppressed in 0.99.21
