### ISSUE TITLE
[bug] Crash when triying to move a table column

### ISSUE THREAD

**Issue by userfav** [giuspen/cherrytree#1342]
**Version, Operative system**
Windows 10 - x64 / Cherrytree version 0.99.20  / portable mode

**Describe the bug**
Cherrytree crashes when you try to move a table column.

**To Reproduce**
- Create a table with tree columns and some rows. 
- Click on some row of the center column to focus.
- Right click on the cell  and choose "Move column left"

![imagen](https://user-images.githubusercontent.com/46328784/99260604-61bcc300-27fa-11eb-9832-24a98d9b34a6.png)

Crash:

![imagen](https://user-images.githubusercontent.com/46328784/99260425-1bfffa80-27fa-11eb-94c1-419045c44bf9.png)

**Comment by giuspen** [comment]
Thanks for the report I'll see if I can reproduce

**Comment by txe** [comment]
The fix will be in 0.99.21
