### ISSUE TITLE
monospace again...

### ISSUE THREAD

**Issue by Hoffenbar** [giuspen/cherrytree#1343]
I don't want to stress this, but with 0.99.20.0 it isn't possible to combine a text which is tagged to be shown a monospaced also to be shown italic (in addition to the combination with bold, which isn't possible, too and reported as another ticket).
I defined "monospace normal" as the font for monospace. My expectation was to define "monospace", and then the program chooses "monospace bold" for that combination, "monospace oblique" for mono+kursiv, and "monospace Bold oblique" for the combination of all together.
As long as I choose a font which is able to be shown in all combinations, why couldn't cherrytree?
If I remember well, this was all possible with the old python version?

**Comment by giuspen** [comment]
This issue happens since we are now defining a custom font for monospace. I can add a checkbox before the custom font for monospace so if you untick you will have the legacy behaviour. I don't think I can achieve more. Would you be happy with that?

**Comment by Hoffenbar** [comment]
Yes I think this could be a solution !-- Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 18.11.20, 00:21 schrieb Giuseppe Penone <notifications@github.com>:

   
  This issue happens since we are now defining a custom font for monospace. I can add a checkbox before the custom font for monospace so if you untick you will have the legacy behaviour. I don't think I can achieve more. Would you be happy with that?

**Comment by giuspen** [comment]
Will be in 0.99.22
