### ISSUE TITLE
Pasting text into a rich text node won't work anymore 0.99.20.0

### ISSUE THREAD

**Issue by Hoffenbar** [giuspen/cherrytree#1344]
Marked and copied a text in my text editor. 
Tried to insert the text into a node. **Nothing happens** (both ctrl+v, right click/insert).
Try to insert it into a codebox of type text - this works.
Marked a text _within_ a ct node: the paste works!
Seems that interaction with the clipboard is partially "dead".......

Just switched back to 0.99.19.0 - there it works as expected.

**Comment by giuspen** [comment]
This is related to https://github.com/giuspen/cherrytree/issues/1336 will try and look at this tomorrow

**Comment by giuspen** [comment]
fixed in 0.99.21
