### ISSUE TITLE
Expand CodeBoxes Automatically is being ignored

### ISSUE THREAD

**Issue by Tyrewt** [giuspen/cherrytree#1345]
Expand CodeBoxes Automatically option is being ignored. Select text, insert codebox, the codebox height appears with a scrollbar and ignores vertical lines of text past 6 rows.

Expand CodeBoxes Automatically: Checked
CodeBox Type: Plain Text, size 100w x 100h as %.
CherryTree v0.39.4 from Ubuntu 18.04 PPA.

![Screenshot from 2020-11-17 12-54-27](https://user-images.githubusercontent.com/21961083/99428010-1840a680-28d4-11eb-8f0b-bdf0e9413a74.png)

**Comment by giuspen** [comment]
This works much better in the new version 0.99.x.
Unfortunately you cannot install that on 18.04 at the moment, only on 20.04 or more, but I'll try and release a flatpak soon

**Comment by Crankle437** [comment]
Is there an option to enforce to use of the set size of the CodeBox which is set in the properties (enforce line break after x chars)? In the latest version 0.99.23 the automatic resizing is working well, but if a lot of text is in a single line the CodeBox is very wide and not readable any more.

**Comment by giuspen** [comment]
Well you have to untick "Resize Codeboxes Automatically" if you want to enforce your set size. Maybe we should allow this option to go on the codebox so you can generally resize automatically but have exceptions... is this what you are asking?

**Comment by Crankle437** [comment]
Thanks, that's what I was looking for. I've upgraded from 0.39.x to 0.99.x there the settings must be changed and I've missed this setting (Edit -> Preferences -> Rich Text -> Expand CodeBoxes Automatically).
