### ISSUE TITLE
Crash when pasting HTML

### ISSUE THREAD

**Issue by DieHardMan5x** [giuspen/cherrytree#1346]
**Version, Operative system**
CherryTree version: 0.99.20
Xfce version: 4.14
ManjaroLinux 20.2

**Describe the bug**
Crash when pasting HTML into RichText Node.

**To Reproduce**
Select text like on screenshot and paste into cherrytree:
https://gitlab.haskell.org/ghc/ghc/-/merge_requests
(sample site for demonstrating)

**Screenshots**
![image](https://user-images.githubusercontent.com/74651322/99510405-55b23c00-2987-11eb-923b-c6a45cf85813.png)

**Comment by txe** [comment]
I fixed the crash, but still the inserted html won't look like in a browser; we just parse an html document without applying css styles (we cannot apply such styles)
