### ISSUE TITLE
Automated as-installed tests

### ISSUE THREAD

**Issue by merkys** [giuspen/cherrytree#1347]
Debian has a service of continuous integration (CI) which allows to automatically detect when updates of dependencies break their dependents. It would be very nice if CherryTree would have some automated as-installed tests, as they would prevent (unlikely) degradation of functionality due to the changes in its dependencies. Maybe such tests already exist, if so, please let me know how I can run them.

"Automated as-installed" means that these should be runnable on a command line, and would use CherryTree as it is installed in the system. A very simplistic example of such test is `cherrytree --help`, which only guarantees that CherryTree is able to execute successfully. Of course GUI applications are difficult to test, but maybe CherryTree has a CLI which could be used for that?

**Comment by giuspen** [comment]
Cherrytree is building and running unit tests via Travis. You can see https://github.com/giuspen/cherrytree/blob/master/.travis.yml or also the https://github.com/giuspen/cherrytree/blob/master/README.md explains how to build and run

**Comment by merkys** [comment]
I see. However, it seems that Travis runs rebuilds and build-time tests. What I inquired here about were as-installed tests.

**Comment by giuspen** [comment]
The full cherrytree document read and write is under test but that doesn't happen via the cherrytree binary (main()). What you would like is to be able to run via a command line argument to cherrytree?

**Comment by merkys** [comment]
> The full cherrytree document read and write is under test but that doesn't happen via the cherrytree binary (main()). What you would like is to be able to run via a command line argument to cherrytree?

Yes, this would be nice. This way I would be able to test whether CherryTree works properly after installing it system-wide. And Debian CI would be able to test if updates of dependencies do not degrade CherryTree installation.

**Comment by giuspen** [comment]
What about the option to install the test executable? The result would be the same but we would not have to bundle google test inside of cherrytree.

**Comment by merkys** [comment]
This is worth investigating. Could you please indicate where can I find the test executable after building the package?

I guess for the time being as-installed tests do not need to test all the functions. Simply opening some CherryTree file would be OK. If the program opens a file successfully, we can be sure that most of the libraries are loaded properly.

**Comment by giuspen** [comment]
Sure:
build/tests/run_tests

**Comment by merkys** [comment]
Thanks!

**Comment by giuspen** [comment]
Note in the latest git I (just) moved it to build/ beside the cherrytree binary (sorry)
