### ISSUE TITLE
Request for windows build for 0.99.x series

### ISSUE THREAD

**Issue by abid-k** [giuspen/cherrytree#1352]
Hello,

Could you please provide windows installer for 0.99.x series? Looks like a lot of features are added recently, so would like to give it a try.

**Comment by giuspen** [comment]
Hi, there is already at https://www.giuspen.com/cherrytree/#downl I advise you to wait for 0.99.21 though which should come tonight because 0.99.20 has annoying issues with the clipboard on windows
