### ISSUE TITLE
7za sources and license.txt

### ISSUE THREAD

**Issue by malcolmlewis** [giuspen/cherrytree#1356]
Hi
Now that future has moved to present, is it possible to review the 7za license file text. In your source you are not using any of the unrar headers, therefore the reference in this txt file is somewhat redundant?

The reason I ask is trying to get cherrytree back into the openSUSE distribution but with that file I'm failing legal review;

`@babelworx declined the legal report with the following comment: b'Contains non-free unrar license at src/7za/License.txt '`

**Comment by giuspen** [comment]
Thanks @malcolmlewis I'll review this shortly, indeed we are not making any unrar use, I'm surprised that it is in there, the bundle comes from https://sourceforge.net/projects/p7zip/
