### ISSUE TITLE
Nested Tables - copy paste

### ISSUE THREAD

**Issue by Jaz-z** [giuspen/cherrytree#1358]
Operating System: Kubuntu 20.04 desktop
KDE Plasma Version: 5.18.5
KDE Frameworks Version: 5.68.0
Qt Version: 5.12.8
Kernel Version: 5.4.0-54-generic
OS Type: 64-bit

CherryTree 0.99.21

**Describe the bug**
copying all information including nested tables from an LibreOffice odt file and pasting into a cherryTree node, tables partly (or sometime all) show as stacked on each other.
But after closing cherrytree and reopening the file the tables appear to be correct.

A test odt document is attached. To replicate, select all (select everything in the document) and paste in a cherrytree node.

[nested tables.zip](https://github.com/giuspen/cherrytree/files/5578628/nested.tables.zip)

**Comment by giuspen** [comment]
Will be ok in 0.99.22
