### ISSUE TITLE
feature request: Scroll past the end

### ISSUE THREAD

**Issue by krisko** [giuspen/cherrytree#136]
Hi,
I've got interesting feature to implement in cherrytree...
Could you add option to allow scrolling past the end of text in node.
Example: I always add number of empty lines at the bottom of file, to be able to scroll text to the middle of screen, or just higher from the bottom.

Thank you

**Comment by giuspen** [comment]
Hi, I also would find this useful personally since I use this in geany. In
future I will try to achieve it.

**Comment by hb20007** [comment]
Duplicate of #109

**Comment by txe** [comment]
Resolved by #1162 for C++ version, Edit->Preferences->Text and Code-> [] Scroll Beyond Last Line
