### ISSUE TITLE
CherryTree 0.99.21: search and node issue

### ISSUE THREAD

**Issue by 1Martinik** [giuspen/cherrytree#1361]
I have tested the CherryTree 0.99.21 on my Windowss 10 x64 and I would like to share with you my findings when using my 600MB .ctb database file.
CherryTree crashes in the following situations:

- when use search: no matter what are you searching
- I have created a node with all information found here https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.txt. When reopen the cherry tree and click on this node the program is craching without showing the node content.

This is the event log
Faulting application name: cherrytree.exe, version: 0.99.21.0, time stamp: 0x00000000
Faulting module name: libgtk-3-0.dll, version: 3.24.23.0, time stamp: 0x00000000
Faulting application path: C:\Program Files\CherryTree\mingw64\bin\cherrytree.exe
Faulting module path: C:\Program Files\CherryTree\mingw64\bin\libgtk-3-0.dll

P.S.
On Kali Linux 2020.1 I have CerryTree 0.38.8 and it works perfect.

**Comment by txe** [comment]
duplicate  #1337
