### ISSUE TITLE
Changing the color of the rich text background...

### ISSUE THREAD

**Issue by fattywompus** [giuspen/cherrytree#1362]
I've been spoiled by how configurable cherrytree has been in the past.  In the .99 versions I have updated to There are only 4 options to change the main page background and in the config file the colors are listed in a string so I don't know which one might be the background.  Any chance we could see an option to set a custom background for the rich text area as easily as we still can for the tree and monospace background?  Or if not maybe a config file that's straight forward to tweak?

**Comment by steveno** [comment]
I saw a comment from @giuspen somewhere on here that this was a known missing feature of the new version. Hopefully this issue will prevent them from forgetting it.

**Comment by giuspen** [comment]
It was completely missing some time ago, now at least  there are few pre existing themes. Shouldn't be too difficult in future to add an interface to create a custom theme.

**Comment by fattywompus** [comment]
Thanks for the reply.  Even if it was just as simple as a color picker for the main page background.  Everything else can either already be configured or, as far as the window itself goes, can be set to match the OS.  Of course if you wanted to implement theme's you'll get no complaints from me :)  I use cherry tree on a few different computers both on linux and windows so an actual theme file would save me a lot of fiddling around with each individual setting when setting up new instances or after big updates or reinstalls.  

Also, have to say many thanks to giuspen and everyone involved for making and maintaining cherrytree.  It's the greatest note taking program ever!

**Comment by knotha** [comment]
I use cherry tree for scientific writing, and setting my own custom text and background colours are a big part of finding the flow. If you could implement any way to set custom colours, e.g. by config file or simple picker it would be great. Thank you very much for all effort on cherrytree, it's a great editor.

**Comment by giuspen** [comment]
I will make a simple theme editor

**Comment by R3ality** [comment]
+1 to the feature request of adjusting the colors of the Rich Text area.

Assuming that a theme editor (as proposed by @giuspen above) would take more time/effort I believe that (simpler?) options for changing (only) the color of the Text and Background would more than suffice. These could work in conjunction (not instead of) the predefined Style Schemes. Example mockup of the Preferences UI option below to illustrate:
![image](https://user-images.githubusercontent.com/762122/107163961-34288580-69b5-11eb-814c-2954909086b1.png)

So essentially the user could pick whichever predefined style that is closest to their desired color scheme. And then further customize the two most important colors without the need for a fully featured theme editor.

**Comment by R3ality** [comment]
Until this feature request is implemented the predefined Style Schemes can be modified manually. **Please note that any modifications to these are at your own risk!**

They are XML files found in `.\mingw64\share\gtksourceview-3.0\styles` (note that there are copies also in `.\mingw64\usr\share\cherrytree\styles` which don't appear to be used). They'll also be overwritten during subsequent version upgrades.

For example, to change the background color of the "cobalt" Style Scheme:
1. Make a backup of _cobalt.xml_ (for example _cobalt.xml.bak_)
2. Open _cobalt.xml_ in a text editor
3. Find and replace `#001b33` (the default background color of this scheme) with your desired color hex code. It only appears once
4. Relaunch cherrytree and make sure "cobalt" is selected as the active scheme for Rich Text

For any other Style Scheme look for this line in the "Global Settings" section of the file
`  <style name="text"                        foreground="white" background="dark_blue"/>`
Then modify whichever color names are referenced from the "Colors" section (in this example it is "dark_blue" for the background color)

**Comment by giuspen** [comment]
I'm trying to put this in the next release

**Comment by giuspen** [comment]
The implementation is complete and will be available in the upcoming 0.99.31
