### ISSUE TITLE
click on line number(s) to select line(s)

### ISSUE THREAD

**Issue by aalleexxaannddrree** [giuspen/cherrytree#1363]
**Is your feature request related to a problem? Please describe.**
Using mouse, selecting lines now requires to be at 1st character of 1st line you want to copy, then slide down to the end.

**Describe the solution you'd like**
Using mouse, it would be easier (as in Notepad++ and others) to select the whole line by clicking its line number space.

**Comment by giuspen** [comment]
a triple click is the standard to select a line, is that enough?

**Comment by aalleexxaannddrree** [comment]
That helps 👍 
But does not work for 1 gesture multi-line selection.
I'll have to change some habits, so for multiple lines, still do a Maj-click somewhere in the text. 
But I recognize it's not the top priority thing ^o^

**Comment by Peterling007** [comment]
I dont know the behaviour of notepad++ and similar on this topic. 
But since years i thought from time to time, it would be so practical to mark a block of lines by streaching over the linenumber-column with the left-button-pressed mouse.

**Comment by HolyshitOvO** [comment]
I also have this requirement. I mainly use cheeytree to record common codes, so I have to turn on the line number display in the settings, but when I edit the code, I always inadvertently swipe on the line number to select the line , but it doesn't work, and then I realize, oh, it's cheeytree, and that's causing me trouble. This function is supported in notepad++ sublime text idea vs. I hope the author can improve this.

Finally, thank the author very much for making such a good software! @giuspen

**Comment by giuspen** [comment]
Ok I implemented this, will be in 0.99.56. If you can build and test before the release and provide feedback would be useful.

**Comment by aalleexxaannddrree** [comment]
Hi
This has been implemented yes, but it actually selects the whole paragraph (several lines), and not only 1 line as the software cited do. 
The perfect behavior would be (for me):
-Single line selection with 1 click on the border .
-Several lines selection with sliding click on the border .
-Paragraph selection with 2 clicks on the border .

Not sure if everybody does see it that way...

Anyway, thanks for your work on Cherrytree !

**Comment by giuspen** [comment]
you are right the single click on the border is definitely not right, this may be the behaviour of the double click instead

**Comment by CandyTek** [comment]
The software implements a part of the function of swiping line numbers to select text lines, but in fact it does not always work well.

However, I still want to thank this software, which made me change the habit of selecting lines by line numbers. Now I will use triple-click to select lines in all selectable text interfaces, because there are no line numbers in other places such as web pages, and you can use triple-click selection to get through most places smoothly.
