### ISSUE TITLE
[bug] Not saving changes of icon or blocked node on occasions

### ISSUE THREAD

**Issue by userfav** [giuspen/cherrytree#1364]
**Version, Operative system**

CT 0.99.21 PORTABLE MODE - Windows 10 x64 , database type: ctb

**Describe the bug**

Nothing big, jut a little annoying, but in some cases, cherrytree is not saving the changes of icon or block/unblock of a node.

**To Reproduce**

I made a single ctb file, with four nodes, and changed some icons to the yellow circles, as can be seen here:

![imagen](https://user-images.githubusercontent.com/46328784/99919733-f6915600-2cfd-11eb-9436-5066382119e8.png)

At this point, I save the changes an exit CT.

I open again the file and change the icon of the node **3. three** to the green one:

![imagen](https://user-images.githubusercontent.com/46328784/99919776-42dc9600-2cfe-11eb-9bbe-30e96f4976eb.png)

It doesn't show the icon preview, I don't know if that's normal:

![imagen](https://user-images.githubusercontent.com/46328784/99919808-6273be80-2cfe-11eb-820d-d329a39010ea.png)

So now I have this:

![imagen](https://user-images.githubusercontent.com/46328784/99919856-b4b4df80-2cfe-11eb-8b49-4c8964952236.png)

And now I save and quit cherrytree again.

When I open again the file, the icon remains on yellow:

![imagen](https://user-images.githubusercontent.com/46328784/99919885-e037ca00-2cfe-11eb-9d13-a868e8506dcc.png)

Same behavior happens if I "block" the node, save the changes, exit cherrytree and open it again.  It is shown unblocked again.

My configs and the test files:

[test-file.zip](https://github.com/giuspen/cherrytree/files/5580588/test-file.zip)

**Comment by userfav** [comment]
Maybe it's a little more worrying, I see that also happens when changing nodes names (that's why on the screenshots the child nodes names change, I don't notice it the first time).

**Comment by txe** [comment]
Thanks, I take a look

**Comment by txe** [comment]
Thanks again, the fix will be in 0.99.22
