### ISSUE TITLE
Crashes when toggling font properties (monospace, small, underline, etc.)

### ISSUE THREAD

**Issue by dzes483** [giuspen/cherrytree#1367]
**Version, Operative system**
Version 0.99.22, operating system LMDE 4 Debbie

**Describe the bug**
When the user toggles any font property such as bold, italic, monospace, small and superscript, etc., the program instantly crashes. This happens when using keyboard shortcuts as well as the Formatting menu. It does not crash when toggling any of the header properties.

**To Reproduce**
1. Go to Formatting
2. Click on Toggle __ Property (except for h1, h2, and h3: those work)
3. Program instantly crashes. The font property chosen for the selected text does not persist.

Alternatively:
1. Use any of the keyboard shortcuts for font properties (Ctrl + M, Ctrl + B, etc. except for the header shortcuts)
2. Program instantly crashes. The font property chosen for the selected text does not persist.

This feature was working before the latest update.

**Comment by txe** [comment]
I cannot reproduce the issue (as well as #1369). @giuspen maybe it is related to the deb file from your site? can you try it?

**Comment by giuspen** [comment]
The deb file is generated from the ppa, I'm no longer generating a deb myself. I cannot reproduce either.
@dzes483 have you built yourself from sources?

**Comment by dzes483** [comment]
No, I installed it with Flatpak.

**Comment by dzes483** [comment]
It is working now! Thank you for your support and for the software!
