### ISSUE TITLE
File link with arguments?

### ISSUE THREAD

**Issue by ReinRalle** [giuspen/cherrytree#137]
Is it possible under windows to use a File link with arguments?

What I'm trying: C:\Windows\System32\cmd.exe /k 

What I get:  "The File Link 'C:\Windows\System32\cmd.exe /k' is not valid"

Any solution?

PS: Super program in the division ... many, many thx

**Comment by giuspen** [comment]
Try to change to:
C:\Windows\System32\cmd.exe /k %s
Yu need the %s that will be replaced with the filepath

**Comment by ReinRalle** [comment]
Unfortunately, no luck ;-(

What I want to achieve, is to call a terminal under Windows and pass arguments.

What works: 
**C:\windows\system32\cmd.exe**

To open the terminal in a specific location, the command is: 
**C:\windows\system32\cmd.exe / k cd d:\TestFolder**

That does not work ;-(

I Am unfortunately beginners in Python, but I wonder whether it is not possible to add this feature in CherryTree?

Ralf

PS: I am just starting with CherryTree and I want to use it primarily as a local blog system.

I also work with some scripting dialects (* .bat, * .vbs, * .sh and try to start python).

It would be a great help if I could not only monitor with CherryTree my steps, but "initiate" also from CherryTree.

For example: start a terminal, start a script, start a program with arguments and so on.

I could also take an IDE, but I would like to put CherryTree to the top.

CherryTree -> start IDE 1 with args -> Script 1
CherryTree -> start IDE 2 with args -> Script 2
CherryTree -> start Terminal 1 with args -> start git
CherryTree -> start Terminal 2 with args -> start docker
CherryTree -> start Terminal 3 with args -> start VirtualBox
CherryTree -> start putty, FileZilla etc with arguments(
CherryTree -> test Code fragments

args => Set folder, set colours, set switches, redirect stdin, stdout, stderr and so on

And all comment simultaneously with CherryTree.

If that were possible, it would be cool

**Comment by txe** [comment]
`C:\windows\system32\cmd.exe / k cd d:\TestFolder` doesn't work because `cd` needs an `/D` to changing a driver (d: in this case)
Running code from cherrytree is possible by executing codeboxes.
