### ISSUE TITLE
Crash when trying to add a link

### ISSUE THREAD

**Issue by iuvege** [giuspen/cherrytree#1374]
I'm using the 0.99.22 version from flathub (in my case on Debian 10).

The program is crashing (closing without messages) when you select some text and then try to add a link, whether from the button bar, or from the menu or with [CTRL]+L. The "Add link" dialog does not appear in any moment.

**Comment by iuvege** [comment]
It is now solved, from today's update in flatpak (although the version number inside the program have not changed).

**Comment by giuspen** [comment]
Thanks I will issue a new official version this evening, it was too late to do that last night
