### ISSUE TITLE
Program freezes using mouse to drag a node to a different position in the left pane.

### ISSUE THREAD

**Issue by T-2** [giuspen/cherrytree#1377]
Cherrytree version 0.9.22 updated via PPA
OS: Linux Mint 20 MATE

Program freezes using mouse to drag a node to a different position in the left pane.
 Only way out is to force quit so I can start it again.
 Only does this if you try dragging shortly after starting Cherrytree. If you first expand some sub nodes in the left pane and view some nodes it does not freeze when you then try to drag a node to a new position.
 It's like a variable is not initialized until you do something else and then all is well.
 Has been doing this in every version since the first 0.99 version.
 Also did it in Linux Mint 19.3 MATE.
 Also does this on two different machines. Same OS and CT versions.
 Does this with both a 790K ctb file and a 6MB ctb file.

**Comment by T-2** [comment]
Got some more info on this. The problem occurs with a very specific sequence and is very repeatable even on latest release.
Tree Example:
Top Node 1
   Sub Node 1
      Sub-Sub Node 1
        Sub-Sub-Sub Node 1
   Sub Node n
      Sub-Sub Node 2
      Sub-Sub Node n
If I drag with the mouse Sub-Sub-Sub Node 1 and quickly drop it on Sub-Sub Node 2 it freezes or crashes Cherrytree only if Sub-Sub Node 2 already has Sub-Sub-Sub Nodes under it. If it does not have any Sub-Sub-Sub Nodes it does not crash. I say quickly because if I hover over Sub-Sub Node 2 and wait until it expands and it displays the Sub-Sub-Sub Nodes under it then drop Sub-Sub-Sub Node 1 it does not crash. Again it only does this the first time you do this type of operation after you start the program.

**Comment by giuspen** [comment]
I'll have a look in the weekend thanks

**Comment by giuspen** [comment]
it would be easier if you could provide a test document where I simply have to drag n drop to reproduce the issue

**Comment by T-2** [comment]
Does you latest post mean you do not need me to put together a test document?

**Comment by giuspen** [comment]
I think so but not 100% sure since could not reproduce your issue anyway. Can you build and run from the latest source code? If not no worries you'll give me feedback once 0.99.26 is out.

**Comment by T-2** [comment]
Since I have a workaround and I do not want to mess up my current install doing something I have never done before I think I will wait for .26. Thanks

**Comment by T-2** [comment]
Looks like you can close this one. No more freezing dragging and dropping nodes. Also fixed - no more black box covering the nodes directly under the node you are dragging. Now I can see where I am dropping them! The Dark Theme icons are much easier to see now.
Thanks for all the work on this.

**Comment by giuspen** [comment]
Great, thanks for coming back on this

**Comment by T-2** [comment]
It's baaaaack! After a week of no issues it did it again when I tried to drag and drop a node on top of another one. So your fix reduced the frequency of freezes but they are not gone. Therefore it is going to take a while for me to get a reliable sequence of steps for you to try to duplicate. I'll keep you posted.

**Comment by T-2** [comment]
Have not seen this problem for several versions now. I think we can close it for good this time.
Thanks.
