### ISSUE TITLE
Missing copy, cut, paste for tables in contextual menu

### ISSUE THREAD

**Issue by pckeller29** [giuspen/cherrytree#1379]
Hi
I must have missed something and please pardon me if I made you waste some time but I'm having a weird issue. I don't find these basic commands. Of course, keyboard shortcuts are working happily.

CherryTree 0.99.13 running on a Windows 10 in French.

No basic cut/copy/paste items neither in table contextual menu nor Edit menu.

1. select any kind of text in a table
2. Right click to show contextual menu
3. No classical, simple, basic Cut or Copy or Paste

Same things with Edit menu although there are raw text cut, copy, paste

Sorry, can't attach bitmap. Something went wrong.
Thank you

**Comment by pckeller29** [comment]
![cherrytree_ttQhdjnD3C](https://user-images.githubusercontent.com/9974154/100372093-0d3ef200-3009-11eb-9add-986fe98ddb48.png)

**Comment by giuspen** [comment]
Understood, I'll fix this thanks

**Comment by pckeller29** [comment]
You're welcome ;-)

**Comment by giuspen** [comment]
will be ok in 0.99.24

**Comment by pckeller29** [comment]
Just installed latest 0.99.24 version and checked. Works perfectly. Thank you!
