### ISSUE TITLE
Creation of a table of content

### ISSUE THREAD

**Issue by Crankle437** [giuspen/cherrytree#1382]
Ubuntu 20.04, 0.99.23

If a closing bracket is at the end of the headline the table of content is not working correctly. It will add the anchor to the end of the next line and in the TOC the next line is also showed and breaks the overview (see screenshot, TOC and headline _test2(test)_). If a anchor already exists at a headline, it will not create a second anchor or uses the existing anchor, it links to anchor which could not be found (see screenshot, click on link _test2_ -> error message)

![cherrytree](https://user-images.githubusercontent.com/46601128/100525444-373b1480-31c1-11eb-9cd3-ff4c65297476.png)

**Comment by giuspen** [comment]
thanks will be on in 0.99.24

**Comment by Crankle437** [comment]
I think the linking error was not fixed. If an anchor already exists the toc will not work correctly. Maybe it is possible to check if an anchor already exists and if one exists take it to create a link to it or maybe to create a second anchor for the toc only.

As you can see in the screenshot, before creating the toc an anchor `test_anchor` already exists. Then the toc will not correctly link to the headline
![test](https://user-images.githubusercontent.com/46601128/101069430-45f74200-359a-11eb-9b49-7f8b7ff9d30e.png)

**Comment by giuspen** [comment]
thanks, will be ok in 0.99.25

**Comment by Crankle437** [comment]
Thank you for your new release and instantly fixing bugs :) I'm very sorry but I think the issue is not fully fixed. :/
Now the toc is created correctly with all links, but the already existing anchors get overwritten, so all manually set links are broken (see screenshot):
![Screenshot_2020-12-09_21-28-47](https://user-images.githubusercontent.com/46601128/101684277-704b7280-3a66-11eb-8de7-0d89b33506f8.png)

Isn't this possible?
1. check if anchor exists
2. if anchor exists link to this anchor
3. if anchor does not exists create new anchor
4. link to new anchor
5. next headline, step 1


So all old anchors should still be valid and the toc should also work with the already existing anchors ;)

**Comment by Crankle437** [comment]
Should I open a new issue?

**Comment by giuspen** [comment]
I'll have a thought, I'm not sure about introducing support for other anchor names, I may just leave both

**Comment by Crankle437** [comment]
@giuspen: you mean you will create a new anchor for the toc and you'll not delete the manual created anchor? I think this would also be okay :)

**Comment by giuspen** [comment]
should be ok in 0.99.26

**Comment by Crankle437** [comment]
Thank you, now everything works fine :)

**Comment by Crankle437** [comment]
Hi @giuspen 

would it be possible to define a shortcut for creating a ToC? Perhaps to crate the ToC from the current node.

**Comment by giuspen** [comment]
You should be able to assign already a shortcut from the preferences dialog, tab keyboard shortcuts
