### ISSUE TITLE
[bug] can't open encrypted .ctx file when the filename is renamed

### ISSUE THREAD

**Issue by userfav** [giuspen/cherrytree#1383]
**Version, Operative system**

Win 10 x64 - CT ver. 0.99.23 - portable mode

**Describe the bug**

Encrypted ctx file can't be opened (password not recognized) when the ctx file name is renamed.

(I don't know if this is an expected behavior but for a moment really scared me because I thought that the file goes somehow corrupted)

**To Reproduce**

1. Create an encrypted SQLite password protected "test.ctx" file.
2. Close CT, and rename the file "text.ctx" to -for example- "test_renamed.ctx".
3. Open CT and try to open the renamed file. The password will not work with the new name.
4. If you revert the filename change the password works correctly.

Thanks

**Comment by giuspen** [comment]
The old version was coping with this, I will have a thought about supporting it

**Comment by userfav** [comment]
Thanks, some aspects to consider:

- If the filename it's fixed it, in the long run it becomes another password to remember.
- It limits the file management organizational capabilities (lets say that I want to preserve the state of a CT file to a date, I copy the original al renamed with a prefix, a date for example)
- It's not a common behavior on another encrypted software (encrypted compressed files (7z, rar, etc); office software (encrypted Microsoft docs or Libreoffice, etc.) or files from backup tools.
- If the version 0.39.4 doesn't work the same way, some people (like my case) they might think that the file goes corrupted - -adding some unreability caracteristic to the software-, or they can think that they simply forgot the password.
- When you create a new encrypted file, that condition (that the filename can't be changed to open the file) is not alerted to the user.

**Comment by giuspen** [comment]
will be supported in 0.99.24
