### ISSUE TITLE
[feature request] Option to preserve original letter case node names when exporting to plaintext

### ISSUE THREAD

**Issue by userfav** [giuspen/cherrytree#1385]
**Is your feature request related to a problem? Please describe.**

When exporting multiply nodes on plain-text format, the letter case of node names are forced to upper-case.

For example, if your node it's called "This is a nice Node" it's transformed to "THIS IS A NICE NODE" in the output file.  

This behavior doesn't happen when exporting to PDF/HTML. 

**Describe the solution you'd like**

I understand why this can be useful for some cases, so I think that with an option to preserve the original case can be resolved:

![imagen](https://user-images.githubusercontent.com/46328784/100544872-802db000-3237-11eb-9718-ac3af426648c.png)

**Comment by txe** [comment]
> When exporting multiply nodes on plain-text format, the letter case of node names are forced to upper-case.

Are you sure? I don't see such behavior during txt export (tried Win and Linux)

**Comment by txe** [comment]
What is your cherrytree version and OS version?

**Comment by userfav** [comment]
> 
> 
> What is your cherrytree version and OS version?

I'm with the 0,99.23 version, Win 10, portable mode.
The ct files is Sqlite. 

An example, this is what I have (all nodes are empty here):

![imagen](https://user-images.githubusercontent.com/46328784/100550889-e4fb0180-325b-11eb-9063-385c616c4ee4.png)

This are the export options:

![imagen](https://user-images.githubusercontent.com/46328784/100550907-1542a000-325c-11eb-8b27-151952cc32e1.png)

This is the output:

![imagen](https://user-images.githubusercontent.com/46328784/100550927-4b801f80-325c-11eb-8f4d-fe2f7e43bfc0.png)

Test file:

[testfile.zip](https://github.com/giuspen/cherrytree/files/5612679/testfile.zip)

**Comment by giuspen** [comment]
I don't think we are particularly fond with the uppercase but we do need somehow to distinguish the node name from the node content, and being plain text we cannot apply any style. What would you propose?

**Comment by userfav** [comment]
I doesn't have a specific proposal (I made this post because I had some markdown nodes to export and I put the header symbol (#) in the node name so I didn't need another type of identification of the node name). 

Besides that, I check some note-taking software to see how they handle exporting to plaintext, this is what I see:

Program | Modify node name in some way? | Add separator line? 
------------ | ------------- | --------------
Cintanotes | No | No
Mempad | Optional character before node name / Recursivity | No
Flasnote | Show the node tree path | Yes, at the end of each note content
All My Notes Organized|Show all path, add [Note] prefix| No
KeyNote NF|Node name between optional characters| No

Line separation is OK but doesn't resolve the need of  "distinguish the node name from the node content".

Maybe the most interesting case is how Mempad handle it. You can assign an optional character, lets, say "$" to be the prefix of each node name, and optionally you can set to add one more of the same character on each level of the tree, so in my case (following the test that I show above to @txe ) it will be end like this:

    $ parent node
    
    $$ child node 1
    
    $$ child node 2
    
    $$ child node 3
    

(this resolves my case with the markdown files, just replacing the $ symbol with the # symbol)

With this format, you can also replicate the "All My Notes Organized" way of handle it (if you allow to add more than one character, without recursion).

I hope this helps.

**Comment by giuspen** [comment]
A good research thanks, I think we'll go with the prefixing character(s) by default and possibly make it configurable

**Comment by giuspen** [comment]
will be in 0.99.25
