### ISSUE TITLE
Information copied from the Linux terminal will be badly formatted

### ISSUE THREAD

**Issue by feitat** [giuspen/cherrytree#1387]
**Version, Operative system**
v0.39.4  win10 64bit

**Describe the bug**
Information copied from the Linux terminal will be badly formatted

**Screenshots**
![image](https://user-images.githubusercontent.com/16658141/100566278-994e6380-3300-11eb-8198-bb5be7fd7b5d.png)
![image](https://user-images.githubusercontent.com/16658141/100566360-c0a53080-3300-11eb-9320-fc43090d9641.png)
Normally it should be displayed like :
![image](https://user-images.githubusercontent.com/16658141/100566396-d9ade180-3300-11eb-8992-a3c03b6f29f1.png)
![image](https://user-images.githubusercontent.com/16658141/100566415-e3374980-3300-11eb-8972-9396ccdc6510.png)

**Comment by giuspen** [comment]
You have to put it in a codebox or tag it monospace. What you paste from a terminal is just plain text.

**Comment by feitat** [comment]
> You have to put it in a codebox or tag it monospace. What you paste from a terminal is just plain text.

Thanks, I accidentally clicked MS on the taskbar and the problem was solved
