### ISSUE TITLE
CherryTree 0.99.24 won't open attached files

### ISSUE THREAD

**Issue by TriggerDingus** [giuspen/cherrytree#1390]
**Version, Operative system**
State the Version and the Operative System/Desktop. Try the latest available version before reporting an issue.
CherryTree 0.99.24
Pop! 20.10
Gnome 3.38.1

**Describe the bug**
I have a CherryTree file/project in which I have many nodes to which I've attached various files using Edit>Insert File. The files are of various types, E.G. jpg, pdf, odt, etc. The issue is I can't open the attached files by double-clicking them or right-clicking and selecting Open File. When I attempt to do so, nothing happens; no error, no program opening in the background, nothing.

I've double-checked the attached files by hovering over them to make sure their sizes are legit and to assure I didn't insert an empty icon - they all look good.

I saw in an old bug report that somewhat reported a similar issue and it was closed because they installed using Snap. Mine is installed using the Pop! Shop ala flathub(flatpak).

I do have my CherryTree data file(s) in a Cryptomator vault, and so to verify that wasn't causing an issue I copied the file(s) to an unencrypted file location and tested it there but the same result occurred.

There isn't an error to attach, though I've attached a picture of one of my rich text nodes with some attached files. I've also attached a snapshot of when I attempt to exit the program - it appears it thinks I did open file attachments.

![image](https://user-images.githubusercontent.com/75340371/100804370-bebf9800-33fa-11eb-9265-e8655dc743f6.png)

![image](https://user-images.githubusercontent.com/75340371/100804722-5cb36280-33fb-11eb-9092-1b44ed535708.png)

**Comment by giuspen** [comment]
I will double check now with flatpak and see if I can fix it (it is apparently preventing from starting an external process). In the meantime I advise if you are on an Ubuntu 20.10 based distribution to use the giuspen ppa for the best experience.

**Comment by TriggerDingus** [comment]
Works now! I downloaded the revision you posted on 12/1/20 directly from your PPA and it's fixed.
I went through about 10 note taking apps before quickly settling on CherryTree. It operates exactly like I think and so was a very intuitive app for me to dig into and be immediately productive. Great work, man!
