### ISSUE TITLE
[Feature Request] Allow the user to scroll past the bottom of the editor buffer/content.

### ISSUE THREAD

**Issue by nt-o** [giuspen/cherrytree#1393]
**Is your feature request related to a problem? Please describe.**
It is frustrating when the content of a node reaches the bottom of the editor and I am unable to continue scrolling in order to position the active line somewhere above the very bottom of the window.  Adding a bunch of \n's is a workaround, but it would be nice to be able to scroll past the bottom of the contents by default.

**Describe the solution you'd like**
See above.

**Comment by userfav** [comment]
Did you tried this option?:

![imagen](https://user-images.githubusercontent.com/46328784/100906933-7eb6ee80-34a8-11eb-99fe-c0b2e3e127f6.png)

**Comment by giuspen** [comment]
Thanks @userfav, this is already possible in 0.99.24
