### ISSUE TITLE
MacOS - BigSur has broken the dependencies

### ISSUE THREAD

**Issue by krupalb** [giuspen/cherrytree#1398]
**Version, Operative system**
Mac OSX Big Sur 11.0.1

**Describe the bug**
The Mac os (BigSur) compile process is failing. I've have all the dependencies installed as stated in the instructions. This worked on Catalina. Just tried to update CherryTree I'm getting the following error please help.

I tried 
brew reinstall gtkmm glib 
same error? are my dependencies broken on Big Sur?

`In file included from /Users/randomuser/tools/cherrytree/src/ct/ct_clipboard.cc:24:
/Users/randomuser/tools/cherrytree/src/ct/ct_clipboard.h:24:10: fatal error: 'gtkmm/textiter.h' file not found
#include <gtkmm/textiter.h>
/Users/randomuser/tools/cherrytree/src/ct/ct_app.cc:         ^~~~~~~~~~~~~~~~~~24
:10: fatal error: 'glib/gstdio.h' file not found
#include <glib/gstdio.h>
         ^~~~~~~~~~~~~~~
In file included from /Users/randomuser/tools/cherrytree/src/ct/ct_codebox.cc:24:
/Users/randomuser/tools/cherrytree/src/ct/ct_codebox.h:24:10: fatal error: 'gtkmm.h' file not found
#include <gtkmm.h>
         ^~~~~~~~~
In file included from /Users/randomuser/tools/cherrytree/src/ct/ct_export2html.cc:24:
In file included from /Users/randomuser/tools/cherrytree/src/ct/ct_export2html.h:26:
In file included from /Users/randomuser/tools/cherrytree/src/ct/ct_table.h:26:
/Users/randomuser/tools/cherrytree/src/ct/ct_codebox.h:24:10: fatal error: 'gtkmm.h' file not found
#include <gtkmm.h>
         ^~~~~~~~~
/Users/randomuser/tools/cherrytree/src/ct/ct_config.cc:25:10: fatal error: 'gtkmm.h' file not found
#include <gtkmm.h>
         ^~~~~~~~~
In file included from /Users/randomuser/tools/cherrytree/src/ct/ct_actions_import.cc:24:
In file included from /Users/randomuser/tools/cherrytree/src/ct/ct_actions.h:26:
In file included from /Users/randomuser/tools/cherrytree/src/ct/ct_dialogs.h:26:
In file included from /Users/randomuser/tools/cherrytree/src/ct/ct_misc_utils.h:26:
/Users/randomuser/tools/cherrytree/src/ct/ct_types.h:30:10: fatal error: 'glibmm/ustring.h' file not found
#include <glibmm/ustring.h>
         ^~~~~~~~~~~~~~~~~~
In file included from /Users/randomuser/tools/cherrytree/src/ct/ct_actions_others.cc:24:
In file included from /Users/randomuser/tools/cherrytree/src/ct/ct_actions.h:26:
In file included from /Users/randomuser/tools/cherrytree/src/ct/ct_dialogs.h:26:
In file included from /Users/randomuser/tools/cherrytree/src/ct/ct_misc_utils.h:26:
/Users/randomuser/tools/cherrytree/src/ct/ct_types.h:30:10: fatal error: 'glibmm/ustring.h' file not found
#include <glibmm/ustring.h>
         ^~~~~~~~~~~~~~~~~~
In file included from /Users/randomuser/tools/cherrytree/src/ct/ct_dialogs.cc:24:
In file included from /Users/randomuser/tools/cherrytree/src/ct/ct_dialogs.h:26:
In file included from /Users/randomuser/tools/cherrytree/src/ct/ct_misc_utils.h:26:
/Users/randomuser/tools/cherrytree/src/ct/ct_types.h:30:10: fatal error: 'glibmm/ustring.h' file not found
#include <glibmm/ustring.h>
         ^~~~~~~~~~~~~~~~In file included from /Users/randomuser/tools/cherrytree/src/ct/ct_actions_help.cc:24:
In file included from /Users/randomuser/tools/cherrytree/src/ct/ct_actions.h:26:
In file included from /Users/randomuser/tools/cherrytree/src/ct/ct_dialogs.h:26:
In file included from /Users/randomuser/tools/cherrytree/src/ct/ct_misc_utils.h:26:
/Users/randomuser/tools/cherrytree/src/ct/ct_types.h:30:10: fatal error: 'glibmm/ustring.h' file not found
#include <glibmm/ustring.h>
         ^~~~~~~~~~~~~~~~~~
~~
In file included from /Users/randomuser/tools/cherrytree/src/ct/ct_actions_tree.cc:24:
In file included from /Users/randomuser/tools/cherrytree/src/ct/ct_actions.h:26:
In file included from /Users/randomuser/tools/cherrytree/src/ct/ct_dialogs.h:26:
In file included from /Users/randomuser/tools/cherrytree/src/ct/ct_misc_utils.h:26:
/Users/randomuser/tools/cherrytree/src/ct/ct_types.h:30:10: fatal error: 'glibmm/ustring.h' file not found
#include <glibmm/ustring.h>
         ^~~~~~~~~~~~~~~~~~
In file included from /Users/randomuser/tools/cherrytree/src/ct/ct_actions_view.cc:24:
In file included from /Users/randomuser/tools/cherrytree/src/ct/ct_actions.h:26:
In file included from /Users/randomuser/tools/cherrytree/src/ct/ct_dialogs.h:26:
In file included from /Users/randomuser/tools/cherrytree/src/ct/ct_misc_utils.h:26:
/Users/randomuser/tools/cherrytree/src/ct/ct_types.h:30:10: fatal error: 'glibmm/ustring.h' file not found
#include <glibmm/ustring.h>
         ^~~~~~~~~~~~~~~~~~
In file included from /Users/randomuser/tools/cherrytree/src/ct/ct_actions_export.cc:24:
In file included from /Users/randomuser/tools/cherrytree/src/ct/ct_actions.h:26:
In file included from /Users/randomuser/tools/cherrytree/src/ct/ct_dialogs.h:26:
In file included from /Users/randomuser/tools/cherrytree/src/ct/ct_misc_utils.h:26:
/Users/randomuser/tools/cherrytree/src/ct/ct_types.h:30:10: fatal error: 'glibmm/ustring.h' file not found
#include <glibmm/ustring.h>
         ^~~~~~~~~~~~~~~~~~
In file included from /Users/randomuser/tools/cherrytree/src/ct/ct_actions_format.cc:24:
In file included from /Users/randomuser/tools/cherrytree/src/ct/ct_actions.h:26:
In file included from /Users/randomuser/tools/cherrytree/src/ct/ct_dialogs.h:26:
In file included from /Users/randomuser/tools/cherrytree/src/ct/ct_misc_utils.h:26:
/Users/randomuser/tools/cherrytree/src/ct/ct_types.h:30:10: fatal error: 'glibmm/ustring.h' file not found
#include <glibmm/ustring.h>
         ^~~~~~~~~~~~~~~~~~
In file included from /Users/randomuser/tools/cherrytree/src/ct/ct_actions_file.cc:24:
In file included from /Users/randomuser/tools/cherrytree/src/ct/ct_actions.h:26:
In file included from /Users/randomuser/tools/cherrytree/src/ct/ct_dialogs.h:26:
In file included from /Users/randomuser/tools/cherrytree/src/ct/ct_misc_utils.h:26:
/Users/randomuser/tools/cherrytree/src/ct/ct_types.h:30:10: fatal error: 'glibmm/ustring.h' file not found
#include <glibmm/ustring.h>
         ^~~~~~~~~~~~~~~~~~
In file included from /Users/randomuser/tools/cherrytree/src/ct/ct_actions_edit.cc:24:
In file included from /Users/randomuser/tools/cherrytree/src/ct/ct_actions.h:26:
In file included from /Users/randomuser/tools/cherrytree/src/ct/ct_dialogs.h:26:
In file included from /Users/randomuser/tools/cherrytree/src/ct/ct_misc_utils.h:26:
/Users/randomuser/tools/cherrytree/src/ct/ct_types.h:30:10: fatal error: 'glibmm/ustring.h' file not found
#include <glibmm/ustring.h>
         ^~~~~~~~~~~~~~~~~~
In file included from /Users/randomuser/tools/cherrytree/src/ct/ct_actions_find.cc:24:
In file included from /Users/randomuser/tools/cherrytree/src/ct/ct_actions.h:26:
In file included from /Users/randomuser/tools/cherrytree/src/ct/ct_dialogs.h:26:
In file included from /Users/randomuser/tools/cherrytree/src/ct/ct_misc_utils.h:26:
/Users/randomuser/tools/cherrytree/src/ct/ct_types.h:30:10: fatal error: 'glibmm/ustring.h' file not found
#include <glibmm/ustring.h>
         ^~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [src/ct/CMakeFiles/cherrytree_shared.dir/ct_config.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
1 error generated.
1 error generated.
make[2]: *** [src/ct/CMakeFiles/cherrytree_shared.dir/ct_export2html.cc.o] Error 1
make[2]: *** [src/ct/CMakeFiles/cherrytree_shared.dir/ct_codebox.cc.o] Error 1
1 error generated.
make[2]: *** [src/ct/CMakeFiles/cherrytree_shared.dir/ct_app.cc.o] Error 1
1 error generated.
1 error generated.
1 error generated.
1 error generated.
1 error generated.
1 error generated.
make[2]: *** [src/ct/CMakeFiles/cherrytree_shared.dir/ct_actions_file.cc.o] Error 1
1 error generated.
make[2]: *** [src/ct/CMakeFiles/cherrytree_shared.dir/ct_actions_help.cc.o] Error 1
1 error generated.
make[2]: *** [src/ct/CMakeFiles/cherrytree_shared.dir/ct_actions_view.cc.o] Error 1
make[2]: *** [src/ct/CMakeFiles/cherrytree_shared.dir/ct_clipboard.cc.o] Error 1
make[2]: *** [src/ct/CMakeFiles/cherrytree_shared.dir/ct_actions_export.cc.o] Error 1
1 error generated.
make[2]: *** [src/ct/CMakeFiles/cherrytree_shared.dir/ct_dialogs.cc.o] Error 1
make[2]: *** [src/ct/CMakeFiles/cherrytree_shared.dir/ct_actions_tree.cc.o] Error 1
make[2]: *** [src/ct/CMakeFiles/cherrytree_shared.dir/ct_actions_format.cc.o] Error 1
1 error generated.
make[2]: *** [src/ct/CMakeFiles/cherrytree_shared.dir/ct_actions_others.cc.o] Error 1
make[2]: *** [src/ct/CMakeFiles/cherrytree_shared.dir/ct_actions_edit.cc.o] Error 1
1 error generated.
make[2]: *** [src/ct/CMakeFiles/cherrytree_shared.dir/ct_actions_import.cc.o] Error 1
1 error generated.
make[2]: *** [src/ct/CMakeFiles/cherrytree_shared.dir/ct_actions_find.cc.o] Error 1
make[1]: *** [src/ct/CMakeFiles/cherrytree_shared.dir/all] Error 2
make: *** [all] Error 2`

**Comment by IamCrypt0n** [comment]
Did you solve it? Im having this problem atm

**Comment by giuspen** [comment]
can you try:
`brew install giomm-2.4 gtkmm3 gtksourceviewmm3`
and build again?

**Comment by IamCrypt0n** [comment]
Running the  command gives following output:
`==> Searching for similarly named formulae...
Error: No similarly named formulae found.
Error: No available formula or cask with the name "giomm-2.4".
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.`

Bulding afterwards results in the same errror:
`ld: warning: directory not found for option '-L/usr/local/opt/gettext/lib'
ld: library not found for -lgtkmm-3.0
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [cherrytree] Error 1
make[1]: *** [src/ct/CMakeFiles/cherrytree.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
1 warning generated.
1 warning generated.
[100%] Linking CXX executable ../run_tests
ld: warning: directory not found for option '-L/usr/local/opt/gettext/lib'
ld: library not found for -lgtkmm-3.0
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [run_tests] Error 1
make[1]: *** [tests/CMakeFiles/run_tests.dir/all] Error 2
make: *** [all] Error 2`

Greetings

**Comment by giuspen** [comment]
I think this can be closed now, cherrytree is even available as a binary in homebrew
