### ISSUE TITLE
Breadcrumbs in the Node Name Header

### ISSUE THREAD

**Issue by dalexeev** [giuspen/cherrytree#1399]
**Is your feature request related to a problem? Please describe.**
For example, if the nested nodes of different branches have the same name, then looking at the sidebar is required to determine the exact path.

**Describe the solution you'd like**
Add a setting that allows you to see the full path to the current node in the header (for example, **Notes / 2020 / December**), and not just the last name (**December**).

**Comment by janthird** [comment]
I second this request and would add a feature to allow the font size or tab size on the breadcrumb tabs to set in preferences.  I use a fairly large font and the breadcrumbs show the first three letter and then three dots.

**Comment by giuspen** [comment]
OK will be in 0.99.37. I also reduced the size of the font so maybe won't be necessary to make it configurable.
