### ISSUE TITLE
[bug] Spell-check language selection not working (but ok from menu)

### ISSUE THREAD

**Issue by userfav** [giuspen/cherrytree#1400]
**Version, Operative system**

CT ver. 0.99.24 / Windows 10 x64 / portable mode

**Describe the bug**

Spell-check Language selection (from the "Preferences" window) doesn't have effect on the editor, but selecting the language manually from the right click menu works ok.

**To Reproduce**

Write some spanish words on the editor:

![imagen](https://user-images.githubusercontent.com/46328784/101206596-1c97ee00-364e-11eb-8759-70851e47406f.png)

Now enable the Spell-check and set the language on "Spanish (Castillian)":

![imagen](https://user-images.githubusercontent.com/46328784/101206722-481ad880-364e-11eb-809c-a277219ca467.png)

On the editor, the spell-check will notify with the red underline that the words are not Spanish ones (which is wrong):

![imagen](https://user-images.githubusercontent.com/46328784/101206807-6f71a580-364e-11eb-964f-323e8cff5bee.png)

but that's because it's still selected the english language, as can be seen using the right menu:

![imagen](https://user-images.githubusercontent.com/46328784/101207060-d1caa600-364e-11eb-9173-ea4e45251e69.png)

If I select the spanish language on this menu, the spell-check works correctly:

![imagen](https://user-images.githubusercontent.com/46328784/101207195-05a5cb80-364f-11eb-9f9e-f900c17e328c.png)

**Comment by giuspen** [comment]
thanks will be ok in 0.99.25
