### ISSUE TITLE
Tooltips missing on the Bookmarks window

### ISSUE THREAD

**Issue by userfav** [giuspen/cherrytree#1403]
**Version, Operative system**
Ct. v. 0.99.24 / Windows 10 x64

**Describe the bug**

Tooltips are missing from the buttons of the Bookmarks window.

![imagen](https://user-images.githubusercontent.com/46328784/101262889-87195e80-3720-11eb-9701-017179c5a18a.png)

**Comment by giuspen** [comment]
thanks, added for 0.99.25
