### ISSUE TITLE
install on macos

### ISSUE THREAD

**Issue by xjxyxgq** [giuspen/cherrytree#1405]
**Version, Operative system**
macos 10.14.2

**Describe the bug**
I can't make install.

Unless the following code is commented out in `cherrytree/tests/tests_misc_utils.cpp`:

~~~
// test doesn't work on WIN32 and MacOS (Travis)
#if !(defined(_WIN32) || (defined(_TRAVIS) && defined(__APPLE__)))
    ASSERT_TRUE(CtMiscUtil::mime_type_contains(UT::unitTestsDataDir+"/mimetype_cpp.cpp", "text/"));
#endif
~~~

**Comment by giuspen** [comment]
can you try the latest from git?
