### ISSUE TITLE
Icon theme update?

### ISSUE THREAD

**Issue by userfav** [giuspen/cherrytree#1408]
I was thinking some days ago about updating the CT icons. So I cloned the repository and I saw that CT use a manageable quantity of icons. Also I saw that most of the non-original icons were pretty similar to the current set of elementary-OS icons.

So I updated the CT icons using the actual elementary icon-set when it was possible and this is the result:

![refresh](https://user-images.githubusercontent.com/46328784/101388377-9faf8300-389e-11eb-9baa-b301bb15f2ae.png)

This is the actual icon-set:

![original](https://user-images.githubusercontent.com/46328784/101388408-aa6a1800-389e-11eb-80e0-28cc750577ca.png)

Here I upload a picture with a comparison between the menus with this set of icons and the actual ones after compile CT using them (thanks for the instructions) in case that you don't want to compile CT to figure it out how it will looks:  [https://imgbox.com/ZLS5ZZ7q](url) (copy the link in a new tab if doesn't work)

Some notes about this set:

- All are SVGs.
- When possible, I used the elementary icons but trying to not break too much the current use case as you can see.
- Tried to use the 48 px size (even if that is not convenient because in CT most icons are seen in 16 px)
- When I redraw something, tried to follow the actual set, but the coloring following the elementary guidelines.
- All icons where modifications of the elementary set, modifications of the actual ones, or I re-drew it from scratch by myself, so there wasn't another source) 
- I didn't touch the original cherries icons (except the little ones, to simplify them for better looking when the icon is small)

Here are the icons, hope you like, cheers:

[icons_refresh_2020-12-07.zip](https://github.com/giuspen/cherrytree/files/5654529/icons_refresh_2020-12-07.zip)

Preview: 

![imagen](https://user-images.githubusercontent.com/46328784/101393720-48adac00-38a6-11eb-8150-1d007c1e5a73.png)

**Comment by giuspen** [comment]
Nice work I'll have a look :)

**Comment by giuspen** [comment]
Can I use your icons and credit you in the about dialog? If yes with or without your email?

**Comment by userfav** [comment]
Of course, glad you like! If you see some problem with an icon or want to add a new one let me know and I will check it out.
About the credit, just  with "Ugo Yak" will be fine (that's an alias that I use when I do [graphic stuff](https://www.instagram.com/ugoyak.art/))

**Comment by giuspen** [comment]
Thanks Ugo 😉
