### ISSUE TITLE
goto ... Previous/Next node ... from keyboard not work (ALT-Left ... ALT-Right)

### ISSUE THREAD

**Issue by rvboyd** [giuspen/cherrytree#1412]
CherryTree v 0.99.25 on Pop!_OS 20.10 (i.e., Ubuntu 20.10)

Arrow Icons for going to Previous or Next node work OK ... but ALT-Left and ALT-Right keyboard shortcuts no longer work.

**Comment by giuspen** [comment]
should be ok in 0.99.26
