### ISSUE TITLE
Insert/Edit Link via Ctrl-L no longer returns to location of LAST Inserted Link

### ISSUE THREAD

**Issue by rvboyd** [giuspen/cherrytree#1413]
CherryTree v 0.99.25 on Pop!_OS v20.10 (i.e., Ubuntu v20.10)

Ctrl-L to Insert/Edit Link NO LONGER goes to LOCATION of LAST inserted link. Constantly returns to default position of "To Website". 
98% of time I want to link to another Node (often near last inserted link) ... but keeps going back to Website ... and I lose location within the Node Tree.
Is there some way to configure this back to old behaviour?

**Comment by giuspen** [comment]
Will be ok in upcoming 0.99.30
