### ISSUE TITLE
Spanish translation update

### ISSUE THREAD

**Issue by userfav** [giuspen/cherrytree#1415]
I include here the spanish missing translations for the new tooltips added on 0.99.25

**New:**

Move the Selected Bookmark Up > Mover arriba el marcador seleccionado
Move the Selected Bookmark Down > Mover abajo el Marcador seleccionado
Remove the Selected Bookmark > Quitar el marcador seleccionado
Sort the Bookmarks Descending > Ordenar marcadores de forma descendente
Sort the Bookmarks Ascending > Ordenar marcadores de forma ascendente

**Corrections to existent translations:**

(string id 358) _Increase Toolbar Icons Size > Aumen_tar iconos de la barra de herramientas
(string id 360) _Decrease Toolbar Icons Size > _Reducir iconos de la barra de herramientas

**Comment by giuspen** [comment]
@userfav I'm going to send an email to the translators with the new files shortly, is it ok to send it to you too?

**Comment by userfav** [comment]
@giuspen Fine by me, thanks
