### ISSUE TITLE
Editing a table increases RAM usage

### ISSUE THREAD

**Issue by dardoor** [giuspen/cherrytree#1416]
**Version, Operative system**
CherryTree 0.99.25, Windows 7 and Windows 10

**Describe the bug**
When editing a table's properties, columns or rows, the memory (RAM) usage grows with every operation.

**To Reproduce**
1. Insert Table
2. Increase Column Width (Ctrl+.), Decrease Column Width (Ctrl+Alt+.)
3. Repeat 2 several times.

The same happens also if you add or remove columns or rows. Every time there's a "redrawing" of the UI the memory usage of chertytree.exe goes up. Over time it can get pretty high.

**Comment by giuspen** [comment]
I'm going to rework the tables soon, I'm aware the performance is very bad at the moment

**Comment by giuspen** [comment]
fixed in upcoming 0.99.28
