### ISSUE TITLE
Table: Ctrl+, keyboard shortcut only works once

### ISSUE THREAD

**Issue by dardoor** [giuspen/cherrytree#1417]
**Version, Operative system**
CherryTree 0.99.25, Windows 7 and Windows 10

**Describe the bug**
Pressing Ctrl+, (add row) or Ctrl+Alt+, (delete row) only works once, until the context menu is invoked again.

**To Reproduce**
1. Press Ctrl+, to add a row.
2. Press Ctrl+, again to add another one.
Only one row gets added, the second command doesn't work.
3. Open the context menu (mouse R-click or keyboard Menu button).
4. Press Ctrl+, to add a row.
Now it works again, one time.

**Comment by giuspen** [comment]
I'll fix this thanks

**Comment by giuspen** [comment]
Will be ok in 0.99.26
