### ISSUE TITLE
Pasted Chinese Characters

### ISSUE THREAD

**Issue by ventolinmono** [giuspen/cherrytree#1418]
Sometimes when I copy western latin characters and paste them into CherryTree it gets pasted as chinese characters. I'm using CherryTree 0.39.4 on Debian 10.

**Comment by giuspen** [comment]
Please upgrade to 0.99.x via flatpak https://flathub.org/apps/details/com.giuspen.cherrytree

**Comment by ciranus** [comment]
@ventolinmono 
Also check that you have these fonts installed: `fonts-unifont xfonts-unifont`

**Comment by ciranus** [comment]
@ventolinmono 
Solved with 0.99.x or not ?
I got this problem long time ago with 0.39, and hardly understood it (never came to clear conclusion).

**Comment by ventolinmono** [comment]
Haven't had this problem on 0.99.25.

**Comment by giuspen** [comment]
closing then, thanks
