### ISSUE TITLE
language does't change

### ISSUE THREAD

**Issue by Kurwa228** [giuspen/cherrytree#1422]
**Version, Operative system**
Cherrytree 0.99.25
Arch Linux x86_64 5.9.12-arch1-1 GNOME 3.38.2 Mutter Wayland Adwaita
Install with AUR-helper yay https://aur.archlinux.org/pkgbase/cherrytree/

**Describe the bug**
If I change to any language in the settings, English is saved

**To Reproduce**
1. go to 'Preferences' Ctrl+alt+P
2. Click on 'miscellaneous'
3. Click and choose any 'Language'
4. Restart
5. English is saved

**Screenshots**
![Снимок экрана от 2020-12-12 13-40-57](https://user-images.githubusercontent.com/14250372/101981716-ef67c300-3c7f-11eb-8f8c-353ed715e51d.png)

terminal log:
```
** Message: 13:43:46.793: Language overwrite = en (localedir = /home/vv/.cache/yay/cherrytree/src/cherrytree-0.99.25/po)

(process:28381): Gtk-WARNING **: 13:43:46.795: Locale not supported by C library.
	Using the fallback 'C' locale.
[2020-12-12 13:43:46.833] [   ] [debug] /home/vv/.config/cherrytree/config.cfg parsed
[2020-12-12 13:43:46.833] [gtk] [critical] gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
[2020-12-12 13:43:46.869] [   ] [debug] autosave is started
[2020-12-12 13:43:46.913] [gtk] [warning] Error loading plugin: libaspell.so.15: cannot open shared object file: No such file or directory

[2020-12-12 13:43:46.913] [gtk] [warning] Error loading plugin: libvoikko.so.1: cannot open shared object file: No such file or directory

[2020-12-12 13:43:46.914] [gtk] [warning] Error loading plugin: libhspell.so.0: cannot open shared object file: No such file or directory

[2020-12-12 13:43:46.914] [gtk] [warning] Error loading plugin: libnuspell.so.4: cannot open shared object file: No such file or directory

[2020-12-12 13:43:46.915] [gtk] [warning] Error loading plugin: libaspell.so.15: cannot open shared object file: No such file or directory

[2020-12-12 13:43:46.915] [gtk] [warning] Error loading plugin: libvoikko.so.1: cannot open shared object file: No such file or directory

[2020-12-12 13:43:46.915] [gtk] [warning] Error loading plugin: libhspell.so.0: cannot open shared object file: No such file or directory

[2020-12-12 13:43:46.915] [gtk] [warning] Error loading plugin: libnuspell.so.4: cannot open shared object file: No such file or directory

```
It's work same with ja, ru, de etc
And change language worked in version 0.99.24

**Comment by giuspen** [comment]
are you building from sources or using the package from the repo? It looks like you don't have gspell installed

**Comment by ciranus** [comment]
`libgspell` should normally be installed because a dependency of CT package (at least for .deb / tbc for Arch)
But this is just a spell-checker.

@ Kurwa228 
> It's work same with ja, ru, de etc
> And change language worked in version 0.99.24

![ksnip_20201214-231515](https://user-images.githubusercontent.com/61602511/102142759-38c43800-3e63-11eb-9238-64b46bf3e147.png)

This is weird.
CT language configuration is stored at 
`~/.config/cherrytree/lang`

And are your system locales correctly configured for ja, ru, de etc

```
localectl list-locales
sudo dpkg-reconfigure locales
```

**Comment by Kurwa228** [comment]
> are you building from sources or using the package from the repo? It looks like you don't have gspell installed

`sudo pacman -Q gspell`
`gspell 1.8.4-1`

**Comment by Kurwa228** [comment]
> @ Kurwa228
> 
> > It's work same with ja, ru, de etc
> > And change language worked in version 0.99.24
> 
> ![ksnip_20201214-231515](https://user-images.githubusercontent.com/61602511/102142759-38c43800-3e63-11eb-9238-64b46bf3e147.png)
> 
> This is weird. CT language configuration is stored at `~/.config/cherrytree/lang`
> 
> And are your [system locales](https://wiki.archlinux.org/index.php/Locale) correctly configured for ja, ru, de etc ?
> Not convinced it has any effect on CT, but better check.

Files `~/.cache/yay/cherrytree/scr/cherrytree-0.99.25/po` looks like 

![Снимок экрана от 2020-12-15 15-24-03](https://user-images.githubusercontent.com/14250372/102214745-ce0a0f80-3ee9-11eb-911d-1b84889d7d54.png)

File `~/.config/cherrytree/lang`

![Снимок экрана от 2020-12-15 15-27-17](https://user-images.githubusercontent.com/14250372/102215033-2e00b600-3eea-11eb-81d9-cf5e7db353da.png)

System locales:
`locale -a`
```
C
en_US.utf8
POSIX
ru_RU.utf8
```

I ran `env LANG=ru_RU.UTF-8 cherrytree &`

```
vv@gaycom ~> ** Message: 15:31:27.737: Language overwrite = ru (localedir = /home/vv/.cache/yay/cherrytree/src/cherrytree-0.99.25/po)
(process:25505): Gtk-WARNING **: 15:31:27.739: Locale not supported by C library.
	Using the fallback 'C' locale.
[2020-12-15 15:31:27.771] [   ] [debug] /home/vv/.config/cherrytree/config.cfg parsed
[2020-12-15 15:31:27.771] [gtk] [critical] gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
[2020-12-15 15:31:27.861] [   ] [debug] autosave is started
[2020-12-15 15:31:27.904] [gtk] [warning] Error loading plugin: libaspell.so.15: невозможно открыть разделяемый объектный файл: Нет такого файла или каталога
```


and `env LANG=en_US.UTF-8 cherrytree &` 

```
vv@gaycom ~> ** Message: 15:38:19.810: Language overwrite = ru (localedir = /home/vv/.cache/yay/cherrytree/src/cherrytree-0.99.25/po)
(process:26119): Gtk-WARNING **: 15:38:19.811: Locale not supported by C library.
	Using the fallback 'C' locale.
[2020-12-15 15:38:19.853] [   ] [debug] /home/vv/.config/cherrytree/config.cfg parsed
[2020-12-15 15:38:19.853] [gtk] [critical] gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
[2020-12-15 15:38:19.887] [   ] [debug] autosave is started
[2020-12-15 15:38:19.939] [gtk] [warning] Error loading plugin: libaspell.so.15: невозможно открыть разделяемый объектный файл: Нет такого файла или каталога
```

My default locale is ru_RU.UTF-8 but same error work for all language

And I change language in Preference to en, file `~/.config/cherrytree/lang` was overwritten to en and run in terminal with env. Same error. 

My `locale`

```
LANG=ru_RU.UTF-8
LC_CTYPE="ru_RU.UTF-8"
LC_NUMERIC="ru_RU.UTF-8"
LC_TIME="ru_RU.UTF-8"
LC_COLLATE="ru_RU.UTF-8"
LC_MONETARY="ru_RU.UTF-8"
LC_MESSAGES="ru_RU.UTF-8"
LC_PAPER="ru_RU.UTF-8"
LC_NAME="ru_RU.UTF-8"
LC_ADDRESS="ru_RU.UTF-8"
LC_TELEPHONE="ru_RU.UTF-8"
LC_MEASUREMENT="ru_RU.UTF-8"
LC_IDENTIFICATION="ru_RU.UTF-8"
LC_ALL=
```


My `env`

```
COLORTERM=truecolor
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
DESKTOP_SESSION=gnome
DISPLAY=:0
GDMSESSION=gnome
GDM_LANG=ru_RU.UTF-8
GNOME_SETUP_DISPLAY=:1
GNOME_TERMINAL_SCREEN=/org/gnome/Terminal/screen/01520ff3_fa61_4737_b862_bc7438c451d2
GNOME_TERMINAL_SERVICE=:1.109
HOME=/home/vv
LANG=ru_RU.UTF-8
LOGNAME=vv
MAIL=/var/spool/mail/vv
MOTD_SHOWN=pam
PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
PWD=/home/vv
SESSION_MANAGER=local/gaycom:@/tmp/.ICE-unix/967,unix/gaycom:/tmp/.ICE-unix/967
SHELL=/usr/bin/fish
SHLVL=2
SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
TERM=xterm-256color
USER=vv
USERNAME=vv
VTE_VERSION=6201
WAYLAND_DISPLAY=wayland-0
XAUTHORITY=/run/user/1000/.mutter-Xwaylandauth.YSHVV0
XDG_CURRENT_DESKTOP=GNOME
XDG_DATA_DIRS=/home/vv/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
XDG_MENU_PREFIX=gnome-
XDG_RUNTIME_DIR=/run/user/1000
XDG_SESSION_CLASS=user
XDG_SESSION_DESKTOP=gnome
XDG_SESSION_TYPE=wayland
```

I checked locale-conf and locale-gen all is well
Other gtk packages like transmission-gtk, nautilus and gnome-terminal doesn't give error

**Comment by giuspen** [comment]
I think I understood what is causing it, you basically have built the package locally to /home/vv/.cache/yay/cherrytree/src/cherrytree-0.99.25 or this AUR helper yay has. Cherrytree is running for you in developer debug mode using local build directory rather than installed and some binaries may no longer be there, may have been moved. I'll sort this out but in the meantime if you remove /home/vv/.cache/yay/cherrytree/src/cherrytree-0.99.25 should get back to work

**Comment by giuspen** [comment]
Also can you locate where the file cherrytree was installed on your system?

**Comment by giuspen** [comment]
The binary file, e.g. "find / -name cherrytree"

**Comment by Kurwa228** [comment]
> Can you tell me if you have subfolders in home/vv/.cache/yay/cherrytree/src/cherrytree-0.99.25/po ?
No

> The binary file, e.g. "find / -name cherrytree"
```
/home/vv/.cache/yay/cherrytree
/home/vv/.cache/yay/cherrytree/src/cherrytree-0.99.25/pygtk2/cherrytree
/home/vv/.config/cherrytree
/usr/bin/cherrytree
/usr/share/cherrytree
```



> ...I'll sort this out but in the meantime if you remove /home/vv/.cache/yay/cherrytree/src/cherrytree-0.99.25 should get back to work
Yes ! It's works, thank u !
