### ISSUE TITLE
Non-ASCII characters not recognized in directory names on Linux

### ISSUE THREAD

**Issue by Christian-V** [giuspen/cherrytree#1423]
CherryTree 0.99.25 on Linux Mint 20 Mate.

Certain Unicode characters (probably all non ASCII characters, I obviously did not do the complete test!) prevent links to directories from being opened, without causing an error message.

For example, clicking on links to directories (ch being my username) :
/home/ch/Documents/Testé
or
/home/ch /Documents/Test¤
has no effect.

On the other hand, the links of the same name function normally if Testé and Test¤ are ordinary files.

**Comment by giuspen** [comment]
Can you check in the preferences dialog that you don't have a custom action for directory clicked?

**Comment by Christian-V** [comment]
I did not touch the options of the links and there is for the opening of the directories (in gray):
xdg-open% s &
(as for files).

I tried to allow relative links and  Documents/Testé/  does not respond while  Documents/  opens.

On the other hand I found strangely in  /home/ch/.config/cherrytree/config.cfg :
[...]
pick_dir_import =/home/ch
pick_dir_export =/home/ch
pick_dir_file =/home/ch/Documents/Connaissances, sciences/Mathématiques
pick_dir_img =/home/ch/Office
pick_dir_csv =/home/ch
pick_dir_cbox =/home/ch
link_type = file
[...]

"Mathematics" is the directory on which I initially found the fault, but it is not the most recently opened.
I deleted this value and finally CherryTree put me:
pick_dir_file =/home/ch
but that doesn't change anything.

I also tried to replace the language fr with en without change.

**Comment by ciranus** [comment]
Can you show this:
`localectl list-locales`

**Comment by giuspen** [comment]
Do you have the cherrytree ppa / you installed the .deb package or the flatpak?

**Comment by Christian-V** [comment]
So when I put "default" as the language, it works! Thank you ciranus.
And in addition my interface is always in French.
I didn't believe it much because it seemed to me that the processing of file paths should not depend on the choice of language.

For all intents and purposes, I still answer the other questions:

localectl list-locales => (summarizing on one line):
C.UTF-8, en_AG.UTF-8 en_AU.UTF-8 en_BW.UTF-8 en_CA.UTF-8 en_DK.UTF-8 en_GB.UTF-8 en_HK.UTF-8 en_IE.UTF-8 en_IL.UTF- 8 en_IN.UTF-8 en_NG.UTF-8 en_NZ.UTF-8 en_PH.UTF-8 en_SG.UTF-8 en_US.UTF-8 en_ZA.UTF-8 en_ZM.UTF-8 en_ZW.UTF-8 en_BE.UTF- 8 fr_CA.UTF-8 fr_CH.UTF-8 fr_FR.UTF-8 fr_LU.UTF-8

egrep -v '(# | ^ $)' /etc/locale.gen
en_US.UTF-8 UTF-8
fr_FR.UTF-8 UTF-8

xdg-mime query default inode / directory
/ usr / bin / xdg-mime: 957: local: --no-desktop-1.desktop: bad variable name

I have the giuspen PPA and I am not using flatpak. CherryTree is updated by the mintUpdate update manager. And previously I only used .deb.

I don't know enough about programming to properly analyze the indicated program.
I do not see where it would depend on the choice of language.

I wait a bit in case there are any further comments and I will close the issue.

**Comment by ciranus** [comment]
Please don't add extra spaces in commands. Space is a character. Just copy/paste the required commands.
'inod**e/d**irectory' is not same as 'inod**e / d**irectory'

1 - You don't need all these locales. You can reconfigure your locales and keep  **fr_FR.UTF-8** only.
`sudo dpkg-reconfigure locales`

> xdg-mime query default inode / directory
> / usr / bin / xdg-mime: 957: local: --no-desktop-1.desktop: bad variable name

2 - Try again with the command I gave you:
`xdg-mime query default inode/directory`

**Comment by ciranus** [comment]
@giuspen 
Do you understand why lang setting to **default** does not give the same result as **fr** in a fr_FR.UTF-8 locale environment ?

And I have noticed that drag&drop of `/tmp/Testé` directory from Dolphin to CT will create `file:///tmp/TestÃ©` (in a KDE desktop).
Probably something to be fine-tuned.

**Comment by Christian-V** [comment]
Sorry, regarding the order:
xdg-mime query default inode/directory
it's a misunderstanding ; in fact I had made the correct order, but the Google translator added spaces and I did not think of removing them in my answer. In fact :
xdg-mime query default inode/directory
/usr/bin/xdg-mime: 957: local: --no-desktop-1.desktop: bad variable name

Regarding the installed language packs, if I do:
sudo dpkg-reconfigure locales
if I check (with a star) that r_FR.UTF-8 UTF-8, put the cursor on this line and validate, it does not change anything.
On the other hand, in the Languages ​​section of my Control Center I deleted all the variants of English (all incomplete) and French (complete but useless) except "French, France". Now I have :

localectl list-locales
C.UTF-8
fr_FR.UTF-8

egrep -v '(#|^$)' /etc/locale.gen
fr_FR.UTF-8 UTF-8

But this change nothing in CherryTree.

I understand that the choice of language in CherryTree changes some characteristics (especially the menus).
But it seems to me that the paths of directories (or files, in principle it is the same under Unix) encoded in UTF-8 do not change.
By the way in the link edition, the path is the same whether I do a copy and paste or a search with the gadget and is displayed correctly even if I change the language.
We would have to see why everything works for files and not for directories.

**Comment by ciranus** [comment]
I am a bit surprised if nothing has been defined to 'xdg-open' a directory.
Can you try this command ?

`grep 'directory=' ~/.config/mimeapps.list`

**Comment by giuspen** [comment]
@ciranus I'm not sure but will try something

**Comment by Christian-V** [comment]
```
grep 'directory=' ~/.config/mimeapps.list
inode/directory=Caja --no-desktop-1.desktop
inode/directory=Viewnior.desktop;XnView Multi Platform.desktop;Xed.desktop;
```
`xdg-open ~/`  works and even `xdg-open ~/Documents/Testé`
They open the the specified directory in Caja.

**Comment by ciranus** [comment]
Ok. I did not know Caja as a file-manager.

There is something wrong with '--no-desktop-1.desktop' option, but if it works, forget it.

/usr/bin/xdg-mime: 957: local: **--no-desktop-1.desktop: bad variable name**

**Comment by Christian-V** [comment]
grep 'directory=' ~/.config/mimeapps.list
inode/directory=Caja --no-desktop-1.desktop
inode/directory=Viewnior.desktop;XnView Multi Platform.desktop;Xed.desktop;

xdg-open ~/ works and even xdg-open ~/Documents/Testé
They open the the specified directory in Caja

Caja is the Mate fork of Nautilus, file manager of Gnome.
The Caja file --no-desktop-1.desktop is a desktop file located at ~/.local/share/applications/
"--no-desktop" is an option of Caja which says not to manage the icons of the wallpaper and does not actually make a difference, a copy of Caja which manages the desktop being anyway already started on startup. .
"-1" is typical when a desktop file is duplicated.
I don't know what doesn't appeal to xdg-open about this name. In this desktop, there is: Name [fr_FR] = Caja --no-desktop
Maybe this is a naming inconsistency for xdg-open as used by CherryTree with fr language ? In any case it works everywhere else.

I don't really want to touch this statement, which may disrupt the opening of directories in some cases.
Besides, since it works in CherryTree with the "default" language, there is no reason.
I shall wait and see ...

**Comment by ciranus** [comment]
Yes don't worry with your Caja, although something is not clean in your system, just to be aware.
This is what I see in **caja-folder-handler.desktop** which should be used as inode/directory application:

```
Name=Caja
GenericName[fr]=Ouvrir un dossier
GenericName=Open Folder
TryExec=/usr/bin/caja
Exec=/usr/bin/caja --no-desktop %U
Icon=folder-open
```

I have never seen capital letters used for application names in mimeapps.list, like "**C**aja", not any '--xyz' options.
I am quite convinced what is correct in mimeapps.list is this:

`inode/directory=caja-folder-handler.desktop`
instead of
`inode/directory=Caja --no-desktop-1.desktop`

But not a CT investigation, and when it works... it works.

**Comment by Christian-V** [comment]
Indeed the "real names" of the desktop files (as listed by the terminal) under "/usr/share/applications" rarely have a capital letter (which does not have much significance, it is a simple use).
But it is different for "visible" names (for example in Caja) which are declared in the desktop file or under "/home/ch/.local/share/applications", where the names are dependent on modifications of the general menu or of the creation of launchers.
For Caja, it's already complicated, and even more so in my case with all the operations done on the menus or launchers. In addition, the Mozo menu editor has long been bugged.

To see, I still replaced as you suggest in "~/.config/mimeapps.list":
inode/directory = Caja --no-desktop-1.desktop
by
inode/directory = caja-folder-handler.desktop

It apparently doesn't change anything in the way it works or in the context menu of the directory icons and even in "Other applications" for the choices "Caja and" Caja --no-desktop ".
By contrast:
```
xdg-mime query default inode/directory
caja-folder-handler.desktop
```
It is indeed cleaner ... but **that does not change CherryTree's problem with the languages ​​fr or en ... or zh_CN (tested just to see). He is therefore elsewhere.**

**Comment by ciranus** [comment]
> I replaced as you suggested in "~/.config/mimeapps.list":
> inode/directory = Caja --no-desktop-1.desktop
> by
> inode/directory = caja-folder-handler.desktop
> 
> It apparently doesn't change anything 

Because your mime was wrong and rejected at **user** level. The default mime declared at **system** level was probably used.


> ```
> xdg-mime query default inode/directory
> caja-folder-handler.desktop
> ```
> 
> It is indeed **cleaner** ... but that does not change CherryTree's problem

As I said ! Then easier to investigate future problems with a clean system.

**Comment by giuspen** [comment]
I was able to reproduce, so I'm confident it will be OK in upcoming 0.99.26
