### ISSUE TITLE
Icon theme: going 16px?

### ISSUE THREAD

**Issue by userfav** [giuspen/cherrytree#1426]
This is something that I was thinking about it when I started to replace some icons of the theme.

Nowadays, CT uses svg on all icons, and mostly on a dimension of 48x48 px.

48 px is a good dimension for good detailed icons, but regrettably they have a problem when they are downscalated: the icon start to look blurry. 

Example, this is a "48 px" drawing downscalated: 
![imagen](https://user-images.githubusercontent.com/46328784/102018078-a8de9b00-3d49-11eb-8e17-c6fd02cb806a.png)

And this is the same icon but redrawed to look good on 16 px:
![imagen](https://user-images.githubusercontent.com/46328784/102018137-14286d00-3d4a-11eb-8f9e-53d8db0a27b6.png)

The 16 px one, upscaled look simpler but in the original size for what intended (the little top box, the 16 px one) looks more sharp and clear.

That's the reason that mostly of the programs even if they work with svg icons they use a icon for each specific size.

Now I'm not suggesting here to have multiple icons for each size, but that maybe is better to "downscale" the icons that CT manages to match his default, that is, 16 px.

I search the equivalents and re-draw the missing. Here I show a comparison between the actual icon set, and one on 16px:

![imagen](https://user-images.githubusercontent.com/46328784/102018294-38387e00-3d4b-11eb-8070-e2e058ceb6d2.png)
![imagen](https://user-images.githubusercontent.com/46328784/102018327-5ef6b480-3d4b-11eb-9a97-b8ef2cd0bc29.png)

![imagen](https://user-images.githubusercontent.com/46328784/102018505-5652ae00-3d4c-11eb-8481-5fd508238301.png)
![imagen](https://user-images.githubusercontent.com/46328784/102018669-5901d300-3d4d-11eb-8b3c-e9238df9587b.png)

As you can see, it's true that some level of detail is lost, but the icons on their default size looks more defined and colorful. 

Here I attach the icons (as always, I didn't edit the original cherries, except the finders) if you want to test and compare.

[icons_16px_2020-12-13.zip](https://github.com/giuspen/cherrytree/files/5685043/icons_16px_2020-12-13.zip)

Of course, this is an opinion, no problem if you consider that could be a problem or don't adjust to a future implementation.

They also work on dark themes, example:

![imagen](https://user-images.githubusercontent.com/46328784/102018704-ab42f400-3d4d-11eb-84d9-a6fdec28e5d8.png)
![imagen](https://user-images.githubusercontent.com/46328784/102018710-b564f280-3d4d-11eb-9431-6639afb843c6.png)

Cheers

**Comment by giuspen** [comment]
Thanks @userfav I want to see how they look when upscaled and in hidpi monitor before deciding

**Comment by userfav** [comment]
@giuspen Yes, the icons are still svg and scalable as always, but that's something to consider. I could only test them on a 2k monitor.

**Comment by giuspen** [comment]
I merged your work, thanks.
Some feedback from me about what I like less/have some doubts:
- the icon bold/italic/strikethrough/underlined, they all look bold and not as detailed as other icons with letters
- the s icon for small is quite big, bigger than the h just before and the following a, maybe could be the same size if not slightly smaller
- (this less important) the magnifier is not so clear that it's a magnifier because the stick is maybe too small

**Comment by userfav** [comment]
Thanks, feedback is needed and appreciated! They are all good points.

About the  bold/italic/strikethrough/underlined: I have also have the sense that they all looked "bold". The elementary folks made a symbolic thinner alternative to them but the letters were "B" for bold, "U" for underlined, "S" for strikethrough, etc. and I prefer the current by them not having the first letter on english. I attach below a variant using the same "a" used on the superscript icon.  Also I changed the "small" icon using the same "s" that was used on the superscript/subscripts icons. Here's a preview, tell me what you think.

![imagen](https://user-images.githubusercontent.com/46328784/102025498-1f45c200-3d77-11eb-8674-2fa4047ed54d.png)

[icons_frm-txt_2020-12-13.zip](https://github.com/giuspen/cherrytree/files/5685594/icons_frm-txt_2020-12-13.zip)

About the magnifiers, yes, I understand what you mean, I made them bigger to gain clarity when inside have a lot of objects. This recourse is used on other programs as well, a near example can be Inkscape, when they also have many objects inside the magnifier:

![imagen](https://user-images.githubusercontent.com/46328784/102025643-24efd780-3d78-11eb-89bc-0bd345e82262.png)

I guess that when you use a light theme the stick look thin, that's because of the lighter border added to make them pop-up with darker themes:

![imagen](https://user-images.githubusercontent.com/46328784/102025804-1a820d80-3d79-11eb-8507-dd3080937643.png)

If you want I can make the stick more wider but I think that if the circle is smaller the things inside will be look too cramped.

**Comment by giuspen** [comment]
I like your changes thanks!

**Comment by userfav** [comment]
@giuspen Good to know! I take the opportunity to comment you that noticed that I misspelled the name of an icon in the "icons_16px_2020-12-13.zip" pack. It says "ct_fmt-txt-lastest.svg" when should be "ct_fmt-txt-latest.svg".

Cheers

**Comment by giuspen** [comment]
thanks @userfav I spotted the typo and also I found an additional icon of an open lock which was not part of the theme, I simply have ignored it

**Comment by userfav** [comment]
@giuspen I attach a pack of little adjustments, I explain why in the table below. Don't worry, I think I won't bother you about the icons for a while now ;)

![imagen](https://user-images.githubusercontent.com/46328784/102126696-2da0e600-3e2a-11eb-9190-34f921ea2564.png)


[icons_adjustments_2020-12-14.zip](https://github.com/giuspen/cherrytree/files/5691141/icons_adjustments_2020-12-14.zip)

**Comment by giuspen** [comment]
@userfav no bothering at all, I like your work and I'm sure the cherrytree users will like it too, thanks!

**Comment by userfav** [comment]
> 
> 
> @userfav no bothering at all

Good, because I forgot the sorting ones :pray:

![imagen](https://user-images.githubusercontent.com/46328784/102160305-f4856780-3e63-11eb-833a-136363d5a4d0.png)

[icons_adjustments_2020-12-14_sorting.zip](https://github.com/giuspen/cherrytree/files/5692917/icons_adjustments_2020-12-14_sorting.zip)

**Comment by giuspen** [comment]
😄 thanks I'll update shortly

**Comment by userfav** [comment]
@giuspen Giuspen, with the feedback from others users I adjust the icons so the same can be seen acceptable with lighter or darker themes, I use some transparency so the white borders will not be too jarring also I unified the colors of all icons that can have problems with the contrast.  Also I made some tweaks on the icons with the "insert" characteristic (added a "plus") so now are more easy to interpret. Preview: of the same icons on light and dark: 

![imagen](https://user-images.githubusercontent.com/46328784/102357643-4ece1780-3f8d-11eb-94e5-3ecbd45328d5.png)
![imagen](https://user-images.githubusercontent.com/46328784/102357752-6f966d00-3f8d-11eb-9ea7-47601ac879b5.png)

![imagen](https://user-images.githubusercontent.com/46328784/102357619-470e7300-3f8d-11eb-9439-d3d8047625da.png)

Files: [icons_dark-theme_fixes_2020-12-16.zip](https://github.com/giuspen/cherrytree/files/5703134/icons_dark-theme_fixes_2020-12-16.zip)

**Comment by giuspen** [comment]
Super, thanks @userfav I'll update later

**Comment by rogue-ronin** [comment]
Do you have a set that isn't this small? I use them quite large on my toolbar.

Old eyes, ya know... :smiley:

**Comment by userfav** [comment]
@rogue-ronin  Sure!, this is the previous 48px mixed with the latest fixes for the darker themes. If something if seeing off let me know.

[icons_48px.zip](https://github.com/giuspen/cherrytree/files/5705951/icons_48px.zip)

**Comment by rogue-ronin** [comment]
That's actually a mix of 48px and 16px... :smile:

**Comment by rogue-ronin** [comment]
This is a mix of 48px and 16px... :smiley:

Do you have a full set at 48px?

Aloha!

**Comment by userfav** [comment]
There are some 16px svgs but mostly are the "symbolic" ones who are scalable, for example: 

![imagen](https://user-images.githubusercontent.com/46328784/102420502-0dffee00-3fe1-11eb-9443-6faca8ad0785.png)

Witch  ones look bad? can you show me a screenshot?

**Comment by rogue-ronin** [comment]
No worries, my friend. I may have overstated, implying appearance issues.

Looking pretty good here, thanks again!

**Comment by userfav** [comment]
Closing because it was done on version 0.99.26
