### ISSUE TITLE
Cherrytres is slow to open tree 

### ISSUE THREAD

**Issue by mwest0101** [giuspen/cherrytree#1427]
**English:**

Thank a lot for the app, it's a lot ussefull. 

I have a issue. 

When you have a big doc in one branch it's works slowly, I think that a good solutions is: 

Instead to use CTB or CTD files 
add it the posibility to the app to store all info as indepentely files. in "markdown" format and separating in directory each  branch. Off course the app must save the images in the folder correspondent.

Thank a lot.

**Spanish**

Muchas gracias por la aplicación, es muy útil.

Tengo un problema

Cuando tienes un gran documento en una rama, funciona lentamente, creo que una buena solución es:

En lugar de utilizar archivos CTB o CTD
agréguele la posibilidad a la aplicación de almacenar toda la información como archivos independientes. en formato "markdown" y separando en directorio cada rama. Por supuesto, la aplicación debe guardar las imágenes en la carpeta correspondiente.

Muchas gracias.

**Comment by ciranus** [comment]
> When you have a big doc in one branch it's works slowly, I think that a good solutions is:

"Big" because of text content, or images content ?
If you export this node as CT document, what is this size ?

**Comment by mwest0101** [comment]
It's a Big text content, All my info in CTD format it has a size of 1.6 MB.

**Comment by ciranus** [comment]
Then not so big.
If you re-import this exported node as a new node.
Do you have the same problem with this new node ?

**Comment by mwest0101** [comment]
Yes, I export and import and it does the same. The version is: 0.99.25

**Comment by mwest0101** [comment]
I have in the node a big table, with data.

**Comment by ciranus** [comment]
Interesting. This table can explain.
If there is nothing confidential in this node (really check before), can you share this exported node here (attach the file ?) ?

**Comment by giuspen** [comment]
yes the performance of the large tables is extremely bad, I'll work on that soon

**Comment by mwest0101** [comment]
> 
> 
> yes the performance of the large tables is extremely bad, I'll work on that soon

Yes , i didn't think about it. This is really the issue. 

This is the node file:
https://drive.google.com/file/d/1Y6T_twH4ZyHCEvce62BfXOYNG-JxSLpZ/view?usp=sharing

**Comment by giuspen** [comment]
fixed in upcoming 0.99.28

**Comment by mwest0101** [comment]
Great, Thanx

> fixed in upcoming 0.99.28

Great.  thanks.
