### ISSUE TITLE
FIND Functions Adding Empty Lines to Blank Nodes?

### ISSUE THREAD

**Issue by puddlecheese** [giuspen/cherrytree#1428]
**Version, Operative system**
Windows 10 Enterprise 20H2 19042.685

**Describe the bug**
Empty nodes in tree have new lines added to them upon using search functions.

**To Reproduce**
1. Create a new named RICH TEXT node.
2. BOLD = NO, USE SELECTED COLOR = NO, USE SELECTED ICON = NO, TAGS = NO. Issue occurs regardless of if node is READ ONLY or not.
3. The newly created note has 1 empty line. This is expected.
4. Run a FIND INTO ALL THE TREE NODES CONTENTS function.
5. The newly created empty node now has 2 blank lines instead of a single line.

**Screenshots**
![Screenshot 2020-12-14 015907](https://user-images.githubusercontent.com/75978515/102068208-0a862000-3db1-11eb-9c1a-ef62008bee5e.png)

**Comment by giuspen** [comment]
thanks, will be ok in 0.99.26
