### ISSUE TITLE
Crash when you try to open a bookmarked node that was deleted

### ISSUE THREAD

**Issue by userfav** [giuspen/cherrytree#1430]
**Version, Operative system**

0.99.25 / Win 10 x64 / portable mode

**Describe the bug**

CT crashes when you try to open a bookmarked node that was previously deleted.

**To Reproduce**

1. Create a node
2. Bookmark the node created.
3. Delete the node
4. Go to the "Bookmarks" menu and select the deleted node name from the list.

**Comment by giuspen** [comment]
thanks will be ok in 0.99.26
