### ISSUE TITLE
New icons dark theme

### ISSUE THREAD

**Issue by fpaskali** [giuspen/cherrytree#1431]
**Version**
0.99.25

**Bug**
The new icons have very low contrast on dark theme.

**Screenshot**
![](https://imgur.com/uyZ5N2I.png?raw=true)

**Comment by giuspen** [comment]
Thanks this has been already fixed for upcoming 0.99.26

**Comment by userfav** [comment]
@fpaskali @aligeyik @T-2 Just asking for opinions of dark theme users here, in 0.99.26 you will see the icons, now for the 0.99.27, what you do thing about this mockup?:

![imagen](https://user-images.githubusercontent.com/46328784/102269294-31e90400-3efb-11eb-846f-b9ad8bd1dc84.png)
![imagen](https://user-images.githubusercontent.com/46328784/102269332-3e6d5c80-3efb-11eb-9ab6-03e5ebf8b0c8.png)

This are the same icons on a light theme:

![imagen](https://user-images.githubusercontent.com/46328784/102269494-7aa0bd00-3efb-11eb-8cad-8e415fab68b0.png)
![imagen](https://user-images.githubusercontent.com/46328784/102269524-855b5200-3efb-11eb-8c2e-57c3507f00e5.png)

**Comment by puddlecheese** [comment]
These are looking great!

Personally, I might try to increase the contrast or clarity/sharpness or general readability of the INSERT icons. That little star symbol over them strikes me as a little blurry, currently.

To a lesser extent, the bottoms of the SUBSCRIPT icons seem to get a bit lost against the dark mode background, but upping the brightness might be too contrasty, so difficult to say. Gradients can be tricky!

That being said, if you're familiar with the icons generally, neither of the above should really prove to be much of an obstacle.

Awesome job!

**Comment by userfav** [comment]
@puddlecheese Noted, thanks!

**Comment by userfav** [comment]
> Sad I might not be able to use these currently on Windows, as there doesn't seem to be a dark mode for menu / toolbars, currently. Maybe some day!

@puddlecheese Actually, you can have a dark theme on Windows (this is how I'm testing the icons without having to use a virtual machine) :

![image](https://user-images.githubusercontent.com/46328784/102491566-27d81a00-404f-11eb-9b7b-27af40b53516.png)

First, you need to download a dark GTK3 theme (from, GnomeLook, for example) and put the theme on:

[cherrytree installation directory]\mingw64\share\themes\

then on the folder:

[cherrytree installation directory]\mingw64\share\gtk-3.0\

you need to create the file "settings.ini" whith this content:

```ini
[Settings]
gtk-theme-name=deepin-dark
```

(I'm using the theme "deepin-dark" in this example)

And I think that will do the trick. If you want to return to the windows theme just delete the settings.ini file. Maybe exists some better way to do it but that works for me. Note: With this method I don't have a dark window decoration (as you can see in the screenshot), If you discover how to do it let me know.

Cheers

**Comment by fpaskali** [comment]
@userfav I have finally installed the newest version 0.99.27. I prefer more this version icons than the blueish variant.

**Comment by mvsite** [comment]
> And I think that will do the trick. If you want to return to the windows theme just delete the settings.ini file. Maybe exists some better way to do it but that works for me. Note: With this method I don't have a dark window decoration (as you can see in the screenshot), If you discover how to do it let me know.
> 
Thanks for your tip on getting partial dark mode!  This was greak and working.  However, a bit over 3 years later there is still no progress on a "just-works" dark mode nor a way to make the title bar dark.  It's open source but my excuse it lack of time (and knowledge)..

Window bar is drawn by the OS not GTK3, it seems, but there is some solution.  I did see this posted in a stackoverflow discussion about dark mode title bars (https://stackoverflow.com/questions/39261826/change-the-color-of-the-title-bar-caption-of-a-win32-application):
```
#include <dwmapi.h>

BOOL USE_DARK_MODE = true;
BOOL SET_IMMERSIVE_DARK_MODE_SUCCESS = SUCCEEDED(DwmSetWindowAttribute(
    WINhWnd, DWMWINDOWATTRIBUTE::DWMWA_USE_IMMERSIVE_DARK_MODE,
    &USE_DARK_MODE, sizeof(USE_DARK_MODE)));
```

and from https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/desktop/modernize/apply-windows-themes.md
```
However, for any app that uses the standard Windows title bar, you can enable the dark version of the title bar when the system is in Dark mode. To enable the dark title bar, call a [Desktop Windows Manager](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/windows/win32/dwm/dwm-overview) (DWM) function called [DwmSetWindowAttribute](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/windows/win32/api/dwmapi/nf-dwmapi-dwmsetwindowattribute) on your top-level window, using the window attribute [DWMWA_USE_IMMERSIVE_DARK_MODE](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/windows/win32/api/dwmapi/ne-dwmapi-dwmwindowattribute). (DWM renders attributes for a window.)
```

I assume this is just complicated and annoying enough to not be worth the trouble :)  Anyway I went back and forth but switched all my notes to CherryTree after your post about the partial dark mode. Thanks!
