### ISSUE TITLE
The Recent Documents list doesn't show undercores

### ISSUE THREAD

**Issue by userfav** [giuspen/cherrytree#1435]
**Version, Operative system**

0.99.25 Win 10 / Linux Mint 20

**Describe the bug**

When looking for open a Recent Document, the list don't show underscores on the path or the file:

![imagen](https://user-images.githubusercontent.com/46328784/102526878-13117b80-407b-11eb-8673-0788d3f6d195.png)
 
(the tooltip works ok)

**Comment by giuspen** [comment]
thanks
