### ISSUE TITLE
All notes suddenly rendered in half-size fonts.

### ISSUE THREAD

**Issue by DiagonalArg** [giuspen/cherrytree#1437]
Suddenly, every note (hundreds) is being rendered with a font half the size it was before.  I have no idea what triggered the bug, other than that the computer was overloaded, but on reboot, it's still there.  I'm hoping there is some way to return them to normal, because I really have to squint to see them.

Ubuntu 16.04.  CherryTree 0.39.4

**Comment by giuspen** [comment]
just go to the preferences dialog, tab fonts

**Comment by ciranus** [comment]
>  I have no idea what triggered the bug

Probably not a bug, but a Ctrl+mouse wheel feature.....

**Comment by DiagonalArg** [comment]
Control-mousewheel.  My bad.

thank you *so* much.
