### ISSUE TITLE
Crash occurs when pasting inside cherrytree, under certain conditions

### ISSUE THREAD

**Issue by goodguyandy** [giuspen/cherrytree#1440]
**Version, Operative system**
Linux kali 5.9.0-kali4-amd64 #1 SMP Debian 5.9.11-1kali1 (2020-12-01)

Using i3 as desktop manager

on  x86_64 GNU/Linux

Edit: here's the cherrytree version where the bug is happening:

0.99.25+dfsg-1

**Describe the bug**

_When Trying to paste an empty file copied using xclip with -t flag, the program exits with a 'segmentation fault' error_. 

In the log/terminal a "Segmentation Fault" error is show. 

**To Reproduce**
Edit2: after investigating the bug more, here's the process to reproduce it:

1. Generate an empty file:

`$ touch emptyfile`

2. copy it using xclip with -t image/png option:

`xclip -selection clipboard -t image/png -i emptyfile`
3. Paste inside cherrytree
4. crash occurs

**Comment by ciranus** [comment]
Which exact cherrytree version ?

**Comment by goodguyandy** [comment]
The old version where the bug wasn't happening:
0.37-61.1

The version where the bug is actually happening:

0.99.25+dfsg-1

**Comment by ciranus** [comment]
Can you launch CT from a terminal, and report what happen when you paste the image in CT ?

**Comment by goodguyandy** [comment]
So I investigated the issue more. 
Basically  in the new system my script was generating an empty file (scrot wasn't working properly) then copying using xclip to cherrytree I got the crash. 

I updated the steps to reproduce the crash.

**Comment by goodguyandy** [comment]
> Can you launch CT from a terminal, and report what happen when you paste the image in CT ?

In the log I got only "Segmentation Fault". Take a look at the updated 'steps to reproduce'

**Comment by ciranus** [comment]
I don't understand your command at all

`xclip -selection clipboard -t image/png -i emptyfile`

What does it mean creating an empty file, and trying to paste it as an image ???

Can you copy a 'normal' image to CT ?

**Comment by goodguyandy** [comment]
> I don't understand your command at all
> 
> `xclip -selection clipboard -t image/png -i emptyfile`
> 
> What does it mean creating an empty file, and trying to paste it as an image ???
> 
> Can you copy a 'normal' image to CT ?

Sorry, I wasn't clear. 
Yes, I can copy a 'normal' image. So everything is working fine. 

I decided to not close this post as someone wants to investigate why the crash occurs in that condition. Hope it make sense now.

**Comment by ciranus** [comment]
Yes it crashes. But it does not explain what you intend to do by converting an empty file to image !!
Try to update your script :

`[ -s file ] || xclip -selection clipboard -t image/png -i file`

**Comment by goodguyandy** [comment]
> Yes it crashes. But it does not explain what you intend to do by converting an empty file to image !!
> Try to update your script :
> 
> `[ -s file ] || xclip -selection clipboard -t image/png -i file`

At the beginning, I tought I was coping a valid image file! I realized after that my screenshot script was bugged, and was trying to copy an empty file to clipboard. So when I opened this post I tought the image was valid and not empty. After investigating, I realized I was pasting empty data inside cherrytree. Hope it makes sense now 😄

**Comment by ciranus** [comment]
This will check that your file is not empty.....
`[ -s file ] || xclip -selection clipboard -t image/png -i file`

**Comment by ciranus** [comment]
After 7 updates of your first message, yes it's now clear. Then try this:
`[ -s file ] || xclip -selection clipboard -t image/png -i file`

**Comment by giuspen** [comment]
I will see if I can avoid the crash anyway as we never want a crash even if from a user's mistake

**Comment by giuspen** [comment]
ok it won't crash anymore for this in 0.99.26
