### ISSUE TITLE
How do I upgrade to 0.99.26?

### ISSUE THREAD

**Issue by wisdomlight** [giuspen/cherrytree#1443]
What is the method to upgrade Cherrytree from 0.99.25 to 0.99.26??
Thanks

**Comment by ciranus** [comment]
What is your system ? any linux ? windows ?

**Comment by wisdomlight** [comment]
Sorry I should have mentioned.
Debian Bullseye
GNOME 3.38.2

Gen Kelsang Sherab

Just like an experience in a dream
Everything I now enjoy
Will become a mere recollection
For what has past will not be seen again

Sent from [ProtonMail](https://protonmail.ch), encrypted email based in Switzerland.

**Comment by ciranus** [comment]
Then different solutions if you are not patient enough to wait for Debian CT package updates.

You can add the ppa [_yes, ubuntu ppa... but no risk with CT package / trust me, ... or not_]
https://launchpad.net/~giuspen/+archive/ubuntu/ppa/+packages

Or directly grab cherrytree_0.99.26-2_amd64.deb from here:
http://ppa.launchpad.net/giuspen/ppa/ubuntu/pool/main/c/cherrytree

I personally use a script to check and install CT updates without any ppa.

**Comment by wisdomlight** [comment]
What doe CT means?
I am not very patient.. so I will try either the launch pad or directly grab the .deb. 
But when grabing the .deb file - do i need to remove the previous one and then install?? 
Or can I install the new .deb and it will adapt itself to the fact that there an older version is already installed ?
> I personally use a script to check and install CT updates without any ppa.
I personally would love to know how to do this.

**Comment by ciranus** [comment]
CT for ... CherryTree. You don't need to uninstall.

Download cherrytree_0.99.26-2_amd64.deb , then
`sudo apt install ./cherrytree_0.99.26-2_amd64.deb`

**Comment by wisdomlight** [comment]
ahh
thank @ciranus 
i tried installing flatpak on my Librem 5 an arm based device
when `
flatpak remote-add --if-not-exists flathub https://flathub.org/apps/details/com.giuspen.cherrytree`

I get `
errer: GPG verification enabled, but no signatures found (use gpg-verify=false in remote config to disable)`
what does it mean??

**Comment by ciranus** [comment]
I don't use flatpak.
Which problem did you have with the deb package ?

**Comment by wisdomlight** [comment]
> Sorry, I don't use flatpak on **arm** (different issue).
> Is it OK for Debian or not ?

Yes it is fine.
Thank you
But I see you do have an arm package so that's ok.
Thank you so much for CT and I am happy to say I have started a regular donation for CT.
Happy festive times and Happy new year to come.

**Comment by ciranus** [comment]
"I" do not have any arm package.

These are the people to thank !
Written by Giuseppe Penone (aka giuspen) and Evgenii Gurianov (aka txe).
https://www.giuspen.com/cherrytree/

**Comment by wisdomlight** [comment]
I see - well I thank @giuspen and @txe 
And I am pleased they have created an ARM package.

**Comment by giuspen** [comment]
:) and thanks @ciranus for your help with the issues
