### ISSUE TITLE
Shift+CursorLeft/Right don't work anymore

### ISSUE THREAD

**Issue by Hoffenbar** [giuspen/cherrytree#1444]
Just noticed, with 0.99.26, that ctrl+cursorkeys to select a word, sentences etc., won't work anymore.
Right now, a have the waitcursor, program totally blocked while within the process of documenting.... I think I must kill the programm via taskman, with the risk of loosing some content....

**Comment by userfav** [comment]
Possibly duplicated with  #1441

**Comment by Hoffenbar** [comment]
Yes! Problably the same, and I agree with 1441 that the save-Icon isn't good.
And sorry, I ment Shift+Cursor.
Just replay Ctrl+Cursor -> the program hangs again.

**Comment by giuspen** [comment]
yes it's a duplication and already fixed, I'll release a new version shortly
