### ISSUE TITLE
Double Screen Refresh ?

### ISSUE THREAD

**Issue by Hoffenbar** [giuspen/cherrytree#1446]
Windows, since several releases up until the newest 0.99.26

Switching to a new page sometimes shows the content of that page, than the page gets cleared and then the content is shown again, resulting in a short flicker.

**Comment by giuspen** [comment]
that is because of a GTK rendering issue with Codebox and Tables, the only workaround I found so far is this (to basically reload the node)

**Comment by giuspen** [comment]
fixed in upcoming 0.99.28

**Comment by MJimitater** [comment]
Thanks @giuspen , table editing works WAY better in 0.99.28!! Major improvement for UX! Thanks, happy new year!

**Comment by giuspen** [comment]
Great, happy new year 😉
