### ISSUE TITLE
Inserting row in table does not work or lasts several minutes

### ISSUE THREAD

**Issue by Hoffenbar** [giuspen/cherrytree#1447]
Windows, since several releases up until the newest 0.99.26

I have a table with about 50 rows. Navigating into the last row and right clicking to bring up the context menu,, than choosing "Zeile einfügen" (Insert row). My expectation was "Appending a new row", but thats not the point. The point is, that many many seconds nothing happens, before a new row appears after the last one.

**Comment by giuspen** [comment]
OK this is again the problem of the tables performance, there are few issues on this I'll try and sort out soon

**Comment by giuspen** [comment]
fixed in upcoming 0.99.28
