### ISSUE TITLE
0.99.26 Keyboard Text Navigation Broken

### ISSUE THREAD

**Issue by metal450** [giuspen/cherrytree#1448]
Upon updating to 0.99.26, the standard text navigation shortcuts have broken: i.e.

Shift+Left -> Normally moves the cursor to the left, while selecting text
Shift+Right -> Normally moves the cursor to the right, while selecting text
Shift+Up -> Normally moves the cursor to the previous line, selecting text in between
Shift+Down -> "" to the next line

Also: CherryTree crashed (pegged at 100% cpu usage) after using these hotkeys.

I found that I can unbind these keys in the preferences, which prevents the crash & restores text navigation to working order - so this is no longer an issue for me personally, but I'm not sure everyone would realize that it's possible to use the preferences to restore text navigation to standard behavior.

Kubuntu 20.04.

**Comment by giuspen** [comment]
Will be ok in 0.99.27
