### ISSUE TITLE
Custom CSS

### ISSUE THREAD

**Issue by monkiki** [giuspen/cherrytree#145]
Hello,

Is possible to create a custom CSS to change the default styles for H1, H2, P and so on?

Thanks in advance.

**Comment by shivarajnaidu** [comment]
why not !? CSS is for change styles as our wish..

**Comment by monkiki** [comment]
Well, perhaps the question should have been different: where can I change these styles?

**Comment by giuspen** [comment]
Since the version 0.36.7 you can override the styles.css just putting your
modified one in the cherrytree config directory.
To open the cherrytree config directory click the menu item help–open
preferences directory.

**Comment by monkiki** [comment]
Sorry but there is no changes in the view using ~/.config/cherrytree/styles.css

```
h1, h2, h3 {
    color: #f00;
    font-weight: bold;
    text-decoration: underline;
}

div.main h1 {
    padding-top: 1em;
    font-weight: bold;
    padding-bottom: 1em;
}

p {
    line-height: 1.2;
}
```

![image](https://cloud.githubusercontent.com/assets/130590/15837871/78c57c1e-2c3b-11e6-88e3-aa9c9be741db.png)

**Comment by monkiki** [comment]
Sorry, any idea?

**Comment by giuspen** [comment]
The css is for the exported html only

**Comment by monkiki** [comment]
Ups, thanks for the info.

**Comment by pihentagy** [comment]
But wait, is there a style sheet for the interface display itself? Can I style H1, H2, and so on?

**Comment by giuspen** [comment]
The css is only for the export to html at the moment

**Comment by 1637664504** [comment]
> The css is only for the export to html at the moment

Modify windows version as below:
cherrytree_0.38.8_win32_portable\bin\styles.css
div.main h1 {
    font-weight: bold;
    display: inline;
	font-size: 125%;
	color: #FF0000;
}

div.main h2 {
    padding-top: 0.75em;
    /*padding-bottom: 0.5em;*/
    font-weight: bold;
    font-size: 125%;
    color: ##0000FF;
    display: inline;
}

div.main h3 {
    padding-top: 0.75em;
    font-weight: bold;
    font-size: 100%;
    color: #2E8B57;
    display: inline;
}
-----------<<

Result: h1 h2 h3 only font size change. Color not change. How should change ?
Thanks
Liu Jiang
