### ISSUE TITLE
Time filter for Search "Find in Nodes Names and Tags doesn't work

### ISSUE THREAD

**Issue by Sisyfos3** [giuspen/cherrytree#1453]
CT 0.99.27, Windows 10 and Linux Mint 20

When searching in nodes names and tags, searching is unsuccessful if any time filter is selected, otherwise it finds all occurences of the search pattern.   

Merry Christmas and a Happy New Year! Thank you for a wonderful piece of software, Can't do without it :-)

**Comment by Sisyfos3** [comment]
It works if "Node created before" or "Node modified before" is set, but not when "Node created after" or Node modified after" is set (either alone or in combination with the "before" filters)

**Comment by giuspen** [comment]
Merry Christmas and happy 2021 ;)

**Comment by giuspen** [comment]
thanks will be ok in 0.99.28
