### ISSUE TITLE
.ctz File not loading after upgrading to Kali 2020.4

### ISSUE THREAD

**Issue by SpaceCyborg** [giuspen/cherrytree#1455]
Hello folks,

First time raising an issue, please bear with me.

Thanks to the dev(s) for a great tool! :)

**Version, Operative system**
VERSION_ID="2020.4"
Linux kali 5.9.0-kali4-amd64 #1 SMP Debian 5.9.11-1kali1 (2020-12-01) x86_64 GNU/Linux
CherryTree 0.99.25 (started experiencing with 0.99.23)

**Describe the bug**
Issue was first experienced about two weeks ago after upgrading to Kali 2020.4
At the time, CT version was 0.99.23. Currently running 0.99.25
I am not able to open / load my *.ctz file - it is password protected. 

1. Import | From CherryTree File
2. My .ctz file is saved in "Documents" folder BUT does not "show up" 
3. I have to type the name of the file and ONLY then it "shows up"
4. I clicked "open" and nothing happens
5. The top bar menu is inactive (nothing happens as I click any "menu item", e.g. "Import" menu button) for about 45 seconds
6. Eventually, after about 45sec the menu bar buttons becomes active 
7. File is not loaded
8. I tried this same procedure on another VM (TL-OSINT) and I was able to load the file. Here are the specs for this VM:   Linux kali 5.6.0-kali2-amd64 #1 SMP Debian 5.6.14-1kali1 (2020-05-25) x86_64 GNU/Linux   // VERSION_ID="2020.4" // CherryTree 0.99.23 [[This VM is Kali-based.]]

Thank you very much for a great tool!

**Comment by giuspen** [comment]
Can you open a terminal and run
cherrytree path_to_file
What happens

**Comment by SpaceCyborg** [comment]
Please see below:

What happened on Terminal >>
![image](https://user-images.githubusercontent.com/40194695/103106957-9f570c00-4642-11eb-813b-c05dbf297730.png)

What happened when CT launched >>
![image](https://user-images.githubusercontent.com/40194695/103106916-44251980-4642-11eb-88ee-5cc78b380bcc.png)

**Comment by giuspen** [comment]
Sorry you have to replace path_to_file with the actual path to the .ctz file which I don't know but you can find out since is on your file system

**Comment by ciranus** [comment]
> Linux kali 5.9.0-kali4-amd64

It looks like a so typical **kali** issue. 'root' is a not 'user'.

![ksnip_20201227-113052](https://user-images.githubusercontent.com/61602511/103168875-6e8bf800-4837-11eb-8ee3-18db7d2a2bc9.png)

**Comment by Crankle437** [comment]
You have executed the command as user "root", look at the terminal prompt or type the command `whoami` to see the current user. The user "root" in this case has no home directory `/home/root/`, `/root/`is the home directory of the user "root". To help you, you have to run the command from giuspen with the path to your *.ctz file to look into the debug infos. ;)

e.g. test.ctz is saved under `/home/test/test.ctz` -> `cherrtree /home/test/test.ctz`

**Comment by SpaceCyborg** [comment]
Thank you everyone for your prompt response. 

**Mystery solved**: the file ext had been changed to .ctz!  
I am not sure how / when I changed this! :( All I can say is that it wasn't me! *embarrassed*
Everything works perfectly now. 

Thanks guys.

**Comment by ciranus** [comment]
Do you confirm you launch Cherrytree as a **root** ? (then still a kali specificity ?).

**Comment by SpaceCyborg** [comment]
@ciranus , see below:

![image](https://user-images.githubusercontent.com/40194695/103211365-aadf5700-4910-11eb-89d5-ce465b2d634a.png)

**Comment by ciranus** [comment]
I just hope you understand the risks of considering "root" as a normal Joe user. 
You should not in a clean linux installation, and definitively not in a Debian environment.
But not a CT issue.
Then issue **closed**.

**Comment by MJimitater** [comment]
@ciranus Been really admiring your work lately, thank you for helping with issues, scrutinizing them!!

**Comment by davidegalletti** [comment]
Sort of similar issue after upgrading to Ubuntu 20.04.1 LTS
cherrytree does not open a file (Permission denied) if it is on this disk:

`/dev/sda3 on /media/davide/Windows type fuseblk (rw,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions,allow_other,blksize=4096,uhelper=udisks2)`

the user (davide) I use to run cherrytree owns the file and its directory:

`drwxrwxrwx 1 davide davide    16384 dic 28 10:46  ./
-rwxrwxrwx 1 davide davide  2355516 dic 25 12:35  Todo.ctd*`

running from the terminal:

`davide@davide-HP:~$ cherrytree /media/davide/Windows/Dati/Todo.ctd
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (failed to map segment from shared object): ignored.
ln: failed to create symbolic link '/home/davide/snap/cherrytree/28/.config/gtk-2.0/gtkfilechooser.ini': File exists
Gtk-Message: 13:39:13.022: Failed to load module "overlay-scrollbar"
Gtk-Message: 13:39:13.022: Failed to load module "gail"
Gtk-Message: 13:39:13.023: Failed to load module "atk-bridge"
error reading from plain text xml
Traceback (most recent call last):
  File "/snap/cherrytree/28/bin/cherrytree", line 114, in <module>
    f_main(args)
  File "/snap/cherrytree/28/bin/cherrytree", line 79, in f_main
    main.main(args)
  File "/snap/cherrytree/28/share/cherrytree/modules/main.py", line 257, in main
    CherryTreeHandler(args, lang_str)
  File "/snap/cherrytree/28/share/cherrytree/modules/main.py", line 89, in __init__
    self.window_open_new(args.filepath, args.node, True, True if args.filepath else False)
  File "/snap/cherrytree/28/share/cherrytree/modules/main.py", line 94, in window_open_new
    window = core.CherryTree(self.lang_str, filepath, node_name, self, is_startup, is_arg, False)
  File "/snap/cherrytree/28/share/cherrytree/modules/core.py", line 256, in __init__
    self.file_startup_load(open_with_file, node_name)
  File "/snap/cherrytree/28/share/cherrytree/modules/core.py", line 1523, in file_startup_load
    self.file_load(os.path.join(self.file_dir, self.file_name))
  File "/snap/cherrytree/28/share/cherrytree/modules/core.py", line 2020, in file_load
    cherrytree_string = self.file_get_cherrytree_data(filepath, True)
  File "/snap/cherrytree/28/share/cherrytree/modules/core.py", line 1992, in file_get_cherrytree_data
    else: file_descriptor = open(filepath, 'rb')
IOError: [Errno 13] Permission denied: u'/media/davide/Windows/Dati/Todo.ctd'`

**Comment by SpaceCyborg** [comment]
> I just hope you understand the risks of considering "root" as a normal Joe user.
> You should not in a clean linux installation, and definitively not in a Debian environment.
> But not a CT issue.
> Then issue **closed**.

Risks understood. . . Thanks for highlighting. 
Agreed, not CT issue. Please go ahead and close.

**Comment by ciranus** [comment]
@MJimitater 
Thanks, and really amazed you seem to be familiar with [Simplex](https://github.com/MJimitater/simplex) mathematical method..... (other discussion....).

@davidegalletti
It's a different issue.
Why do you need gtk3-nocsd in your system ?

Try CT from ppa version 
https://launchpad.net/~giuspen/+archive/ubuntu/ppa

**Comment by davidegalletti** [comment]
thanks! From ppa works just fine
