### ISSUE TITLE
Cannot find printf.h header on openSUSE

### ISSUE THREAD

**Issue by malcolmlewis** [giuspen/cherrytree#1458]
Hi
Building on openSUSE Tumbleweed.

With the spdlog unbundle on openSUSE we have fmt headers in it's own package, therefore in the changes to /src/ct/ct_logging.h it is in the same format as _WIN32 so have to patch out the ifdef to build.

```
diff -Naur a/src/ct/ct_logging.h b/src/ct/ct_logging.h
--- a/src/ct/ct_logging.h	2020-12-27 08:48:50.000000000 -0600
+++ b/src/ct/ct_logging.h	2020-12-27 10:17:49.481450227 -0600
@@ -24,12 +24,13 @@
 #pragma once
 
 #define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_DEBUG
-#ifdef _WIN32
-#include <fmt/printf.h>
+/*#ifdef _WIN32
+#include <fmt/printf.h>*/
 #define SPDLOG_FMT_EXTERNAL
-#else
+#include <fmt/printf.h>
+/*#else
 #include <spdlog/fmt/bundled/printf.h>
-#endif
+#endif*/
 #include <spdlog/spdlog.h>
 #include <spdlog/fmt/fmt.h>
 #include <glibmm/ustring.h>
```

Perhaps it should just be `fmt/printf.h`?

**Comment by giuspen** [comment]
Hi, I'll see if I can just make it build everywhere with fmt installed outside of spdlog. If I fail I'll try and autodetect if fmt is installed or not

**Comment by malcolmlewis** [comment]
@giuspen Many thanks :)

**Comment by giuspen** [comment]
Should be ok now, fmt is looked for outside of spdlog
