### ISSUE TITLE
MacOS | Compilation error on v0.99.27

### ISSUE THREAD

**Issue by reedcrif** [giuspen/cherrytree#1459]
Just for information, compilation error on Cherrytree v0.99.27

**Version, Operative system**
MacOS 11.1

**Describe the bug**
Compilation finished by an error:

```
/path/to/cherrytree/tests/tests_misc_utils.cpp:93: Failure
Value of: threadSafeDEQueue.empty()
  Actual: false
Expected: true
libc++abi.dylib: terminating
/bin/sh: line 1: 32435 Abort trap: 6           ../run_tests
make[2]: *** [run_tests] Error 134
make[2]: *** Deleting file `run_tests'
make[1]: *** [tests/CMakeFiles/run_tests.dir/all] Error 2
make: *** [all] Error 2
``` 

When commenting the test, compilation works:

Line 93, file: `tests_misc_utils.cpp`
```
    // ASSERT_TRUE(threadSafeDEQueue.empty());
```

**To Reproduce**
Follow the README.md for MacOS

Once compiled, Cherrytree launches well but a right clic crash the app.

**Comment by giuspen** [comment]
Unfortunately I do not own a Mac, if you know of a way to set up a virtual machine with MacOs please point me to it so that I can test the Mac build myself

**Comment by marianopela** [comment]
> Unfortunately I do not own a Mac, if you know of a way to set up a virtual machine with MacOs please point me to it so that I can test the Mac build myself

https://github.com/kholia/OSX-KVM

**Comment by giuspen** [comment]
Interesting thanks @marianopela I'll try and set up the VM after releasing 0.99.28

**Comment by reedcrif** [comment]
Hi, I tried the 0.99.28 and compilation and usage (right clic) work fine :)

Thanks!
