### ISSUE TITLE
Rich text monospace background doesn't work in Windows 10

### ISSUE THREAD

**Issue by 0xtaf** [giuspen/cherrytree#1461]
**Cherry Tree version:** 
0.99.27

**OS version:**
Edition: Windows 10 Pro
Version: 1909

**Describe the bug**
Changing the background color of the rich text with "Monospace Background", doesn't work.

**To Reproduce**
1. Go to 'Edit > Preferences > Theme'
2. Click on 'Monospace Background' color picker.
3. Choose a color. And restart the app.
4. See nothing changes.

**Screenshots**
 [Screenshot1](https://i.imgur.com/ZPHqG1M.png)
 [Screenshot2](https://i.imgur.com/XYgjVN0.png)

**Comment by userfav** [comment]
Curious, I can't reproduce on Win10 x64 (same version but portable mode)

![imagen](https://user-images.githubusercontent.com/46328784/103421881-6dcbcc80-4b7d-11eb-9fd7-603895fb92f4.png)
![imagen](https://user-images.githubusercontent.com/46328784/103421888-7d4b1580-4b7d-11eb-8578-deaf5db5a653.png)

Can you show us an screenshot of an mono-spaced formatted line of text?

**Comment by 0xtaf** [comment]
After booting my computer today, it's solved. I don't know what happened but there's no problem now. Thank you for the answer!
