### ISSUE TITLE
Config.cfg re-created when it is symlinked

### ISSUE THREAD

**Issue by toxision** [giuspen/cherrytree#1464]
**Version, Operative system**
0.99.27 installed via .deb file directly from Debian, running on Sparky Linux

**Describe the bug**
I am keeping application configs in a cloud storage and usually only create symlinks wherever a certain config file is need. CT however seems to remove the existing symlink to the config.cfg, after it reads its values. Then it saves a new config.cfg in that same folder. Config file is saved in the default location at: ~/.config/cherrytree/config.cfg
Details in the logs at the bottom

**To Reproduce**
1. move/rename the config.cfg
2. create a symlink from it into the config folder
3. open Cherrytree and change a setting
4. new config is created with the same values and symlink is removed

**Logs and outputs**
Config folder status before:
lrwxrwxrwx  1 toxision toxision   57 Jan  1 21:08 config.cfg -> /full_path_removed/cherrytree.config.cfg

Starting Cherrytree in verbose and changing a setting:
21:12 ~....: cherrytree
[2021-01-01 21:12:10.535] [   ] [debug] /home/toxision/.config/cherrytree/config.cfg parsed
[2021-01-01 21:12:10.880] [   ] [debug] autosave is started
[2021-01-01 21:12:10.880] [   ] [debug] mod time sentinel is started
[2021-01-01 21:12:11.242] [   ] [debug] Node name: *removed
[2021-01-01 21:12:18.336] [   ] [debug] shift images in MenuBar/context menu

Config folder status after:
-rw-r--r--  1 toxision toxision 4.0K Jan  1 21:14 config.cfg

(For completeness the status of the initial config file to where it was symlinked:
-rw-r--r-- 1 toxision toxision 4.0K Jan  1 21:01 cherrytree.config.cfg)

**Comment by giuspen** [comment]
thanks will be working in upcoming 0.99.28
