### ISSUE TITLE
 Right-arrow special characters pasted into a CT sub-node's table, crashes CT each future viewing.

### ISSUE THREAD

**Issue by guigirl42** [giuspen/cherrytree#1465]
**Version, Operative system**
0.99.27 in ArchLinux KDE, 0.99.27 in SparkyLinux Xfce.

**Describe the bug**
Due to my procedural unfamiliarity, my initial reports instead of being in GitHub, are here:
1. https://www.giuspen.com/2020/12/cherrytree-0-99-27-issued/comment-page-1/#comment-36594
2. https://www.giuspen.com/2020/12/cherrytree-0-99-27-issued/comment-page-1/#comment-36596
3. https://www.giuspen.com/2020/12/cherrytree-0-99-27-issued/comment-page-1/#comment-36600
4. https://www.giuspen.com/2020/12/cherrytree-0-99-27-issued/comment-page-1/#comment-36606
5. https://www.giuspen.com/2020/12/cherrytree-0-99-27-issued/comment-page-1/#comment-36607

A subnode i edited recently, apparently ok at the time, subsequently causes a CT instant crash each & every time it is selected in the tree. CT appears to be its usual excellent self everywhere else, but this subnode is now broken & inaccessible from within CT.

Additionally, other standard CT operations that necessitate that subnode being accessed even in the background [eg, trying to save the file as XML; initiating the “Find Into All the Tree Nodes Contents” search] also crash CT. 

Afaik, all other nodes still seem unaffected hence available for me still to access & edit. 

**To Reproduce**
Steps to reproduce the behaviour [or at least, i believe this was my sequence of events]:
1. Go to 'https://download1.gigabyte.com/Files/Manual/mb_manual_ga-z97(h97)-hd3_v2.x_e.pdf', download the English version, go to page 30 of 40, near the top of that page, copy the text illustrated in this picture: https://i.postimg.cc/bv8FygKD/20210101-133239.png
2. Click on a CT node / subnode & create a table.
3. Paste that text from clipboard into one row.
4. Save the CT file [i use the default sqlite format].
5. In future, attempting to access this specific node / subnode instantly crashes CT.
6. See error msg in terminal:
```
[2020-12-31 11:58:14.403] [ ] [debug] autosave: no needs to save file
[2020-12-31 11:58:46.108] [ ] [debug] Node name: To Do
Entity: line 16: parser error : PCDATA invalid Char value 27
nstant-Off
^
Entity: line 18: parser error : PCDATA invalid Char value 27

elay 4 Sec.
^
[2020-12-31 11:58:46.116] [gtk] [info]
unhandled exception (type std::exception) in signal handler:
what: Document not well-formed.
Line 18, column 8 (fatal):
PCDATA invalid Char value 27

Trace/breakpoint trap
```
7. Atm i cannot be certain, but i strongly suspect it might be those double-arrowheads that i unfortunately included in my copy-paste, which might be upsetting CT. 

**Screenshots**
Possible location of some of the bad characters, viewed in HexEditor: 
https://i.postimg.cc/CKHY3k1R/20210103-002209.png

**Comment by giuspen** [comment]
Thanks for creating the issue, I'll try and reproduce this later today

**Comment by giuspen** [comment]
@guigirl42 if you create a new empty cherrytree document can you reproduce the issue there?
Can you tell me what PDF viewer you are using to copy from so that you rerpoduce the issue?
I cannot reproduce unfortunately but if you can build from the latest github source code I can try to propose something for you to test

**Comment by giuspen** [comment]
please see https://github.com/giuspen/cherrytree/blob/master/README.md#building-cherrytree-on-arch

**Comment by guigirl42** [comment]
Thank you @giuspen - the pdf reader i used was/is `okular` https://archlinux.org/packages/extra/x86_64/okular/. Later today i hope to make time to experiment with a new dummy CT document as you asked. I'm distressed that so far it's not been reproducible for you. As i wrote, i cannot be certain that those arrowhead symbols are responsible, but the problem only arose after i had pasted that text [including those symbols] into my CT subnode table row, AND the error messages i have provided explicitly point to that text.

Whilst i don't do it often, i have built various packages from source before, in Manjaro & in Arch using PKGBUILDs, & in Ubuntu using `make` etc, so i am happy to try your suggestion there, also later today if time permits. 

Actually, checking my files, one of the packages i built before was cherrytree-0.38.6 in July last year [to update from 0.38.5 given that the Arch Repo was outdated & i was impatient for the new version]. 

I shall get back to you as soon as i can with updated info.

**Comment by giuspen** [comment]
@guigirl42 I applied some fixes that may allow you to open the document with latest 0.99.28. Please try it and let me know.

**Comment by guigirl42** [comment]
That sounds exciting, thank you! I shall try that as my first action then, rather than experimenting with a dummy document. Shall let you know.

**Comment by giuspen** [comment]
That's right, hopefully with 0.99.28 you'll be able to visit that node, if not please paste here the terminal output

**Comment by guigirl42** [comment]
I've done the build, & i thought it was going well, but it seems to have fallen over at the last hurdle:
```
** (run_tests:4147): CRITICAL **: 11:47:18.415: Gtk::Builder::get_widget(): dynamic_cast<> failed.
[       OK ] ReadWriteTests/ReadWriteMultipleParametersTests.ChecksReadWrite/14 (198 ms)
[ RUN      ] ReadWriteTests/ReadWriteMultipleParametersTests.ChecksReadWrite/15

** (run_tests:4147): CRITICAL **: 11:47:18.530: gtkmm: object `RecentDocs' not found in GtkBuilder file.

** (run_tests:4147): CRITICAL **: 11:47:18.530: gtkmm: Gtk::Builder: widget `RecentDocs' was not found in the GtkBuilder file, or the specified part of it.

** (run_tests:4147): CRITICAL **: 11:47:18.530: Gtk::Builder::get_widget(): dynamic_cast<> failed.

** (run_tests:4147): CRITICAL **: 11:47:18.612: gtkmm: object `RecentDocs' not found in GtkBuilder file.

** (run_tests:4147): CRITICAL **: 11:47:18.612: gtkmm: Gtk::Builder: widget `RecentDocs' was not found in the GtkBuilder file, or the specified part of it.

** (run_tests:4147): CRITICAL **: 11:47:18.612: Gtk::Builder::get_widget(): dynamic_cast<> failed.
[       OK ] ReadWriteTests/ReadWriteMultipleParametersTests.ChecksReadWrite/15 (197 ms)
[----------] 16 tests from ReadWriteTests/ReadWriteMultipleParametersTests (3140 ms total)

[----------] Global test environment tear-down
[==========] 73 tests from 7 test suites ran. (3492 ms total)
[  PASSED  ] 73 tests.
[100%] Built target run_tests
guigirl@archlinuxTower[~/cherrytree/build] 11:47:18 Sun Jan 03 $> ./build/cherrytree
bash: ./build/cherrytree: No such file or directory
guigirl@archlinuxTower[~/cherrytree/build] 11:47:44 Sun Jan 03 $> 
```

**Comment by guigirl42** [comment]
FYI:
```
guigirl@archlinuxTower[~/cherrytree/build] 11:59:26 Sun Jan 03 $> ls
total 12896
drwxr-xr-x 2 guigirl guigirl    4096 2021-01-03 11:44 bin
-rwxr-xr-x 1 guigirl guigirl 6051488 2021-01-03 11:47 cherrytree
-rw-r--r-- 1 guigirl guigirl  316344 2021-01-03 11:44 CMakeCache.txt
drwxr-xr-x 6 guigirl guigirl    4096 2021-01-03 11:47 CMakeFiles
-rw-r--r-- 1 guigirl guigirl    8617 2021-01-03 11:44 cmake_install.cmake
-rw-r--r-- 1 guigirl guigirl     887 2021-01-03 11:44 cmake_uninstall.cmake
-rw-r--r-- 1 guigirl guigirl    4038 2021-01-03 11:40 CPackConfig.cmake
-rw-r--r-- 1 guigirl guigirl    4451 2021-01-03 11:40 CPackSourceConfig.cmake
-rw-r--r-- 1 guigirl guigirl     321 2021-01-03 11:44 CTestTestfile.cmake
drwxr-xr-x 2 guigirl guigirl    4096 2021-01-03 11:45 lib
-rw-r--r-- 1 guigirl guigirl   11854 2021-01-03 11:44 Makefile
-rwxr-xr-x 1 guigirl guigirl 6763240 2021-01-03 11:47 run_tests
drwxr-xr-x 4 guigirl guigirl    4096 2021-01-03 11:44 src
drwxr-xr-x 4 guigirl guigirl    4096 2021-01-03 11:47 tests
guigirl@archlinuxTower[~/cherrytree/build] 11:59:29 Sun Jan 03 $> 
```

**Comment by guigirl42** [comment]
Dear @giuspen i am simply delighted to write the following words. **You have SOLVED it for me!** Your new version works *brilliantly*; my subnode now behaves completely normally --no crashing--. I can see that those troublesome symbols have now been removed from my table -- haha, that was going to be my very first action if they were still there, to delete them!

I am truly grateful to you. Not only is CT a wonderful resource for the community, but your responsiveness & enthusiastic cooperation is breathtaking. I sincerely thank you.
***

Btw fwiw: though i could not [for some reason] finish the build via your https://github.com/giuspen/cherrytree/blob/master/README.md#building-cherrytree-on-arch, i decided that instead i would update my old PKGBUILD & build it that way. When i went to the AUR to grab the current PKGBUILD for 0.99.27 to use as my template, i was very happy to discover that Maintainer Morgenstern had already built 0.99.28 & updated the AUR, so all i needed to do now simply was do a standard package update here. Nice & easy!
***

Once more i thank you.

**Comment by giuspen** [comment]
Excellent thanks @guigirl42 for reporting the issue 😉
