### ISSUE TITLE
Odd zoom/font issue Cherrytree 0.69 and 0.70

### ISSUE THREAD

**Issue by kiweegie** [giuspen/cherrytree#147]
This started happening fairly recently in my current version of Cherrytree (0.69). Upgrading to latest version has not helped, same symptoms apply.

Not sure what has happened or what exactly triggers it but it's as if the preset formats for H1, H2 headings etc have reversed - instead of increasing the font from "normal" to large it goes super small.

Added to this while typing in a node large sections of text will suddenly increase in size - as if all text has been selected and set to H1 (when it does work to make the text larger).

I've checked in Edit > Preferences > Font and Text font was set to Sans Normal 6. I increased this to 10 which looks better but it seems to have changed back again.

Having said that its now working ok so appears to be coming and going. I saw this comment about s possibly related issue with CTRL key but under version 0.36.7 for which a release of 0.36.8 was to resolve the problem.

http://www.giuspen.com/topic/bug-in-cherrytree-v-0-36-7-with-font-zoom/

regards Kiweegie.

**Comment by txe** [comment]
Closing this because it was related to really old version and I believe it doesn't happen anymore
