### ISSUE TITLE
Unable to open older files 

### ISSUE THREAD

**Issue by fredcdobbs** [giuspen/cherrytree#1471]
**Version, Operative system**
State the Version and the Operative System/Desktop. Try the latest available version before reporting an issue.

Cherrytree 0.99.28      Linux Mint Ulyana 64-bit Kernel 5.4.0-58-generic x86_64   Mate    system updates CherryTree

**Describe the bug**

When trying to open older file i get error message
![Screenshot at 2021-01-03 17-55-09](https://user-images.githubusercontent.com/76926707/103494862-6ad71300-4ded-11eb-8f32-4806f98488be.png)

 tried on several dated before Dec 2020 all would have error message. Any file after file date Dec 2020 will open 
![Screenshot at 2021-01-03 18-03-01](https://user-images.githubusercontent.com/76926707/103494977-f3ee4a00-4ded-11eb-9697-60af4c5da1b0.png)

recently updated current version. I do not have any previous version to down grade to test opening these older files.

zipped cherrytree files  android.ctb and chromebook.ctb for testing
[cherrytreefile.tar.gz](https://github.com/giuspen/cherrytree/files/5762703/cherrytreefile.tar.gz)

**To Reproduce**
If applicable, attach a non-personal document where the issue can be reproduced systematically.

**Screenshots**

**Comment by giuspen** [comment]
Thanks for providing the test documents I'll try and sort out this evening

**Comment by MuStefan-GH** [comment]
I have exactly the same error using:
Cherrytree 0.99.28 Linux Mint 20 Cinnamon 64-bit Kernel 5.8.0-33-generic x86_64 

Thanks for looking into it! :)

**Comment by giuspen** [comment]
I'll try and release 0.99.29 later today to fix this

**Comment by giuspen** [comment]
thanks will be ok in upcoming 0.99.29

**Comment by fredcdobbs** [comment]
Thank you    upgraded to 0.99.29  Issue fixed

**Comment by MuStefan-GH** [comment]
Yes! It works again. Thanks a million!

**Comment by giuspen** [comment]
Great ;)
