### ISSUE TITLE
Adds/remove chars when pasting text copied from CherryTree since 0.99.x

### ISSUE THREAD

**Issue by paramecie** [giuspen/cherrytree#1472]
Hi Giuseppe!

1001 from France here :-)

Version 0.99.14

Many times, but not always, when I paste in a Thunderbird blank e-mail a copy of a CherryTree text, chars are added at the beginning, and sometimes removed at the end.

It seems to happen only when i've a bulleted list in the original text.
It happens since the recently rebuilt new version (0.99 or something like this), a few months ago.
It never happened before (0.39.x)

This is the original, in CherryTree:

![image](https://user-images.githubusercontent.com/32078594/103589690-42820e00-4eec-11eb-9ecc-c4cf4f9dea10.png)

When I copy/paste it in Thunderbird, it adds some chars at the beginning (some partial HTML code).
Sometimes it also remove the last characters (“.co” or “.c” instead of .com), but not for this test:

![image](https://user-images.githubusercontent.com/32078594/103589710-4dd53980-4eec-11eb-8fc5-8617ad04aa5b.png)

Using a simple clipboard viewer, in HTML, I can see strange “bullets” tokens which may be the problem?

![image](https://user-images.githubusercontent.com/32078594/103589819-968cf280-4eec-11eb-9244-394123362d49.png)

If I remove the bullets from the original text in CherryTree, it pastes with zero error.

Hoping you can fix this, as we often use CT to copy/paste some reference texts having often bullet lists...

Thank you and wishing you the best for 2021 - and please stay safe ;-)

**Comment by giuspen** [comment]
Hi 1001 happy new year 😉
Sure I can fix but can you confirm it happens also with latest 0.99.29 first? A huge quantity of fixes came in after 0.99.14...

**Comment by paramecie** [comment]
Ciao Giuseppe!

Ah yes, I'd be happy of this fix! I confirm for 0.99.14 - didn't notice a new version, sorry. I test it in a few minutes and will reply.

**Comment by paramecie** [comment]
Ahhhh sorry - same exact problem with 0.99.29.

The above text pasted in Thunderbird just right now:

![image](https://user-images.githubusercontent.com/32078594/103706609-5b9ec380-4fad-11eb-8cef-45a2bd8a013a.png)

**Comment by giuspen** [comment]
I'll fix before the next version

**Comment by paramecie** [comment]
Wow, grazie mille.

But warning, in your profile picture, there seem to be a kind kid behind you!

Take great care of you (both).

**Comment by paramecie** [comment]
BTW - I tested more:

* no problem with numbered lists
* but same problem with todo lists, see below:

![image](https://user-images.githubusercontent.com/32078594/103791377-af0f2100-5042-11eb-9df1-23b4fcde6db4.png)

0.99.29

Have a good evening !

**Comment by giuspen** [comment]
Couldn't reproduce on Ubuntu 20.04. What is your operative system?

**Comment by paramecie** [comment]
Sorry! Win 7 - 64bits, French (if that matters).

**Comment by paramecie** [comment]
I confirm.

I have a test VM almost empty, with only Access 2003, Firefox and Thunderbird installed.

I installed CherryTree and didn't change any options.
I didn't even save the folder, I just typed.

When pasting in a Thunderbird e-mail, it show a part of the HTML code, see below:

![image](https://user-images.githubusercontent.com/32078594/104529758-c03fcb00-560a-11eb-8ec1-1fa95fb6d227.png)

**Comment by paramecie** [comment]
Some more testing...

I tested Joplin (a note application) - but won't use it for various reasons - and yours is better :-)

When I paste from CheeryTree to a new Joplin note, it also makes something anormal, see the spacing here:

![image](https://user-images.githubusercontent.com/32078594/104610253-316f9480-5684-11eb-90af-f1e3852ed7f3.png)

The original text in CherryTree is:

![image](https://user-images.githubusercontent.com/32078594/104610420-667be700-5684-11eb-8e3c-9286f6614e75.png)

I'll see if I can find other applications where this is a problem.
But for now, Thunderbird and Joplin.

**Comment by hpta** [comment]
I can confirm for me the thunderbird behaviour on new W10 64bit English version is the same as @paramecie reports. (cherrytree 0.99.29)

Another issue i have is copying from cherrytree to Microsoft Teams or OneNote: if there are any pictures, they are not copied - I have to paste the whole thing to Word first and then copy it from there.

**Comment by giuspen** [comment]
Thanks will be ok in 0.99.30

**Comment by paramecie** [comment]
Ohhh VERY fine Giuseppe!
It'll then make possible to use 0.99.x on a couple of PCs here, for which I needed a copy/paste working...
Thank you!

**Comment by giuspen** [comment]
my pleasure thanks for reporting the issue ;)

**Comment by paramecie** [comment]
Release 0.99.30, I can confirm it's fixed!
GG, Giuseppe - thank you.
