### ISSUE TITLE
homebrew support of cherrytree

### ISSUE THREAD

**Issue by ssxcxS45XT** [giuspen/cherrytree#1473]
https://github.com/giuspen/cherrytree#building-cherrytree-on-macos

Currently, cherrytree has to be manually compiled to be installed on Mac OS X. Can the support using homebrew be added? Thanks.

**Comment by giuspen** [comment]
I'll investigate

**Comment by giuspen** [comment]
I created a pull request for adding cherrytree to homebrew https://github.com/Homebrew/homebrew-core/pull/69968 hopefully it will be merged

**Comment by giuspen** [comment]
it's done, just:
`brew update`
`brew install cherrytree`
