### ISSUE TITLE
Delete Key Tries to Delete Node When In Text Editor

### ISSUE THREAD

**Issue by puddlecheese** [giuspen/cherrytree#1475]
**Version, Operative system**
CherryTree: 0.99.29
Windows 10 64-Bit

**Describe the bug**
If Delete is bound to "Delete the Selected Node", pressing the "Delete" key while editing text seems to prompt the Node Delete confirmation dialog?

**To Reproduce**
Bind DELETE key to "Delete the Selected Node"
Edit text in a node
Press delete key

**Screenshots**
N/A

**Comment by giuspen** [comment]
Can you bind to Shift+Delete instead?

**Comment by giuspen** [comment]
Currently the keyboard shortcuts for the tree work no matter where the focus is and it is simpler to keep it this way

**Comment by puddlecheese** [comment]
I can, easy enough. Just noticed that the functionality seemed to change!
Hopefully the simplification helps with your efforts, which are very appreciated!
Thank you!
Feel free to close this "issue" if convenient :)!

**Comment by giuspen** [comment]
Ok cheers ;)
