### ISSUE TITLE
system tray bug leads to toolbar hidden when startup

### ISSUE THREAD

**Issue by hitzhangjie** [giuspen/cherrytree#148]
Hello, giuspen, I found a bug in cherrytree. When I enable system tray, and when I close it, cherrytree will write the current configuration/status into ~/.config/cherrytree/config.cfg, the config item 'toolbar_visible' is always set to 'False', so when I start it next time, toolbar is hidden.
If I disable system tray, it works well.
Thanks for your execellent work, I love cherrytree!

**Comment by giuspen** [comment]
Hi, what version and operative system?

**Comment by hitzhangjie** [comment]
I'm sorry for response so late.

I came across the problem mentioned above in the following environment:
OS: Fedora 21
Cherrytree: 0.35.2

Besides, now I have tried Cherrytree v0.37 in Fedora 24 and openSUSE Leap 42.1, it works well !

**Comment by giuspen** [comment]
OK Cheers
