### ISSUE TITLE
terminate called after throwing an instance of 'Gio::Error'

### ISSUE THREAD

**Issue by user216** [giuspen/cherrytree#1480]
Can't start cherrytree
```
~$ cherrytree 
terminate called after throwing an instance of 'Gio::Error'
Aborted (core dumped)

5.4.0-59-generic #65-Ubuntu SMP Thu Dec 10 12:01:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

cherrytree/focal 0.99.29-1 amd64

**Comment by giuspen** [comment]
How you installed it

**Comment by user216** [comment]
via **ppa** and **apt-get install**

**Comment by giuspen** [comment]
I assume you were able to run 0.99.29, if yes please close this

**Comment by user216** [comment]
yep. Fist few days I use non-C+ version from snap and after make some manipulations with flatpak instance and it run. But cant give any comments, because forget details about steps that I did :)

So for now I close this issue.

**Comment by alarichartsock** [comment]
Getting this as well. @user216 do you remember roughly what you did to resolve it?
