### ISSUE TITLE
follow settings of parrent node

### ISSUE THREAD

**Issue by user216** [giuspen/cherrytree#1481]
in old (0.39) , none C++ versions, cherrytree remembered "type" of parent  note and follow this type when I create  child note.

But in new versions of cherrytree I need to choose everytime type of node (in my case I use always  'syntax-hightiting' type, so its annoying a lot of to make changing of note type everytime when I create new note :(

Can you please take back "following parent type note" feature  in you new releases?

**Comment by giuspen** [comment]
Ok

**Comment by giuspen** [comment]
will be ok in 0.99.30

**Comment by andrii482** [comment]
thanks for fix !
