### ISSUE TITLE
just inform that therre is one more 'cherrytree' :)

### ISSUE THREAD

**Issue by user216** [giuspen/cherrytree#1483]
so in case if in system this two project should be installed, possible conflicts when invoking app's

https://pypi.org/project/cherrytree/

**Comment by steveno** [comment]
That project is significantly younger (first commit was in 2018) and it also isn't similar at all except the name. I wouldn't worry about it myself.

**Comment by giuspen** [comment]
Yep this is younger, too late name taken 😁
