### ISSUE TITLE
Compilation problems: Linux Mint & Kali Linux latest versions

### ISSUE THREAD

**Issue by pedroflor** [giuspen/cherrytree#1485]
**Linux Mint & Kali Linux updated on 09/Jan/2021**

**The bug**
Build errors. Can't compile at all.

**To Reproduce**
1. Download https://github.com/giuspen/cherrytree/archive/0.99.29.tar.gz
2. Follow the procedure to build from: https://github.com/giuspen/cherrytree#building-cherrytree-on-ubuntu-2004
3. Get the errors

**Errors**
```
-- CT_VERSION = 0.99.29
Tests are ON
CMake Error at tests/CMakeLists.txt:4 (add_subdirectory):
  The source directory

    /path/to/cherrytree-0.99.29/tests/googletest

  does not contain a CMakeLists.txt file.


CMake Error at tests/CMakeLists.txt:18 (set_target_properties):
  set_target_properties Can not find target to add properties to: gtest


CMake Error at tests/CMakeLists.txt:19 (set_target_properties):
  set_target_properties Can not find target to add properties to: gtest_main


CMake Error at tests/CMakeLists.txt:20 (set_target_properties):
  set_target_properties Can not find target to add properties to: gmock


CMake Error at tests/CMakeLists.txt:21 (set_target_properties):
  set_target_properties Can not find target to add properties to: gmock_main


-- Configuring incomplete, errors occurred!
See also "/path/to/cherrytree-0.99.29/build/CMakeFiles/CMakeOutput.log".
```

**This problems it's NOT present in cherrytree-0.99.23**

Attaching CMakeOoutput.log
[CMakeOutput.log](https://github.com/giuspen/cherrytree/files/5792045/CMakeOutput.log)

**Comment by giuspen** [comment]
You cannot rely on the GitHub tarball because there are submodules. Please look at https://www.giuspen.com/cherrytree/#downl for the tarball or clone from git and then get the submodules code with the appropriate command

**Comment by pedroflor** [comment]
> You cannot rely on the GitHub tarball because there are submodules. Please look at https://www.giuspen.com/cherrytree/#downl for the tarball or clone from git and then get the submodules code with the appropriate command

Thanks a lot!!! A happy cherryTree user :+1:
