### ISSUE TITLE
Languages

### ISSUE THREAD

**Issue by Camilot55** [giuspen/cherrytree#1496]
Hello Giuseppe.
You can make sure that full names are displayed instead of language abbreviations.
For example like this:
![я](https://user-images.githubusercontent.com/76065578/105210504-f16d4d80-5b6c-11eb-8cc3-df1e06cc9ee7.png)

`const inline static std::array<const gchar*, 21> AVAILABLE_LANGS {
    LANG_DEFAULT, "Czech", "German", "Greek", "English", "Spanish", "Finnish", "French", "Armenian", "Italian",
    "Japanese", "Lithuanian", "Dutch", "Polish", "Portuguese Brazil", "Russian", "Slovenian", "Swedish", "Turkish", "Ukrainian", "Chinese (simplified)"
};

/*
const inline static std::array<const gchar*, 21> AVAILABLE_LANGS {
    LANG_DEFAULT, "cs", "de", "el", "en", "es", "fi", "fr", "hy", "it",
    "ja", "lt", "nl", "pl", "pt_BR", "ru", "sl", "sv", "tr", "uk", "zh_CN"
};
*/
`

**Comment by MJimitater** [comment]
@Camilot55 maybe best to do a PR for this?

**Comment by Camilot55** [comment]
> @ Camilot55 может лучше сделать пиар для этого?

Что?

**Comment by Camilot55** [comment]
> @Camilot55 maybe best to do a PR for this?

What?

**Comment by Camilot55** [comment]
And why is it bad to display the full name of the country for the language?

**Comment by giuspen** [comment]
@Camilot55 it is a fair request, @MJimitater was just asking if you could implement the change yourself and submit a PR (Pull Request), anyway should be a quick fix I'll try and do myself soon

**Comment by Camilot55** [comment]
@ Guispen I tried to make changes, but an error occurs, which I have not figured out yet. But if you do it faster please let us know!

**Comment by giuspen** [comment]
Don't worry it's a quick fix
