### ISSUE TITLE
"Search in all nodes contents" makes CT freeze

### ISSUE THREAD

**Issue by GoogleCodeExporter** [giuspen/cherrytree#15]
```
http://www.giuspen.com/topic/search-in-all-nodes-contents-makes-ct-freeze/
```

Original issue reported on code.google.com by `giuspen@gmail.com` on 28 Nov 2014 at 10:46

Attachments:
- [ct-search-bug.zip](https://storage.googleapis.com/google-code-attachments/giuspen-cherrytree/issue-15/comment-0/ct-search-bug.zip)

**Comment by L0uac** [comment]
This issue is still here, but not always reproductible. How can I help ?

**Comment by giuspen** [comment]
You can help either trying to find a way to have it systematically or trying to understand where exactly the application hangs

**Comment by RalfJahns** [comment]
I see this bug when I search by clicking the "	magnifying glass icon" more than once (first search works):

sel node id=29, seq=6
sel node id=38, seq=1
sel node id=39, seq=2
sel node id=21, seq=4
sel node id=56, seq=13
/usr/share/cherrytree/modules/core.py:4683: GtkWarning: IA__gtk_text_iter_set_line_offset: assertion 'char_on_line <= chars_in_line' failed
  text_buffer.place_cursor(target)
sel node id=29, seq=6
sel node id=38, seq=1

**Comment by txe** [comment]
too old
