### ISSUE TITLE
Exit code block via keyboard?

### ISSUE THREAD

**Issue by skahan** [giuspen/cherrytree#150]
I'm using ubuntu cherrytree 0.37.1. 

In rich text node, after inserting and editing code block, is there a keyboard shortcut to exit code block and return to rich text editing? 

Also, I wanted to confirm that there's no way to cause code blocks to auto-adjust height (checking pref>rich text>misc 'Expand CodeBoxes Automatically' doesn't do anything).

Thanks.

**Comment by giuspen** [comment]
Hi, the auto adjust height works only after you press enter and the
vertical scrollbar would need to appear.

Currently there's no shortcut to exit the code box and move the cursor just
after, if this is your request, I will consider support this

**Comment by skahan** [comment]
Yes please I would like the request the ability to exit code blocks via keyboard shortcut. Thanks!

**Comment by giuspen** [comment]
I implemented the shortcut Ctrl+Spacebar not only to leave the codebox as you asked but also to enter the codebox if the cursor is just before a codebox. I would appreciate if you could test this feature that is currently in the git master HEAD. If you need me to create a package for you let me know.

**Comment by skahan** [comment]
I'd be happy to test but I'm embarrassed to say don't know too much about
git, and I'm also very new too linux so I don't even know for sure how to
do a package install. If you want to provide instructions on either I'm
sure I can manage to follow them and I'd be able to test it out today.

**Comment by giuspen** [comment]
Please try to download http://www.giuspen.com/software/cherrytree_0.37.1-2+4_all.deb and then just double click on it - Ubuntu should guide you through the installation

**Comment by skahan** [comment]
Guiseppe - downloaded and installed. I tried both into and out of codebox
with ctrl + space and both work perfectly. Thanks very much!

**Comment by giuspen** [comment]
Great, thanks for testing, take care
