### ISSUE TITLE
Background color

### ISSUE THREAD

**Issue by s0i37** [giuspen/cherrytree#1500]
**Is your feature request related to a problem? Please describe.**
It is very nessecary to add changing background color feature. Like a keepnote.

**Describe the solution you'd like**
Like a keepnote.

**Comment by giuspen** [comment]
It is possible from preferences dialog tab themes to select some predefined themes (e.g. classic for white background) but anyway soon I'll improve the selection as also discussed in https://github.com/giuspen/cherrytree/issues/1362

**Comment by giuspen** [comment]
The implementation is complete and will be available in the upcoming 0.99.31
