### ISSUE TITLE
Has put "insert special symbol" icon on a toolbar, but nothing happens when pressing it.

### ISSUE THREAD

**Issue by Antonyjj** [giuspen/cherrytree#1503]
CherryTree 0.99.25 , Win7x64

Has put "insert special symbol" icon on a toolbar, but nothing happens when pressing it. It works if call it from Edin Menu though.

And some minor request. When dragging node by mouse (in a tree frame) it becomes long bar that covers its currenst position (is showed by line), so you need to move it to the right first to be able to see where it is actually pointing.
![изображение](https://user-images.githubusercontent.com/73707692/105985532-a1324600-60ac-11eb-81ad-14b52ea8ccda.png)
![изображение](https://user-images.githubusercontent.com/73707692/105985633-c4f58c00-60ac-11eb-892c-cbae2eab1a28.png)

It would be much more convinient if from the first dragging attempt it would show  the bar (with dragged node) shifted a bit to the right to see the line (that shows its anticipated position).

**Comment by giuspen** [comment]
thanks I reworked the symbols to pop up in a dialog, this will make it work also from the toolbar
