### ISSUE TITLE
Ctrl+V for Windows 10.

### ISSUE THREAD

**Issue by HEDGHOK** [giuspen/cherrytree#151]
Hello.
My problem is with the Windows 10, when you copy text from any document, website, it does not matter. Do not copy keys by combining Сtrl + V. Please correct, that would be after you copy into your program you can insert text. Overall, the program is very good, you fellows

**Comment by HEDGHOK** [comment]
Please give an answer to my report. I would be grateful, it is very important to me.

**Comment by giuspen** [comment]
Hi, is only the Ctrl+V keyboard shortcut not working or also if you right click and select Paste doesn't work?

**Comment by HEDGHOK** [comment]
Not only inserts at key combination and it works through the context menu. I suspect that in fact it merely copies but does not display the information, I tested this theory on earlier versions of the program. There, as soon as the program has been installed a married paste, but after the first closing of the program and opening it again do it anymore. After you reinstall the program to even more rannyu version when opening fyla, seen the text that is inserted when it is not displayed. So I realized that it just does not display information. Thank you for attention!

**Comment by giuspen** [comment]
I plan to try to upgrade the library in use from the old gtk2 to the new
gtk3 soon and hopefully it will work better in win10

**Comment by HEDGHOK** [comment]
Hopefully this will work. Thank you for attention.

**Comment by txe** [comment]
Tested on Win10, Ctrl+V is working
