### ISSUE TITLE
Menu Languages

### ISSUE THREAD

**Issue by Camilot55** [giuspen/cherrytree#1511]
The question is, you can make the national flag icons appear on the left in the language selection menu opposite each country.

Flag of Russia - Russian
Flag of Bulgaria - Bulgarian
Flag of Italy - Italian

Icons in the archive
[Lang.zip](https://github.com/giuspen/cherrytree/files/5939005/Lang.zip)

**Comment by giuspen** [comment]
Should be ok for most of the flags but I have some doubts about the English which being generic for now (not en_US or en_GB) probably should show the origin of the language which is GB, not US.

**Comment by Camilot55** [comment]
You can put a flag like this

![English](https://user-images.githubusercontent.com/76065578/107228673-bd37cf00-6a3e-11eb-8d95-c2f3c1379ab4.jpg)

**Comment by Camilot55** [comment]
Flag svg
[ct_en_GB.zip](https://github.com/giuspen/cherrytree/files/5944145/ct_en_GB.zip)

**Comment by Camilot55** [comment]
Hello Giuseppe.
 I work at the Russian Federal Nuclear Center and some of the employees are actively using your program.
 They sent me some comments and suggestions on the program, I will implement them and send you.
 Thank.

**Comment by giuspen** [comment]
Hi Viktor, that's great thanks if you get stuck let me know and I'll help ;)

**Comment by Camilot55** [comment]
OK, Thank.

**Comment by Camilot55** [comment]
Hello Giuseppe.
I have sent you my suggestions by email, please let us know about your decision. If your decision is positive, should I make a pull request or will you add it yourself?

**Comment by giuspen** [comment]
Hi Viktor it is easier for me if you submit a pull request with the changes you would like to be merged in

**Comment by giuspen** [comment]
I added the flags, let me close this now
