### ISSUE TITLE
Background color crash

### ISSUE THREAD

**Issue by martalorentte** [giuspen/cherrytree#1512]
**Version, Operative system**
MacOs BigSur, version 11.1

**Describe the bug**
When changing the background color of a word/sentence to a personalized one, Cherrytree crashes and it shows "Segmentation fault: 11" on the terminal. 
If you choose one of the colors that the window already offers, it works just fine. It only happens when creating a personalized color or choosing one that you have previously created. It crashes the moment that you click on "select".

**To Reproduce**
1. Select a word/sentence.
2. Click on 'pick a background color'. 
3. On personalize section: Click on [+] button, then click on "select" // Choose a previous personalized color, then click on "select".
4. Cherrytree crashes and shows the error "Segmentation fault: 11" on the terminal.

**Comment by giuspen** [comment]
Thanks, will be ok in 0.99.31

**Comment by martalorentte** [comment]
Thank you so much!
I pulled the code and it definitely works! 😄
