### ISSUE TITLE
Delete word using Ctrl+Del

### ISSUE THREAD

**Issue by JohnStd** [giuspen/cherrytree#1513]
It is not possible to delete a word to the right of the cursor by pressing Ctrl+Del. When I would like to delete a word which is placed right to cursor, it attempts to delete current branch.

Ctrl+Del is used to delete next word (right to cursor) in other apps like browsers or common text editors. But in CherryTree it could cause whole branch delete. This can cause the entire branch to be accidentally deleted if you click Yes in the dialog box.

So, I think it is better to use Ctrl+Del to delete word next to cursor.

p.s. Is it possible to restore deleted branch? And how?

CherryTree 0.99.29
Linux

**Comment by Camilot55** [comment]
Yes.  Remote branch can be restored if you have enabled in the settings "Create a Backup Copy Before Saving"

**Comment by Camilot55** [comment]
Saving
Autosave Every x Minutes - Saves the working document every x minutes, where x represents the number defined in this setting.
Autosave on Quit - Saves the document upon closing Cherrytree.
Create a Backup Copy Before Saving - Stores a copy of the previous version before saving the new version. Backups are stored in the same directory as the current document.

To open a backup:
Rename the backup file, deleting the ~ characters appended to its extension.
Open the backup file within Cherrytree.
Number of Backups to Keep - Defines the number of backups to keep. The oldest backup is removed when this limit is exceeded.


This also applies to autosaves that run on a time interval. For example, if your application is configured to save every 5 minutes, Cherrytree creates a backup every five minutes. When the backup limit is exceeded, a backup is cycled out every 5 minutes.

**Comment by giuspen** [comment]
I didn't know about this Ctrl+Del being a standard to delete a word right to the cursor.
So maybe I'll change to Ctrl+Shift+Del.
@Camilot55 is right about restoring a deleted node that's the only way

**Comment by JohnStd** [comment]
@giuspen Yes, it would actually be better if the shortcut for deletion will be Ctrl+Shift+Del or somthing similar. 
For now, I turned off (removed) Ctrl+Del in settings and it works now for deleting next word as expected to be.

**Comment by giuspen** [comment]
Turns out Ctrl+Shift+Delete removes the following chars in the current line. I'll just remove the shortcut and if the user wants one will set it up in the preferences
