### ISSUE TITLE
Add more "Pentesting" icons

### ISSUE THREAD

**Issue by pedroflor** [giuspen/cherrytree#1514]
**Feature request**
Would be nice to have some extra icons for diferent stuff... like pentesting. I'm a visual guy.

Again, a picture is worth a thousand words :)

**Please refer to the following image to see the requested feature**
![new_icons_cherrytree](https://user-images.githubusercontent.com/3332674/107703882-b1dce180-6c92-11eb-8032-dc7232502b69.png)
I'm not a graphic designer, but I can do my best if you provides me some guide.

Best regards.

**Comment by giuspen** [comment]
If you can start with a contained set of images you would like cherrytree to support, I can then see if I find something free around to support that topic. Cherrytree is using vectorial (svg) free icons.

**Comment by pedroflor** [comment]
Hi @giuspen ! thanks for writeback.
I have a few free svg icons... 
I would like to know what code needs to be modified.

Thanks again.

**Comment by giuspen** [comment]
I'm going to add some icons to those selectable as node icons shortly and reference the commit here so you can see the changes

**Comment by giuspen** [comment]
You can see I referenced the last commit to this issue and in that commit you can see the code that needs to change. That array has to be increases in size and added your svg icon names - svg to be placed in icons folder.

**Comment by metal450** [comment]
If you're willing to add a few more icons, there are a few topics I'd love (I've been overriding them on each of my own PCs, but it would be great if they were available by default).  I've attached the SVGs I'm using. I found them on free icon sites, but I didn't explicitly check the license.

Topics are:
*Money/Finance - I used dollar bills
*Shopping - I used a shopping cart
*Photography - I used a camera
*Videos/Movies - I used a clapperboard
*Work - I used a briefcase
*Travel - I used a globe/earth
[icons.zip](https://github.com/giuspen/cherrytree/files/6047670/icons.zip)

Thanks in advance! :)

**Comment by pedroflor** [comment]
Hi @metal450, great icons!

**Comment by giuspen** [comment]
Yes I'll add either the ones you attached or similar

**Comment by metal450** [comment]
Awesome, thanks! :)

**Comment by pedroflor** [comment]
Hi @giuspen!
I'm attaching the new (ugly) icons. 
[new_icons.zip](https://github.com/giuspen/cherrytree/files/6062993/new_icons.zip)

I also modified the file [ct_const.h](https://github.com/giuspen/cherrytree/pull/1542/commits/57b359ae906dc9bd9b119a37c1bc36d618b4440b)

**Comment by giuspen** [comment]
done

**Comment by pedroflor** [comment]
Thanks a lot!
