### ISSUE TITLE
Corrupt database when upgrading cherrytree from 0.39.4 to 0.99.30

### ISSUE THREAD

**Issue by gituser789** [giuspen/cherrytree#1515]
I upgraded cherrytree from 0.39.4 to 0.99.30.
I have two cherrytree book, the small one is about 50MB, everything works fine with the new version.
The big one (about 1.9GB), throws an error about corrupt database. In 0.39.4, everything works fine. I also tried to open some backup-files 'database.cbt~~~' but the problem is the same.

What can i do next for troubleshooting?

[2021-02-12 08:25:11.480] [   ] [warning]
=== Database problems report ===
: *** in database main ***
On tree page 402148 cell 0: invalid page number -1796660343
On tree page 1003456 cell 0: invalid page number 1847773131
On tree page 988355 cell 0: invalid page number -1619505815
On tree page 167990 cell 0: invalid page number -879197794
On tree page 150781 cell 0: invalid page number 1962053489
Page 138498 is never used
Page 138499 is never used
Page 138500 is never used
Page 138501 is never used
Page 138502 is never used
Page 138503 is never used
Page 138504 is never used
Page 138505 is never used
Page 138506 is never used
Page 138507 is never used
Page 138508 is never used
Page 138509 is never used
Page 138510 is never used
Page 138511 is never used
Page 138512 is never used
Page 138513 is never used
Page 138514 is never used
Page 138515 is never used
Page 138516 is never used
Page 138517 is never used
Page 138518 is never used
Page 138519 is never used
Page 138520 is never used
Page 138521 is never used
Page 138522 is never used
Page 138523 is never used
Page 138524 is never used
Page 138525 is never used
Page 138526 is never used
Page 138527 is never used
Page 138528 is never used
Page 138529 is never used
Page 138530 is never used
Page 138531 is never used
Page 138532 is never used
Page 138533 is never used
Page 138534 is never used
Page 138535 is never used
Page 138536 is never used
Page 138537 is never used
Page 138538 is never used
Page 138539 is never used
Page 138540 is never used
Page 138541 is never used
Page 138542 is never used
Page 138543 is never used
Page 138544 is never used
Page 138545 is never used
Page 138546 is never used
Page 138547 is never used
Page 138548 is never used
Page 138549 is never used
Page 138550 is never used
Page 138551 is never used
Page 138552 is never used
Page 138553 is never used
Page 138554 is never used
Page 138555 is never used
Page 138556 is never used
Page 138557 is never used
Page 138558 is never used
Page 138559 is never used
Page 138560 is never used
Page 138561 is never used
Page 138562 is never used
Page 138563 is never used
Page 138564 is never used
Page 138565 is never used
Page 138566 is never used
Page 138567 is never used
Page 138568 is never used
Page 138569 is never used
Page 138570 is never used
Page 138571 is never used
Page 138572 is never used
Page 138573 is never used
Page 138574 is never used
Page 138575 is never used
Page 138576 is never used
Page 138577 is never used
Page 138578 is never used
Page 138579 is never used
Page 138580 is never used
Page 138581 is never used
Page 138582 is never used
Page 138583 is never used
Page 138584 is never used
Page 138585 is never used
Page 138586 is never used
Page 138587 is never used
Page 138588 is never used
Page 138589 is never used
Page 138590 is never used
Page 138591 is never used
Page 138592 is never used

[2021-02-12 08:25:15.180] [   ] [error]

**Comment by giuspen** [comment]
Open again with 0.39.4 and then save and vacuum. If still doesn't work still from 0.39.4 try File--Save as and rewrite the whole database to another file

**Comment by gituser789** [comment]
I opened the database in 0.39.4, made a change, saved it and openend it in 0.99.30 again - 'corrupt database'.
Next, in 0.39.4 I uses 'save as' cbt and xml - both actions failed 'write failed - writing to disk / tree to xml.

Note: When doing everyday work in 0.39.4, everything is fine. 

I also opened every single page in 0.39.4, to see if there is may a broken page, but seems not. 
Is there another way to debug the database? What can I do next?

**Comment by giuspen** [comment]
Ok rather than doing file--save as, try to export--to cherrytree document and see if you can export parts of the tree (a node and all its submodes and so on). If that works you can maybe successfully export most of the data and find out which is the node that has issues

**Comment by gituser789** [comment]
That works! I partly exported the database and found one broken node. With many import files, I build up the new database again. Now it is also working under 0.99.30. Thanks a lot.

**Comment by giuspen** [comment]
Great!
