### ISSUE TITLE
All images missing on import, screen capture feature, Cherrytree in AppImage, Thanks and regards.

### ISSUE THREAD

**Issue by joejac** [giuspen/cherrytree#1516]
First, I thank you for sharing this nice program.
I have a few suggestions:
All my personal knowledge-base, and my memory is stored in the venerable KeepNote, but it is abandoned and not running in almost any modern Linux OSs.
1. Cherrytree imports well the text of all KeepNote notes but no images at all, all **images are missing**.
2. I depend of taking quick **screen captures** from web pages parts of images and videos for my research and of other programs for documentation. Can you please  include a screen capture function, like for example, "control insert" which would go to next program opened and would allow to capture a region of the screen and automatically inserts the capture image inside the cursor position in Cherrytree document.
3. Last, to pack Cherrytree in AppImage, since Flatpak consumes too much resources of the machine.
Thank you and regards
Jose

**Comment by giuspen** [comment]
I can fix the import from keepnote if you attach an example that I can use to verify and fix the issue. Point 2 can do in future but other tasks have higher priority. Point 3 unfortunately no, cannot spend time on it, you have to try to build appimage yourself.

**Comment by joejac** [comment]
Jose C. has shared a OneDrive file with you. To view it, click the link below.
<https://1drv.ms/u/s!AuqM5-ajj7JliIFid60GOqmg6mymAA>
[https://r1.res.office365.com/owa/prem/images/dc-generic_20.png]<https://1drv.ms/u/s!AuqM5-ajj7JliIFid60GOqmg6mymAA>
Block de Notas General.tar.gz<https://1drv.ms/u/s!AuqM5-ajj7JliIFid60GOqmg6mymAA>

Hello Mr. Giuseppe and thank you for your kind answer.
1. I am sending a reduced copy of my Personal KeepNote files since the original is big, almost 1GB. Please do not make the link of this archive file public, thanks.
2. Thank you for including the screen capture feature in your task list, is understandable you have other priorities. I will check from time to time your website to see when this feature is released.
3. Well, the real issue is not the AppImage, the real problem is that I work with MX Linux KDE 19.3, the latest version. I already talked with the developers and this is what they told me, and I quote:
"they will not work on 'buster' based Debian derivatives.
You'll have to stick with the 0.39.4 series provided by MX/antiX (Debian does not even provide any cherrytree debs for buster).
cherrytree 0.99 series will come with MX/antiX 21 (Debian bullseye) and not sooner."
This means probably I will not be able to run Cherrytree 0.99 series in a couple of years. I do not know if you have any suggestion, sorry for my ignorance in the issue, I am not a developer only a user.
Best regards and thank you for your time.
José
________________________________

**Comment by joejac** [comment]
Hello Giuseppe, please let me know when you downloaded the file to delete the link, thank you and regards.

**Comment by giuspen** [comment]
Hi @joejac I have just downloaded Block de Notas General.tar.gz
GitHub is public everyone can access here, you have to send me privately by email stuff you don't want to make public.

**Comment by giuspen** [comment]
the images import should work fine in upcoming 0.99.31

**Comment by joejac** [comment]
> the images import should work fine in upcoming 0.99.31

Thank you very much Giuseppe.
Regards
José
