### ISSUE TITLE
Modern interface as additional option

### ISSUE THREAD

**Issue by ony2020** [giuspen/cherrytree#1517]
![Cherrywhite (1)](https://user-images.githubusercontent.com/78557328/107865174-1bf8b080-6e64-11eb-9fb1-37063650c4e9.jpg)

![Cherrydark](https://user-images.githubusercontent.com/78557328/107865175-2450eb80-6e64-11eb-93d6-f03631b8fd05.png)

**Comment by Sisyfos3** [comment]
Why not just remove unwanted entries from the toolbar?? (File/Preferences/Toolbar)
Much faster than having Giuspen coding for a new interface (I think he has more important things to attend to) and you get exactly what you want on the toolbar.
Just my 2 cents... 
/Sisyfos

**Comment by ony2020** [comment]
Frankly I am quite happy with app as it is, Just I wanted to share a modern look for Cherry-tree and see what giuspen/ cherrytree Users will say about it especially that open source projects lacking in this domain,  and I already know that the priority is to port the app to gtkmm

**Comment by giuspen** [comment]
The porting to Gtkmm3 is done fortunately.
Discussions about improving parts of the ui are welcome but unless it's a minor change a large interaction and consent from other users is required
