### ISSUE TITLE
PDF Export: cannot open PDF

### ISSUE THREAD

**Issue by MJimitater** [giuspen/cherrytree#1519]
**Version, Operative system**
CherryTree 0.99.30 on Windows 10

**Describe the bug**
Exported a node to PDF, but trying to open the PDF (in Adobe Acrobat Reader 2017) gives Error Message: `There was an error processing a page. There was a problem reading this document (135).`

**To Reproduce**
Find [attached](https://github.com/giuspen/cherrytree/files/5981612/RUL.zip) the node that gives me problems with exporting to PDF
1. Open node and go to `Export -> Export to PDF`
2. Save as `RUL.pdf` file
3. Try to open pdf file with reader (in my case Acrobat Reader)

**Screenshots**
![CT_bug](https://user-images.githubusercontent.com/26901261/107949044-f6b78f80-6f94-11eb-9a97-e4b683405dcf.PNG)

Not sure if the fault is on my end, please let me know. And do let me know if I can provide/help anything more.
Anyway, I love CT, I use it everyday, huge thanks to @giuspen and many other brave collaborators for this awesome software!!

**Comment by unKn0wnUser453** [comment]
You can use google chrome....

**Comment by unKn0wnUser453** [comment]
I found out a better / more stylish way to export to PDF from cherrytree the other day (see below)
Export the cherrytree to HTML

# Create PDF from Cherrytree HTML
## Windows
### Install
https://wkhtmltopdf.org/downloads.html
pip3 install pdfkit
### Run
```python
import pdfkit
config = pdfkit.configuration(wkhtmltopdf= r'C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe')
options={'enable-local-file-access':None}
pdfkit.from_file('.\index.html','test.pdf', configuration=config, options=options)
```

**Comment by MJimitater** [comment]
@unKn0wnUser453 Thanks for the work-around, it works nicely!!
Since I do strive for CT to not have this bug, I'll leave this issue open for the time being.

**Comment by giuspen** [comment]
It will be hard to understand what acrobat reader 2017 doesn't like... any log produced from acrobat reader mentioning content?

**Comment by MJimitater** [comment]
@giuspen thanks for your take on this, I haven't dug deeply on this, but I can't get my hands on an Acrobat Reader log file right away.
But, as @unKn0wnUser453  has pointed out, interestingly, displaying the PDF in Google Chrome works! And it works also in Edge Browser. I also tried Firefox, but, similarly to Acrobat Reader, it only shows an error message.
I could guess it to be perhaps a problem with the PDF viewers and not a CT issue, but it seems far-fetched that even Acrobat doesn't work properly.
I could only guess what causes the issue with some PDF viewers and others not. 
What do you think?

**Comment by giuspen** [comment]
Can you narrow down what kind of content causes the issue or us it happening even with a node with only written "hello world"

**Comment by MJimitater** [comment]
Thanks, I tried to narrow it down, but the issue doesn't occur consistently enough, so I'll keep my eyes open and will report back if I have any new insights

**Comment by MJimitater** [comment]
Closing for now until further notice

**Comment by giuspen** [comment]
Ok thanks
