### ISSUE TITLE
cherrytree won't save or save as on Kali Linux

### ISSUE THREAD

**Issue by luigithub11** [giuspen/cherrytree#1527]
So I just recently started using CherryTree 0.99.9 on Kali Linux, I am running it in my VM Workstation Player. I actually used cherrytree to keep my notes upon learning more on using Linux. My problem is that when I am about to save my notes, it does not save anything, may it be on a format of SQLite or XML. 

1. Go to CherryTree  0.99.9 app built in on Kali Linux.
2. Click on or create any text. 
3. Click on Save/Save As and choose on the folder you want to put it in.
4. No error message produced but once you click Save, nothing will happen. 

I also tried running cherrytree on my terminal and it gives me this error.

Unable to init server: Could not connect: Connection refused

(cherrytree:2834): Gtk-WARNING **: 13:16:44.489:cannot open display:

Thanks.

**Comment by giuspen** [comment]
Upgrade to 0.99.30 please

**Comment by giuspen** [comment]
...or latest from GitHub

**Comment by luigithub11** [comment]
Thanks,  man. I'll try it out later.

**Comment by luigithub11** [comment]
Everything worked after reinstalling the latest version of CherryTree, I was not able to save my save my notes using it.
