### ISSUE TITLE
Unable to copy table cell contents using keyboard shortcut Ctrl + C (Copy as Plain Text)

### ISSUE THREAD

**Issue by pinkLagoon** [giuspen/cherrytree#1528]
**Version, Operative system**
Windows 10
Cherrytree 0.99.30

**Describe the bug**
Using the keyboard shortcut for Copy as Plain Text (Ctrl + C for me), I would have expected the selected text in a cell in a table to be copied to the clipboard. Instead, the clipboard remains unchanged.

**To Reproduce**
1. Create a table with some content in it.
2. Select text within a cell in the table.
3. Press the keyboard shortcut for Copy as Plain Text.
4. Paste the contents into Notepad. If the clipboard does not contain the previously selected text, the issue remains.

**Comment by giuspen** [comment]
thanks will be ok in 0.99.32
