### ISSUE TITLE
Replace in Node hangs CherryTree

### ISSUE THREAD

**Issue by tom-i** [giuspen/cherrytree#153]
Actual result:
When I want replace some text inside some node, my cherryTree always hangs.

Steps to reproduce:
1. Click on "Search" menu
2. Click on "Replace in Selected Node and Subnodes contents"
3. Fill dialog with strings.
4. Click on "OK" button.
BUG - CherryTree hangs.

Version: GIT 0.37.1

**Comment by giuspen** [comment]
I cannot reproduce the problem. I need a document where the problem
happens, knowing the node to select and the string to put in the
search/replace entries

**Comment by txe** [comment]
Can't be repeated
