### ISSUE TITLE
hpaned_pos limit is too small for the right side tree

### ISSUE THREAD

**Issue by onetuser** [giuspen/cherrytree#1534]
**Version, Operative system**
0.99.31, Linux

**Describe the bug**
Width of tree panel looks limited to 
hpaned_pos=958
(if edit config and set greater value, cherrytree resets to this value on start).
However together with option 'Display Tree on the Right Side' this value is too small: right side tree takes too much space every time cherrytree restarts.

**To Reproduce**
1. Enable 'Display Tree on the Right Side'
2. Make width of tree panel small.
3. Restart cherrytree
4. Width of tree panel is large, even larger than width of text panel on high resolution monitor.

**Comment by giuspen** [comment]
Mhmm strange I cannot reproduce this... maybe you can share your config.cfg?

**Comment by onetuser** [comment]
> Mhmm strange I cannot reproduce this... maybe you can share your config.cfg?

`[state]
toolbar_visible=true
win_is_maximized=true
win_position_x=10
win_position_y=10
win_size_w=963
win_size_h=630
hpaned_pos=958
tree_visible=true
link_type=webs
show_node_name_header=true
nodes_on_node_name_header=0
toolbar_icon_size=1
fg=#9090eeee9090

[tree]
rest_exp_coll=0
nodes_bookm_exp=false
nodes_icons=c
aux_icon_hide=false
default_icon_text=25
tree_right_side=true
cherry_wrap_ena=false
cherry_wrap_width=130
tree_click_focus_text=false
tree_click_expand=false

[editor]
syntax_highlighting=custom-colors
auto_syn_highl=sh
rt_style_scheme=solarized-dark
pt_style_scheme=solarized-dark
ta_style_scheme=user-2
co_style_scheme=cobalt
enable_spell_check=false
spell_check_lang=en_US
show_line_numbers=false
scroll_beyond_last_line=true
spaces_instead_tabs=false
tabs_width=4
anchor_size=16
embfile_icon_size=48
embfile_show_filename=true
embfile_max_size=10
line_wrapping=true
auto_smart_quotes=false
triple_click_paragraph=false
enable_symbol_autoreplace=true
wrapping_indent=-14
auto_indent=true
rt_show_white_spaces=false
pt_show_white_spaces=true
rt_highl_curr_line=true
pt_highl_curr_line=true
rt_highl_match_bra=false
pt_highl_match_bra=true
space_around_lines=0
relative_wrapped_space=50
h_rule====================================================================================================
special_chars=“”„‘’•◇▪▸☐☑☒★…‰€©®™°↓↑→←↔↵⇓⇑⇒⇐⇔»«▼▲►◄≤≥≠≈±¹²³½¼⅛×÷∞ø∑σ√∫ΔδΠπΣΦΩωαβγεηλμ☺☻☼♥♣♦✔♀♂♪♫✝
selword_chars=.-@
chars_listbul=•◇▪-→⇒
chars_toc=▸•◇▪
chars_todo=☐☑☒
chars_smart_dquote=“”
chars_smart_squote=‘’
latest_tag_prop=weight,foreground
latest_tag_val=heavy,#9090eeee9090
timestamp_format=%Y/%m/%d - %H:%M
links_underline=true
links_relative=true
weblink_custom_on=false
filelink_custom_on=false
folderlink_custom_on=false
weblink_custom_act=firefox %s &
filelink_custom_act=xdg-open "file://%s" &
folderlink_custom_act=xdg-open "file://%s" &

[codebox]
codebox_width=500
codebox_height=100
codebox_width_pixels=true
codebox_line_num=false
codebox_match_bra=true
codebox_syn_highl=plain-text
codebox_auto_resize=false

[table]
table_rows=3
table_columns=3
table_col_width=60

[fonts]
rt_font=Sans 19
pt_font=Sans 12
tree_font=Sans 12
code_font=Monospace 16

[colors]
tt_def_fg=#ffffff
tt_def_bg=#001b33
monospace_bg=#7f7f7f
ms_dedic_font=false
monospace_font=Monospace 9
color_palette=#000000:#ffffff:#7f7f7f:#ff0000:#a020f0:#0000ff:#add8e6:#00ff00:#ffff00:#ffa500:#e6e6fa:#a52a2a:#8b6914:#1e90ff:#ffc0cb:#90ee90:#1a1a1a:#4d4d4d:#bfbfbf:#e5e5e5
col_link_webs=#00008989ffff
col_link_node=#071c838e071c
col_link_file=#8b8b69691414
col_link_fold=#7f7f7f7f7f7f
style_1_text_fg=#ffffff
style_1_text_bg=#000000
style_1_sel_fg=#ffffff
style_1_sel_bg=#0088ff
style_1_cusor=#ffffff
style_1_curr_line_bg=#003b70
style_1_linenum_fg=#777777
style_1_linenum_bg=#000d1a
style_2_text_fg=#000000
style_2_text_bg=#ffffff
style_2_sel_fg=#ffffff
style_2_sel_bg=#43ace8
style_2_cusor=#000000
style_2_curr_line_bg=#eef6ff
style_2_linenum_fg=#000000
style_2_linenum_bg=#d6d2d0

[misc]
toolbar_ui_list=tree_add_node,tree_add_subnode,separator,go_node_prev,go_node_next,separator,*,ct_save,export_pdf,separator,find_in_allnodes,separator,handle_bull_list,handle_num_list,handle_todo_list,fmt_indent,fmt_unindent,separator,handle_image,handle_table,handle_codebox,handle_embfile,handle_link,handle_anchor,separator,fmt_clone,fmt_latest,fmt_rm,fmt_color_fg,fmt_color_bg,fmt_bold,fmt_italic,fmt_underline,fmt_strikethrough,fmt_h1,fmt_h2,fmt_h3,fmt_small,fmt_superscript,fmt_subscript,fmt_monospace
systray=false
start_on_systray=false
autosave_on=false
autosave_val=1
check_version=false
word_count=false
reload_doc_last=true
win_title_doc_dir=true
mod_time_sentinel=false
backup_copy=false
backup_num=3
autosave_on_quit=false
enable_custom_backup_dir=false
custom_backup_dir=
limit_undoable_steps=20

[codexec_term]
custom_codexec_term=
`

![screen](https://user-images.githubusercontent.com/43379855/109581176-ff6ba200-7b0c-11eb-8229-52f80d34e1c4.png)

**Comment by giuspen** [comment]
Will be ok in 0.99.32
