### ISSUE TITLE
To question #1362

### ISSUE THREAD

**Issue by Camilot55** [giuspen/cherrytree#1538]
Hi Giuseppe.
You can make it so that User-1 and User-2 tabs in the Theme menu become active only when the user has selected them.
At that it is not clear what to attribute them to!

**Comment by Camilot55** [comment]
Please add to translate style names: cobalt ...... user-1 ....

**Comment by Camilot55** [comment]
Please explain what function does clone format perform?

**Comment by giuspen** [comment]
Not sure about translating code style IDs.... except for user-1 and user-2, maybe those could have a translatable description

**Comment by giuspen** [comment]
There is an action to repeat/reapply the format on the last formatted text.
Basically the clone expands that allowing you to cherry pick any cherrytree formatting as if you just applied it to then reapply with the apply latest formatting action
