### ISSUE TITLE
Can't open integred file (gif)

### ISSUE THREAD

**Issue by idomenee** [giuspen/cherrytree#1539]
**Version, Operative system**
Linux Opensuse Leap42.2 KDE

**Describe the bug**
Hi Giuseppe,
Thanks for your nice application.
I migrate my application to flatpak 0.99.31.
I notice that I can't open any more the integrated file image (animated gif) I had in my document.
Double Click on the link don't open the file.
The file is still there. I can click right and "save as"
Best Regards

**Screenshots**

![image](https://user-images.githubusercontent.com/79783591/109411348-b3501e80-79a1-11eb-9aa9-45d1b5dcc3e9.png)

**Comment by giuspen** [comment]
Hi, this is a flatpak issue, if possible use a native package or build from source code

**Comment by idomenee** [comment]
Ok thanks. Have nice day.
