### ISSUE TITLE
Bug : Pressing space after * doesn't give bullet point

### ISSUE THREAD

**Issue by abidrahmank** [giuspen/cherrytree#154]
Earlier versions, if we put \* at the start of a line and put a space, it will be automatically converted to a bullet point. But in the latest one 0.37.1, pressing space just erases the *.

**Comment by giuspen** [comment]
Thank you I found the problem. I would appreciate if you could verify that the fix works in the current git HEAD, if you need I can create a package for you

**Comment by abidrahmank** [comment]
Thanks, it works. Just checked it
