### ISSUE TITLE
Start minimized not working

### ISSUE THREAD

**Issue by Davincible** [giuspen/cherrytree#1540]
I am running Manjaro 5.11 with KDE 5.20, and the start minimized option is not working. I have it checked in the settings, but I still have to start it manually after boot.

**Comment by giuspen** [comment]
Strange it seems to work for me, can you try after you apply the setting to exit completely from cherrytree and open it again?
If you power off your PC with cherrytree running in the system tray it is known that the settings won't be saved.

**Comment by Davincible** [comment]
Well yes, that was the other issue I noticed. I did try that, but then it still doesn't auto start, if I add it to my kde auto start list it does autostart, but not minimized
