### ISSUE TITLE
Zoom in the directory tree is not saved after restart

### ISSUE THREAD

**Issue by luciolebrillante** [giuspen/cherrytree#1544]
**Version, Operative system**
Ubuntu 20.10 and CherryTree 0.99.31

**Describe the bug**
Zoom in the directory tree is not saved when you close the application and restart the computer.

**To Reproduce**
1. Open the application
2. Put your mouse on the directory tree
3. CTRL + Scroll down to zoom
4. Close the application
5. Restart the computer
6. Open the application

**Comment by giuspen** [comment]
Are you sure you are not closing to system tray rather than closing completely?

**Comment by luciolebrillante** [comment]
It works, I don't understand why the zoom wasn't saved but it is probably from my side.

Thank you for your application, it is very useful and powerful.
