### ISSUE TITLE
Change theme / text background

### ISSUE THREAD

**Issue by ipforums** [giuspen/cherrytree#1545]
I was trying to change a rich text theme and none of the built in themes work for me.  They are either too dark or too bright.  I attempted to create a custom theme or modify one of the existing ones.

I'm running CherryTree 0.99.30 on Manjaro LInux and on my machine I got these themes stores in 3 different locations:
/usr/share/gtksourceview-4/styles
/usr/share/gtksourceview-3.0/styles
/usr/share/cherrytree/styles

I attempted creating a new theme file, modified existing, deleted a theme in all 3 folders at the same time.  None of these modifications impacted CherryTree in any way.

What am I missing here?

**Comment by giuspen** [comment]
You are missing 0.99.31 where the theme editor has been implemented

**Comment by iamagithublearner** [comment]
> You are missing 0.99.31 where the theme editor has been implemented

i am using version 0.99.49 on windows 10
is there a way to import themes?
trying to make this dracula theme work
https://github.com/arvi/Agila-Theme#agila-dracula-theme

**Comment by giuspen** [comment]
@iamagithublearner is it code or rich text you are interested in

**Comment by iamagithublearner** [comment]
> @iamagithublearner is it code or rich text you are interested in

Rich text 
really appreciate your quick reply <3

**Comment by giuspen** [comment]
So basically all you have to do is to go to the preferences dialog tab themes and there are 2 user configurable themes. You apply the RGB to the same values of the theme you want to copy from

**Comment by iamagithublearner** [comment]
> So basically all you have to do is to go to the preferences dialog tab themes and there are 2 user configurable themes. You apply the RGB to the same values of the theme you want to copy from

Ah yeah , that's what i have been doing, but there's no way to 'import' themes? 
Devs have to make/port theme for cherrytree specifically? That's why there are no themes yet?

**Comment by giuspen** [comment]
Cherrytree is only implementing these 2 themes (user-1 and user-2) with 8 RGB colors as you may have noticed.
I can add in future import/export of the themes but we would need a standard definition and mapping the 8 RGB used in cherrytree to 8 fields of the standard definition
