### ISSUE TITLE
Request: Close image resize on enter

### ISSUE THREAD

**Issue by Davincible** [giuspen/cherrytree#1547]
In my current study workflow I take a lot of screenshots and then double click the pasted images to downscale them. However, having to grab my mouse every time to click okay is a bit tedious. Would be a much smoother workflow if that would automatically happen upon pressing enter

**Comment by giuspen** [comment]
Will be in 0.99.32

**Comment by Davincible** [comment]
@giuspen Thanks a lot for adding this feature, however, it only works with the main enter key now, not with the numpad enter key. That enter key still has the same behavior. Could this also be added?

**Comment by giuspen** [comment]
@Davincible yes I'll add the numpad enter
