### ISSUE TITLE
Finding or Adding Dictionaries

### ISSUE THREAD

**Issue by SteveH66** [giuspen/cherrytree#155]
I am using Linux Mint.  At the moment, I am finding some odd behavior, in particular in the dictionary isn't is underlined as misspelled.  Not the whole word, just the isn, like it is not recognizing the 't.  Doesn't passes spell check, so I guess that it is in the dictionary or whatever.  So, I was going to add isn't to the dictionary - when I right click on the 'misspelled' isn't, it doesn't offer to add isn't to the dictionary it - offers to add isn and I don't think that is a good idea.  I actually wanted to add a word list file to whatever word-list file CherryTree uses for it's spell checking.  Unfortunately, I can't find it's dictionary word list for en_US or whatever.  What directory is it located in under Linux?

**Comment by metal450** [comment]
Experiencing the same thing under Windows.
