### ISSUE TITLE
[Feature Request] Create list of nodes

### ISSUE THREAD

**Issue by KrishnaTO** [giuspen/cherrytree#1551]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It would help me when I'm creating multiple sub-nodes, to manually to be able to paste a list of topics (delimited by a new line) into a textbox, and have each topic be an individual subnode. 

Currently, I create a new node/subnode per each new topic, where this process can be optimized. 

This textbox can be called from the import menu or by 'insert multiple nodes'? Currently, the closest method I can find is the Import > From folder of plain text files, where each file within a folder will be created as an individual subnode. 

Let me know if this is feasible or additional clarifications are required, or external methods to getting the results are recommended (script create files with filenames of topics, then import as nodes)

Thanks for this critical piece of software!

**Comment by giuspen** [comment]
Should be feasible

**Comment by Mentsh** [comment]
I am looking for something similar - Where I can import a list and it make them into nodes 
Please let me know if this already exists and I just need to format it differently. I was trying to do this via a txt file. 

Thank you. 

Example:

# TESTING 4.x
## 4.10.9 Test Upload of Malicious Files
## 4.11 Client-side Testing
### 4.11.1 Testing for DOM-Based Cross Site Scripting
### 4.11.2 Testing for JavaScript Execution
### 4.11.3 Testing for HTML Injection
### 4.11.4 Testing for Client-side URL Redirect

**Comment by giuspen** [comment]
It doesn't exist yet but I'll propose something soon

**Comment by mimecry** [comment]
yes please, this would be a massive addition

**Comment by giuspen** [comment]
This has been implemented and will be in 0.99.56 but if you can test it already building from the current source code would be useful.
File->Import->From Indented List File
The file syntax is very simple, the indentation can be of multiple of one spaces or multiple of one tab, example:
1
2
 2.1
  2.1.1
  2.1.2
 2.2
3

**Comment by KrishnaTO** [comment]
Thank you! This is exciting.

Can confirm the single space and tab work exactly as match found per line, even if in the same file. 
It seems if a higher level is recognised like level 3, when level 2 was expected, the node on level 3 will be ignored. Note that the line after '2' was level 2 thanks to a tab instead of spaces, so worked as expected there. 

```
1
  2
	2.1
		2.1.1
		2.1.2
	2.2
3
```

![image](https://user-images.githubusercontent.com/128637640/235217918-42111d97-e238-4062-811a-209aaae39771.png)

Ideally, if it could output an error when lines are skipped due to potential errors, that'd be a great catch. 
Anyways, thank you, I appreciate this handy feature to this great app!

--- 
Another pile-on to this feature, if ever tempted, could be ignoring prefix special characters or assigning them as special symbols. I see the value in creating task lists, which can be quickly typed using notepad, then imported with 'to-do' boxes where the node would have the space to add additional information.

**Comment by giuspen** [comment]
I agree something should be done to prevent a line on a wrong level to be dropped.
One option could be to decrease the level to the first valid level, another option would be to add intermediate missing levels as empty nodes+empty node name.
What do you think?

**Comment by KrishnaTO** [comment]
Should a placeholder node be implemented, it'd allow manual corrections with node names. 

If the node levels are adjusted, it would make level 3 nodes equal to subsequent level 2 nodes, likely leading to confusion in subject matter, IMO; so placeholders should be preferred, as you've already committed.  😄 

---
Another feature idea popped up: there could be a case for import files to use incorrectly spaced lines under proper node titles to be used as comments.
