### ISSUE TITLE
CherryTree didn't open after inputting the right password for locked notebook

### ISSUE THREAD

**Issue by bahtioraliev** [giuspen/cherrytree#1552]
**Version, Operative system**
Linux
5.8.0-44-generic
#50~20.04.1-Ubuntu SMP Wed Feb 10 21:07:30 UTC 2021
Desktop

**Describe the bug**
CherryTree didn't open after inputting the right password for locked notebook.

**To Reproduce**
1. Start CherryTree 
2. Input password for locked notebook (ctx)
3. The password will be received correctly and CherryTree will close himself with no message (issue)
4. CherryTree will continue to run in the background 
4. After opening CherryTree again, it will startup correctly 

**Screenshots**
![image](https://user-images.githubusercontent.com/76793434/110607823-481dfd80-8194-11eb-8d97-0e21fcdaf19f.png)

**Comment by giuspen** [comment]
Do you have start to system tray enabled in the preferences dialog, tab miscellaneous?

**Comment by bahtioraliev** [comment]
@giuspen yes, already.

**Comment by giuspen** [comment]
You should disable start hidden in system tray then to solve this

**Comment by bahtioraliev** [comment]
Thank you @giuspen.
The suggestion indeed worked.
Closing the ticket.
