### ISSUE TITLE
Pasting screenshot from the clipboard to CherryTree will cause hanging and crash.

### ISSUE THREAD

**Issue by bahtioraliev** [giuspen/cherrytree#1555]
Version, Operative system
Linux
5.8.0-44-generic
#50~20.04.1-Ubuntu SMP Wed Feb 10 21:07:30 UTC 2021
Desktop

Describe the bug
Pasting screenshot from the clipboard to CherryTree will cause hanging and crash.

To Reproduce
1. Create any screenshot with any screenshot taking tool 
2. Paste the image from the clipboard
3. CherryTree will hang for a moment (stuck and become unresponsive) then the os will identify it and suggest forcing quit or wait. 
3. You will get the crash 
![image](https://user-images.githubusercontent.com/76793434/110790349-9d800a80-8279-11eb-9304-c139e89e78f1.png)

**Comment by giuspen** [comment]
I cannot reproduce on latest, how did you install the package? What is the version?

**Comment by bahtioraliev** [comment]
@giuspen 
CherryTree 0.99.32 (installed from ubuntu software)
Screenshot tool - Ksnip (installed from ubuntu software)

**Comment by sklages** [comment]
Didn't even know it is now possible :+1:  .. works like a charm with `0.99.31`, **Manjaro Linux, KDE**

**Comment by bahtioraliev** [comment]
@giuspen it behave the same on `0.99.31`

**Comment by Sisyfos3** [comment]
Works fine for me (always have) on Win10/Linux Mint 20.1/0.99.32

**Comment by giuspen** [comment]
@bahtioraliev looks like a flatpak issue, can you uninstall from the Ubuntu software and add the PPA instead so install the native version

**Comment by giuspen** [comment]
sudo add-apt-repository ppa:giuspen/ppa
sudo apt install cherrytree

**Comment by bahtioraliev** [comment]
@giuspen 
Thank you very much, indeed it looks like the installation from repository resolved this behavior.
Your help is much appreciated. 
I will close this ticket.
If the issue will reoccure, I will update.
