### ISSUE TITLE
Codebox size in new versions

### ISSUE THREAD

**Issue by Zer0CoOLoL** [giuspen/cherrytree#1556]
Hello!
Changing of codebox size doesn't work correctly since migrating from pygtk2, where this feature works correctly.
P.S. Anyway, thank you very much for this brilliant program!

![123a](https://user-images.githubusercontent.com/63714913/111024848-e22eb180-83f1-11eb-8a31-bf18e2088c3c.gif)

**Comment by giuspen** [comment]
Works fine here, what do you have in preferences dialog, tab rich text, expand codeboxes automatically? If you toggle it?

**Comment by Zer0CoOLoL** [comment]
Thanks for your answer!
Default settings, last portable windows version. I'm even deleted "cherrytree" folders from profile. Toggling not helping anyway.
I think the point here is that if you use the size in pixels, then really, there are no problems, everything works like a clock, but if you use percentages (they are by default), then this problem arises.

**Comment by giuspen** [comment]
Ok I'll have a look

**Comment by giuspen** [comment]
Thanks will be ok in 0.99.33
