### ISSUE TITLE
[Bug] When I set the keyboard shortcut in Cherrytree, the program freezes 

### ISSUE THREAD

**Issue by netios** [giuspen/cherrytree#1559]
**Version, Operative system**
State the Version and the Operative System/Desktop. Try the latest available version before reporting an issue.

ver : cherrytree 0.99.32 ( cherrytree_0.99.32.0_win64_setup.exe : cafc3233e2c22b6e689d4d58cfe87e0b5fcf342b549d23122bfcac4025b6d3c6 )
os  : windows 10 pro 1909
pc  : amd ryzen 2600, 16Gb, ssd..

**Describe the bug**

When I set the keyboard shortcut in Cherrytree, the program freezes and ends after about 5 seconds. 

**To Reproduce**
If applicable, attach a non-personal document where the issue can be reproduced systematically.
1. Go to 'Files > Perferences > Keyboard Shortcut'
2. Click on 'Anything item' and Cancel or X (close) button.
4. Program freezing.

**Screenshots**

There are no screenshots because the program stops.

**Comment by giuspen** [comment]
Thanks I'll have a look

**Comment by giuspen** [comment]
Will be ok in 0.99.33 that I will release in few days

**Comment by netios** [comment]
Thanks

I love your cherrytree.
I recommend cherrytree to many Koreans around me.
They want to be Korean language support.
I have a translation of the language .po file into Korean from cherrytree
github.
This was done in one day on March 23, 2021.
I will give you cherrytree.po for korean, We would appreciate it if you
apply it to the next version.
Thank you for always.

from Sean.lee

2021년 3월 17일 (수) 오전 9:38, Giuseppe Penone ***@***.***>님이 작성:

**Comment by giuspen** [comment]
@netios I wrote you by email please send me the file there thanks

**Comment by netios** [comment]
Thanks


2021년 3월 24일 수요일, Giuseppe Penone ***@***.***>님이 작성:
