### ISSUE TITLE
 Feature request: Ability to drag-and-drop images or to embed files

### ISSUE THREAD

**Issue by vatterspun** [giuspen/cherrytree#156]
Current behavior: need to manually add images and files via the **Edit** menu.

Requested behavior: add files/images by drag-and-drop.

Additional actions (if possible) by file type: 
- Images - should show up immediately, resized to fit in window (maybe with a right-click option to use the resize window available in the **Edit - Insert Image** operation)
- Plain text - when a Plain Text node, should allow entry into the text pane or addition as a node if dragged into the node pane.
- RTF files - same as above but for RTF files.
- Other file types - appear as a simple icon with their file extension (as with an **Edit - Insert File**)

[Edit note: This _entry_ was buggy ... lots of duplicate text.  Sorry about that.]

**Comment by manad777** [comment]
Pasting from the clipboard (ie image data copied from something like Paint) would also be a good idea. This can be useful if people are capturing screenshots of a window to paste in CherryTree. This way there'd be no need to save as file first and then deleting it.

**Comment by giuspen** [comment]
@manad777 Pasting an image from the clipboard is already supported

**Comment by rishanb** [comment]
2nd this - would love to see drag and drop multiple images supported. PDF's would be a close 2nd.

**Comment by kettenfett** [comment]
#757 #

**Comment by metal450** [comment]
+1 for file attachments. For notes that require a large number of supplementary files, it would be much quicker to just drop them all onto the note - whereas now it's necessary to open the file selection dialog one at a time for each.

**Comment by rkram132** [comment]
Will be good to be able to add multiple images at once. instead of doing it manually for each image

**Comment by giuspen** [comment]
this is currently supported
