### ISSUE TITLE
Crash when editing keyboard shortcut

### ISSUE THREAD

**Issue by v3rt3x-4rr4y** [giuspen/cherrytree#1560]
**Version, Operative system**
CherryTree: 0.99.32, OS: Windows 10 Pro version 2004 build 19041.867, PC: Intel x64 i7-4790K 4.0GHz 16GB RAM.

**Describe the bug**
CherryTree crashes/exits when the keyboard shortcut key combination for a function is edited.

**To Reproduce**
If applicable, attach a non-personal document where the issue can be reproduced systematically.
1. Open CherryTree
2. From main menu: File => Preferences => Keyboard Shortcuts
3. Scroll down to and select "Change the color of the selected text foreground"
4. Click the "Change Selected" button.
5. Make a change to assigned shortcut keys and click "OK" (or just click "Cancel").
6. After one or two seconds CherryTree crashes/exits.

**Screenshots**
![ct-001](https://user-images.githubusercontent.com/6816793/111079774-5f8e1b00-84f3-11eb-936c-20234f3e36f7.jpg)

**Comment by giuspen** [comment]
Will be ok in 0.99.33 that I will release in few days

**Comment by v3rt3x-4rr4y** [comment]
All good in 0.99.33, thanks for the quick fix.
