### ISSUE TITLE
link to file does not work if unc path 

### ISSUE THREAD

**Issue by kerlerm** [giuspen/cherrytree#1565]
cherrytree 0.99.31, Windows 10 64 version

I set a link pointing to an UNC path on a share in our local network. When clicking on the link, nothing happens. 
I expect cherrytree to open UNC pathes and the linked files in the corresponding programme. Only regular drive letters "c:..." work as expected.

To reproduce:
1. click on chain symbol "Insert a link"
2. Select "To File"
3. Enter a UNC path e.g. `\\samba\testshare\testfile.txt`
4. Ok
5. left click on created link: Nothing happens

Same problem for "To folder" on the "Insert/Edit link" tab.

**Comment by rpierluigi** [comment]
Also with cherrytree 0.99.32 with windows 10 64 Versione 20H2 
Have the same problem link UNC 
do not work anymore

**Comment by hogfellow** [comment]
i also use:
cherrytree 0.99.32 with windows 10 64 Versione 20H2 and have the same problem link UNC.
After a long wait, the program comes back.

**Comment by giuspen** [comment]
@rpierluigi you say do not work anymore, can you tell what is the previous version where it was working?
I will give it a go anyway just it's tricky because cannot test it at home.

**Comment by rpierluigi** [comment]
Hi Giuseppe with version 0.99.29 it works correctly. Thanks again for your
great work with cherrytree.

Il giorno ven 19 mar 2021 alle ore 22:57 Giuseppe Penone <
***@***.***> ha scritto:

**Comment by giuspen** [comment]
Can you try 0.99.33 that I just released for this issue and report if it's still there?

**Comment by rpierluigi** [comment]
Hi No also with 0.99.33 the link UNC to a Directory doesn't work
I tried to click on the existing links in the file .ctx and to create a new
one but the result is that both don't work


Il giorno sab 20 mar 2021 alle ore 16:59 Giuseppe Penone <
***@***.***> ha scritto:

**Comment by grijshoofd** [comment]
Hi,
I have the same problem with 0.99.33 (Win10):
Absolute links to a file work, but relative links don't.
When I set my preference to relative links AND I make one, I see that in config.cfg pick_dir_file contains still an absolute link (with driveletter)
When I set my preference to absolute links, it works fine.

**Comment by giuspen** [comment]
The UNC links will work again in upcoming 0.99.34
