### ISSUE TITLE
CodeBox text too small

### ISSUE THREAD

**Issue by Kardell** [giuspen/cherrytree#1568]
**Version, Operative system**
CherryTree 0.99.32
Arch Linux, the latest, LXDE

**Describe the bug**
Something happens that the text inside CodeBox becomes very small across all nodes.
Either it's some shortcut I hit by accident or a bug.

**To Reproduce**
while editing in the application.
I can increase the text size inside each CodeBox by Ctr++ but on occasion it goes back to small across all nodes.

**Screenshots**
![Screenshot_2021-03-18_19-00-25](https://user-images.githubusercontent.com/7378224/111682499-5915e100-881c-11eb-93e1-b1e3ecbe2c3e.png)

**Comment by giuspen** [comment]
Could it be that you mouse-scroll with the Ctrl held down by accident?

**Comment by Kardell** [comment]
Hi giuspen, 
I just tried that but this shortcut affects all text inside the node.
What I experience is that suddenly the text inside all CodeBoxes across all nodes turn small like in the above screenshot.
When I export this to PDF the text inside the boxes remains small.
To revert that I have to increase the font size in each of the boxes.
Best regards

**Comment by Kardell** [comment]
So far for me the workaround to increase the text size across all CodeBoxes to default size is to go to File -> Preferences -> Fonts -> Code Font and just hit + then - and all will come back to default Monospace Regular 9.
When the problem occurs the visible font size is like size 5.

**Comment by giuspen** [comment]
@Kardell if you put the cursor in a codebox and hit Ctrl+Plus that is the same as going to the preferences dialog and change the code font. Does it work for you?

**Comment by Kardell** [comment]
I just tried and Ctrl+Plus (or Ctrl+Scroll Up/Down) makes text bigger/smaller in that single CodeBox not the others in the same node if I do it from preferences it changes across all CodeBoxes in all the nodes. This problem could be system related. I am happy with the workaround. Please feel free to close it.

**Comment by giuspen** [comment]
I'll fix this, should change also in other codeboxes same as from preferences dialog, then will close, thanks

**Comment by giuspen** [comment]
In upcoming 0.99.34 zoom is to behave like change in preferences dialog
