### ISSUE TITLE
Closing Hotkey Edit Dialog Closes CherryTree

### ISSUE THREAD

**Issue by MaxEtMoritz** [giuspen/cherrytree#1570]
**Version, Operative system**
At least CherryTree 0.99.31 and 0.99.32, Windows 10

**Describe the bug**
When trying to edit a Hotkey in settings, CherryTree closes when the edit Dialog Box is closed, no matter if the Close button, OK button, Cancel button, Alt + F4 or propably any other method of closing the dialog is used. The changes made are not saved.

**To Reproduce**
1. Go to File -> Settings -> Keyboard Shortcuts
2. Select any Action and click the Pen in the upper right Corner to edit the Shortcut.
3. Press `OK`, `Cancel`, `Close` Button or `Alt` + `F4` keys (Propably anything that would close the dialog).
4. See CherryTree close entirely without updating the settings if OK was pressed.

**Video**
https://user-images.githubusercontent.com/71436559/111874819-29d7af00-8997-11eb-837e-f0b9c5321096.mp4

**Comment by giuspen** [comment]
This should be fixed in 0.99.33 thaw was released today, can you confirm?

**Comment by MaxEtMoritz** [comment]
Yes, it's working now! Thanks for fixing!
