### ISSUE TITLE
[Feature Request] Set Link Search for Anchor Names

### ISSUE THREAD

**Issue by Crankle437** [giuspen/cherrytree#1572]
Hi,

if you want to set a new link to an anchor you have to go to the node, click on the anchor symbol and choose the already create anchor. It would be nice if there is a search for anchor names or you can paste the exact anchor name into the field `Anchor Name (optional)` and a link to the anchor will be set. :)

![cherrytree-insert_edit_link](https://user-images.githubusercontent.com/46601128/111918068-9d56ea80-8a83-11eb-96ce-e1e95ededa52.png)

**Comment by giuspen** [comment]
will be in upcoming 0.99.42
