### ISSUE TITLE
Dependency missing 

### ISSUE THREAD

**Issue by danostg** [giuspen/cherrytree#1575]
**Version, Operative system**
State the Version and the Operative System/Desktop. Try the latest available version before reporting an issue.
LinuxMint 19.3

**Describe the bug**
upgrade to  cherrytree_0.99.33-1_amd64.deb  dependency missing
upgrade to  cherrytree_0.99.33-2_amd64.deb  dependency missing

libgtkmm-3.0-1v5 (>= 3.24.0)

**To Reproduce**
If applicable, attach a non-personal document where the issue can be reproduced systematically.
5.   Try to upgrade to your 2 download files as above

**Screenshots**
![image](https://user-images.githubusercontent.com/34676884/112262525-790f2f80-8c76-11eb-82a7-dc4645dd87dd.png)

**Comment by giuspen** [comment]
You should either upgrade Linux Mint or use the flatpak, cannot go with the Feb package there because the libraries are too old for cherrytree 0.99.x
