### ISSUE TITLE
Lack of unicode support in node name causes crash

### ISSUE THREAD

**Issue by mimecry** [giuspen/cherrytree#1578]
**Version, Operative system**
Windows 10 v1909, build 18363.418. Cherrytree version 0.99.33

**Describe the bug**
Cherrytree crashes when trying to import from folder of plain texts, when the text document names contain unicode characters. If there are plain texts without Unicode characters in their names, Cherrytree will only import those instead. 

**To Reproduce**
1. Create a folder with 3 text files, 2 consisting of unicode characters
2. Import the folder content as nodes using "Import folder of text files"
3. Cherrytree will only import the file without unicode character
4. Delete the file without unicode character from the folder and try to import again
5. This time, Cherrytree will crash

**Screenshots**
The following is the crash error Cherrytree gives when it terminates:

![image](https://user-images.githubusercontent.com/10742312/112625613-c4d1fc80-8e61-11eb-9f6d-c182e64b9834.png)

**Attachment**
Sample text files for your debugging convenience 

[a.txt](https://github.com/giuspen/cherrytree/files/6211480/a.txt)
[á.txt](https://github.com/giuspen/cherrytree/files/6211481/a.txt)
[à.txt](https://github.com/giuspen/cherrytree/files/6211482/a.txt)

**Comment by giuspen** [comment]
Thanks I'll have a look

**Comment by giuspen** [comment]
Thanks will be ok in 0.99.34

**Comment by mimecry** [comment]
thank you very much! by the way, i tried searching but couldn't find any info about this: is there an upper limit to the number of nodes/subnodes you can have in Cherrytree?

**Comment by giuspen** [comment]
The only limit I'm aware of is the maximum number an int64 can store, which is 2^63-1

**Comment by mimecry** [comment]
thank you! the manual states that it's better to use SQL storage type for large documents, at around how many thousands/tens of thousands of nodes/subnodes do you think it would be better for SQL as opposed to XML?

**Comment by giuspen** [comment]
Consider than with XML every time you save anything it rewrites everything in the tree. With SQLite only the node(s) you modify

**Comment by mimecry** [comment]
right. in that case i'll play around and see which is better for my usecase
