### ISSUE TITLE
Keyboard shortcut to exit codebox to the next line

### ISSUE THREAD

**Issue by wisdomlight** [giuspen/cherrytree#1587]
**Is your feature request related to a problem? Please describe.**
We have a shrotcut for creating CodeBox 
then you write the line(s)
Then you want to go and write normal text below the CodeBox and you need to use the mouse for that.

**Describe the solution you'd like**
Keyboard shortcut to escape the CodeBox?

**Comment by giuspen** [comment]
Actually there is already even though not explicit, it is Ctrl+Space to both enter and exit the codebox without using the mouse

**Comment by wisdomlight** [comment]
Lol 
I tried so many options - but of course not the one that works....
thanks ctrl space
