### ISSUE TITLE
Anomaly on characters following a link to a website

### ISSUE THREAD

**Issue by Christian-V** [giuspen/cherrytree#1589]
**Version, Operative system**
Linux Mint 20.1 (or earlier)

**Describe the bug**
When you type or paste just after the text of a link to a website one or more characters other than a space or a line break, followed by a space or a line break, these characters are integrated into the text of the link (color change, underline, active click).
In addition for certain characters (emoticons for example) this happens later, depending on what we do next (click elsewhere for exemple) and the underline is much lower. It disappears momentarily if you work on the next line. 

This does not happen with one of the other three types of links, nor at the start of a web link. 

This can be annoying, for example, if you put the link text in parentheses or if it is at the end of a sentence followed by a period.

**Comment by giuspen** [comment]
I will see if I can reproduce and get back if not

**Comment by giuspen** [comment]
Thanks, fixed in upcoming 0.99.34
