### ISSUE TITLE
No such table errors result in corrupted .ctb

### ISSUE THREAD

**Issue by erik-sk** [giuspen/cherrytree#1592]
Currently running version 0.99.32 in Manjaro Linux.

Started getting "no such table" errors today. After which the .ctb file is corrupted and I lose all the data.
The first error I got was "error parsing the cherrytree file: sqlite3_prepare_v2: no such table: bookmark"
But have been getting various other errors, the main similarity is the "no such table" comment. 
Here area some screenshots of other errors.
![2021-04-07_11-43](https://user-images.githubusercontent.com/37672001/113803822-485fe780-9798-11eb-8b9a-a3da90a729d5.png)
![2021-04-07_11-50](https://user-images.githubusercontent.com/37672001/113803875-63caf280-9798-11eb-81a4-446fce8b4e4c.png)

And a comparison of the file sizes (original is 400k, corrupted is 8kb)
![2021-04-07_11-44](https://user-images.githubusercontent.com/37672001/113803983-9543be00-9798-11eb-9377-f3854e131cab.png)

All I am doing is adding some text to a record and a table within it. I use this mostly as a record of attendance and in class work for my teaching job. There isn't anything super fancy in it. This .ctb has been working fine for quite a while.  Luckily there are hidden backup copies saved or I would have lost all my notes on all of my classes. 

![2021-04-07_12-01](https://user-images.githubusercontent.com/37672001/113805031-ad1c4180-979a-11eb-8f0a-229ca0f19f98.png)

Not sure what to try to clear this up.

**Comment by giuspen** [comment]
Are you using any sort of autosynch software like Dropbox? Do you have the autosave on? Did you notice anything or did you do anything differently in the last session?

**Comment by erik-sk** [comment]
I do use Dropbox, and I turned it off. Things in Cherrytree seem normal again, but now I need to figure out how to still be able to use Dropbox. I guess turn it off while I have Cherrytree open??? This is all very weird, because I have used it with Dropbox running for as long as I have used this app and never had this problem before.

**Comment by giuspen** [comment]
It seems highly probable that the database corruption was caused by concurrent access of cherrytree and Dropbox. There is an option to automatically reload the cherrytree database in case of external update but it is disabled by default and it was probably disabled for you. This should prevent such issues, I disabled by default because some users had their document reloaded unexpectedly but you may give it a go

**Comment by erik-sk** [comment]
I will give that a try this morning. If it seems like it's acting normal I will come back and close this. Thanks for the help.

**Comment by erik-sk** [comment]
This definitely seems like it was the Dropbox issue. Actually something of my own doing. I had renamed a computer that is synced to Dropbox and somehow the name reverted back. It caused other strange activity on Dropbox and after clearing and reinstalling that laptop seems to be acting normally and no more issues with the Cherrytree DB getting corrupted.
