### ISSUE TITLE
Cherry Tree Import Option Crash - Latest Version

### ISSUE THREAD

**Issue by javadevelopment4** [giuspen/cherrytree#1593]
Downloaded the latest version from the web-site

I have 3,000 text files in a folder. When i tried to import the folder via import option it got crashed instead of importing one by one...

I have also tried with 3,000 html files as well..It goes the same result

Looks the files needs to be processed one by one...

**Comment by giuspen** [comment]
No I rather think that one of your files causes the crash. If you try to import from a folder of two text files is it working?

**Comment by javadevelopment4** [comment]
If i import files one by one, all the text files are working fine
if i import two files in a folder it is working fine
if i import the folder which contains all the files it is crashing immediately.

Note: It is not crashing in the middle. as soon as clicked import or choosing the folder with huge files.

**Comment by giuspen** [comment]
Maybe it really goes out of memory

**Comment by javadevelopment4** [comment]
Few More Obervations

# some time it quits quitted without any message
# some times it quites with the close dialog program from windows
# some time a strange error ....

Can you please import folder with huge text or html files (may be 2,000 or 3,000) files??

You can duplicate a single file to en number of files freely using (https://www.skyjuicesoftware.com/software/QuickFileDuplicator/index.html) - free for non-commercial use.

**Comment by javadevelopment4** [comment]
@giuspen are you able to reproduced the error with huge files?

**Comment by giuspen** [comment]
Haven't tried yet, easier if you give me something to try with

**Comment by javadevelopment4** [comment]
@giuspen Attach

uploaded the sample files which i have tried. unzip and import the entire folder in cherry tree and it will be crashed.

https://easyupload.io/ry11mq

**Comment by giuspen** [comment]
Thanks for providing the files to test with so I could reproduce easily, it was not an out of memory, it will be ok in upcoming 0.99.37

**Comment by javadevelopment4** [comment]
Below are the problems notices.

#1 - Looks the contents of the nodes are not indexed. Search all the nodes after importing the text files folder is very slow for a keyword
#2 - When searched for a keyword in all the nodes, the search is keeps on going and take more than several minutes

Suggestion:
Index all the contents and unique keywords
Search would be type-ahead and fast 
The results should be returned in less than 5 seconds.

**Comment by javadevelopment4** [comment]
The search is very slow when searched for a text in whole nodes. It takes minutes. It would be helpful if it can be optimized

**Comment by javadevelopment4** [comment]
The search was very very slow...The import got resolved..However search for
a keyword in entire nodes or files is very much time consuming

Thanks

**Comment by ees2** [comment]
If you try to Import From Folder of Plain Text Files, and one of the files does not have an extension, Cherry Tree crashes.  To reproduce can put only one small file with no extension in a folder and it will crash trying to import the folder.  Obviously not crucial as the workaround is to make sure all files have an extension like they should.

Great software, love it.
