### ISSUE TITLE
Unique-constraint-failed error when saving

### ISSUE THREAD

**Issue by schlosj** [giuspen/cherrytree#1595]
CherryTree Version: 0.99.30

Import from folder of HTML files worked all right for 3,521 files (< 10 KB each).
Saving, however, results in this error message:
      !! sqlite3_step: UNIQUE constraint failed: children.node_id

Any idea how to avoid this?

**Comment by schlosj** [comment]
The error reported above occures when CherryTree is saved as storage type SQLite. It does not occure with storage type XML.
According to the manual '...XML should not be used with large documents.' Could anybody indicate when a document should be considered as 'large', MB, GB, TB ...? Thank you!

**Comment by giuspen** [comment]
Hi, could you zip that large folder of html files and let me use it for testing? If you can, you may send it privately to my email address that you can find in the help--about dialog

**Comment by giuspen** [comment]
Hi @schlosj and thanks for sharing with me the folder to test the import with. I tested and while being a slow to save so many new nodes into the SQLite db, I did not get the error.
I tested on the very latest code while your version is few releases behind, can you test on 0.99.33?
Can you say what is your operative system?
If you create a new CTB document of one node and import there (that is what I have done in my test) do you still get the error?

**Comment by schlosj** [comment]
Hi, I upgraded to CherryTree 0.99.33.0, win64 portable and confirm: saving with storage type SQLite, not protected, ctb, works. No error any longer. 
Privious version was 0.99.30.0. I'm using Windows 10. 
Thanks a lot!
