### ISSUE TITLE
Incompatibility of password protected files linux vs windows version

### ISSUE THREAD

**Issue by GoogleCodeExporter** [giuspen/cherrytree#16]
```
What steps will reproduce the problem?
1. Create password protected file ( sqlite or xml ) in linux version of program
2. Try to open this file in windows verion of program
3. Et vice versa

What is the expected output? What do you see instead?
File must be opened after password was typed , but there's always "wrong 
password" in result 

What version of the product are you using? On what operating system?
0.32 and 0.35 linux and windows 

Please provide any additional information below.


```

Original issue reported on code.google.com by `xmax...@gmail.com` on 8 Dec 2014 at 7:50

**Comment by moldcraft** [comment]
I have the same problem: I worked only on Ubuntu until now, I migrated for a few months on Windows but my `.ctx` won't open. I opened it in Ubuntu and `Save As...` unprotected `.ctb` then on Windows I reSaved `.ctd` to `.ctx`.

I haven't tested if the new `.ctx` file created on Windows works on Ubuntu (I am lazy).

**Comment by giuspen** [comment]
Hi, the problem is related to specific chars in the password and the linux
vs windows terminal/shell. Can you try to spot what char/chars are not
cross platform and let me know?

**Comment by moldcraft** [comment]
lower/upper case letter, numbers and only this `^` special character. e.g.: `he11^W^R1D`

**Comment by moldcraft** [comment]
Now I tried to open in Ubuntu the `.ctx` created on Windows and it says the pass is wrong

**Comment by giuspen** [comment]
I can see the problem thank you. I'm going to ban the caret char from the passwords in the next versions

**Comment by moldcraft** [comment]
I removed the `^` character from password and now I can open the file on Windows and Linux.

Thank you!

P.S. Can you explain please why it happens?

**Comment by giuspen** [comment]
That's because it's a special character in Windows command line, see
http://www.pcmech.com/article/use-the-carat-to-escape-characters-in-the-command-prompt-and-batch-files/

**Comment by moldcraft** [comment]
Better you should [escape special characters](http://www.robvanderwoude.com/escapechars.php) on windows instead of blacklisting characters

**Comment by giuspen** [comment]
You're right, when I started I just picked the quickest solution. If you
could implement the fix yourself, test on both linux and windows and create
a pull request that would be of great help.
On 3 May 2016 14:51, "moldcraft" <notifications@github.com> wrote:

Better you should escape special characters
<http://www.robvanderwoude.com/escapechars.php> on windows instead of
blacklisting characters

—
You are receiving this because you commented.
Reply to this email directly or view it on GitHub
<https://github.com/giuspen/cherrytree/issues/16#issuecomment-216533502>

**Comment by moldcraft** [comment]
Ok, I will try.

So the escape must be done only in 2 places, on [save](https://github.com/giuspen/cherrytree/blob/b709a203f4f4a29f5be5a4c003588958df0dd781/modules/core.py#L1589) and [open](https://github.com/giuspen/cherrytree/blob/b709a203f4f4a29f5be5a4c003588958df0dd781/modules/core.py#L1945)?

**Comment by giuspen** [comment]
Correct, thank you for your help!
