### ISSUE TITLE
Copy “Automatic Syntax Highlighting” Text to "RichText" Text Box，Color Error

### ISSUE THREAD

**Issue by fu607666** [giuspen/cherrytree#160]
Copy “Automatic Syntax Highlighting” Text to "RichText" Text Box，Color Error

My English is not good, see Attachment:

[Color Error.tar.gz](https://github.com/giuspen/cherrytree/files/349372/Color.Error.tar.gz)

**Comment by txe** [comment]
I checked the issue in 0.99, it was fixed
