### ISSUE TITLE
new settings menu

### ISSUE THREAD

**Issue by Camilot55** [giuspen/cherrytree#1602]
Hi, Giuseppe. 
We will be developing a new settings menu. 
Do I have any suggestions? 
I think the convenience for users will be.
 Are you interested in my offer?

**Comment by giuspen** [comment]
Hi Viktor, what do you mean, is it to rework the preferences dialog?

**Comment by Camilot55** [comment]
Yes

**Comment by giuspen** [comment]
OK that makes sense. You have done a very good job reworking the menu so I'm more than happy if you want to do the same for the preferences dialog (after 0.99.34 is out).
