### ISSUE TITLE
Remove the colon from the files with the translation

### ISSUE THREAD

**Issue by Camilot55** [giuspen/cherrytree#1603]
Hi, Giuseppe. 
There is a suggestion to change a little bit one file in the project to get rid of this in the files with the translation.

#: / home/giuseppe/git/cherrytree/src/ct/ct_main_win. cc:577
#: /#: /home/giuseppe/git/cherry tree/src/ct/ct_main_win.cc:589
#: /#: /home/giuseppe/git/cherry tree/src/ct/ct_main_win.cc:592
#: /#: /home/giuseppe/git/cherry tree/src/ct/ct_main_win.cc:595
#: /#: /home/giuseppe/git/cherry tree/src/ct/ct_main_win.cc:599
#: /#: /home/giuseppe/git/cherry tree/src/ct/ct_main_win.cc:603
msgid ": "
msgstr ": "

The file is attached can you merge it manually or do I do a PR?
[ct_main_win.zip](https://github.com/giuspen/cherrytree/files/6298731/ct_main_win.zip)

**Comment by giuspen** [comment]
Hi Viktor, that translatable string is there for a reason and is not to be taken away.
There is at least a translation (may be the Armenian? Or was it an Asian language...) where that becomes something else rather than the space and colon, different languages have different punctuation :)

**Comment by Camilot55** [comment]
I checked, only hy.po (msgid ": "
msgstr"՝") differs, you can make a condition for it in the code

**Comment by giuspen** [comment]
Mhmm what's the problem in leaving as it is now, it already works... doesn't it

**Comment by Camilot55** [comment]
OK. The question is closed.
