### ISSUE TITLE
Click on relative path not opening external programs - Windows 10

### ISSUE THREAD

**Issue by selra-hc** [giuspen/cherrytree#1604]
**Version, Operative system**
CherryTree 0.99.33 on Windows 10 64b (Enterprise 1809)
Just updated from 0.99.20 (no bug)

**Describe the bug**
There is no external program opening when clicking on a relative path link (explorer, word,...). 
Works without problem with absolute path.
Mentioned by @grijshoofd in a comment in #1565, so may be a duplicate depending on the way it's handled regarding UNC :) if so, sorry then :/

**To reproduce:**
(almost entirely copied from #1565)
click on chain symbol "Insert a link"
Select "To File"
Enter a relative path e.g. main_directory_content\test\testfile.txt
Ok
left click on created link: Nothing happens
Same problem for "To folder" on the "Insert/Edit link" tab.

**NB**
If I put the test file directly in the main directory where the ctd file is :
testfile.txt
it opens

![image](https://user-images.githubusercontent.com/67684262/114544992-af2f4600-9c5b-11eb-9ee0-8d7127489765.png)
![image](https://user-images.githubusercontent.com/67684262/114545044-c3734300-9c5b-11eb-8802-1d4f24873a3d.png)

*****

**NB 2**
Thanks giuspen & all for the good work nevertheless, some new functionalities in 0.99.33 are cool :)

**Comment by giuspen** [comment]
Relative path means relative to the cherrytree document/database. I just tried it and it works normally, maybe your cherrytree document is on a different drive than the linked file? Haven't tried that will check in a moment

**Comment by giuspen** [comment]
Works also on different drive for me but could be because I'm using a newer development version. I'll release 0.99.34 shortly please try there and report if it works

**Comment by selra-hc** [comment]
Hi @giuspen, I can confirm it works again with 0.99.34.

Thanks for the good work :)

I'll close the issue
