### ISSUE TITLE
SPACE and NON-BREAKING SPACE behaviour 

### ISSUE THREAD

**Issue by sklages** [giuspen/cherrytree#1608]
**Version, Operative system**
Version `0.99.32` on Manjaro Linux  (official repo, not flatpak), `UTF-8` encoding.

**Describe the bug**
Copying text data from terminal or mail programm using either `Ctrl-C` or `Chtr-Shift-C` with four leading spaces to Cherrtyree and then from Cherrytree to a text editor always copies the first one correct 
(`&#32;`) and the other three as non-breaking space (`0xa0`, `&#160;`). 
Further testing shows me: when copying more than one consecutive `space`, only the first one is correct `space`, all following spaces are `non-breaking spaces`.

Do you get what I mean?

**To Reproduce**

**Screenshots**
![image](https://user-images.githubusercontent.com/1837422/114691649-2e824f80-9d18-11eb-8ee0-1b8227151f9a.png)

Honestly I am not sure if this is an issue with `Cherrytree`, but I do not have this issue with any other program .. 
Any idea where to look at? Or do get something wrong here?

thanks,
Sven

**Comment by giuspen** [comment]
If you copy from a cherrytree rich text that is html so in order to have the spaces preserved it becomes an html non breaking space. If you don't want that do copy as plain text from cherrytree, with right click or Ctrl+Shift+C

**Comment by sklages** [comment]
Yes, that's what I did. It simply does not make any difference. 

Creating text in cherrytree and copying it to text editor works just fine, with either `Ctrl-C` or `Ctrl-Shift-C`. 

Copying text from another source (text, Email, terminal output, here konsole) to cherrytree and then copying to another target (text editor) exhibits the described behaviour.
This is not an issue, when I copy text directly from e.g. terminal to text editor ...

**Comment by giuspen** [comment]
Ok I'll try and reproduce

**Comment by giuspen** [comment]
This should be fixed in 0.99.43, can you confirm?

**Comment by sklages** [comment]
Well, I copied the same (type of) text from terminal to CT and from there to ST without any issue.
But my setup has changed: now on Fedora 35 (GTK). 
This issue seems to be solved. Thanks for the fix and thanks for a nice piece of OSS :+1:
