### ISSUE TITLE
Setting font size for small text

### ISSUE THREAD

**Issue by ynoxia** [giuspen/cherrytree#161]
Hello. :)

Is it possible to set font size for small text in configuration? The font size used for small text in my CT env is really very small, and difficult to read.

Thank you.

**Comment by giuspen** [comment]
Ciao Giulio.

I can propose a slightly larger "small font" and see if anybody complains,
at the moment it is not possible to configure it.

I just committed the proposed change in git, can you try it and give
feedback? or you need me to create a package for you?

**Comment by ynoxia** [comment]
I'll try the committed change and give my feedback ASAP.

Thank you for this patch. :)

**Comment by ynoxia** [comment]
I tried this change in my local Fedora env, and now small text is surely more readable, and more comfortable to use.

If anybody does not complain :), you can consider the possibility to maintain this change.

Thank you.
