### ISSUE TITLE
Latest 0.99.34 can't set H1/H2/H3 formatting anymore

### ISSUE THREAD

**Issue by lmattcris** [giuspen/cherrytree#1611]
**Version, Operative system**
Windows 10 pro x64, Linux Lubuntu 20.04

**Describe the bug**
Saved notes with H1/H2/H3 formatting don't show anymore the formatting, plus they can't be enabled anymore.
Both OSes tested have the same behavior, no more header formatting in any way, both on existing notes and new ones

**To Reproduce**
1. Open a new instance
2. Create a node
3. Add text and click any of h1/h2/h3 on toolbar OR from menu Format / Toggle heading property / Toggle h1 property

**Screenshots**

**Comment by keesse** [comment]
I can confirm that, haven't tried the linix version yet.

**Comment by giuspen** [comment]
It works for me, what am I missing here... can you run from a terminal and tell me what it prints out when you click and doesn't work?
If you access your config.cfg, can you see lines starting
scalable_h1=
scalable_h2=
...
scalable_h6=
please paste here

**Comment by Crankle437** [comment]
I've the same problem. If I click on the button for h1, h2, h3 or press Ctrl+1/2/3 nothing happens and nothing is displayed in the console either.

OS: Ubuntu 20.04.2 LTS

**Comment by sklages** [comment]
Just updated to `0.99.34` and it works like intended for me. No issues.
System: Manjaro Linux / KDE Plasma / Cherrytree (flatpack)

**Comment by giuspen** [comment]
I think I understood, will try in a moment and if resolved will release a fix

**Comment by giuspen** [comment]
It should be good to go now, anybody with the issue can build the latest from github and confirm?

**Comment by giuspen** [comment]
I released 0.99.35 please write here if solves the issue

**Comment by lmattcris** [comment]
> I released 0.99.35 please write here if solves the issue

I'm using the amd64 binary, while I see on launchpad only the arm64 one, so I can't test it sorry :)
Let's see if I can try the Windows build

**Comment by lmattcris** [comment]
> I released 0.99.35 please write here if solves the issue



> > I released 0.99.35 please write here if solves the issue
> 
> I'm using the amd64 binary, while I see on launchpad only the arm64 one, so I can't test it sorry :)
> Let's see if I can try the Windows build

Ok, I can confirm the Windows build runs correctly. Will verify the Linux one when available for amd64.
Thanks!

**Comment by giuspen** [comment]
Thanks @lmattcris

**Comment by Crankle437** [comment]
Thanks it is also working on Ubuntu 20.04.2 now :)

**Comment by giuspen** [comment]
Thanks @Crankle437
