### ISSUE TITLE
Bookmarks back in menu bar

### ISSUE THREAD

**Issue by repsorp** [giuspen/cherrytree#1613]
Any way to get "Bookmarks" back in menu bar for quick access ?

**Comment by Camilot55** [comment]
Right-click in the tree control panel. This is a quick way
![Безымянный1](https://user-images.githubusercontent.com/76065578/114862988-9dd76c80-9e08-11eb-89af-b37436714ab6.png)

**Comment by repsorp** [comment]
Bookmarks do not display with right click in the tree control panel

![2](https://user-images.githubusercontent.com/6297032/114907370-4a224e80-9e1b-11eb-9086-2ae5253d35e0.png)

Bookmarks are only displayed when you click on Tree view in the menu bar and then on Bookmarks

![1](https://user-images.githubusercontent.com/6297032/114907752-b00ed600-9e1b-11eb-927f-c0f8935b3f14.png)

Direct access to Bookmarks in menu bar was quicker anyway ;-)

Ubuntu 20.10

**Comment by Camilot55** [comment]
Believe me, you perform the same number of movements now as before. Isn't that right? Since it is now made more practical and more expedient in terms of performing operations.

**Comment by repsorp** [comment]
> Believe me, you perform the same number of movements now as before. Isn't that right? 

hmmmm... I'm not quite convinced ;-)

Anyway, do you know why bookmarks are not displayed with right click in tree control panel ?

**Comment by Camilot55** [comment]
Хорошо. Я посмотрю. Скорей всего ошибка

**Comment by giuspen** [comment]
There indeed seem to be a bug, but you should be able to access the bookmarks via top menu Tree--Bookmarks--> the same way as you before were accessing directly Bookmarks-->

**Comment by Camilot55** [comment]
Dear repsorp. 
You can also customize the toolbar for quick access to bookmarks. 
Look:

![Безымянный1](https://user-images.githubusercontent.com/76065578/114969647-3a921c80-9e92-11eb-9498-95226569ee13.png)
![Безымянный2](https://user-images.githubusercontent.com/76065578/114969651-3e25a380-9e92-11eb-85a8-44a07841b9f6.png)
![Безымянный3](https://user-images.githubusercontent.com/76065578/114969657-42ea5780-9e92-11eb-9c96-64322ee53f5e.png)

**Comment by Hoffenbar** [comment]
The new solution for shortcuts is cumbersome. In the previous release, one click opened my favorits.
Thats the first thing.
The second one: my bookmarks are silently gone. This is something that should not happen from one relaese to another!

**Comment by giuspen** [comment]
The top Bookmarks menu has been moved as a submenu of Tree so Tree--Bookmarks--> the same way as you before were accessing directly Bookmarks--> not really disappeared.

**Comment by Hoffenbar** [comment]
Yes, but the access is not as quick as with the previous solution. Besides this, my existing bookmarks are silently gone.....

**Comment by Camilot55** [comment]
I'm sorry, but the app is developing and trying to keep up with the times! Or are you afraid of the new? Does everything new scare you? At the moment, out of 5,000 people surveyed, there is not one who is not satisfied with the new main menu. All the functions of the app are saved, some only changed their location and this is not critical. The only critical thing is that while there are errors in the application that need to be fixed. I hope you are changing your old technique to a new one, which also has a new menu and new features. You study them and use them as well as now, and do not write to the developer "Return the old menu!". You take and use a new one, then it becomes convenient for you. So do not be afraid of anything new, the world of digital technology is developing, breathing and living. By the way, unfortunately, I am also not young (I am 54 years old), but I am not afraid of new products. Good luck learning and using it.

**Comment by giuspen** [comment]
@Hoffenbar there was a bug in 0.99.34 please upgrade to 0.99.35 the bookmarks should be back

**Comment by giuspen** [comment]
@Camilot55 you made a great job if a set of users will require something specific I can think about some sort of configurability

**Comment by repsorp** [comment]
@Camilot55 Don't feel attacked on your work. 
The new update has brought big changes to the menu bar which has upset my habits a bit because for me the access to the bookmarks is essential and must be accessible in the fastest way.
I personally don't want to clutter the visual interface with the toolbar and that's why bookmarks in the menu bar was the best solution for me.
This is just my personal opinion and I will try to get used to the new interface even if it means a loss of comfort.

**Comment by Camilot55** [comment]
Excellent. I wish you good luck.

**Comment by Camilot55** [comment]
@giuspen We did a great job with you. I hope our cooperation will bear fruit. You are a very good person.

**Comment by Camilot55** [comment]
The question is off-topic. 
I wanted to know your opinion. I guess my English is disgusting, but I try to raise my level higher. Do you think?

**Comment by Hoffenbar** [comment]
Yey, the bookmarks are back with 0.99.35 - many thanks and thank you all for this great program.

**Comment by repsorp** [comment]
> @repsorp Excellent. I wish you good luck.
> I'm sorry if I offended you in any way.

No offense at all
Keep up the good work

**Comment by repsorp** [comment]
> The question is off-topic.
> I wanted to know your opinion. I guess my English is disgusting, but I try to raise my level higher. Do you think?

As long as I can understand it is good for me ;-)

**Comment by giuspen** [comment]
Thanks @Camilot55 you're a gentleman too! :)
I pushed the new version to launchpad last night but has been in the queue since, it went through now you should see the update.
Your English is better than my Russian, I'm studying daily though as you are :)

**Comment by giuspen** [comment]
Thanks for the feedback @Hoffenbar

**Comment by Camilot55** [comment]
@repsorp Sie beherrschen mehr Deutsch, ich bin nur ein Schulkurs.
I know Kazakh, Russian and Gypsy languages better, and a little Tatar.

**Comment by Camilot55** [comment]
@repsorp Wenn es Ihnen nicht schwer fällt, schließen Sie Ihre Frage. Vielen Dank. Viel Glück.

**Comment by repsorp** [comment]
Could a shortcut for bookmarks be considered?

**Comment by repsorp** [comment]
> Could a shortcut for bookmarks be considered?

Found it... Sorry
