### ISSUE TITLE
Text insert - how to stop?

### ISSUE THREAD

**Issue by wisdomlight** [giuspen/cherrytree#1615]
When I put the cursor in the middle of a text line and type, it functions like insert text in Word - it 'eats' up all the characters that are on the line replacing them with what I am typing.
How do I stop that?

**Comment by sklages** [comment]
Hit the `Insert` key once, that usually toggles between inserte/overwrite mode.

**Comment by wisdomlight** [comment]
Thanks @sklages 
I realized the problem was using such and advance keyboard I didn't realize I was hitting the insert key.....
doohhh
