### ISSUE TITLE
Support HiDPI

### ISSUE THREAD

**Issue by Bystroushaak** [giuspen/cherrytree#162]
Hello.

I have new notebook Dell XPS 13, which have 12" 4k LCD. This forced me to dig into issues with small applications, which I resolved by using HiDPI, which virtually lowers the resolution to half. Sadly, cherrytree ignores the OS settings and everything is extremely small.

Here is the default installation (I didn't changed the window size):

![2016-07-08 14 29 33](https://cloud.githubusercontent.com/assets/227282/16687494/4ab89c4c-4519-11e6-8326-b03b3be53be0.jpg)

Here is settings with bigger font:

![2016-07-08 14 30 36](https://cloud.githubusercontent.com/assets/227282/16687504/5d437026-4519-11e6-83a5-30144cacc0ad.jpg)

This is almost usable, but all the icons are too small.

Could you please fix it? More and more people have 4k displays and I think this issue will be more and more common. I don't really have idea how, maybe don't use the absolute units (px) and use relative (em?), or something like that.

**Comment by giuspen** [comment]
Hi, you can increase the size of the icons from the top menu View--Increase
Toolbar Icons Size

**Comment by Bystroushaak** [comment]
Thanks. I will try that tomorrow.
