### ISSUE TITLE
No key shortcut for moving rows in tables

### ISSUE THREAD

**Issue by Ty1241** [giuspen/cherrytree#1626]
In old version 0.39.4 there were two simple shortcuts to move rows in tables:
![old](https://user-images.githubusercontent.com/82744317/115134170-2a9f4780-a00e-11eb-8969-22af4c4ef5f8.png)

In new version 0.99.36 this shortcuts are used to increase or decrease column width so this buttons no longer have any shortcuts.
![new](https://user-images.githubusercontent.com/82744317/115134187-4dc9f700-a00e-11eb-90bb-47ab78cea639.png)

Please add any shortcuts to those buttons.

also its not possible to manualy assign any shortcuts to this features because they are not listed in Preferences > Keyboard shortcuts.

**Comment by giuspen** [comment]
I missed that, will do something about it

**Comment by giuspen** [comment]
Will be in 0.99.37
