### ISSUE TITLE
Linux, CT 0.99.36, critical warning

### ISSUE THREAD

**Issue by muashieWuphu** [giuspen/cherrytree#1628]
Hi,
I was having segfaults in version .34 and .35. The version .36 works OK, but I can see this in the command line:
`[2021-04-18 07:46:05.258] [gtk] [critical] gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed`

Thanks for working on this great program, btw!

**Comment by giuspen** [comment]
Thanks I will check if I have it too and if could cause any harm, what is your OS and package type?

**Comment by muashieWuphu** [comment]
Hi, this is PLD linux, rpm package, Version .36 is not yet in distro. I just updated spec file and built rpm locally.
