### ISSUE TITLE
[feature request] system tray icon: click to hide CT

### ISSUE THREAD

**Issue by dardoor** [giuspen/cherrytree#1631]
It would be nice if L-clicking on the system tray icon would also hide CT if it's open (so the equivalent of closing the CT window if System Tray Docking is enabled).

I think most programs that use the system tray icon (in Windows) work like this, so it's a show/hide toggle (maximize/minimize toggle).

**Comment by giuspen** [comment]
I thought that's what happens. What is your operative system and cherrytree version?

**Comment by dardoor** [comment]
No, it has never worked this way for me.
Windows 10 20H2 and CT 0.99.36. But it was the same with older CT versions and also on Windows 7 I think.

But I noticed now that CT does react to L-clicking even when it's open. For example if I move the CT window and then L-click the tray icon it will move the CT windows back to where it was before. It doesn't hide/minimize it, though.

**Comment by giuspen** [comment]
Thanks will be ok in the next version 0.99.37
