### ISSUE TITLE
Debian Sid can't upgrade CT because - libc6(>=2.33) - not available

### ISSUE THREAD

**Issue by wisdomlight** [giuspen/cherrytree#1632]
So on Debian Bullseye/Sid
CT is saying there's new V 0.99.36-3
Trying to install with Package Installer gives an Error - Dependency not satisfialble: libc(>=2.33)
But this [Debian package page](https://packages.debian.org/sid/libc6) seems to have no 2.33 only 2.31.
So is it not possible to upgrade??

**Comment by giuspen** [comment]
0.99.36-1, 0.99.36-2 and 0.99.36-3 are the same versions really but built for Ubuntu 20.04, 20.10, 21.04 respectively. Please try all 3 on Debian and if none is installing/working I'll build a package myself specific for dDebian and make it available.

**Comment by wisdomlight** [comment]
Thanks - the 0.99.36-1 did install fine on my Debian sid.
Cheers
