### ISSUE TITLE
h1 h2 h3 .. formats: change font attributes

### ISSUE THREAD

**Issue by ynoxia** [giuspen/cherrytree#1633]
Cherrytree 0.99.36 introduced a default setting of the text formats h1, h2, h3 etc.

Once these formats are set, it is no longer possible to change bold and italic text attributes. In CT 0.99.36 for Linux Fedora, I noticed this behavior:

+ after setting a text in small font, it is not possible to change all, or part of the text, to italic - if not in preferences for all text in small font;
+ it is not possible to change the bold and italic attributes of all or part of the text in h1, h2, h3 format  - if not in preferences for all text in these formats;

In previous versions of CT, there was full user handling of bold and italic text, which I have used extensively in my CT documents, and which make my documents clearer and more readable, surely in my personal use of CT.

A possible solution that maintains the convenience of the new setting of text formats may be to allow the user the possibility to modify bold, italic and underline attributes of all, or part of the text formatted as h1, h2, h3, or also small.

Is it possible to implement it?

Thank you.

**Comment by giuspen** [comment]
I will check, should be feasible to apply the default first and then the additional tags on top

**Comment by giuspen** [comment]
Note that if you have bold as default I don't expect you to be able to un-bold some text, only the other way around so if it's not bold by default you can also tag bold some of it

**Comment by ynoxia** [comment]
The new feature that allows to have a default for text formats is very useful, especially for the font size.

But if this default nails the style of the text everywhere, it becomes, in my humble opinion, a little too rigid.

At this time, for example, even if you do not set italic style for text formats as default, it is impossible to subsequently set a word or phrase in italic style. Only normal text allows this. The bold style behaves as you reported in your previous comment.

Setting a default for text formats is very useful. But if the user retains full freedom in his own text settings while typing and formatting, then the functionality, always IMHO, becomes excellent.

**Comment by giuspen** [comment]
Even though with 0.99.36 you are not seeing the bold/italic/underline set partially on a small,h1...h6, this doesn't mean that the property is not there/has been removed. You will see again those tags/properties in 0.99.37 (or access the latest code from github)

**Comment by ynoxia** [comment]
Thank you Giuseppe for your consideration about this topic. 🙏
