### ISSUE TITLE
bydirectional anchor linking

### ISSUE THREAD

**Issue by wisdomlight** [giuspen/cherrytree#1638]
**Describe the solution you'd like**
When using an anchor to link from one node to another. When I click on the link and it takes me to the different node where the anchor is. A way to go back to where I initiated the link - would be great.

**Comment by giuspen** [comment]
The button to go to the previously visited node or its keyboard shortcut which is Alt+Left if I recall correctly should do what you ask

**Comment by giuspen** [comment]
Ok great
