### ISSUE TITLE
[feature request] Key combination to minimize/popup from system tray

### ISSUE THREAD

**Issue by lmattcris** [giuspen/cherrytree#1639]
**Is your feature request related to a problem? Please describe.**
One nice feature of the _ancient_ KeyNoteNF is the association to a key combination to minimize the application to system tray **and** recall it from there.
Don't know how much this is feasible/practical with the multiple OSes supported by cherrytree, but it could come in handy. The application can be stored away when doing some other work, then be recalled to add data to notes.

**Describe the solution you'd like**
Well, a _programmable_ key could be cool, but as I wrote above, I have no idea if that's a mess to support on different OSes and window managers

**Comment by giuspen** [comment]
If you have system tray enabled in the preferences dialog, then Ctrl+Q or Alt+F4 will minimise to tray. For the opposite, so to un-minimise, you will need to create a desktop dependent shortcut that launches the "cherrytree" command

**Comment by lmattcris** [comment]
Uhm... I just tried it on Win 10 and it doesn't work.
I assigned to it a different key combo on desktop, like Ctrl + Shift + F12, and it starts as expected. Then I press Ctrl + Q or Alt + F4 and it docks to the tray, fine.
However when I press again Ctrl + Shift + F12 it doesn't pop up, **neither** it does spawn a second process - I'm quite confident that this is avoided by cherrytree, as it's application's duty

**Comment by giuspen** [comment]
Ok I'll check

**Comment by lmattcris** [comment]
Good news on Ubuntu though: the same setting on Lubuntu, with LxQt / Shortcut settings, does work

**Comment by giuspen** [comment]
This has been solved already from https://github.com/giuspen/cherrytree/issues/1631 and will be OK in0.99.37
