### ISSUE TITLE
Nodes created on Windows are invisible on Linux

### ISSUE THREAD

**Issue by polcad** [giuspen/cherrytree#164]
Nodes created on Windows (rich text, maybe other types as well) are invisible on Linux. Sometimes CherryTree freezes when opening *.cdt by double clicking on it (Linux Mint).

**Comment by giuspen** [comment]
You have to provide a concrete example because I never had the issue and
please specify the cherrytree version

**Comment by polcad** [comment]
I had Windows ver 0.37.1 and linux ver 0.33.4. However after upgrading the linux version of CherryTree to match the Win version , the problem is gone so I presume it was version incompatibility. Unfortunatelly I do not have that database anymore, because Cherrytree destroyed it when I was traying to open it once in linux, then win, then linux.

**Comment by giuspen** [comment]
Please use always the latest version in any operative system. About the
database destroyed, you can see if you still have the backups that are in
the same folder with same name and trailing ~

**Comment by polcad** [comment]
I realized later that there was a version mismatch. There is a very old (0.23 I believe) version of Cherrytree in Ubuntu repositories that was originally causing problems. That probably should be updated.
I like Cherrytree very much and I would have a feature request (1) to make possible to select multiple nodes for printing. At the moment it is only one or all. (2) Make it possible to define the subnode level from the top to print. Also quality of images in pdf is a bit low, printed from xml database.

**Comment by lurch** [comment]
ISTR I once saw something like this myself a long time ago, where _some_ notes (but not all notes) added to CherryTree in one OS were invisible when viewing the same notes in a different OS (I was using both Linux and Windows, but I can't remember on which OS I was creating the notes and on which they were invisible).

I eventually worked out that the notes weren't _actually_ invisible, but were simply being displayed with the same colour for the text and the background! So all I had to do was highlight-all, change the font colour, and suddenly my notes were visible again :slightly_smiling_face:

**Comment by txe** [comment]
Closing, it is possible now to print subnotes and image quality is imporoved
