### ISSUE TITLE
CTRL+SHIFT+ENTER Able to Modify Locked Notes with Numbered Lists

### ISSUE THREAD

**Issue by puddlecheese** [giuspen/cherrytree#1640]
**Version, Operative system**
Windows 10 Enterprise
0.99.29

**Describe the bug**
On locked documents with auto-generated numbered lists, pressing CTRL+SHIFT+ENTER will add 3 whitespaces to the locked document on a row that is part of a numbered list.

**To Reproduce**
If applicable, attach a non-personal document where the issue can be reproduced systematically.
1. Create a node.
2. Type "1. text"
3. Press ENTER to auto-generated the next numbered line
4. Lock the note, then press CTRL+SHIFT+ENTER
5. 3 whitespaces may be added to the end of the text on the row in the numbered list

I am using a slightly old version, I can see if I can reproduce on a newer version later when I'm not at work. Just wanted to get this documented, just in case...

**Comment by giuspen** [comment]
Thanks will be fixed in 0.99.37
