### ISSUE TITLE
Error Parsing the CherryTree File

### ISSUE THREAD

**Issue by a56z** [giuspen/cherrytree#1642]
Hi, I saved the CherryTree file in Windows 10. When opening the same file in Linux it gives me the following error:

`Error Parsing the CherryTree File:
"array::at:__n(which is 121) >=_Nm(which is 49)"`

Please advise how to fix this so I can this CherryTree document (ctb) in Linux

**Comment by giuspen** [comment]
Hi, you have an older version in Linux where some custome icons for the nodes didn't exist. Just upgrade to the latest

**Comment by a56z** [comment]
cool, that works :)
I'm relatively new to Linux, I downloaded the Ubuntu/debian version and can start the current version manually from the terminal. However starting CherryTree from GUI still loads the old version. 
I tried adding the environment variable with the path of the latest version but that doesn't do it.

Do you mind sharing how I can link the new version to the GUI as and replace the old version?

I basically installed it like this:

```
git clone https://github.com/giuspen/cherrytree.git
cd cherrytree
git submodule update --init
./build.sh
./build/cherrytree
```

**Comment by giuspen** [comment]
Could it be that you installed from the ubuntu software store which has an old snap package?
In that case you have to uninstall that, add the PPA https://launchpad.net/~giuspen/+archive/ubuntu/ppa
```
sudo add-apt-repository ppa:giuspen/ppa
sudo apt update
sudo apt install cherrytree
```

**Comment by a56z** [comment]
Yes that's right, using it for Kali Linux - I didn't see another Debian version for download. 

I have to uninstall CherryTree and then proceed with the 3 lines you just posted to install it properly, correct?

**Comment by giuspen** [comment]
Yep

**Comment by a56z** [comment]
hm ok, not sure exactly why but that's not working on my Kali Linux. 
On the `sudo apt update` I get a 404 on the address:
```
Ign:1 http://ppa.launchpad.net/giuspen/ppa/ubuntu impish InRelease
Err:3 http://ppa.launchpad.net/giuspen/ppa/ubuntu impish Release
  404  Not Found [IP: 91.189.95.85 80]
Hit:2 http://kali.download/kali kali-rolling InRelease
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/giuspen/ppa/ubuntu impish Release' does not have a Release file.
 Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```
then when installing via `sudo apt install cherrytree` it again installs the 0.99.30 version:
```
Unpacking cherrytree (0.99.30+dfsg-1) ...
Setting up cherrytree (0.99.30+dfsg-1) ...
```

The debian package I downloaded 2 days ago was from the website's gui. 
Is command line installation not working yet for this version on Debian?
Otherwise I'm not sure what I'm missing really.
Thanks for your help, really appreciate it

**Comment by giuspen** [comment]
0.99.30 is the last official version in the Debian repo since you are failing to add the PPA.
You may as well just download the Debian package from the PPA and double click https://launchpad.net/~giuspen/+archive/ubuntu/ppa/+packages

**Comment by a56z** [comment]
double click after downloading 1-3 from https://launchpad.net/~giuspen/+archive/ubuntu/ppa/+packages doesn't work. 
Looks like I need literal instruction here...  

The ppa part works now after running `sudo apt-get install software-properties-common` but I still can't use CherryTree. 

What is the exact commands I need to run to install it and run the latest version on Debian?

**Comment by giuspen** [comment]
Try 1-2 and if that also fails 1-1 (they all the same versions but different Ubuntu versions)

**Comment by a56z** [comment]
got ya, also using this it works great. You're the best :)
https://github.com/giuspen/cherrytree#building-cherrytree-on-ubuntu-2004
