### ISSUE TITLE
Bookmark no longer on top menu bar

### ISSUE THREAD

**Issue by rylos60** [giuspen/cherrytree#1643]
Please add a configurable option to have the bookmarks under a dedicated menu in the top menu bar.

-Scott

**Comment by giuspen** [comment]
I will shortly

**Comment by rylos60** [comment]
Thanks much!

-Scott
________________________________

**Comment by giuspen** [comment]
there will be an option in preferences dialog tab miscellaneous in 0.99.37

**Comment by rylos60** [comment]
You sir are awesome!

Thank you
-Scott
________________________________

**Comment by rylos60** [comment]
Quick question. Is there a way to automatically bold the txt when using the insert timestamp function?

-Scott
________________________________

**Comment by giuspen** [comment]
Not at the moment

**Comment by rylos60** [comment]
Thanks for the quick response. Care if I request this on Github?

-Scott
________________________________

**Comment by giuspen** [comment]
Yes please raise a separate issue

**Comment by rylos60** [comment]
Done. Thanks

-Scott
________________________________
