### ISSUE TITLE
[linux] New gnome-icon-theme dependency investigation

### ISSUE THREAD

**Issue by ciranus** [giuspen/cherrytree#1648]
Latest linux CT releases (> 0.99.30) are now requesting a specific '**gnome**-icon-theme' package, which includes old gnome **png** icons.
CT is now using embedded **svg** toolbar/menu icons.
I did not find any explanation in any changelog/threads of this new extra gnome png icons dependency.
I have never used this specific gnome package.

Is it really necessary ? 
Or could it preferably be tagged as 'recommended/suggested' package dependency, only for those who need specific gnome icons ?

**Comment by giuspen** [comment]
I have been reported crashes when that was missing. Basically contains the default GTK icon theme AFAIK.
It is true that cherrytree is embedding all the extended stock icons but there are still icons that GTK gets from the theme.

**Comment by ciranus** [comment]
It is weird to add a 17M  icons package **unused** by CT because someone assumed one day that lack of this package could explain a crash . Very probably wrong analysis.
Never seen any crash without 'gnome-icon-theme' package, and never used it.
Furthermore, reverse dependency list of 'gnome-icon-theme'  is very limited.

libgtk**2**.0-0 depends on  'gnome-icon-theme' .
libgtk-**3**-0 does not depend on 'gnome-icon-theme' , then definitively should not be necessary.

**Comment by ciranus** [comment]
One more comment on this strange new gnome-icon-theme dependency.
CT 0.99.**30** package [from Debian](https://packages.debian.org/bullseye/cherrytree) does not need gnome-icon-theme.
Impossible to track when and why gnome-icon-theme has been introduced after 0.99.30.

[Debian/Ubuntu compilation instructions](https://github.com/giuspen/cherrytree#building-cherrytree-on-ubuntu-2004) also show that gnome-icon-theme (which is not a dev package) has been added as build dependency.

What happened from 0.99.30 to 0.99.36 is still a mystery.

**Comment by giuspen** [comment]
If I remember correctly, the gnome-icon-theme is to ensure that we have a full valid Gtk stock. The absence in the system of a gtk stock icon in use in cherrytree would cause an exception and consequently a crash. I can try and remove the dependency but ther eis the risk of ending up with some users experiencing crashes, not sure if it's worth

**Comment by ciranus** [comment]
I have **never** installed `gnome-icon-theme` package in my system (Debian or Ubuntu), and both Debian & Ubuntu has never added  `gnome-icon-theme` as CT dependency, and these icons are **not used** by CT.
Never seen anywhere any crash or justification without this **15,6 Mo** package dependency.
I am 99% sure that the crash you have in mind was not caused by lack of `gnome-icon-theme`.
I still install 0.99.43 (unconventional way) **without** `gnome-icon-theme` package .
Then minor remark, but never seen any justification of this sudden new dependency.

**Comment by giuspen** [comment]
I will simply look at what other Gtk3 apps such as gedit, inkscape, do and if those apps do not have such dependency I'll remove it

**Comment by ciranus** [comment]
gedit
```
Depends: gedit-common gedit-common gir1.2-glib-2.0 gir1.2-gtk-3.0 gir1.2-gtksource-4 gir1.2-pango-1.0
gir1.2-peas-1.0 gsettings-desktop-schemas iso-codes python3-gi python3-gi-cairo python3 python3.9 libatk1.0-0 libc6
libcairo2 libgdk-pixbuf-2.0-0 libgirepository-1.0-1 libglib2.0-0 libgspell-1-2 libgtk-3-0 libgtksourceview-4-0
libpango-1.0-0 libpeas-1.0-0 libxml2
```
inkscape
```
Depends: libpoppler-glib8 librsvg2-common python3 libatkmm-1.6-1v5 libboost-filesystem1.74.0 libc6 libcairo2
libcairomm-1.0-1v5 libcdr-0.1-1 libdbus-glib-1-2 libdouble-conversion3 libfontconfig1 libfreetype6 libgc1 libgcc-s1
libgdk-pixbuf-2.0-0 libglib2.0-0 libglibmm-2.4-1v5 libgomp1 libgsl25 libgspell-1-2 libgtk-3-0 libgtkmm-3.0-1v5
libharfbuzz0b libjpeg62-turbo liblcms2-2 libmagick++-6.q16-8 libpango-1.0-0 libpangocairo-1.0-0 libpangoft2-1.0-0
libpangomm-1.4-1v5 libpng16-16 libpoppler102 libpotrace0 libreadline8 librevenge-0.0-0 libsigc++-2.0-0v5 libsoup2.4-1
libstdc++6 libvisio-0.1-1 libwpg-0.3-3 libx11-6 libxml2 libxslt1.1 zlib1g
```
**gtk3** is not **'gnome**'. gtk3 installs both `adwaita-icon-theme` `hicolor-icon-theme` by default.
Only these 2 themes could have potentially been used by CT, but never `gnome-icon-theme.`

libgtk-3-0
`Depends: adwaita-icon-theme hicolor-icon-theme`

Even thunderbird and firefox do not need  `gnome-icon-theme`. 
I am not 99% sure that gnome-icon-theme has never been required by CT, but 100% sure.

**Comment by giuspen** [comment]
OK
