### ISSUE TITLE
Spell check

### ISSUE THREAD

**Issue by Camilot55** [giuspen/cherrytree#1651]
Hi, Giuseppe.
 In Cherrytree, spell checking is only used for rich text. Why not enable this function for plain text as well. Let this function remain in its original place, but when it is enabled, it checks the spelling of both rich text and plain text. At the moment, I'm preparing a new settings dialog.

**Comment by giuspen** [comment]
Hi Viktor you are probably right, I'll see if I can include the plain text.

**Comment by Camilot55** [comment]
I looked at this question. There are a lot of fixes for me. And I'm afraid of making mistakes in your code. I think you can do it much faster!

**Comment by giuspen** [comment]
Sure no worries I'll do it shortly if feasible as it should

**Comment by Camilot55** [comment]
Hi, Giuseppe. 
Look at this other error:
[2021-04-26 08:48:57.832] [gtk] [critical] Class::register_derived_type(): base_query.type_name is NULL.

**Comment by giuspen** [comment]
Hi Viktor when are you seeing it?

**Comment by Camilot55** [comment]
![Error](https://user-images.githubusercontent.com/76065578/116121842-77ec7a80-a6da-11eb-9608-f850f940020b.png)

**Comment by giuspen** [comment]
OK Viktor I made the change while leaving the control in the rich text tab.  About the error I think it's windows only, could be a Gtkmm windows build issue, I haven't understood yet what causes it.
