### ISSUE TITLE
Copy bug in case of quick app closing

### ISSUE THREAD

**Issue by ony2020** [giuspen/cherrytree#1652]
**Version, Operative system**
0.99.36, Windows 8.1

**Describe the bug**
When I copy a text in cherrytree and close the app quickly and go to e.g. notepad, there is nothing to paste, I have tried to copy and wait a little bit and everything works perfectly ,which indicate that the copy process in cherrytree takes a second or more. Also be aware that if you have something copied before repeating the bug it will not be there to paste in another apps which means, there is a bug that wipe everything in clipboard

**To Reproduce**
1. Go to 'any cherrytree file'
2.  'copy any text using Ctrl + C or copy from right click menu'
3. after you copied close cherrytree as fast as possible
4. go to another app and you will see that there is nothing to be pasted

**Comment by giuspen** [comment]
I'm not sure there is a way to fix this, it's the way the clipboard works it's basically fetching the data from cherrytree at paste time but if you closed cherrytree the source is no longer there. If you copy as plain text only Ctrl+Shift+C though it may work

**Comment by ony2020** [comment]
I have tried copy as plain text, it didn't worked either. I wonder if it's possible to put the copied data in the clipboard regardless if cherrytree is open or not. **Edit**  the bug happens in particular when you save the changes if you make new file and copy text without saving the file it works fine.

**Comment by ony2020** [comment]
I have tried copy as plain text, it didn't worked either. I wonder if it's possible to put the copied data in the clipboard regardless if cherrytree is open or not. I have tried to repeat the same bug in the cherrytree_0.39.4 version and there is no such bug. maybe it is related to GTK 3 on Windows

**Comment by ony2020** [comment]
I have tried copy as plain text, it didn't worked either. I wonder if it's possible to put the copied data in the clipboard regardless if cherrytree is open or not. I have tried to repeat the same bug in the cherrytree_0.39.4 version and there is no such bug. maybe it is related to GTK 3 on Windows

**Comment by giuspen** [comment]
I may be able to do something for the plain text only case, I'll have a look
