### ISSUE TITLE
[0.99.36-linux] icons missing in extended vertical toolbar list

### ISSUE THREAD

**Issue by ciranus** [giuspen/cherrytree#1653]
![ksnip_20210424-225808](https://user-images.githubusercontent.com/61602511/115972872-56ac5280-a551-11eb-8de2-b0068f020059.png)

Icons should preferably be visible in extended vertical toolbar list.

**Comment by giuspen** [comment]
Not sure if it's possible to do anything there but you can configure a second row of toolbar icons in the preferences dialog

**Comment by ciranus** [comment]
If I am not wrong (I should check), they were visible in all previous CT release (< 0.99.**30**).
Well, minor issue, unless it is identified as a regression.

**Comment by giuspen** [comment]
I'll check, note that anyway unfortunately displaying icons in the menus is deprecated (what a silly decision from Gtk), we are displaying icons in the menus using a home made mechanism but that menu is automatically generated from the toolbar widget with the icons that do not fit

**Comment by ciranus** [comment]
Understood; probably a regression from gtk2 to gtk3.
Thanks for the clarification.
