### ISSUE TITLE
URL detection doesn't recognize TAB as a delimiter

### ISSUE THREAD

**Issue by xpalidotious** [giuspen/cherrytree#1654]
When pasting text that contains URLs, cherrytree will automatically detect the URL and recognize a space character as the end of the URL. But if a URL is followed by a TAB character, then the weblink in cherrytree will end up including the tab and any text that follows the tab until there is a space, EOL or other delimiter.

To reproduce the issue you may need to paste the example below into a plain text editor first since github does something funny with tabs:

1. paste the example below into a text editor
2. copy and paste the text from the editor into a rich text node in cherrytree

> http://www.example.com/example-with-tabs.html	ThisShouldNotBePartOfTheURL!
> http://www.example.com/example-with-spaces.html    ThisShouldNotBePartOfTheURL!

This is an old issue that goes back at least a few years and is still current in windows version 0.99.36.

**Comment by giuspen** [comment]
I'll have a look thanks

**Comment by giuspen** [comment]
thanks will be OK in 0.99.37
