### ISSUE TITLE
Unable to import nmap file

### ISSUE THREAD

**Issue by khaoticdude** [giuspen/cherrytree#1656]
**Version, Operative system**
0.99.30

**Describe the bug**
Nmap is a port scanning tool. For it's file output, it uses the .nmap extension. It's essentially just a .txt file. However to import this file, you have to manually change the extensions to .txt.

**To Reproduce**
Try to import a simple text file with the extension .nmap

**Comment by giuspen** [comment]
I haven't found a way to detect the file type on Windows yet except via the extension

**Comment by khaoticdude** [comment]
I'm using CT on debian On Apr 27, 2021 02:17, Giuseppe Penone ***@***.***> wrote:
I haven't found a way to detect the file type on Windows yet except via the extension

**Comment by ciranus** [comment]
@khaoticdude 
The problem of windows is that the file extension is used to extrapolate the file type.
It seems .nmap exotic extension has different meaning in the windows environment (network tool, or NaviComputer Map Format / unclear).
Is it a big problem to open the nmap text file in a text editor, and just copy the content to CT ?

**Comment by giuspen** [comment]
@khaoticdude can you attach one of such .nmap files? (Maybe zipped) In Linux the detection of file type is quite robust so it surprises me.

**Comment by khaoticdude** [comment]
Sure, here you go 
[nmap.zip](https://github.com/giuspen/cherrytree/files/6385921/nmap.zip)

**Comment by giuspen** [comment]
This will be fixed in 0.99.37

**Comment by khaoticdude** [comment]
Awesome! what was the fix?

**Comment by giuspen** [comment]
This was actually a regression in the porting from the old pygtk2 to the current gtkmm3

**Comment by khaoticdude** [comment]
Makes sense. I remember it used to work fine a while back.On May 2, 2021 16:52, Giuseppe Penone ***@***.***> wrote:
This was actually a regression in the porting from the old pygtk2 to the current gtkmm3

**Comment by khaoticdude** [comment]
Kali Linux finally pushed out the latest version of CherryTree. Are you not able to import files anymore?!?!
