### ISSUE TITLE
Menu-bar and Toolbar dark mode

### ISSUE THREAD

**Issue by tetrahedon7** [giuspen/cherrytree#1657]
OS: Linux Mint 20.1 Cinnamon (4.8.6)
Version: 0.99.36

When I select "dark background, light text" in Theme, it only darkens the tree panel but the menu-bar and toolbar remain light. All the controls are also in light mode. Is there a way to fix this, that I'm missing? If not, please make this feature available; the white bars over an otherwise dark background is quite jarring

![Screenshot from 2021-04-27 11-02-19](https://user-images.githubusercontent.com/69251025/116190816-ee27c600-a748-11eb-882a-5e38085c504b.png)

**Comment by Camilot55** [comment]
@tetrahedon7 You have an LM. Please configure the system. I don't have one. See screenshots
![Снимок экрана от 2021-04-27 12-52-16](https://user-images.githubusercontent.com/76065578/116206102-e6bbe900-a757-11eb-9cf8-33432a2f4f73.png)
![Снимок экрана от 2021-04-27 12-53-03](https://user-images.githubusercontent.com/76065578/116206111-e7ed1600-a757-11eb-8d25-aa32e9b41681.png)

**Comment by tetrahedon7** [comment]
Everything's already set to dark theme though. I'm not facing this issue with any other application..

![image](https://user-images.githubusercontent.com/69251025/116293414-7d1df800-a7b4-11eb-88b0-5ed8d3cde6d8.png)

**Comment by tetrahedon7** [comment]
For some weird reason, after changing the "Controls" theme a couple of times and restoring the theme back to Arc-Dark seems to have... fixed the issue. I don't know what happened there, I'd done the same thing before. Sorry for bothering about a non-issue, and thanks..

**Comment by rajhlinux** [comment]
I also had the same issue. 
Seems like we need to configure GTK GUI library directly.

This is what did the trick for me on FreeBSD 14.2:

Close cherry tree.
Then open terminal and enter:
`export GTK_THEME=Adwaita:dark`

Open cherry tree again and it should apply a dark theme which won't burn your eyes.

![Screenshot_20240826_210151](https://github.com/user-attachments/assets/cf1476a1-3fa0-4201-a416-c03df9fae96d)
