### ISSUE TITLE
High Resource Usage - Performance issues

### ISSUE THREAD

**Issue by izysec** [giuspen/cherrytree#1658]
Hi,

I've been using CherryTree for a while now for my note taking. Currently running 0.99.18. My cherry tree probably has 100+ nodes in totality with text, links and screenshots.

Off late, I've noticed performance issues with CT. 
- When typing, often (~15-20 seconds) CherryTree completely hangs for 2-3 seconds
- I notice that more than even my browsers, CT takes more memory (screenshot)
- Also, when I hit save, or it auto-saves, the CPU utilization can go extremely high causing CT to hang again until the save is complete (screenshot)

I figure this is maybe because there is too much data in my current instance. My database is encrypted and my Notes.ctz file is ~65mb. My questions are
a. Is this normal given my data size?
b. Is there a recommended # of trees/amount of data CT can process smoothly after which it's recommended to have a new CT instance?

![image](https://user-images.githubusercontent.com/64199310/116514876-3e3d8e80-a8e9-11eb-972b-32832e7a3919.png)

**Comment by mimecry** [comment]
0.99.18 is nearly 20 releases ago. best that you update to 0.99.36 first to see if your problem persists. for what it's worth i think 65 MB is nowhere near heavy enough to be causing that sort of lag

**Comment by izysec** [comment]
Thanks @mimecry I didn't realize I wasa _that_ out of date. I have updated to the latest, but I see similar issues. Saving causes CPU utilization to go upto 70% and hangs CT for a minimum of 5 seconds.

**Comment by mimecry** [comment]
have you confirmed that the issue is limited to just your 65 MB .ctz, by trying to reproduce the issues with a brand new .ctz file?

**Comment by giuspen** [comment]
You should use the SQLite database so that at save time it will save only what you edited rather than the whole tree as XML database does (File--SaveAs). Still being password protected it is basically compressing and password protecting at every save 65 MB of data. About the memory usage you can reduce the number of undo states in the preferences dialog.

**Comment by izysec** [comment]
Thank you guys. Changing it to an SQLite db made the response time a lot faster. And reducing the undo states from 20 -> 7 has pulled CPU usage down to ~80MB (from 1600). Hang during save time has reduced to about 1 second from 5-7 and CT CPU usage spikes to ~40% at the time. 

Thanks again! I will close this issue out :)

**Comment by mimecry** [comment]
@izysec just curious, are you doing work on a SSD or HDD?

**Comment by ciranus** [comment]
@izysec
Splitting your 65MB document in smaller documents (5 ?) classified by theme can clearly help (this is what I've done some time ago). It also contributes to more clarity (less nodes per tree).
What you need to protect with a password can be moved to a separate protected .ctz document.
For info, do you have a lot of images in your document ?

**Comment by izysec** [comment]
@mimecry  - I'm on a laptop which has a harddisk but also a 250gb SSD so I'm assuming it's utilizing both. I'm not specifically running on a particular one.

@ciranus - Thanks for the suggestion. Splitting was definitely an answer, just that I've really got that many related notes in this one. I could move out the older/archived nodes to another document. Also, I'd prefer for all my documents to be password protected. Using the SQLite db format, password protected works fine.
Do I have a lot of images - I do! Lots of images and screenshots :)

**Comment by ciranus** [comment]
> Lots of images and screenshots :)

This is the root cause of fast growing documents.
I have raised this investigation long time ago: any possibility of storing images in a separate folder, but it was a bit late in 0.99 development.

**Comment by mimecry** [comment]
@izysec i meant to ask if you're writing your CT database to a SSD or HDD, as there should be a rather significant difference between the two
