### ISSUE TITLE
[0.99.36] Command type list not saved in config.cfg

### ISSUE THREAD

**Issue by ciranus** [giuspen/cherrytree#1660]
**Version, Operative system**
[0.99.36] linux

**Describe the bug**
Command type list modification in Preferences is not saved in config.cfg

**To Reproduce**
1. Modify command list in preferences
2. Close/reopen CT
3. The default list is still visible.

**Screenshots**
![ksnip_20210429-212344](https://user-images.githubusercontent.com/61602511/116606972-bb8cf180-a931-11eb-932e-02109adc5afc.png)

**Comment by giuspen** [comment]
It is not saved if you **remove** a default item at the moment, yes, there was another issue about this if I remember correctly. Do you confirm that the issue is only when you remove something and that re-appears?

**Comment by ciranus** [comment]
Adding or removing items will not be saved. 100% reproducible.
Not a big issue, but I thought it should be saved.

**Comment by giuspen** [comment]
Sure I'll have a look

**Comment by giuspen** [comment]
Adding works for me as expected. I tried adding a command for awk, can you try the same and say if it works for you? You should have someting like this in the config.cfg then:
```
[codexec_type]
awk=awk -f <tmp_src_path>
```

**Comment by ciranus** [comment]
I still confirm.
Have added awk, close/reopen. awk is not there.

Nothing like [codexec_type] in config.cfg.

**Comment by giuspen** [comment]
Can you build latest from GitHub and try that?

**Comment by ciranus** [comment]
I would prefer to avoid specifically installing the dev environment which requires **368 MB** of extra code !
This is a minor issue..
I don't think it's a big risk if you propose your change in 0.99.37.
I propose to report back on this later.
