### ISSUE TITLE
Changed margins in the page setup

### ISSUE THREAD

**Issue by frodo5** [giuspen/cherrytree#1664]
cherrytree_0.99.36.0_win64_portable.7z

**Is there a possibility the changed margins in the page setup to save?** 

![1](https://user-images.githubusercontent.com/82698833/116779771-a2428d00-aa78-11eb-9f76-cfee39fdaeb9.png)

**Comment by giuspen** [comment]
I will check if those values can be retrieved from that dialog yes

**Comment by giuspen** [comment]
the settings will be preserved since next version 0.99.37
