### ISSUE TITLE
[linux] locale LANG/LANGUAGE system variable

### ISSUE THREAD

**Issue by ciranus** [giuspen/cherrytree#1667]
**Version, Operative system**
All CT up to 0.99.36; LINUX (Debian).

**Describe the bug**
If lang file is empty or contains `default`, CT starts without error. The system language will be used by CT
However, if a language is selected in Preferences, lang file will be filled with **xy** (=en, it,fr etc), and CT will then start with this error:

```
$ cherrytree
** Message: 21:38:48.321: Language overwrite = en (localedir = /usr/share/locale)

(process:13132): Gtk-WARNING **: 21:38:48.325: Locale not supported by C library.
Using the fallback 'C' locale.
```
but the correct CT locale should be found at `/usr/share/locale/<xy>/LC_MESSAGES/cherrytree.mo`

I've found why this error is reported in a terminal.
There are two system variables: **LANG** and **LANGUAGE**.

examples:
```
$ printenv | grep LANG

LANG=en_US.UTF-8 ; LANGUAGE=en
LANG=fr_FR.UTF-8 ; LANGUAGE=fr
LANG=it_IT.UTF-8 ; LANGUAGE=it
```

If CT is started with `LANGUAGE=xy cherrytree` , **without** any lang file, everything works fine without error.
It then seems that CT is passing `<xy>` to the system as **LANG**=xy (wrong), and not **LANGUAGE**=xy.

I did not find in the CT code how LANG or LANGUAGE variable is passed to the system, but replacing LANG=xy by LANGUAGE=xy will avoid the locale error reported in a terminal.

**Comment by giuspen** [comment]
```
    const std::string ct_lang = CtMiscUtil::get_ct_language();
    if (ct_lang != CtConst::LANG_DEFAULT) {
        const std::string ct_lang_utf8 = ct_lang + ".UTF-8";
        if ( fs::alter_locale_env_var("LANGUAGE", ct_lang + ":en") and
             fs::alter_locale_env_var("LANG", ct_lang_utf8) and
             fs::alter_locale_env_var("LC_ALL", ct_lang_utf8) ) {
            g_message("Language overwrite = %s (localedir = %s)", ct_lang.c_str(), fs::get_cherrytree_localedir().c_str());
        }
        else {
            g_critical("Couldn't set language %s", ct_lang.c_str());
        }
    }
```

**Comment by ciranus** [comment]
I've found many more files in the code which contain `lang` string, but I don't understand the mechanism at all.
Then if you know... you know !!

Very old issue:
`language does't change · Issue #1422 · giuspen/cherrytree` https://github.com/giuspen/cherrytree/issues/1422

**Comment by ciranus** [comment]
Low priority in May 2021, but still need some clarification with 0.99.43.

Only 2 language selections are possible:
1 - the default lang defined by the system is OK
2 - or english only / nothing more.

This might not be an issue for 99% of users.
However, the correct behavior should be that any UI language should potentially be selected according to the preferences lang list.

A confirmation of this issue is however needed (as I had previously installed localepurge, but of course reinstalled `/usr/share/locale/xy/LC_MESSAGES/cherrytree.mo` files for this test.
