### ISSUE TITLE
Drag and drop (to-do) lists

### ISSUE THREAD

**Issue by instancezero** [giuspen/cherrytree#1669]
**Is your feature request related to a problem? Please describe.**
It is tedious to rearrange a list of items in a node. This primarily refers to to-do lists but would be useful generally.

**Describe the solution you'd like**
1) Mouse down on the list bullet
2) drag to new position in list
3) mouse up, text is moved to new location.

Use case:
I have just imported about 100 related items from multiple sources. Many of these items are redundant/related and drag/drop would make it a lot easier to get them organized.

**Comment by giuspen** [comment]
You can use Alt+Up/Down to move rows up/down if that may help with this task

**Comment by instancezero** [comment]
Indeed. That works. It would be helpful if these things were in menus or sub-menus so we can discover shortcut keys.

Also one small thing: If the row is indented, it loses the indentation. Not a big deal (already discovered the crtl-alt-> and < shortcuts for indent) but still a minor inconvenience.

**Comment by giuspen** [comment]
It should be in the right click menu I think, I'll check

**Comment by instancezero** [comment]
It is. I should have found that! Thanks.

**Comment by giuspen** [comment]
I'll look at the loss of indentation
