### ISSUE TITLE
[gtk3 version] New line feature with optional carriage return

### ISSUE THREAD

**Issue by ciranus** [giuspen/cherrytree#1671]
Horizontal rule feature has been modified from gtk2 to gtk3.
I did not find in the change log when this modification has been introduced, and why, but previous horizontal rule behavior was fine to me.

With CT-gtk2, horizontal rule was just horizontal rule.
With CT-gtk3, horizontal rule is horizontal rule + carriage return.

**Proposal**: give the flexibility in preferences to choose with or without carriage return, by adding an explicit regex **\n** in "Horizontal rule" configuration preferences.

Replace in Preferences:
![NL](https://user-images.githubusercontent.com/61602511/117063954-d4c4e200-ad25-11eb-8ad0-0f171c79ea6a.png)
Illustration:
If I want to add an horizontal rule between `AAAAA` and `BBBBB`, placing the cursor before first B, and adding horizontal rule + carriage return is OK.

![nl2](https://user-images.githubusercontent.com/61602511/117065170-6d0f9680-ad27-11eb-9962-bccb020b8310.png)

However, if an empty line is already inserted between `AAAAA` and `BBBBB`, an extra empty line is not needed. It will be added, but then necessary to remove it.

![nl3](https://user-images.githubusercontent.com/61602511/117066147-aac0ef00-ad28-11eb-8d8d-ce16556fe43f.png)

**Comment by giuspen** [comment]
Ok

**Comment by ciranus** [comment]
For info, I use `―` (which name is "HORIZONTAL BAR" / UTF8- 0xE2) instead of `~` used as default.
Better for me. Don't know if it could be considered as an improvement, but it would break HR consistency for already existing documents.

```
~~~~~~~~~~~~~~~~~~~~~~~~~~

――――――――――――――――――――――――――
```
