### ISSUE TITLE
Bookmarks menu missing on the latest version

### ISSUE THREAD

**Issue by lucaszarzur** [giuspen/cherrytree#1672]
Version: 0.99.36
S.O.: Ubuntu 20.04

In the old versions, at least the 0.99.24 the "Bookmarks" menu is on the top menu of Cherrytree. I downloaded the latest version to test, and I miss this option.  I know that the "Bookmarks" is in the "Tree" menu, but as it was before it is much better.

See the attached Screenshots to compare the versions.
![new version - bookmarks is not present](https://user-images.githubusercontent.com/48775448/117195897-3a63ad80-adbc-11eb-94f5-df6eb0e01388.png)
![old version - bookmarks present](https://user-images.githubusercontent.com/48775448/117195898-3afc4400-adbc-11eb-87bf-9a78e87ae350.png)

**Comment by giuspen** [comment]
Don't worry it will be back (configurable) in 0.99 37, for now you find it under the tree menu only

**Comment by ciranus** [comment]
This is also the very first thing I've noticed when trying 0.99.36 (from 0.99.30).
issue closed 14 days ago => Bookmark no longer on top menu bar #1643
