### ISSUE TITLE
GUI should explain nature of "encrypted" files

### ISSUE THREAD

**Issue by manad777** [giuspen/cherrytree#168]
So I just found out that encrypted cherrytree documents are just password-protected 7zip files. When you open the file, it extracts it in /tmp, and works on it there. On _graceful_ application closing, it clears the temp file. This means that if the app crashes, or the system shuts down suddenly, the unencrypted file is still there in /tmp. 

I have no problem with this. There's no shame in not providing hardcore/in-RAM encryption (and the current method is enough for me). I just think this isn't communicated well, and for some people, this isn't secure enough. 

Improvement suggestion:
In the first save dialog, where you select file type, if user selects an encrypted options, a text label appears in the same window that explains what CT does. Something like this:

> CT will save the document in an encrypted 7zip archive. When viewing or editing a document, CT will extract the encrypted archive to a temporary folder, and work on this unencrypted copy. When closing gracefully, the document is placed in an encrypted archive again, then deleted from the temporary directory. Note that in the case of an ungraceful CT shutdown, such as an application or system crash, the unencrypted document will remain on the disk as a temporary file.

**Comment by giuspen** [comment]
I will do how you advice or similarly in the next major version, thank you
:)

**Comment by giuspen** [comment]
Implemented in https://github.com/giuspen/cherrytree/commit/8ed315b09b9d4dc5bd637b37ec4f86ceabf55880

**Comment by crestone** [comment]
May be good idea using memory for this?
I mean - https://www.sqlite.org/inmemorydb.html
