### ISSUE TITLE
Add additional spell checking options 

### ISSUE THREAD

**Issue by Jernel-dotcom** [giuspen/cherrytree#1683]
Add additional spell checking options.
Currently, only one language could be selected.

Suggestion to add additional option for spell checking.
To archive an ability to select multiple languages.

![image](https://user-images.githubusercontent.com/60522029/118364136-d8ffc380-b59f-11eb-8a80-a22da4b969d2.png)

**Comment by giuspen** [comment]
It is not possible with the current library (gspell) I will need to investigate alternatives

**Comment by v217** [comment]
I need the languagetool.org spell checker too.
A possible workaround is using https://github.com/alboro/fractalnote with the languagetool extension for your browser.

**Comment by v217** [comment]
Another workaround option is just to pipe the most recent edited node content through https://github.com/Findus23/pyLanguagetool and append the output to the node content of the cherrytree sqlite file.

**Comment by Jernel-dotcom** [comment]
@v217 There is an option to ingrate it with cherrytree?
