### ISSUE TITLE
BUG: Copy/Paste Linux Non-Ascii Characters

### ISSUE THREAD

**Issue by godylockz** [giuspen/cherrytree#1687]
**Version, Operative system**
Debian Linux (Latest Version / OS)

**Describe the bug**
Copying and Pasting text includes a weird ascii character feff  at the beginning of the text inserted.

**To Reproduce**
1. Download Tilix (Terminal Emulator)
2. Open Tilix
3. Run a command `whoami`
4. Select text, Right-Click, Copy as HTML
5. Paste into CherryTree

**Additional**
Possible fixes to prevent this problem going forward:
- Look at beginning / end of a paste and if any non-ascii characters are detected, delete them.
- Remove leading/trailing whitespace characters on paste

If you need clarification, let me know. I am running CherryTree version 0.99.36

**Comment by godylockz** [comment]
I believe what I am seeing is what is called a "Byte Order Mark" (i.e. FF EF) being pasted into cherrytree

**Comment by giuspen** [comment]
I just tried to copy as html and paste in a rich text node in cherrytree 0.99.37 and I didn't see those characters. Have you tried on 0.99.37 yet?

**Comment by godylockz** [comment]
Yes I am running the latest version. Did you try to copy and paste that text outside of cherry tree? That's when I can see it.

**Comment by giuspen** [comment]
It is not clear to me what "paste that text outside of cherrytree" means. Reading your issue you say 5. Paste into CherryTree

**Comment by godylockz** [comment]
So if I copy and paste the text as html, cherry tree interprets it and looks fine. However when I select the text and recopy it to another source I then see the prepended <ffef>. If you like, I can attach a cherry tree doc with an example.

**Comment by giuspen** [comment]
I tried to subsequently copying from cherrytree and pasting to libreoffice writer or geany text editor and didn't see the bad characters. Can you tell me what external app shows the characters when pasting from cherrytree?

**Comment by godylockz** [comment]
I was using notepad++ to convert the encoding and was able to see the bad characters were there. Also, cyberchef can give you the actual hex code:
https://gchq.github.io/CyberChef/#recipe=To_Hex('Space',0)&input=77u/TElTVEVOCgrvu79MSVNURU4

Bad characters in this example are: EF BB BF, which is a byte order mark when googled.
[badchars.zip](https://github.com/giuspen/cherrytree/files/6535379/badchars.zip)

**Comment by giuspen** [comment]
OK I fixed it thanks

**Comment by godylockz** [comment]
Thank you 👍
