### ISSUE TITLE
Move node to another database file

### ISSUE THREAD

**Issue by Groberen** [giuspen/cherrytree#1688]
**Is your feature request related to a problem? Please describe.**
Have a relatively big cherrytree database with many nodes, this database has grown over time.
Now, several nodes are old, and I'd like to archive those - preferably transfer it to another cherrytree database. Because all of this are personal work, each node have to be hand picked in order to be removed/archived.

**Describe the solution you'd like**
When two different files are opened - two session of Cherrytree runs at same time - there should be a way of either drag'n drop a node from one database file to another, or being able to copy and paste complete nodes (and sub nodes) between files.

Thank you for a great app

**Comment by giuspen** [comment]
Yes it is something I should support

**Comment by giuspen** [comment]
will be in 0.99.47
