### ISSUE TITLE
Add text font name and test size indication 

### ISSUE THREAD

**Issue by bahtioraliev** [giuspen/cherrytree#1696]
Add text font name and test size indication.

It will be great if we could get indication for fond size and fond name, like it appear in other text editor apps.
![image](https://user-images.githubusercontent.com/76793434/119468944-997b6900-bd4f-11eb-9411-eca7065468bb.png)

For example: I'm wish to change the underline color, so I went to preferences > Format, find multiple sizes, tried to adding the small  size but change the color. At that point I understand that it becomes very complicated to find the size of text you are standing on.

Indication like that could be great solution to reflect the text style where the cursor it pointing on.

**Comment by bahtioraliev** [comment]
Hello @giuspen,
Any plan to add this functionality? If no, let's close this one to indicate that such functionally would appear soon.

**Comment by giuspen** [comment]
Hi, I cannot work on this anytime soon, too much stuff in the backlog

**Comment by bahtioraliev** [comment]
Hi @giuspen, Any chance to include this feature in the near future?
