### ISSUE TITLE
GnuPG for encrypt of notes DB

### ISSUE THREAD

**Issue by crestone** [giuspen/cherrytree#170]
How about to implement encrypt the DB file with GnuPG?
https://bitbucket.org/vinay.sajip/python-gnupg
I think it's powerful capabilities and strong encryption

**Comment by phd21** [comment]
Dear Giuseppe,
I would like this as an option as well.  And the link from "crestone" regarding "python-gnupg" looks like it might be a pretty good option to use for this, either this program itself or perhaps the code within. I checked my Linux Mint 17.3 repositories, and I already have this "python-gnupg" installed, so I think it is available for others Cherry Tree users as well.

**Comment by jargonfilter** [comment]
So is this note taking software not encrypted?

**Comment by steveno** [comment]
> So is this note taking software not encrypted?

There is an option to encrypt the database if you'd like.

**Comment by txe** [comment]
Closing, cherrytree supports encryption, I don't think using GnuPG is reasonable
