### ISSUE TITLE
StatusIcon Does Not Appear In Tray

### ISSUE THREAD

**Issue by gh9000** [giuspen/cherrytree#1703]
**Version, Operative system**
0.99.37, Linux: Arch Linux, Desktop Environment = Cinnamon 4.8.6-1

**Describe the bug**
**Issue 1** - Cherrytree's system-tray icon on first start-up does not appear, but leaves a blank space where the icon should have been in the system-tray (clicking the blank area does nothing). Restarting the Desktop Environment (Cinnamon) or logging-out-then-in, will fix the icon. Sometimes, playing with the DE's  panel height will cause the icon to appear, but it may only partially render (e.g. the leaves of the cherry may be cut off even though the DE's panel is tall enough to accommodate the icon). This occurs whether the Cherrytree preference, “Miscellaneous -> System Tray -> Start Minimized in the System Tray", is enabled or disabled.

**Issue 2** - When starting Cherrytree from the command-line, the following error message appears:
**[2021-05-26 12:29:37.039] [gtk] [critical] gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed**

Issue 1 and 2 seem to be related. At least the source of the issues seems to be from the same IF statement located @ lines 108-117 in file ‘src/ct_app.cc’. 

I tried multiple variations of commenting lines (110-113 in src/ct_app.cc) to see what worked, and the results were:
- commenting line 110 ('_rStatusIcon->set_visible(false);') fixed the icon issue with no apparent or unexpected side-effects, but the error message persisted.
- commenting any of lines 111-113 WITHOUT commenting line 110 fixed neither the icon nor error message issue.
- commenting line 110 while commenting any of lines 112-113 fixed  the icon but not the error message issue.
- commenting line 110 while commenting line 111 fixed  the icon AND fixed the error message issue. Commenting additional lines (112-113) did not modify this desired behavior.
- the ‘expected’ side-effects of commenting any of lines 111-113 would be to modify the attributes of the status icon, i.e. name (line 111), title (line 112), and tooltip (line 113) will be left unset.

Keep in mind that while I did not notice any unexpected side-effects during limited use of Cherrytree with the patch applied, the developer(s) may recognize potential issues without even applying them.  Finally, the modified code for Issue 1 & 2 affects the status icon's name attribute at the very least, something that the developer(s) set with intent and may not want to leave unset.

Finally, it seems very strange to me that I have experienced this behavior in my normal Linux install and in a fresh install of Arch in  VirtualBox, and that the issues have not been reported by anyone else. I have a feeling I missed a previous bug report, or something really odd is going on with my particular set-ups. The bugs have been present in all the 0.99 versions I've had installed, but I kept with 0.39 for several months after 0.99 was released (0.99.32 was the first 0.99 version I installed).

**To Reproduce**
 **--Issue 1**
1. Add Cherrytree to your system's startup applications.
2. Set Cherrytree preference: “Miscellaneous -> System Tray -> Enable System Tray Docking" (preference "Start Minimized in the System Tray" can be enabled or disabled).
3. Restart system.
4. Upon logging in to your Desktop, observe the System Tray. If Cherrytree opens between two apps in the tray, there will be a blank placeholder (a gap the width of its icon). If it opens at either end of your tray, it may be harder to tell there is a placeholder/gap. Nevertheless, the expectation is to see Cherrytree's icon, and there will not be one.
5. Restart your DE or logout/login, and the Cherrytree icon will appear as expected.

 **--Issue 2**
1. Close Cherrytree if it's already running.
2. Open a terminal and run 'cherrytree'.
3. Output will include the following error:
**[2021-05-26 12:29:37.039] [gtk] [critical] gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed**

**Attachment**
The attached 'patch' file combines the modified code to address Issue 1 and Issue 2.

[cherrytree-0.99.37_statusicon_errormsg.patch.txt](https://github.com/giuspen/cherrytree/files/6550433/cherrytree-0.99.37_statusicon_errormsg.patch.txt)

Thank you.

**Comment by giuspen** [comment]
Would it be possible for you to make a pull request?

**Comment by giuspen** [comment]
fixed in 0.99.38
