### ISSUE TITLE
Question: Tiny Font Size in MacOS

### ISSUE THREAD

**Issue by Kayx23** [giuspen/cherrytree#1705]
Why is the default font size so tiny in MacOS? 

![Screenshot at May 27 22-01-40](https://user-images.githubusercontent.com/39619599/119918809-216f9780-bf37-11eb-98d3-48184d0a5c94.png)

While I can adjust the h1-h6 font size in preference, the font in the left pane is still tiny and not readable. I'm on `MacOS Catalina 10.15.7`

**Comment by giuspen** [comment]
You can control the default font sizes in the preferences dialog, tab fonts

**Comment by Kayx23** [comment]
hi @giuspen I have adjusted the scales for all font size (small to h1) to at least 2-3 x. Tried restarting the program as well. They do not seem to have an effect on the default font size, such as the text in the left pane.

**Comment by giuspen** [comment]
No you have to change the font in the tab with name fonts, not the scaling which is for few tags only

**Comment by Kayx23** [comment]
ahh ok found. Thanks
