### ISSUE TITLE
insert webp file

### ISSUE THREAD

**Issue by gargle256** [giuspen/cherrytree#1709]
cherrytree 0.99.37 on win10 20H2

When I try to insert a picture in webp format, cherrytree close without informations.

It occur every time.
The manipulation is :
- insert > insert image
- select a webp picture
- few seconds after, the program close.

I link the test file in zip format. (github don't allow webp too)
[ethernet.zip](https://github.com/giuspen/cherrytree/files/6568940/ethernet.zip)

**Comment by giuspen** [comment]
thanks the image format is not currently supported from the library in use (Glib), such cases are now handled with an error dialog rather than a crash
