### ISSUE TITLE
No more PPAs for older Ubuntus?

### ISSUE THREAD

**Issue by manad777** [giuspen/cherrytree#171]
One of my machines runs the previous LTS, 14.04/Trusty, and I notice the latest version, 0.37.3, was only published via PPA for 16.04/Xenial. 0.37.2 was released for a whole bunch of Ubuntu versions. I was wondering if you just forgot, or if other Ubuntus won't get PPAs from now on? 

It's not a problem if that's the case, I can just uninstall the PPA and start using the tar file from the website, like I used to before I discovered the PPA.

**Comment by giuspen** [comment]
I just forgot, thanks for notifying :)

**Comment by manad777** [comment]
Thanks!
