### ISSUE TITLE
about shortcut "insert emoji"

### ISSUE THREAD

**Issue by netios** [giuspen/cherrytree#1712]
I want to set a shortcut key for Insert emoji.
It seems that it cannot be set in the current version of cherrytree 0.99.37 (win10, linux mint 20). 
Can you please add it to the shortcut key settings to enable it? 
![image](https://user-images.githubusercontent.com/10227352/120731318-545cf100-c51e-11eb-862f-6ba29fcff873.png)
![image](https://user-images.githubusercontent.com/10227352/120731754-33e16680-c51f-11eb-8351-adf75c2bf167.png)

**Comment by giuspen** [comment]
This comes from Gtk3, not cherrytree. There is a shortcut but could be that cherrytree is overriding it. I'll verify and get back

**Comment by giuspen** [comment]
The Gtk3 defined shortcut is Ctrl+.
It works generally except in a table cell and in a codebox because that shortcut is overridden and used for something else.
Maybe I should free the Ctrl+. use from tables and codeboxes so that the insert emoji from keyboard shortcut works there too...

**Comment by netios** [comment]
Ctrl + .
Confirmed that it works well in Cherry Tree.
I am satisfied. 
Thank you for letting me know

**Comment by giuspen** [comment]
I found out that not only Ctrl+. triggers the Gtk3 "Insert Emoji", but also Ctrl+;

**Comment by netios** [comment]
Dear giuspen
clipboard history.!!!   CTL + ;
This is a very useful feature.
Thank you!
