### ISSUE TITLE
Crashes while editing false-recognized hyperlinks in pasted text

### ISSUE THREAD

**Issue by AGenuZ** [giuspen/cherrytree#1713]
**v.0.99.37, Windows**

It crashes when I trying to edit pasted text with false-recognized hyperlinks.

**To Reproduce**

1. Download and open attached [**bug.txt**](https://github.com/giuspen/cherrytree/files/6601917/bug.txt)
_I've tried to paste it into Github editor, but it "brokes" the bug effect after saving._

2. Copy it's content into clipboard and paste it in into Cheerytree node:

3. Select all text by presing Ctrl+A;

4. Make it bold by pressing Ctrl+B;

5. Press Ctrl+B again;

6. CherryTree crashes.

**Screenshots**
![](https://user-images.githubusercontent.com/85378254/120877530-874ac780-c5a6-11eb-9909-6c179c1793d4.jpg)

**Comment by giuspen** [comment]
shouldn't happen anymore in upcoming 0.99.38, reopen if you see it again
