### ISSUE TITLE
[0.99.37] Link markdown paste problem on some sites

### ISSUE THREAD

**Issue by ciranus** [giuspen/cherrytree#1714]
**Version, Operating system** : CT 0.99.37 / linux / Firefox 78.10 /   [ [Copy Markdown link ](https://addons.mozilla.org/fr/firefox/addon/copy-markdown-link/)  ] firefox addon

**Describe the bug** : link markdown pasting from Firefox to CT regression since  https://github.com/giuspen/cherrytree/issues/1007

Copy link Markdown from Firefox to CT does not correctly behave anymore (regression) :

Example 1: https://www.giuspen.com/cherrytree/
-> markdown link will open in Firefox from CT, although bad link:
`http://](https://www.giuspen.com/cherrytre`

Example 2: https://github.com/giuspen/cherrytree/issues/1007
-> works apparently fine, even link edit shows a correct link.
**But**, the real link itself is wrong, starts with: `http://b](https`: and obviously will not open in Firefox.
`http://b](https://github.com/giuspen/cherrytree/issues/1`

**Screenshots**
CT:
![ksnip_20210605-115747](https://user-images.githubusercontent.com/61602511/120887870-99078b80-c5f5-11eb-8a3c-7e82fb983bc7.png)

Firefox:
![fx](https://user-images.githubusercontent.com/61602511/120888120-f18b5880-c5f6-11eb-8eb7-d5f1342122c6.png)

Markdown export file: [markdown_test.zip](https://github.com/giuspen/cherrytree/files/6602768/markdown_test.zip)

**Comment by giuspen** [comment]
thanks will be ok in upcoming 0.99.38
