### ISSUE TITLE
No text formatting in table cell?

### ISSUE THREAD

**Issue by Hoffenbar** [giuspen/cherrytree#1717]
After selecting some text in a table cell and then clicking on the 'monospace'-symbol, the following errormessage appears (0.99.37 portable in Windows), stating that there is no text selected:

![image](https://user-images.githubusercontent.com/46227007/121145915-b6c83100-c83f-11eb-8113-1901378a958d.png)

And, for long time now, formatting a monospaced text in bold isn't possible most of the time (but sometimes it is possible). Right now I marked this line and click on bold, bold, but only some characters turned bold:

![image](https://user-images.githubusercontent.com/46227007/121202608-b6e32380-c875-11eb-9989-7d9dbd98186e.png)

It seems that there are some fundamentals, I don't understand.....

**Comment by giuspen** [comment]
The rich text is not yet supported in table cells

**Comment by Hoffenbar** [comment]
Yes, of course, I forgot this. I'm sorry. So, this ticket can be closed....
