### ISSUE TITLE
Cherrytree DB corrupted pswd not working

### ISSUE THREAD

**Issue by hanskrejci** [giuspen/cherrytree#172]
Hi,
I'm facing problem with my cherrytree DB.
1st of al I had a message saying "write to disk fail" while saving the DB. Then I tried to reopen cherrytree and the same DB and since then my password is not working. I have few temp DBs with "~" - tilda sign or more. But none of them works. 
Is there a way how to overcome problem with password?
Thanks,
Jan

**Comment by giuspen** [comment]
Hi, please try to open the protected document directly with 7zip and insert
the password when asked

**Comment by hanskrejci** [comment]
ahh ok it seems it's completely broken as it has 90B size ... :(

**Comment by giuspen** [comment]
I'm sorry to hear that... what version are you running?

**Comment by hanskrejci** [comment]
CherryTree 0.36.4 running on RedHet ELV 6.7.

**Comment by hanskrejci** [comment]
Solution - backup, backup, backup .... ;) 
fortunately I have backup from today's morning, so loses are not high.

**Comment by giuspen** [comment]
Happy to hear that :)
Also keep the app up to date, current is 0.37.3
