### ISSUE TITLE
Slow performance on pc

### ISSUE THREAD

**Issue by Voksel** [giuspen/cherrytree#1722]
I have pc with gtx 1660 and ryzen 5 3600 that should be more then capable to run the program without any issues, however when I open a file it lags. Scrolling, switching between nodes and typing is painfully slow. On my laptop which has worse specs the same file runs smoothly without any issues. I tried reinstalling, saving file in .ctd instead of .ctb format but nothing helped. . both my laptop and my pc run windows 10 with all updates and both of them run Cherry Tree version 0.99.38. I also noticed that when the size of windows is decreased the lag also decreases.

**Comment by Voksel** [comment]
Solved issue by manually deleting preferences folder. Cause of issue still unknown.

**Comment by 88HSGX** [comment]
I had exactly the same problem.
I unchecked "Autosave every 1 minutes" and "Create a backup before saving" in File/Preferences/Miscellaneous/Saving.
It was making 3 backups and an autosave every minute!
This has helped tremendously.
