### ISSUE TITLE
Dependencies problem with 0.99.38.3 and .4

### ISSUE THREAD

**Issue by wisdomlight** [giuspen/cherrytree#1731]
**Version, Operative system**
     Operating System: Debian GNU/Linux 11 (bullseye)
      Kernel: Linux 5.10.0-7-amd64
      Architecture: x86-64

I already use CT 0.99.36

**Describe the bug**
dependencies issue. not a bug. usually I can find the missing packages in the debian web site. not this time though.

**To Reproduce**

**Screenshots**
![Screenshot from 2021-06-18 22-28-48](https://user-images.githubusercontent.com/14957169/122617909-17980a80-d085-11eb-94ab-361fd4740914.png)

**Comment by giuspen** [comment]
![image](https://user-images.githubusercontent.com/6842059/122618134-86756380-d085-11eb-82da-5391eeb2e765.png)
these packages are for specific ubuntu versions. where are you trying to install?

**Comment by wisdomlight** [comment]
I use this [site t](https://is.gd/ydU4SX)o download 
it has  a amd64.deb which I download.

I open the downloaded file with gdebi package installer
that's as much as I know

**Comment by giuspen** [comment]
OK Debian 11 should be compatible with 20.04 focal or 20.10 groovy. Look at https://launchpad.net/~giuspen/+archive/ubuntu/ppa/+packages for Focal or Groovy

**Comment by wisdomlight** [comment]
I managed installing up to 38.2 - I'll try your suggestion now
thanks

**Comment by giuspen** [comment]
Don't worry about the number that comes after the "-", those are all the same version, 0.99.38, just built for for different ubuntu versions but same source code version. The 1.0 will come soon as the C++/Gtkmm3 version is getting more stable. Night ;)

**Comment by giuspen** [comment]
libgspell-1-1 is an older version which is a dependency for the  18.04 package.
cherrytree 0.99.38-4 is the package for the old ubuntu 18.04.
