### ISSUE TITLE
More "tabs" please

### ISSUE THREAD

**Issue by RF-I** [giuspen/cherrytree#1735]
Hi the tabs feature to revisit previously visited nodes illustrated below is very useful and powerful, but why is it limited to only three nodes? By the time I want to return to a place I have been I have already been through ten or more nodes. Can this be increased please? Make it like tabs in a browser? (i.e. unlimited) It also serves as a good history recorder. thank  you , other than this CherryTree is near perfect for my usage. When this and the undo/redo problem is fixed I will find it useful enough to donate.

![image](https://user-images.githubusercontent.com/85957737/123134948-258fb780-d406-11eb-9b81-c8778c15d184.png)

**Comment by userfav** [comment]
Can be increased changing the value in the line "nodes_on_node_name_header=X" in the cherrytree "config.cfg" file

**Comment by Camilot55** [comment]
Please change to the number of tabs you need
![1](https://user-images.githubusercontent.com/76065578/123318504-b5d61580-d548-11eb-8af6-1ce1f6c97089.png)

**Comment by RF-I** [comment]
Thank you so much! I did not recognize tabs as "Last Visited Nodes". Makes my day thank you!
