### ISSUE TITLE
Password not recognised when directories have certain characters

### ISSUE THREAD

**Issue by jPerez042** [giuspen/cherrytree#1736]
Version:
Version 0.99.38 (from PortableApps) on Windows 10 pro

Description:
When an SQLite password protected file is moved to a path containing certain characters used in Spanish such as á, é, í, ó, ú or ñ; the password is not recognised or the file is not opened (I have not tried using characters from other languages).

If the character is removed from the respective directory name then the file opens normally.

Example / Steps to reproduce:
1. A file is created and saved in CherryTree as SQLite password protected with the path "c:\temp\notebook.ctx"
2. Move the file to a location containing any of the characters mentioned above, for instance "c:\temp\bitácora\notebook.ctx"
3. Try to open the file on CherryTree and the program will keep asking for a correct password.

If the special characters are removed (e.g. c:\temp\bitacora\notebook.ctx) then the file will open as normal.

**Comment by giuspen** [comment]
Thanks I can reproduce it

**Comment by giuspen** [comment]
Will be fixed in upcoming 0.99.39

**Comment by cmorgenstern** [comment]
This [commit](https://github.com/giuspen/cherrytree/commit/3d3639f7dbc21bcb1bc5d2405fb5ac818070ca60#diff-bd9002484fdc69c2bf20fb74a088c7d48b3349a9141f72b5cd4ccd95df233db2) appears to have introduced a build error using the latest repository clone:

```
/home/user/.cache/yay/cherrytree-git/src/cherrytree/src/7za/CPP/Windows/System.cpp: In function ‘bool NWindows::NSystem::GetRamSize(UInt64&)’:
/home/user/.cache/yay/cherrytree-git/src/cherrytree/src/7za/CPP/Windows/System.cpp:103:36: error: ‘g_fopen’ was not declared in this scope; did you mean ‘fopen’?
  103 |                         FILE * f = g_fopen( "/proc/meminfo", "r" );
      |                                    ^~~~~~~
      |                                    fopen
make[2]: *** [src/7za/CMakeFiles/7za_static.dir/build.make:2960: src/7za/CMakeFiles/7za_static.dir/CPP/Windows/System.cpp.o] Error 1
```

**Comment by giuspen** [comment]
Thanks @cmorgenstern I'll fix in few hours

**Comment by cmorgenstern** [comment]
@giuspen apologies for the delay in replying, tested and appears to be fixed - builds cleanly. Cheers.
