### ISSUE TITLE
Option to hide 'status bar' from 'view' menu like how VS Code does.

### ISSUE THREAD

**Issue by PranavBhattarai** [giuspen/cherrytree#1742]
I think there are a set of people who don't really need the status bar to tell users while he⁄she creating notes.

I'm one of them. I don't need to know what type of node it is, when it was created and when it was modified.

Screen space is vital through which I do multiple things at the same time, and even a small notch like that **does** make a difference.

Most of the IDE, browsers, even some file managers provide an option to hide the **Status Bar**. Why not we bring this Cherry too?

**Comment by giuspen** [comment]
ok will be in upcoming 0.99.42
