### ISSUE TITLE
File links in exported PDF do not work when path isn't relative

### ISSUE THREAD

**Issue by folcraed** [giuspen/cherrytree#1749]
**Version, Operative system**
OS: Manjaro Linux
DE: GNOME 40.1.0
Cherrytree: 0.99.37, .ctd file format
Evince: 40.1

**Describe the bug**
When creating file links in Cherrytree, for instance `file:///home/rob/Pictures/greatpicture.png`, Cherrytree cannot use the `file://` prefix, giving an error. Removing `file://` from the link will work as expected when clicked on.

Export the file to PDF, open it and click on the link produces an error:
`/home/rob/home/rob/Pictures/greatpicture.png": No such file or directory`

Note the double `/home/rob` in the PDF link path. It appears that without the `file://` prefix, the PDF viewer assumes the path starts from the folder where the PDF is, appending it to the start of the link's path.

If I open the PDF in Vim and batch edit the link paths, adding `file://` back to them, save and open the PDF again in Evince, the links will work as expected. It seems that without the `file://` prefix, the PDF reader assumes the path is relative. Adding the prefix makes the path absolute.

**To Reproduce**
1. Create a Cherrytree .ctd document, enter some text, highlight a word and add a link to a file in another folder not in the current Cherrytree document path.
2. Save and export the file to PDF in another folder, like the /home folder.
3. Open the PDF in default viewer and click on the link.

I'm guessing that because Cherrytree doesn't use the `file://` prefix internally, it also omits it when exporting to PDF. However, the PDF reader (Evince in this case, though tried others with same results) will assume the path is relative without the prefix. This is fine when the paths are relative, but breaks when they're not.

The links *do* work if the link is created with a relative path to the Cherrytree document, and the PDF is located in the same path. However, this is not always the case in my use, and I suspect with many users. I keep my notes in a folder that is on a different path from where I store other files. The exported PDFs are then linked to a research program I use that stores it's files on yet another path. Absolute paths are something of a necessity in my use.

I don't know if this is something that is fixable, but thought it worth reporting. If you need more information, please ask. I'll do what I can to help.

**Comment by giuspen** [comment]
thanks, will be fixed in upcoming 0.99.39
