### ISSUE TITLE
Auto loading encrypted file and starting minimized

### ISSUE THREAD

**Issue by dpeley** [giuspen/cherrytree#1751]
I found a bug in CherryTree regarding CTX encrypted note files. If the preference "Start Minimized in the System Tray" is set, and CherryTree is opened by double-clicking on the encrypted note file, the program will auto-minimize on startup and the dialog box for the decryption password will disappear, making the file inaccessible and the program has to be force-closed.

Further, if the preference "Reload Document from last Session" is also checked, and the encrypted note file is the last one opened, you will be unable to open CherryTree by normal means, because it will immediately try opening the encrypted note file while minimized, and the password dialog box will be gone.

My current workaround is either to uncheck "Start Minimized" or just start CherryTree by double-clicking on an un-encrypted note file. Not very inconvenient, but thought you should know. Thanks again for this awesome program!

My working environment facts:
Windows 10 21H1, build 19043.1083
CherryTree version 0.99.38
Encrypted file type: CTX
Encrypted file size: 19.3MB

**Comment by giuspen** [comment]
Thanks this will be fixed in upcoming 0.99.39
