### ISSUE TITLE
question : Are Cherrytree a good replacement for Passwordgorilla (abandoned)

### ISSUE THREAD

**Issue by Groberen** [giuspen/cherrytree#1753]
Hi.

For several years, I've used Passwordgorilla to store passwords. This software is unfortunately not maintained any more, so I'm looking for another solution.

So I was thinking, why not CherryTree since I'm already familiar using it ?

So the most pressing question : How secure are .ctx and .ctz files in terms of not risking confidential/personal being getting stolen ?

Under Save As dialog box, I notice it mention both .ctx and .ctz files are tamporary saved to a temporary directory in unencrypted form.

**Comment by giuspen** [comment]
Hi, the encryption is simply using https://www.7-zip.org/ (=>Strong AES-256 encryption in 7z and ZIP formats) but under the hood there is still an unprotected .ctd or .ctb file which lives in a temporary folder generated with https://developer.gnome.org/glib/stable/glib-File-Utilities.html#g-dir-make-tmp and removed when closing cherrytree

**Comment by Groberen** [comment]
Ok, thanks for answer.
