### ISSUE TITLE
CherryTree Codebox Dots Replaces Whitespace

### ISSUE THREAD

**Issue by NoPurposeInLife** [giuspen/cherrytree#1759]
Hi All,
I'm using CherryTree for Windows 10, how do i remove the dots that replaces whitespace in CherryTree's Codebox. As shown in the image below, there is 3 spaces between test and test2, how do i remove these dots?

![image](https://user-images.githubusercontent.com/30126475/126070088-f004d9fb-5214-4a2d-a1a8-6fafc2b4fe03.png)

**Comment by giuspen** [comment]
Preferences dialog, tab "Plain Text and Code", untick "Show White Spaces"

**Comment by NoPurposeInLife** [comment]
Thank you!
