### ISSUE TITLE
Printout of tables do not correspond to actual column width

### ISSUE THREAD

**Issue by thgreve** [giuspen/cherrytree#1760]
**Version, Operative system**
Cherrytree's version 99.38 Ubuntu 20.04.2

**Describe the bug**
The table gets printed with all column-width being the same (assumingly: Edit Table Properties -> Column Properties -> Default Width). Modifications to the column width through Ctrl+. / Ctrl+Alt+. are not been taken into account.

**Comment by thgreve** [comment]
Update:
- Updated Cherrytree to 99.39: Error remains as described
- The error is the same when printing to hardware and to file

**Comment by giuspen** [comment]
Yes haven't looked at it yet but will try for the next release

**Comment by thgreve** [comment]
Unfortunately the bug is still there in 99.40 ...

Cheers,
Thomas

**Comment by thgreve** [comment]
Almost fixed in version 99.41 - Many Thanks!  The solution is quite sufficient for me but the width gets not presented WYSIWYG. The column-width in both, exported PDF and printout are  different from CherryTree - furthermore pdf is different from printout. This leads sometimes to undesired forced linebreaks.
