### ISSUE TITLE
Add tag to node to prevent CT to search in that node and subnodes

### ISSUE THREAD

**Issue by Groberen** [giuspen/cherrytree#1761]
**Is your feature request related to a problem? Please describe.**

First, my primary use of this nice program is to write a personal log document. Sometimes, there will be old nodes that the content are not longer relevant, but I still want to archive it if I decide I want to have a look into it.

So when the document have grown for some years now, there are quit many old nodes that has no relevance, but that still pop up when doing a search.

**Describe the solution you'd like**

It's more simple to say it than make it, but for the purpose of describing the GUI:
In a node properties dialog box, there could be a check box labeling "Prevent searching inside this node and sub nodes".

**Comment by giuspen** [comment]
This will be in the next release 0.99.42
