### ISSUE TITLE
Increase font size of name header

### ISSUE THREAD

**Issue by iamfabo** [giuspen/cherrytree#1764]
I'm wondering if it is possible to increase the font size of the name header (see the screenshot attached), since there is no option avaliable to change it.

![Screenshot 2021-07-28 134917](https://user-images.githubusercontent.com/60046736/127317590-c5f6d9ad-3e54-44c6-8768-1191b0a43320.png)

Thanks in advance for any suggestions.

**Comment by giuspen** [comment]
it would make sense to try and match the size of the tree, I'll have a look

**Comment by giuspen** [comment]
In upcoming 0.99.41 the size will follow what you set for the tree
