### ISSUE TITLE
[for volunteer graphic designer] Please create monochromatic toolbar icons

### ISSUE THREAD

**Issue by omega3** [giuspen/cherrytree#1766]
Obviously, it is my subjective opinion but I don't like toolbar icons. 

https://i.imgur.com/tBsgRYG.png

Especially, remove text formatting, Change color of selected text font / foreground,  Change color of selected text background, Memory of the latest Text Format type, when put next to each other look so similar that to me that look almost the same.

Perhaps there is a Cherrytree user who happens to be a graphic designer who could as a volunteer contribute to the project an design some more modern looking monochromatic toolbar svg icons for day and night mode or even colorful icons but which are more distinguishable.

Or can you tell me if there is a source of free open source, creative common, that can be used for toolbar?

Example how it could look like:
https://i.imgur.com/9lt6c5X.png

**Comment by userfav** [comment]
The example icons that you show are from the Breeze iconset?

**Comment by omega3** [comment]
Some of them. These are actually png's from a screenshot of older Cherrytree version. It was easier for me to prepare such look to show example. But LOWriter has nice svg Breeze light and dark themes:
![obraz](https://user-images.githubusercontent.com/1286452/129319153-0edbdbfa-3690-4e3b-922f-3d8d36ac8907.png)

Maybe it is not a big deal but I also prefer **B** and _I_ and U instead of other letters because they indicate their English names.

**Comment by userfav** [comment]
I will check the Breeze theme to see if I can adapt some of them to CT, as a little test.

**Comment by userfav** [comment]
Well, check this out. I take the matching icons from Breeze. Are missing those that are specific to CT. On my monitor doesn't look too good, I assume maybe for the scaling.

Oh, this are for a light theme, I'm on Windows, so was more easy to me that way, but the Breeze icons have a dark version so I guess is not a problem.

[ct_breeze_ligth_INCOMPLETE.zip](https://github.com/giuspen/cherrytree/files/6987221/ct_breeze_ligth_INCOMPLETE.zip)

Screenshots:

![image](https://user-images.githubusercontent.com/46328784/129460762-f2986190-42af-4c19-8cad-6f2e0c7f6792.png)
![image](https://user-images.githubusercontent.com/46328784/129460877-9977d0e7-a89f-4ce4-b90b-378cd5417eff.png)

**Comment by omega3** [comment]
Thank you. Looks good. I will make myself a match for Breeze dark. Actually I have them already installed on my system, so it is easier than I thought.
For Linux users they are in
`/usr/lib64/libreoffice/share/config/`

**Comment by userfav** [comment]
I can now try doing make the missing specifics icons (and the dark version as well) but... are they looking OK in your pc? That was intriguing me. On my machine they look a little smaller and less defined than, Libreoffice, for example. Con you switch a moment to a lighter theme and take an snapshot to see some reference?

**Comment by omega3** [comment]
To me, it looks very good. Maybe it is a screen resolution issue. My is 1280 x 1024. I don't know but it may also have something to do with antyaliasing settings.

https://imgur.com/eVkwrQu

https://imgur.com/HO4W5mz

https://imgur.com/nHxmAAS

https://imgur.com/PWIUDAl

https://imgur.com/HD2Lnjp

**Comment by userfav** [comment]
@omega3 Thanks! I tweak some screen settings and I think that now looks a little better.

Here I attach an update (aprox. 90%). I changed some of the previous for more suited ones and started to make the missing. Maybe I tweak the "finders" and the "new node" icons in the future. Feedback is appreciated.

[ct_breeze_light_INCOMPLETE_v2.zip](https://github.com/giuspen/cherrytree/files/6989291/ct_breeze_light_INCOMPLETE_v2.zip)

 Screenshots:

![image](https://user-images.githubusercontent.com/46328784/129500734-d0bcced3-070f-4e0b-9235-5a33be3b9c30.png)
![image](https://user-images.githubusercontent.com/46328784/129500768-6e990dbf-c8d1-43d9-af08-e3b8042bc4fc.png)

**Comment by MJimitater** [comment]
Great work, thanks, I like it - nice and clean!
I agree that "New node" icons seem good to further tweak in the future, I always liked the little cherry in it :)

**Comment by userfav** [comment]
@MJimitater Check this pack, is complete and re-make the nodes icons trying to put cherries without break (too much) the guidelines.

[CT_Breeze_Light_icons_v1.zip](https://github.com/giuspen/cherrytree/files/6994043/CT_Breeze_Light_icons_v1.zip)

(Next I will make the dark version)

![image](https://user-images.githubusercontent.com/46328784/129600211-a6dba340-49db-4292-b747-921d555080fb.png)

**Comment by omega3** [comment]
It is better than I could ever imagine. Really great work. 
Yes. Finders could indicate more what they actually do, I mean find in selected note content or all nodes. Of course I could get used to how they look now but if you could somehow make theme more intuitive that would be awesome.

Also "Insert horizontal rule" could more resemble the original svg, I mean two parallel signs
```
----
----
```
Although I haven't learned Inkscape I think should not be a problem to create such icon.

But have a look at linestyle.svg LibreOffice_Breeze
I have it from here
https://github.com/Andreas-Kainz/breeze-icon-theme
It think it is a good one even without changes.
https://i.imgur.com/m8EmpN9.png

By the way, is it in line with Breeze license terms to use it in another program? At least not as default package attached to Cherrytree but for personal use?

**Comment by userfav** [comment]
Finally, here is the Dark version (also the Lighter version updated):

[CT_Breeze_Light_v2.zip](https://github.com/giuspen/cherrytree/files/6995677/CT_Breeze_Light_v2.zip)
[CT_Breeze_Dark_icons_v2.zip](https://github.com/giuspen/cherrytree/files/6995681/CT_Breeze_Dark_icons_v2.zip)

 Preview:

![image](https://user-images.githubusercontent.com/46328784/129635886-0094bcdb-14f4-457f-805d-0b7518126ae6.png)

@omega3 This version has the Horizontal Rule fixed:

![image](https://user-images.githubusercontent.com/46328784/129635991-4e5475e2-592b-457d-ba56-8b00bad83e78.png)

Respect to the "H" icons, I will see what I can do in the next days.

About the license, it's a good question. I take the icons from this repository: [https://github.com/KDE/breeze-icons](https://github.com/KDE/breeze-icons) that have [LGPL license](https://github.com/KDE/breeze-icons/blob/master/COPYING.LIB) so I don't think should be a problem for personal use at least.

I extract this comparison between GPL and LGPL from [Stackoverflow](https://stackoverflow.com/questions/1114045/gpl-and-lgpl-open-source-licensing-restrictions#:~:text=LGPL%20allows%20you%20to%20use,source%20software%20with%20your%20application.):

> GPL
>
> Other developers can borrow and modify the code and re-distribute it as part of their own project, only if their entire project is also licensed under the GPL.
> 
> This prevents the code from being used in proprietary software.
> 
> LGPL
> 
> Other developers can borrow and modify the code and re-distribute it as part of their own project, provided that the portion used under the LGPL, including any modifications, is re-licensed under the LGPL. Other portions of the project are permitted have other licenses.
> 
> This allows the code to be used in otherwise proprietary software.
>

**Comment by omega3** [comment]
Thank you for explaining license issue and for dark theme.

Do you know how to make separators invisible?
https://i.imgur.com/1wOA6qq.png

Is separator also svg file or is it somehow coded in Cherrytree?

**Comment by userfav** [comment]
@omega3 I haven't seen the separator listed as a icon in the code repository folder, so maybe it depends of  the system theme selected, I don't know for sure.

**Comment by userfav** [comment]
Update to the "H" icons to show some size difference, and some minor tweaks to other icons. 

[CT_Breeze_Light_icons_v3.zip](https://github.com/giuspen/cherrytree/files/7006678/CT_Breeze_Light_icons_v3.zip)

[CT_Breeze_Dark_icons_v3.zip](https://github.com/giuspen/cherrytree/files/7006677/CT_Breeze_Dark_icons_v3.zip)

**Comment by omega3** [comment]
Thank you for "H" icons. They are much more intuitive now. Are you going to work on tweaking the "finders"?
When I look at [original svg's](https://i.imgur.com/tBsgRYG.png), they look pretty good to me. Maybe only instead of blue magnifying glass could be black and white to match monochromatic themes.

**Comment by userfav** [comment]
Here I attach the packs with a new "finder/replace" style.

[CT_Breeze_Dark_icons_v4.zip](https://github.com/giuspen/cherrytree/files/7009755/CT_Breeze_Dark_icons_v4.zip)
[CT_Breeze_Light_icons_v4.zip](https://github.com/giuspen/cherrytree/files/7009756/CT_Breeze_Light_icons_v4.zip)

As you say, I finally go on a similar route than the original ones, with a big magnifier. I tried to be close to the Breeze theme (and use the magnifier that they designed)  but the CT finders convey too much information to be put on a small icon. So I use the size of the "Replace" button to make a big magnifier. Preview:

![image](https://user-images.githubusercontent.com/46328784/129961783-3efe2675-071e-4dea-a924-b0da15376782.png)

**Comment by omega3** [comment]
This looks great. To me it looks like a completed work. I am sure many Cherrytree users will use it. 

Thank you very much for your contribution to Cherrytree. 

I don't know if this issue can be closed now or should I leave it open and let giuspen decide. I will leave it open. Maybe someone else will want to write here.

**Comment by MJimitater** [comment]
@userfav yeah, thanks for your work, looks awesome to me

**Comment by mimecry** [comment]
@userfav how do you replace the icons in Windows if i may ask? i found out that themes are stored in C:\Program Files\CherryTree\mingw64\share\icons but not sure how to proceed, couldn't find any options in CT prefs

**Comment by userfav** [comment]
@mimecry Sure, you need to create an "icons" folder where the config files of Cherrytree are stored and drop there the icons that you want to replace (without sub-directories). 

The simplest way to locate that folder is using the option: "**File** > **Preferences** > **Open Preferences Directory**"

In my case is here:

![image](https://user-images.githubusercontent.com/46328784/130106274-f80e5b68-ca7b-4341-83bb-3fac76ec557b.png)

**Comment by mimecry** [comment]
@userfav got it working, thank you very much!

**Comment by giuspen** [comment]
the next version will have these two additional icon themes available in the preferences dialog
