### ISSUE TITLE
Ability to add "tags" to nodes. 

### ISSUE THREAD

**Issue by Tombert** [giuspen/cherrytree#1767]
**Is your feature request related to a problem? Please describe.**

CherryTree is awesome, but one thing that has been a bit of an issue (and maybe I'm just not looking in the right place) has been searchability, specifically in anything that isn't directly in the text.  I think being able to add tags to nodes so that things are more easily searchable would make this a bit easier. 

**Describe the solution you'd like**

I would like to be able to have an option to add "tags" to nodes/subnodes, and have ctrl-shift-f search for those tags in addition to the stuff in the plain text. 

Here's an example that actually came up for me: 

I'm writing some notes for some statistics homework, the book uses the term "boxplot" for what I've always called a "box and whisker plot".  I matched the wording from the book, which is fine, but then when I was looking for my notes on the subject months later, I kept searching for the string "box and whisker plot", and couldn't immediately find what I was looking for.  

If there were a tagging ability, I could have attached the tag "box and whisker" to the node, so that searches would turn up that node when I was looking for it.

**Comment by Tombert** [comment]
Just for reference, what I've started doing now is adding a section to the bottom of each node called "tags", where I just type out all the tags manually so that they' show up in my searches, but that's a little clunky.

**Comment by giuspen** [comment]
You can do it but currently only for node name, so searching for a node and not a node content (Search--Find--Find in Nodes Names and Tags)

**Comment by giuspen** [comment]
This will be in the next version as the search in multiple nodes has been unified and it will find the tags you add to the node via node properties
