### ISSUE TITLE
Corrupted file, No backups even though "Create a Backup Copy Before Saving" was enabled!

### ISSUE THREAD

**Issue by TimBullas** [giuspen/cherrytree#1769]
**Version, Operative system**
State the Version and the Operative System/Desktop. Try the latest available version before reporting an issue.
CherryTree 0.99.38, Windows 10 Home 2004
**Describe the bug**

I've just had my .ctb file corrupted for the second time after an error about not being able to save due to sync issues. 
The first time about a month or so ago, I was able to use one of the 3 backup files and move it to a new folder and didn't lose much work.
The folder it was in was in was synced to one drive, so I thought that must've been causing the issue. 

This time it happened again while working in the folder on my desktop that I had moved it to after the first corruption. 
Even though "Create a Backup Copy Before Saving" was enabled in preferences, there were no backups in the folder that the .ctb file was in. 

I've just lost at least one month's worth of notes for my course, this has completely screwed me!!!!!
Is there any other place that the backups might be saved to??
Please Help Me!!! 

**To Reproduce**
If applicable, attach a non-personal document where the issue can be reproduced systematically.

**Screenshots**

**Comment by TimBullas** [comment]
Did some research on Sqlite database corruption. 
Looks like it was a disk space issue that caused the corruption. 

Data is gone, not much I can do about that. 😞

After a little playing around with CherryTree, I found the "save and vacuum" option fixed the issue of not creating backups when saving.

**Comment by mimecry** [comment]
unfortunate, hope someone will lend you their notes

**Comment by giuspen** [comment]
@TimBullas I'm sorry to hear that, are you saying that the lack of available disk space seemed to have caused the corruption?
You mentioned you have some synchronisation software running, is that right? Often such cloud synchronisations store older copies of the data. I would think that it is the synchronisation software maybe acting while cherrytree is also writing that is the most probable cause, I find it crazy that the sqlite failing to expand causes such corruption.
Is it a plain CTB or a password protected database (CTB into a CTX)
