### ISSUE TITLE
Incorrect link insertion from clipboard

### ISSUE THREAD

**Issue by MrSplinterRat** [giuspen/cherrytree#1781]
Hello!

Cherrytree v.0.99.40

Links with '|' character like

https://www.google.com/search?q=bpmn&tbs=lr:lang_1ru|lang_1uk&lr=lang_ru|lang_uk

are inserted from the clipboard incorrectly, 
only the substring 'https://www.google.com/search?q=bpmn&tbs=lr:lang_1ru'
becomes part of the hyperlink, and everything starting with the '|' - 
is no longer defined as part of a hyperlink.

Symbol '|' _may appear in a URL, as shown in the example above.

The reason is in the following code:
ct_const.h: 206:
const inline static char URL_INVALID_CHARS[]{" \n\r\t\"<>\\^`{|}"};

The only place where this constant is used in the source code is
ct_imports.cc:154, it is used there for 'Parse plain text for possible web links'

I consider it expedient to remove the '|' character from the value of the constant URL_INVALID_CHARS,
and write the line ct_const.h: 206 like this:
const inline static char URL_INVALID_CHARS[]{" \n\r\t\"<>\\^`{}"};

**Comment by giuspen** [comment]
thanks for the detailed analysis of the problem and providing the solution too
