### ISSUE TITLE
Sorting a table with more than one column doesn't work properly

### ISSUE THREAD

**Issue by Futhark1988** [giuspen/cherrytree#1784]
**Version, Operative system**
Win10
CherryTree 0.99.40

**Describe the bug**
Sorting a table with more than one column doesn't work properly.

**To Reproduce**
If applicable, attach a non-personal document where the issue can be reproduced systematically.
1. Create a table with more than one column.
2. Add some rows with something similar in the first column e.g. 3 rows with "test1" and 3 with "test2"
3. Write something in the second column for each row.
4. Right click on the second row and select Sort rows Ascending.

**Expected behaviour**
All rows are sorted based on the first and second column.

**Current behaviour**
The rows are not sorted properly.

**Comment by giuspen** [comment]
ok improved the sorting for next version
