### ISSUE TITLE
[F11] Fullscreen expands the width of tree explorer rather than the editing frame

### ISSUE THREAD

**Issue by NouGithub** [giuspen/cherrytree#1785]
Ubuntu 18.04.5 + Cherrytree 0.99.40

Going into Fullscreen mode [F11] expands the tree-explorer's size in order to fill the screen, while the editing frame retains its pre-fullscreen width (i.e., number of columns).

Is this a bug or the intended functionality?  If the latter, is there an option that I may be missing that allows for the tree-explorer to retain its width while expanding the width of the editing frame when entering into fullscreen mode?

Thank you

**Comment by funnelfiasco** [comment]
For what it's worth, I get the expected behavior with 0.99.40 on Fedora Linux 34 (KDE/Wayland). The tree view remains fixed and the editor expands to fit the screen.

**Comment by giuspen** [comment]
@NouGithub is your tree on the left as default or configured to be on the right?

**Comment by NouGithub** [comment]
@funnelfiasco that's worth something! Thank you for the add.

@giuspen  It is on the right. :)

**Comment by NouGithub** [comment]
You're welcome!  And thank you.  Helping you in squashing bugs, feels great.
