### ISSUE TITLE
Provide a MacOS app bundle

### ISSUE THREAD

**Issue by gagarine** [giuspen/cherrytree#1789]
Today cherrytree can only be installed by command line package manager such as brew or MacPort.

This is not the traditional way to install app on MacOS. Most people don't know how to use a CLI. It's also very fragile and may crash on update.

**Describe the solution you'd like**
Provide `app bundle ` inside a .dmg archive. So user can install the app like most app on MacOS: download the archive and install the app by copying it in the /Applications folder.

This may help:
https://stackoverflow.com/questions/1596945/building-osx-app-bundle
https://github.com/auriamg/macdylibbundler/

**Comment by giuspen** [comment]
I tried in the past and gave up, I'll try again

**Comment by phillips321** [comment]
would love to see a native app package

**Comment by dehesselle** [comment]
@giuspen I can build a native macOS app for Cherrytree if you're interested, building and packaging GTK apps for macOS is my specialty. You can take my work for Zim (https://gitlab.com/dehesselle/zim_macos) as a reference of how that will look like.

**Comment by phillips321** [comment]
> @giuspen I can build a native macOS app for Cherrytree if you're interested, building and packaging GTK apps for macOS is my specialty. You can take my work for Zim (https://gitlab.com/dehesselle/zim_macos) as a reference of how that will look like.

I’m sure many people will be pleased if you are capable?

**Comment by giuspen** [comment]
@dehesselle that would surely be appreciated. I had a quick look to your build system for zim and I noticed that you are rebuilding everything including the libraries. Is there a reason to not try and bundle the built libraries/binaries from homebrew which is what I wanted to try in the first place?

**Comment by dehesselle** [comment]
I don't want to discourage you from trying to use Homebrew, it's just not what I'm offering to do. I'm looking to use my build stack to bring more GTK based apps to macOS. That way a project gets an app and I can further mature my build stack.

I also have technical reasons, but they might not carry as much weight for you as they do for me:

- When I started building GTK for macOS, I decided against Homebrew/MacPorts/... and to go as native as possible, i.e. build GTK how GNOME/GTK people themselves are doing it, so I won't have any problems in case I need support ("This is a GTK problem, talk to them!" - "This is a Homebrew-based build, talk to them!").
- Both Homebrew and MacPorts follow the rolling release model and do not support selecting and sticking to specific versions of software. That's a big "no-no" if you want to create reliable and reproducible builds or just need to be picky to circumvent bugs and/or regressions.
- Supporting older macOS versions can range from "cumbersome" to "impossible" depending on age.

**Comment by giuspen** [comment]
@dehesselle I'm happy with your approach and to eventually link your result and/or use your scripts (which one you prefer) for the benefit of the users

**Comment by dehesselle** [comment]
The first release is ready for testing.
- project page: https://gitlab.com/dehesselle/cherrytree_macos
- downloads: https://gitlab.com/dehesselle/cherrytree_macos/-/releases
- I have not tested the arm version.
- macOS Ventura is to be considered **not supported** at this time; it runs but many UI items don't react to mouse events ([upstream issue](https://gitlab.gnome.org/GNOME/gtk/-/issues/5305))

Questions:
- Is the `t` in Cherrytree supposed to be upper or lower case?
- The menu bar is not integrated with the macOS menu bar (and that's not specific to my packaging), correct?

**Comment by giuspen** [comment]
Many thanks for your work @dehesselle I'm going to link your releases page from https://www.giuspen.net/cherrytree/#downl
It is not really important but personally I prefer either all lowercase (cherrytree) or camelcase (CherryTree)

**Comment by dehesselle** [comment]
Thanks for the info, I'm going to change a few places to camelcase (it's also camelcase in the title bar).

You can ping me when you release a new version/bugfix/... and I'll create the app for it.

**Comment by giuspen** [comment]
Ho @dehesselle I issued a new version 0.99.52 would be useful if you try and upgrade your installer when you have time, thanks!

**Comment by dehesselle** [comment]
@giuspen I'll have it ready in a few hours.

**Comment by dehesselle** [comment]
@giuspen Done.

**Comment by giuspen** [comment]
Thank you very much @dehesselle

**Comment by dehesselle** [comment]
Shall we close this issue?

**Comment by mmajchrowicz-afine** [comment]
Could we ask for 1.0.0 app bundle ? :)

**Comment by dehesselle** [comment]
@mmajchrowicz-afine Done.

**Comment by sectroyer** [comment]
@dehesselle Thanks works awesome. Also a lot of (Mac OS X 10.13 specific) bugs fixed 😄 Good job 👍

**Comment by phillips321** [comment]
> @mmajchrowicz-afine Done.

Is this via brew or a standalone app? If so where is the app?

**Comment by mmajchrowicz-afine** [comment]
@phillips321 It's available here:
[https://gitlab.com/dehesselle/cherrytree_macos/-/releases](https://gitlab.com/dehesselle/cherrytree_macos/-/releases)

@dehesselle works great.

**Comment by phillips321** [comment]
> @phillips321 It's available here: https://gitlab.com/dehesselle/cherrytree_macos/-/releases
> 
> @dehesselle works great.

Can we link this on the main repo Readme?

**Comment by giuspen** [comment]
Ok @phillips321 I will mention also in https://github.com/giuspen/cherrytree/blob/master/README.md ( currently only in https://www.giuspen.net/cherrytree/#downl )

**Comment by sectroyer** [comment]
Maybe another version bump ? :)

**Comment by phillips321** [comment]
Hi @dehesselle , would you be able to create a latest update to this please?

**Comment by dehesselle** [comment]
There's quite some updating to do, I'll try to make it a Christmas present.

**Comment by phillips321** [comment]
> There's quite some updating to do, I'll try to make it a Christmas present.

Is there anything I can do to help? If you can document the steps for me to reproduce?

**Comment by dehesselle** [comment]
Areas I could use help with:
- port a C-based patch for an older version of enchant to the newer Vala-based enchant
- upstream macOS-specific changes to make CherryTree work as an app
- contribute to gtk-mac-bundler for a more Apple-native app bundle structure (e.g. libraries belong in Contents/Framworks, not Contents/Resources/lib)
- contribute to JHBuild so it can work with a distutils-free Python

If you want to dig into the building/packaging part instead, I need to do a bit of housecleaning first. Keep in mind that this part is not suitable for quick/occasional contributions, it requires you to spend serious time on it.

**Comment by dehesselle** [comment]
I've done the necessary work to get CherryTree 1.2.0 out the door. There's still things left to do, so there'll be another update soon-ish.

Next time please open a new issue to ping me for an update.
