### ISSUE TITLE
Segfault/crash from exporting imported markdown file with a table

### ISSUE THREAD

**Issue by gvido-berzins** [giuspen/cherrytree#1790]
**Version, Operative system**
This may not be OS specific.
Tested on:
- Windows 10
- Arch Linux

**Describe the bug**
If the user has imported a markdown file which contains a table and exports such node, a segmentation fault occurs and crashes the program.

This is pretty annoying, when I imported all my markdown notes, I couldn't find the issue, after some debugging, found the cause at least.

**To Reproduce**
1. Open Cherrytree
2. Import a markdown file containing a table
```markdown
| Col 1 | Col 2 | Col 3 |
|-------|-------|-------|
| r2    | r2    | r2    |
| r3    | r3    | r3    |
| r4    | r4    | r4    |

This needs to be here, otherwise the table is not imported.
```
3. Select node
4. Export to PDF

**GDB output**
https://pastebin.com/XFgQ8Fu8

**Video**
https://user-images.githubusercontent.com/90025177/132994132-79f2e00c-b628-4391-b662-f051629a09a2.mp4

**Comment by giuspen** [comment]
Thanks I'll have a look

**Comment by giuspen** [comment]
will be ok in upcoming 0.99.41

**Comment by gvido-berzins** [comment]
Great! Glad to see the software being improved.
