### ISSUE TITLE
Can't open one particular node

### ISSUE THREAD

**Issue by rmwiseman** [giuspen/cherrytree#1793]
I don't know whether something has been corrupted, or whether something has changed that is not backward compatible, but there's a particular node in CherryTree that, whenever I try to open it, or whenever the search hits it, CherryTree crashes!

I use flatpak to run CherryTree on Ubuntu (Mint, actually) and I see some output when I run it from the command line.

When I just navigate to the node, all it shows is a debug message with the node name ("Cameras"), and then crashes silently.

During a search, an error is shown a couple of times:

    [2021-09-13 08:10:22.703] [   ] [debug] Node name: 03 Wed
    Entity: line 17: parser error : PCDATA invalid Char value 1
    t;,&quot;conf&quot;:84.626534,&quot;log&quot;:&quot;Main Gate exit (Hub)&quot;}q
                                                                                   ^
    [2021-09-13 08:10:23.999] [   ] [error] safe_parse_memory [1] Document not well-formed.
    Line 17, column 159 (fatal):
    PCDATA invalid Char value 1
    
    Entity: line 17: parser error : PCDATA invalid Char value 1
    t;,&quot;conf&quot;:84.626534,&quot;log&quot;:&quot;Main Gate exit (Hub)&quot;}q
                                                                                   ^
    [2021-09-13 08:10:23.999] [   ] [error] safe_parse_memory [2] Document not well-formed.
    Line 17, column 159 (fatal):
    PCDATA invalid Char value 1
    
    [2021-09-13 08:10:25.471] [   ] [debug] Node name: Cameras

Is there a way I can clean/fix this node without deleting it?

**UPDATE:** I don't think those errors are relevant to the problem now.  I've been browsing the sqlite file and they're not even in the problematic node.  I also don't think it's anything to do with text in the node: I made a copy of the .ctb file, used sqlite3 to remove the text from the node, then in CherryTree, browsed to the node again and it still crashed.

**Comment by giuspen** [comment]
@rmwiseman if you can share the document privately with me I can sort this out, if this is not possible I can at least understand a bit more if you can build cherrytree from the source code as described on https://github.com/giuspen/cherrytree#building-cherrytree-on-ubuntu and reproduce the crash when running from the built sources.

**Comment by rmwiseman** [comment]
Thanks for the response.  I'm afraid I can't share the document, but I've built from source code and bizarrely, it doesn't crash!  The version number agrees with what I've already got installed, too.  I don't understand why it's crashing with the pre-built version.  One thing I see that is different is that the appearance (colours, specifically) is different even though it knew which document to open, so it must have remembered some things from my normal installation.  Any thoughts as to why the pre-built version 0.99.41 crashes when the one I've built from source doesn't?

**Comment by rmwiseman** [comment]
> Any thoughts as to why the pre-built version 0.99.41 crashes when the one I've built from source doesn't?

Is there any other information I can provide that might help get to the bottom of this?

**Comment by giuspen** [comment]
Absolutely, I advise you to use the native package for the best experience, so go via the PPA https://launchpad.net/~giuspen/+archive/ubuntu/ppa
The flatpak has different versions of the libraries, typically more recent and so less tested.

**Comment by rmwiseman** [comment]
Thanks, I'm now using the native package and all is lovely again.
