### ISSUE TITLE
Slow F8 - Request to change behaviour to go direct to current day page instead of rendering through the year and month first.

### ISSUE THREAD

**Issue by dbwiz** [giuspen/cherrytree#1796]
I'm using the most recent CT with a CTB.  My CTB is about 400MB with > 1200 nodes.
I've noticed when I hit F8 it takes ~2 seconds to get to the daily page.  However, if from there I ALT+LEFT then ALT+RIGHT to get back to the daily page its instant.
With current CT, it seems that F8 causes it to render the year page first, then rendering the month page and then the day page.  I see them flash by.
The way I use CT, I put yearly goals and various text on the year page, then the month page I put a few screenfuls of links of things I have organized to work on (wordcount 4.6k, mostly links).  
So it's taking time to render the big year page, then render the huge month page, then render my small day page (about 3/4 of a screen max as that's how I focus on things just for today)
The delay is a little annoying.  I hit F8 about 50 times a day.
If it bugs me I can always workaround it and change the month and year pages to just link to another page, leaving them almost blank.  I'd rather not though, as what I do now makes sense to me logically.

I'd like to propose a change so that that hitting F8 goes directly to the current day node.

The change will have the side-benefit that I rarely look at the yearly page, and not rendering it will save memory.  Hitting F8 after opening the notebook on the current days page uses 70MB on those two pages.
Thank you for your consideration and all your efforts.  However you close this ticket is fine by me.  It's a fantastic program and I don't know what I'd do without it!

**Comment by giuspen** [comment]
OK you will find it in next release 0.99.42
