### ISSUE TITLE
0.99.41 Windows settings issue

### ISSUE THREAD

**Issue by keesse** [giuspen/cherrytree#1800]
After upgrading from 0.99.40 to 0.99.41 on Windows, I found that for fixed width fonts, the foreground was the same color as the background I had set in my notes (light grey), after setting this back to black, everythings was fine again.

**Comment by keesse** [comment]
BTW, this was the same in Linux when updating to 0.99.41, but quickly solved.

**Comment by giuspen** [comment]
I understand, but for a user who has the default values of foreground and background the text will be visible, and it is fully configurable then.
It's an issue only for the users that in an earlier version changed the background to a color that is very close to the current default foreground.
Maybe I should have forced the background to the default in 0.99.41 but then other users would have been upset.
I could have set the foreground default to not override the font colour but then most users would not even know that you can set it.
