### ISSUE TITLE
Color of monospace items changed silently, entries no longer readable

### ISSUE THREAD

**Issue by Hoffenbar** [giuspen/cherrytree#1801]
**Version, Operative system**
Windows 10, 0.99.41

**Describe the bug**
Color of monospace items changed silently, entries no longer readable, since they are light grey on white now - not very funny....

**To Reproduce**

**Screenshots**
A screenshot is useless, since you cannot see what is missing there...

**Comment by Hoffenbar** [comment]
Meanwhile I unchecked a (new?) checkbox where the monospace color is configured to lightgrey.

**Comment by Hoffenbar** [comment]
And now I see that this i a duplicate of #1800 - sorry.

**Comment by giuspen** [comment]
I understand, but for a user who has the default values of foreground and background the text will be visible, and it is fully configurable then.
It's an issue only for the users that in an earlier version changed the background to a color that is very close to the current default foreground.
Maybe I should have forced the background to the default in 0.99.41 but then other users would have been upset.
I could have set the foreground default to not override the font colour but then most users would not even know that you can set it.
