### ISSUE TITLE
Export Code Blocks only.

### ISSUE THREAD

**Issue by SultanOfSolder** [giuspen/cherrytree#1806]
I'm starting to develop embedded projects using circuitpython. Being that it's an embedded environment, code size is limited. One of the ways to limit code size is to eliminate comments and doc strings, which is not a best practice, especially when you look at the code a year later.

What I'd like to do, ala Jupyter Notebooks, is to write documentation in Rich Text and interspersed the actual code in the Rich Text with code blocks. When the time comes, I export all the code block in a node or tree into a single file for the end device. (Even though compiling eliminates comments, documenting arduino code in this fashion, with links and embedded content, would also be spectacular.)

I've looked through the XML and SQLite file formats from a test document, so I know the code blocks are well defined. I can write a python script that exports only code blocks to a text file, but having a button within Cherrytree to do this would be amazing. Especially in circuitpython, where the end device starts running new code as soon as the file is updated.

**Comment by datavectors** [comment]
I have played with polyglot Jupyter Notebooks recently so I think I understand your goal.

In lieu of a custom button could you, as a work around, perhaps place a tiny extra codeblock above each codeblock.  This would act as a "button" to export the other codeblocks. It could contain the python script to export child codeblock. 

Or perhaps just embed above codeblock a hyperlink which calls an external script to export codeblock.

**Comment by SultanOfSolder** [comment]
Hadn't though of that. Thanks for the idea.
