### ISSUE TITLE
Monospace font won't accept #FF0000 as foreground colour

### ISSUE THREAD

**Issue by v3rt3x-4rr4y** [giuspen/cherrytree#1807]
**Version, Operative system**
Windows 10 Pro, Version 21H1, Build 19043.1237
CherryTree 0.99.41

**Describe the bug**
If monospace text is set to "red" (ie #FF0000) as a foreground colour, the text displays as light grey.
Setting to a slightly different value e.g. #FF0001 causes text to display as red.

**To Reproduce**
1. Enter some text, then select it.
2. Enter CTRL+M to change text to monospace.
3. Enter CTRL+SHIFT+F to open foreground colour dialog.
4. Click" "Red" button, alternatively select "Custom" -> "+" button, then use colour picker to select #FF0000 and click "OK".
5. Text displays light grey.
6. CTRL+SHIFT+F to open foreground colour dialog.
7. Select "Custom" -> "+" button, then use colour picker to select #FF0001 and click "OK".
8. Text displays red.

**Screenshots**
![Screenshot-001](https://user-images.githubusercontent.com/6816793/134334628-43c04b1d-6489-4d65-b959-f9d08c3cc76e.png)

**Comment by giuspen** [comment]
if you want to manually set the foreground colour to the monospace you have to go to the preferences dialog and un-tick the automatic selection of a foreground colour. Similarly for the monospace background colour.

**Comment by v3rt3x-4rr4y** [comment]
Understood, apologies for my misunderstanding - thanks for looking into this.
