### ISSUE TITLE
Question: is it possible to configure color of focused node's name in treeview?

### ISSUE THREAD

**Issue by zhenya-kozhevnikov** [giuspen/cherrytree#1809]
I've tried to set up same color behavior for tree view as Cherrytree has for node's content view (right pane) - text keeps it's color regardless of being focused or not (see screenshot).

But, as I understood, in treeview focused node's text color equals treeview background color. 
If so, is it possible to override focused node's name color by some configuration? Because, for Solarized Dark scheme (for instance) it makes text barely visible.

![cherrytree_qG7bKSPSzX](https://user-images.githubusercontent.com/15067660/134889765-f3692217-ad1d-4c01-833d-291897b803ef.png)

**Comment by giuspen** [comment]
will be in upcoming 0.99.42
