### ISSUE TITLE
Linux config.cfg move to cherrytree dir location no longer works in new versions?

### ISSUE THREAD

**Issue by jdsys271** [giuspen/cherrytree#1811]
**Version, Operative system**
Ubuntu 20.04, building from cherrytree v0.99.41

**Describe the bug**
config.cfg does not get detected under cherrytree dir, neither under ./cherrytree/build dir.  It automatically creates it under $HOME/.config/cherrytree.
Older cherrytree v0.39.4 was able to detect config.cfg in the cherrytree dir for "portability" purposes such as when run from a flash drive.

Is there a specific dir that this works in in the latest versions of cherrytree or has this been left out in the new versions?

**Comment by giuspen** [comment]
it has been left out after migrating from python, I haven't thought at the built binary on linux as portable, but still I can easily support it. Where would you like the config.cfg to be checked for portable mode?

**Comment by jdsys271** [comment]
oh i see.
It would be preferred in the same dir that cherrytree is running from, does the Build dir make sense?
But i also see a lot more files such as /styles, etc, than just config.cfg included in $HOME/.config/cherrytree/.
Maybe a 'config' dir under ./build/, would that make sense?

**Comment by giuspen** [comment]
Ok will be in upcoming 0.99.42
