### ISSUE TITLE
A trend of an option which merge the "Title bar" with "Menu bar". And why its really cool concept to have in Cherry?

### ISSUE THREAD

**Issue by PranavBhattarai** [giuspen/cherrytree#1815]
This is a VS Code with **native** title bar.
![image](https://user-images.githubusercontent.com/32763112/135955668-b6083b45-1770-45a8-8914-547c81b7196d.png)

This is a VS Code after enabling **custom** title bar.
![image](https://user-images.githubusercontent.com/32763112/135955901-66384bd0-3b2c-4d94-8643-b107d234598c.png)

This is a Firefox with title bar.
![image](https://user-images.githubusercontent.com/32763112/135956081-5212a891-28fb-4810-9097-eff9ac6358d3.png)

This is a Firefox disabling title bar.
![image](https://user-images.githubusercontent.com/32763112/135956154-ce921ab4-baa5-4d00-9024-a2c23a72b6af.png)

This is a very common Window design concept these days. We see an option to remove the title bar in Chrome, Chromium, IntelliJ, etc, and [will soon come in Gimp too](https://gitlab.gnome.org/GNOME/gimp/-/issues/7172#note_1254206). Title bar is _kindof_ useless area consuming a big area. Some people find it useful and some don't. Some even to the lengths by installing 3rd-party extensions/scripts to achieve this. I mean the whole idea of having a dedicated title bar area just to close, minimize and maximize doesn't seem sensible to me. And I don't need to be reminded that I'm using Firefox or VScode which is labeled in the Title bar as an ad _(standard protocol)_. The first thing I do after installing Firefox on anyone's computer is to disable that title bar. I find it annoying.

![image](https://user-images.githubusercontent.com/32763112/135956832-a8bb6c66-645a-448c-8516-86225f73be78.png)
In the case of the Cherry tree, it's very important to have **menu bar** which includes File, Edit, etc options. So we can't use a similar approach that Firefox uses but we surely can use the similar approach which VSCode used. VScode _ninja_ technique fits the criteria. Because it will include both menu bar and cherry tree name and the name of the file which user is writing, integrated inside same menu bar space. 

Let me know what you think. I think it would be great to have such an option that triggers this behavior. It will definetely mordernized CherryTree look and feel.

**Comment by thwerks** [comment]
I think it might more useful to hide the file menu (like in VSCode) where you can reveal it again by pressing the Alt key. This is very common but having the file menu inside the title bar might now be the best choice, thats far less common and not always sensible.

**Comment by PranavBhattarai** [comment]
> where you can reveal it again by pressing the Alt key,

 I too have similar thoughts about this a long time ago when I noticed how Firefox Alt functions. But in the case of Firefox, menus are barely used. But not in the case of Cheery because one needs a menu bar more often. Regardless of that, I do think the option to, "Show menu bar when Alt is pressed" is not a bad idea.
 
 >  it can make relocating the window more difficult

 I do agree with this. Currently, this feature is a little buggy which makes it, even more, harder to resize the window which I have mentioned above about Super + arrows keys not resizing the window. Plus it's the big size of menu options which we don't see it normally.
 
 For what it's worth, it does be tricky to _use to_ this behavior which is why it's not ENABLED by default. It does need some refinement so that everyone can enjoy this option.
 
 We might need to create a new issue asking for this feature/option:
 
 "Hide Menu bar if Alt is not pressed".
 
 _I love this idea. Nothing new/unique. Have seen this implemented in various software. Thanks for your insight @thwerks_

**Comment by thwerks** [comment]
Thank you sir for the comments and feedback. I personally rarely use the File menu in Cherrytree so I prefer if it could be hidden. though i think most programs that have this feature use Alt as a toggle, rather than momentary operation. 

As for File menu in Title Bar, i think its a nice feature for some users, particularly people who are using Cherrytree in full screen operation but for less than fullscreen its a bit of a hassle to relocate the window. In the current test of this feature, please consider adding some padding on the left side between  Cherry icon and "File" because its difficult to relocate the window from left side or when the window isnt full screen.

One more thing, I saw some programs that had feature like this (file in title bar) and they had an option to only engage the feature when window was maximized, that might be a nice option to have for that feature.

**Comment by giuspen** [comment]
will be in upcoming 0.99.43
