### ISSUE TITLE
More use of Anchors

### ISSUE THREAD

**Issue by moashxer** [giuspen/cherrytree#1816]
**Is your feature request related to a problem? Please describe.**
I use anchors in many Nodes and sub-nodes and I can't find the respective ones due to; 
1. Cannot search for Anchors eg: I've used anchors in many nodes and subdnodes eg:#DNA anchor is called more than 10 times in nodes/subs like Eyes/legs/blood so on. And I don't have the ability look all of em at in one single place other than finding it manually.

**Describe the solution you'd like**
1. Ability search for #tags or #anchors
2. A created anchor should be able to call in multiple nodes/subnodes

**Comment by moashxer** [comment]
Already the request has been made by other users regarding this case. The issue is when you've an whole lot of notes it's hard to manage and maintain

Request's of other users
https://github.com/giuspen/cherrytree/issues/1059
https://github.com/giuspen/cherrytree/issues/1407

**Comment by datavectors** [comment]
Suggested workaround:
Not only in a large CherryTree document with many nodes, but also across a large number of documents scattered around I use ripgrep to search (regex style) for tags or anchors. Then I can parse the ripgrep output to go to the target in a document. It is a simple command line call to ripgrep.

**Comment by datavectors** [comment]
You can write the script in a CT codebox then execute that codebox .. if you wish.

However I use external scripts.

**Comment by giuspen** [comment]
in the next version the search dialog has been unified and bugs fixed, if you search for a node name, node content, node tag, anchor name, it will pop out in the same search
