### ISSUE TITLE
Hyperlinks rendering change when moving cursor key

### ISSUE THREAD

**Issue by scheckr** [giuspen/cherrytree#183]
Hello Giuspen,

Since version 0.37.5, a bug has been introduced in the rendering of hyperlinks I think.
A picture is worth a thousand words, so I attached a screencast of the behavior.
I think hyperlinks should NOT be displayed underlined(but in a specific color of course) unless it's hovered by the mouse pointer(similar behavior as in a browser). Furthermore, it shouldn't be affected by the place of the blinking cursor key. 

Have a nice day.

I wish CherryTree existed on the Android platform but that's another story.

![cherrytree_hyperlink_bug](https://cloud.githubusercontent.com/assets/22662105/19155932/7c9ed1aa-8be0-11e6-8e99-a1193797353e.gif)

**Comment by giuspen** [comment]
Hi there. Strange, I cannot reproduce the problem on windows 7 or linux
mint cinnamon. Note that there's a preference setting to not underline links

**Comment by scheckr** [comment]
Thanks Giuspen for reminding me about the underline links option, I forgot about it.
I narrowed down the bug. In fact the bug happens only when using the Ubuntu Regular Font for text.
This way, all underlined texts are affected. This bug does not happen with Noto Sans Font for example.
First screencast using Ubuntu Regular Fonts and the underline links option checked.
Second screencast using Noto Sans Regular Fonts and the underline links option checked.

I hope this helps. Have a good day

![cherrytree_ubuntu_regular_fonts](https://cloud.githubusercontent.com/assets/22662105/19172612/0cc987e2-8c23-11e6-8f14-cf42b621f3a7.gif)
![cherrytree_noto_sans_fonts](https://cloud.githubusercontent.com/assets/22662105/19172619/14b9f4c8-8c23-11e6-8a79-d0371c7d5e0d.gif)

**Comment by scheckr** [comment]
I am using Xubuntu 16.04 by the way
