### ISSUE TITLE
0.99.42 wrong language, switching language impossible

### ISSUE THREAD

**Issue by Hoffenbar** [giuspen/cherrytree#1832]
**Version, Operative system**
Just updated to 0.99.42 on Windows 10 (portable version, copied the old 0.99.41 cfg over)

**Describe the bug**
Interface appears in english. But this is not the system default language, which instead is german. After explicitely switched to german an restart of the program, the interface remains in english.

**To Reproduce**
If applicable, attach a non-personal document where the issue can be reproduced systematically.

**Screenshots**

**Comment by giuspen** [comment]
there was a failure to copy over the compiled languages in the script, sorry about that, I'm going to update the windows portable and installer shortly.
