### ISSUE TITLE
Ability to search the keyboard shortcuts

### ISSUE THREAD

**Issue by Flavored-37860** [giuspen/cherrytree#1833]
**Currently we can't search the shortcuts we are looking for.**

![cherrytree_MA6i5PwSUf](https://user-images.githubusercontent.com/92237041/137836704-020ddeb2-04ec-4f65-985f-37c4d395d6c4.jpg)

**Add the ability to search shortcuts in Preferences ➔ Keyboard Shortcuts**. Thanks!

**Comment by PranavBhattarai** [comment]
![image](https://user-images.githubusercontent.com/32763112/144995869-898b7001-8bc3-4c97-b859-774c2954b0a0.png)
Was about to create a new issue on this. The above screenshot is one example that shows LibreOffice giving users to search shortkeys. Many IDEs and editors provide this option.

As software advance more and more, the more we are going to see new features and options.
To sort list the feature we need, the developer provides search functionality. Take Android for example. I think, starting Android 10, users can search the "remove animation" option from the phone Settings or if a user wants to enable Developer option, he/she can just tap the search bar in Settings and jump directly to that option.

We need this inside on CherryTree's "Keyboard Shortcuts" section, where we can simply press, **Ctrl + F** to search all shortkeys or **Search bar** to search the shortkey we are looking for.

**Comment by giuspen** [comment]
you will be able to search typing part of the description of the shortcut in 0.99.45

**Comment by PranavBhattarai** [comment]
Wow. Thanks a lot. This makes things more user-friendly.
