### ISSUE TITLE
Ctrl + Numpad 0 to reset Zoom 🔍

### ISSUE THREAD

**Issue by Flavored-37860** [giuspen/cherrytree#1835]
We can use `Ctrl + Numpad+/Numpad-` to control zoom in Web Browsers, Notepad++, Windows Notepad & many other applications. We can also reset the zoom level in them with `Ctrl + Numpad 0`.
Similarly in Cherrytree, we can zoom in & out by using `Ctrl + Numpad+/Numpad-` or by `Ctrl + Mouse Wheel`
but **we cannot reset the zoom level to default font size value set in preferences with `Ctrl + Numpad 0`**.

![1ZvDiCItkX](https://user-images.githubusercontent.com/92237041/137840062-b0979ff9-b1e1-473c-a179-92d560fcdfe4.gif)

Allow to reset the zoom level with `Ctrl + Numpad 0` in both tree & content view. Thanks!

**Comment by giuspen** [comment]
This has now been implemented and will be available in upcoming v1.1.4
