### ISSUE TITLE
Search with new version 0.99.41 and 0.99.42.1 not work correctly 

### ISSUE THREAD

**Issue by rpierluigi** [giuspen/cherrytree#1837]
**Version, Operative system** windows 10 21H1 Version of cherrytree portable 0.99.41 and 0.99.42.1

Search with new version 0.99.41 and 0.99.42.1 not work correctly 

I wanted to report that the search does not work correctly in the latest versions of the program I tried version 0.99.34 on the same database with 34 it correctly finds 15 occurrences while with 41-42 it finds only 9 you could verify the problem thank you in advance. I attach files where you see the problem.
**Screenshots**
If applicable, add screenshots to help explain your problem
![ErroreInRicercaNuoveVersioniCherrytree](https://user-images.githubusercontent.com/15266442/138290879-5590b742-238e-44b7-bb2d-d84d194b3820.png)
.

**Comment by giuspen** [comment]
fixed in upcoming 0.99.43 (via running menu item command under top menu search to clear search exclusions)
