### ISSUE TITLE
Feature Request: Hide Menu Bar like VSCode (press Alt to reveal)

### ISSUE THREAD

**Issue by thwerks** [giuspen/cherrytree#1849]
i rarely use the menu bar so it would be great to be able to hide it and get it just by pressing Alt key. Many programs have this arrangement but VS Code is the first that comes to mind. 

The option for moving file menu into title bar i dont like for most of my usage. Usually i keep Cherrytree as a small window for taking/reading notes, so i don't want the file menu taking space. But, putting file menu in title bar makes it very annoying to relocate the window and on a netbook its would be troublesome also. 

please consider to make it possible to hide menu bar but keeping the title bar

Thank you for your consideration

**Comment by giuspen** [comment]
Makes sense and shouldn't take too much effort to implement

**Comment by thwerks** [comment]
i would suggest the Alt key function as a toggle rather than momentary, such like it does in VS Code and Firefox. 

the difference between firefox and VScode is that in VS Code Alt will toggle the file menu, even if you click away, it remains. Whereas with Firefox, its toggle also but file menu disappears if you click away.  I think a persistent toggle would be more idea for cherrytree because there may be times when you need the menu repeatedly and therefore a persistent toggle might be overall more useful than momentary or a temporary toggle.

**Comment by giuspen** [comment]
will be in upcoming 0.99.43, I have defined F12 as default keyboard shortcut for now but will check if OK also on windows
