### ISSUE TITLE
Highlight Issue

### ISSUE THREAD

**Issue by keithkeekw** [giuspen/cherrytree#185]
Hi Giuspen,

I stumbled upon an issue with CherryTree where the highlight in Python is being bring forward into another node which the node is just a Rich Text.

This happen whenever I start CherryTree.

[GIF](http://i.imgur.com/LUzeGb1.gif)

I am able to replicate this in Windows as well as Linux.

**Comment by giuspen** [comment]
Hi Keith, thanks for reporting the issue, should be fixed in current master HEAD, can you please try it?
