### ISSUE TITLE
MacBook M1 Pro fresh install, home-brew cheerytree creates black window

### ISSUE THREAD

**Issue by phillips321** [giuspen/cherrytree#1852]
MacOS 12.0.1 MacBook M1Pro

When running cherrytree from a homebrew install the window is black.

<img width="957" alt="Screenshot 2021-11-02 at 21 33 53" src="https://user-images.githubusercontent.com/2072147/139955085-083c1c47-75e8-4611-a4c6-a00be0262226.png">

This a fresh OS install followed by a fresh homebrew install:
```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
cherrytree
```

**Comment by AlStanchev** [comment]
Also having this on MacOS 12.0.1 MacBook Pro 16
On Big Sur it was working ok.

**Comment by josephwhenry** [comment]
I'm seeing this too, I think CherryTree hasn't been updated for Monterey yet. Did a fresh reinstall and saw a lot of calls to resources with big-sur in the name.

**Comment by giuspen** [comment]
Has anybody tried to build from the sources in homebrew instead of using the binary? There are instructions on https://github.com/giuspen/cherrytree#building-cherrytree-on-macos

**Comment by josephwhenry** [comment]
Hey @giuspen , yes I did try installing it through homebrew yesterday. This was where I saw all the calls to resources with "big-sur" in the name (I'm on Monterey).

**Comment by troyf** [comment]
Following the directions to build from source yields the same black screen (actually a title bar of a response window asking for the repository's password. If correctly typed and ENTER pressed, black screen. If incorrect password, the title bar/response window remain... probably re-prompting for the password)
Troy.
#

**Comment by giuspen** [comment]
It's more of a test rather than a directive since I don't have a working virtual machine with Monteray working at the moment. to avoid duplications please follow this on https://github.com/giuspen/cherrytree/issues/1844 I'm closing this as a duplication
