### ISSUE TITLE
Question - Recent Tabs

### ISSUE THREAD

**Issue by LookingForWayOut** [giuspen/cherrytree#1858]
Hello.

Is there a way, a list or indicator, to show me my recently modified nodes? I am trying out the program and realized that if I add in many nodes/notes, easily forget which were updated. Updated either by adding nodes, from a crash or shutdown, etc. I see can tell on the bottom of each node the last modified date, but what about a method or list or indicator showing all nodes, sorted by their modified date?

Thank you.

**Comment by giuspen** [comment]
Hi, you can search setting a filter on the created or modified date. You can search with a regular expression of '.*' on nodes names and tags, that should give all matches within the timeframe

**Comment by LookingForWayOut** [comment]
Thanks for the info.
I may be doing it wrong.
If I do it like the (attached) image for any nodes changed since yesterday (Saturday), the program freezes.
<img width="323" alt="2021-11-07 21_56_58-Find in Multiple Nodes" src="https://user-images.githubusercontent.com/11941595/140677390-a23bcf22-8e6d-4fb2-92c1-6ebd756e0ca8.png">
If I declick "node content," then it lists all 200+ nodes, even though on three or four were modified since yesterday.

**Comment by LookingForWayOut** [comment]
I also tried it without "regular expression" clicked. Still brings me 200+ nodes, even though only a few were modified since Saturday, in this case.

**Comment by LookingForWayOut** [comment]
I tried the latest version, but it still locks up the program.

**Comment by giuspen** [comment]
I will give a try and provide feedback

**Comment by LookingForWayOut** [comment]
Hello, hello. I wanted to see if anyone else has been able to see if I am doing it wrong, or it is just not doing what I expect it to do?
Thanks. :)

**Comment by giuspen** [comment]
There was in fact a bug, will be fixed in 0.99.46. You have to deselect the node content and leave only node name and tags (Ctrl+T does it for you) and it is correct to use ".*" and regular expression selected.

**Comment by LookingForWayOut** [comment]
I just tried that today and the first few tries did not work. As I was typing out a message about it, and snapshots, another try ended up working (even though the parameters were the same).

I did a check for nodes created after January 1.

<img width="221" alt="1" src="https://user-images.githubusercontent.com/11941595/156791497-9420412d-047c-4984-8591-3d4ea93507e1.PNG">

Results.

<img width="112" alt="2" src="https://user-images.githubusercontent.com/11941595/156791700-d89b0ee7-db9b-4c30-bacf-e89debfd0ace.PNG">

Since dates not shown in the list, I checked each node on the bottom and they are correct to the search.

<img width="161" alt="3" src="https://user-images.githubusercontent.com/11941595/156791868-17ed8c38-a035-4a20-840b-691318966df6.PNG">

I did the same with modified dates for after this Monday.

<img width="302" alt="4" src="https://user-images.githubusercontent.com/11941595/156792009-89cdeb6e-e73f-436d-8f27-ec6c7acdad90.PNG">

<img width="111" alt="5" src="https://user-images.githubusercontent.com/11941595/156792184-bc5cd99d-362f-467d-b42a-302d2a61825c.PNG">

<img width="212" alt="6" src="https://user-images.githubusercontent.com/11941595/156792293-71a765ed-8a21-4e15-89cb-a9845b0dbc63.PNG">

Just, I should not run them together (both a create and modified box clicked). Give no results.

But, I am happy with able to see what I recently modified to keep on trying things out.

Thank you.
