### ISSUE TITLE
Execute code in codebox with another terminal emulator.

### ISSUE THREAD

**Issue by alltogo91** [giuspen/cherrytree#1860]
I like to use CodeBox´s , but I don't like the XTerm Elulator to run code...is there any possibility to use another emulator like "konsole".

I tried to replace xterm with konsole (German version of console)  but it doesn't work.

**Comment by giuspen** [comment]
The thing is that xterm is very versatile while other virtual terminals may not allow such control.
My plan is to support soon an integrated virtual terminal into cherrytree to solve in particular the fact that the current mechanism works only on Linux and Windows but not on the Mac Os.

**Comment by alltogo91** [comment]
Thank´s for your response, I did not know that xterm is particularly suitable for technical reasons. What you are planning sounds very good. I am looking forward to an integrated terminal. 

By the way, i am a big fan of cherrytree, thanks for the great project.

**Comment by ciranus** [comment]
> I tried to replace xterm with konsole (German version of console) but it doesn't work.

It works for me in KDE.

![ct](https://user-images.githubusercontent.com/61602511/141819696-dba39f0a-7080-4711-9bdd-e4e696e5463f.png)

**Comment by alltogo91** [comment]
I just tried it again and yes, now it works...thanks

**Comment by ciranus** [comment]
Great.
And konsole  is not the "_German version of console_", but the [KDE's Terminal Emulator]https://konsole.kde.org/)

**Comment by giuspen** [comment]
Closing this as seems complete. Furthermore I'm working on an integrated terminal as an alternative for the next release.
