### ISSUE TITLE
cherrytree 0.99.43-4 Debian Bullseye Dependency Issue

### ISSUE THREAD

**Issue by Exoiz** [giuspen/cherrytree#1864]
deb file appears to have been packaged with a dependency for libgspell-1-1, can a deb file be packaged for libgspell-1-2 ?

The following packages have unmet dependencies:
 cherrytree : Depends: libgspell-1-1 (>= 1.2.0) but it is not installable
E: Unable to correct problems, you have held broken packages.

Without rebuilding from source the nasty hack below does work however it will encounter issues I highly suspect.

`wget https://launchpad.net/~giuspen/+archive/ubuntu/ppa/+files/cherrytree_0.99.43-4_amd64.deb`
`ar x cherrytree_0.99.43-4_amd64.deb`
`tar -xf control.tar.xz`
`nano control` ← remove dependency (libgspell-1-1 (>= 1.2.0), )
`tar cfJ control.tar.xz md5sums control`
`ar rcs newpackage.deb debian-binary control.tar.xz data.tar.xz`
`sudo apt install ./newpackage.deb`
`sudo ln -s /usr/lib/x86_64-linux-gnu/libgspell-1.so.2.3.0 /usr/lib/x86_64-linux-gnu/libgspell-1.so.1`

**Comment by ciranus** [comment]
Hello,
You can also remove `gnome-icon-theme` dependency which is not necessary for Debian package.
https://packages.debian.org/bullseye/cherrytree

**Comment by giuspen** [comment]
0.99.43-4 is for Ubuntu 18.04

**Comment by giuspen** [comment]
Look at the series column https://launchpad.net/~giuspen/+archive/ubuntu/ppa/+packages you probably want 20.04 (focal?)

**Comment by ciranus** [comment]
Concerning `gnome-icon-theme` dependency, the remark already made in [May](https://github.com/giuspen/cherrytree/issues/1648#issuecomment-833316285) is also valid for ubuntu package which does not require `gnome-icon-theme`.
https://packages.ubuntu.com/hirsute/cherrytree
`gnome-icon-theme` dependency has been added very recently (from V#40) for unclear reason in ppa builds.

**Comment by Exoiz** [comment]
> Look at the series column https://launchpad.net/~giuspen/+archive/ubuntu/ppa/+packages you probably want 20.04 (focal?)

You're correct, using the below deb package installed correctly for Debian Bullseye with no modification to the package required.
`https://launchpad.net/~giuspen/+archive/ubuntu/ppa/+files/cherrytree_0.99.43-1_amd64.deb`
