### ISSUE TITLE
"File" and "Format" has the same Alt access key

### ISSUE THREAD

**Issue by Arteneko** [giuspen/cherrytree#1865]
**Version, Operative system**

CherryTree 0.99.41, Windows 10

**Describe the bug**

When pressing Alt for a few secs., a series of underlines appear, notifying that we can now use the underlined symbols to expand the menus.

The File and the Format ones both are bound to the Alt+F combination.

I would've made a change myself, but I don't really know which key would be the best for that... Any opinion ?

**Comment by giuspen** [comment]
I can fix this when I will modify the translatable strings again, in the meantime if you press F twice you should go to the second menu item accelerated with the letter F

**Comment by Arteneko** [comment]
Thanks for the info, and the tip

**Comment by giuspen** [comment]
will be fixed in next version 0.99.45
