### ISSUE TITLE
Request For Comments: Hosted Notes, Networking and Multi-User Collaboration 

### ISSUE THREAD

**Issue by thwerks** [giuspen/cherrytree#1866]
Hi everyone, I just wanted to raise the idea of using CherryTree in a network environment. Ether for the purpose of centralized/hosted notes or multi-user collaboration, etc.

I have briefly used CherryTree in a Linux networked environment (over SSHFS) and it did work but when two users simultaneously used it, its was having unpredictable behavior. So, I don't think CherryTree can work over a network well currently.

Personally I feel the hierarchical method of CherryTree is wonderful but it's mostly just to the benefit of the individual. Its not easy or maybe not even possible to leverage CherryTree's technology in a collaborative setting. Whatever benefit CherryTree brings to the individual, its far greater to a collective. 

Now I ask, what are some possible methods to achieve this and what other extraneous considerations would be needed to facilitate multi-user capability within CherryTree?

Excluding the technical elements, fundamental elements would be like: locking a node for editing (meanwhile another user can still view), edit-lock timeout.  Create/read/write permissions, user access and login. And general hosting method. 

More technically speaking I think SSL/HTTPS is probably the best way to host, its simple, firewalls easily allow it and webapp and websocket might be convenient to use. KeePass has a very interesting hosted method, i think the client accesses an SSL connection. I have no idea but i think its possible to make CherryTree act as a client and access the database file remotely over SSL like as in KeePass. How to handle authentication, user permissions, etc, So possibly there would need to be  a lightweight server utility or perhaps a webapp that self-hosted the database that also provided a wrapper functionality for communication between the webapp database server and the CherryTree client. 

I'm not sure what networking capabilities GTK has for this kind of networking.  Its possible there's something better than SSL such as SSH. I don't know if GTK has ability for websocket. It would be cool if CherryTree as a client could use websocket to pull the data and push changes to the server. Then flag the client to reload the node. I don't think it matters much how the data comes into  CherryTree. once the data is there you can push or post.

There's also the way CherryTree fetches data from the database. I don't know how that occurs but i know its a very latent process that isn't optimized for the internet, it lag much over the internet. that should probably be tuned and or discover how the process should be.  Would it be real-time synchronous, or be cached and perform reconciliation and conflict handling. That depends on how much control GTK offers over network communication, I dont know. I think maybe the easiest approach is best. Lock nodes for editing with timeout so reconciliation can be avoided. Then its just a matter of tuning how CherryTree fetches. 

I'm not GTK developer but its seems CherryTree is just communicating to a database that could be hosted anywhere. and only a matter of how to handle user access, node locking and other things like that. Possibly fundamental changes to CherryTree itself wouldn't be needed or would be minimal.

Personally i think the payoff would be huge. There aren't exactly a lot or hostable hierarchical information management systems out there. And anyone with a privacy concern has little or no choices. In fact there just isn't really anything out there. If you're a corporation  managing informational data, you're just back to hosting individual files and documents on a ftp, samba or http server or Google Docs. Unless you have like some crazy complex webapp that you spent years making; small companies can afford to make their own webapps usually.

I mean what else is really out there? I feel this need has not be adequately met and i see a lot of companies just storing documents on file servers over VPN because there's no real alternative. I might be able to help, I have years of experience in computer networking and have built IT environments from the ground up and saw many companies who definitely benefit from this. Just think about it, thanks.

**Comment by giuspen** [comment]
Hi @thwerks the topic of collaboration on a cherrytree document is very interesting and I believe a great fan to implement, on the other hand I believe it requires a lot of time. To minimise the code duplication, I believe an approach would be to make cherrytree start in three modes: standalone (just like now), server and client. TCP over a secure layer and the definition of a protocol. I cannot work personally on it for now but in future may be.

**Comment by thwerks** [comment]
thank you for the comment sir. when you have time, maybe we can talk about the things needed to implement this technology. such as node write locking and permissions for example. I do also have some questions about how the database information is leaded into ram and also wanted to possible help with implementing a client server protocol.

**Comment by Bulwagga** [comment]
My use case is a little different. I work at four computers around the house.  Two Ubuntu boxes and two Windows boxes.  Since there is only one of me, I can store my cherrytree mtb file on a samba share located on a raspberry pi.  It is very nice to have my notes available wherever I happen to be working.
