### ISSUE TITLE
Frozen when not connected to the internet

### ISSUE THREAD

**Issue by repsorp** [giuspen/cherrytree#1867]
**Version, Operative system**
Cherrytree version 0.99.43 (Flatpak)
Ubuntu 21.10

**Describe the bug**
Totally frozen when there is no connection to the internet

**To Reproduce**
Only occurs if "Automatically check for newer version" is activated in preferences.

Logs:
```
~$ journalctl -p 4 -b | grep cherrytree
nov. 18 01:21:27 zyx systemd[2061]: Started app-flatpak-com.giuspen.cherrytree-333165.scope.
nov. 18 01:21:27 zyx systemd[2061]: app-gnome-com.giuspen.cherrytree-333165.scope: Deactivated successfully.
nov. 18 01:21:27 zyx cherrytree[333177]: Language overwrite = en (localedir = /app/share/locale)
nov. 18 01:21:27 zyx cherrytree[333177]: Locale not supported by C library.
nov. 18 01:21:27 zyx cherrytree[333177]: Failed to load module "canberra-gtk-module"
nov. 18 01:21:27 zyx cherrytree[333177]: Failed to load module "canberra-gtk-module"
nov. 18 01:21:27 zyx com.giuspen.cherrytree.desktop[333177]: [2021-11-18 01:21:27.526] [gtk] [critical] Class::register_derived_type(): base_query.type_name is NULL.
nov. 18 01:21:27 zyx com.giuspen.cherrytree.desktop[333177]: [2021-11-18 01:21:27.529] [   ] [debug] /home/zyx/.var/app/com.giuspen.cherrytree/config/cherrytree/config.cfg parsed
nov. 18 01:21:27 zyx com.giuspen.cherrytree.desktop[333177]: [2021-11-18 01:21:27.604] [   ] [debug] autosave is started
nov. 18 01:21:27 zyx com.giuspen.cherrytree.desktop[333177]: [2021-11-18 01:21:27.698] [   ] [debug] Node name: Remove purple colour from GDM on Ubuntu 21.10
nov. 18 01:21:27 zyx com.giuspen.cherrytree.desktop[333177]: [2021-11-18 01:21:27.819] [   ] [debug] fs::download_file: start downloading https://www.giuspen.com/software/version_cherrytree
```

**Comment by ciranus** [comment]
`libcanberra-gtk-module: /usr/lib/x86_64-linux-gnu/gtk-2.0/modules/libcanberra-gtk-module.so`

`libcanberra-gtk-module`  is a **gtk2** module (something strange).
For investigation:
is `libcanberra-gtk-module` package installed ?
If not, can you install it and confirm the result.

**Comment by repsorp** [comment]
"libcanberra-gtk-module" is installed:
```
/usr/lib/x86_64-linux-gnu/gtk-2.0/modules/libcanberra-gtk-module.so

/usr/lib/x86_64-linux-gnu/gtk-3.0/modules/libcanberra-gtk-module.so

```
I switched from ppa to flatpak for convenience when upgrading system.
For now I think I'll stay with the flatpak version with version check disabled.

**Comment by ciranus** [comment]
Ok now clarified.
Then something to be technically investigated in the Flatpak package itself.

**Comment by giuspen** [comment]
I'm curious if you use the PPA version does it still happen?
sudo add-apt-repository ppa:giuspen/ppa
sudo apt install cherrytree

**Comment by repsorp** [comment]
> I'm curious if you use the PPA version does it still happen?

Doesn't happen with PPA version
When disconnected PPA version only freezes if I click on "Check Newer Version in "Help" menu
Flatpak version freezes from start...

**Comment by ciranus** [comment]
> When disconnected, PPA version only freezes if I click on "Check Newer Version in "Help" menu

What do you mean by freeze ?
I just get this message with no freeze at all. To be first clarified.
![ct2](https://user-images.githubusercontent.com/61602511/142648176-e5ed2ee8-24bc-4af7-93e4-98a9806c9d36.png)

**Comment by repsorp** [comment]
> > When disconnected, PPA version only freezes if I click on "Check Newer Version in "Help" menu
> 
> What do you mean by freeze ? I just get this message in the status bar, with no freeze at all. To be first clarified.
> 
> ![ct2](https://user-images.githubusercontent.com/61602511/142648176-e5ed2ee8-24bc-4af7-93e4-98a9806c9d36.png)

Not any message, application is frozen, cannot close the window or click anywhere, nothing's working

**Comment by repsorp** [comment]
Maybe something to do with my VPN (Wireguard) but it would be weird because "kill switch" is not activated...

**Comment by repsorp** [comment]
OK... 
So it has to do with my VPN config...
Cherrytree is working fine when my VPN is deactivated
On the other hand I don't know what to modify with the VPN since only cherrytree has this problem for the moment.

**Comment by ciranus** [comment]
However, the VPN cannot explain the CT freeze you have, or I miss something.

**Comment by repsorp** [comment]
> However, the VPN cannot explain the CT freeze you have, or I miss something.

It must have something to do otherwise why CT would work when the VPN is disabled ?

**Comment by ciranus** [comment]
As I said, "_or I miss something_", because I don't see any logic behind.
Said differently, a mystery to me.

**Comment by repsorp** [comment]
A mystery to me as well...

**Comment by repsorp** [comment]
Found in the logs when I turn off the wifi, open cherrytree and then try to close the application:
`│Nov 19 18:34:32 zyx gnome-shell[2270]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x260000b    `                                       │

**Comment by ciranus** [comment]
for investigation only:

`dpkg --search bin/gnome-shell`

`echo $SHELL`

**Comment by repsorp** [comment]
```
~$ dpkg --search bin/gnome-shell
gnome-shell: /usr/bin/gnome-shell-extension-tool
gnome-shell-extension-prefs: /usr/bin/gnome-shell-extension-prefs
gnome-shell: /usr/bin/gnome-shell-perf-tool
gnome-shell: /usr/bin/gnome-shell
```

```
~$ echo $SHELL
/bin/bash

```

**Comment by ciranus** [comment]
I don't know gnome at all, but note that your log is just a **warning** which should not explain a freeze due to unavailabe network, unless you have something wrong with your window manager settings.

**Comment by giuspen** [comment]
I will see if I can add a timeout to the libcurl function call that is used in this context
