### ISSUE TITLE
error when generating html when using an apostrophe in the page title

### ISSUE THREAD

**Issue by 13werwolf13** [giuspen/cherrytree#1869]
if you create a page in whose name an apostrophe will be used, for example "it's a great day" then the menu will not work because of the unescaped character

you can see an example in my notes at https://itrus.su/ by trying to open the menu item "auto get host-tracker allowed ip's for anginx access rules"

**Comment by giuspen** [comment]
thanks will be fixed in upcoming 0.99.44
