### ISSUE TITLE
Import from Zim not working

### ISSUE THREAD

**Issue by mdphillips1** [giuspen/cherrytree#1870]
I have just installed Cherry Tree, switching from Zim Desktop Wiki due to Cherry Tree's greater formatting capabilities in comparison to Zim.  I have tried to use the File>Import>From Zim Folder to import my notes from Zim, selecting the folder that is/was the notebook name in Zim.  However, after selecting the folder and clicking 'Open', the dialogue box closes and nothing imports.
According to the online manual, a dialogue box should appear (after clicking 'Open') that asks me "who is the parent?"  This dialogue box did not appear.
Needless to say, I would rather not have to type out (or copy/cut and paste) all of my notes from Zim into CherryTree.  Importing should be much quicker and easier.

I am using Linux Ubuntu 20.04.03 64-bit, with CherryTree 0.99.43.  The Zim Desktop Wiki version I have installed is 0.73.5.

Please can somebody help?

**Comment by giuspen** [comment]
If you run cherrytree from a terminal is something printed out when your import from zim fails?

**Comment by mdphillips1** [comment]
Thanks for your reply.
I don't run CherryTree on a terminal.  I have a shortcut on my launcher.  There is no printout when the import fails.  The dialogue box just closes and nothing happens.

**Comment by ciranus** [comment]
> I don't run CherryTree on a terminal.

Then you should to see what happen.

![2021-11-21_00-07](https://user-images.githubusercontent.com/61602511/142743497-56b91633-e3cb-477c-9044-abf619d5f18a.png)

**Comment by giuspen** [comment]
@mdphillips1 I can help only if you share with me the data to import or if you run from a terminal and tell me more about what you see printed. In alternative you can enable the log from the preferences, close and reopen cherrytree, reproduce the issue then attach the log. but in linux it is much easier to just open a terminal write cherrytree and run from there

**Comment by mdphillips1** [comment]
@giuspen Sorry for the late reply.  I just checked now (before seeing your comment), and it says that there is no notebook.zim file in one of the directories that is 2 levels within the one that I am trying to import.  I'm not quite sure why it's saying this.  Although there is no notebook.zim file in the directory specified, this is not the directory that I am trying to import.  I have checked the other directories within the one I am trying to import, and they don't have notebook.zim files either.  Any idea why this might be happening?

For the record, the message below is what I am seeing.  I am trying to import the Health & Fitness folder as a notebook ('file' or 'instance' according to CherryTree), but for some reason the below message is appearing.

[2021-12-05 14:52:46.714] [   ] [error] import exception: [Import Exception]: Directory: /home/philm004/Notebooks/Health & Fitness/Chris_Wark/Square_One_Healing_Cancer_Coaching_Program does not contain a notebook.zim file

**Comment by ciranus** [comment]
Problem confirmed, and workaround found. 
I already had this problem with other applications (problem selecting a directory, and not a file).
I've installed zim for test.
▸ creation of `/home/user/Notebooks/TestNotes/notebook.zim` file.

However, the file importer is looking for **directory**, and not a .zim **file**.

![CT1](https://user-images.githubusercontent.com/61602511/144755121-c319e2da-d94c-44f5-9cfc-abc294299d6e.jpg)

![CT2](https://user-images.githubusercontent.com/61602511/144754953-f11a448a-e889-4556-81ce-9418f783d160.jpg)

3 Workaround, from `/home/user`, manually type **Notebooks** in the file selector

![CT3](https://user-images.githubusercontent.com/61602511/144754977-d5d3930c-6c33-47ef-b8fe-30f93de9e321.jpg)

![CT4](https://user-images.githubusercontent.com/61602511/144755001-93528a65-1636-476b-90f7-2aa2688d0bf3.jpg)
-----
@giuspen
Not related to the subject, but for information or future request, it was a opportunity for me to investigate the **AT-SPI** warning seen in my KDE environment (reported above).
Solutions: either install `at-spi2-core` or add **NO_AT_BRIDGE** shell environment variable
`export NO_AT_BRIDGE=1`

**Comment by giuspen** [comment]
Thanks @ciranus for helping out. I tried to reproduce but couldn't, I improved though the default selected folder at import time which is the one containing the notebook.zim file same as the old pygtk2 version was doing.
I haven't understood though if zim works without this file, for further help @mdphillips1 you should zip and send me test data so that I can first ensure that is properly visualised by zim and then try and import it

**Comment by giuspen** [comment]
this will be fixed in the next release 0.99.51
