### ISSUE TITLE
Bug: Attachment filenames with hyphens/dashes do not show hyphens/dashes

### ISSUE THREAD

**Issue by metal450** [giuspen/cherrytree#1875]
**Version, Operative system**
Version 0.99.43, Windows

**Describe the bug**
Minor bug: file attachments that contain dashes/hyphens in the name do not show dash/hyphen (it seems to just show a space).  Please see screenshot

**To Reproduce**
1. Create a file i.e. "test - file.txt"
2. Attach it to a note
3. Observe that it shows "test file.txt" rather than "test - file.txt"

**Screenshots**
![2021-11-21 11 28 04](https://user-images.githubusercontent.com/1877409/142776256-3d05956e-d493-4693-b46a-63ed5fe4e2ff.png)

**Comment by giuspen** [comment]
Cannot reproduce on linux, will try on windows later

**Comment by giuspen** [comment]
strange, I cannot see it in windows 10 either. maybe you attach a file to this issue and I'll try with that

**Comment by giuspen** [comment]
or maybe it's a font issue, can you try to play with the fonts?

**Comment by metal450** [comment]
Yup, looks like that's it. Calibri 11 shows the issue, 10 & 12 don't.  Very odd tho, as I never saw that before this update.

Anyway, just a minor UI oddity, so not worth spending time on I s'pose :)
