### ISSUE TITLE
Error dialog fails when search pattern contains ampersand (&)

### ISSUE THREAD

**Issue by golimarrrr** [giuspen/cherrytree#1876]
**Version, Operative system**
0.99.33 Win10
0.99.43 Debian10

**Describe the bug**
Searching for text on node works but if it is not found the error dialog shows no text

**To Reproduce**
1. Go to any node
2. Ctrl-F and search for 'abc&def'
3. Dialog box is empty and console shows:
```
(cherrytree:2121): Gtk-WARNING **: 17:05:14.469: Failed to set text 'The pattern 'abc&def' was not found' from markup due to error parsing markup: Error on line 1: Entity did not end with a semicolon; most likely you used an ampersand character without intending to start an entity — escape ampersand as &amp;
```

**Comment by giuspen** [comment]
thanks
