### ISSUE TITLE
Monospace background can't be modified

### ISSUE THREAD

**Issue by tonyrulez** [giuspen/cherrytree#1877]
**Version, Operative system**
0.99.43, Windows 10

**Describe the bug**
Can't find where to change monospace text background. For example the background has almost the same color as selection color, so you can't really see what you selected with your cursor. Here, update is highlighted:

![kép](https://user-images.githubusercontent.com/27233005/143543790-6d572491-ce24-421c-ac52-a3847df0f9b1.png)

**To Reproduce**
According to the [manual](https://giuspen.com/cherrytreemanual/#rich-text-pref), under theme there should be a Monospace Background setting:

> Theme
> Monospace Background - Defines the background color of monospace text.

I don't have that:

![kép](https://user-images.githubusercontent.com/27233005/143543977-238788eb-e18e-41c1-9eb8-892607f45e84.png)

**Comment by giuspen** [comment]
look at the tab "Format"
![image](https://user-images.githubusercontent.com/6842059/144726521-8362c07a-40b2-40df-a5ea-9d4ab3795404.png)

**Comment by tonyrulez** [comment]
Got it, thanks.
