### ISSUE TITLE
RFI: scalability of the CherryTree 'database'/storage system

### ISSUE THREAD

**Issue by netweaver1970** [giuspen/cherrytree#1878]
Hi,
I recently stumbled on this program, And I like the idea a lot.
But before I go flat out and start capturing all my knowledge from scraps of paper/emails/everywhere into CherryTree, I would like to know what are the real usage limits, in terms of hierarchies, nodes, embedded images, total file size(s) etc ...
Certainly if putting compression in play.
Also, what about corruption? I know with SQLite it's not uncommon (cf. HomeAssistant SQLite usage).
Once one decides to trust his knowledge into a tool, one needs to be sure about it's limits or recovery ability when things go haywire.

Thanks.

**Comment by Sisyfos3** [comment]
@netweaver1970, I have used CT for at least five or six years, maybe longer. My data file is now about 14 GB in size, I've never lost anything (but I back up my data daily). As far as I can tell, there are no limits on the number of nodes/subnodes, embedded images, attached files etc. I am extremely pleased with CT, @Giuspen has produced an outstanding piece of software. Many many thanks to him.
/Sisyfos3

**Comment by netweaver1970** [comment]
thanks for you experience. Is that with SQLite or XML file format?

**Comment by Sisyfos3** [comment]
That is with the SQLlite CTX file format

**Comment by netweaver1970** [comment]
hmmm, I'm already having a corruption :( 
![image](https://user-images.githubusercontent.com/18028618/144612359-b77e265d-38c6-42b3-a9b8-e66d14d181d4.png)

I have few backup files (I guess) left in the directory, so I'll try with one of the 'older' ones.
![image](https://user-images.githubusercontent.com/18028618/144612750-e2219183-a04b-4338-9c61-8e682ec10c48.png)

The location is my Documents folder (auto synced with with the AD network user profile with the server)
But my Keepass datafile is also stored in the same location, for years already and I never had corruption there.

Any idea how to prevent this?

**Comment by giuspen** [comment]
@netweaver1970 I also have been always using sqlite and never experienced a corruption. The XML format is not usable for larger databases because keeps saving everything all the times. I need more info to understand what happens there, the most likely cause is the auto synching
