### ISSUE TITLE
Tables in Root Node appear in every child node in text export

### ISSUE THREAD

**Issue by brownslink** [giuspen/cherrytree#1880]
**Version, Operative system**
Kubuntu 20.04 LTS with the giuspen/ppa/ubuntu focal up-to-date

**Describe the bug**
A table in the document corresponding to the root node is repeated in the text file export in every note.

**To Reproduce**
If applicable, attach a non-personal document where the issue can be reproduced systematically.
1. Download the [attached CherryTree file](https://github.com/giuspen/cherrytree/files/7651780/bug.ctd.txt) and remove the .txt suffix.
2. Export "All the Tree" to a "Single File" as "Plain Text"
3. Open the result in a text editor.
4. See that the table is replicated in every child node.

**Screenshots**
none

**Comment by giuspen** [comment]
Thanks I'll have a look

**Comment by giuspen** [comment]
fixed in upcoming 0.99.44
