### ISSUE TITLE
RTL links not working

### ISSUE THREAD

**Issue by osman1963** [giuspen/cherrytree#1889]
When creating a link, either to a note or a file, using RTL (Arabic) words, the word is turned into green and underlined, showing it is a link but when moving the mouse over it its pointer doesn't change, and the word is unclickable. Using English words to do the same works just fine.
Cherrytree ver. 0.99.43 on Windows 10
Thanks in advance

**Comment by giuspen** [comment]
can you attach or send me privately a test document where I can see this?

**Comment by osman1963** [comment]
Here you go :)

**Comment by giuspen** [comment]
it hasn't worked, please try to do it from the GitHub page rather than answering the email

**Comment by giuspen** [comment]
or write me directly an email you can find my email address by clicking help--about in cherrytree

**Comment by giuspen** [comment]
Thanks for sending privately your test document @osman1963 this will be fixed in upcoming 0.99.45

**Comment by osman1963** [comment]
Thanks a million :)
