### ISSUE TITLE
Drag and drop a selection is not working anymore

### ISSUE THREAD

**Issue by Jupek1** [giuspen/cherrytree#1891]
Hi,

In Linux Mint Cinnamon 20.2 drag and drop a selection is not working anymore (Cherrytree version 0.99.44). That worked in previous versions. 

Thanks for your great software.

**Comment by giuspen** [comment]
you are right, the thing is that before it was working but for plain text only (was losing formatting/embedded objects), now I took control of the default behaviour to support drag and drop of files from the file manager to cherrytree but I'm not supoorting the internal drag and drop of a selection. I will implement this to work properly for also rich text

**Comment by giuspen** [comment]
will be fixed in 0.99.47
