### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by Camilot55** [giuspen/cherrytree#1897]
In this version, tags like bold (<b> do not work...<\b>). I suggest removing them from executable files or finding another solution for displaying bold font
![2](https://user-images.githubusercontent.com/76065578/146436656-732227ac-2d04-4691-9b71-e5fc97a6175b.png)

**Comment by giuspen** [comment]
also reported on https://github.com/giuspen/cherrytree/issues/1890

**Comment by giuspen** [comment]
thanks, will be fixed in 0.99.45
