### ISSUE TITLE
German mistranslation

### ISSUE THREAD

**Issue by 11011100** [giuspen/cherrytree#1898]
**Version, Operative system**
CherryTree 0.99.44, Windows 10

**Describe the bug**
In the menu bar under View, the german translation contains the entry "Statusleiste anzeigen/ausblenden" twice.
The upper menu item, which hides the menu bar should be "Menüleiste anzeigen/ausblenden" instead.

**Screenshots**
![CherryTree_GermanMistranslation](https://user-images.githubusercontent.com/23618649/146446165-fc1cee89-462a-4bec-8803-f753dbcb146d.png)

**Comment by giuspen** [comment]
thanks for reporting, it has been fixed by @Mr-Update PR
