### ISSUE TITLE
Bulleted list display on Windows

### ISSUE THREAD

**Issue by tbleier** [giuspen/cherrytree#190]
On Windows systems some of the characters used for bulleted lists are not really ideal :-)

![cherrytree 0 37 4](https://cloud.githubusercontent.com/assets/22977852/19592843/f0171090-977d-11e6-9967-3ffb714d7bf8.png)

CherryTree 0.37.4 on Windows 10
Changing the font does not help - how are the bullet point characters chosen?
On Linux everything seems to be ok

**Comment by tbleier** [comment]
Update: depens on font - works with "Sans Normal", does not work with Windows-Fonts

**Comment by giuspen** [comment]
The characters used for the bulleted lists are currently configurable editing manually the config.cfg:
`chars_listbul = •◇▪-→⇒`
I should probably add this to the preferences dialog

**Comment by philippHRO** [comment]
> 
> 
> The characters used for the bulleted lists are currently configurable editing manually the config.cfg:
> `chars_listbul = •◇▪-→⇒`
> I should probably add this to the preferences dialog

I just did this, and it works. But all existing lists in my document still use the old symbols. I suspect in the future, this setting my be possible in Preferences, so it would be nice, if, by then, it would also change the existing list symbols with the new ones.
