### ISSUE TITLE
Feature request: Codebox execution improvement

### ISSUE THREAD

**Issue by lua-rocks** [giuspen/cherrytree#1902]
Codebox executing is very cool feature, I love it so much! But it would be much better to see the result directly in cherrytree without any confirmation popups and external terminals - just press the "Run" button and instantly get the result.

**Comment by giuspen** [comment]
it is in the plans to implement soon a internal to cherrytree virtual terminal emulator as currently the code execution doesn't work at all on mac os so this will solve this too

**Comment by giuspen** [comment]
This is done and will be in the upcoming version that shall be released in about a week. Unfortunately the library does not support Windows at the moment so the integrated terminal is available only in Linux and Mac OS.
