### ISSUE TITLE
about cherrytree's vision on  lack of setups

### ISSUE THREAD

**Issue by e4e6** [giuspen/cherrytree#1905]
hello i do use Kubuntu 20 , this is a great project dont misunderstand me but some projects killing themselves like some guy creates a framework with no tutorials, no proper docs , so i see this is also happening to this project :( well in this case no proper "setups" i happend to find a flatpak repo ; https://flathub.org/apps/details/com.giuspen.cherrytree which I dont know it is a volunteer or offical one but it would be nice to be one offical flatpak or snap for easy installation for novices, and offical links in this repo so ppl find that more easy and this is also count for windows setup "exe" there is not offical one not in this repo or the offical website which is down https://www.giuspen.com/cherrytree/ , i see some shady websites are putting cherrytree exe's on their websites and could be very well a virus.. because of no offical setups...  cherrytree is not popular and meaning less developer for this opensource project, I do sincerely think in this way not to blame anyone this is a great project thanks for your efforts

**Comment by datavectors** [comment]
In CherryTree look at top bar > Help > Online Manual (F1)

**Comment by giuspen** [comment]
The flatpak is official, I take care personally of it, however I advice to use the native package where available.
The packages downloaded from giuspen.com are official, built from me; the packages built in the official repositories of the various distributions are safe and so are the packages in the giuspen PPA under my control.
Sooner or later I'll spend some time on the documentation but for now I rather spend the limited free time in developing

**Comment by e4e6** [comment]
ok https://www.giuspen.com/ is down for me so i did not notice the website is OK , thats why I raise the issue
