### ISSUE TITLE
cherrytree 0.37.4 - fedora 24 - tray icon

### ISSUE THREAD

**Issue by mvrk69** [giuspen/cherrytree#191]
Hi,

I updated from Fedora 23 to Fedora 24 recently, and cherrytree tray icon doesn't work anymore.

I open cherrytree, the tray icon shows, but then i close cherrytree, and after that if i click the trayicon it doesn't show up the window, and if i right click doesn't show any option.

**Comment by giuspen** [comment]
I tested on fedora 24 cinnamon and it works properly, I guess you are on gnome correct?

**Comment by mvrk69** [comment]
Yes, i have Gnome.

But i've just tested it on another computer with F24 and Gnome and it works, so must be something on my F24 installation :(

**Comment by giuspen** [comment]
Note that there are 2 different systray types supported, the standard one and the appindicator, selectable from the preferences (tab miscellaneous). Try both maybe at least one works properly.
