### ISSUE TITLE
Minor display bug in confirmation dialog

### ISSUE THREAD

**Issue by Hoffenbar** [giuspen/cherrytree#1913]
**Version, Operative system**
Windows 10 21H1 19043.1415, Cherrytree 0.99.44 (portable)

**Describe the bug**
If one is about to delete a node with many subnodes, a confirmation dialogue appears, like in this example:

![image](https://user-images.githubusercontent.com/46227007/147682535-0eb85f01-8154-45e2-8829-5e5f9a6a5d8d.png)

And here we see ```<b>``` and ```</b>``` as attributes, instead the name of the node should probably formatted in bold typeface.

**To Reproduce**
If applicable, attach a non-personal document where the issue can be reproduced systematically.
1. Mark a node with many subnodes
2. In the conext menu, click on ```delete node``` (in German ```Knoten löschen```, last menu item)
3. The confirmation dialogue appears

**Screenshots**
See above.

**Comment by wmcody** [comment]
To add to this, in English the wording is awkward.

![image](https://user-images.githubusercontent.com/26467320/147694131-dc9412c7-ea38-4a7c-9799-0830f24ee218.png)

Better:

Are you sure you want to **delete the node 'xxx'**?

The node has children. **They will be deleleted too!**

**Comment by giuspen** [comment]
This was fixed in https://github.com/giuspen/cherrytree/commit/0efdb84fed390168ab757fc4a2de9faa1878847b thanks
