### ISSUE TITLE
Linux System Tray Docking

### ISSUE THREAD

**Issue by paul1149** [giuspen/cherrytree#1919]
I'm on MX Linux 19.4, which is built on Debian, and I use the KDE desktop environment.

I enabled the system tray icon, and it worked, but I expected the regular icon in the System Panel's Task Manager to disappear. I was trying to save space by switching to the smaller tray icon, but now I had two Cherrytree icons in the Panel.

Are there any plans to remove the standard Panel icon when the Tray icon is enabled?

Thanks. Enjoying CT very much.

**Comment by ciranus** [comment]
This can be managed with plasma system setting  global panel.
1 - add a specific cherrytree window rule
2 - add skip taskar property

Tested / it works fine.

**Comment by paul1149** [comment]
Works great, thank you. For posterity, I found it at `System Settings -> Window Behavior -> Window Rules -> New... -> (set matching rules) -> Arrangement & Access tab -> Skip taskbar, Force, Yes.`

**Comment by ciranus** [comment]
or directly with this command:
`kcmshell5 kcm_kwinrules`

Thanks for the feedback. Can be closed.
