### ISSUE TITLE
[v0.37.6][windows] Translation error in german language

### ISSUE THREAD

**Issue by philippHRO** [giuspen/cherrytree#192]
**There is a translation error in the german language file.**

"Siblings" was translated to "Kinderknoten" in at least one occasion, which is the sorting function in the context menu, upon rightclicking a node in the node tree.

"Kinderknoten" means "child node", which obviously is not the same as a sibling.

**This makes sorting the tree with the sorting function very unintuitive, as the user will expect the children of the node they right-clicked to be sorted, but instead the siblings are sorted.**

There may be other instances, where this translation error was made.

**Comment by giuspen** [comment]
Please download the (text document) https://raw.githubusercontent.com/giuspen/cherrytree/master/locale/de.po and edit it with https://poedit.net/ to fix the wrong translations then send it back to me via email or upload somewhere and link it here

**Comment by philippHRO** [comment]
Here is the file:

[de.po.txt](https://github.com/giuspen/cherrytree/files/557080/de.po.txt)

I also changed the translation of msgid's on line 82 and 242, regarding quitting the application. The german versions  were misleading as to whether it will close to tray or shut down completely.

**Comment by giuspen** [comment]
Thank you I committed your work see https://github.com/giuspen/cherrytree/commit/88603d8aaec0f5c08bff7710bcd375e2b390e868

**Comment by giuspen** [comment]
Note that the quit goes to tray only if the system tray is enabled, otherwise exits, please be sure that your new translation is fine for both cases

**Comment by philippHRO** [comment]
When "Enable System Tray Docking" is enabled CherryTree shows 2 entries at the bottom of the "file" menu, namely "Quit" which closes to tray and "Exit CherryTree", which closes completely.

When Try Docking is **not** enabled, CherryTree only shows 1 entry, which is "Quit", **which now closes completely.** I think you should change this, so it shows the "Exit CherryTree" msgid.

**Comment by giuspen** [comment]
When the tray is enabled, the normal quit doesn't exit completely as many applications do.
Maybe I could change the text in this case. In this case only a second menu item is available to exit completely. Maybe it makes sense to use the text that exits completely consistently. In the meanwhile I have to rollback your changes to the translations for these menu items unless you fix it for me

**Comment by philippHRO** [comment]
Roll back do the change. I'll then see which button does what and fix the translations accordingly.

**Comment by giuspen** [comment]
I realised I mixed up, I thought you added the reference to Tray but you instead removed it.
```
 #: /home/giuspen/Software/GIT-SW/git_cherrytree/modules/menus.py:179
 msgid "_Quit"
-msgstr "S_chließen (zum Tray)"
+msgstr "S_chließen"
 
 #: /home/giuspen/Software/GIT-SW/git_cherrytree/modules/menus.py:179
 msgid "Quit the Application"
-msgstr "Schließen"
+msgstr "Programm beenden"
```
I won't rollback your change then and in future I may use 2 different labels for the same menu item in case of system tray enabled or not.
Thanks again for your contribution.

**Comment by philippHRO** [comment]
Great!
