### ISSUE TITLE
Unicode characters automatically written to clipboard when creating (sub)nodes

### ISSUE THREAD

**Issue by silverwings15** [giuspen/cherrytree#1922]
**Version, Operative system**
Windows 10 ver 1909, build 18363.418 & CherryTree 0.99.44

**Describe the bug**
When creating nodes/subnodes and writing their names in unicode, the unicode characters get written automatically to clipboard 

**To Reproduce**
1. Open a new or existing CherryTree database
2. Create a new node or subnode using Ctrl-N or Ctrl-Shift-N
3. In the name box, type in unicode characters
4. Try to paste using Ctrl-V, or check using a clipboard manager
5. Previous clipboard content has been replaced with the unicode characters

**Screenshots**
The last 5 clipboard entries in Ditto, the clipboard manager I use

![image](https://user-images.githubusercontent.com/10742312/148345601-3d2e40f0-3c42-4648-b8fd-42394aea3f7f.png)

**Comment by giuspen** [comment]
How do you type unicode characters?

**Comment by silverwings15** [comment]
oh sorry, i should've mentioned, here is the program i use: https://www.unikey.org/en/download.html

**Comment by giuspen** [comment]
I see in your screenshot with the settings an option "Always use clipboard for unicode" which even though not selected makes me think the program may still use the clipboard to achieve the result, so I suspect your program is doing that. You should try to use another way to enter those characters and see if it does the same

**Comment by silverwings15** [comment]
you're right 

- i tried enabling that option and it exhibits the same behavior whenever i type an unicode character 
- i used the builtin windows keyboard and it doesn't have the same issue

unfortunate edge case, since this is the only scenario where that bug has ever happened to me. unfortunately the builtin windows keyboard is a little weird so i'm not too keen on switching, but either way good to know that it isn't a bug on the part of CherryTree. thank you for helping out!
