### ISSUE TITLE
lost menu bar 

### ISSUE THREAD

**Issue by francisgernet** [giuspen/cherrytree#1927]
**Version, Operative system**
v 0.99.44 on Ubuntu 21.04 LT, kernel 5.4.0-92-generic #103-Ubuntu

**Describe the bug**
The menu bar vanished

**To Reproduce**
I try to reboot the system, same pb occurs.
I try to search in ctrl alt P (Keyboard Shortcuts) but find nothing

**Screenshots**
![Screenshot from 2022-01-08 13-44-59](https://user-images.githubusercontent.com/13455776/148644653-9a0050ab-98db-4bc0-b943-7a2f27afbec5.png) with no menu bar

I think it's not an heavy pb, but I can't find an issue, and I have a important use of CHERRYTREES ; without menu bar, less comfortable!

**Comment by giuspen** [comment]
F12

**Comment by francisgernet** [comment]
Thank you very much. CHERRYTREES is really great!

**Comment by wgm-gh** [comment]
I concur - great tool!
I suggest having the Alt key toggle the menu bar, as is standard in UI.

**Comment by giuspen** [comment]
fixed in upcoming 0.99.48
