### ISSUE TITLE
Open more than one instance of cherrytree

### ISSUE THREAD

**Issue by casainho** [giuspen/cherrytree#193]
As a user I would like to open a few instances of cherrytree because I use a few different files / notebooks.
I am using Linux Ubuntu and seems to not be possible to have more than 1 instance open.

I am new to cherrytree and it is amazing compared to the other OpenSource alternatives - thank you for what was accomplished!!!
I am a user of OneNote but at home I really prefer to use OpenSource.

**Comment by giuspen** [comment]
you can have as many instances as you wish. just click the top menu file--new instance

**Comment by casainho** [comment]
Thanks. Will do that next time.
