### ISSUE TITLE
Russian spelling dictionary does not work

### ISSUE THREAD

**Issue by Sudneko** [giuspen/cherrytree#1932]
**Version, Operative system**
Сherrytree_0.99.44.0 Windows 10 x64
Сherrytree_0.99.45.0 Windows 10 x64

**Describe the bug**
Since version 0.99.44.0, the russian spelling dictionary has stopped working. There was a similar error a couple of versions ago, please fix it.

**To Reproduce**
1. Copy the text and paste it into your note.
"Детройт, 2038 год. Технологии развились до такой степени, что человекообразные андроиды встречаются на каждом шагу"
2. Click on Tools >> Enable\disable spell check
3. choose a Russian language in dictionary
![121212](https://user-images.githubusercontent.com/7460703/149673285-77f309ba-17b4-4143-97dc-bba87f85a3db.JPG)

**Comment by lua-rocks** [comment]
I'm using 0.99.45 and it works fine.

![screenshot](https://user-images.githubusercontent.com/82697845/150587229-4d8f2252-21f6-4a74-9019-1ffe38e159b6.png)

**Comment by Sudneko** [comment]
> I'm using 0.99.45 on Xubuntu and it works fine.

I'm glad to hear that at least somewhere there is no such error. Let's wait for a solution to the problem under Windows 10

**Comment by Sudneko** [comment]
Today I finally understood how to partially solve this problem. In short, the reason for the non-working dictionary is that there are Cyrillic characters in the path to the program folder. 
Just an example:
1. C:\папка\cherrytree_0.99.45.0
![RU](https://user-images.githubusercontent.com/7460703/151710046-bc32652a-cfab-4925-9d05-1dada9a735e4.PNG)

2. C:\folder\cherrytree_0.99.45.0
![EN](https://user-images.githubusercontent.com/7460703/151710048-368cf5d0-36f0-4e39-a89b-824e21365560.PNG)

**Comment by lua-rocks** [comment]
On linux it still works fine.

![screenshot](https://user-images.githubusercontent.com/82697845/151711408-a58bbaf4-dbbd-404d-9ebd-d3691a3bfdd1.png)

**Comment by ciranus** [comment]
@Sudneko 
I don't know windows at all, but for info, what is the default character encoding of your windows installation ?
UTF-8 ? windows-1251 ? anything else ?
[Character Encoding Recommendation for Languages](https://scratchpad.fandom.com/wiki/Character_Encoding_Recommendation_for_Languages)

**Comment by Sudneko** [comment]
> what is the default character encoding of your windows installation ?

Apparently windows-1251

**Comment by ciranus** [comment]
If someone familiar with windows knows how to confirm, It would be better to be sure.
Always difficult with windows to identify simple commands.
I had in mind that windows was installed with UTF-8 by default.

And do you know where are stored your dictionaries ?

**Comment by ciranus** [comment]
As I don't see any benefit at using specific 'windows-xyz' font encoding, I am convinced everything specific windows should be avoided when just adding complexity.
Never seen any problem with UTF-8.
If you consider this is solved, you can close this issue.
