### ISSUE TITLE
Copying from codebox problem

### ISSUE THREAD

**Issue by AGenuZ** [giuspen/cherrytree#1934]
**Windows, Cherrytree 0.99.45**

There is a bug, when copy&paste **a selection** from codebox. It captures next excess symbol and append a several spaces at begining.

Here's screenshots for understanding:
![image](https://user-images.githubusercontent.com/85378254/149755063-0b923b7d-d9be-4f1e-9fb6-cf4c0f50d43a.png)
![image](https://user-images.githubusercontent.com/85378254/149755263-949bea63-69a5-438f-8fd5-22af450ec3dc.png)

**Comment by giuspen** [comment]
Thanks will be fixed in 0.99.46
