### ISSUE TITLE
Strip Trailing Spaces

### ISSUE THREAD

**Issue by godylockz** [giuspen/cherrytree#1935]
"Strip Trailing Spaces" was moved out of the right-click menu options. Any chance that can be added back OR a new feature be added to strip trailing/leading spaces on paste?

**Comment by giuspen** [comment]
"Strip Trailing Spaces" is missing from the right click menu only for the rich text, you can find it for code and codeboxes. Isn't it for code that we need it?

**Comment by godylockz** [comment]
@giuspen I usually use it for both cases. But mostly due to the pasting from outside sources into cherrytree and it has whitespace.

**Comment by giuspen** [comment]
So you would like the rich text right click to also have the strip trailing spaces?

**Comment by godylockz** [comment]
Yes please 👍

**Comment by giuspen** [comment]
ok will be in 0.99.46
