### ISSUE TITLE
You Have No Write Access to E:\

### ISSUE THREAD

**Issue by glimmerwell** [giuspen/cherrytree#1936]
**CherryTree 0.99.45, Windows 10 LTSC 2021, Windows 7 Pro**

**Describe the bug**
Sorry, I could find no forum to discuss this issue. I am dual booting Windows 10 LTSC 2021 and Windows 7 Pro. Both O/S's have access to the same extra harddrive, E:\. I am trying to use CherryTree in each O/S, but sharing the same CherryTree file. If I create and use a CherryTree file in Win7, then try to later use that same file when I boot into Win 10, Win10 can read the file, but not write to it. The same thing happens if I start in Win10, then try to write to that file in Win7. Notepad++ can read and write to the same files both ways. The drive is fine.

I get the following error message:

   You Have No Write Access to E:\

I am using SQLite, Password Protected (.ctx) CherryTree files.

BTW, CherryTree is a great program. I love it! Thanks for it!

**Comment by glimmerwell** [comment]
I tried using CherryTree as portable. Still have problem.

**Comment by glimmerwell** [comment]
Thanks you so much for your help! Yes, to anyone else with this issue:

Its totally a file share/permissions thing. It was weird because most other software did not have this issue. I had to mess with folder properties sharing/file permission stuff in both W7 and W10. I was able to config it to do what I want: access the same CherryTree file from both versions of Windows. And that is cool!

Again, CherryTree is a fantastic piece of software. I only wish there was a CherryTree forum so users could help each other. Thank you so much! You can close this "issue" now if you want.

**Comment by ciranus** [comment]
> It was weird because most other software did not have this issue.

This is not related to the software you use, but to the **folder** you want to write something in.
By default, the file will take the R/W permission of the folder.
The R/W permission of a partition or folder will be different from the operating system it has been created/configured, and an other one (seen as something foreign/external).
Only FAT partition formatting would totally avoid this permission configuration.
You can close this issue.

**Comment by glimmerwell** [comment]
The e:\ drive is formatted as NTFS. 

In this situation I had the CT file and a Notepad++ .txt file, both created in W7, living in the same folder on the e:\ drive. The Notepad++ file allowed read/write access from W10, but the CT file did not. That is why I at first thought it might be a CT thing, but of course it wasn't, and also why I at first did not suspect that this was a permissions issue. So I am still confused about that, even though the issue is solved. 

Thanks so much for the extra time and patience!
