### ISSUE TITLE
Receiving messages about the wrong locale when using Russian interface.

### ISSUE THREAD

**Issue by lua-rocks** [giuspen/cherrytree#1937]
**Version, Operative system**

```
                          ./+o+-       luarocks@MAINFRAME
                  yyyyy- -yyyyyy+      OS: Ubuntu 20.04 focal
               ://+//////-yyyyyyo      Kernel: x86_64 Linux 5.4.0-96-generic
           .++ .:/++++++/-.+sss/`      Uptime: 6h 41m
         .:++o:  /++++++++/:--:/-      Packages: 2163
        o:+o+:++.`..```.-/oo+++++/     Shell: fish 3.3.1
       .:+o:+o/.          `+sssoo+/    Resolution: 1280x720
  .++/+:+oo+o:`             /sssooo.   DE: Xfce
 /+++//+:`oo+o               /::--:.   WM: Xfwm4
 \+/+o+++`o++o               ++////.   WM Theme: Greybird
  .++.o+++oo+:`             /dddhhh.   GTK Theme: Greybird [GTK2]
       .+.o+oo:.          `oddhhhh+    Icon Theme: elementary-xfce-darker
        \+.++o+o``-````.:ohdhhhhh+     Font: Noto Sans 11
         `:o+++ `ohhhhhhhhyo++os:      Disk: 126G / 456G (29%)
           .o:`.syhhhhhhh/.oo++o`      CPU: AMD Phenom II X4 945 @ 4x 3GHz
               /osyyyyyyo++ooo+++/     GPU: GeForce GTX 465
                   ````` +oo+++o\:     RAM: 1234MiB / 3930MiB
                          `oo++.    
```

**Describe the bug**

Receiving messages about the wrong locale when using Russian interface.

The bug does not depend on the layout and has partial relation to #1886.

**To Reproduce**

1. Go to 'File > Preferences > Preferences > Miscellaneous'
2. Select Russian language and close cherrytree
3. Run from terminal `cherrytree`
4. See warning:
```
** Message: 20:50:02.811: Language overwrite = ru (localedir = /usr/share/locale)

(process:21797): Gtk-WARNING **: 20:50:02.813: Locale not supported by C library.
	Using the fallback 'C' locale.
```
5. Create any code block in your document and run it
6. See warning: `/bin/bash: warning: setlocale: LC_ALL: cannot change locale (ru.UTF-8)`

I'm no expert in this, but it seems to me that locale should be called "ru_RU.utf8" instead of "ru.UTF-8".

**Comment by lua-rocks** [comment]
@ciranus 
```
> locale
LANG=en_US.UTF-8
LANGUAGE=en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=en_US.UTF-8
LC_TIME=en_US.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=en_US.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=en_US.UTF-8
LC_NAME=en_US.UTF-8
LC_ADDRESS=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
LC_ALL=

> env |grep LANG
LANGUAGE=en
LANG=en_US.UTF-8
GDM_LANG=en

> cat ~/.config/cherrytree/lang
default⏎
```

**Comment by ciranus** [comment]
Can you try this:
`LANG=ru_RU.UTF-8 ; cherrytree`

**Comment by lua-rocks** [comment]
![screenshot](https://user-images.githubusercontent.com/82697845/150866546-920567e1-05de-42ae-9691-08b70ecc6367.png)

**Comment by ciranus** [comment]
~/.config/cherrytree/lang should be empty for this test (= default).
Do you confirm ?
If yes, where '`Language overwrite = ru`' can come from ????

**Comment by lua-rocks** [comment]
Yes. When its "default" or "en", I don't get this message. It shows only when lang is "ru".

**Comment by lua-rocks** [comment]
I use English interface by default because I don't want cherrytree to crash when I working with code blocks. But for the test I just switched it to Russian.

**Comment by ciranus** [comment]
I know I had difficulty with the CT lang setting (not working for me / I didn't report because found a workaround)
This is why I use LANG=xxxx prefix when needed.

Now why it does not work for ru , I don't know.
Did you install `localepurge` package ?

**Comment by lua-rocks** [comment]
No, I don't know what it is.

**Comment by ciranus** [comment]
```
grep ru /etc/locale.gen

 ru_RU ISO-8859-5
 ru_RU.CP1251 CP1251
 ru_RU.KOI8-R KOI8-R
 ru_RU.UTF-8 UTF-8
 ru_UA KOI8-U
 ru_UA.UTF-8 UTF-8
```
**ru_RU.UTF-8** is technically available at system level.
To be further investigated.

**Comment by lua-rocks** [comment]
Yes, my output is exactly the same (only in a different order). Does this message appear on your system if you switch to Russian?

**Comment by ciranus** [comment]
Problem with russian is confirmed.
Don't clearly understand this:
`Locale not supported by C library.`

**Comment by ciranus** [comment]
Can you try to reconfigure locales, not only for `en_US.UTF-8`, but add `ru_RU.UTF-8`

`sudo dpkg-reconfigure locales`

->> a reboot is very likely necessary to see if any change.

**Comment by lua-rocks** [comment]
I just recently installed `locales-all` package and reconfigured everything. That didn't help.

**Comment by lua-rocks** [comment]
But ok, I'll try again, one moment...

**Comment by lua-rocks** [comment]
Nope 🙄

**Comment by ciranus** [comment]
Then help needed from @giuspen for problem confirmation, or solution.

**Comment by lua-rocks** [comment]
@ciranus Thank you for your help and thanks for confirmed this bug.

**Comment by ciranus** [comment]
You're welcome.
`Locale not supported by C library`  is an old and very common linux issue, but not that easy......

**Comment by ciranus** [comment]
Some news...

> it seems to me that locale should be called "ru_RU.utf8" instead of "ru.UTF-8"

The two letters are for /usr/share/locale/**xy**/
`find /usr/share/locale/ -name 'cherrytree*'`

The good news is your problem is not specific to russian, but for all languages in your specific configuration.

Your specificity is that you want russian UI with default en_US.UTF-8 system configuration.
Please check, but I don't think you can select german, french, italian UI.

If I know this problem, it is because I opened an issued in May 2021, and closed it (low priority at that time).
[[linux] locale LANG/LANGUAGE system variable · Issue #1667 ](https://github.com/giuspen/cherrytree/issues/1667)

> I use English interface by default because I don't want cherrytree to crash when I working with code blocks.

I should have paid more attention to this one.
Can you attach a file to reproduce this ?

**Comment by lua-rocks** [comment]
> Please check you have this file `/usr/share/locale/ru/LC_MESSAGES/cherrytree.mo`

Yes, I have it.

> ... I should have paid more attention to this one ...

If I knew exactly how to reproduce this crash, I would definitely create an issue, but I don't. This happens relatively rarely.

![screenshot](https://user-images.githubusercontent.com/82697845/151086759-7119240e-f8d9-4200-bb1a-82859fefead6.png)

The translation in your screenshot is more complete 🤔

![screenshot](https://user-images.githubusercontent.com/82697845/151086977-3c44814d-041c-478f-a9a1-8ec6b5e2a75c.png)

**Comment by ciranus** [comment]
>Describe the bug :
Receiving messages about the wrong locale when using Russian interface.

Then to summarize, your real problem was not that can't get russian UI at all, but that it was only partial right ?

I see you use CT 0.99.45. There are some doubts currently under investigation.
Can you try to downgrade to 0.99.4**3** and compare.

```
cd /tmp
wget http://hr.archive.ubuntu.com/ubuntu/pool/universe/c/cherrytree/cherrytree_0.99.43+dfsg-1build1_amd64.deb
sudo dpkg -i ./cherrytree_0.99.43+dfsg-1build1_amd64.deb
```

**Comment by lua-rocks** [comment]
I just reported the error. I didn't have any special problems because of it, unless the rare crashes when I used code blocks. I have no complaints about the interface itself. Why do I have to downgrade?

**Comment by ciranus** [comment]
I don't say _you have to_ downgrade, but it would help as a test to understand if you have specific UI regression with 0.99.45.
I currently use 0.99.43 in Debian with no russian UI problem.
Unfortunately, I can't find 0.99.43 package in ppa compliant with focal.
Well, if too boring, wait some days so that 0.99.45 is clarified.

**Comment by lua-rocks** [comment]
If that's what you're doing now, I'd be happy to help you and do a downgrade. But in general I don't want to bother you with it. An incomplete translation is nothing for me personally.

**Comment by lua-rocks** [comment]
Yes, I confirm that the translation in this version is better.

**Comment by ciranus** [comment]
Ok, then seems to be a 0.99.45 regression (that you can reinstall if you want).
In summary, if your issue was **only** some console warning messages with **no** real consequence for you, I would recommend to not worry, and close this issue !

**Comment by lua-rocks** [comment]
> I don't say you _have to_ downgrade

@ciranus That's was actually a very common and funny mistake, sorry for that. In Russian we don't have so many different forms of "you have to", "you would to", "you got to", "you should", "you need", "you must" etc :D
