### ISSUE TITLE
Table column width

### ISSUE THREAD

**Issue by monteleo1** [giuspen/cherrytree#1942]
I'm using CT in kubuntu 21.10. 

The shortcut to increase a table column width (Ctrl+.) does not work for me. I have a underlined "e" instead.

I see also that increase/decrease column width are not available in the toolbar

**Comment by ciranus** [comment]
Works for me in KDE.
You have 2 dot keys: one for numeric pad, and the other combined with letters.
I had some time ago problem with the dot from numpad. Works now.

Did you try both ?

**Comment by MJimitater** [comment]
Way to go @ciranus , thanks for tracking down so many issues 🚀

**Comment by monteleo1** [comment]
I tried both, the one in numeric pad does not work, the other one print "*e*"
and cancel it if I do Ctrl+. again

**Comment by ciranus** [comment]
Are you sure your keyboard is correctly configured ?
Which CT version ??

**Comment by monteleo1** [comment]
I have a Logitech K545 configured as Generic 105-KeyPC (intl.).
All the other shortcuts I usually use are fine.

**Comment by ciranus** [comment]
I mean which cherrytree version ?
and do you confirm you get a dot in a text editor.

**Comment by monteleo1** [comment]
I'm using the latest CT version (0.99.45).
Yes, I have dot in the text editor.
The keyboard layout is correct, I get all the keyboard keys all in a text
editor (e.g. kwrite or kate).

**Comment by ciranus** [comment]
Then I see 2 possibilities:

1 - corrupted ~/.config/cherrytree/config.cfg (shortcuts have been changed for any reason)
-> try with a new one

2 - possible 0.99.45 regression 
-> try cherrytree 0.99.40+dfsg-1 from [Ubuntu – cherrytree dans impish](https://packages.ubuntu.com/impish/cherrytree)

ps: I don't use 0.99.45, but 0.99.43.

**Comment by giuspen** [comment]
I also see this annoying issue with 21.10, there's an issue about it https://askubuntu.com/questions/1372781/new-ctrl-period-key-sequence-default-in-21-10 it is a new default desktop keyboard shortcut. I'll have a thought about what to do

**Comment by giuspen** [comment]
I'm forced to change the keyboard shortcut, I'm proposing the use of backslash key instead of period unless clashes will be detected before the next release

**Comment by PranavBhattarai** [comment]
> I'm proposing the use of backslash key instead of period

Ok, that sounds fine.
Also, let the users define the shortkey value for this shortkey _or any shortkey if we have that functionality._
