### ISSUE TITLE
Ctrl + Alt Shortcuts Not Interpreted Correctly

### ISSUE THREAD

**Issue by arensonzz** [giuspen/cherrytree#1944]
**Version, Operative system**
Cherrytree 0.99.45 Windows 21H2

**Describe the bug**
I recently updated Cherrytree from 0.99.43 to 0.99.45. I use Turkish Qwerty keyboard which has special AltGr key that is registered as `Ctrl + Alt`. Some of the keys like "1" in keyboard prints special characters when holding down `Ctrl + Alt`.  In new version when I press `Ctrl + Alt + 1`, app registers that special character instead of the shortcut to bulleted list. This issue was not happening in 0.99.43. `Ctrl + Alt` shortcuts that have no special character assigned to them like `Ctrl + Alt + P` works fine.

**To Reproduce**
1. Switch to Turkish Q keyboard
2. Press `Ctrl + Alt + 1`  inside a Cherrytree node
3. You should see ">" character printed on the screen instead of bulleted list

**Comment by dardoor** [comment]
I can confirm this, even though I'm using a different language keyboard.
Previously I could use Ctrl+Alt for shortcuts and AltGr for special characters. But now CherryTree treats Ctrl+Alt the same as AltGr and shortcuts no longer work.

**Comment by Limag** [comment]
Same here on Windows 10, 20H2, German keyboard.
CherryTree 0.99.46.

The Key CTRL+ALT+M doesn't inserts a timestamp.  It just inserts a "µ".  This letter is usually to find on ALT-GR + M

Older versions of CherryTree worked well.

**Comment by giuspen** [comment]
Raised ticket https://gitlab.gnome.org/GNOME/gtk/-/issues/5231

**Comment by giuspen** [comment]
In upcoming v1.0.3 there won't be anymore any default keyboard shortcuts with Ctrl+Alt
