### ISSUE TITLE
Print problem with Ubuntu?  Every print job after first one disappears ....

### ISSUE THREAD

**Issue by burundian20** [giuspen/cherrytree#1947]
Hi.. Am using Ubuntu 20.04.3 LTS.  Maybe it is just my computer (I have messed with it so much) but only the first print job from CherryTree makes it to the printer ... all seccessive print jobs disappear into a black hole somewhere and do not even show up in the printer queue.  I have to log out and then back in to Ubuntu in order to get the printer working again.  I only seem to have this problem with CherryTree though ....       (I love CherryTree by the way!!)

**Comment by ciranus** [comment]
> Maybe it is just my computer (I have messed with it so much)

Who knows....
Is you printer correctly working with any other applications than Cherrytree ?

**Comment by burundian20** [comment]
Yes ... it does for the most part.  Since I emailed you I have discovered a
workaround ... which I can live with.

The workaround is when I print (after the first time) a generic
ubuntu-generated message appears at the top of the screen.  If I click on
it it opens a printer window listing different printers.  If I then click
the print button on that window it prints !  (and if it doesn't all I need
do is click the other printer and then back onto my main printer and click
the print button).

So .... if too problematic then that's ok.  I can easily live with the
work-around.  After googling printing problems (HP Laser Jet) I noticed
that people on WIndows and Mac have had similar issues.  So maybe not
CherryTree ... but I don't have much trouble with any other app.  Only
occasionally.

It;s ok ..      I LOVE CHERR TREE.  I went through a WHOLE LIST of
Note-taking apps and yours just NAILS it for me !!   I love it !!     I
hope you guys get some success from your efforts.

**Comment by ciranus** [comment]
> ubuntu-generated message

Ubuntu messages related to cups/printing should preferably be first treated with Ubuntu.
I don't see any cherrytree issue here.
You should close this issue, unless you are able to confirm a specific cherrytree issue.
