### ISSUE TITLE
Increase file size attachment limit

### ISSUE THREAD

**Issue by casainho** [giuspen/cherrytree#195]
File attachment is great!! I use a lot everyday professionally on OneNote.

Please increase the file size attachment limit or make it as a configuration value.

**Comment by giuspen** [comment]
you can edit, in config.cfg, "embfile_max_size = 10" at your own risk

**Comment by casainho** [comment]
Thanks!!!

**Comment by casainho** [comment]
Forgot to say that I am using now 100MBytes limit and had no problem for now.

**Comment by giuspen** [comment]
Cheers
