### ISSUE TITLE
Background color for rich text

### ISSUE THREAD

**Issue by RuslanSel** [giuspen/cherrytree#1953]
How to set background color for rich text?
Thanks in advance.

**Comment by ciranus** [comment]
[Cherrytree - Text Color Background](https://giuspen.com/cherrytreemanual/#_formatting)

**Comment by ciranus** [comment]
[Cherrytree - Theme / Custom Background and Text](https://giuspen.com/cherrytreemanual/#rich-text-pref)

**Comment by RuslanSel** [comment]
Thanks.
