### ISSUE TITLE
Export with --password option

### ISSUE THREAD

**Issue by tracezet** [giuspen/cherrytree#1965]
It would be very cool to be able to do export like this: 
`cherrytree ~/cherrytree.ctx -t ~/sync/ -w --password $cherrypass`

It would be possible to do synchronization for example through syncthing, nextcloud and others, for devices where it is not possible to run cherrytree.

I can do the export without adding the --password option, it's not pretty, but works with this:
`7z x -ppassword cherrytree.ctx && cherrytree cherrytree.ctb -t ~/sync/`
But that command will not export if cherrytree is already running :(

**Comment by giuspen** [comment]
ok will be in upcoming 0.99.46

**Comment by tracezet** [comment]
> ok will be in upcoming 0.99.46

thanks a lot for the password option but I can't do export when the cherrytree is already running
maybe there is some way to run the export without a GUI?

**Comment by ciranus** [comment]
Problem confirmed:
`--password` option does not work if CT is already active.

**Comment by tracezet** [comment]
I think the --password option has nothing to do with it,  export without  --password behaves the same way if the СT was active before the command was run

Here it would be necessary to cancel the check (or how it works) for the availability of a GUI or move the export to a separate module so that it can be run by a script on a server or with an already running cherrytree

**Comment by giuspen** [comment]
If you pull the latest from git and build from sources, you will find an additional command line option -S/--secondary_session which allows to run in isolation from a possibly already running main instance

**Comment by tracezet** [comment]
> If you pull the latest from git and build from sources, you will find an additional command line option -S/--secondary_session which allows to run in isolation from a possibly already running main instance

thanks a lot
I have been using cherry for about 10 years, this is the best program for me. thank you for it!

**Comment by ciranus** [comment]
Just for info (non issue  for me), don't know if it behaves as expected by tracezet, but it does not work for me

`cherrytree -p ******* --secondary_session confid.ctz`

`--secondary_session` does not change anything.

**Comment by tracezet** [comment]
`cherrytree -S -P $cherypass cherrytree.ctx -t /sync/`
I'm using this command - works without error

**Comment by ciranus** [comment]
'`-t /sync/`' should be explained more explicitly somewhere. Not obvious to me.
However, still does not work.
I then conclude: not compatible with file.**ctz**

**Comment by tracezet** [comment]
> '`-t /sync/`' should be explained more explicitly somewhere. Not obvious to me.
> However, still does not work.
> I then conclude: not compatible with file.**ctz**
'-t /sync/' is export to text files 
`cherrytree -S -P test ct.ctz -t /tmp/` works
`cherrytree -S -P test ct.ctz` works

git clone https://github.com/giuspen/cherrytree.git you did it?

**Comment by ciranus** [comment]
if everything works as you confirm in your tests, my bad.
Latest `ct_app.cc ct_app.h`  concerned by this change.
Then needs to check and again.
Sorry.

**Comment by tracezet** [comment]
> if everything works as you confirm in your tests, my bad.
> Latest `ct_app.cc ct_app.h` concerned by this change.
> Then needs to check again and again.
> Sorry.

no problem, at least I checked other options ))
