### ISSUE TITLE
bug: Changing a node type loses codebox content in Ubuntu

### ISSUE THREAD

**Issue by jarickkk** [giuspen/cherrytree#198]
**CherryTree 0.37.6, Ubuntu 16.04.1 LTS, x64**
I have a rich text node with a codebox inside.
![step1](https://cloud.githubusercontent.com/assets/18553297/19856263/2c6d2dc4-9f92-11e6-9c61-bc202079bc20.png)
Then I change a node type to plain text or code. The codebox is transfered into new node type without problems.
![step2](https://cloud.githubusercontent.com/assets/18553297/19856280/4062a692-9f92-11e6-9de3-722b40dccafd.png)
If I leave this node and come back again (without closing database) I will see no change of the node type (it's rich text again)
![step3](https://cloud.githubusercontent.com/assets/18553297/19856337/7682ee30-9f92-11e6-9257-453437d56a1c.png)
If I save database and reopen it I will see this node as plain text, but without content from the codebox.
![step4](https://cloud.githubusercontent.com/assets/18553297/19856412/bddded16-9f92-11e6-88fb-2bc9c51551af.png)

**Comment by burningalchemist** [comment]
Reproducable.

**Comment by giuspen** [comment]
I should have fixed this problem with latest commit https://github.com/giuspen/cherrytree/commit/ecb30c9cdf62bdddb5de03c379c3fbb41ac431d6 please see if it works for you
