### ISSUE TITLE
[Question] How do I change the background color and text color of a selected node in the tree?

### ISSUE THREAD

**Issue by SonofaNoob** [giuspen/cherrytree#1986]
![Question](https://user-images.githubusercontent.com/75463665/156944552-5d70b23d-7e1e-42bd-be67-26fcefbe89b4.png)

I've been trying different things in the Preferences > Theme tag, but nothing seems to be working.  I have no idea what I am doing.

**Comment by idgas01** [comment]
UPDATE: I think that I am getting used to the default background color and white text color.  So it's not that important anymore.  But instead of closing this, I would like to keep it open because maybe there is a way to change it and it wouldn't hurt to know.  Thank you.

**Comment by SonofaNoob** [comment]
I am closing this ticket because your program is ridiculously slow and laggy and I found a better one called AllMyNotes.
