### ISSUE TITLE
[Question] Is there a way to increase the padding or space between a node and a node icon?  Also, custom icons?

### ISSUE THREAD

**Issue by SonofaNoob** [giuspen/cherrytree#1987]
I am using the gold star on some important nodes that I will be editing and reading a lot.  But the icon is really close to the node name.  I wish that there was a gap or space in between.  I'd like to define the number of pixels or whatever between the icon and the node name.  Is there a way to do that?

Also, could the program be made so that we can use custom icons?  I love creating and using icons, usually for my taskbar.  And it would be nice to be able to do that in this program too.

**Comment by iNoSec2** [comment]
For the space and it is a way i use to workaround, just put space at the start of the node name

**Comment by idgas01** [comment]
That doesn't work.  At least not normal keyboard spaces.  I could put 20 spaces and it would reset to 0 spaces before the name.  It might work with like whitespace character or something, but I don't really want to use nonstandard characters or add spaces to everything.  A padding adjuster would be better.
