### ISSUE TITLE
Search is very very slow on searching 4000 subnodes/nodes with text has been added

### ISSUE THREAD

**Issue by goodev2021** [giuspen/cherrytree#2019]
Hi,

I have imported 4000 text files- each one of 250 kb which comes around 1GB of text content

Searching for a keyword in the entire node takes several minutes.

Is it possible to fetch up the first 10 or 100 results in less than a second and do some pagination if possible.

Thanks

**Comment by datavectors** [comment]
I would try [ripgrep](https://github.com/BurntSushi/ripgrep/releases) as an external supplementary search tool.

**Comment by giuspen** [comment]
I improved the speed of searching/replacing with 'all matches' option, but I still need to decide something about the case where the all matches dialog is then populated by a huge number of results.
A user sent me privately a test cherrytree that has so many hits that at the time of populating the all matches dialog it crashes.
I'll do a pagination inside of the dialog with a maximum number of items per page and load only one page at a time, this should fix the issue. I'll update here on the status.

**Comment by giuspen** [comment]
I completed the implementation of multi pages support in the all matches dialog with a limit of 50 and I believe the result is pretty good so closing this ticket for now, I'll probably issue a new version 1.0.2 in the next few days

**Comment by giuspen** [comment]
Thanks for the feedback @LucasSchelkes-BA ;)
