### ISSUE TITLE
Invisible characters in pasted code from RTF Node

### ISSUE THREAD

**Issue by rgucluer** [giuspen/cherrytree#202]
Invisible characters are added to copied text in a certain senario:

1. Copy text **from a code box** from a web page:
    [http://php.net/manual/en/function.htmlspecialchars-decode.php](http://php.net/manual/en/function.htmlspecialchars-decode.php)
   ﻿Example # 1 A htmlspecialchars_decode() example
   `echo htmlspecialchars_decode($str,ENT_NOQUOTES);`
2. Paste code into a Cherrytree **RTF node**

3. Copy code from RTF node , paste it into your editor

In this situation I got an php error 

> Fatal error: Call to undefined function ﻿echo htmlspecialchars_decode()

if I delete invisible characters doesn't have the error.
invisible characters:

1. left of echo  0xEFBBBF (U+FEFF)
2. right of echo 0xC2A0 (U+00A0)
3. left of ENT_NOQUOTES 0xC2A0 (U+00A0)

- If I paste the code into a Cherrytree codebox , and copy that text to my code editor there is no invisible character.
- If I paste the code directly to my code editor, there is no invisible character.
- I use Atom editor. To find the invisible characters , I used ﻿highlight-bad-chars Atom package https://atom.io/packages/highlight-bad-chars

**Comment by giuspen** [comment]
I should have fixed this problem, could you please test the current git
master HEAD?

**Comment by rgucluer** [comment]
Thank you for your response. I tried, 2nd and 3rd invisible characters are fixed. They are normal now. 
First invisible character (U+FEFF) sometimes appear left of "echo" .
When I select the row with mouse click+drag; invisible character appears
When I click end of the row and select with SHIFT+HOME then copy; invisible character does not appear.

As a work around we can use:
- pasting into Cherrytree with CTRL+SHIFT+V (Paste as plain text)
- or pasting code always in a code box

**Comment by giuspen** [comment]
Could you please try now the current git master HEAD?

**Comment by rgucluer** [comment]
It's OK. Paste without any invisible characters. Thank you for your attention. Keep up this good work.
