### ISSUE TITLE
Requesting an official Appimage release for Cherrytree

### ISSUE THREAD

**Issue by keyboard-penman** [giuspen/cherrytree#2025]
Cherrytree is one of the pieces of software that I prolifically use. I recently made the permanent change from Windows to Linux. Things like Installing, removing and re-installing a different version of Cherrytree, works like a charm on Windows machines. Simply because the author provides a self contained installer.

While I don't really have a prohibitive problem against typing out `sudo add-apt-repository ppa:giuspen/ppa / sudo apt install cherrytree` (that's what I currently have, I tried the snap version first but it's not an official release and lags behind the Developer's release by a year), an Appimage (or even a self contained binary tarball) would make things so much more neater, quicker and modular. Even for a Linux newbie who just wants to get his favorite hierarchical note taking app up and running ASAP. And perhaps even make life of people seeing to it's distribution easier too (instead of the mess of different distribution methods there is now).

I really don't wish to sound like I want people to conform to my way of doing things, but this is merely a request, for the Developer to at least consider the idea and I only ask because Cherrytree to me is such an awesome piece of software, one that proves indispensable to all sorts of people, including yours truly. Thanks.

**Comment by thwerks** [comment]
Count my vote for this. Running Cherrytree on Debian/MX Linux/ LMDE is a pretty disappointing experience. Package dependencies can never be met so your always stuck with an old version of Cherrytree always wondering if your issues have been resolved already; new features hopelessly out of reach. I dont use Ubuntu and I never will; flatpak and snaps are gimmick. The only real solution is Appimage in my opinion. Please please make this happen

**Comment by ciranus** [comment]
> Running Cherrytree on Debian/MX Linux/ LMDE is a pretty disappointing experience. Package dependencies can never be met so your always stuck with an old version of Cherrytree 

Can you try this for investigation:
[[debian][all][amd64] CT 0.99.**46** deb package](https://github.com/giuspen/cherrytree/issues/1980)

**Comment by giuspen** [comment]
I will give it a try in the next days

**Comment by ciranus** [comment]
Hope you and family are as fine as possible in this WW complicated period of time.
I am preparing a generic 0.99.47 update which will solve the spdlog/libfmt dependency issue for Debian/Ubuntu derivatives.

**Comment by keyboard-penman** [comment]
> I will give it a try in the next days

Thanks

**Comment by giuspen** [comment]
It's almost done, It's about 90 MB in size.
This is excluding the latex binaries required to render the LatexBox though, which would need to be installed separately for the LatexBox to work.
Bundling all together would increase the file of about 70 MB.
I'm unsure if better to just bundle it all together and make it 160 MB or keep it light.

**Comment by keyboard-penman** [comment]
> It's almost done, It's about 90 MB in size. This is excluding the latex binaries required to render the LatexBox though, which would need to be installed separately for the LatexBox to work. Bundling all together would increase the file of about 70 MB. I'm unsure if better to just bundle it all together and make it 160 MB or keep it light.

160 MB seems doesn't seem bad.

**Comment by giuspen** [comment]
Can you download and try the test appimage called 0.99.47.1 built on the current git code https://www.giuspen.com/software/CherryTree-0.99.47.1-x86_64.AppImage and report how it goes?

**Comment by ttffm** [comment]
> Can you download and try the test appimage called 0.99.47.1 built on the current git code https://www.giuspen.com/software/CherryTree-0.99.47.1-x86_64.AppImage and report how it goes?

I downloaded it, made it executable, but it didn't do anything when I tried to open it.

**Comment by thwerks** [comment]
> Can you download and try the test appimage called 0.99.47.1 built on the current git code https://www.giuspen.com/software/CherryTree-0.99.47.1-x86_64.AppImage and report how it goes?

i tried compiling 0.99.47 on Debian 11 and it compiles fine. I had to make the binary executable and rename the file to .appimage and it worked perfectly. copied to other debian systems and it works just fine.

**Comment by thwerks** [comment]
> Can you download and try the test appimage called 0.99.47.1 built on the current git code https://www.giuspen.com/software/CherryTree-0.99.47.1-x86_64.AppImage and report how it goes?

when i run your appimage in terminal it has errors:

/tmp/.mount_Cherryh6llpC/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.mount_Cherryh6llpC/AppRun.wrapped) 

But when i compile the latest Cherrytrtee 0.99.47 following the directions for Debian, it works fine on my Debian 11 and LMDE 5 installations. 

Though the source compiles and binary runs fine by launching from terminal; i could not get it to load in Cinnamon by double clicking on it. I had to rename the file ./build/cherrytree file to cherrytree.appimage, after that it could load by double clicking on it. Im not sure if this issue is related to Cinnamon/Nemo alone or if other DEs/File Managers might have an issue as well. File manager (Nemo) identifies the cherrytree built bin file as a "shared library" and not as the typical "program" file type. But by changing the extension to .appimage, the file manager then identifies the file as a "program" and it launches when double clicking on it.

**Comment by ciranus** [comment]
> Cherrytree on Debian/MX Linux/ LMDE is a pretty disappointing experience. Package dependencies can never be met

Because you try to use ubuntu **ppa** builds.
I agree it's really hard to identify which ppa package is compatible with Debian. 

If you have time, I would be really interested to get feedback on CT Debian builds in [this thead](https://github.com/giuspen/cherrytree/issues/2025#issuecomment-1105988853) to clarify what is so specific in your distribution derivatives.
You just have to know if your derivative is Debian **stable** or **testing** compatible.

**Comment by giuspen** [comment]
Thanks to all that tried the first appimage and reported the results. I was thinking I was there but I will need to do more testing with different and older distributions.

**Comment by keyboard-penman** [comment]
> Can you download and try the test appimage called 0.99.47.1 built on the current git code https://www.giuspen.com/software/CherryTree-0.99.47.1-x86_64.AppImage and report how it goes?

I'm seeing this post 5 days late and by this time the main cherrytree website is down again. Can't download the appimage.

**Comment by ArenT1981** [comment]
I already had a fully built/perfectly functioning Cherry Tree 0.99.47 installation on my Fedora 35 system, but I was also curious just to test out/try this AppImage, as it would be super convenient for just ensuring I have access to Cherry Tree on all of my linux systems, including old laptops/old distributions. 

Anyway, I am pleased to confirm that after downloading the file and a quick `chmod +x`, that it **works flawlessly**. I would suggest including this AppImage link in the downloads section of your main Cherry Tree website.

@giuspen Thanks for the great work on Cherry Tree. fantastic piece of software. I was further pleased to see (as a software developer) that if I open the  Cherry Tree sqlite file using sqlitebrowser, that it is perfectly intelligible/very clear to see how the file is structured/organised, which is also reassuring just in case of disaster recovery/extraction of any data, should that ever be necessary (thus far it is proven extremely stable :-) ).

**Comment by giuspen** [comment]
Thanks for the feedback @ArenT1981 I will also release an appimage of the upcoming 0.99.48

**Comment by keyboard-penman** [comment]
> Thanks for the feedback @ArenT1981 I will also release an appimage of the upcoming 0.99.48

Received the new 0.99.48 Appimage. Thanks a lot for responding to this issue. Regards.
