### ISSUE TITLE
Collapse, Expand Text Selection

### ISSUE THREAD

**Issue by ventolinmx** [giuspen/cherrytree#2026]
Hi, first of all thank you very much for Cherrytree. I use it every day to take all kinds of notes.

So i've been looking for this function on text editors for a while where the user selects a piece of text and make it collapsable or "hides" it but with an icon to expand it again. Much like some code editors have or like this function on the tree but inside each node.

Can this be possible?

**Comment by RFImages** [comment]
Strongly agree! I have been nagging about this :)
See
https://github.com/giuspen/cherrytree/issues/2026

https://github.com/giuspen/cherrytree/issues/2360

**Comment by ventolinmx** [comment]
Closing this as it is a duplicate of #2360 Sorry

**Comment by RFImages** [comment]
This does not seem to be closed
