### ISSUE TITLE
BUG: shortcut for changing parent's node doesn't work

### ISSUE THREAD

**Issue by joseluis** [giuspen/cherrytree#203]
I'm trying to setup a shortcode for "Change parent's node", but although it does appear in the menu, it doesn't respond to the keys. The rest of the shortcodes seems to work perfectly fine.

Version 0.37.6 on Linux Mint 17.3

* I've tried several shortcodes like ctrl + shift + 1, alt + 2 or F12 without any effect
* If I change the shortcode for printing (originally ctrl + p), it does work.
* If I add a new shortcode for an action without shortcode by default, (like tree node information summary), it does work

Problem seems to be specific to this action.

**Comment by giuspen** [comment]
I see the problem. I just set up a static keyboard shortcut for this action
(Ctrl+Shift+Right) in the git master HEAD, would you be able to test and
provide feedback?

**Comment by joseluis** [comment]
Sorry for the delay. I've just tested it with current master it does work for me now using CTRL + SHIFT + RIGHT.

But that option doesn't appear anymore in the Keyboard Shortcuts settings. In fact all the "Tree > Node move" actions are missing there.

**Comment by giuspen** [comment]
It is correct that the shortcuts for "Tree > Node move" are not customizable and so do not appear in the preferences dialog
