### ISSUE TITLE
在加载大文件时候会很卡，基本软件会死掉。

### ISSUE THREAD

**Issue by ai930** [giuspen/cherrytree#204]
在处理大文件的时候就会出现卡死软件界面的情况。我只是保存这个网页的内容！
http://dubbo.io/User+Guide-zh.htm

**Comment by giuspen** [comment]
Only English please

**Comment by ai930** [comment]
In dealing with large files when there will be stuck software interface situation. I just save the contents of this page!

**Comment by notmikeb** [comment]
@ai930 I think you should tell the detail of how to do it. which version of cherrytree do you use ?
does you use import from a html file or a whole html folder ?
how do you save the web's page ? it does matter in your question
