### ISSUE TITLE
The title and quick navigation became hexadecimal

### ISSUE THREAD

**Issue by VainAnts** [giuspen/cherrytree#2061]
**Version, Operative system**
Version :0.99.47;  system:Windows10 64 ;language: Chinese Simplified 

**Describe the bug**
The title and quick navigation became hexadecimal

**Screenshots**
![image](https://user-images.githubusercontent.com/9073302/174209357-be77cdcc-e867-4522-8ec1-1475a75560aa.png)

**Comment by ciranus** [comment]
Do you mean very suddenly ?
Or did you change something just before ?
