### ISSUE TITLE
Folder selection fails, file selection OK

### ISSUE THREAD

**Issue by berndspeiser** [giuspen/cherrytree#2065]
Hi, 
I have just downloaded Cherrytree version 0.99.47 through flatpak to a openSuSE Leap 15.3 (KDE) system. I have an earlier version of cherrytree (0.38.2) available.
While this works with the 0.38.2 version, I am not able to select any folders with the 0.99.47 version. For example, when trying to export to HTML, I get a file/folder menu, but when I click on a menu, the directory is opened and not selected. If I write the directory path into the "name" line, the same happens. Selecting a file for e.g. export to pdf works fine.
Similar behavior is observed for import. It works for a single text file, but not for e.g. a KeepNote folder.
Can you help me?
Thanks!
Best regards

**Comment by ciranus** [comment]
Is `xdg-desktop-portal-kde` installed ? If not, try with it.

**Comment by berndspeiser** [comment]
Yes, xdg-desktop-portal-kde is installed (version 5.18.5). 
How can I debug if it is a flatpak issue?

**Comment by ciranus** [comment]
I don't know, I have never used flatpak.
You probably need to first compare with OpenSuse CT package (maybe available somewhere), or build it.

[building-cherrytree-on-opensuse](https://github.com/giuspen/cherrytree#building-cherrytree-on-opensuse)

**Comment by berndspeiser** [comment]
There is CT version 0.38.2 in the openSuSE "standard" installation. I can't find another openSuSE build quickly. Maybe I need to do more investigation.
I could try to build myself, yes. Thank you for the suggestion.
Since I want to upgrade to openSuSE 15.4 pretty soon anyway, which has CT version 0.99.42 as standard and does not seem to have this problem (I have tested in the meantime on another machine), however, I will probably not do the extra installation on my "old" system. 
But, thanks again for helping.

**Comment by ciranus** [comment]
You are right. First upgrade to openSuSE 15.4.
You can then close this issue.

**Comment by giuspen** [comment]
As an alternative to the flatpak there is also the appimage version which is a single file you dounload and run https://www.giuspen.net/software/CherryTree-Latest-x86_64.AppImage
