### ISSUE TITLE
Keystroke, keyboard shortcut conflict and errornous behaviour when using backslash(\) on a Danish keyboard

### ISSUE THREAD

**Issue by GreyishOne** [giuspen/cherrytree#2069]
**Version, Operative system**
CherryTree 0.99.48, Windows 10 Pro 21H2

**Describe the bug**
With a Danish keyboard, backslash (\) is typed [ALT GR] + [<]. This appear to conflict with several keyboard shortcuts especially in tables and codeblocks. Because of this backslash can't be typed in codeblocks, instead it attempts to change the width of the block and the shortcuts that would change the width of a table column or width of a codeblock won't respond as intended, perhaps doing one, but not the other (appear to only want to use the increment or decrement latest used from the rightclick-menu).

**To Reproduce**
1. Use a Danish keyboard
2. Type a backslah (\) ([ALT GR] + [<] on Danish keyboard) in a codeblock
3. The codeblock width changes instead of typing a backslash

**Comment by giuspen** [comment]
In upcoming v1.0.3 there won't be anymore any default keyboard shortcuts with Ctrl+Alt
