### ISSUE TITLE
Packaging typo in latest Windows portable release

### ISSUE THREAD

**Issue by tech189** [giuspen/cherrytree#2070]
**Version, Operative system**
0.99.48.1, Windows

**Describe the bug**
The folder inside the latest portable 7z release for Windows has the wrong name. It is `cherrytree_0.99.48.0_win64_portable` when it should be `cherrytree_0.99.48.1_win64_portable` (`.0` vs `.1`). This leads to [Scoop](https://scoop.sh/) being unable to extract and install the program - https://github.com/ScoopInstaller/Extras/issues/8790. Please could you fix this typo?

**To Reproduce**
If applicable, attach a non-personal document where the issue can be reproduced systematically.
1. Download https://www.giuspen.net/software/cherrytree_0.99.48.1_win64_portable.7z
2. Unpack the file
3. See the typo in the folder name

**Comment by giuspen** [comment]
Should be ok if you download it again. The content of the bundle is the same, only the folder is now renamed correctly to 0.99.48.1.
I fixed also the installer to display 0.99.48.1.
Note that cherrytree.exe has still version 0.99.48.0 (and this caused the issue) as that never changed, it is only the bundle that had few missing files so needed a new number.

**Comment by giuspen** [comment]
Who already downloaded a file with the name 0.99.48.1 do NOT need to download again, the files were already all correct except for the portable folder name and the installer displayed version
