### ISSUE TITLE
colModes

### ISSUE THREAD

**Issue by adminka-root** [giuspen/cherrytree#2075]
After launching the cherry tree, the first text selection works correctly. The following selections have to be done 2 times. Video-recording of the event: https://drive.google.com/file/d/1A-ZXLLL7CbJmo66JjOCcFJi-Wp6_oS_0/view?usp=sharing
(I attached a link to google drive for the ability to download and watch in original quality)

`❯ inxi -b
System:    Host: adminka-X751LN Kernel: 4.15.0-180-generic x86_64 bits: 64 
           Desktop: Cinnamon 4.0.10 Distro: Linux Mint 19.1 Tessa 
Machine:   Type: Laptop System: ASUSTeK product: X751LN v: 1.0 serial: <root required> 
           Mobo: ASUSTeK model: X751LN v: 1.0 serial: <root required> 
           UEFI: American Megatrends v: X751LN.303 date: 04/18/2019 
Battery:   ID-1: BAT0 charge: 22.0 Wh condition: 22.6/37.4 Wh (60%) 
CPU:       Dual Core: Intel Core i7-4510U type: MT MCP speed: 2780 MHz min/max: 800/3100 MHz 
Graphics:  Device-1: Intel Haswell-ULT Integrated Graphics driver: i915 v: kernel 
           Device-2: NVIDIA GM108M [GeForce 840M] driver: nvidia v: 470.103.01 
           Display: x11 server: X.Org 1.19.6 driver: modesetting,nvidia 
           unloaded: fbdev,nouveau,vesa resolution: 1600x900~60Hz 
           OpenGL: renderer: NVIDIA GeForce 840M/PCIe/SSE2 v: 4.6.0 NVIDIA 470.103.01 
Network:   Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet driver: r8169 
           Device-2: Qualcomm Atheros QCA9565 / AR9565 Wireless Network Adapter driver: ath9k 
Drives:    Local Storage: total: 931.51 GiB used: 577.56 GiB (62.0%) 
Info:      Processes: 298 Uptime: 11h 56m Memory: 11.61 GiB used: 2.97 GiB (25.6%) Shell: bash 
           inxi: 3.0.27 
`

`❯ cherrytree --version
CherryTree 0.99.48
`

**Comment by giuspen** [comment]
thanks will be fixed in next release
