### ISSUE TITLE
[0.37.6] Windows: all monospaced text has a dark grey background

### ISSUE THREAD

**Issue by keesse** [giuspen/cherrytree#208]
Hi, just upgraded my Windows version to 0.37.6.
Now all monospaced text has a dark grey background, both old notes and new notes
See attached screenshot
![mono spaced text - cherrytree 0 37 6](https://cloud.githubusercontent.com/assets/18166189/20348262/db106e1c-ac04-11e6-9e92-362f0a254633.png)

**Comment by giuspen** [comment]
The background color will be configurable in the preferences dialog in the next 0.38.0. Currently if you want to disable this you have to edit config.cfg and change `monospace_bg = #7f7f7f` to `monospace_bg =`

**Comment by keesse** [comment]
Hi Giuspen, thank you for your reply.
On Windows I allready downgraded to 0.37.5.
On Ubuntu I found no config.cfg but a config.py
There I found a line with: dad.monospace_bg = DEFAULT_MONOSPACE_BG
I changed DEFAULT_MONOSPACE_BG = "#7f7f7f" to 
DEFAULT_MONOSPACE_BG = "", leaving out the "" resulted in an error.
After restarting Cherrytree, I still had a dark grey background, I also changed to "#

**Comment by giuspen** [comment]
The  config.cfg is the preferences text file and you can find it from the top menu item Help--Open Preferences Directory
