### ISSUE TITLE
All unicode emoji/fonts/symbols are no longer copy-pastable in new versions of CherryTree.

### ISSUE THREAD

**Issue by PranavBhattarai** [giuspen/cherrytree#2094]
In previous releases/versions, this was never a problem (it was never a big deal to copy particular icons/emoji from different websites/apps to design notes in CherryTree). In but past few releases, I have noticed that this was no longer doable.
We can copy the same icons/symbol if it **already** inside your node (i.e. in the previous version when u have designed the note). But if you want the same or different icons/fonts/emoji which is not already inside CherryTree, then you no longer can copy-paste them anymore from **outside** (i.e outside CT software).
### 🔥✓𝛌 ॐ ≈
 Different math calculation and non-math subjects need these types of symbols to design notes. It important basic feature. I wonder what happened in new releases. 
```
Current CherryTree Version:  0.99.48
Icons copied from:           GNOME Characters
Distro:                      Fedora 36 Workstation 
```

### Update: 
But if you, try to change node properties or create a new node, you can use the fonts (i.e you can **SEE**, the fonts/emoji without an issue!  

~~I think this is more related to CherryTree "visibility issues", which CT didn't have before!~~ Nope. Pasted icons/fonts, if it had a visibility issue, <ins>leave a genuine space/area</ins>; which CT clearly didn't. Hence proved, it's a real issue.

**Comment by giuspen** [comment]
I did copy and paste the icons from this ticket into a cherrytree rich text node without problems.
Using firefox on ubuntu 20.04.
I'll give it a quick try on Fedora 37 as I have a VM set up with it.

**Comment by giuspen** [comment]
I tried the same on Fedora 37 copy from firefox paste into cherrytree rich text node and it worked

**Comment by PranavBhattarai** [comment]
The problem is specific between **CherryTree** and **GNOME Characters**.
![Screencast-from-10-26-2022-07_45_32-PM](https://user-images.githubusercontent.com/32763112/198048395-0d1c4334-874f-4433-8481-b981b95b8206.gif)
All GNOME Characters Unicode emojis/characters are no longer **copy-pastable**. 
But it works fine if I copy any emoji/character from GNOME Character into any other application like Firefox, VSCode, TextEditor, etc. 

So weird. What going on?
![image](https://user-images.githubusercontent.com/32763112/198049670-f61b1f38-dd8a-4212-90f4-8c0253ab1230.png)

**Comment by giuspen** [comment]
I tried the latest cherrytree on ubuntu 20.04 and gnome-characters 42.0 from snap package and it works (even though it crashed my virtualbox virtual machine twice, weird).
I will try later on Fedora 37.

**Comment by giuspen** [comment]
OK I managed to reproduce in Fedora 37 and fix
