### ISSUE TITLE
Snap version of CherryTree cannot open files

### ISSUE THREAD

**Issue by the-langster** [giuspen/cherrytree#2101]
**Version, Operative system**

CherryTree: 0.99.48 – snap

  Operating System: Ubuntu 20.04.5 LTS
  Kernel: Linux 5.15.0-46-generic
  Architecture: x86-64

**Describe the bug**
Permission settings of the snap-version prevent opening files. This happens both when trying to open existing file with CherryTree, and when opening CherryTree and then hitting "Open File". When hitting "Open File", CherryTree immediately terminates. The non-snap version works fine. I reckon that this could be a problem of my setup.

Here is my console output:
```
foo@foo:~/Desktop$ cherrytree tanker.ctd
ln: failed to create symbolic link '~/snap/cherrytree/49/.config/gtk-2.0/gtkfilechooser.ini': File exists
Gtk-Message: 11:24:52.607: Failed to load module "canberra-gtk-module"
Gtk-Message: 11:24:52.608: Failed to load module "canberra-gtk-module"
[2022-08-26 11:24:52.611] [   ] [debug] ~/snap/cherrytree/49/.config/cherrytree/config.cfg parsed
[2022-08-26 11:24:52.702] [   ] [debug] autosave is started
I/O error : Permission denied
I/O error : Permission denied
I/O warning : failed to load external entity "~/Desktop/tanker.ctd"
[2022-08-26 11:24:52.757] [   ] [error] _get_parser ~/Desktop/tanker.ctd Could not create parser context
(warning): failed to load external entity "~/Desktop/tanker.ctd"

[2022-08-26 11:24:52.757] [gtk] [critical] 
unhandled exception (type Glib::Error) in signal handler:
domain: g-file-error-quark
code  : 2
what  : Failed to open file “~/Desktop/tanker.ctd”: Permission denied
```

Ceterum censio, Ubuntu should stop shoving snaps down our throats.

**Comment by sunxueren** [comment]
sme problem – over night, cherrytree can no longer access the user home directory; I reinstalled cherrytree, problem persists.

UBUNTU; "permission denied".

**Comment by giuspen** [comment]
Sorry about that I did successfully open cherrytree files myself before releasing the snap, I'll try to reproduce this evening. In case I don't understand what's wrong @hellsworth can you please have a look too?

**Comment by hellsworth** [comment]
@giuspen Yes I'd be happy to take a look a bit later today.

>Ubuntu should stop shoving snaps down our throats.
@the-langster This is not a case of Ubuntu forcing snaps on you at all. You do not need to use the snap and Giuspen has done a great job providing both a [deb](https://packages.ubuntu.com/jammy/cherrytree) and [flatpak](https://flathub.org/apps/details/net.giuspen.cherrytree). Perhaps you did not know about these other formats. Still, thank you for reporting this snap bug though, we will get it fixed :)

**Comment by ngt500** [comment]
Same problem with 0.99.48 in ubuntu 20.04.1
First noticed sqlite password protected file not accepting password. Then I tried creating a new non password protected file and it would crash when trying to save.
If I switch back to latest/edge 0.99.36 in snap store it works.

`systemd[2103]: Started Application launched by gnome-shell.
systemd[2103]: Started snap.cherrytree.cherrytree.20b6d9ce-892a-4e8e-8668-fa541c1833fc.scope.
systemd[2103]: gnome-launched-cherrytree_cherrytree.desktop-10722.scope: Succeeded.
kernel: [ 2106.382947] audit: type=1400 audit(1661526679.267:270): apparmor="DENIED" operation="open" profile="snap.cherrytree.cherrytree" name="/home/username/Documents/" pid=10795 comm="head" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000
cherrytree_cherrytree.desktop[10823]: ln: failed to create symbolic link '/home/username/snap/cherrytree/49/.config/gtk-2.0/gtkfilechooser.ini': File exists
cherrytree[10722]: Failed to load module "canberra-gtk-module"
kernel: [ 2106.479491] audit: type=1326 audit(1661526679.363:271): auid=1000 uid=1000 gid=1000 ses=4 subj=? pid=10722 comm="cherrytree" exe="/snap/cherrytree/49/bin/cherrytree" sig=0 arch=c000003e syscall=314 compat=0 ip=0x7fc279eb8a3d code=0x50000
cherrytree[10722]: Failed to load module "canberra-gtk-module"
cherrytree_cherrytree.desktop[10722]: [2022-08-26 08:11:19.373] [   ] [debug] /home/username/snap/cherrytree/49/.config/cherrytree/config.cfg parsed
cherrytree_cherrytree.desktop[10722]: [2022-08-26 08:11:19.516] [   ] [debug] autosave is started
cherrytree_cherrytree.desktop[10722]: ERROR: Permission denied
cherrytree_cherrytree.desktop[10722]: /home/username/Notes-test.ctx
cherrytree_cherrytree.desktop[10722]: System ERROR:
cherrytree_cherrytree.desktop[10722]: Unknown error -2147024883
cherrytree_cherrytree.desktop[10722]: [2022-08-26 08:11:23.833] [   ] [debug] !! CtP7zaIface::p7za_extract
kernel: [ 2110.942585] audit: type=1400 audit(1661526683.827:272): apparmor="DENIED" operation="open" profile="snap.cherrytree.cherrytree" name="/home/username/" pid=10722 comm="cherrytree" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000
kernel: [ 2110.942601] audit: type=1400 audit(1661526683.827:273): apparmor="DENIED" operation="open" profile="snap.cherrytree.cherrytree" name="/home/username/" pid=10722 comm="cherrytree" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000
cherrytree_cherrytree.desktop[10722]: [2022-08-26 08:16:40.144] [gtk] [warning] Error creating IO channel for /proc/self/mountinfo: Permission denied (g-file-error-quark, 2)
cherrytree_cherrytree.desktop[10722]: [2022-08-26 08:16:40.212] [gtk] [info] Settings schema 'org.gtk.Settings.FileChooser' does not contain a key named 'show-type-column'
kernel: [ 2427.322695] traps: cherrytree[10722] trap int3 ip: sp:7ffd081f5370 error:0 in libglib-2.0.so.0.7200.1[7fc27a33e000+8f000]
systemd[2103]: snap.cherrytree.cherrytree.20b6d9ce-892a-4e8e-8668-fa541c1833fc.scope: Succeeded.

`

**Comment by giuspen** [comment]
Thanks @hellsworth , also an appimage is available to download for who has issues https://www.giuspen.net/cherrytree/#downl
I did test on 22.04 and believed the snap would anyway work the same everywhere, apologies I'm learning in these days how it works, I suspect everyone on 20.04 is having troubles

**Comment by sunxueren** [comment]
Thank you for the quick fix; that one works.

**Comment by hellsworth** [comment]
@giuspen I'm pretty sure it's because the home plug is missing. Just doing a local build to test and will open a PR.

**Comment by giuspen** [comment]
Great thanks @hellsworth
