### ISSUE TITLE
Hitting <shift><tab> on the • bullet point completely kills cherrytree and loses some work (other bullet points work as they should normal)

### ISSUE THREAD

**Issue by dimyself** [giuspen/cherrytree#2103]
**Version, Operative system**
0.99.47
arch linux up to date
XFCE

**Describe the bug**
I believe its a bug. If i <tab> on a bullet point started with this char  - , it changes the bullet point style and indents. But if i <shift> <tab> from the  •  bullet point, it kills cherrytree (and doesnt even save). The other bullet point styles dont kill cherrytree using the same shortcut. Also, if I hit <enter> at the • bullet, it also kills cherrytree

I checked cherrytree keyboard shortcuts, and dont see any using <tab>. I haven't changed them from defaults.

I also checked OS keyboard shortcuts, and dont see anything for shift tab. 

I've tried shift & tab in other apps and it doesn't kill the app, so I believe this is specific to cherrytree

Its annoying and loses a lot of time, because if i hit shift and tab to reverse the bullet point, it kills the app, and i lose some work. I'm not sure if anyone else has had this bug or not...Or maybe its something i'm missing

It used to work fine for me on my system. Its been awhile since I used this functionality though. I can also try from other desktops or another computer.

**To Reproduce**
1. Go to beginning of line and insert a - char
2. Hit the tab key to indent and change the bullet point style until it reaches the •  bullet point
3. Then hit shift & tab to reverse the indentation and bullet style (or if i hit <enter>)
4. cherrytree is killed by doing this shift tab (or hitting enter) action...but ONLY using the • bullet point. All others work as supposed to normal and dont kill the app

![cherrytree_bug](https://user-images.githubusercontent.com/36783626/186975225-18507ab1-5508-4b3a-b443-6a0edaa123f3.gif)

**Comment by giuspen** [comment]
Hi,
Can you go to preferences dialog, tab special characters, chars for bulleted list.
Can you copy and paste those charactes here?
E.g. the default is 6 characters •◇▪-→⇒

**Comment by giuspen** [comment]
While it is not crashing for me on Ubuntu 22.04, I can see that Shift+Tab on that particular character is behaving incorrectly, it is not rotating to an indent character but leaving an empty character. I'll have a look something is not right

**Comment by giuspen** [comment]
Thanks for reporting, it's been fixed will be ok in 0.99.49
