### ISSUE TITLE
crash on import

### ISSUE THREAD

**Issue by kbrannen** [giuspen/cherrytree#2107]
**Version, Operative system**
`Ubuntu 20.04.4 LTS`

```
kevin@dogbert:~> snap list --all
Name                Version                     Rev    Tracking       Publisher    Notes
cherrytree          0.99.48                     56     latest/stable  hellsworth   -
cherrytree          0.99.48                     49     latest/stable  hellsworth   disabled
```
I tried reverting to revision 49 and the same problem happens.

**Describe the bug**
Cherrytree crashes when I try to do any import: html, text, html folder, etc. If run from a terminal then more info becomes visible:
kevin@dogbert:~> cherrytree
[2022-08-28 23:13:43.935] [   ] [debug] /home/kevin/snap/cherrytree/56/.config/cherrytree/config.cfg parsed
[2022-08-28 23:13:44.058] [   ] [debug] autosave is started
[2022-08-28 23:14:06.166] [   ] [debug] Node name: Technical
[2022-08-28 23:14:08.669] [   ] [debug] shift images in MenuBar/context menu
[2022-08-28 23:14:12.183] [gtk] [warning] Error creating IO channel for /proc/self/mountinfo: Permission denied (g-file-error-quark, 2)
[2022-08-28 23:14:12.279] [gtk] [info] Settings schema 'org.gtk.Settings.FileChooser' does not contain a key named 'show-type-column'
Trace/breakpoint trap (core dumped)

**To Reproduce**
1. Start Cherrytree.
2. Create a new node (optional, problem happens with or without this, but I'm listing this since I did it above and I wanted to make sure no nodes wasn't causing the issue).
3. Select File->Import->From_HTML_File (but I've seen it fail on at least 3 different file types so I think the problem is with the code when it tries any import) ... then it crashes.

If it wasn't obvious above, this is with the latest Ubuntu snap.
This is on a KDE desktop, but I have no problem running other GTK programs or snaps.

**Comment by giuspen** [comment]
Hi @kbrannen please try to update again as a new package has been released following multiple users reporting crashes in the updated snap.
Same version 0.99.48, but a new package should be downloaded.
If still crashes and you urgently need a working version and you cannot install on the system, also consider the AppImage version of cherrytree (all in a single file, nothing to install) https://www.giuspen.net/cherrytree/#downl
If you can install, the best version is the deb package / adding the ppa.
Please let me know if the crash is solved for you too.

**Comment by kbrannen** [comment]
Snap says there is no update and that revision 56 is the latest. I removed it since it didn't work, added your PPA and installed the package like normal software. :) That is working just fine and doesn't have any issues. So you can close this if you already have a ticket open for the bad snap.

Thanks for the quick response! :)

**Comment by giuspen** [comment]
I tried today on an ubuntu 18.04 virtual machine and the snap is still not working with the current revision 57.

If I try File--Open File I get the following error:

[2022-09-01 21:48:32.851] [gtk] [warning] Error creating IO channel for /proc/self/mountinfo: Permission denied (g-file-error-quark, 2)
(cherrytree:2964): Gtk-WARNING **: 21:48:32.928: Can't open portal file chooser: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files

@hellsworth if you have an idea of what could be the cause please let me know, otherwise tomorrow I'll try to play with this issue myself.

**Comment by giuspen** [comment]
@hellsworth for me it was failing much earlier as I tried to open an existing document and the file selection dialog didn't come out, I haven't tried to create a new document/save.
If you have some time to play with this issue that would be great so I can focus on other tickets.

**Comment by giuspen** [comment]
Note my tests are on an Ubuntu 18.04 Mate

**Comment by hellsworth** [comment]
yes @giuspen I got you on this bug :)
I know that it's related to portals now, and will work on a solution today.
