### ISSUE TITLE
[Bug] node moving/relocation causes other nodes to expand

### ISSUE THREAD

**Issue by turbodude** [giuspen/cherrytree#211]
Hello! 
I have lots of nodes and other nodes inside those, and it seems like moving some of them up and down the tree or left and right causes other nodes with children to expand. It's hard to see any patterns but some nodes stay contracted, and others just expand without any apparent reason.
I'm using Windows 10 and used to be using Windows 7 before that.
And thanks for the program, it's a wonderwork, I'm having it opened every day.

**Comment by giuspen** [comment]
Hi, it would help if you would be able to provide a sequence of operations,
using for example the cherrytree manual (
http://giuspen.com/cherrytreemanual/CherrytreeManual.ctb) where you observe
one expansion that should not happen so that I can analyse the case and
provide feedback

**Comment by turbodude** [comment]
OK, here it is:
When I open the file and move around some nodes - nothing happens. But once I have folded the branch "Menus", it gets expanded right after I move any node. I tried saving the document before moving and got the same result. The branch "Preferences" stayed folded all when I was doing all that.

**Comment by giuspen** [comment]
Correct, you probably have the option (in preferences, tab Tree 1) "Nodes in Bookmarks Always Visible" selected... in fact I realize it is True by default, maybe I should instead set it to False by default since it is unexpected

**Comment by turbodude** [comment]
Yes, that option has been selected. I unchecked it and the original problem is gone. 
Thanks!
