### ISSUE TITLE
Keyboard shortcut for "decrease codebox width" not reachable on German keyboard

### ISSUE THREAD

**Issue by dolorosus** [giuspen/cherrytree#2113]
Keyboard shortcut for "decrease codebox width" is not reachable on german keyboard.

ctrl+alt+backslash is not possible on German keyboard, because backslash needs the AltGr key. 
Unfortunately this keyboard shortcut, cannot be changed in the preferences.

Version: 0.99.48

**Comment by giuspen** [comment]
I will try to make the keyboard shortcut editable

**Comment by giuspen** [comment]
It's too much of a job to make the shortcut editable, I cannot do it for now.
I can try to find another combination more accessible though.
What about Ctr+'(' and Ctrl+Alt+'(' ==> '(' instead of '\'

**Comment by dolorosus** [comment]
Thanks a lot.
Ctr+'(' and Ctrl+Alt+'('  is reachable on a German keyboard layout.

I may be wrong, but wasn't Ctr+'.' and Ctrl+Alt+'.'  once the shortcut for this?

**Comment by giuspen** [comment]
Unfortunately Ctrl+'.' has been taken from GTK for the insertion of smileys, that's why I had to lose it
