### ISSUE TITLE
Crashes on Double Exit

### ISSUE THREAD

**Issue by 4n1qz5skwv** [giuspen/cherrytree#2114]
**Version, Operative system**
Microsoft Windows [Version 10.0.19044.1889] | CherryTree 0.99.48

**Describe the bug**
Crashes on clicking exit from tray when "Do you want to save the changes?" popup is active.

**To Reproduce**
1. Open CherryTree and make some edit (do not save)
2. Select Exit from tray (a popup to save the changes will appear, do no dismiss it)
3. Select Exit from tray Again.
4. Crash

**Screenshots**
![image](https://user-images.githubusercontent.com/76768193/188890886-e06c893a-b4b5-4599-a93a-e4b90e6f2e83.PNG)

**Comment by giuspen** [comment]
Thanks will be fixed in upcoming 0.99.49
