### ISSUE TITLE
crash when node with table is exported to HTML

### ISSUE THREAD

**Issue by wgreene310** [giuspen/cherrytree#2115]
**Version, Operative system**
99.48, Windows 10

**Describe the bug**
When a table cell contains more than one line, cherrytree crashes when this node is exported to HTML.
The reason is that in ct_export2html.cc, rtl_for_lines has fewer entries than node_lines so this test,
if (rtl_for_lines.at(i))
throws an exception.

**Comment by giuspen** [comment]
This is fixed in upcoming 0.99.49. Please test it there, I will try and release by the end of tomorrow.

**Comment by wgreene310** [comment]
Yes, thanks, the latest version of the code appears to have fixed the problem.

**Comment by giuspen** [comment]
Thanks for testing it
