### ISSUE TITLE
7-zip "cannot access the file" while CT is running

### ISSUE THREAD

**Issue by dardoor** [giuspen/cherrytree#2116]
If I try to compress/archive the .ctb file with 7zip while it's open in CherryTree, I get the error:
"The process cannot access the file because it is being used by another process."

Using Windows 10, CT 0.99.44.

Is there a way to avoid this, maybe?
I know that it happens with LibreOffice too, but it doesn't happen for example with Notepad or Notepad++.

**Comment by giuspen** [comment]
If you use the .ctd (xml instead of sqlite) you should be able to access the file while being in use from cherrytree

**Comment by dardoor** [comment]
Yep that works, thanks!
