### ISSUE TITLE
monospace text not displaying correctly

### ISSUE THREAD

**Issue by wgreene310** [giuspen/cherrytree#2119]
**Version, Operative system**
99.49, windows 10

**Describe the bug**
It seems that if I set the monospace property for some text, that
text is always greyed out. This is true for the default font for this
property or even if I set the font in preference to, e.g. courier new bold.
If I change the font size, for example, the text is changed as expected.

**Comment by giuspen** [comment]
There is a preferences dialog option for the colour of the monospace text, may be in the tab theme or in the tab rich text
