### ISSUE TITLE
Hotkey Suggestions

### ISSUE THREAD

**Issue by Camilot55** [giuspen/cherrytree#2128]
Hi Giuseppe.
It is possible to correct the display of hotkeys in the prompts. For example, not in this form <control><shift>F, but in the usual Ctrl+Shift+F.
![Безымянный](https://user-images.githubusercontent.com/76065578/193498964-2d62ae7c-b3ed-4257-a275-de5c2fe827c1.png)

**Comment by giuspen** [comment]
Hi Viktor, yes that's ok
