### ISSUE TITLE
Loss of transparency with PNGs

### ISSUE THREAD

**Issue by BattleW0rm0** [giuspen/cherrytree#2132]
**Version, Operative system**
Ubuntu 20.04 with dark mode enabled (see below)
Cherrytree 0.99.49

**Description**
PNG's lose their transparency, either with Ubuntu's dark mode enabled or not. Although it is much less visible with light mode because the background is a light gray and not dark gray.
Screenshot below.

**To Reproduce**
The same problem occurs whether you copy/paste the image or you insert it via the menu

**Screenshots**
Here is a screenshot, you can see on the right with the light mode activated that the image background isn't really white like cherrytrees background visible on top.
![image](https://user-images.githubusercontent.com/59833894/194732280-54e31224-26a5-42d2-ad3f-a6ee6bfd6e46.png)

**Comment by giuspen** [comment]
Hi can you attach one PNG that you imported into cherrytree that causes the issue? I have imported several PNGs but don't recall seeing it

**Comment by BattleW0rm0** [comment]
> Hi can you attach one PNG that you imported into cherrytree that causes the issue? I have imported several PNGs but don't recall seeing it

Hello, thanks for answering.
Here are two images that behave this way, I've tried with others and it's the same.
[https://imgur.com/a/GvysKyD](https://imgur.com/a/GvysKyD)

**Comment by BattleW0rm0** [comment]
I forgot to mention the same thing happens to anchor icons : 
![comparison2](https://user-images.githubusercontent.com/59833894/194776505-c6eb102b-7dde-46bb-959d-df3b74372fbc.png)

Dark theme on top and standard on the bottom. If you zoom in, you can see the grayish/beige color of the background with the light theme.

**Comment by giuspen** [comment]
Also discussed in older ticket https://github.com/giuspen/cherrytree/issues/1402

**Comment by giuspen** [comment]
will be fixed in 0.99.51
