### ISSUE TITLE
cherrytree process lives in background if try to exit using tray icon when "enter password" windows is active

### ISSUE THREAD

**Issue by 4n1qz5skwv** [giuspen/cherrytree#2133]
**Version, Operative system**
Microsoft Windows [Version 10.0.19044.2130] | CherryTree 0.99.49

**Describe the bug**
title

**To Reproduce**
If applicable, attach a non-personal document where the issue can be reproduced systematically.
1. Open a password protected cherrytree .ctx file (do not enter password)
2. Try to exit using tray icon.
3. It becomes a zombie.

**Comment by giuspen** [comment]
will be fixed in 0.99.51
