### ISSUE TITLE
"Start Minimized in the System Tray" also affects click on systray icon

### ISSUE THREAD

**Issue by dolorosus** [giuspen/cherrytree#2134]
Windows 10
Cherrytree 0.99.50

**Describe the bug**
Not sure if it's a really bug or just an unwanted behaviour.

If the option _"Start Minimized in the System Tray"_ is active, clicking on the systray icon does not open the Cherrytree window, but creates an entry in the taskbar, which you have to click a second time to open the Cherrytree window.

Steps to reproduce the behaviour:
1. Go to _"settings", "Miscellaneous"_
2. select _"Enable System Tray Docking"_
3. select _"Start Minimized in the System Tray"_
4. minimize Cherrytree to systray (click the window close button)
5. Click on the Cherrytree icon in systray
6. **Expected behaviour:** the Cherrytree Windows opens up
    **actual behaviour:** an entry on the taskbar is created. Only after clicking on this entry in the taskbar, the Cherrytree window opens.

**Comment by giuspen** [comment]
I cannot reproduce on my laptop:

Edition	Windows 10 Home
Version	21H2
Installed on	‎21/‎12/‎2020
OS build	19044.2130
Experience	Windows Feature Experience Pack 120.2212.4180.0

I'll try on another later.

**Comment by dolorosus** [comment]
To be honest, after playing around with various settings I decided to delete the config and start from scratch.
Now I can't reproduce this behaviour anymore.

I'm sorry  alarming you.

**Comment by dolorosus** [comment]
To be honest, after playing around with various settings I decided to delete the config and start from scratch.
Now I can't reproduce this behaviour anymore.

I'm sorry  alarming you.
