### ISSUE TITLE
Keyboard Shortcut corruption

### ISSUE THREAD

**Issue by glotim** [giuspen/cherrytree#2136]
**Version, Operative system**
Linux Mint MATE 21.0
CherryTree v 0.99.50

**Describe the bug**
I recently upgraded from Linux Mint MATE 20.3 to 21.0 via Nuke and Pave. I installed the latest Cherrytree via your website. Copied all my settings to the new install. (Restored the ~/.config/cherrytree/config.cfg file)
Everything appears to work except the Insert Timestamp keyboard shortcut. If you Insert Timestamp from the menu it works fine. If you try to do it from a keyboard shortcut it just puts a "e" on the line and then you cannot move the cursor with the cursor keys or backspace or delete it. You have to click to another line then the e disappears.

I have cleared the keyboard shortcut and restarted then set it up again and restarted still the same.

I have also changed the timestamp format and restarted and no change. 

Does not matter what notes file you use.

Also have a identical setup at work and this does not happen.

**Comment by giuspen** [comment]
Are you using the default keyboard shortcut Ctrl+Alt+M or you defined a custom one?

**Comment by glotim** [comment]
I used a custom one instead Ctrl+;
So I just changed it back to the default and restarted and that now works.
Then I changed it back to Ctrl+; and and restarted the problem comes back.
What is going on?

**Comment by glotim** [comment]
OK. Figured this out. When you install Zoom for Linux it installs a little deal that sits in the tray has the letters "EN" all the time. Not sure what that is for however you can click on that and select Preferences and a dialog box comes up that has "iBus Preferences" as the title. I poked around there and on the "Emoji" tab it has some keyboard Shortcuts settings. Sure enough on a line that says Emoji annotation: it lists "<Control>semicolon;<Control>period"
I changed that first one to <Control>colon and then my CherryTree keyboard shortcut immediately worked.
So classic battle of the keyboard shortcut daemons!
By the way it also has <Control><Shift>u mapped for something called Unicode code point
I hope this will help others.
Now I am going to see if I can set that iBus thing to only run when I run Zoom. Not all the time.

**Comment by giuspen** [comment]
Yes that's what I suspected as I had a similar trouble recently and I had to stop using the keyboard shortcut Ctrl+period. I'll close this then.
