### ISSUE TITLE
cherrytree won't install on kubuntu 22.10

### ISSUE THREAD

**Issue by paescu68** [giuspen/cherrytree#2139]
Seems libspdlog1 was updated..

$ sudo apt-get install cherrytree
[..]
The following packages have unmet dependencies:
 cherrytree : Depends: **libspdlog1** but it is not installable
E: Unable to correct problems, you have held broken packages.

$ sudo apt-get install libspdlog1
Package libspdlog1 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or is only available from another source
**However the following packages replace it:
  libspdlog1.10:i386 libspdlog1.10**

**Comment by giuspen** [comment]
Thanks for reporting, I updated the package in the PPA for 22.10 please report if works now

**Comment by paescu68** [comment]
Works fine now - thanks for the lightning quick response!
