### ISSUE TITLE
Monospaced text has dark grey background

### ISSUE THREAD

**Issue by anmej** [giuspen/cherrytree#214]
Monospaced text (produced by ctrl+M) invariably has dark grey background when created. I can change it manually, but I'd like it to have the page background by default.

**Comment by giuspen** [comment]
Will be graphically configurable from next version with quick disable

**Comment by anmej** [comment]
Great, thanks.

**Comment by fifJfil** [comment]
You can change the value manually in ~/.config/cherrytree/config.cfg at line "monospace_bg =..." ( for ex. #ffffff for white background).

**Comment by tonyrulez** [comment]
Where exactly is this graphically configurable? I can't seem to find it in the latest version.

**Comment by rorschach-jl** [comment]
> Where exactly is this graphically configurable? I can't seem to find it in the latest version.

I'm using v0.99.46 and found it under "settings -> format" - here you can enable or disable the colors for the fore- and background
