### ISSUE TITLE
Keep CherryTree "Always On Top" (window in focus)

### ISSUE THREAD

**Issue by ajaxStardust** [giuspen/cherrytree#2145]
**Is your feature request related to a problem? Please describe.**
No. No problem. 

**Describe the solution you'd like**
I thought I'd seen the option to keep the CherryTree window Always On Top (to keep the window always in focus, for example making notes while coding in a separate app). 

I've gone through the on-line manual and can't find anything. Everything about "top" that i've found is related to Node management.

Thank you!

**Comment by giuspen** [comment]
I'm not sure if windows desktop allows to set any window as always on top or you have to do something in the specific app, I'll have a look.

**Comment by ajaxStardust** [comment]
Thank you so much for your prompt reply! 

Windows actually does allow it. There are also 3rd party apps which enable it, but I've tried them, and what i tried was kind of "clunky", or "janky" if those words mean anything to anyone! lol. In any case, this resource came up when i googled. looks like he's providing some [AutoHotKey script](https://www.groovypost.com/howto/howto/windows-programs-always-on-top/)... i've never used that app, but it might give you some insight (i hear it's a great app for repetitious coding if you can learn to utilize it)? 

Apps that I can think of which have it integrated? 
-- [Notepad2](https://www.flos-freeware.ch/notepad2.html) - a Scintilla-based text editor
-- Sysinternals - [Process Explorer](https://learn.microsoft.com/en-us/sysinternals/) 
-- [IrfanView](https://www.irfanview.com) - image viewer app. 

Just a few off the top of my head. 

Best wishes, and thank you very much for CherryTree. It's really awesome! I used to use FlashNote by Softvoile, but i'm afraid-- for a great a guy as Nokolay is, his focus is on his other apps like FlashPaste (which i really like, BTW). Once I discovered CherryTree, i haven't looked back in terms of this type of app. Very nice. Well done and thoughtful!

**Comment by ajaxStardust** [comment]
Hey there, G! Just wanted to throw this out there, in case you've ever worked with Firefox extensions in case that could provide any insight. 
https://addons.mozilla.org/en-US/firefox/addon/always-on-top/

**Comment by giuspen** [comment]
This option will be available in upcoming version 0.99.54 under the top menu "View"

**Comment by ajaxStardust** [comment]
You're fabulous, Giuseppe! Thank you for this. I'm looking forward to it!
Cheers!
