### ISSUE TITLE
Support Path Links Starting from Home Folder with ~/

### ISSUE THREAD

**Issue by emendir** [giuspen/cherrytree#2149]
The feature which gives one the ability to link text in a cherrytree node to a file/folder on the local filesystem is great, but it does not yet support paths starting with `~/`, for example `~/.bashrc`, which means _'the file called `.bashrc` located in the current user's home folder'_.
Instead, CherryTree currently interprets such paths as relative paths, looking for them in the directory of the CherryTree file.

**Comment by giuspen** [comment]
ok will be in 0.99.52
