### ISSUE TITLE
Auto shutdown

### ISSUE THREAD

**Issue by ttcipher** [giuspen/cherrytree#215]
Windows 7, cherrytree 0.37.6 quits after a few minutes, no error or notification.  Previous versions no problems.

**Comment by giuspen** [comment]
In the preferences dialog, tab Miscellaneous, Do you have "Autosave Every N Minutes" or "Reload After External Update to CT* File" selected? If you deselect both of them, do you still have cherrytree closing automatically? If you can reinstall 0.37.5, please check that the problem does not appear there.

**Comment by giuspen** [comment]
I will be issuing a new version 0.38.0 shortly after the end of the year,
let me know if you will have the problem with that and if that is the case
if you are available to do testing we can try and fix the problem

**Comment by ttcipher** [comment]
Will do and thanks ...
