### ISSUE TITLE
Add new building instructions for gentoo

### ISSUE THREAD

**Issue by flint2** [giuspen/cherrytree#2151]
I´m now the maintainer for the cherrytree package in Gentoo Linux distribution

https://packages.gentoo.org/packages/app-text/cherrytree

You can install cherrytree with the command:

`sudo emerge cherrytree`

Maybe you can update README.md, or if you accept PR I can do it.

**Comment by giuspen** [comment]
Hi a PR would be ideal thanks

**Comment by flint2** [comment]
Created PR https://github.com/giuspen/cherrytree/pull/2153

**Comment by giuspen** [comment]
Thanks!
