### ISSUE TITLE
Collapsed nodes are always expanded again when CT is reopened

### ISSUE THREAD

**Issue by paul1149** [giuspen/cherrytree#2154]
**Version, Operative system**
.99.43, on MX Linux 21, with KDE desktop environment

**Describe the bug**
Many nodes/subnodes insist on being expanded every time I open Cherrytree. I have Saved the DB, I have Save and Vacuumed the DB. I have collapsed the parent node that houses subnodes. Nothing works to keep them collapsed.

**To Reproduce**
If applicable, attach a non-personal document where the issue can be reproduced systematically.
1. collapse various nodes or subnodes
2. Close CT.
3. Open CT
4. the collapsed nodes will be open again

This is an annoyance-level bug, as it forces me to reorganize the node tree each time, for clarity.

THANKS

**Comment by giuspen** [comment]
This is very strange. The expanded collapsed nodes are not in the database but rather in ~/.config/cherrytree/config.cfg please upgrade to latest, try again and look at your settings in the preferences dialog, tab tree

**Comment by paul1149** [comment]
Aha. That apparently explains it. I can't upgrade, as my current version is the most recent in the repositories. But I went to settings and saw the "always expand nodes with bookmarks" option. I didn't recall any bookmarks, actually don't know how they work, but on unchecking it the problem has now disappeared. 

Thanks much! :)
