### ISSUE TITLE
Search in table can't list multiple instances of query

### ISSUE THREAD

**Issue by revotsna1** [giuspen/cherrytree#2155]
I have multiple cells containing a query. Searching for query returns one result starting at beginning of table. The table itself does not become highlighted as regular word would. I think it would be useful to be able to highlight individual instances of queries within a table.

Also, I was using regex to find. Using the same regex or a term in the find & replace returns no results when applied to a table.

**Comment by giuspen** [comment]
This has now been implemented, will be in upcoming v1.1.0
