### ISSUE TITLE
Highlight of matching braces always active in codebox

### ISSUE THREAD

**Issue by luc0x61** [giuspen/cherrytree#2157]
**Version, Operative system**
CT 0.99.51, Windows 11 Pro 22H2

**Describe the bug**
I disabled in Preferences / Plain and Text Code / Text Editor / Highlight Matching Braces
I can't disable the highlight of matching braces in any codebox. If I exit a codebox with a mouse click elsewhere, and the cursor in the codebox was on a starting/ending brace, the brace couple still remains highlighted.
If I move the cursor on a non-brace character the highlight disappears. However, if I editing elsewhere I anyhow select "Undo", **all** the last brace couple of **all** the codeboxes are highlighted again.

This happened with a few codeboxes using basic XML, like
```
<TAG>
  foo
</TAG>
```
where the brackets of the closing tag keep being highlighted

**To Reproduce**
If applicable, attach a non-personal document where the issue can be reproduced systematically.
1. Disable Preferences / Plain and Text Code / Text Editor / Highlight Matching Braces
2. Create a few codeboxes as shown above in description
3. Ending on last closing bracket still highlights '<' and '>' couple -- **error 1**
4. Moving the cursor somewhere else seems to disable temporarily highlight
5. Click/Edit outside of codebox
6. Select Undo: the highlight is re-enabled in all codeboxes -- **error 2**

**Screenshots**
![immagine](https://user-images.githubusercontent.com/56227954/202723298-4a157975-00f9-496c-b700-a963e85d5f36.png)

**Comment by giuspen** [comment]
when you create/edit every single codebox there is a local tick for the Highlight Matching Brackets
![image](https://user-images.githubusercontent.com/6842059/202754858-a39de408-2287-433d-ae75-47800f03813e.png)

**Comment by luc0x61** [comment]
Oh well, please excuse me for not having paid enough attention...

**Comment by giuspen** [comment]
no problem
