### ISSUE TITLE
Check For Newer Version Not Working

### ISSUE THREAD

**Issue by Metaxona** [giuspen/cherrytree#2162]
**Version: 0.99.38, Operating system: Windows 10 64 bit**

**Describe the bug**
Clicking Check For Newer Version Doesn't do anything. The latest version is 0.99.51, but after clicking the check for newer version in help menu, nothing happened. 

**To Reproduce**
If applicable, attach a non-personal document where the issue can be reproduced systematically.
1. Click Help
2. Click 'Check For Newer Version'

**Comment by giuspen** [comment]
It used to be broken on windows in the past but I'm pretty sure it works now. Please try it on 0.99.51 if there is no dialog, anyway something should be written on the status bar - either that you are running the latest or failed to get latest version info

**Comment by Metaxona** [comment]
anyway I can download a portable package or installer for windows 10 64 bit? all your site seems down and can't be accessed both .com and .net, even the link attached in this repo is not working.

**Comment by giuspen** [comment]
Can you access https://www.giuspen.net/cherrytree/#downl

**Comment by Metaxona** [comment]
![image](https://user-images.githubusercontent.com/110418886/202976741-0cce13ff-0c73-42f6-b424-d7514439ced1.png)

i get this error when i go there

**Comment by giuspen** [comment]
Ok I uploaded the windows release on github, see https://github.com/giuspen/cherrytree/releases

**Comment by Metaxona** [comment]
Thank you very much

**Comment by Metaxona** [comment]
![image](https://user-images.githubusercontent.com/110418886/203140401-5075549a-97ae-4494-971f-7b3eae74258e.png)

just checked the `check new version` in 0.99.51 in windows and this is what showed up instead of Running the latest version or something

**Comment by giuspen** [comment]
Makes sense because the version information is retrieved from https://www.giuspen.net/software/version_cherrytree that for some reason is inaccessible to you. I will try to use github releases to retrieve the latest version available starting from 0.99.52

**Comment by Metaxona** [comment]
Thanks again, I will now close this issue.
