### ISSUE TITLE
[Feature Request] Add option to disable tooltips

### ISSUE THREAD

**Issue by thdoan** [giuspen/cherrytree#2169]
**Is your feature request related to a problem? Please describe.**
I no longer need nor want to see the tooltips telling me what each menu item and toolbar icon does. I find them distracting.

**Describe the solution you'd like**
I wish there was an option to disable the tooltips.

**Comment by robot3498712** [comment]
Second that. More precisely, I don't mind tooltips for menu items (I display just the icons), but the tooltips for tree explorer items do bother me, since I can read the full text anyway, and stuff popping up constantly indeed is distracting while going through nodes to locate something.
A simple on/off switch would suffice.

**Comment by nmcltpx** [comment]
I third this, for the same reasons as the people above; tooltips popping up unnecessarily are a huge distraction for me.
A simple on/off, especially for the Tree would work.

**Comment by giuspen** [comment]
Ok I added the possibility to disable the tooltips of tree, menus and toolbar in v1.0.3 that I will try and release this weekend, you will have to manually edit the config.cfg file though as there is no UI yet

**Comment by nmcltpx** [comment]
I have just upgraded to 1.0.3 through homebrew.
I can confirm that the tooltip options get added after the application is quit.
(On a Mac, the config.cfg file is in `/Users/{username}/.config/cherrytree/config.cfg`)
The tooltip settings are:
```
tree_tooltips
menus_tooltips
toolbar_tooltips
```
On changing from true to false, the settings persist.
Thank you very much for making this change, it is much appreciated.

**Comment by giuspen** [comment]
these options are also in the preferences dialog in v1.1.0
