### ISSUE TITLE
keyboard shortcuts with Ctrl don't always work

### ISSUE THREAD

**Issue by turbodude** [giuspen/cherrytree#217]
Hello
So, very regularly after using Cherrytree for a few minutes or so, the shortcuts such as **Ctrl+Z/C/X/V/etc** and **Shift+Ctrl+whatever** just stop working for me. Their corresponding commands continue to work via the context menu and the menu bar, the problem is with the keyboard only.

So far I've been unable to identify at what point this happens exactly. What I'm doing is just moving around, duplicating and formatting some text, and copy-pasting it from Chrome.

This happens in rich text nodes, I can't say anything about two other types as I don't use them.

The issue seem to disappear if I relaunch cherrytree, but usually comes back pretty quickly.

I do have multiple input languages active, and my os is Windows 10 LTBS, but I believe I used to experience this on Win 7 as well.

**Comment by gBopHuk** [comment]
I confirm that doesn't work in windows7 and cherrytree 0.37.5.

**Comment by turbodude** [comment]
It looks like the trigger might be a copy and paste of a text from a browser, but the bug occurs only some times.

**Comment by miniboes** [comment]
I have the same issue. Ctrl and ctrl shift commands don't work at all for me.

**Comment by txe** [comment]
Fixed on Gtk3
