### ISSUE TITLE
Chinese fonts are not fully displayed, and the horizontal line at the top cannot be displayed

### ISSUE THREAD

**Issue by meijialun** [giuspen/cherrytree#2171]
**Version, Operative system**
CherryTree 0.99.52, Win10 x64

**Describe the bug**
Chinese fonts are not fully displayed, and the horizontal line at the top cannot be displayed, with Yahei 11. The previous versions were all displayed normally.

**To Reproduce**
1. Enter some Chinese like: 不，工
2. See what it looks like

**Screenshots**
![Snipaste_2022-11-28_14-27-14](https://user-images.githubusercontent.com/5047912/204208802-34b2af44-3797-47f9-90df-0b58b21b9ab9.png)

**Comment by netios** [comment]
it's same in korean.

Version, Operative system
CherryTree 0.99.52, Win10 x64

![image](https://user-images.githubusercontent.com/10227352/204437199-d718cd19-c0eb-4b84-8298-555ad4a3ef41.png)

**Comment by giuspen** [comment]
fixed in upcoming 0.99.55
