### ISSUE TITLE
German translation proposal

### ISSUE THREAD

**Issue by dagobert666** [giuspen/cherrytree#2173]
Hello,

cherrytree is a very nice software. :-)

Matthias Hoffmann does a great job, but i have 2 little changes for the german translation.
In the right click menu on a page is missing a r.
"Codezeile ode_ Selektion ausführen" must be "Codezeile oder Selektion ausführen"

In the preferences the english option "Theme" was translated into "Thema".  Thema is something like topic in german.
Much better is "Darstellung". (Or "Design")
"Icon-Thema" --> "Icon-Darstellung"
"Icons für dunkles Thema setzen" --> "Icons für dunkle Darstellung setzen"
"Icons für helles Thema setzen" --> "Icons für helle Darstellung setzen"

Thank you for creating Cherrytree

**Comment by giuspen** [comment]
Thank you @dagobert666 I applied your suggestions
