### ISSUE TITLE
Search Dialog Option For Excluded Nodes

### ISSUE THREAD

**Issue by metal450** [giuspen/cherrytree#2174]
The ability to mark nodes as "Exclude from Searches" is super useful (i.e. to exclude a parent "trash can" node).  However, occasionally, the need does arises to search them.  Currently, the way to do that is to edit the node, re-enable its subnodes for searching, do the search, then edit the node again and exclude it again.

It would be great if the search dialog could have an option to "Omit marked to exclude" or "override excludes" or similar, which could be toggled to do one-off global searches.  That's how it's done in the SourCherry Android app, & it works great.

**Comment by giuspen** [comment]
OK will be in upcoming 0.99.54

**Comment by metal450** [comment]
Awesome, thanks!
