### ISSUE TITLE
Unmovable separation bar with small window

### ISSUE THREAD

**Issue by pckeller29** [giuspen/cherrytree#2179]
Hi
I'm not sure this is a bug. Rather a limitation by design.
When Cherrytree window is a bit small (in width), but still quite usable, the separation bar between tree part and the main part is stuck. I mean, I can't slide it in any direction.
![cherrytree](https://user-images.githubusercontent.com/9974154/207014675-82aa06c3-7704-4693-92bc-52175bb8043d.png)
This unfortunate situation makes the tree view unreadable.
In the previous example, the window width is about 924 points.
To workaround this situation, I have to enlarge the window which frees the separation bar a bit. Actually, I have to resize until the bar is far enough from the left to let me see enough of the tree view.
Is it possible to remove this limitation ? I mean, allow the user to move the separation bar in any direction whatever the window width ?
I'm using a Windows 10 with Cherrytree v0.99.52.
Thanx

**Comment by pckeller29** [comment]
Just upgraded to 0.99.53 and same issue.

**Comment by pckeller29** [comment]
I understand you may not have enough time to answer all requests but can you maybe point me out which code / module is involved in this limitation please ?
Thanx a lot.

**Comment by pckeller29** [comment]
Well I'm a bit puzzled. Just tried on an Kubuntu system and the problem doesn't occur. I even compiled a 0.99.53, No issue, even on a smaller window.
So this problem only happens on Windows.
Any idea what can cause this annoying behavior ?
Thank you

**Comment by silverwings15** [comment]
it's only an issue on your windows device, i can resize the tree panel just fine on my windows laptop, even if it's a small window

**Comment by pckeller29** [comment]
OK, I will focus on that then. Thank you for your comment.

**Comment by pckeller29** [comment]
I got it. It was a setting from the Tree Explorer:

![CherryTreeSettings](https://user-images.githubusercontent.com/9974154/210591339-8021db54-9ce1-4acd-8249-54d958e7078d.png)

The editor window has to be wide enough to be able to display all the Last Visited Node Name Header.

![CherryTree pcg](https://user-images.githubusercontent.com/9974154/210591983-2c605f3d-6b1f-473d-a19a-11a58083a0d2.png)

That's why the separation bar is fully pushed to the left to allow the display of the Last Visited Nodes.

Reducing this setting from 10 to 8 solved my issue.

![cherrytree](https://user-images.githubusercontent.com/9974154/210593575-87caa830-7aab-483d-b7bc-30988ca0df35.png)

Thanx a lot @silverwings15 for helping figuring it out something I may have spent a long time to find!
