### ISSUE TITLE
Intallation deb - libfmt7 -> libfmt8 update

### ISSUE THREAD

**Issue by KrishnaTO** [giuspen/cherrytree#2182]
**Version, Operative system**
 -> CT_0.99.53.deb installation

**Describe the bug**
Looking to install latest from releases/...deb on LM21 where current installation is requiring libfmt7+ but only libfmt8+ is available. 

I think the dependencies for deb installation needs to be updated as libfmt7 isn't available anymore (may also be responsible for stuck apt release updates, current version 0.99.43)

Let me know if libfmt8 isn't compatible, then will have to find libfmt7 from...somewhere, maybe an alley.

**Comment by giuspen** [comment]
Linux Mint 21 is based on Ubuntu 22.04 LTS https://www.giuspen.net/cherrytree/#downl so either add the PPA or if you want to manually download the package look for https://launchpad.net/~giuspen/+archive/ubuntu/ppa/+packages and in the column series you need Jammy (22.04 LTS)

**Comment by KrishnaTO** [comment]
Sorry about that, not sure what happened between yesterday and today, but it is resolved.
