### ISSUE TITLE
Some way of marking task as "done"

### ISSUE THREAD

**Issue by sectroyer** [giuspen/cherrytree#2185]
I would like to be able to mark a branch as "done". With big documents I think CherryTree lacks a way to easilly distinguish which task are done or not. For example on the screenshot I attached. I would lik to look at the tree and clearly see that "smaller work 2" is done and both "task1" and "task 2" are done but not "task 3". It could a different icon colour, some checkmark, an ability cross over the text, or maybe text highlighting as in text document (with different colours for different meanings)?. For me it really doesn't matter as simply by looking at the tree of a complex document I can instantly see what is "done" or not. If it would be possible to add multiple "tags" (like with text highlight colours) it would be awesome but even simple "done" would make my life easier :)

<img width="279" alt="Zrzut ekranu 2022-12-24 o 14 45 11" src="https://user-images.githubusercontent.com/6706818/209438701-4723c431-cef4-43a9-bebf-6395fc95e5e0.png">

**Comment by Sisyfos3** [comment]
You can achieve this by right-clicking on the node (or select node and press F2), then check the box "Use selected Icon" and pick an icon of your liking. Or use "Use Selected Color" if that's more to your liking.

HTH,
Sisyfos3

**Comment by sectroyer** [comment]
After some testing I can say yeah it does what I wanted. To be honest I use both an icon and a custom text color. CherryTree even remembers the color I have selected and I can reuse it by simply clicking "tick" :) However it doesn't remember the last icon I have chosen. Could this be changed?

**Comment by Sisyfos3** [comment]
That is a question I forward to @giuspen . I think it's possible but what do I know ;-)

**Comment by RFImages** [comment]
I just use the "To do list" checkboxes for this It works nicely with three modes, 
Select your items and press the checkbox in the toolbar - all will be given a checkbox

☐ Not started
☒ on hold/pending
☑ Done

**Comment by mmajchr** [comment]
Well I don't want to make a checklist as an item on tree itself. What I want is to mark whole tree branch as "DONE". Using different icon and text color does the trick. However fact that CherryTree doesn't remember the icon is annoying 😄 Especially since it DOES remember text color.

**Comment by giuspen** [comment]
@mmajchr are you saying that you are losing the specified node icon? You are the first to report such issue, can you ensure you are using the latest 0.99.55 and you are not using an older version too on another PC?

**Comment by Sisyfos3** [comment]
@giuspen, if I understand his issue, he's not loosing the icon, it's just that Cherrytree doesn't remember the last selected icon for a node (in the same way it remembers the last selected color for a node).
Best regards and thank you for a wonderful piece of software.
Sisyfos3

**Comment by giuspen** [comment]
I added the memory of last selected icon same as already for the last selected colour, will be in next release
