### ISSUE TITLE
"Search in all nodes" doesn't show results after 2nd search.

### ISSUE THREAD

**Issue by tom-i** [giuspen/cherrytree#219]
When you search with "Search in all nodes", it find results without problem, but when you search again, I can see just greyed window of search dialog (as you can see on attached picture).

Steps to repro:
1. Run "Search in all nodes" e.g. by ~~"Ctrl + Alt + f"~~ **"Ctrl + Shift + f"**.
2. Search some string.
3. Click on result (you've been placed to searched node).
4. Repeat step 1.
5. Search another string.

BUG - dialog of results is grayed.

Version: updated GIT version

Output from terminal:
`/home/tomik/programs/git_cherrytree/modules/findreplace.py:238: Warning: invalid unclassed pointer in cast to 'GtkContainer'
  self.allmatchesdialog.show()
/home/tomik/programs/git_cherrytree/modules/findreplace.py:238: GtkWarning: IA__gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed
  self.allmatchesdialog.show()`

Picture:
![cherryt_2ndfind](https://cloud.githubusercontent.com/assets/16342114/21849163/b1f931cc-d804-11e6-8082-e0e987597fe3.png)

**Comment by giuspen** [comment]
Hi, what is the linux distro and version? What cherrytree version? Does it happen also with the current git master HEAD?

**Comment by tom-i** [comment]
Hi giuspen,
It's on my Fedora 22, and version of CherryTree from about is: 0.37.99, but I don't know where to check it GIT version (when I start it, update check last GIT version and update CherryTree).

**Comment by tom-i** [comment]
Did you reproduce it Giuspen? Or should I try enything else?

**Comment by giuspen** [comment]
Hi Tom, can you upgrade your fedora to 25? I cannot reproduce on ubuntu and
would rather try on latest stable fedora than an old system

**Comment by tom-i** [comment]
Maybe some day, but not now. It's my working computer, and we're now too busy with our release that I can't do less prio projects, especially upgrading my computer to newer Fedora. So maybe after one month when I'll have some "free" time. Otherwise I have to live with this bug. Thank you Guispen for you reply.

**Comment by giuspen** [comment]
It happened to me once on windows but wasn't able to reproduce since then :(

**Comment by tom-i** [comment]
I can reproduce it every time on my updated VoidLinux distribution at home. 
Oh.. jesus.. I wrote it badly, I wrote "Ctrl + Alt + f" but it should be **"Ctrl + Shift + f"** :(

**Comment by giuspen** [comment]
I will implement something and then ask you to try the github version

**Comment by giuspen** [comment]
Could you try the current github master HEAD version?

**Comment by tom-i** [comment]
You rock maaan... it works now :P 
Thank you so much ;)

**Comment by giuspen** [comment]
Great :)
