### ISSUE TITLE
add increase / decrease column size in the button list on the toolbar

### ISSUE THREAD

**Issue by jean-raphael** [giuspen/cherrytree#2195]
The ideal would probably be to have an area in the toolbar that displays different tools depending on the element selected or used

but for the moment, since the keyboard shortcuts don't work porperly on all the os, 

adding these buttons in the toolbar would be a good start,

because the right click then decrease size, is very slow

even more ideal solution for me, be able to create a table that is permanently at 100% of the page width, with the possibility to change the ratio of each column

**Comment by giuspen** [comment]
In the next version 0.99.55 the keyboard shortcuts for the table actions will be configurable in the preferences dialog and the same action will also be available to be added to the toolbar
