### ISSUE TITLE
Ubuntu 20.045, Cherrytree 0.99.53;  text that is present in Export to single txt file, cannot be found with shift+ctrl+F in cherrytree itself 

### ISSUE THREAD

**Issue by Newbieyy1945** [giuspen/cherrytree#2198]
**Version, Operative system**
State the Version and the Operative System/Desktop. Try the latest available version before reporting an issue.

**Describe the bug**

**To Reproduce**
If applicable, attach a non-personal document where the issue can be reproduced systematically.

**Screenshots**

**Comment by giuspen** [comment]
Try to run "Search" -> "Clear all exclusions from search"
