### ISSUE TITLE
CherryTree Codebox execution with Internal terminal not working.

### ISSUE THREAD

**Issue by Fran-P-github** [giuspen/cherrytree#2199]
## General information

- OS: Ubuntu 20.04.5 LTS x86_64

- Kernel: 5.15.0-53-generic

- Shell: zsh 5.8

- Terminal: gnome-terminal

- XTerm: XTerm(353)

- CherryTree: 0.99.53

## Issue
Hello, I'm new using CherryTree, I just downloaded it yesterday and I wanted to test it's features, I tried to test the code box and see if it would work. When I tried to run a simple `Hello world!` program in Python3 with the internal terminal it seems that somehow the code hangs on and I can't see any output (note that I tested it without the internal terminal option and it worked perfectly), I just see the command that is put into the Xterm terminal, which is the default one: `python3 <tmp_src_path>`. Just in case, in the preferences section I also have the default command which is: `xterm -hold -geometry 180x45 -e "<command>" &`

I also noticed that when I run the program with the internal terminal and I don't see any output, if I press the **reset** button the program tries to kill a process that apparently doesn't exist, my computer starts doing noise and some programs don't work properly, for example "**Screen**" which is a terminal emulator / multiplexer just like **XTerm**.

### External terminal (Works)
![External terminal output](https://user-images.githubusercontent.com/77561295/212492320-3bd72cfe-b928-46f2-a1a1-5d3bec485df9.png)

![External terminal debug](https://user-images.githubusercontent.com/77561295/212492343-5f2d408d-d975-4457-831e-96ff39c068c8.png)

### Internal terminal (Doesn't work)
![Internal terminal no output](https://user-images.githubusercontent.com/77561295/212493965-e55de114-6f1f-4ae3-aff1-d53df3169d2b.png)

![Internal terminal debug messages](https://user-images.githubusercontent.com/77561295/212493975-181a0e8b-2517-4c93-9e76-4cac928fdde4.png)

At this point I'm honestly clueless of what could cause the error and how could I fix this, if I'm being dumb and missing something silly I'm really sorry for the waste of time, any suggestions / ideas / instructions to fix this error would be appreciated.

Thanks in advance and happy new year.

**Comment by giuspen** [comment]
Hello @Fran-P-github and happy new year to you.
Can you specify how you installed cherrytree?
e.g. ppa/snap/appimage/flatpak/...

**Comment by Fran-P-github** [comment]
Hello @giuspen I installed cherrytree following the Ubuntu instructions in the readme file, I copied all the commands to install the dependencies and documentation, and compile and run cherrytree. I'm not really sure which type of installation that would be called.

**Comment by giuspen** [comment]
Ok. Could you try to download and run the AppImage from https://www.giuspen.net/cherrytree/#downl and report if it behaves the same?

**Comment by Fran-P-github** [comment]
Sure, I downloaded the AppImage, executed it and it behaved exactly the same.

**Comment by giuspen** [comment]
Could you temporarily restore the default shell in your system (I suppose dash or bash) and try again? I will also try zsh to see if that is causing the issue but I'm having some connectivity issues at the moment

**Comment by Fran-P-github** [comment]
I just changed the default shell to bash and now the internal terminal works perfectly, the reset button also works.

**Comment by giuspen** [comment]
Ok great I will push something later or tomorrow that I would like you to try after restoring your favourite shell zsh. I'll let you know when I push the change

**Comment by Fran-P-github** [comment]
Sure @giuspen, thank you so much for your time and help.

**Comment by giuspen** [comment]
Thanks to you for reporting @Fran-P-github . I pushed a commit that fixed the issue for me after I also tried to use zsh and the integrated terminal wasn't working anymore (it didn't hang for me though).
It would be useful if you could git pull, rebuild and let me know if it works for you as well with zsh set as your default shell.

**Comment by Fran-P-github** [comment]
I rebuilt cherrytree and the integrated terminal with zsh now works!! But, (I want to mention it so you know, but I don't pretend you to fix it because the main issue now works fine) I think due to the package "powerlevel10k" that I've installed, which uses its own characters and colors doesn't work and ends showing the code that it should use to work, so it looks like this:

How it should look:
![powerlevel10k original look](https://user-images.githubusercontent.com/77561295/212573546-0682d74a-c02b-45ee-a388-eb061c0e067a.png)

How it looks in the integrated terminal:
![powerlevel10k internal terminal](https://user-images.githubusercontent.com/77561295/212573561-7f65c155-c9f0-4bfc-b950-64c5f6f5c30f.png)

But of course, again, I don't pretend you to fix this because it works perfectly, I just want to report it so you know about it.
