### ISSUE TITLE
ctd file is not opened by cherrytree if path contains diacritic

### ISSUE THREAD

**Issue by GoogleCodeExporter** [giuspen/cherrytree#22]
```
What steps will reproduce the problem?
1. Place test.ctd file into directory e.g. "c:\ěščřž".
2. Select it and press Enter...

What is the expected output? What do you see instead?
Cherrytree starts but the file is not opened.
If the path does not contain diacritic, the file is opened.

What version of the product are you using? On what operating system?
CherryTree 0.35.6

Thank you.
Stanislav Havelka

```

Original issue reported on code.google.com by `stand...@gmail.com` on 5 Jan 2015 at 2:02

**Comment by fracte** [comment]
The same happens if the cherrytree filename contains diacritic too.

What version of the product are you using? On what operating system?
CherryTree 0.36.9 on Windows 8.1 in french language

Thank you,
Samuel Poette.

**Comment by giuspen** [comment]
Hello Samuel, are you available to test a development version?

**Comment by txe** [comment]
The issue with not-Latin symbols in ctd file path is fixed.
The issue with not-Latin symbols in cherrytree path can't be fixed.
