### ISSUE TITLE
Support for HiDPI displays

### ISSUE THREAD

**Issue by crestone** [giuspen/cherrytree#220]
Need support for HiDPI displays.
For GTK3 HiDPI currently supported, look https://wiki.archlinux.org/index.php/HiDPI but need HD resolution for all icons.
Can you implement support for HiDPI?
Thanks.

**Comment by giuspen** [comment]
The plan is to migrate to gtk3 after upcoming 0.38.x. All the icons have the svg sources so the current resolution of 48x48 of the png can be increased as desired. What resolution do you advise?

**Comment by manad777** [comment]
Thanks @giuspen, looking forward to it! 

High-DPI has been a curse on my new laptop, the cons (lack of app support) far outweight the pros at this point in time. I think it's gonna be another 5 years before I can recommend a high-DPI laptop.

Regarding your question, I've never used GTK, and never had to deal with high resolutions in my own apps, so sorry if this is wrong advice. But couldn't you pick the highest res within reason (1024x1024?) and let GTK scale the image down automatically to the button size when you set it as the button's background? Wouldn't that make things future-proof?

**Comment by giuspen** [comment]
Hi, I will try and use vectorial lmages (svg) directly, that should work fine in gtk3 on windows

**Comment by Tajnymag** [comment]
I would second that. On my machine, text is sealed properly, but icons are far too small. Running Arch.

**Comment by chppppp** [comment]
Bumping this thread :) My Surface Book 2 resolution is 3000x2000 and when I copy/paste images from Snipping Tool into CherryTree it looks atrocious. Any tips on mitigating this would be appreciated!!

**Comment by djbajic** [comment]
Same here, using linux mint with 3840x2160 and icons are barely visible. Congrats for the program, by the way, really useful, I use it on a daily basis!

**Comment by ma-sadeghi** [comment]
Hi @giuspen, can I ask what the status is on HiDPI support? Thanks :)

**Comment by giuspen** [comment]
Hi @ma-sadeghi nothing will be done on the Pygtk2 version, this is something that will come after the Gtkmm3 version

**Comment by ma-sadeghi** [comment]
Thanks for your quick reply @giuspen. Do you have an ETA?

**Comment by giuspen** [comment]
For the Gtkmm3 to fully replace the current Pygtk2 this summer, then we'll see...

**Comment by malventano** [comment]
It may be useful to first just support native resolution text on high DPI displays, as text on high DPI displays renders blurry and can be straining on the eyes.

**Comment by txe** [comment]
it would be nice If someone can check HiDPI with 0.99

**Comment by aceluby** [comment]
Checked the latest version (.99) and HiDPI seems to be working as it should. Looks great!

**Comment by txe** [comment]
That's great, thanks for checking! Closing then
