### ISSUE TITLE
Ubuntu 22.04.1, Cherrytree 0.99.53 crashes after a search : 

### ISSUE THREAD

**Issue by Newbieyy1945** [giuspen/cherrytree#2201]
**Version, Operative system**
State the Version and the Operative System/Desktop. Try the latest available version before reporting an issue.

**Describe the bug**

**To Reproduce**
If applicable, attach a non-personal document where the issue can be reproduced systematically.

**Screenshots**

As my issue #2198 could not be solved I decided to install a new Ubuntu 22.04.1 and after that I installed and started Cherrytree and created  a new Linux_new.ctb and then I used the exported txt file to build up a new .ctb. Took some time but it seemed to work. Some time later when I searched for the text 'spotify'  Cherrytree crashed. The crash is reproducable so I booted 22.04.1 again and reproduced the problem in a clean syslog. I have included the relevant part of the syslog below:

I started Cherrytree at this moment

Jan 19 17:02:39 newbie-Z490M systemd[1626]: Started Application launched by gnome-shell.
Jan 19 17:02:39 newbie-Z490M systemd[1626]: Started snap.cherrytree.cherrytree.7b8abfce-c094-4205-96c0-652a8186dc7f.scope.
Jan 19 17:02:39 newbie-Z490M systemd[1]: tmp-snap.rootfs_MI4yBH.mount: Deactivated successfully.
Jan 19 17:02:40 newbie-Z490M kernel: [  138.287069] kauditd_printk_skb: 4 callbacks suppressed
Jan 19 17:02:40 newbie-Z490M kernel: [  138.287070] audit: type=1326 audit(1674144160.165:84): auid=1000 uid=1000 gid=1000 ses=3 subj=snap.cherrytree.cherrytree pid=2991 comm="cherrytree" exe="/snap/cherrytree/64/bin/cherrytree" sig=0 arch=c000003e syscall=314 compat=0 ip=0x7eff56d16a3d code=0x50000
Jan 19 17:02:40 newbie-Z490M cherrytree_cherrytree.desktop[2991]: [2023-01-19 17:02:40.233] [   ] [debug] /home/newbie/snap/cherrytree/64/.config/cherrytree/config.cfg parsed
Jan 19 17:02:40 newbie-Z490M cherrytree_cherrytree.desktop[2991]: [2023-01-19 17:02:40.391] [   ] [debug] autosave is started
Jan 19 17:02:40 newbie-Z490M cherrytree_cherrytree.desktop[2991]: [2023-01-19 17:02:40.493] [   ] [debug] Node name: log9maart
Jan 19 17:02:50 newbie-Z490M systemd[1626]: Started Application launched by gnome-session-binary

I did 'search spotify' in cherrytree and Cherrytree crashes

Jan 19 17:04:00 newbie-Z490M cherrytree_cherrytree.desktop[2991]: [2023-01-19 17:04:00.150] [   ] [debug] Node name: 16.04.2
Jan 19 17:04:00 newbie-Z490M cherrytree_cherrytree.desktop[2991]: [2023-01-19 17:04:00.185] [   ] [debug] Node name: 18.04
Jan 19 17:04:00 newbie-Z490M cherrytree_cherrytree.desktop[2991]: [2023-01-19 17:04:00.188] [   ] [debug] Node name: 18.04.3
Jan 19 17:04:00 newbie-Z490M cherrytree_cherrytree.desktop[2991]: [2023-01-19 17:04:00.191] [   ] [debug] Node name: 18.04.4
Jan 19 17:04:00 newbie-Z490M cherrytree_cherrytree.desktop[2991]: [2023-01-19 17:04:00.222] [   ] [debug] Node name: 20.10 Z490M
Jan 19 17:04:00 newbie-Z490M cherrytree_cherrytree.desktop[2991]: [2023-01-19 17:04:00.223] [   ] [debug] Node name: rampDec2022
Jan 19 17:04:00 newbie-Z490M cherrytree_cherrytree.desktop[2991]: [2023-01-19 17:04:00.223] [gtk] [critical] gtk_text_iter_set_line_offset: assertion 'char_on_line <= chars_in_line' failed
Jan 19 17:04:00 newbie-Z490M cherrytree_cherrytree.desktop[2991]: [2023-01-19 17:04:00.223] [gtk] [critical] gtk_text_iter_set_line_offset: assertion 'char_on_line <= chars_in_line' failed
Jan 19 17:04:00 newbie-Z490M cherrytree_cherrytree.desktop[2991]: [2023-01-19 17:04:00.244] [   ] [debug] Node name: 22.04.1 Z490M
Jan 19 17:04:00 newbie-Z490M cherrytree_cherrytree.desktop[2991]: [2023-01-19 17:04:00.267] [   ] [debug] Node name: snap
Jan 19 17:04:00 newbie-Z490M cherrytree_cherrytree.desktop[2991]: [2023-01-19 17:04:00.274] [   ] [debug] Node name: spotify
Jan 19 17:04:00 newbie-Z490M cherrytree_cherrytree.desktop[2991]: [2023-01-19 17:04:00.290] [   ] [debug] Node name: VLC
Jan 19 17:04:00 newbie-Z490M cherrytree_cherrytree.desktop[2991]: [2023-01-19 17:04:00.291] [   ] [debug] Node name: Audacity
Jan 19 17:04:00 newbie-Z490M cherrytree_cherrytree.desktop[2991]: [2023-01-19 17:04:00.306] [   ] [debug] Node name: InstallOud
Jan 19 17:04:00 newbie-Z490M cherrytree_cherrytree.desktop[2991]: [2023-01-19 17:04:00.333] [   ] [debug] Node name: log9maart
Jan 19 17:04:00 newbie-Z490M gnome-shell[1834]: WL: error in client communication (pid 2991)
Jan 19 17:04:02 newbie-Z490M cherrytree[2991]: Error flushing display: Broken pipe
Jan 19 17:04:02 newbie-Z490M systemd[1626]: snap.cherrytree.cherrytree.7b8abfce-c094-4205-96c0-652a8186dc7f.scope: Consumed 5.105s CPU time.
Jan 19 17:05:01 newbie-Z490M CRON[3133]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Jan 19 17:05:28 newbie-Z490M gnome-shell[1834]: libinput error: event4  - Dell Dell USB Keyboard: client bug: event processing lagging behind by 24ms, your system is too slow
Jan 19 17:05:32 newbie-Z490M systemd[1]: Starting Download data for packages that failed at package install time...
Jan 19 17:05:32 newbie-Z490M systemd[1]: update-notifier-download.service: Deactivated successfully.
Jan 19 17:05:32 newbie-Z490M systemd[1]: Finished Download data for packages that failed at package install time.
Jan 19 17:05:33 newbie-Z490M dbus-daemon[852]: [system] Activating via systemd: service name='org.freedesktop.timedate1' unit='dbus-org.freedesktop.timedate1.service' requested by ':1.63' (uid=0 pid=871 comm="/usr/lib/snapd/snapd " label="unconfined")
Jan 19 17:05:33 newbie-Z490M systemd[1]: Starting Time & Date Service...
Jan 19 17:05:33 newbie-Z490M dbus-daemon[852]: [system] Successfully activated service 'org.freedesktop.timedate1'
Jan 19 17:05:33 newbie-Z490M systemd[1]: Started Time & Date Service.

**Comment by giuspen** [comment]
Can you share privately this document with me? (where searching for "spotify" cherrytree 0.99.53 crashes)
Can you try another package type different than snap https://www.giuspen.net/cherrytree/#downl and report if it still crashes?
For example the AppImage is a single file very easy/quick to download and run

**Comment by Newbieyy1945** [comment]
Dear Mr. Penone,

I downloaded CherryTree-0.99.53-x86_64.AppImage , it is now in my 
./Download directory and I made it executable. When I run it there are 
no crashes searching for 'spotify'.  Looks like a 'snap' problem I think

thanks

Marius Hentzen

thanks

Giuseppe Penone schreef op 2023-01-21 21:38:

> Can you share privately this document with me? (where searching for 
> "spotify" cherrytree 0.99.53 crashes)
> Can you try another package type different than snap 
> https://www.giuspen.net/cherrytree/#downl and report if it still 
> crashes?
> For example the AppImage is a single file very easy/quick to download 
> and run
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>



Links:
------
[1] 
https://github.com/giuspen/cherrytree/issues/2201#issuecomment-1399328277
[2]

**Comment by giuspen** [comment]
Thank you @Newbieyy1945 I will try to reproduce the crash with the snap package.
Note that the package that I advice on ubuntu based distributions is the deb package which you can install as follows from a terminal, adding the official PPA repository:
sudo add-apt-repository ppa:giuspen/ppa
sudo apt update
sudo apt install cherrytree
This way it will update automatically when I release new versions.

**Comment by Newbieyy1945** [comment]
Giuseppe Penone schreef op 2023-01-22 20:07:

> Thank you @Newbieyy1945 [1] I will try to reproduce the crash with the 
> snap package.
> Note that the package that I advice on ubuntu based distributions is 
> the deb package which you can install as follows from a terminal, 
> adding the official PPA repository:
> sudo add-apt-repository ppa:giuspen/ppa
> sudo apt update
> sudo apt install cherrytree
> This way it will update automatically when I release new versions.
> 
> --
> Reply to this email directly, view it on GitHub [2], or unsubscribe 
> [3].
> You are receiving this because you were mentioned.Message ID: 
> ***@***.***>

Thanks mr Penone,

Until Ubuntu 18.04 I always used this method and I will used it again in 
the future,

Regards

Marius Hentzen

Links:
------
[1] https://github.com/Newbieyy1945
[2] 
https://github.com/giuspen/cherrytree/issues/2201#issuecomment-1399576292
[3]

**Comment by Newbieyy1945** [comment]
I installed Cherrytree with the PPA repository and the problem was solved, apparently a "SNAP" induced problem
