### ISSUE TITLE
Build error with cmake

### ISSUE THREAD

**Issue by jean-raphael** [giuspen/cherrytree#2203]
CMake Error at tests/CMakeLists.txt:10 (add_subdirectory):
  The source directory

    [PATH]/cherrytree/tests/googletest

  does not contain a CMakeLists.txt file.

CMake Error at tests/CMakeLists.txt:31 (set_target_properties):
  set_target_properties Can not find target to add properties to: gtest

CMake Error at tests/CMakeLists.txt:32 (set_target_properties):
  set_target_properties Can not find target to add properties to: gtest_main

CMake Error at tests/CMakeLists.txt:33 (set_target_properties):
  set_target_properties Can not find target to add properties to: gmock

CMake Error at tests/CMakeLists.txt:34 (set_target_properties):
  set_target_properties Can not find target to add properties to: gmock_main

**Comment by giuspen** [comment]
looks like you didn't do:
git submodule update --init

**Comment by jean-raphael** [comment]
hmm rtfm obviously =)

there is a doc to explain  how cherrytree is struxtured ? and a doc to explain what library do what ?

**Comment by giuspen** [comment]
No unfortunately no docs, even the manual is very old I should update it myself but that takes a lot of time... off the development

**Comment by jean-raphael** [comment]
> No unfortunately no docs, even the manual is very old I should update it myself but that takes a lot of time... off the development

it's true but on the other hand it may help to gain new developers, in any case I'm interested if I can contribute.
Anyway i will try to understant it

**Comment by travis-pluto** [comment]
Thanks giuspen I ran into the same error doing a build.sh deb and that resolved it.  I have used your app for a long time and wanted to update.  Thanks a lot for an amazing app!
