### ISSUE TITLE
Not possible to change Hotkeys for tabe manipulation

### ISSUE THREAD

**Issue by Groberen** [giuspen/cherrytree#2219]
**Is your feature request related to a problem? Please describe.**
The built in keyboard shortcuts for manipulating tables all includes Ctrl,, brackets and curly brackets. Because the Norwegian keyboard layout doesn't have separate keys for brackets, none of those keyboard shortcuts can work.
The only workaround is using mouse, that can be very tedious - extremely tedious if having a big table that must be adjusted on regular basis.

**Describe the solution you'd like**
Add to Preferences - Keyboard Shortcuts, ability to change for the following actions regarding table: Move colomn right/left, Move row updown, and Increase/Decrease Column width.

**But also - keyboard shortcuts priority**
The keyboard shortcuts for table manipulation shouldn't get in conflict if same keyboard combination are used to manipulate nodes, so those keyboard shortcuts must work only when the cursor is placed within a table.

**Comment by giuspen** [comment]
In the next version 0.99.55 the keyboard shortcuts for the table actions will be configurable in the preferences dialog.

About re-using the same keyboard shortcut for multiple actions according to what is focused, that is more tricky, may happen in future but not yet.
