### ISSUE TITLE
Cherrytree crashes during PDF export

### ISSUE THREAD

**Issue by ciku78** [giuspen/cherrytree#2227]
**Version, Operative system**
Windows 10 21H2
Cherrytree 0.99.54

**Describe the bug**
The program crashed when I try to export a document in PDF. I  have applied some custom setting and suspect it's caused by the settings because it does not happen with the standard setup and the same document. 

**To Reproduce**
I can give my custom settings and the file. The issue happens every time I try to export, also on other systems/PCs with the same setting.

**Comment by giuspen** [comment]
Yes please help me reproduce the issue detailing the settings that cause it and possibly sharing with me a document that causes the crash specifying the export settings. If you want to send the document privately to me please look at help--about Dialog for my email

**Comment by giuspen** [comment]
After receiving the data privately I can confirm that I can reproduce the crash. I'll update here once I have a fix.

**Comment by giuspen** [comment]
This has been now fixed. The fix will be in 0.99.55. Thanks for reporting.
