### ISSUE TITLE
Feature Request: COLUMN/BOX EDIT MODE FOR US CODERS (and you too)

### ISSUE THREAD

**Issue by RFImages** [giuspen/cherrytree#2232]
As an FPGA developer I use Notepad++ for coding and cherrytree for logging/notes.

Notepad++ and most advanced text editors offer a life changing Column or block select edit mode that allows you to make any rectangular text selection by holding down the alt key while drawing a box:
![image](https://user-images.githubusercontent.com/18133626/221700810-2b909926-d09c-49c1-b7d4-08e8b1766f95.png)

I use this almost exclusively when copy/pasting blocks of text, and it is difficult to go back and forth to Cherry tree not being able to have the same feature.

Please implement! A necessity for coders.

Of course it would only be useful with monospaced fonts, but that's ok! There should be a special text edit mode for code anyway. There are "codeboxes" but they don't look too versatile or feature laden, (underdeveloped)

**Comment by giuspen** [comment]
Actually there is a column edit mode in cherrytree, even though not as powerful.
If you hold down Ctrl and Alt, then you can select in column edit mode with the mouse (inspired by https://www.geany.org/ / https://www.scintilla.org/).
This supports only removing and adding characters at the moment. I thought about adding clipboard support but nobody ever asked for it, you are actuallt the first.

**Comment by RFImages** [comment]
oh I did not know that - yes I see that it adds a multirow cursor but I do not see that I can select a block of text for editing (say I want to delete/copy/cut multiple columns of text from multiple rows, I don't see that I can do it in one keystroke.. Copy pasting (between apps or dociuments) is really what makes it powerful, It would be great if you can build on this.

**Comment by RFImages** [comment]
Oh wait I do see that there is a start and finish cursor, so I guess copy pasting is the missing feature.

**Comment by giuspen** [comment]
that's right, the clipboard is the next step (and some cosmetic improvements)

**Comment by giuspen** [comment]
The clipboard support will be in upcoming 0.99.56 (for now no right click menu items for copy/cut, only via keyboard shortcuts)

**Comment by pdelrot-samea** [comment]
Hello, I will not add a duplicate : this block mode/column edit would really help me.
Best regards, Pascal

**Comment by giuspen** [comment]
@pdelrot-samea this is already available in the current version 1.0.0

Just hold Ctrl+Alt down while you do the selection with the mouse, then you can either type characters (which will be added in column mode) or use the clipboard via Ctrl+C / Ctrl+X / Ctrl+V

**Comment by pdelrot-samea** [comment]
Bonjour,
Great ! got it.

May I suggest few improvements for the future when you will have some time.
- during selection, the complete line still with a blue background (as for classic line selection). During first try, because of this, I first thought that the bloc selection was not working
- the thin vertical lines for selection border visibility may be improved.

I have in mind Notepad++ or Kate.
In Kate, a nice feature during bloc mode selection is : clic top right corner, clic bottom left corner (or reverse...) and you get the selected bloc (no mouse drag).

Finally, thanks for creating cherrytree.
Best regards, Pascal

**Comment by giuspen** [comment]
Cheers @pdelrot-samea 😉

**Comment by RFImages** [comment]
> 

I finally upgraded to 1.0.0 and the column mode works nicely, except when it doesn't.

Here is an example:
I did ctrl-alt and made this selection, I saw the begin and end markerss which dissappeared when I attempted a screen cap but as you can see it copy pasted the entire blue selection instead of the demarked column.

![image](https://github.com/giuspen/cherrytree/assets/18133626/7cafc16a-43fa-4375-a494-e1e6de34e348)

![image](https://github.com/giuspen/cherrytree/assets/18133626/0ba731e4-1a79-4fb8-980e-9fa369ee4d26)

Other times it has functioned as expected.

![image](https://github.com/giuspen/cherrytree/assets/18133626/87563c9c-b565-4e4f-aab6-6e81218583a8)

It seems to be an issue if the line wraps around.

 I do agree that it would be helpful (less initially confusing) if the blue selection background of the selected area only highlighted the actual selection area of the column mode, but once you understand it, it works. 

Thank you @giuspen for implementing this and your excellent responsiveness to issues and feature requests. 
Cheers! 
Or should I say Cherries!
