### ISSUE TITLE
Executing C# dotnet 

### ISSUE THREAD

**Issue by Adam-wil** [giuspen/cherrytree#2234]
Hi Giuspen, 

Firstly, great work on CherryTree, its my new NoteBook! 

I would like to know how to execute C# from the codeblocks. 

Can you help me with some more instructions setting up the preferences / tmp path please. As I understand it please see images below: 

To Run the C# 

![image](https://user-images.githubusercontent.com/58685502/222623970-44d8c0c6-7705-4b30-b1f9-ebeb4bbf0df3.png)

Do I need to set the C:\Program Files\CherryTree\mingw64\bin> to the Environment Variable Path ? 

![image](https://user-images.githubusercontent.com/58685502/222624016-6d4fce0c-ffcd-4ed8-bfcb-a82640d0aa64.png)

![image](https://user-images.githubusercontent.com/58685502/222624067-f461a44a-8423-4a96-ab4b-e0ee9bb371fc.png)

Any help would be appreciated. Cheers Adam

**Comment by giuspen** [comment]
Hi @Adam-wil 
The command that you need to write is:
`csc /out:<tmp_bin_path> <tmp_src_path> && <tmp_bin_path>`
And a valid Hello World would be:
```
namespace HelloWorld {
class Hello {
    static void Main(string[] args) {
        System.Console.WriteLine("Hello World!");
    }
}
} // namespace HelloWorld
```
And if the codebox type is `c-sharp` and the folder containing csc.exe is in the system Path ( C:\Windows\Microsoft.NET\Framework64\v4.0.30319 ), you will get:
```
Microsoft (R) Visual C# Compiler version 4.8.4084.0
for C# 5
Copyright (C) Microsoft Corporation. All rights reserved.

This compiler is provided as part of the Microsoft (R) .NET Framework, but only supports language versions up to C# 5, which is no longer the latest version. For compilers that support newer versions of the C# programming language, see http://go.microsoft.com/fwlink/?LinkID=533240

Hello World!

C:\Program Files\CherryTree\mingw64\bin>
```

**Comment by Adam-wil** [comment]
Thanks Guispen, 

I managed to get the c-sharp compiling. Saving the snippet as a testc.cs by right clicking the snippet and saving as cs. Then adding it to the file path worked. 

![WhatsApp Image 2023-03-04 at 14 39 58](https://user-images.githubusercontent.com/58685502/222876399-91e85a5a-97a4-40f9-9ccd-908d63f6a1a7.jpg)


Thanks from you help on this!

**Comment by giuspen** [comment]
No problem I added support command in the default list in upcoming 0.99.55 and a dedicated icon for c-sharp
