### ISSUE TITLE
I cannot save any new file for any format

### ISSUE THREAD

**Issue by midoelomda** [giuspen/cherrytree#2244]
**Version, Operative system**
Linux Mint 21.1 Cinnamon. 

**Describe the bug**
I already have the last version of Cherrytree installed on my laptop, but I cannot save any file at any path.
I searched on google but I did not got any solution, I was work with Cherrytree on my previous OS (Windows 10).
I love this app and want to work with it on Linux.
Screenshot attached.

**Screenshots**
![Screenshot from 2023-03-17 10-37-20](https://user-images.githubusercontent.com/127295730/225855922-ac9ee8b8-5f33-4d5c-a2a2-0682e3a63b00.png)
![Screenshot from 2023-03-17 10-37-02](https://user-images.githubusercontent.com/127295730/225855932-0fb90f44-fb42-4ab9-ba0e-27bba55c0227.png)
![Screenshot from 2023-03-17 10-36-04](https://user-images.githubusercontent.com/127295730/225855935-df8d77af-d3d7-40b9-a7d8-c4321bed24e3.png)

**Comment by midoelomda** [comment]
I re-install it again via same method (PPA)
Still have same issue.

**Comment by giuspen** [comment]
Ok no problem
