### ISSUE TITLE
Issue: No package 'gtkmm-3.0' found

### ISSUE THREAD

**Issue by pukkie1309** [giuspen/cherrytree#2246]
Hi all.
Firstly, I am new to Github so please forgive if my post is at irrelevant place.
I am trying to install cherrytree on my VM Parrot Pwnbox and I am having a issue that is No package 'grkmm-3.0' found.
Please help me solve the problem.
Many thanks for everyone helps.
I also upload a screenshot of my installation issue below
![image](https://user-images.githubusercontent.com/36656592/227786112-de0a2157-036e-429c-b676-e1579b2e9cb6.png)

**Comment by giuspen** [comment]
I haven't heard about this Parrot before but looks like it's Debian based so look for https://github.com/giuspen/cherrytree#building-cherrytree-on-ubuntu

**Comment by pukkie1309** [comment]
> I haven't heard about this Parrot before but looks like it's Debian based so look for https://github.com/giuspen/cherrytree#building-cherrytree-on-ubuntu

Thank Giuspen.
Parrot is Debian based and I also followed Installation Guide to build CherryTree on Ubuntu but the issue is still there. I tried to reinstall the libgtkmm-3.0-dev and the result is like this: 
![image](https://user-images.githubusercontent.com/36656592/227828626-198720ef-79c4-481d-9fc5-17f17b4b0359.png)

**Comment by pukkie1309** [comment]
> I haven't heard about this Parrot before but looks like it's Debian based so look for https://github.com/giuspen/cherrytree#building-cherrytree-on-ubuntu

Thank you for your help Giuspen. I found the solution by  following the suggestion to install the missing or unmet dependencies and simultaneously installing the old packages with the up-to-date packages.
