### ISSUE TITLE
[0.38.100] Time filter button doesn't show date/time

### ISSUE THREAD

**Issue by piyo-gh** [giuspen/cherrytree#225]
Windows 10 x64 Japanese

Time filter button doesn't show selected date/time. It is always empty.
So, I must click button to check current setting to see.

![ct01](https://cloud.githubusercontent.com/assets/18474085/22408970/a5c000a0-e6c5-11e6-9734-72f257187bdc.png)

**Comment by giuspen** [comment]
Can you see the timestamp on the status bar? Can you insert a timestamp in the text? Do you have standard or customised timestamp format in the preferences dialog?

**Comment by piyo-gh** [comment]
I installed 0.38.100 standalone for test. So, I didn't modifyed timestamp format.
I can insert timestamp, it is like `2017/01/30 - 09:02`.
And statusbar shows timestamp, too.

**Comment by giuspen** [comment]
Thanks, should be fixed with https://github.com/giuspen/cherrytree/commit/0126cccdd7ae255724eec43e8b81e1f70886e38f
