### ISSUE TITLE
Line wrapping in code boxes

### ISSUE THREAD

**Issue by rayylu** [giuspen/cherrytree#2251]
**Problem**
I cannot find a way to enable line wrapping in code boxes. This makes me have to scroll horizontally to view an entire line of code in a cherrytree window with limited size.

**Proposed Solution**
Add an option to enable line wrapping for individual code boxes

**Comment by giuspen** [comment]
If you disable the codebox auto resize, then you should be able to control the width and have the wrapping

**Comment by rayylu** [comment]
Thanks, I didn't find that option. For anyone else looking for it, Rich Text -> Expand CodeBoxes Automatically
