### ISSUE TITLE
app crashes if sorting table

### ISSUE THREAD

**Issue by schnaggi** [giuspen/cherrytree#2253]
**Version, Operative system**
windows 10 22h2
cherrytree 0.99.55 from portableapps.com

**Describe the bug**
app crashes after sorting table's rows

**To Reproduce**
If applicable, attach a non-personal document where the issue can be reproduced systematically.
I created a node and a table in it, I filled the table with some data but not all cells are filled. Now I sort the table's rows.
In the crashfile the app hangs, in my "productive" file the file crashes.

**Screenshots**
[crashtest.zip](https://github.com/giuspen/cherrytree/files/11151235/crashtest.zip)

**Comment by giuspen** [comment]
I can reproduce, thanks for reporting I'll sort it out shortly

**Comment by giuspen** [comment]
Will be fixed in 0.99.56
