### ISSUE TITLE
File naming convention used?

### ISSUE THREAD

**Issue by tleylan** [giuspen/cherrytree#2255]
It isn't a feature or a bug. I'm a little confused by the file naming convention used.

Using the following test file name this is surely the active file
testData.ctx23518001941.ctx

Three additional files show up in the folder as follows.
testData.ctx23518001941.ctx~
testData.ctx23518001941.ctx~~
testData.ctx23518001941.ctx~~~

Are these backups?
Would I need to restore one or does the software determine whether something is wrong with the main file?
Can they be prevented from being created?

I also don't recall adding all those digits to the file name.
Can I rename the active file and remove them?

**Comment by giuspen** [comment]
Yes are the backups, the added number is a timestamp, you can disable the backups in the preferences dialog but you should not. I'll get back on this I need to revisit the need for the timestamp and why the backups include the timestamp, I forgot about that. Can you specify your OS and version of cherrytree?

**Comment by tleylan** [comment]
I appreciate the info. I have version 0.99.55 and I'm using Windows 11. It isn't a major issue more curiosity than anything else.
