### ISSUE TITLE
resize font with mouse wheel changes it to SANS even in config file

### ISSUE THREAD

**Issue by mvsite** [giuspen/cherrytree#2257]
**Version, Operative system**
Current CherryTree 0.99.55 on Windows 11

**Describe the bug**
After I set the fonts either in the interface or in the config file, then at any point if I resize them such as with ctrl+mousewheel, then the font changes to "Sans" and this is also changed in the config file.

**To Reproduce**
1. Run cherrytree and have some text in the display
2. set a custom font such as Monospace
3. use the ctrl+mousewheel to zoom in changing the font size to a different size
4. at this point it will revert to Sans

**Comment by giuspen** [comment]
Confirmed on Win10

**Comment by giuspen** [comment]
Thanks for reporting this, it will be fixed in 0.99.56
