### ISSUE TITLE
Crash on MacOS: Trace/BPT trap: 5

### ISSUE THREAD

**Issue by kaktusztea** [giuspen/cherrytree#2261]
**Version, Operative system**
Cherrytree 0.99.55 (brew), MacOS Monterey 12.6.4 

**Describe the bug**
I start cherrytree, but when I select a .ctx file and try to open it, the app crashes always. It doesn't matter which .ctx it is.

```shell
$ cherrytree
[2023-04-15 13:59:34.912] [   ] [debug] /Users/kaktusz/.config/cherrytree/config.cfg parsed
[2023-04-15 13:59:35.330] [   ] [debug] autosave is started
[2023-04-15 13:59:35.581] [   ] [debug] fs::download_file: start downloading https://raw.githubusercontent.com/giuspen/cherrytree/master/debian/changelog
[2023-04-15 13:59:51.245] [gtk] [info] Settings schema 'org.gtk.Settings.FileChooser' is not installed
Trace/BPT trap: 5
``` 

I just upgraded to new version by brew. Then tried also `brew cleanup` and `brew reinstall cherrytree` as well. These didn't help.

**Before** upgrade I got this error (that's why I upgraded):

```shell
dyld[32613]: Library not loaded: '/usr/local/opt/icu4c/lib/libicuuc.70.dylib'
  Referenced from: '/usr/local/Cellar/gspell/1.10.0/lib/libgspell-1.2.dylib'
  Reason: tried: '/usr/local/opt/icu4c/lib/libicuuc.70.dylib' (no such file), '/usr/local/lib/libicuuc.70.dylib' (no such file), '/usr/lib/libicuuc.70.dylib' (no such file), '/usr/local/Cellar/icu4c/72.1/lib/libicuuc.70.dylib' (no such file), '/usr/local/lib/libicuuc.70.dylib' (no such file), '/usr/lib/libicuuc.70.dylib' (no such file)
Abort trap: 6
```

**Comment by giuspen** [comment]
Can you try to build cherrytree locally following https://github.com/giuspen/cherrytree#building-cherrytree-on-macos and then if you succeed can you try to run the built cherrytree and report how it goes?

**Comment by giuspen** [comment]
My guess anyway is that homebrew is beyond repair, it happened to me once, in that case completely removing it https://mac.install.guide/homebrew/5.html and then reinstalling it will likely solve the issue

**Comment by kaktusztea** [comment]
Thanks for the tips.
Before start to compile I just tried a last method and it worked:

```
brew tap beeftornado/rmtree
brew rmtree cherrytree
brew install cherrytree
```
