### ISSUE TITLE
dashed line at the top when scrolling down the tree structure

### ISSUE THREAD

**Issue by He-Zu** [giuspen/cherrytree#2264]
dashed line at the top when scrolling down the tree structure - see screenshot

![grafik](https://user-images.githubusercontent.com/116963345/233081972-5676d182-70bf-48a7-8328-4841c53873ee.png)

**Comment by He-Zu** [comment]
sorry, i found out this is not a cherrytree problem. it occurs in many applications and is due to cinnamon desktop
forget this request

**Comment by giuspen** [comment]
ok np
