### ISSUE TITLE
Entire .ctb and its same folder backups deleted. Other files in folder remain.

### ISSUE THREAD

**Issue by DanNicolau** [giuspen/cherrytree#2269]
I just had all my notes and their ~ backups wiped... I keep my notes in the Documents folder on windows and am using version 0.99.48. They were password protected. After trying to open the path of the file and getting an error that the file does not exist 14kB notes.ctx, notes.ctx~ ... ~~~ were created but didn't open. I'd love to provide some logs so I can help reproduce the issue but I can't find their location if they exist.

I know I did not accidentally delete the folder because I had a few notes.txt files in there from early in my employment that which are still there and fine.

This is very frustrating since I have about a year's worth of notes and my work is very dependent on referencing those notes. These notes cannot be reconstructed from documentation so I am left to rewrite them from my memory and from asking my peers. I enjoyed using cherry tree while it worked because it was lightweight and hierarchical but this is issue is deeply concerning, especially since it deleted all the ~ backups too...

**Comment by DanNicolau** [comment]
Found a file on disk using autopsy but was not able to recover and doesn't seem right. Was about 16kb and could not open because it was corrupted. Not much I can do at this point to recover.

**Comment by giuspen** [comment]
I'm very sorry that cherrytree has caused data loss to you. I have worked hard recently in preventing this from happening again (starting from 0.99.52 https://github.com/giuspen/cherrytree/blob/master/changelog.txt ) it is very important that cherrytree is kept up to date as I try to be reactive to the most serious issues but what happened to you has been fixed already.

**Comment by DanNicolau** [comment]
Thanks for the update. Closing since issue resolved in updated version.
