### ISSUE TITLE
List view in HTML export is broken

### ISSUE THREAD

**Issue by ganeshbelgur** [giuspen/cherrytree#2276]
**Version, Operative system**
Cherrytree version: 0.99.55
Operating System: Windows 10 64-Bit

**Bug description**
List view is broken in HTML exports if there is some text before an unordered list. Some parts of the text appears to be omitted too. 

**Steps to reproduce**
1. Create a new Node that uses Rich Text
2. Add some text.
3. After the text, add an unordered list
4. Choose Export to HTML, with "All the Tree", "Include Node Name" and "Links Tree in Every Page" options turned on.
5. Open the resulting HTML file to see that the list view is broken

**Screenshots**
Text in Cherrytree:
![cherrytree-text-in-ctb-file](https://github.com/giuspen/cherrytree/assets/10693043/fd917822-bca6-4ac9-a703-01d7b9c6999e)

Text in HTML export:
![cherrytree-text-in-html-export](https://github.com/giuspen/cherrytree/assets/10693043/2e3319c4-5482-4a72-9d36-2923005dde69)

**Comment by giuspen** [comment]
I see it thanks I'll try and sort out before the next release

**Comment by giuspen** [comment]
thanks for reporting, this will be fixed in upcoming 0.99.56
