### ISSUE TITLE
Recent Documents corruption when file is deleted/missing

### ISSUE THREAD

**Issue by ValdikSS** [giuspen/cherrytree#2277]
**Version, Operative system**
Fedora 37, CherryTree 0.99.55 from Flatpak.

**Describe the bug**
When the last opened database .ctb file has been deleted since CherryTree last run, the program upon opening would corrupt its path in "Recent documents" entry, replacing either part or entire path as random garbage symbols.

**To Reproduce**
1. Open the database in CherryTree, make sure "Miscellaneous → Reload Document From Last Session" checkbox is set in the preferences
2. Close CherryTree
3. Rename the database file which was previously opened, to make the program unable to open it on start
4. Start CherryTree
5. Check Recent Documents items: it would not show the path of the previous file

**Screenshots**
![image](https://github.com/giuspen/cherrytree/assets/3054729/e1a66f01-b1a7-433f-99c8-c502a292966d)

**Comment by giuspen** [comment]
thanks for reporting, this will be fixed in upcoming 0.99.56
