### ISSUE TITLE
EcmaScript6 Syntax Hightlighting

### ISSUE THREAD

**Issue by kolomu** [giuspen/cherrytree#228]
Hello, it would be great if you can implement ES6 highlighting or atleast remove some valid ES6 words like class, import, ... from javascript. (ES6 is a newer JS version) 

I tried searching for the syntax highlighting feature but couldn't find it. 
Maybe you can give me a hint where I have to look so I can try implementing stuff like this on my own.

Thanks in advance.

**Comment by giuspen** [comment]
Hi, the library in use for the syntax highlighting is gtksourceview.
You can find the syntax at https://developer.gnome.org/gtksourceview/stable/lang-tutorial.html
CherryTree is already hosting some language definitions in additions to the default available in the library in  the subfolder language-specs: https://github.com/giuspen/cherrytree/tree/master/language-specs
At the moment I cannot implement the new language spec myself but I will include it if you will work on it.
Cheers.
