### ISSUE TITLE
html generation problem

### ISSUE THREAD

**Issue by 13werwolf13** [giuspen/cherrytree#2286]
when using bulleted or numbered lists, a problem occurs when generating html (in the screenshot)
I tried different character combinations but couldn't get it to generate correctly.
![image](https://github.com/giuspen/cherrytree/assets/3271641/b864a24f-3e44-4bac-9fb6-247f7b10d8cb)

**Comment by giuspen** [comment]
Can you attach a test document?

**Comment by 13werwolf13** [comment]
> Can you attach a test document?

I am attaching the exported branch.
it already differs from what is in the screenshot (I tried to find the correct working combination), but the problem persists, although it is somewhat modified.

[itrus.su--android--software_list.ctb.zip](https://github.com/giuspen/cherrytree/files/11592780/itrus.su--android--software_list.ctb.zip)

**Comment by giuspen** [comment]
Thanks this is fixed in upcoming 0.99.56
