### ISSUE TITLE
Unable to install  cherrytree-0.99.55.Fedora37_amd64.rpm on Fedora 38

### ISSUE THREAD

**Issue by ynoxia** [giuspen/cherrytree#2291]
**Version, Operative system**
Linux Fedora 38

**Describe the bug**
Try to install `cherrytree-0.99.55.Fedora37_amd64.rpm` on Fedora 38 via `dnf`.

The installation fails with this message:

```
Errore: 
 Problema: conflicting requests
  - nothing provides libspdlog.so.1()(64bit) needed by cherrytree-0.99.55-1.x86_64 from @commandline
(try to add '--skip-broken' to skip uninstallable packages)
```

Library `libspdlog` is present, but symlink `libspdlog.so.1` is missing:

```
lrwxrwxrwx 1 root root     19  1 mar 01.00 /usr/lib64/libspdlog.so.1.11 -> libspdlog.so.1.11.0
-rwxr-xr-x 1 root root 425208  1 mar 01.00 /usr/lib64/libspdlog.so.1.11.0
```
I could create the missing symlink. But for procedural cleaning, is it possible to modify `cherrytree-0.99.55.Fedora37_amd64.rpm`  to be installed on Fedora 38 as well?

Grazie. :)  🙏

**Comment by giuspen** [comment]
I will create the package for Fedora38 for the upcoming cherrytree 0.99.56
