### ISSUE TITLE
LATEX error with portable version of Cherry tree

### ISSUE THREAD

**Issue by Eagle20236** [giuspen/cherrytree#2294]
Cherry tree version: 0.99.55
OS: Windows 64 Home

When running the portable  version of Cherry tree, selecting 'Insert Latex' from the 'Insert' menu generates the error 'Could not access the executable 'dvipng'.

However, this file is present in the ...\cherrytree_0.99.55.0_win64_portable\mingw64\bin\ directory.

This problem does not exist on the same computer for a gull installation of Cherry tree

**Comment by giuspen** [comment]
I can see the problem, it makes sense I can easily fix it for the upcoming release 0.99.56. In the meantime you can solve the issue adding the bin folder of the portable folder to your system path

**Comment by Eagle20236** [comment]
Thank you and thanks for a great program. I use this now instead of Treepad.

**Comment by giuspen** [comment]
Fixed in upcoming 0.99.56
