### ISSUE TITLE
Stop cursor flashing

### ISSUE THREAD

**Issue by justbest23** [giuspen/cherrytree#2298]
I humbly request that CherryTree either uses the same settings as the OS or has its own setting for cursor flashing. Seeing a flashing cursor on screen drives me mad!

Hopefully this is an easy fix. Thank you for your consideration.

**Comment by giuspen** [comment]
Ok I'll have a look

**Comment by justbest23** [comment]
Much appreciated!

**Comment by justbest23** [comment]
Thank you for the super quick turnaround! The fix is perfect!
