### ISSUE TITLE
Request - How about an option to install an actual Cherry Tree desktop icon and system tray panel icon.

### ISSUE THREAD

**Issue by phd21** [giuspen/cherrytree#230]
Dear Giuseppe,

Simple Request - How about an option to install a different desktop and system tray panel icon that actually looks like a Cherry Tree instead of two cherries, please? This would be nice as node icons as well. See some attached examples.

![brazilian_cherry_tree-icon](https://cloud.githubusercontent.com/assets/6324548/23194191/b8486e6c-f87a-11e6-8b2b-f13ac4474e3f.png)

![cherrytree](https://cloud.githubusercontent.com/assets/6324548/23194192/b84a6744-f87a-11e6-8ad6-203e6e102186.jpeg)

![cherry_tree_fruit-icon](https://cloud.githubusercontent.com/assets/6324548/23194193/b84a9764-f87a-11e6-947d-4510562ffdde.png)

![cherrytree_icon175x175](https://cloud.githubusercontent.com/assets/6324548/23194194/b84b71a2-f87a-11e6-9157-6cc76807416a.png)

![cherrytree_k5111083-haslines](https://cloud.githubusercontent.com/assets/6324548/23194190/b846c42c-f87a-11e6-979e-aa2d05f69f63.jpg)

Thank you for your consideration...

Best regards to you and yours,
Phil
phd21

**Comment by txe** [comment]
Now, users can customize build-in icons including node icons,
