### ISSUE TITLE
Getting core dump when closing the app

### ISSUE THREAD

**Issue by A-ri-eL** [giuspen/cherrytree#2302]
Hi, all! 

For some reason [cherrytree](https://www.giuspen.net/software/cherrytree_0.99.56-2~Debian12_amd64.deb) is performing core dumps every time I close the app after some time working on it. All of them points to the same issue (segfault):

~$ cherrytree --version
CherryTree 0.99.56

~$ lsb_release -a
Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm

~$ kf5-config --version
Qt: 5.15.8
KDE Frameworks: 5.103.0
kf5-config: 1.0

~$ ls -lhS /var/lib/systemd/coredump/
total 53M
...  20M jul  3 22:03 core.cherrytree.1000.d64dfff681984efa9d44251c0dd62f2b.30844.1688432589000000.zst
...  14M jul  3 14:58 core.cherrytree.1000.d64dfff681984efa9d44251c0dd62f2b.4464.1688407082000000.zst

Here is the most recent one:

    jul 03 22:03:28 $HOSTNAME sudo[43692]:    $USER : TTY=pts/3 ; PWD=/home/$USER ; USER=root ; COMMAND=/usr/bin/journalctl --reverse --grep cherrytree
    jul 03 22:03:13 $HOSTNAME drkonqi-coredump-processor[43642]: "/usr/bin/cherrytree" 30844 "/var/lib/systemd/coredump/core.cherrytree.1000.d64dfff681984efa9d44251c0dd62f2b.30844.1688432589000000.zst"
    jul 03 22:03:13 $HOSTNAME systemd[1145]: app-cherrytree-15e36a609ac64734bea48b7cdb10233c.scope: Consumed 1h 1min 2.223s CPU time.
    jul 03 22:03:13 $HOSTNAME systemd-coredump[43641]: Process 30844 (cherrytree) of user 1000 dumped core.

    Module libsystemd.so.0 from deb systemd-252.6-1.amd64
    Stack trace of thread 30844:
    #0  0x00007f6b677e2cda _ZN3Gtk8TreeView13get_selectionEv (libgtkmm-3.0.so.1 + 0x3e2cda)
    #1  0x000055ed0e856973 n/a (cherrytree + 0x3f4973)
    #2  0x00007f6b677c2ff0 n/a (libgtkmm-3.0.so.1 + 0x3c2ff0)
    #3  0x00007f6b65fa43b0 g_closure_invoke (libgobject-2.0.so.0 + 0x163b0)
    #4  0x00007f6b65fb7076 n/a (libgobject-2.0.so.0 + 0x29076)
    #5  0x00007f6b65fbdbf5 g_signal_emit_valist (libgobject-2.0.so.0 + 0x2fbf5)
    #6  0x00007f6b65fbddbf g_signal_emit (libgobject-2.0.so.0 + 0x2fdbf)
    #7  0x00007f6b66ad6f52 n/a (libgtk-3.so.0 + 0x2d6f52)
    #8  0x00007f6b66b06dde n/a (libgtk-3.so.0 + 0x306dde)
    #9  0x00007f6b65fa43b0 g_closure_invoke (libgobject-2.0.so.0 + 0x163b0)
    #10 0x00007f6b65fb7076 n/a (libgobject-2.0.so.0 + 0x29076)
    #11 0x00007f6b65fbdbf5 g_signal_emit_valist (libgobject-2.0.so.0 + 0x2fbf5)
    #12 0x00007f6b65fbddbf g_signal_emit (libgobject-2.0.so.0 + 0x2fdbf)
    #13 0x00007f6b668b3497 gtk_adjustment_set_value (libgtk-3.so.0 + 0xb3497)
    #14 0x00007f6b66b038b0 n/a (libgtk-3.so.0 + 0x3038b0)
    #15 0x00007f6b66b0f8c1 n/a (libgtk-3.so.0 + 0x30f8c1)
    #16 0x00007f6b65fa9616 n/a (libgobject-2.0.so.0 + 0x1b616)
    #17 0x00007f6b65fac5ac g_object_set_valist (libgobject-2.0.so.0 + 0x1e5ac)
    #18 0x00007f6b65fad11c g_object_set (libgobject-2.0.so.0 + 0x1f11c)
    #19 0x00007f6b66a99fbd n/a (libgtk-3.so.0 + 0x299fbd)
    #20 0x00007f6b65fa7611 g_cclosure_marshal_VOID__OBJECTv (libgobject-2.0.so.0 + 0x19611)
    #21 0x00007f6b65fa45a9 n/a (libgobject-2.0.so.0 + 0x165a9)
    #22 0x00007f6b65fbdbbf g_signal_emit_valist (libgobject-2.0.so.0 + 0x2fbbf)
    #23 0x00007f6b65fbddbf g_signal_emit (libgobject-2.0.so.0 + 0x2fdbf)
    #24 0x00007f6b6691f355 gtk_container_remove (libgtk-3.so.0 + 0x11f355)
    #25 0x00007f6b677ebd6b _ZN3Gtk12Widget_Class22dispose_vfunc_callbackEP8_GObject (libgtkmm-3.0.so.1 + 0x3ebd6b)
    #26 0x00007f6b65faabb8 g_object_run_dispose (libgobject-2.0.so.0 + 0x1cbb8)
    #27 0x00007f6b66a9aebd n/a (libgtk-3.so.0 + 0x29aebd)
    #28 0x00007f6b65fa43b0 g_closure_invoke (libgobject-2.0.so.0 + 0x163b0)
    #29 0x00007f6b65fb7124 n/a (libgobject-2.0.so.0 + 0x29124)
    #30 0x00007f6b65fbdbf5 g_signal_emit_valist (libgobject-2.0.so.0 + 0x2fbf5)
    #31 0x00007f6b65fbddbf g_signal_emit (libgobject-2.0.so.0 + 0x2fdbf)
    #32 0x00007f6b66b740dd n/a (libgtk-3.so.0 + 0x3740dd)
    #33 0x00007f6b65faabb8 g_object_run_dispose (libgobject-2.0.so.0 + 0x1cbb8)
    #34 0x00007f6b6781b098 _ZN3Gtk6Object19_release_c_instanceEv (libgtkmm-3.0.so.1 + 0x41b098)
    #35 0x00007f6b677abb96 _ZN3Gtk14ScrolledWindowD1Ev (libgtkmm-3.0.so.1 + 0x3abb96)
    #36 0x000055ed0e85b38a _ZN9CtCodeboxD0Ev (cherrytree + 0x3f938a)
    #37 0x000055ed0e7c942f _ZN11CtTreeStore29_iter_delete_anchored_widgetsERKN3Gtk16TreeNodeChildrenE (cherrytree + 0x36742f)
    #38 0x000055ed0e7c952d _ZN11CtTreeStoreD1Ev (cherrytree + 0x36752d)
    #39 0x000055ed0e7c9689 _ZN11CtTreeStoreD0Ev (cherrytree + 0x367689)
    #40 0x000055ed0e737e73 _ZN9CtMainWinD1Ev (cherrytree + 0x2d5e73)
    #41 0x000055ed0e7383e9 _ZN9CtMainWinD0Ev (cherrytree + 0x2d63e9)
    #42 0x00007f6b67720147 _ZN3Gtk17Application_Class23window_removed_callbackEP15_GtkApplicationP10_GtkWindow (libgtkmm-3.0.so.1 + 0x320147)
    #43 0x00007f6b65fa7611 g_cclosure_marshal_VOID__OBJECTv (libgobject-2.0.so.0 + 0x19611)
    #44 0x00007f6b65fa45a9 n/a (libgobject-2.0.so.0 + 0x165a9)
    #45 0x00007f6b65fbdbbf g_signal_emit_valist (libgobject-2.0.so.0 + 0x2fbbf)
    #46 0x00007f6b65fbddbf g_signal_emit (libgobject-2.0.so.0 + 0x2fdbf)
    #47 0x00007f6b677eae84 n/a (libgtkmm-3.0.so.1 + 0x3eae84)
    #48 0x00007f6b65fa43b0 g_closure_invoke (libgobject-2.0.so.0 + 0x163b0)
    #49 0x00007f6b65fb7344 n/a (libgobject-2.0.so.0 + 0x29344)
    #50 0x00007f6b65fbdbf5 g_signal_emit_valist (libgobject-2.0.so.0 + 0x2fbf5)
    #51 0x00007f6b65fbddbf g_signal_emit (libgobject-2.0.so.0 + 0x2fdbf)
    #52 0x00007f6b66b73eb1 gtk_widget_hide (libgtk-3.so.0 + 0x373eb1)
    #53 0x00007f6b65faabb8 g_object_run_dispose (libgobject-2.0.so.0 + 0x1cbb8)
    #54 0x00007f6b66a0934d gtk_main_do_event (libgtk-3.so.0 + 0x20934d)
    #55 0x00007f6b67140815 n/a (libgdk-3.so.0 + 0x3c815)
    #56 0x00007f6b6719a702 n/a (libgdk-3.so.0 + 0x96702)
    #57 0x00007f6b65eaa7a9 g_main_context_dispatch (libglib-2.0.so.0 + 0x547a9)
    #58 0x00007f6b65eaaa38 n/a (libglib-2.0.so.0 + 0x54a38)
    #59 0x00007f6b65eaaacc g_main_context_iteration (libglib-2.0.so.0 + 0x54acc)
    #60 0x00007f6b666ff65d g_application_run (libgio-2.0.so.0 + 0xdd65d)
    #61 0x000055ed0e5fbeee main (cherrytree + 0x199eee)
    #62 0x00007f6b6596718a n/a (libc.so.6 + 0x2718a)
    #63 0x00007f6b65967245 __libc_start_main (libc.so.6 + 0x27245)

    Stack trace of thread 30866:
    #0  0x00007f6b659c5d36 n/a (libc.so.6 + 0x85d36)
    #1  0x00007f6b659c83f8 pthread_cond_wait (libc.so.6 + 0x883f8)
    #2  0x000055ed0e78ab63 _ZN16CtStorageControl20_backupEncryptThreadEv (cherrytree + 0x328b63)
    #3  0x00007f6b65cd44a3 n/a (libstdc++.so.6 + 0xd44a3)
    #4  0x00007f6b659c8fd4 n/a (libc.so.6 + 0x88fd4)
    #5  0x00007f6b65a495bc n/a (libc.so.6 + 0x1095bc)

    Stack trace of thread 30845:
    #0  0x00007f6b65a3bfff __poll (libc.so.6 + 0xfbfff)
    #1  0x00007f6b65eaa9ae n/a (libglib-2.0.so.0 + 0x549ae)
    #2  0x00007f6b65eaaacc g_main_context_iteration (libglib-2.0.so.0 + 0x54acc)
    #3  0x00007f6b65eaab11 n/a (libglib-2.0.so.0 + 0x54b11)
    #4  0x00007f6b65ed4cfd n/a (libglib-2.0.so.0 + 0x7ecfd)
    #5  0x00007f6b659c8fd4 n/a (libc.so.6 + 0x88fd4)
    #6  0x00007f6b65a495bc n/a (libc.so.6 + 0x1095bc)

    Stack trace of thread 30846:
    #0  0x00007f6b65a3bfff __poll (libc.so.6 + 0xfbfff)
    #1  0x00007f6b65eaa9ae n/a (libglib-2.0.so.0 + 0x549ae)
    #2  0x00007f6b65eaacef g_main_loop_run (libglib-2.0.so.0 + 0x54cef)
    #3  0x00007f6b6673a8f6 n/a (libgio-2.0.so.0 + 0x1188f6)
    #4  0x00007f6b65ed4cfd n/a (libglib-2.0.so.0 + 0x7ecfd)
    #5  0x00007f6b659c8fd4 n/a (libc.so.6 + 0x88fd4)
    #6  0x00007f6b65a495bc n/a (libc.so.6 + 0x1095bc)

    Stack trace of thread 30905:
    #0  0x00007f6b65a3bfff __poll (libc.so.6 + 0xfbfff)
    #1  0x00007f6b65eaa9ae n/a (libglib-2.0.so.0 + 0x549ae)
    #2  0x00007f6b65eaaacc g_main_context_iteration (libglib-2.0.so.0 + 0x54acc)
    #3  0x00007f6b600244bd n/a (libdconfsettings.so + 0xb4bd)
    #4  0x00007f6b65ed4cfd n/a (libglib-2.0.so.0 + 0x7ecfd)
    #5  0x00007f6b659c8fd4 n/a (libc.so.6 + 0x88fd4)
    #6  0x00007f6b65a495bc n/a (libc.so.6 + 0x1095bc)
    ELF object binary architecture: AMD x86-64
    jul 03 22:03:09 $HOSTNAME kernel: cherrytree[30844]: segfault at 55e84e905719 ip 00007f6b677e2cda sp 00007ffe6eff2600 error 4 in libgtkmm-3.0.so.1.1.0[7f6b676e6000+137000] likely on CPU 0 (core 0, socket 0)

**Comment by giuspen** [comment]
Hi @A-ri-eL it would be useful if you can build for debug from the source code following https://github.com/giuspen/cherrytree#building-cherrytree-on-ubuntu but instead of `./build.sh` use `./build.sh debug` then you should be able to give me a core dump with the actual cherrytree symbols

**Comment by A-ri-eL** [comment]
Thanks for your answer. 

As I'm using a Debian 12 docker container to compile, ninja was not able to perform some tests that seem to need graphical user interface, then it always failed. So I managed to get a `.deb` package with a not-stripped cheerytree bianary via `export DEB_BUILD_OPTIONS=nostrip`.

```
~$file `which cherrytree`
/usr/bin/cherrytree: ELF 64-bit LSB pie executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=76338fe2c8b814ca77dcf9726429e657573fd214, for GNU/Linux 3.2.0, with debug_info, not stripped
```
[coredump-cherrytree_18-07-2023.zip](https://github.com/giuspen/cherrytree/files/12086191/coredump-cherrytree_18-07-2023.zip)

**Comment by giuspen** [comment]
I'm having difficulty to read that crash dump, probably because the binary of cherrytree that I pass to gdb is not the same that you are using.
I will improve build.sh to support 2 arguments so that you will be able to pass both arguments 'debug' and 'notests' while at the moment you can pass only one

**Comment by A-ri-eL** [comment]
@giuspen  ^-^  I proceeded exactly as you described so I've got:
```
~$ ls
build.ninja  CMakeCache.txt  cmake_install.cmake    CPackConfig.cmake        src
cherrytree   CMakeFiles      cmake_uninstall.cmake  CPackSourceConfig.cmake

~$ file ./cherrytree 
./cherrytree: ELF 64-bit LSB pie executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=a7c74ef792e741ba3650f5f43267d3dbff6e2a79, for GNU/Linux 3.2.0, with debug_info, not stripped

$ ./cherrytree --version
CherryTree 1.0.0
```

Then starting `cherrytree` from GDB and after working some time on the App when closing it I've got:
```
(...)
[Thread 0x7fffe1dfe6c0 (LWP 15242) exited]

Thread 1 "cherrytree" received signal SIGSEGV, Segmentation fault.
0x00007ffff7be2cd7 in Gtk::TreeView::get_selection() () from /lib/x86_64-linux-gnu/libgtkmm-3.0.so.1
(gdb) bt
#0  0x00007ffff7be2cd7 in Gtk::TreeView::get_selection() () from /lib/x86_64-linux-gnu/libgtkmm-3.0.so.1
Backtrace stopped: Cannot access memory at address 0x7fffffffb448
(gdb)
```

**Comment by giuspen** [comment]
Unfortunately in your backtrace the symbols (names of functions) are not visible, I don't understand why.
Maybe try once again after after uninstalling completely your installed cherrytree and ensuring it's not running already maybe on the systray? (e.g. `ps aux | grep cherrytree`)
I have concern that maybe one instance of cherrytree was running so it didn't really run from your built sources.
Then
git pull
git clean -dfx
./build.sh debug notests
$ gdb ./build/cherrytree
(gdb) r
...after it crashes
(gdb) bt

**Comment by giuspen** [comment]
Yes this is a good backtrace I will have a look vs the code, may get back with more questions

**Comment by giuspen** [comment]
Could you please pull the latest from git, rebuild and if it crashes again generate again a backtrace for me?

**Comment by A-ri-eL** [comment]
It worked! No more crashes :)

**Comment by giuspen** [comment]
Thanks!
