### ISSUE TITLE
Windows: paste web-image if data available

### ISSUE THREAD

**Issue by DaPa** [giuspen/cherrytree#2303]
**Version, Operative system**
cherrytree 0.99.56 on Windows 10 (21H2) x64

**Describe the bug**
In Windows, an image copied from a web browser (Firefox, Chrome) can be pasted in other tools (Paint, Word, ...) even if they don't have internet access (blocked by firewall) because the clipboard contains already the bitmap data (as shown below by InsideClipboard tool from Nirsoft).
A possible fix is suggested here: https://github.com/DaPa/cherrytree/commit/a36ccd57414d035da8230a1048cf55227ae44ff3

Test after patched build:
![image](https://github.com/giuspen/cherrytree/assets/4947697/b6ec1147-5089-4aa5-af96-2978df64f6bb)

**Comment by giuspen** [comment]
thank you @DaPa I added your patch, will be in upcoming version 1.0.0
