### ISSUE TITLE
Task Bar - Window Preview missing

### ISSUE THREAD

**Issue by hermann-san** [giuspen/cherrytree#2307]
Buongiorno! 

**Version, Operative system**
State the Version and the Operative System/Desktop. Try the latest available version before reporting an issue.
CherryTree 0.99.56  Linux Mint 21.1

**Describe the bug**

When I hover with the mouse arrow over a symbol In my task bar, I usually see a small window preview.
Not so with CherryTree.

**To Reproduce**
mouse over the Cherrytree symbol (see screenshot below)

**Screenshots**
One Virtualbox window open and one preview windows pop's up.
![Auswahl_007](https://github.com/giuspen/cherrytree/assets/7679654/62776915-ceb7-4715-9411-cfcf60db698d)

In this example there are 2 windows open, however I don't see a preview pop-up window.
![CHerry](https://github.com/giuspen/cherrytree/assets/7679654/f2366986-645f-4ea8-ae5e-1c96a718c742)

**Comment by giuspen** [comment]
Hi, I'm also on mint 21.1 and I cannot reproduce the issue, maybe is the type of package?
Try the PPA after removing what you have:
```
sudo add-apt-repository ppa:giuspen/ppa
sudo apt update
sudo apt install cherrytree
```

**Comment by hermann-san** [comment]
Hi @giuspen , thanks for your hin. In the meantime I've noticed that other apps are also affected.  I guess that it's a Cinnamon Desktop  issue.  Restarting Cinnamon helps getting back to normal. I'll try t-shoot with Mint folks. It could be even a defective SATA Controller (that has already caused other issues) I'll try to fix that first. Thanks.
