### ISSUE TITLE
Blurry output when exporting LaTeX

### ISSUE THREAD

**Issue by Daria-E** [giuspen/cherrytree#2308]
**Version, Operative system**
0.99.56, Debian 12 (installed from Flathub)

**Describe the bug**
When exporting as PDF, TeX boxes are very low-res. Fix may be related to #639, not sure what renders the TeX box.

**To Reproduce**
Create a new node, add TeX(t) to it. Export as PDF.
See attached [lowres-latex.zip](https://github.com/giuspen/cherrytree/files/12026356/lowres-latex.zip)
 (contains `test.ctb` and `test.pdf`).

**Comment by giuspen** [comment]
Thank you I significantly improved the result for upcoming new version as you can see in attached file [test.pdf](https://github.com/giuspen/cherrytree/files/12061126/test.pdf)

**Comment by giuspen** [comment]
Improved a little more [test4.pdf](https://github.com/giuspen/cherrytree/files/12061140/test4.pdf)

**Comment by Daria-E** [comment]
Blazing fast response. Much appreciated!
