### ISSUE TITLE
[Bug?] image failed to render under wayland on fedora 25

### ISSUE THREAD

**Issue by evolighting** [giuspen/cherrytree#231]
Not only image in rich text but  those in tool bar UI fail to render, leaving only black box.

There is no debug information.

Switch from wayland back to Xorg fix it.

But  I think it is a real issues, maybe for pyGTK?

**Comment by giuspen** [comment]
I have to switch to gtk3 shortly and the issue will disappear after that. I think the obsolete gtk2 currently in use does not support wayland

**Comment by evolighting** [comment]
@giuspen I'm using version CherryTree 0.37.5.
So all I need to do is just waiting for a update switching to gtk3?

Since Xrog still works fine right now, it is not  a big trouble.

And just close that issue?

**Comment by giuspen** [comment]
Yes wait for the gtk3 version, I'll start to work on that soon and hope to release within a couple of months. Will probably be 0.39.x
