### ISSUE TITLE
Use Selected Icon Crash

### ISSUE THREAD

**Issue by asoymos** [giuspen/cherrytree#2313]
**Version, Operative system**
0.99.56 Flatpak in Debian Bookworm

**Describe the bug** > **To Reproduce**
F2 > Change Node Properties > Use Selected Icon >> Do nothing, opening same dialog again crash Application.

**Comment by giuspen** [comment]
Duplicate of https://github.com/giuspen/cherrytree/issues/2304#issuecomment-1633684572 please look at that for a temporary workaround, the new version 1.0.0 fixing that will be released in the next days

**Comment by asoymos** [comment]
Ok thanks!!
