### ISSUE TITLE
Cannot add curly braces { } in cherry tree

### ISSUE THREAD

**Issue by FlorianTieto** [giuspen/cherrytree#2316]
**Version, Operative system**
1.0.0

**Describe the bug**
1. Create a new empty node
2. In the new node try to write a text containing {. For instance : Hello World { }
3.  I make { bei pressing ALTGR + 7
4. I get the error 
![image](https://github.com/giuspen/cherrytree/assets/102660823/db6da293-0309-419d-89eb-5432e52c8b73)
"No Table connected"
5. I press ok on the error and there is no {
6. I guess it is an issue that ALTGR+7 is used shortcut, blocking the { to be created.

**Comment by giuspen** [comment]
If you look at the preferences dialog, tab Keyboard Shortcuts you can find the unwanted keyboard shortcut and either change it or simply disable it. Note that Windows interprets Ctrl + Alt as AltGr

**Comment by giuspen** [comment]
In upcoming v1.0.3 there won't be anymore any default keyboard shortcuts with Ctrl+Alt
