### ISSUE TITLE
Enhancing User Experience: Introducing Auto-Save Feature to CherryTree

### ISSUE THREAD

**Issue by thiagolmoraes** [giuspen/cherrytree#2318]
Is your feature request related to a problem? Please describe.
Yes, the current version of CherryTree lacks an auto-save feature. This has been a source of frustration for users, including myself, as it poses a risk of data loss in case of unexpected crashes or accidental closing of the application.

Describe the solution you'd like
I would like to propose the implementation of an auto-save feature in CherryTree. The solution should automatically save changes made to notes at regular intervals, ensuring that users' work is constantly backed up and reducing the risk of losing important information. Ideally, the auto-save frequency should be customizable, allowing users to set their preferred time intervals for automatic saving.

With this feature in place, users can have peace of mind knowing that their notes are always protected and recoverable, even in the event of unforeseen interruptions or system issues. The addition of auto-save would significantly enhance the user experience and make CherryTree even more reliable and user-friendly.

Thank you for considering this feature request, and I believe that implementing auto-save would further solidify CherryTree's position as an excellent note-taking and information management tool.

**Comment by funnelfiasco** [comment]
What version are you using? CherryTree has had an autosave feature for a while. Look in Preferences -> Miscellaneous for the relevant settings.

**Comment by giuspen** [comment]
As @funnelfiasco says, the auto save has been implemented long ago, please upgrade to the latest
