### ISSUE TITLE
the dir link is gone after the CherryTree file to reopen (when non Lainn characters in the dirpath)

### ISSUE THREAD

**Issue by Paffnik** [giuspen/cherrytree#2320]
**Version, Operative system**
v1.0.0, Windows 11 x64

**Describe the bug**
The problem occurs when copying the directory path in Windows and then pasting it into the CherryTree file. When you reopen the CherryTree file, the link with the path to the directory becomes inactive if there was another link before it, which is overwritten with a link to the directory. If there was a simple text before the link to the directory, then when the CherryTree file is reopened, the last word of this text also becomes an active link to the directory. This problem is relevant when there are not only Latin characters in the path in particular with Cyrillic characters!!!!!!!!!!!!!!!!!!
![01](https://github.com/giuspen/cherrytree/assets/89673841/7e62bebb-82b6-430b-8ef8-0d455c96bbf5)
![02 the dir link is gone after the CherryTree file to reopen](https://github.com/giuspen/cherrytree/assets/89673841/9281ed61-862e-4345-b725-2de653082d92)

**Comment by giuspen** [comment]
On my Win10 when I copy a directory with Cyrillic characters from the file manager and paste into CherryTree, the short notation (e.g. C:\PROGRA~1\INTERN~1) is found in the clipboard and pasted in CherryTree, so in the end I see only Latin characters.
I don't have a Win11 right now but I will try to have one soon, maybe in the meantime you can test on a Win10 and report if this is a Win11 only issue or also affects Win10?

**Comment by Paffnik** [comment]
Sorry for long answer. In Win10 the same problem. I made a video with this problem.

**Comment by Paffnik** [comment]
[https://youtu.be/7tZcq3VWx5s 
](url)

**Comment by Paffnik** [comment]
Our copy of Windows uses cp-1251 codepage

**Comment by Paffnik** [comment]
In parallel with the solution of the problem I suggest making a setting in the program settings: The copied path to the directory inserts as a link or as plain text.

**Comment by giuspen** [comment]
> In parallel with the solution of the problem I suggest making a setting in the program settings: The copied path to the directory inserts as a link or as plain text.

Note @Paffnik that you can paste as plain text (Ctrl+Shift+V instead of Ctrl+V) to avoid a link being created on paste.

**Comment by giuspen** [comment]
Thanks for reporting, this will has now been fixed, the fixed will be in next version > 1.0.1
