### ISSUE TITLE
Why is there a ghost in one node?

### ISSUE THREAD

**Issue by codeco1978** [giuspen/cherrytree#2323]
**Version, Operative system**
Debian 12

**Describe the bug**
I know it is strange to explain, but there is a ghost emoji in one of my nodes and I don't know why.

**To Reproduce**
I don't know

**Screenshots**
![obfuscated](https://github.com/giuspen/cherrytree/assets/74433485/a2d3fea7-b59c-4dda-bea3-4ba09ed435a4)

**Comment by giuspen** [comment]
That identifies exclusions from the search set in that node properties. If it was not you to set those intentionally, either change node properties to untick those or Search--Clear all exclusions from the search

**Comment by codeco1978** [comment]
Thanks!
