### ISSUE TITLE
Square brackets on German keyboard doesn't work

### ISSUE THREAD

**Issue by LucasSchelkes-BA** [giuspen/cherrytree#2324]
**Version, Operative system**
CT version 1.0.0 on Windows 10

**Describe the bug**
The square brackets on a German keyboard are inserted by `AltGr` + `8` (or `9` respectively). However, this causes the following message:
![image](https://github.com/giuspen/cherrytree/assets/113904447/f431b3ae-3833-4146-9c6f-7c42ede3932a)
Im guessing the keyboard combination is a shortcut regarding tables. Could we perhaps change the default here?

**To Reproduce**
Press  `AltGr` + `8` (or `9` respectively) on German keyboard

Great piece of software btw, I use it almost daily! ❤

**Comment by giuspen** [comment]
If you look at the preferences dialog, tab keyboard shortcuts, you can change or disable the guilty shortcut, this should solve this.
I expect you need to disable Ctrl+Alt+( and Ctrl+Alt+) since in Windows AltGr equals to Ctrl+Alt

**Comment by LucasSchelkes-BA** [comment]
Thanks @giuspen , works like a charm now! 💯
