### ISSUE TITLE
document from last session is not opened upon restart

### ISSUE THREAD

**Issue by karel1** [giuspen/cherrytree#2329]
**Version, Operative system**
Linux Manjaro (Arch) , CT vs 1.0.0

**Describe the bug**
CherryTree does not open last document from last session. It does show the document in File / Recent Documents and does load it when selected.

The config file (with added .txt or it would not upload) is attached.

This has been the case since ± half a year with all recent versions of CherryTree (and on two Linux installations).

Thank you for looking into this, greetings from your Dutch translator!

**Screenshots**
[config.cfg.txt](https://github.com/giuspen/cherrytree/files/12360076/config.cfg.txt)

**Comment by karel1** [comment]
On Linux Mint (my 3rd Linux) with CT .99.43 the last document opens fine! And that document is the same document in the same folder that is used by the Linux Manjaro installation.

**Comment by giuspen** [comment]
Can you try on Linux Mint to do File-->Preferences-->Export and then in Manjaro File-->Preferences-->Import, I'm curious if there is any change after that? I will try your config too and let you know

**Comment by giuspen** [comment]
Strange I couldn't reproduce your issue importing your preferences on Ubuntu, I shall give it a try on Manjaro... in the meantime can you try to temporarily disable the systray / start on stystray and see if anything changes?

**Comment by karel1** [comment]
Negative on both your questions (Import and Disable Systray options). BTW The systray options were enabled in my Manjaro CT and also did not (and do not) work.
Also: Manjaro / Arch are running with Wayland and Mint with X11.

**Comment by giuspen** [comment]
If you start cherrytree from a terminal, as it fails to run the document from the last session, is it printing any complaint?

**Comment by giuspen** [comment]
... also can you specify which desktop are you running Manjaro with?

**Comment by giuspen** [comment]
... also could it be that your document is on an external or network drive and you have cherrytree to start automatically at boot and that drive may not be mounted yet at that time so the document comes available later when cherrytree is already running?

**Comment by karel1** [comment]
Both Arch and Manjaro have KDE desktop. No, the document is on SSD drive and in home folder. In terminal it runs OK, meaning it opens the document from last session.
This got me looking in the settings of the KDE Launcher / Menu with respect to CT. And that showed the cause, see attachment. Once I cleared the Arguments field, CT opened the document from last session OK!
Thanks for your support!

![scrnshot](https://github.com/giuspen/cherrytree/assets/3692937/8e79a8a7-a035-4807-ba61-2304a57e42bf)

**Comment by giuspen** [comment]
Oh I see, is it the `--new-window` option causing the problem for you?

**Comment by karel1** [comment]
Very strange / can't explain: I added '--new-window' again and then rebooted and CT starts OK.
I then also added ' %f' ,rebooted and CT starts OK.
My 'problem' is solved, you can close this issue. Thanks again!

**Comment by giuspen** [comment]
Ok cheers @karel1
