### ISSUE TITLE
Easy way to clear Recent Documents

### ISSUE THREAD

**Issue by deseactor** [giuspen/cherrytree#2330]
I'm constantly clearing recently opened documents and it's quite tiring so I started editing the config file to remove them. 
It would be good to add something like "_Remove all_" in "_Files - Recent Documents - Remove from list_" or disable storing function for recent files in settings.

P.S. Having the opportunity to talk to you Giuseppe , I want say you big THANKS, I use CherryTree almost every day for a few years. Also thanks for supporting Ukraine it's very heartwarming ❤. Wish you all the best.

**Comment by giuspen** [comment]
It's my pleasure to keep cherrytree up, I'm always its first user 😉
I can quickly add an option in the config.cfg to do not remember the recently used documents, that you will have to change from false to true. In future with a control from the preferences dialog but in the upcoming version I cannot touch the translatable strings.

**Comment by deseactor** [comment]
Option in the config file would be just great, if it will be changed where I can track that it's added, here in this issue or on the main site? Thanks.

**Comment by giuspen** [comment]
I will notify here once implemented

**Comment by giuspen** [comment]
I did add the key recent_docs that you have to set to false.

**Comment by deseactor** [comment]
Amazing, I'm so grateful.
