### ISSUE TITLE
Build error - spdlog ct_actions_edit.cc.o

### ISSUE THREAD

**Issue by cmorgenstern** [giuspen/cherrytree#2331]
**Version, Operative system**
Build and compile from ([9470744](https://github.com/giuspen/cherrytree/commit/9470744842afcff9b3ed7fe264f3cd255f260628))
Arch Linux 6.4.10-arch1-1

**Describe the bug**
Build and compile in a clean chroot fails:
```
...
In file included from /usr/include/spdlog/fmt/fmt.h:31,
                 from /usr/include/spdlog/common.h:45,
                 from /usr/include/spdlog/spdlog.h:12:
/usr/include/fmt/core.h:1826:35: note:   initializing argument 2 of ‘constexpr fmt::v10::format_arg_store<Context, typename std::remove_cv<typename std::remove_reference<T>::type>::type ...> fmt::v10::make_format_args(T& ...) [with Context = basic_format_context<appender, char>; T = {const char [13], Glib::ustring}]’
 1826 | constexpr auto make_format_args(T&... args)
      |                                 ~~^~~~~~~~
make[2]: *** [src/ct/CMakeFiles/cherrytree_shared.dir/build.make:76: src/ct/CMakeFiles/cherrytree_shared.dir/ct_actions_edit.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:221: src/ct/CMakeFiles/cherrytree_shared.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
make: Leaving directory '/build/cherrytree-git/src/cherrytree/build'
```
Full build log is attached:
[cherrytree-git-1.0.0.r17.g94707448-1-x86_64-build.log](https://github.com/giuspen/cherrytree/files/12374482/cherrytree-git-1.0.0.r17.g94707448-1-x86_64-build.log)

**To Reproduce**
```
git clone https://aur.archlinux.org/cherrytree-git.git
cd cherrytree-git
makepkg -s
```
Expected - successful pkg.tar.zst created
Actual - build error (see above)

**Comment by giuspen** [comment]
Sorry I'm not familiar with Arch Linux versions, is this the latest and greatest that you are running?

**Comment by giuspen** [comment]
Can you pull the latest, git submodule update --init, edit https://github.com/giuspen/cherrytree/blob/master/CMakeLists.txt#L28 change ON to OFF for USE_SHARED_FMT_SPDLOG so the bundled version is used and build again?

**Comment by cmorgenstern** [comment]
Sorry for the delay in replying - this was indeed the issue. Looks like [spdlog](https://archlinux.org/packages/extra/x86_64/spdlog/) in the Arch Linux repos is a minor version behind [gabime/spdlog](https://github.com/gabime/spdlog.git) (1.11 versus 1.12). 

The [updated version](https://archlinux.org/packages/extra-staging/x86_64/spdlog/) is in extra-staging at the moment, so I have modified the [AUR package](https://aur.archlinux.org/packages/cherrytree-git) to use the git submodule version for now.
