### ISSUE TITLE
Preventing the use of a non-empty directory as storage type

### ISSUE THREAD

**Issue by A-ri-eL** [giuspen/cherrytree#2333]
It would be useful to prevent a **non-empty** directory from being used as a storage type when using multiple files as a backend. Unfortunately, no check is made in that sense, and as a consequence, I lost some files.

 :(

**Comment by giuspen** [comment]
I'm sorry to hear that, I thought there is an overwrite confirmation, were you prompted from that dialog?
Do you still think that CherryTree should refuse to overwrite a directory if not empty at all or maybe make it more clear in the overwrite confirmation that the directory is not empty?

**Comment by giuspen** [comment]
There is indeed a bug, the overwrite confirmation is not currently working in the multifold I'm going to fix this

**Comment by A-ri-eL** [comment]
Unfortunately I didn't get any overwrite confirmation prompt, but I think that it would be more secure if CT refused to _select_ a directory that was not empty at all.

About the files: I managed to get them back :)
