### ISSUE TITLE
No way to set keyboard shortcuts for to level menu elements

### ISSUE THREAD

**Issue by sectroyer** [giuspen/cherrytree#2335]
**Version, Operative system**
1.0.0, Mac OS X

**Describe the bug**
In Settings there is an option to set keyboard shortcuts for menu items. However there is no way to set keyboard shortcuts for top level menu items like: Edit, Format, Search, etc. This is especially annoying their default keyboard shortcuts (Alt+e,o,s) are exactly the ones that are used in Polish language to type letters ę,ó,ś used in many words 😄

**Comment by giuspen** [comment]
You can modify the accelerators in the file https://github.com/giuspen/cherrytree/blob/master/po/pl.po and submit a pull request or send the file to me by email. Is that ok?
For example
msgid "_File"
msgstr "_Plik"
If you change to
msgstr "P_lik"
The accelerator will become the letter L

**Comment by sectroyer** [comment]
I think there is not many changes to make if you want to hardcode them, here is a list of my suggestions of what to change:
```
msgstr "_Edycja"   -> msgstr "Edyc_ja" # no good candidate IMHO as e is ę, d is used for tree c is ć and a is ą :D 

msgstr "F_ormat" ->  msgstr "For_mat"

msgstr "_Szukaj" -> msgstr "Sz_ukaj" # s is ś and z is ż :)

msgstr "_Zakładki"  -> msgstr "Za_kładki"  # z is ż, a is ą :)

```

Also I just noticed that Alt+Shift+X removes a line however in Polish is should type Ź 😄

**Comment by giuspen** [comment]
@sectroyer if none of the letters are suitable another solution is possible, something like:
`msgstr "_Edycja"   -> msgstr "Edycja (_P)"`
For example to set the P as accelerator. Such solution is used for example in the Chinese menus. Let me know your decision.

**Comment by sectroyer** [comment]
Currently 
`_P` is used for `File -> Plik (_P)` it's much better suited :) J isn't currently used so I think it's best as it's part of `Edycja` word at least 😄I just gave examples of letters that I don't see any conflict for. I think when there is a letter available that is part of accelerated word it's best to use it. Tough anything that doesn't conflict with Polish letters is okay for me 😄

**Comment by giuspen** [comment]
Ok I applied your change in https://github.com/giuspen/cherrytree/commit/62a790b8a1c9aa2498cd21020039da7028c817c2 - note that unwanted keyboard shortcuts connected to actions can be disabled in the preferences dialog, tab keyboard shortcuts

**Comment by sectroyer** [comment]
Disabling keyboard shortcuts for top level elements (like Edit, Format, Tools, etc.) is not possible via keyboard shortcuts tab 😄

**Comment by sectroyer** [comment]
I recently started using 1.0.2. Almost everything works as expected and I can type Polish special characters. Except Alt+z, looks it's still assigned to Bookmarks (Zakładki).

**Comment by giuspen** [comment]
Ok I just fixed the last accelerator, you'll find it in upcoming 1.0.3
