### ISSUE TITLE
Ctrl+) does not decrease the width of a table column

### ISSUE THREAD

**Issue by wgreene310** [giuspen/cherrytree#2336]
**Version, Operative system**
1,0.0.0 Windows 10

**Describe the bug**
Ctrl+) does not decrease the width of a table column.
However, Ctrl+( does increase the width.

**Comment by giuspen** [comment]
This is indeed an issue even though it is caused by the option to auto expand the codebox being ticked in the preferences dialog.
I think I should allow the user to auto expand independently horizontally and vertically and maybe even allow this option to be per codebox rather than global

**Comment by wgreene310** [comment]
Many thanks for the quick response.

>caused by the option to auto expand the codebox being ticked in the
preferences dialog.

I unchecked this option in the preferences dialog, restarted cherrytree,
but am still seeing the problem.
Maybe I'm misunderstanding?

**Comment by giuspen** [comment]
In fact it's me that am misunderstanding, you clearly wrote table and I read codebox (sorry)
I can see the issue on Windows while not on Linux, weird, I'll investigate further and sort it out.

**Comment by giuspen** [comment]
I changed the default keyboard shortcuts for increase/decrese table column to Ctrl+Alt+> and Ctrl+Alt+< in the upcoming version 1.0.1 - note that you can change Ctrl+) as doesn't work on Windows, must be taken by the OS
