### ISSUE TITLE
Is it better to post issues here or in the site forum? 

### ISSUE THREAD

**Issue by AntiNSA** [giuspen/cherrytree#234]
I have recently made some posts in the site forum. Let men  know if its neccessary to post those issues here. And let me know for future refrence which is the preferred medium. Thanks!

**Comment by giuspen** [comment]
It would be better if bugs are reported with github issues while the forum is for discussing with other users. Having said so it is difficult for me on my own to follow all bugs and development, it would be great if someone would help fixing the issues.
