### ISSUE TITLE
Still problems with false assigned CTRL + ALT sequences in keyboard mappings of cherrytree on INT-keyboards with ALT+GR

### ISSUE THREAD

**Issue by vitusb** [giuspen/cherrytree#2341]
Hello Giuseppe ...
We're still unable to insert special keys by using "Alt Gr"-key on german keyboard like "µ ~ ² ³ { [ ] } \" etc. ...

The problem is a default-configuration in "config.cfg" where cherrytree uses "CTRL-ALT"-sequences in order to map some functions AND it is not new:

- https://github.com/giuspen/cherrytree/issues/2069
- https://github.com/giuspen/cherrytree/issues/1944
- https://github.com/giuspen/cherrytree/issues/2324
- https://github.com/giuspen/cherrytree/issues/2316
- https://github.com/giuspen/cherrytree/issues/2124
- ... and so on ...

... although you released a ticket on the the GNOME developer-hub: https://gitlab.gnome.org/GNOME/gtk/-/issues/5231 , i think it is better to remove ALL problematic sequences from config by default:

```
[keyboard]
codebox_change_properties=
codebox_decrease_height=
codebox_decrease_width=
codebox_increase_height=
codebox_increase_width=
handle_anchor=
handle_bull_list=
handle_codebox=
handle_embfile=
handle_image=
handle_latex=
handle_num_list=
handle_table=
handle_todo_list=
insert_timestamp=
node_unbookmark=
preferences_dlg=
spellcheck_toggle=
table_column_decrease_width=
table_column_increase_width=
table_column_left=
table_column_right=
table_row_delete=
table_row_down=
table_row_up=
tree_node_toggle_ro=
```
Reason:

The problem was also discussed in depth here: https://github.com/msys2/MINGW-packages/issues/13372 ... Windows interprets Ctrl+Alt as AltGr, to accommodate some compact keyboards like those of netbooks which have neither the AltGr key or a right-hand Alt key (https://en.wikipedia.org/wiki/AltGr_key#Ctrl+Alt), so using CTRL+ALT ist not really a good idea and we see this by **the lots of filed issues. It is also a big challenge for a normal user to delete all 26 relevant entries manually by using the gui-method of cherrytree.**

It is possible to sync a partial "config.cfg" (with the entries above) into the users "%USERPROFILE%\AppData\Local\cherrytree" - directory. Cherrytree will then merge its config with this one, when running after copy, but i think it is a better and much simpler solution to **remove all sequences above from default config because also Microsoft does NOT RECOMMEND to use "Ctrl+Alt" as a shortcut modifier:**

* https://devblogs.microsoft.com/oldnewthing/20040329-00/?p=40003

Best regards,
  Veit Berwig

**Comment by giuspen** [comment]
I understand the problem but I need to find another solution rather than suddenly drop all these keyboard shortcuts for everyone.
Ideally replace <alt> with another key (e.g. the windows key, so <ctrl><meta> but this probably won't work, I'll try) or provide a very quick way to remove all the <ctrl><alt> keyboard shortcuts

**Comment by giuspen** [comment]
In upcoming v1.0.3 there won't be anymore any default keyboard shortcuts with Ctrl+Alt
