### ISSUE TITLE
Wrong masked underscore in german translation of msgid "CherryTree File"

### ISSUE THREAD

**Issue by vitusb** [giuspen/cherrytree#2342]
Hello Giuseppe ...

When opening files with the german translation, the german dialog shows ...

"_CherryTree-Datei" and not "CherryTree-Datei":

![_CherryTree-Datei](https://github.com/giuspen/cherrytree/assets/83558069/7386a881-44a0-4c66-a192-3d63b46ec6ac)

The german .po-file of version 1.0.1 has the relevant entry:
https://github.com/giuspen/cherrytree/blob/1.0.1/po/de.po#L94C8-L94C27

The french .po-file of version 1.0.1 does not has this entry:
https://github.com/giuspen/cherrytree/blob/1.0.1/po/fr.po#L95

Best regards,
 Veit Berwig

**Comment by giuspen** [comment]
Vielen Dank Veit, will be fixed in upcoming v1.0.3
