### ISSUE TITLE
Captcha not working on www.giuspen.net

### ISSUE THREAD

**Issue by Sudneko** [giuspen/cherrytree#2343]
I know I'm veering off topic a bit, but how else can I bring this error to the author's atten

**Version, Operative system**
Any version of Windows, any IP address.

**Describe the bug**
The captcha hasn't worked since about July 17, possibly earlier, and it still hasn't been fixed.

**To Reproduce**
Go to 
https://www.giuspen.net/2023/07/cherrytree-1-0-0-issued/
and try to leave a message

**Screenshots**
https://www.giuspen.net/2023/08/cherrytree-1-0-1-issued/
![1](https://github.com/giuspen/cherrytree/assets/7460703/35f8379c-a1e5-4528-8c68-2087a41d5339)

**Comment by giuspen** [comment]
Thanks I wasn't aware, hopefully it is working now
