### ISSUE TITLE
Remove formatting globally ?

### ISSUE THREAD

**Issue by repsorp** [giuspen/cherrytree#2346]
Is there a way to completely remove formatting (Shift+Ctrl+R) globally, I mean "All the tree" ?

**Comment by giuspen** [comment]
No it's pretty dangerous to do this blindly. If you don't have images/codeboxes/tables/latex there is a command in the tree to change all the nodes to plain text though and then you can return to rich text later, that will do. Note you will also lose the links target (retain the link name)

**Comment by repsorp** [comment]
Change Node Properties > Node Type > Plain Text
Apparently doesn't remove Text Color Background...

My problem is that I'd like to change a "Light Style Scheme" for a "Dark Style Scheme" but "Text Color Background" also needs to be modified globally for legibility...

**Comment by giuspen** [comment]
The plain text is following its own theme or style scheme.
Go to the preferences dialog, tab Theme.
Under the Style Schemes choose an existing one or a customisable user-1 or user-2.

**Comment by repsorp** [comment]
Thanks but doesn't solve the problem of "Text Color Background" (Shift+Alt+B) who can't be modified globally.

**Comment by giuspen** [comment]
The plain text doesn't support a background tag, doesn't support any tag, has only global properties associated to the whole tree.
Maybe use screenshots to better describe your issue.

**Comment by repsorp** [comment]
Node Properties > Node Type has been set to "Plain Text"
![2023-09-10 22-38-51](https://github.com/giuspen/cherrytree/assets/6297032/72ba6942-7743-4d97-bf45-a34a3ed10b29)

However "Text Color Background" (Shift+Alt+B) is still active

![2023-09-10 22-37-40](https://github.com/giuspen/cherrytree/assets/6297032/2cbe656e-20fc-48f7-b5b3-6f7e90524514)

**Comment by giuspen** [comment]
Yes but you changed the property of the node named ANDROID, not of all the children. Not of createTarFork...
In the right click menu, not the properties of the node, there's a command to change the syntax of the children (node type) to be the same of the parent. Right click on the node ANDROID and try that.

**Comment by repsorp** [comment]
It's working fine now but losing all the links target is a bummer :-(
Unfortunately I'll have to stick to the light theme
Thanks for your help
