### ISSUE TITLE
Sending Images to clipboard

### ISSUE THREAD

**Issue by SecMyth** [giuspen/cherrytree#235]
Small feature request:
besides enabling to save images as PNG, please allow to save them in clipboard.
I simply want to copy an image from cherrytree to another application like MS Word.

**Comment by giuspen** [comment]
this used to work (tested years ago in windows 7), can you specify windows and office versions?

**Comment by SecMyth** [comment]
I'm using Windows 7 Enterprise SP1 with Microsoft Office Standard 2010 (14.0.7177.5000)
Using the context menu and "copy", But neither Word or IrfanView is able to paste a valid image.

**Comment by giuspen** [comment]
Just tried in win7 and office 2010 and it worked. Please try to run from the python sources in the windows terminal if you can and let me know if the terminal outputs something

**Comment by philippHRO** [comment]
I tested this, too. It does not work when pasting to IrfanView, but in word 2016 it worked.
Windows 10 x64, Cherrytree 0.38

**Comment by txe** [comment]
I checked paste from 0.9918 to InfraView and it worked

**Comment by kettenfett** [comment]
yep! Seems like it's working again. Tested with 0.99.18
