### ISSUE TITLE
Copy Link doesn't work on Windows if text is highlighted

### ISSUE THREAD

**Issue by metal450** [giuspen/cherrytree#2362]
**Version, Operative system**
Windows 10, CherryTree 1.0.2

**Describe the bug**
In a richtext node, if you highlight a line of text that contains a hyperlink, then right-click the hyperlink (while the text is still highlighted), & select "Copy Link" from the context menu, the link is not copied to the clipboard.

If you deselect the text & then right click the hyperlink & "Copy Link", then it works.

Expected behavior: that you can "Copy Link" whether or not the text surrounding it happens to be highlit.

**Comment by Kansai53** [comment]
I can confirm this bug. Copying links doesn't work if there's highlighted text.

**Comment by giuspen** [comment]
this will be fixed in upcoming v1.1.3
