### ISSUE TITLE
Search broken on Linux when updating 1.0.1->1.0.2

### ISSUE THREAD

**Issue by metal450** [giuspen/cherrytree#2365]
**Version, Operative system**
OS: KDE Neon 5.26; CherryTree 1.0.2

**Describe the bug**
After updating from CT 1.0.1 to 1.0.2, search no longer works: if I use Ctrl+T to search for a node name, the results dialog comes up. But selecting one of the nodes in the dialog does not bring up the node in the main UI -in other words, you can see the list of results, but it seems there's no way to actually get back to the resulting node.

**Comment by metal450** [comment]
I also can't seem to get it to rollback - checking the packages on the repo https://launchpad.net/~giuspen/+archive/ubuntu/ppa/+packages , most prior versions aren't there, and I can't get it to install 1.0.1 again with apt.

Please help - how can I rollback to 1.0.1? I'm stuck unable to start work this morning because I can't locate the docs I need among my thousands of nodes :cry:

**Comment by giuspen** [comment]
Ctrl+T is just a Ctrl+Shift+F with the flag to search in node names and tags only, I'm surprised I broke it but will have a look.
You can download the AppImage of a previous release on https://github.com/giuspen/cherrytree/releases that will go on every Linux distro/ version

**Comment by metal450** [comment]
The same occurrs with Ctrl+Shift+F

**Comment by giuspen** [comment]
(also discussed on https://github.com/giuspen/cherrytree/issues/2361)
I've been told that this issue appears on Linux Mint based on Debian 11/Ubuntu 20.04 while it does not on Linux Mint based on Debian 12/Ubuntu 22.04 (a user just upgraded LMDE 5 Debian 11 -> LMDE 6 Debian 12 and told me the issue has gone).
I haven't been able to reproduce it on my Ubuntu 20.04 (non Mint-ed).
I will try Debian 11 shortly, if I still cannot reproduce I will try and get hold of an older Linux Mint (I do have Mint but only the latest based on 22.04).

**Comment by puresse** [comment]
Hello, I managed to pull back to 1.0.1

Here is what I did
1. apt remove cherrytree
2. download libfmt7_7.1.3+ds1-5_amd64.deb from here: https://packages.debian.org/bullseye/amd64/libfmt7/download
3. download cherrytree 1.0.1 for my debian version 11 (ubuntu 20.04, linux mint 20.1) from this link here: https://github.com/giuspen/cherrytree/releases/download/1.0.1/cherrytree_1.0.1-2.Debian11_amd64.deb
4. then install downloaded libfmt via dpkg
5. then install downloaded cherrytree1.01 via dpkg
6. and last but not least, do a "sudo apt-get hold cherrytree" so that it does not get updated again

running fine again.

**Comment by giuspen** [comment]
@puresse I think the AppImage of 1.0.2 should also run fine as the bug seems to be only with a particular gtk3 version. It would be great if you could test that for me. I'll try to reproduce shortly anyway and fix

**Comment by giuspen** [comment]
I cannot reproduce this on Ubuntu 20.04 or Debian 11. Are all the people having this issue on Linux Mint or there are other cases?

**Comment by metal450** [comment]
KDE Neon 5.26

**Comment by giuspen** [comment]
I pushed a new package in the Ubuntu 20.04 / focal PPA. For some reasons (likely a bug in g++ not there anymore anyway in later versions) that compiler plus specific options set from the debhelper builder messed up with a local variable used in multiple lambda functions. After I changed that variable to be non local it went away.

**Comment by metal450** [comment]
I can confirm it's fixed - thanks!
