### ISSUE TITLE
Search Progressbar

### ISSUE THREAD

**Issue by metal450** [giuspen/cherrytree#2373]
https://github.com/giuspen/cherrytree/issues/1830 was resolved, however the "progressbar" portion not yet addressed.

Currently when you perform a search, it appears to do nothing for awhile (it's not clear that it's searching in the background), & then suddenly the results pop up. The first time I did this I actually didn't think the search worked, so searched again, and then 2x results popped up.

Need some sort of progressbar/indicator that a search is in progress.

**Comment by giuspen** [comment]
I'm surprised because there actually is a progress bar on the bottom right and also a stop button beside the progress bar. Which operative system and version are you running?

**Comment by metal450** [comment]
Ohhhh, I see it! It's so tiny down there I didn't even notice it (it's maybe like 3 or 4 pixels tall, and at the VERY bottom of the window with no margin below, so it was virtually clipped by the Windows taskbar. On a large monitor it's almost imperceptible):

![2023-10-19 18 26 12](https://github.com/giuspen/cherrytree/assets/1877409/bc77fcf1-2fdb-424a-90f8-abcc32c5484e)

**Comment by giuspen** [comment]
It in indeed very slim on windows, it depends from the theme I'll see if I can fatten it up

**Comment by giuspen** [comment]
I added a minimum height on windows that fixes this issue
