### ISSUE TITLE
1.0.2 locks up/has to be ended when attempting to cut or copy a codebox.

### ISSUE THREAD

**Issue by dbwiz** [giuspen/cherrytree#2378]
**1.0.2 and 1.01, Windows nolatex.  SQLite (CTB)**
(1268 RT nodes, 2610 images, 114+11 tables, 375 codeboxes, 4793 anchors, 300MB)

**Describe the bug**
On Rich text node, locks up and cursor circles after a few seconds when attempt to move a codebox via cut or copy. Task manager states 15% CPU, no change after 5 minutes.   Ended process.  Did not occur in 1.0.0 as I used it all day since it came out and only upgraded from 1.0.0 to 1.0.2 a couple days ago.   Don't have a copy of 1.0.0 anymore :(   Tried 1.0.1 but same response.   Repeated many times.

**To Reproduce**
1. Open rich text node with codebox (my node was quite lengthy)
2. Select codebox and CTRL+C
3. (system becomes unresponsive)

**Screenshots**
Nil

**Workaround**
None.
Cannot copy missing codebox info from backup copy.
Increase frequency of backup from 120 to 20 mins
Possibly, migrate to file version.

Thank you for writing and your support with CherryTree.  I'll try to build 1.0.0 tonight from source and continue.   This is a critical bug for me, I have to find a solution this weekend.  I may convert to the file version if I can't continue with CTB.
Peter Martin

**Comment by giuspen** [comment]
Hi Peter, you can find version 1.0.0 of windows prebuilt at https://github.com/giuspen/cherrytree/releases/tag/1.0.0
Are you doing copy/cut codebox via right click menu?

**Comment by giuspen** [comment]
Maybe there is some particular content in this codebox that causes the issue. Maybe you can export only this node and send it to me privately?
And please describe exactly what you select before Ctrl+C and also try instead to use the right click menu to see if the result is the same.

**Comment by gitcattail** [comment]
Having the exact problem with cherrytree 1.0.2
Doesen't matter if I run cherrytree on windows or kali linux they both crash when trying to paste or work with not just codebox but just about anything it can randomly crash.
I'm gonna give version 1.0.0 a go. I know I have had cherrytree solid as a rock years ago, but not so much anymore..

Down below is what event viewer got me when it crashed, working on a simple codebox with one line.

Faulting application name: cherrytree.exe, version: 1.0.2.0, time stamp: 0x65133881
Faulting module name: libgtk-3-0.dll, version: 3.24.39.0, time stamp: 0x6513387f
Exception code: 0xc0000005
Fault offset: 0x0000000000247a6c
Faulting process id: 0x0x4F64
Faulting application start time: 0x0x1DA2117A048A41E
Faulting application path: C:\Program Files\CherryTree\mingw64\bin\cherrytree.exe
Faulting module path: C:\Program Files\CherryTree\mingw64\bin\libgtk-3-0.dll
Report Id: 2b79637b-a258-4cc4-8bf2-023c76d9fbdd
Faulting package full name:
Faulting package-relative application ID:

[eventviewer.txt](https://github.com/giuspen/cherrytree/files/13473501/eventviewer.txt)

**Comment by dbwiz** [comment]
My apologies for not replying and continuing the issue, I remember it was very important at the time but I've moved on to the most recent version and not experienced it again.  I can't recall what I did, however the bug is no longer an issue for me.
