### ISSUE TITLE
CT 1.0.2 print very large Anchor symbol

### ISSUE THREAD

**Issue by Groberen** [giuspen/cherrytree#2379]
**Is your feature request related to a problem? Please describe.**

When printing out a page containing an anchor, the anchor symbol is just too large on page. Not measured, but the height of the anchor symbol is roughly 4 times higher than characters formatted with H1.

**Describe the solution you'd like**
A small symbol - if any. Actually, I don't quite see that anchor symbol have a purpose when printed out to paper.
An anchor symbol that have the same height as the surrounded font can be acceptable - or just height of plain text as default if no text around the anchor.

**Comment by giuspen** [comment]
OK I'm just hiding it for now in upcoming v1.0.3 as likely of no use, in case I'll make it configurable if needed
