### ISSUE TITLE
Building.md file for all informations about building

### ISSUE THREAD

**Issue by inson1** [giuspen/cherrytree#2383]
**Is your feature request related to a problem? Please describe.**
I think Readme doesnt look good. All informations there are, are about building the project. Yes, that should be another issue. This one is about moving all the building informations into its own file. So there is space for nicer Readme.

**Describe the solution you'd like**
Create Building.md file for all informations about building the project and then add only one section to Readme with link to that file.

What do you think?

**Comment by giuspen** [comment]
It's a good idea, it would help me if you could propose the rework yourself in a pull request as I'm not exactly an expert in markdown

**Comment by inson1** [comment]
sorry for spam, I'm just reorganizing my solved issues - jg8tzJHCu0Qcc1zJGcht
