### ISSUE TITLE
Cherrytree crashes if table is sorted

### ISSUE THREAD

**Issue by schnaggi** [giuspen/cherrytree#2391]
**Version, Operative system**
1.0.2
Win10 22H2, latest updates

**Describe the bug**
open attached file and sort table, Cherrytree will crash

**To Reproduce**
open attached file and sort table
[cherrytree_crash_20231120.zip](https://github.com/giuspen/cherrytree/files/13420001/cherrytree_crash_20231120.zip)

**Comment by giuspen** [comment]
Thanks I see it

**Comment by giuspen** [comment]
Thanks, will be fixed in upcoming 1.0.3
