### ISSUE TITLE
bookmarked node's name changes dont show up in the bookmarks Menu

### ISSUE THREAD

**Issue by jfoll31** [giuspen/cherrytree#2393]
**Version, Operative system**
1.0.2,Ubuntu 4.15

**Describe the bug**
When I modify the name of a bookmarked node, its bookmark name is not changed inside the bookmarks menu,
although clicking the bookmark do opens the right node.

**To Reproduce**
1. click on a bookmarked node
2. press F2 
3. Change the node name
4. open the bookmarks menu
5. look at the node's bookmark name
6. See that it does not match with the node name

**Screenshots**

**Comment by giuspen** [comment]
Thanks for reporting, this will be fixed in upcoming 1.0.3
