### ISSUE TITLE
Unable to install cherrytree-1.0.2 on Fedora 39

### ISSUE THREAD

**Issue by ynoxia** [giuspen/cherrytree#2394]
**Linux Fedora 39**

Try to install cherrytree-1.0.2.Fedora38_amd64.rpm  on Fedora 39 via dnf.

The installation fails with this message:

```
Errore: 
 Problema: conflicting requests
  - nothing provides libfmt.so.9()(64bit) needed by cherrytree-1.0.2-1.x86_64 from @commandline
  - nothing provides libspdlog.so.1.11()(64bit) needed by cherrytree-1.0.2-1.x86_64 from @commandline
(try to add '--skip-broken' to skip uninstallable packages)

```
In Fedora 39, these libraries are at an updated higher version. :)

Grazie. 🙏

**Comment by giuspen** [comment]
Ciao, I'm releasing new v1.0.3 today and for that I will generate also the Fedora 39 package

**Comment by giuspen** [comment]
Note that there is a third party package here https://fedora.pkgs.org/39/rpm-sphere-x86_64/cherrytree-1.0.2-1.x86_64.rpm.html ( I'm looking usually at https://pkgs.org/search/?q=cherrytree )

**Comment by ynoxia** [comment]
Grazie sempre Giuseppe. Sempre lavoro fantastico. 🙏
