### ISSUE TITLE
F8, it makes a new date entry with wrong month

### ISSUE THREAD

**Issue by GoogleCodeExporter** [giuspen/cherrytree#24]
```
When I use F8, it makes a new "date" entry with wrong month, for example 2015 / 
ѳ / 08. It gives no month at all with February or other month. And I'm not 
sure what this Greek symbol "ѳ" means either...
I got Windows 7 Pro (Ukrainian).
```

Original issue reported on code.google.com by `giuspen@gmail.com` on 8 Jan 2015 at 8:48

**Comment by xubin0523** [comment]
I got no month using windows 7 (chinese)

**Comment by giuspen** [comment]
Wrong month or no month at all? A screenshot would help

**Comment by txe** [comment]
It should be fine now, the issue was that text wasn't converted from locale to utf8
