### ISSUE TITLE
Syntax highlighting for Solidity.

### ISSUE THREAD

**Issue by ArtyomPythonski** [giuspen/cherrytree#2401]
I am taking notes while studying solidity and I noticed that the app is missing syntax highlighting for this programming language. It would be great if you would consider adding it to the project.

**Comment by giuspen** [comment]
Hello Artyom, solidity is already supported in the current version 1.0.3.
Which version are you using?

**Comment by ArtyomPythonski** [comment]
Thank you for your response it seems that my version is still 0.99, I installed  the app using apt repository.
I wonder why it doesn't update it?

**Comment by giuspen** [comment]
Most of the packages are not updated unless it's a rolling release distribution.
If you are using Ubuntu or Linux Mint please add the giuspen repository PPA as described on https://www.giuspen.net/cherrytree/#downl that will keep your cherrytree automatically up to date. If you have a Debian you have to manually install the package when there is an update, the packages are all in the same link as the PPA instructions
