### ISSUE TITLE
Since v1.0.3, search dialog keeps coming up with very large dimensions 

### ISSUE THREAD

**Issue by Ricent82** [giuspen/cherrytree#2404]
Since updating to CherryTree v1.0.3 on Windows (from 1.0.2), the "search" dialog keeps coming up with very large dimensions (obstructing most of the screen). I keep reducing the size, but after some period of time it just reverts to its large dimensions again - so I have to keep resizing it over & over again. I find myself shrinking it down many times per day, which never happened prior to updating.

**Comment by giuspen** [comment]
Thanks @Ricent82 I got this fixed I will release a new version v1.0.4 later today

**Comment by Ricent82** [comment]
Great, thanks!

**Comment by giuspen** [comment]
Fixed in v1.0.4
