### ISSUE TITLE
Search in 'node name and tag' kills cherrytree

### ISSUE THREAD

**Issue by useross** [giuspen/cherrytree#2405]
**Version, Operative system**
Cherrytree 1.0.3, Manjaro Linux

**Describe the bug**
The search (in node names and tags) starts, one can see the slow loading indicator for 10 seconds and then the program crashes. My Database is very big with about `1.9 GB`. Usually the results are there within 1 second.

**To Reproduce**
1. Search -> Search in node names and tags
2. Search whatever you want
3. See very slow loading indicator
4. Watch cherrytree chrashing

**Comment by giuspen** [comment]
Thanks @useross I think I got this fixed, I will release a new version v1.0.4 later today.

If you want to pre test, you can try to build locally following https://github.com/giuspen/cherrytree/blob/master/BUILDING.md#building-cherrytree-on-arch-linux-manjaro-linux or I can prepare an AppImage binary (working on all Linux 64bit)

**Comment by giuspen** [comment]
Fixed in v1.0.4

**Comment by useross** [comment]
Thanks! :)
