### ISSUE TITLE
Toolbars icons very hard to see on 4K resolution

### ISSUE THREAD

**Issue by pckeller29** [giuspen/cherrytree#2406]
Distributor ID: Ubuntu
Description:    Ubuntu 23.10
Release:        23.10
Codename:       mantic

Host computer: Asus ZenPro Duo [UX582](https://www.asus.com/laptops/for-creators/zenbook/zenbook-pro-duo-15-oled-ux582-11th-gen-intel/)

Cherrytree: 1.0.4

On a 4K 16" laptop screen, the toolbar icons are really tiny making them hardly viewable.

**Screenshots**
![Screenshot_20231217_055726](https://github.com/giuspen/cherrytree/assets/9974154/7c0ce2ae-d741-4824-af3a-6a6416379f0b)

As far as I know, there are ways to customize the texts items (by setting dpi/zoom in KDE settings for example) but I haven't found anything in CT to select different set of icon sizes like small, default, big for example.

Actually I'm not sure whether this is a bug or more kind of a feature request.
Thanks for letting me know

Steps to reproduce:
Of course the easiest would be to have such a screen. Without that, I guess opening the attached screenshot full screen then zooming out to have it filling entirely the display should efficiently show the issue.

**Comment by giuspen** [comment]
Hi, probably I should put that setting also in the preferences dialog so that it's move visible, however currently you can still change the size of the toolbar icons under the top menu View--Increase/Decrease toolbar icons

**Comment by giuspen** [comment]
toolbar icons size will be configurable also in prefere3nces dialog in release v1.1.0
