### ISSUE TITLE
xml-stripblanks WARNING when building Debian package

### ISSUE THREAD

**Issue by DennisRasey** [giuspen/cherrytree#2410]
**Version, Operative system**
Debian Testing (docker image debian:testing-slim).
Cherrytree 1.0.4 & latest git version

**Describe the bug**
xml-stripblanks message when building Debian package

**To Reproduce**

> ./build.sh deb

Gives following WARNING (does not appear to be fatal)

> xml-stripblanks preprocessing requested, but XMLLINT is not set, and xmllint is not in PATH

**Resolution**
`apt install libxml2-utils`

**Notes/Thoughts**
Since this appears to only be a WARNING & still results in a successful build; do we gain anything by installing libxml2-utils?

**Comment by giuspen** [comment]
The warning is generated here https://github.com/giuspen/cherrytree/blob/master/scripts/gresource_to_c.py in fact I don't think we gain in stripping the XML blanks as a C file is generated and used at the end of the process but the warning is annoying. I'll check to either disable the stripping or add the dependency

**Comment by giuspen** [comment]
Actually I'm wrong as the .SVG files are .XML
We should add the dependency

**Comment by giuspen** [comment]
Could you be so kind to open a PR as you did for file? :)

**Comment by DennisRasey** [comment]
Created a PR for this
#2415
