### ISSUE TITLE
Possible (small) Bug with CT Color Picker (Custom Font [Background] Color)

### ISSUE THREAD

**Issue by BlauBlinki** [giuspen/cherrytree#2422]
**Version, Operative system**
Tested CT Versions: v1.0.2, v1.0.4
Tested OS: Ubuntu 20.04.6 LTS, Windows 10Px64 (both German Enviroment)

**Describe the bug**
When defining your own custom Font (Background) Color by clicking the "+" Button, always 2 Color Boxes are occupied, instead of one Color Box only.

Tested with an fresh downloaded Copy of CT v.1.0.2 & v1.0.4 at Windows and Ubuntu (PPA installed Version), and if I remember right, the Situation was also already with v0.99.5 too.

Since I use some selfdefined Font Colors, it's rather annoying after 4 Colors you'll start to overwrite the first Color again! :(

Ofc, if there's a method to change the whole default CT Color Palette, I'd change it to my needs! ^^;

So thx in advance for some feedback, or even an Fix if neccessary. ;)

**Screenshots**
![2024-01- 5_cherrytree_ColorPicker_Bug](https://github.com/giuspen/cherrytree/assets/150734054/2539ee98-a9df-4111-a40a-92ccc3b490d0)

**Comment by giuspen** [comment]
I see it thanks for reporting, I'll get back

**Comment by BlauBlinki** [comment]
@giuspen

At your service! ^^

**Comment by giuspen** [comment]
The custom colours are controlled privately from the GTK3 library, the bug is actually there but it's possible to define the top palette completely.
I like the default palette so I'm oriented to not change that but rather to append the last used colours in additional rows and save into the config.cfg for export/re-import 
How many last used colours would suffice your use case?

**Comment by BlauBlinki** [comment]
Well, 8 (9?) color choices should be enough. (at least for me) As shown in the Screenshot I mainly use brighter Versions of the default color Palette.

**Comment by BlauBlinki** [comment]
Of course you could define 2 (or more) rows of additional color boxes... in the end you're the Master of CT, so your word is final! :D

**Comment by giuspen** [comment]
I'll sleep on it but probably tomorrow I'll add 2*9 rows of customs to the palette.
Cheers @BlauBlinki ;)

**Comment by giuspen** [comment]
I have now added up to 2 rows (18) of custom colours that appear below the default colour palette after you select the 1st / 10th. If you would like to try it before the release let me know which package you need as I can prepare it for you.

**Comment by BlauBlinki** [comment]
"If you would like to try it before the release let me know which package you need as I can prepare it for you."

Well, I'd say the AppImage? Would be IMO the quickest way to test/check, and then update evering else? (PPA first, yes? ;)

**Comment by giuspen** [comment]
Please try https://www.giuspen.net/software/CherryTree-1.0.4+16-x86_64.AppImage and provide feedback

**Comment by BlauBlinki** [comment]
Excellent! 18 Boxes for selfdefined Colors should be really enough... After the 19th Color is set, the first one becomes overwritten without any error.

THX A BUNCH FOR THE QUICK WORK, MATE! (and I wasn't aware the AppImage taps on the same CT settings like the PPA Version :)

![2024-01-13_TC_AppImmage_Colorpicker_NEW](https://github.com/giuspen/cherrytree/assets/150734054/9bd50120-3639-496e-815e-7a5cbcf8a68c)

**Comment by giuspen** [comment]
Thanks for testing it mate ;)

**Comment by BlauBlinki** [comment]
Uhm, not to sound stingy, but when can we expect the new color feature in CT? Thx for some feedback.

**Comment by giuspen** [comment]
I wanted to release today but decided to delay a week to improve the search inside of tables/codeboxes, so next weekend v1.1.0 will be
