### ISSUE TITLE
Request: Larger + Wider Scrollbars

### ISSUE THREAD

**Issue by glimmerwell** [giuspen/cherrytree#2427]
Thank you so much for this awesome program!

I would like to request that there be an option to have (much) wider scrollbars. I am on Windows 10 and use dual monitors, with both 1080p and 4K screen resolutions. Often it is difficult to grab the scroll bar as it is really thin and small. 

A larger scrollbar target would speed up the workflow significantly. Also, it would reduce eye strain.

Please consider an option to make them wider and also bigger.

Thanks again!

**Comment by giuspen** [comment]
I did increase significantly the size of the scrollbars on windows as it is indeed hardly usable with that GTK theme. If it will be enough for you I won't make it configurable, otherwise I will make it configurable for now only manually editing the config.cfg file. If you wish to evaluate I can make a Windows build for you.

**Comment by glimmerwell** [comment]
Hey, thank you so much! I would love (and be honored) to evaluate your test build. 

I use the extension **Scrollbar Customizer** in some of my browsers. And I started making my web browser scrollbars perhaps 7mm (1/2 inch) wide with custom colors. I know that is bigger than most people would like.
https://chromewebstore.google.com/detail/scrollbar-customizer/flffekjijpabhjgpoapooggncnmcjopa 

Also, I notice that you have CherryTree hide the scrollbar when the user is not using or hovering over it. That is beautiful, and I am sure many users would prefer that. However; I have found that now I prefer to see it always so on a very long page I can tell by just looking where I am on the page, top, middle or bottom.

Still, I have tried many text editors, notepad utilities and notetaking applications over a very long time. And you have by FAR the best one! I have configured the toolbar and the theme, and it is amazing! Thank you so much for this great tool! I use it every day.

**Comment by giuspen** [comment]
Please download the portable test version https://www.giuspen.net/software/cherrytree_1.0.4.0+18_win64_portable.7z and provide feedback. I also added an option in config.cfg 'overlay_scroll' that you can manually edit changing the value from 2 (system settings) to 0 (off) to disable the overlay scrollbar for the text and so ensure that it doesn't hide

**Comment by giuspen** [comment]
That's ok I'll put also the min scrollbar size in the config.cfg only for now

**Comment by glimmerwell** [comment]
Awesome! I will look forward to the next update! No rush, though!

**Comment by glimmerwell** [comment]
Hi, I just wanted to say thank you again. You continue to impress me with this incredible software of yours! And also how responsive you were!

Also, I love how you handled the UI options with the new scrollbar feature! Genius! 

I just donated to you with PayPal. It is not much, but I hope it helps! Thanks again!

Fat scrollbars...!

**Comment by glimmerwell** [comment]
Oh good, I see you saw the message! Thanks again!

**Comment by giuspen** [comment]
Thanks to you my friend ;)
