### ISSUE TITLE
[0.38.0] Can't import from RedNotebook

### ISSUE THREAD

**Issue by vitovt** [giuspen/cherrytree#243]
[0.38.0] Can't import from RedNotebook
When I choose Import, it ask to open the directory with RedNotebook files and does nothing after that.

**Comment by giuspen** [comment]
Could you zip the directory with the RedNotebook files and share with me?

**Comment by vitovt** [comment]
Here you are

--
Sincerely,
Vitalii Titskiy
tel./Viber: +38(063) 854-64-45
tel.         : +38(067) 713-51-08
http://www.facebook.com/vitovt

Детские товары для спорта, развития и безопасности с доставкой по всей
Украине.
http://kryhitka.com/

Детские спортуголки с доставкой по России:
http://kryhitka.ru/

2017-04-17 22:14 GMT+03:00 Giuseppe <notifications@github.com>:

**Comment by vitovt** [comment]
Here is it:
https://www.dropbox.com/s/jtqji4mtslm9i1b/rednotebook.tar.bz2?dl=0

**Comment by giuspen** [comment]
Thanks, can you try the current git master HEAD version?

**Comment by vitovt** [comment]
I've just tested it.
It was imported successfully.

But some items shows with broken formatting. And some are ok.
![image](https://cloud.githubusercontent.com/assets/315178/26242766/3c45c592-3c92-11e7-8cce-e744959f1b94.png)

![image](https://cloud.githubusercontent.com/assets/315178/26242786/49595bcc-3c92-11e7-8a71-8ccda37ebfd7.png)

and another one:

![image](https://cloud.githubusercontent.com/assets/315178/26242858/9388ba1c-3c92-11e7-945e-6e1af6d915d0.png)

![image](https://cloud.githubusercontent.com/assets/315178/26242876/a46a8fcc-3c92-11e7-8489-41c69979a02e.png)
