### ISSUE TITLE
Option to use traditional title bar and menu or FireFox/Opera style menu.

### ISSUE THREAD

**Issue by HubKing** [giuspen/cherrytree#2443]
**Is your feature request related to a problem? Please describe.**
There are too many top-level menu items, so on a laptop where the main window is small, there is barely any space that I use for window-dragging. I keep accidentally click the menu item when I tried to drag the window.

I could hide menu by F12, but then the title bar is unnecessarily thick.

![image](https://github.com/giuspen/cherrytree/assets/10900489/f8280f63-8e1e-4d94-bf2d-c7733810689b)

**Describe the solution you'd like**
(1) Option to use traditional title bar and menu. It doesn't seems like using the combined menu saves much vertical space any way.

![image](https://github.com/giuspen/cherrytree/assets/10900489/1385828b-8bf8-4a49-b532-7f900acbbb0f)

(2) Opton to use FireFox/Opera-like single menu button. The hamburger on the left or right most of the title bar.

(3) Let users customise menu items. I could move some of the top-level items that I don't use into another top-level item.

(4) Option to make menu open on mouse-up, and allow window-dragging on the top-level menu item. That is, if I press the mouse button on "File" and without lifting it I move the mouse, it drags the window without opening the menu. If I press the mouse button on "File" and without moving the mouse if I lift the button, then the menu opens without dragging the window. This is how other Gnome applications work. For example, Open Gnome Files, do the thing I described on the hamburger icon.

**Comment by giuspen** [comment]
Hi, if you click on the top menu item View you will already find the possibility (1) to disable/enable the menu bar in title bar option

**Comment by HubKing** [comment]
> menu item View

Yeah, I found it. I had searched this option in the Preferences.

**Comment by giuspen** [comment]
It is a valid point as other users also missed the options under the menu View, I will have a thought maybe I'll replicate those also in a new preferences dialog tab

**Comment by HubKing** [comment]
> replicate

The option requires a restart, so, in my opinion, I don't think it belongs to the main menu. Preferences is probably a better place. Menu items are probably for things that can change on-the-fly or people need to do multiple times during a session.

**Comment by giuspen** [comment]
I added the option also in the preferences dialog, will be in upcoming v1.1.0
