### ISSUE TITLE
Backup path twice

### ISSUE THREAD

**Issue by mseliger** [giuspen/cherrytree#2445]
**Version, Operative system**
Linux Mint 21

**Describe the bug**
I've set the following preferences in CherryTree
- Links > Use Relative Paths for Files and Folders
- Miscellaneous > Custom Backup Directory: data
My file is stored at:
/media/msel/Medien/att/cb/Bibliothek/Maria Seliger/Zettelkasten (66621)/
The backup files are stored at:
/media/msel/Medien/att/cb/Bibliothek/Maria Seliger/Zettelkasten (66621)/data/_media_msel_Medien_att_cb_Bibliothek_Maria Seliger_Zettelkasten (66621)_Zettelkasten - Maria Seliger.ctb/
So the path is doubled.
If I don't use a custom backup directory then the files are stored in the same folder as the file.

**Comment by mseliger** [comment]
The path shown in the preferences:
![Path](https://github.com/giuspen/cherrytree/assets/8599087/f571b1bb-e1de-4903-8869-ad14e3d92461)

**Comment by giuspen** [comment]
Hi @mseliger the reason for the annoying path inside of the custom backup directory is that, while in the same directory of the cherrytree document you cannot have another document with the exact same name, this cannot be guaranteed for your whole filesystem where every document (potentially with the same filename) backup goes anyway in the same backup folder. Does it make sense?
