### ISSUE TITLE
Version 1.1.0: Ctrl+T stopped working

### ISSUE THREAD

**Issue by firepainting** [giuspen/cherrytree#2461]
**Version, Operative system**
CherryTree 1.1.0
Linux Mint 21.3 Cinnamon

**Describe the bug**

After 1.1.0 update:
1. Ctrl+T ("Find in Nodes Names and Tags") stopped working. 
2. (Ignore this part, please) ~~IIRC tags used to be just under the nodes and subnodes (in the Tree, on the left side). Those tags were enclosed by square brackets. They all seem gone now, too.~~

**To Reproduce**

1. Open any .ctb file.
3. Press Ctrl+T.
4. The search dialog appears but will not return searched node names or tags.

**Screenshots**

Note: "Node Name and Tags" is ticked.

![Ctrl_T](https://github.com/giuspen/cherrytree/assets/50393421/f0d1574e-8be2-40f9-82c3-e85cd022603e)

TIA!

**Comment by R3ality** [comment]
Confirming same issue (Find in Node Names and Tags not returning any results) on Windows (cherrytree_1.1.0.0_win64_portable_nolatex).

Enabling/disabling any search options doesn't seem to have any effect (no results returned)
Same issue in newly created CTX as well as pre-existing ones

![image](https://github.com/giuspen/cherrytree/assets/762122/ba12f790-fad9-4016-bc28-c9549e51b986)

**Comment by giuspen** [comment]
Thanks for reporting I'll sort it out within a couple of days and release a new version

**Comment by Groberen** [comment]
Confirm this issue on Windows 10, the 7z portable version.

downgrading to version 1.0.4 resolve the issue.

**Comment by giuspen** [comment]
This should be now fixed. If you could try the test build from https://www.giuspen.net/cherrytree/#testing (called 1.1.0+5) and report if that works as expected or still has issues it would be very useful

**Comment by R3ality** [comment]
Happy to report that find in "Node Names and Tags" functionality seems to be working fine on Windows with the test version `cherrytree_1.1.0.0+5_win64_portable.7z`. Furthermore it is now lightning fast like before 1.0.4 which is a very very welcome fix for large .ctx files :)

Verified some of the other search options as well without issues when searching in node names (Match Case, Whole Word, Start Word, Regular Expression (only a few simple ones)). Cannot comment on item nr. 2 raised by @firepainting as I am not familiar with using tags.

Thanks for addressing and thank you for your continued work on this amazing tool!

**Comment by firepainting** [comment]
Hi. (I've been away.)

>If you could try the test build from https://www.giuspen.net/cherrytree/#testing

Just tested CherryTree-1.1.0+7-x86_64.AppImage from the above link and unfortunately on my end, searching got worse.

![CT_Test](https://github.com/giuspen/cherrytree/assets/50393421/5f71835b-86ca-4800-b36e-04cb0f86fae8)

In the screenshot above, all nodes and subnodes are tagged `tag search`.

If I Ctrl+T, it seems to only return the topmost and leftmost node.

In the above example:
- If I Ctrl+T `tag search`, it only returns the red cherries (node 1 and node 2)
- If I Ctrl+T `node search`, same as above (red cherries -- node 1 and node 2)
- If I Ctrl+T `subnode 1.`, it only returns the blue cherries (under node 1)--it doesn't return the other node names containing `1.1.1`, `1.2.1`, and `1.2.1.1`

--

The current version's (1.1.0) search function is better in the sense that if I Shift+Ctrl+F, everything is returned (including node names and tags).

With the test build (1.1.0+7), doing Shift+Ctrl+F yields exactly the same in my example above.

--

Re: my point number 2: my bad. The tags inside square brackets do appear on the search results. Got confused there, I think. I'd rather have those square brackets only in the search results box, anyway, and not on the tree itself.

![Tags_Square](https://github.com/giuspen/cherrytree/assets/50393421/6abf5e00-d1c7-4fec-a6bb-bdd1d1c824b5)

Many thanks.

**Comment by giuspen** [comment]
@firepainting thanks for getting back, can you attach the test document from the screenshot please? Or send me via email (find it in help--about dialog)

**Comment by firepainting** [comment]
@giuspen, just emailed you. Thanks!

**Comment by giuspen** [comment]
Git it thanks @firepainting I'll use it later today, may also release v1.1.1 afterwards as there are few important fixes

**Comment by giuspen** [comment]
This should be now fixed. If you could try the test build from https://www.giuspen.net/cherrytree/#testing (called 1.1.0+10) and report if that works as expected or still has issues it would be very useful. The plan is to release v1.1.1 tomorrow the 27th

**Comment by firepainting** [comment]
Just tested CherryTree-1.1.0+10-x86_64.AppImage and all my issues seem resolved now.

Huge thanks, @giuspen! Can we close this Issue now?

**Comment by giuspen** [comment]
Many thanks @firepainting your testing was very useful, I will close this later today just after the new release

**Comment by firepainting** [comment]
You're so welcome @giuspen and I can't thank you enough, CherryTree is a glorious app :)

**Comment by giuspen** [comment]
Fixed in v1.1.1
