### ISSUE TITLE
Gtk-Warning  & CtDocXmlStorage exception - File does not open

### ISSUE THREAD

**Issue by BFK1975** [giuspen/cherrytree#2471]
**Version, Operative system**
Cherrytree 0.99.48
Parrot Security Edition 6.0, Release Date Jan 24, 2024

**Describe the bug**
Cherrytree starts up fine. If I open an encrypted Cherrytree File, which works fine on both my Kali and Windows OS, I get the following warnings and errors in the shell:

(cherrytree:2894): Gtk-WARNING **: 20:28:38.313: Invalid input string
(cherrytree:2894): Gtk-WARNING **: 20:28:38.314: Invalid input string
(cherrytree:2894): Gtk-WARNING **: 20:28:38.317: Invalid input string
(cherrytree:2894): Gtk-WARNING **: 20:28:38.317: Invalid input string
[2024-03-29 20:28:43.356] [   ] [debug] shift images in MenuBar/context menu
[2024-03-29 20:28:53.785] [   ] [error] CtDocXmlStorage got exception: vector::_M_range_check: __n (which is 168) >= this->size() (which is 140)

Additionally, the following Error appears in a separate window on the screen.

Error Parsing the Cherrytree File:
"CtDocXmlStorage got exception: vector::_M-range_check:__n(which is 168) >= this->size() (which is 140)".

This error message can be clicked away be pressing "Ok". However, opening of the CherryTree file stops at the second node and as soon as I try to click a node to open the program shuts down.

Thanks for your help, it is much appreciated ! I would love to be able to use my CherryTree file on Parrot OS as well.

**Comment by giuspen** [comment]
Hi @BFK1975 I read that Parrot 6 is based on Debian 12 so I advise you to download the latest Debian 12 package from https://www.giuspen.net/cherrytree/#downl currently v1.1.1 and report if you still have the issue with that (0.99.48 is very old)

**Comment by BFK1975** [comment]
Hi @giuspen 
thanks a lot, that worked perfectly  :-) 
Sorry for this silly issue - just strange however that installing cherrytree from command line picked such an old version even though I ran "sudo apt update" before the installation.

**Comment by giuspen** [comment]
No worries @BFK1975 - The official repository in Debian stable unfortunately does not keep up with the version updates of cherrytree. You will only see updates in Debian unstable. Anyway there is a checker for newer versions under the help menu or you can enable the new version check automatically every time you start cherrytree in the preferences dialog
