### ISSUE TITLE
Cherry Tree crashes a parent node is deleted

### ISSUE THREAD

**Issue by Hodgy75** [giuspen/cherrytree#2476]
**Version, Operative system**
State the Version and the Operative System/Desktop. Try the latest available version before reporting an issue.
Cherry Tree 1.1.1
UBuntu 22:04

**Describe the bug**
Every time I try to delete a parent node (i.e. I want to to delete a parent and its children) CT crashes, and the nodes I want to delete are still there. To delete the nodes I have to start at the children, individually, which takes a long time when there are many child nodes.

**To Reproduce**
If applicable, attach a non-personal document where the issue can be reproduced systematically.
1. Go to 'parent node...'
2. Click on 'right click delete node....'
4. See error: app crashes, node not deleted

**Screenshots**

**Comment by giuspen** [comment]
@Hodgy75 could you please test https://www.giuspen.net/software/CherryTree-1.1.1+16-x86_64.AppImage ?

**Comment by Hodgy75** [comment]
Tested 1.1.1+16_64.AppImage. That works absolutely fine for me. Will you put the changes in the version on your Ubuntu repo?

Thank you for CT. I've just this week started using it again, after not for a few years, because now there is Sour Cherries for Android. In CT I like the large number of options for rich text editing, and the fact that the UI is highly customisable.

Ian

**Comment by giuspen** [comment]
Yes I will try to release v1.1.2 tonight as from tomorrow I'm on holiday for about 10 days

**Comment by Hodgy75** [comment]
Don't rush on my part. Enjoy your rest.

Apr 4, 2024 7:20:43 PM Giuseppe Penone ***@***.***>:

**Comment by giuspen** [comment]
Thanks @Hodgy75 ;)

**Comment by giuspen** [comment]
Fixed in v1.1.2
