### ISSUE TITLE
CT don't start after Update with old config file

### ISSUE THREAD

**Issue by joe-vis-git** [giuspen/cherrytree#2482]
Hello, I am using the portable "Windows" version of cherrytree 1.0.4 and wanted to update to version 1.1.1 or 1.1.2. I always replace the complete directory. After starting the .exe nothing happens. This method has always worked. I have now renamed the config in the user directory "C:\Users\user\AppData\Local\cherrytree" and the new version of Cherrytree works. I suspect that my config contains something that prevents the new versions from starting. Has anything been changed in the config files for the new versions?
Thank you very much
best regards
Jens

**Comment by giuspen** [comment]
Hello Jens, did you find out what in the config was preventing cherrytree to start? Was it not starting at all or crashing? Could you share with me privately the config that causes it to not start? (My mail in help--about dialog)

**Comment by joe-vis-git** [comment]
Hi Giuseppe,
yes, I have found the problem. In the config.cfg I had added the following elements under the [misc] [toolbar_ui_list] item
[fmt_indent] and [fmt_unindent]. When I deleted the elements, I was able to start cherrytree again. 
Maybe something has changed in the elements?
Best regards
Jens

**Comment by giuspen** [comment]
Hi @joe-vis-git this information is very useful, thanks, would you be able to copy/paste into this ticket the portion of the config.cfg before and after? I would like to get to the bottom of this.

**Comment by joe-vis-git** [comment]
**Hi Giuseppe,**
here are the two lines of the toolbar_ui_list. I seem to have added the same buttons twice [fmt_unindent,fmt_indent] maybe this is also the problem.
**Best regards
Jens**

**crashs with version 1.1.2.0**
toolbar_ui_list=toggle_show_tree,tree_add_node,tree_add_subnode,separator,go_node_prev,go_node_next,separator,**fmt_unindent,fmt_indent,***,ct_save,export_pdf,separator,find_in_allnodes,find_in_node,find_in_node_n_sub,separator,handle_bull_list,handle_num_list,handle_todo_list,nodes_all_collapse,nodes_all_expand,**fmt_indent,fmt_unindent**,separator,handle_image,handle_table,handle_codebox,handle_embfile,handle_link,handle_anchor,separator,SpecialCharsMenu,fmt_clone,fmt_latest,fmt_rm,separator,fmt_color_fg,fmt_color_bg,fmt_bold,fmt_italic,fmt_underline,fmt_strikethrough,fmt_h1,fmt_h2,fmt_h3,fmt_small,fmt_subscript,fmt_superscript,fmt_monospace,codebox_increase_width,codebox_decrease_width,codebox_decrease_height,codebox_increase_height

**now it works:**
toolbar_ui_list=toggle_show_tree,tree_add_node,tree_add_subnode,separator,go_node_prev,go_node_next,separator,*,ct_save,export_pdf,separator,find_in_allnodes,find_in_node,find_in_node_n_sub,separator,handle_bull_list,handle_num_list,handle_todo_list,nodes_all_collapse,nodes_all_expand,**fmt_indent,fmt_unindent**,separator,handle_image,handle_table,handle_codebox,handle_embfile,handle_link,handle_anchor,separator,SpecialCharsMenu,fmt_clone,fmt_latest,fmt_rm,separator,fmt_color_fg,fmt_color_bg,fmt_bold,fmt_italic,fmt_underline,fmt_strikethrough,fmt_h1,fmt_h2,fmt_h3,fmt_small,fmt_subscript,fmt_superscript,fmt_monospace,codebox_increase_width,codebox_decrease_width,codebox_decrease_height,codebox_increase_height

**Comment by giuspen** [comment]
Many thanks @joe-vis-git I have now fixed this crash, I will also shortly improve the toolbar configurator so that it won't allow to insert the same button twice
