### ISSUE TITLE
CT is not using system-wide language for spell check (English, United States)

### ISSUE THREAD

**Issue by firepainting** [giuspen/cherrytree#2488]
**Version, Operative system**
CherryTree 1.1.2
Linux Mint 21.3 Cinnamon

**Describe the bug**
(Same as title)

**Details**

**Linux Mint system:**
![language](https://github.com/giuspen/cherrytree/assets/50393421/0f215a90-c6e5-4eec-bb15-b78174481058)

![english_us](https://github.com/giuspen/cherrytree/assets/50393421/2f80e18a-09ca-47c7-bb46-b430dfd0ac33)

I just removed the rest of the installed languages, around 22 of them.

Just to be sure, `Enchant 2.3.2` has been installed.

(2 screenshots below)
![synaptic](https://github.com/giuspen/cherrytree/assets/50393421/0f24404c-a2e7-41af-9839-b55c83145494)
![synaptic_2](https://github.com/giuspen/cherrytree/assets/50393421/a534ffdc-16f6-44bd-9d84-c910352d042e)

**CherryTree's Language: System Default**

![system_default](https://github.com/giuspen/cherrytree/assets/50393421/86e3a905-d05f-4497-94e2-8bee806108be)

**To Reproduce**

On CherryTree:
1. Enable Spell Check (Shift+Alt+S)
2. Type US and UK English words
3. US English is marked while UK English is not--except for a few, surprisingly.

Structure below is:
**[US word] [UK word]**

**(First screenshot)**
![sample_1](https://github.com/giuspen/cherrytree/assets/50393421/572cee71-9864-4e23-9edb-6b151303b398)

**(Second screenshot)**
![sample_2](https://github.com/giuspen/cherrytree/assets/50393421/f415693d-161c-4bb6-87fd-529be2f837c6)

(Tag/s: dictionary)

Many thanks!

**Comment by giuspen** [comment]
The language to use in the spell check is selectable in the preferences dialog, tab rich text if I remember correctly, it's a different setting than the interface language.
I will double check that the default for the spell check tries to match the interface language, that may indeed be missing

**Comment by firepainting** [comment]
Well that was...absolutely embarrassing. How to read the manual 101 and spell check vs interface. Got it! 😂️

It's working as expected now. All UK words on the right side are marked.

>preferences dialog, tab rich text if I remember correctly

Yeah that's it.

Many thanks man 😩️

**Comment by firepainting** [comment]
@giuspen CherryTree flags hyphenated compound words. Is it possible to change or correct this?
![hyphen_CT](https://github.com/giuspen/cherrytree/assets/50393421/caf7b997-442f-49d0-a1d0-897536a0d486)

For comparison, LibreOffice Writer doesn't flag them unless of course they're misspelled.
![hyphen_LO](https://github.com/giuspen/cherrytree/assets/50393421/e459789c-22c8-4336-a374-430e4357a984)
