### ISSUE TITLE
Application crash while importing a text file.

### ISSUE THREAD

**Issue by LadyMikea** [giuspen/cherrytree#2492]
Application crash while importing a text files. The files in question are an old dos text files, which I included bellow. Error code is:

Faulting application name: cherrytree.exe, version: 1.1.2.0, time stamp: 0x660f1243
Faulting module name: libstdc++-6.dll, version: 0.0.0.0, time stamp: 0x660f1241
Exception code: 0x40000015
Fault offset: 0x0000000000027dfc

Cherrytree 1.1.2, Windows 10 64bit.

I can copy-paste contents of these files with no problem (and they are displayed correctly with monospace font), but direct import is impossible (import/from plain text file).

[sbpro.txt](https://github.com/giuspen/cherrytree/files/15078303/sbpro.txt)
[sbdsp.txt](https://github.com/giuspen/cherrytree/files/15078345/sbdsp.txt)
[gus.txt](https://github.com/giuspen/cherrytree/files/15078390/gus.txt)

**Comment by giuspen** [comment]
Thanks @LadyMikea I can reproduce it, I'll come back shortly

**Comment by giuspen** [comment]
Thanks @LadyMikea this crash is now fixed. If you are happy to try the fix, I'll build a portable test bundle that you can try and report the result.

**Comment by LadyMikea** [comment]
Well, thank you! I can try a new build of course. I have a weird bunch of odd text files ready to try...

**Comment by giuspen** [comment]
Thanks @LadyMikea please try https://www.giuspen.net/software/cherrytree_1.1.2.0+6_win64_portable.7z and report if it works now as expected

**Comment by LadyMikea** [comment]
Import of plain text files works perfectly now. Thank you very much!
