### ISSUE TITLE
File created ~

### ISSUE THREAD

**Issue by HanaO00** [giuspen/cherrytree#250]
Hello, i use the option "save as", he create the file "Save.ctb" and an invisible file "Save.ctb~"

If i use "Save as" can i remove the invisible file "Save.ctb~" ?

Thank you

**Comment by philippHRO** [comment]
The files with "~" are the automatic backup files, which are maintained by CherryTree.
You can delete them or disable the automatic backup function in the cherrytree settings under "Edit -> Preferences -> Miscellaneous -> Saving"
