### ISSUE TITLE
Deleted ctx-File after "Save as" dialog

### ISSUE THREAD

**Issue by DarthtidusX** [giuspen/cherrytree#2504]
**Version 1.1.2, Operative system Windows 11 Enterprise**
State the Version and the Operative System/Desktop. Try the latest available version before reporting an issue.

**Describe the bug**
When I tried to save my content via "save as" dialog I become an error --> see picture.

The old file were delete but the new file not created.

**To Reproduce**
If applicable, attach a non-personal document where the issue can be reproduced systematically.
1. Go to File.'
2. Click on 'Save as'
3. Click on 'Single SQLite File, 7-zip Encrypted and Password Protected (.ctx)'
4. Set new Password
5. Save to network storage
6. Delete old File
7. Get the Error !! sqlite3 .... table node already exists

**Screenshots**

![cherrytreeBug](https://github.com/giuspen/cherrytree/assets/9286374/17bd8a30-14f5-4a8e-ba50-315560550571)

**Comment by DarthtidusX** [comment]
Hi,

yes that's the issue.
Okay, let me know If you have news.
Thank you.

**Comment by giuspen** [comment]
I see it, thanks for reporting I will come back with a fix shortly

**Comment by DarthtidusX** [comment]
No Problem.
Thank you.

**Comment by giuspen** [comment]
Thanks again for reporting.
I have now added checks and a warning dialog preventing a 'Save As' or 'Export' resulting in the overwrite of the currently open document.
Running 'Save' is the only supported way to update the open document in place.

**Comment by DarthtidusX** [comment]
Oh nice.
Thanks for fixing the issue.
Have a nice weekend.

**Comment by giuspen** [comment]
Have a good weekend ;)
