### ISSUE TITLE
Add up and down keys to table cell navigation

### ISSUE THREAD

**Issue by instancezero** [giuspen/cherrytree#2523]
**Is your feature request related to a problem? Please describe.**
I've been through the key mappings and can't find this, my apologies if I missed something...
The up and down keys let you navigate as expected inside a cell, eventually putting the cursor at the begging or end of the content, but from there subsequent keystrokes get a "invalid" tone. This requires frequent mouse inputs to navigate through the table.
**Describe the solution you'd like**
Up should move to the cell above when the cursor is at the beginning of the cell's content, down should move to the cell below when the cursor is at the end.
Additionally, if there is no row above/below, the cursor should move to the content above/below the table.

**Comment by giuspen** [comment]
Currently the navigation using the four arrows works only in the so called lightweight version of the table (see table property).
In the so called heavy version only Tab and Shift+Tab work to move the focus between cells.

**Comment by instancezero** [comment]
This is a restatement of the problem but I don't see any insight into what might happen in the future. Do you plan to bring this functionality to the "heavyweight" table at some point, or will this functionality be restricted to the "lightweight" version?

**Comment by giuspen** [comment]
What you ask make sense and I would like to support it, I just need to investigate the effort

**Comment by giuspen** [comment]
Please @instancezero try https://www.giuspen.net/software/cherrytree_1.1.2.0+37_win64_portable.7z and report if it works as expected.
If you are on Linux I'll generate an appimage shortly, link will be available at https://www.giuspen.net/cherrytree/#testing

**Comment by instancezero** [comment]
Installed and tested. Works exactly as I'd expect. Thanks!

OT PS: have you considered Liberapay for donations to the project?

**Comment by giuspen** [comment]
Cool thanks for testing @instancezero , it turned out to be simpler than originally thought so I just did it straight away.
I'm not familiar with liberapay, I'll investigate when I'll have some time.
