### ISSUE TITLE
No localization after last update

### ISSUE THREAD

**Issue by gimplyworxs** [giuspen/cherrytree#2529]
**Version, Operating system**
Cherrytree 1.1.3 from PPA
Linux Mint 20.1

There is no localization after yesterday's update.
Language is set to "German" but everything is in "English"

**Comment by giuspen** [comment]
> Language is set to "German" but everything is in "English"

Language is set to German in Linux Mint or in cherrytree preferences?

**Comment by gimplyworxs** [comment]
both

**Comment by giuspen** [comment]
Can you run cherrytree from a terminal and copy/paste the output here?

**Comment by gimplyworxs** [comment]
This is what it outputs:
`~$ cherrytree
** Message: 08:44:27.391: Language overwrite = de (localedir = /usr/share/locale)

(process:4945): Gtk-WARNING **: 08:44:27.419: Locale not supported by C library.
	Using the fallback 'C' locale.
[2024-06-17 08:44:27.450] [che] [debug] /home/hannelore/.config/cherrytree/config.cfg parsed
[2024-06-17 08:44:27.728] [che] [debug] autosave on 5 min
[2024-06-17 08:44:28.473] [che] [debug] Node 197 > Appimage

(cherrytree:4945): Gtk-CRITICAL **: 08:44:28.627: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(cherrytree:4945): Gtk-CRITICAL **: 08:44:28.665: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(cherrytree:4945): Gtk-CRITICAL **: 08:44:28.731: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
`

**Comment by giuspen** [comment]
Can you try to run the AppImage binary file version https://www.giuspen.net/cherrytree/#downl and report if that works / pasting also the output from that?

**Comment by gimplyworxs** [comment]
Doesn't work either :-(.
Output is this:

`./CherryTree-1.1.3-x86_64.AppImage 
** Message: 21:48:08.481: Language overwrite = de (localedir = /tmp/.mount_CherryZFODhw/usr/share/locale)

(process:15583): Gtk-WARNING **: 21:48:08.560: Locale not supported by C library.
	Using the fallback 'C' locale.
[2024-06-17 21:48:08.581] [che] [debug] /home/xxx/.config/cherrytree/config.cfg parsed
[2024-06-17 21:48:08.784] [che] [debug] autosave on 5 min
[2024-06-17 21:48:09.349] [che] [debug] Node 236 > xxx

(AppRun.wrapped:15583): Gtk-CRITICAL **: 21:48:09.444: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(AppRun.wrapped:15583): Gtk-CRITICAL **: 21:48:09.502: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(AppRun.wrapped:15583): Gtk-CRITICAL **: 21:48:09.551: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(AppRun.wrapped:15583): Gtk-CRITICAL **: 21:48:09.578: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
[2024-06-17 21:48:13.161] [che] [debug] shift images in MenuBar/context menu`

**Comment by giuspen** [comment]
Ok I will prepare a test AppImage for you to try in a moment

**Comment by giuspen** [comment]
Can you try https://www.giuspen.net/software/CherryTree-1.1.3+2-x86_64.AppImage ?

**Comment by gimplyworxs** [comment]
That one works!

Output:
`$ ./CherryTree-1.1.3+2-x86_64.AppImage 
** Message: 08:00:42.459: Language overwrite = de (localedir = /tmp/.mount_CherryeXHzK0/usr/share/locale)

(process:2867): Gtk-WARNING **: 08:00:42.583: Locale not supported by C library.
	Using the fallback 'C' locale.
[2024-06-18 08:00:42.622] [che] [debug] /home/xxx/.config/cherrytree/config.cfg parsed
[2024-06-18 08:00:42.945] [che] [debug] autosave on 5 min
[2024-06-18 08:00:43.805] [che] [debug] Node 236 > xxx

(AppRun.wrapped:2867): Gtk-CRITICAL **: 08:00:43.927: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(AppRun.wrapped:2867): Gtk-CRITICAL **: 08:00:43.979: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(AppRun.wrapped:2867): Gtk-CRITICAL **: 08:00:44.029: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(AppRun.wrapped:2867): Gtk-CRITICAL **: 08:00:44.074: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
[2024-06-18 08:00:50.568] [che] [debug] shift images in MenuBar/context menu

`

**Comment by giuspen** [comment]
Thanks @gimplyworxs it's my bad I thought a particular piece of code was not needed anymore but clearly it is required on some Linux systems. This fix will be in v1.1.4 that I plan to release in 1 to 2 weeks

**Comment by gimplyworxs** [comment]
fine, thanks a lot

**Comment by giuspen** [comment]
fixed in upcoming v1.1.4
