### ISSUE TITLE
Setting for navigating the tree (nodes and subnodes) using up and down arrow keys?

### ISSUE THREAD

**Issue by firepainting** [giuspen/cherrytree#2530]
Sorry I couldn't find it.

**Version, Operating system**
CherryTree 1.1.3 
On Linux Mint 21.3 Cinnamon

**Describe the bug**
After clicking on a node/subnode and then pressing up or down arrow keys, the "node highlight" does not move anymore.

**To Reproduce:**
1. Open a CTB file with multiple nodes and/or subnodes, with those sub/nodes populated with stuff, i.e., not empty.
2. Left click on any sub/node on the left.
3. Press up or down arrow keys (on the keyboard).

**Expected Behavior:**
- The sub/node highlight should jump from one sub/node to another.

**Actual Behavior:**
- The sub/node highlight does not move. Instead, the blinking cursor on the body of the sub/node (on the right side) will move up or down.

I don't think this is the default behavior before. 

But in any case I just need to know which setting produces the Expected Behavior above.

Many thanks!

**Comment by giuspen** [comment]
There is an option to automatically put the focus to the text when you click on a node, you have to untick that in the preferences. In alternative if I remember correctly Ctrl+Shift moves the focus to the tree, or try to look under the view menu
