### ISSUE TITLE
Ubuntu 24.04 Not support for any font type bold

### ISSUE THREAD

**Issue by Augusto7743** [giuspen/cherrytree#2533]
Hello.
Thanks for reading my topic.
Ubuntu 24.04 Cherrytree 1.1.2.
Even selecting any font type "bold" the font is rendered as being regular and not bold.
Sans Bold is rendered as being Sans Regular.
That issue not happen in Ubuntu 20.04 or in LibreOffice.

Have an nice day.

**Comment by giuspen** [comment]
Hello Augusto, can you File--Preferences---Export and attach here or send me privately (find email in help--about)

**Comment by giuspen** [comment]
Also which language/alphabet are your notes?

**Comment by giuspen** [comment]
you were right it was a cherrytree issue, fixed now thanks for reporting
