### ISSUE TITLE
Cherrytree Fails to access LaTeX Executable with Invalid LaTeX Input

### ISSUE THREAD

**Issue by Nasko-5** [giuspen/cherrytree#2534]
**Version, Operating system**
Operating system: Windows 10 Pro version 22H2 build 19045.4529
Cherrytree version: 1.1.3

**Describe the bug**
Whenever I input invalid LaTeX into a LatexBlock, Cherrytree fails to access the latex executable and turns the LatexBlock into a warning sign. If any other LatexBlocks are updated, they will turn into warning signs too, regardless of whether they're valid or not.

Whenever you restart Cherrytree, the issue goes away until it runs into invalid LaTeX again

**To Reproduce**
If applicable, attach a non-personal document where the issue can be reproduced systematically.
[test.zip](https://github.com/user-attachments/files/16041328/test.zip) _(uploading it as a zip since .ctb isnt allowed...)_

1. Create a new instance
2. Create a new node
3. Insert a LatexBlock
4. Input invalid LaTeX
5. The LatexBlock turns into a warning sign, opening it up shows the error "Could not access the executable 'latex'"

**Screenshots**

https://github.com/giuspen/cherrytree/assets/66528033/ca5a291d-fc5d-4d0a-81d1-f9021693a45e

**Comment by giuspen** [comment]
thanks for reporting, thisd issue will be fixed in upcoming v1.1.4
