### ISSUE TITLE
Feature Request: Copy & Paste table columns

### ISSUE THREAD

**Issue by MJimitater** [giuspen/cherrytree#2542]
**Is your feature request related to a problem? Please describe.**
At the moment there is an option to cut, copy and paste table rows. But there is no such functionality for columns as far as I can see. 

**Describe the solution you'd like**
3 further options in the right-click table menu to cut, copy and paste table columns.

BTW, CherryTree is a great piece of software and the dedication you pour into it @giuspen is astonishing! Thank you so much!

**Comment by giuspen** [comment]
It would make sense, yes, I'll see if I can squeeze this in after the holidays as it shouldn't take too much effort

**Comment by giuspen** [comment]
This has now been implemented. If you would like a binary to test it please let me know and I will provide it.

**Comment by MJimitater** [comment]
Awesome, thanks for implementing! Makes CT even better :rocket:
