### ISSUE TITLE
Problems with Hyperlinks

### ISSUE THREAD

**Issue by mseliger** [giuspen/cherrytree#2570]
OS: Linux Mint and Windows 10 /11

Hello,
a) when exporting a tree to a single html then the hyperlinks between the nodes of the tree are not working. The program uses the same links as if you exported the tree to multiple files (there the links are working).

b) When creating a link in Cherrytree, Cherrytree is always adding http:// to the link.
E. g. my link for a book in calibre which work under Windows and Linux is:
calibre://show-book/_hex_-4269626c696f7468656b/69070
When I paste the link in the browser it will open the book in Calibre.
When adding a link in Cherrytree the program creates http://calibre://show-book/_hex_-4269626c696f7468656b/69070 - so the link is not working. Is it possible to suppress the http?

Greetings from the Münsterland
Maria

**Comment by gitvectors** [comment]
I do not often use Calibre but it occurs to me that you might use CodeBoxes instead of hyperlinks to launch Calibre pages. The commands are here.

https://manual.calibre-ebook.com/generated/en/cli-index.html

CodeBoxes are often forgotten embedded tools. Choose from multiple syntaxes.

**Comment by giuspen** [comment]
Hallo @mseliger thanks for reporting, point (a) has been fixed for upcoming v1.2.0.
About point (b) it probably makes sense to recognise the pattern `whatever://` and leave it as is. I'll have a think but I'll probably do it.

**Comment by giuspen** [comment]
I'm also no longer prefixing http:// whenever a URL-like prefix is already there, this should solve your problem, let me know if it works for you

**Comment by mseliger** [comment]
Hello giuspen, i've just installed the new version and the hyperlinks works like a charm. Thank you!
Greetings from the Münsterland

**Comment by giuspen** [comment]
Thanks for confirming @mseliger take care
