### ISSUE TITLE
MXLinux 23.4 - Empty Custom Backup Folders

### ISSUE THREAD

**Issue by GoneFishinJax** [giuspen/cherrytree#2577]
**Version, Operating system**
Cherrytree version 1.1.4
System:
  Desktop: Xfce v: 4.18.1 tk: Gtk v: 3.24.36 info: xfce4-panel, plank wm: xfwm v: 4.18.0 vt: 7
    dm: LightDM v: 1.26.0 Distro: MX-23.4_x64 Libretto January 21  2024 base: Debian GNU/Linux 12
    (bookworm)
  Kernel: 6.1.0-25-amd64 [6.1.106-3] arch: x86_64 bits: 64 compiler: gcc v: 12.2.0
    parameters: BOOT_IMAGE=/boot/vmlinuz-6.1.0-25-amd64 root=UUID=<filter> ro quiet splash
    init=/lib/systemd/systemd

**Describe the bug**
I created a custom backup folder location for all my CT backups through GUI and verified it in config.cfg file:

backup_copy=true
backup_num=3
autosave_on_quit=true
enable_custom_backup_dir=true
custom_backup_dir=/home/cybert/Documents/App_files/Cherrytree/Backups

Each CT instance has created a directory in the /Backups folder consisting of the _full_path_filename.extension.  All of these folders are empty. 
 _home_cybert_Documents_App_files_Cherrytree_Recipies_Recipies.ctd

If I try to import the CT directory I get a "The Tree is Empty!" error.

**To Reproduce**
The same thing happens on a different laptop running the same MXLinux 23.4  

**Screenshots**
![image](https://github.com/user-attachments/assets/a1281f4e-9119-4460-9886-f750e9852a7f)

**Comment by GoneFishinJax** [comment]
Problem resolved: backup files are hidden in the directory.  Having recently moved from the Win environment, I forget about the hidden files.  Discovered during an SSH session

─[11:51:45 am]─[.../_home_cybert_Documents_App_files_Cherrytree_Recipies_Recipies.ctd]
$ ls -la
total 1340
drwxrwxrwx  2 cybert cybert   4096 Oct  3 08:52 .
drwxrwxrwx 14 cybert cybert   4096 Sep 28 14:18 ..
-rw-r--r--  1 cybert cybert 451438 Oct  3 08:50 .Recipies.ctd~
-rw-r--r--  1 cybert cybert 451437 Sep 20 12:56 .Recipies.ctd~~
-rw-r--r--  1 cybert cybert 451451 Sep 20 12:55 .Recipies.ctd~~~

**Comment by giuspen** [comment]
I was about to write that, I'm glad you sorted out :)
