### ISSUE TITLE
Code Box Font changes back to text font

### ISSUE THREAD

**Issue by murdock72** [giuspen/cherrytree#258]
Version 0.38.0:

Code Box font have to be a "fixed width" font such as Consolas for my requirements.

This font is set as follows, but newly created code boxes does not allow this font to be applied:
Edit > Preferences > FontsTab > Code Font > Consolas
When the chosen font is selected, it changes. 
Navigating to another node and back again changes the font from what it was set to. 
CodeBox font is also not set according to Preferences.

**Comment by giuspen** [comment]
Click help--open preferences directory and you should see a file config.cfg there verify you have write access

**Comment by murdock72** [comment]
Hi, 
I am using Windows 7. The config.cfg file has full permissions.
The font section of the file is indeed corresponding to that of the application:
`[fonts]
text_font = Sans 9
tree_font = Sans 8
code_font = Consolas 9`
Everytime CherryTree is closed the Date/Time stamp of the file changes - tells me it is writable.

**Comment by murdock72** [comment]
The Config File:
[config.txt](https://github.com/giuspen/cherrytree/files/1074248/config.txt)

**Comment by giuspen** [comment]
Problem also found by http://www.giuspen.com/topic/rtf-font-overrides-code-box-font/ - I'll try to reproduce and propose a development version for you to test

**Comment by txe** [comment]
Fixed
