### ISSUE TITLE
(minor) Double-clicking word selection changed from last version: the underscore is now a word separator.

### ISSUE THREAD

**Issue by dbwiz** [giuspen/cherrytree#2581]
**Version, Operating system**
1.2.0,  Windows 10, install, no-latex. CTB

**Describe the bug**
Double-clicking a string with an underscore now selects only part of the string.  It changed from 1.1.4

**To Reproduce**
If applicable, attach a non-personal document where the issue can be reproduced systematically.
1. Enter "Test_Word" on a node
2. Double-click on "Test" and only "Test" is selected.

**Note**
I use a timestamps as search keys in other systems (I bold them to mean that).   So I'll CTRL+ALT+M to get the timestamp, _double-click it to select the whole thing_, click CTRL+B to bold it and CTRL+C to copy.  Then I paste it in the other system.  Later when I want to go to that place in the other system from my notes, _I double-click the bolded timestamp to select it all_, copy it, flip to the other system and paste in "find all".  That works well, and I use it a lot.   To do this I had to change the default timestamp format as the default doesn't allow that.  I changed the format to be like this:  2024-10-08_1830

Unfortunately, 1.2.0 sets the "_" as a word separator, so double-clicking it now only selects half the timestamp.  

Workaround: I've changed the timestamp format to 2024-10-08-1830 to continue doing this, though in my mind it doesn't look right.

If it doesn't cause any other problems or such, would you please set the underscore back to *not* a word-separator?  Otherwise I can continue with the workaround.

Thank you kindly as always for this indispensable software!

**Comment by giuspen** [comment]
You're right, it wasn't intentional, it is a bug, but there is a quick way for you to solve this.
Look into the preferences dialog, first tab "Text and code", and at the bottom, "Chars to Select at Double Click".
The default is ".-@", I'm going to change it to ".-@_" but in the meantime you can add the underscore yourself, that will do.

![image](https://github.com/user-attachments/assets/498d48e9-9ebd-437f-b344-2c3b91d22cd4)

**Comment by dbwiz** [comment]
I keep thinking I know all the features of CT now I've been using it daily for more than a decade but no, I am still a student.  Thank you kindly!   I've made the change and closed the issue.
