### ISSUE TITLE
Feature Request:  A way to cancel or prevent pasting of long text in a node (minor)

### ISSUE THREAD

**Issue by dbwiz** [giuspen/cherrytree#2582]
**Is your feature request related to a problem? Please describe.**
The current versions of CT with CTB have been very stable, and literally the only time it crashes on me nowadays (and I'm in here 40+hrs/week with a half gig notebook) is when I've had to kill a session myself from accidentally pasting a lot of text.   It's slow, and it's not that it won't finish, it's just that I don't have hours to wait.   It usually happens when I wanted to just paste in a few rows but ended up pasting in the whole result of a query.  So when it happens, after checking for what I'd lose by the file time, I'd kill it and start again.

**Describe the solution you'd like**
I would like  (1) a cancel button for paste if it takes more than 20 seconds, optionally with (2) a progress bar for the paste , or (3) simply a popup warning about text length >10k characters where I could back out of the paste.   This would apply to codeboxes as well as nodes.  I wouldn't necessarily want the thing to paste quicker, there aren't really circumstances where I want all that (although I use plain text boxes sometimes for that, kind of like folding the results inline).  

Thank you!

**Comment by gitvectors** [comment]
From another user. 
I follow the approach of multiple CT books rather than using massive notebooks. But if that is your preference - all eggs in one basket - have you considered parsing the (*.ctd not *.ctb) notebook as an XML doc. Or even concatenating chunks?
And instead of *.ctb use a noSQL database such as eXistdb? Just different ways of managing notes.
https://docs.python.org/3/library/xml.etree.elementtree.html

**Comment by dbwiz** [comment]
@gitvectors   Hi, no, I just like using it as a notebook, like a lab notebook.  I've read you can do things like this, I would not want to it myself.  CT has been very reliable for me since before 1.0 and that is the key feature in my use.  And that the notebook is local and won't disappear by some remote policy decision.  I've been using it for more than a decade.  This request is a minor issue as I'm slowly learning to catch myself before pasting and might close it once I've do.

**Comment by gitvectors** [comment]
So a compromise might be to have a scratchpad notebook solely for pasting new content. Then your main notebook could import from the scratchpad when paste is completed. This would allow the sctatchpad process to be killed without impacting on your main sole notebook.

**Comment by innvader** [comment]
use ctrl shift v to paste it as plain text instead. pasting 1 million lines works in that fashion in a few seconds.

**Comment by dbwiz** [comment]
Thanks, I just tested that on a 1 MB paste.  (1) Plain text page - a second or so (2) Rich text page (what I'm interested in ) - a second or so.  (3) regular paste -> lockup and kill the session.   

I didn't notice the difference in times between the pastes until now.  I use CTRL+SHIFT+V sometimes, I can remember to use it all the time for text pastes I think.  Paste text as plain text. 

Thank you for pointing that out, I'll accept it as the answer.
