### ISSUE TITLE
Version 1.2.0 for Ubuntu 18.04 failed to build

### ISSUE THREAD

**Issue by NouGithub** [giuspen/cherrytree#2583]
Hi!

v1.2.0 isn't coming down to 18.04, please see: https://launchpad.net/~giuspen/+archive/ubuntu/ppa/+packages

Many thanks!

**Comment by giuspen** [comment]
You're right but 18.04 is end of life so wasn't sure it was worth supporting it. Are you planning in continuing to use for years or you will upgrade soon?

**Comment by NouGithub** [comment]
Thank you for your speedy reply. For various reasons, I will be using 18.04 for at least a few more years. If it would be possible to continue your support of it, that would be much appreciated!

**Comment by giuspen** [comment]
OK it is building now the PPA package for 18.04

**Comment by NouGithub** [comment]
That was very kind of you to do.  Many thanks!
