### ISSUE TITLE
Internal links get messed up when importing nodes from CherryTree file

### ISSUE THREAD

**Issue by bakbuk** [giuspen/cherrytree#262]
I had to unite a few ctb's into a single one. I did this by creating a new ctb and then Tree --> Nodes Import --> From CherryTree File, for each of the ctb's. I noticed internal links are messed up: they're clickable, but take me to completely wrong nodes. 

I'm using CherryTree 0.38.0.

In the meanwhile does anyone have any suggestion how to unite a bunch of ctb's into a single one while avoiding this issue?

**Comment by giuspen** [comment]
annoying indeed I'll try and fix in the next days and ask you to verify the fix

**Comment by bakbuk** [comment]
Thanks so much, highly appreciated!

**Comment by anmej** [comment]
I think it's the same problem as this:
https://github.com/giuspen/cherrytree/issues/70

**Comment by giuspen** [comment]
Please test the build 0.38.1+4:
http://www.giuspen.com/software/cherrytree_0.38.1+4_setup.exe
http://www.giuspen.com/software/cherrytree_0.38.1+4_win32_portable.7z
http://www.giuspen.com/software/cherrytree_0.38.1+4-1_all.deb

**Comment by bakbuk** [comment]
Thanks for the fix. I just tested it now by uniting some pretty big ctbs with many internal links in them, and everything's working properly.

Thank you @giuspen for this really great piece of software!
