### ISSUE TITLE
Feature request: left arrow key to affect the tree

### ISSUE THREAD

**Issue by bakbuk** [giuspen/cherrytree#264]
It would be nice if the left arrow key on the keyboard would do what it usually does in similar tree interfaces: fold the current tree section and take you to the parent node. Currently the left arrow key only folds when you're on the parent node itself.

**Comment by giuspen** [comment]
I agree on the "take you to the parent node" that is missing now, not sure about folding at the same time... the cinnamon desktop file manage for instance doesn't fold and just takes you to the parent node

**Comment by bakbuk** [comment]
Yes, that seems correct to me. If one wants to indeed fold the node as well, then another key press would do that, per the way it already works right now.

**Comment by giuspen** [comment]
The commit https://github.com/giuspen/cherrytree/commit/2740f8c39330a2eda8dea0fad143ea7196cc5077 should solve this issue, could you test it? I can package if you need

**Comment by bakbuk** [comment]
I'm not sure how to get started with trying to get it running from the code - could you help me with that please?

**Comment by giuspen** [comment]
I will make a package once I fix the other problem you notified so you can try both, what operative system are you on?

**Comment by bakbuk** [comment]
Windows 7

**Comment by bakbuk** [comment]
Looks great, thanks!
