### ISSUE TITLE
Feature request: a hotkey to collapse the tree

### ISSUE THREAD

**Issue by bakbuk** [giuspen/cherrytree#268]
I feel that a hotkey which collapses all the nodes in the entire tree would be very useful to me.

**Comment by giuspen** [comment]
You can define keyboard shortcuts for many actions in the preferences dialog and this should also be available, can you check?

**Comment by bakbuk** [comment]
Oh that's great, I hadn't realized. It even had a hotkey already defined for it. Thanks!
