### ISSUE TITLE
Search is very very slow when 2000 subnodes/nodes with text has been added

### ISSUE THREAD

**Issue by prog20901** [giuspen/cherrytree#272]
Hi,

When 2000 subnodes/nodes has been added with assume 100 kb of text in each node. 

The search seems to be very very slow. The performance needs to be addressed.

Thanks.

**Comment by leggewie** [comment]
and you should read through the bug tracker before reporting a duplicate to issue 269

**Comment by jkathir** [comment]
@giuspen @leggewie  Is porting to c++ / gtkmm3 has been done ? Do you have any updates on this issue?

**Comment by giuspen** [comment]
Porting to C++ in progress but cannot forecast when first version available due to extremely busy family life these days

**Comment by jkathir** [comment]
Do you have updates on Porting to C++ ?

**Comment by giuspen** [comment]
I'm working on it daily in the early morning for about an hour, so it is progressing, still cannot forecast the completion, too early for that

**Comment by siliconninja** [comment]
Thank you for your hard work!

**Comment by jkathir** [comment]
Thank you for your hard work !!!!

**Comment by prog20901** [comment]
Is porting to C++ has been completed? Is the slowness has been fixed in the recent release?

**Comment by giuspen** [comment]
The porting to C++ of the search has been implemented by @txe and it is, as expected, way faster than the python search. The porting of the whole app is not complete though; I should be able to complete it before the end of the year

**Comment by prog20901** [comment]
Is porting to c++ is completed?

**Comment by giuspen** [comment]
End 2019 start 2020 the first public version should be ready.

**Comment by samuelkathiresan** [comment]
@giuspen is the porting has been completed in the new version?

**Comment by giuspen** [comment]
@samuelkathiresan the porting is not complete but thanks to the hard work of @txe it is not too far from completion

**Comment by javadevelopment4** [comment]
is porting has been done with the latest version?

**Comment by javadevelopment4** [comment]
is the slowness has been fixed in the recent version ?

**Comment by giuspen** [comment]
Please @javadevelopment4 try the latest development version 0.99.4 scroll below in the download section after current stable 0.39.4

**Comment by javadevelopment4** [comment]
Tested the issue in latest version but found the search is very slow.

Thanks

**Comment by giuspen** [comment]
I improved significantly the speed of the search/replace with the option 'all matches' (default), this will be available in the next version 1.0.2 or 1.1.0.
