### ISSUE TITLE
HTML-export IOError: [Errno 36] filename too long

### ISSUE THREAD

**Issue by sm8ps** [giuspen/cherrytree#276]
When I export a medium-size Cherrytree notebook, hierarchical nodes are concatenated which results in filenames longer than the 255 characters that Ext4 supports. For instance, I have
`  File "/usr/share/cherrytree/modules/exports.py", line 706, in node_export_to_html
    file_descriptor = open(node_html_filepath, 'w')`
`IOError: [Errno 36] Der Dateiname ist zu lang: u'/home/stefan/tmp/ct-test/oku5.ctb_HTML/nterhof5--okunterhof5.1--server_software--lxc--5_nginx-proxy--https--ssl-zertifikat_erneuert--SSL_hardening--1.5_Certificate_Signature_Algorithms.html'
`
Since this is a fundamental issue with any file system that has a fixed-length limitation on filenames, I would suggest stacking the hierarchy by use of folders rather than by the text separator (`--`). That way, the structure of the notebook would be even better reflected in the HTML-export. What do others think?
Cheers!
sm
PS: Thanks for this excellent piece of software!

**Comment by sm8ps** [comment]
I dove into the code and found that such an error should in principle not happen. Indeed in 'modules.py' the function 'get_html_filename()' limits the filename to its last 150 characters. This is indeed true for the example stated above: `nterhof5--okunterhof5.1--server_software--lxc--5_nginx-proxy--https--ssl-zertifikat_erneuert--SSL_hardening--1.5_Certificate_Signature_Algorithms.html` consists of exactly 150 characters.
When I issue `touch nterhof5--okunterhof5.1--server_software--lxc--5_nginx-proxy--https--ssl-zertifikat_erneuert--SSL_hardening--1.5_Certificate_Signature_Algorithms.html`, I get the above error. This is on Ubuntu 16.04 and a Ext4 filesystem.
Did some research and found the following discussion on [StackOverflow](https://stackoverflow.com/questions/14886640/ubuntu-encrypted-home-directory-errno-36-file-name-too-long). It is mentioned that eCryptfs (like encrypted home on Ubuntu) has a 143 character size limit on the filesize. This is explained in a [Launchpad bug](https://bugs.launchpad.net/ecryptfs/+bug/344878). Thus this bug affects anyone exporting HTML to an eCryptfs which is common on Ubuntu.
The simple fix is to set `MAX_FILE_NAME_LEN = 143` in 'cons.py'. The test case works fine with it.
@giuspen: Would you please consider including this in the next release? I do not see the need for a formal pull request given that I am not very well acquainted with this kind of procedures.
Cheers!
sm

**Comment by giuspen** [comment]
@sm8ps OK

**Comment by sm8ps** [comment]
Thanks @giuspen! The production of the HTML-export to an EcryptFS does work now locally.
However, the case does not seem fully resolved yet. Indeed, when I try to sync the files via OwnCloud to a Ubuntu Server with a regular ext4-filesystem, then OwnCloud produces a "filename too long"-error. I have not been able to fully localize the issue; it could be PHP-related or something else. For the moment, I do not know where to search for the cause but I shall report back with a new ticket once I have more information.
Cheers!
sm
