### ISSUE TITLE
HTML-export IOError: "filename too long" revisited

### ISSUE THREAD

**Issue by sm8ps** [giuspen/cherrytree#285]
This is an addition to #276 where I mentioned in my last comment that things do net seem fully correct even after setting `MAX_FILE_NAME_LEN = 143`. I have had a few cases where filenames still were too long. Curiously the error only showed after the files were uploaded to an Owncloud server.

I have come to suspect that the issue is related to strings being zero-terminated. I must admit that I am not fully sure about the circumstances but my experience shows that the faulty exports did not occur anymore after setting `MAX_FILE_NAME_LEN = 142`. So I suggest lowering that value again.

**Comment by giuspen** [comment]
OK
