### ISSUE TITLE
[BUG] Unable to resize tables on latest release with ctrl+Scroll

### ISSUE THREAD

**Issue by AntiNSA** [giuspen/cherrytree#292]
Hi, I am using gnome/17.10 and on the latest version I am unable to resize the tables with the rest of the pages, Before you could resize/zoom tables  with scroll , click on another node, then return to zoomed node, and you could see the zoomed table. Now no longer......

SO I am unable to zoom tables. This is a big issue.

**Comment by giuspen** [comment]
Hi, the zoom in tables was never really supported, it was just sharing the rich text font so if you zoomed the rich text font you had that functionality changing node and coming back. Anyway it should zoom properly now, can you try the latest git version?

**Comment by AntiNSA** [comment]
Can you give me a .deb link or the code I need to clone your git and make it work ? Sorry I am not that savy to know how to do that with out a tutorial.

**Comment by giuspen** [comment]
http://www.giuspen.com/software/cherrytree_0.38.3+3-0_all.deb

**Comment by AntiNSA** [comment]
OK, after using the version you provided I can no longer increase/decrease any text....I use cherry tree to teach in class and really need to increase and decrease text..... please..... help me get this working again its a huge feature.

**Comment by giuspen** [comment]
Sure I'll have a look shortly , in the meanwhile you can reinstall the older version

**Comment by giuspen** [comment]
Please try http://www.giuspen.com/software/cherrytree_0.38.3+5-0_all.deb

**Comment by txe** [comment]
Fixed
