### ISSUE TITLE
Feature Request: Carriage Return in table cell

### ISSUE THREAD

**Issue by bitboy85** [giuspen/cherrytree#295]
by now it seems that it is not possible to use a carriage return within table cells.

**Comment by giuspen** [comment]
You right click there is a menu item for that...

**Comment by bitboy85** [comment]
in the context menu is a Point thats called "insert row" "Zeile einfügen" in german. But if i click nothing happens. Version is 0.38.1. If it is the correct one the Translation should be "Zeilenumbruch einfügen"

**Comment by giuspen** [comment]
No it is `Insert NewLine      Ctrl+.` Note you have to be in table cell edit mode, like when typing text enters text in the table cell. When a table row is selected click again on a cell, you should see the cursor blinking, then right click

**Comment by bitboy85** [comment]
Tried again and ist working now. Thanks for your time :)
