### ISSUE TITLE
Some strange issues

### ISSUE THREAD

**Issue by MercuryOoO** [giuspen/cherrytree#297]
https://github.com/giuspen/cherrytree/blob/26dc7141c2b0ba32c66f588a6f15dc00f722621d/modules/printing.py#L62

**Strange issue 1** 

- set_export_filename "2017--十一月--10_周五" causing cherrytree complain _"Error printing file:
error while writing to output stream (exception catched)"_

- set_export_filename "十一月--10_周五" complaining

- set_export_filename "月--10_周五" complaining still

- set_export_filename "--10_周五" **OK!**

**Strange issue 2**

When the exported PDF file name contains Chinese, the resulting file name is garbled.

**Comment by txe** [comment]
it was fixed for windows
