### ISSUE TITLE
Tabbing Between Table Cells

### ISSUE THREAD

**Issue by AlanCW** [giuspen/cherrytree#298]
Hi,

Tabbing between table cells does not work. Moreover, tabbing more than twice causes the entire table to disappear.

OS: Linux Mint 17.

**Comment by giuspen** [comment]
You can tab between table cells pressing Enter. At the moment I don't remember if in the past it was working, anyway I'll have a look and see if I can make it work.

**Comment by giuspen** [comment]
I confirm the Tab has never been working, but the Enter and the up and down arrows do work to switch between table cells.

**Comment by AlanCW** [comment]
Very good, Thank you Giusepppe.

And thank you for your effort in building one of the best and most 
useful apps for the Linux platform.
