### ISSUE TITLE
[Feature] Portable version for linux with config file in same folder

### ISSUE THREAD

**Issue by ghost** [giuspen/cherrytree#300]
I believe the portable version for linux is already the .tar.gz.
You can run ./cherrytree and it will run without installation from the very same folder, however the config.cfg file gets created in $HOME/.config/cherrytree/.  Unless I missed something and if the config.cfg is the only file that needs to be moved to make cherrytree portable, is it possible you can add an option in preferences or something where we can tick box to make portable which will move config.cfg inside a folder called Configs in cherrytree folder ?

**Comment by giuspen** [comment]
If you place the config.cfg beside the file "cherrytree" (cherrytree.exe for the windows version) that makes it portable. Sure a tick box would make it easier

**Comment by 2SI3NX** [comment]
oh nice, so cherrytree first checks if the config.cfg file exists in same folder as cherrytree and if not, checks $HOME/.config/cherrytree/?  I just tested this, works. thank you!
