### ISSUE TITLE
Copied text is deleted from the clipboard when the program is closed.

### ISSUE THREAD

**Issue by Faust30000** [giuspen/cherrytree#303]
If you copy any text from the program from the close it, the text disappears from the clipboard.
OS: Linux Mint

**Comment by txe** [comment]
CherryTree can do nothing about it, it's the issue with X1. But there is a work a round, read [here](https://unix.stackexchange.com/questions/450508/how-to-keep-clipboard-content-from-xterm-after-closing-it-like-firefox-or-le)
