### ISSUE TITLE
Menu Bar Titles gone

### ISSUE THREAD

**Issue by pxcask** [giuspen/cherrytree#325]
In my instance of Cherrytree, the menu bar titles disappeared, except "File". Even though there is no title, I can open the menus by clicking in the menu bar.
![image](https://user-images.githubusercontent.com/34713427/34208699-b809f2f6-e58f-11e7-812c-72b8d50804ab.png)

**Comment by giuspen** [comment]
What is your operative system?

**Comment by pxcask** [comment]
It's Linux Mint 18.3 Cinnamon 64 bit.
