### ISSUE TITLE
problem keeping the database in synched folder on Google Drive

### ISSUE THREAD

**Issue by shentho** [giuspen/cherrytree#329]
I like the program it is great, I was hoping to synch the databases over a number of devices, at work and at home. I thought of placing the database in a synched folder however every time I make a change the program creates a temp file, which is then synched, so I end up with a database called Home.cdt and a 
Home.cdt~, Home.cdt~~,Home.cdt~~~ etc..
please could you figure a solution to this.
![image](https://user-images.githubusercontent.com/23171315/34579851-50f8de7a-f150-11e7-9ad9-72ff689dddb9.png)

Thanks again

shentho

**Comment by giuspen** [comment]
You can disable the backup copies from the preferences dialog (default is 3, change to 0)

**Comment by shentho** [comment]
Wonderful It worked !!
Sorry for the hassle, Newbie

**Comment by sophware** [comment]
Do you end up having to make sure you're not using the database from two computers at once?

**Comment by giuspen** [comment]
@sophware yes, currently collaborative editing is not supported

**Comment by pubmedsurveys** [comment]
hi @giuspen your program is awesome but i have a little problem using in Google Drive : when i open it directly from a Google Drive folder ( W10 ) it opens 'void' but if i copy the same file to my desktop folder all the information is showed. Do you know what is happens?

**Comment by giuspen** [comment]
Something in the path is not decoded properly, maybe try to use a link to the Google drive location

**Comment by txe** [comment]
Closing, the original issue also can be resolved by Custom Backup Directory.
