### ISSUE TITLE
BUG：sqlite3.OperationalError: table node has 13 columns but 11 values were supplied

### ISSUE THREAD

**Issue by kubow** [giuspen/cherrytree#331]
Happens on portable version 0.37.2 running on windows 10 - using *.ctb files.
I believe it has something to do with reordering and changing name of nodes.

It usually puts this kind of message:
Traceback (most recent call last):
  File "core.pyc", line 1523, in file_save
  File "core.pyc", line 1670, in file_write
  File "core.pyc", line 1571, in file_write_low_level
  File "ctdb.pyc", line 60, in pending_data_write
  File "ctdb.pyc", line 354, in write_db_node
sqlite3.OperationalError: table node has 13 columns but 11 values were supplied

Only workaround is to re-save the whole .ctb file

**Comment by giuspen** [comment]
If you save with the latest major version, then using the document with older major versions can lead to issues, is this the case?

**Comment by kubow** [comment]
Well, I am also using cherrytree on linux in more recent version (keep updated), so this could be the case.
My concept is to use files in DropBox and open them both on Windows and Linux (wish It could be also Android and IOS 👍 ).
However saving is good in approx. 90% of the cases and happens only in special cases like reordering a node, promoting a node to root level or renaming a node.

**Comment by giuspen** [comment]
You should upgrade the windows version also to latest 0.38.x and generally always run the latest stable to have all the bugfixes
