### ISSUE TITLE
Checkbox in other fonts 

### ISSUE THREAD

**Issue by sanousy** [giuspen/cherrytree#339]
First of all, thank you for the great effort and ideas combined together to make it simple and creative cherrytree :)

When I change the font I lose the feature of checkbox beside tasks which sticks me to a single font. :\

**Comment by StarWeaver** [comment]
I'm getting this with a lot of fonts I'd like to use. Could we get a config option for the checkboxes like with the chars_listbul and chars_toc?

**Comment by StarWeaver** [comment]
Sorry, we're (well, I'm) talking about the checkboxes that appear as the bullets in todo-type lists.

These things:

![Example](https://i.imgur.com/ka9XFfx.png)

In most fonts they look more like:

![Bad example](https://i.imgur.com/WZITiYo.png)

So I was suggesting a config file variable to change the characters used like you have for list and table of contents bullets already.

**Comment by giuspen** [comment]
Should be ok (configurable in config.cfg) but the old characters are not automatically replaced. Can you test the latest from git master?
