### ISSUE TITLE
Why not support macos?

### ISSUE THREAD

**Issue by peiwenjian** [giuspen/cherrytree#340]
I used this software on Windows, and now I use macos but the software is not very friendly to macos. How can I use it on macos?

**Comment by northdpole** [comment]
It's very easy to install on osx.
If you have homebrew you run the following:

 brew install pygtk
 brew install gtksourceview gtksourceview3 pygtksourceview

Then python cherrytree launches the application

Now we only need to set it up for homebrew as a package

**Comment by gagarine** [comment]
homebrew package is a good first step, but the command line is not an option for most user.

**Comment by gagarine** [comment]
#176
