### ISSUE TITLE
Releasing as Flatpak

### ISSUE THREAD

**Issue by tliron** [giuspen/cherrytree#346]
I'm hoping the developer would be so kind as to publish on Flathub.
It's very easy to do using Flathub's CI, integrated with GitHub:
https://github.com/flathub/flathub/wiki/App-Submission

**Comment by giuspen** [comment]
Problem is not kindness, problem is time these days, if it won't take too long I'll look at that

**Comment by kurobeats** [comment]
I don't know if it'll help, but here's the run down they provide:
https://docs.flatpak.org/en/latest/first-build.html

Then submitting to flathub.org:
https://github.com/flathub/flathub/wiki/App-Submission#how-to-submit-an-app

**Comment by rszibele** [comment]
I have packaged CherryTree as a Flatpak, which can be found [on GitLab](https://gitlab.com/rszibele/flatpak-cherrytree). You could use it as a starting point or copy it verbatim. For anyone finding this issue  by searching, I don't provide any end-user support for the Flatpak build manifest or the supplied bundles, as I have created it for my personal use.

There are however a few things that would probably have to be looked into or modified within the manifest to create a great CherryTree experience suitable for [Flathub](https://flathub.org):

* proper desktop theme integration (I don't know if it's possible with Gtk+2 and I'm not interested in figuring that out)
* --filesystem=host isn't needed as far as I can see, but one would have to make it work with the file dialog portal for the Flatpak sandbox
* there are files that are included in the Flatpak that could possibly be removed (e.g. p7zip's binaries), so the final Flatpak file size could be optimized even further
* proper QA will have to be done to find what works or doesn't work (i.e. less used features that I may not be using)

Other than those required tweaks for a Flathub release, the Flatpak itself works great.

**Comment by kurobeats** [comment]
I'll see if I can get it on Flathub, thanks @rszibele

**Comment by tliron** [comment]
Cherrytree is no longer packaged for Fedora 31. :( This has to do with them deprecating various Python 2 packages. So, I think getting on Flathub is now more urgent!

**Comment by giuspen** [comment]
For fedora 31 issue see also https://github.com/giuspen/cherrytree/issues/581 - I do need to focus on the porting to gtkmm3 that indeed is super urgent, first release should be ready in a couple of months

**Comment by moonburnt** [comment]
interested in flatpak version too, since arch linux (and its derivatives) has purged cherrytree from repos due to stale dependencies (and aur version has python2 dependencies that conflict with python3 packages. So Im basically stuck with cherrytree 0.38.8)

**Comment by giuspen** [comment]
https://flathub.org/apps/details/com.giuspen.cherrytree
