### ISSUE TITLE
Feature request: Change default heading color

### ISSUE THREAD

**Issue by aasami** [giuspen/cherrytree#349]
It would by really good to have different colors for heading1 heading2 and heading3.
And if it is user configurable, that would be awesome!

**Comment by muhlinux** [comment]
Adding to this, it would indeed by nice having the option to configure how new heading are created.
For example, I would like the h1 property  to be underlined be default. And to control what font and size is used.

**Comment by wolfbyte** [comment]
I think it would be cool for this too. I would prefer to be able to edit a stylesheet or something to that effect for the document.

**Comment by 1637664504** [comment]
I also want to know , change default h1 h2 h3 stylesheet.

**Comment by Guigz25** [comment]
Any news on this enhanced feature ?

**Comment by giuspen** [comment]
I'm going to implement something supporting this but there are other issues with higher priority first

**Comment by aasami** [comment]
> I'm going to implement something supporting this but there are other issues with higher priority first

Like exporting to Evernote, Joplin, Zim, ... ? I'd love to move to other note taking app now. But, cherrytree is a walled garden. Easy to get in with ton of import features but no usefull export tool. :-(

**Comment by giuspen** [comment]
The export to HTML is quite complete and standard, you should be able to import that into your future note taking app

**Comment by giuspen** [comment]
This will be in upcoming 0.99.34. Three new headings h4,h5,h6 have been added and all the headings plus the 'small' can be customised in several properties.

**Comment by cdarsac** [comment]
Hello,

I use the 0.99.45 CherryTree version.

Is it possible to customised headings h1, h2 and h3 ?
