### ISSUE TITLE
superscript and subscript tags are not recognized when copied from an external source

### ISSUE THREAD

**Issue by ycnmhd** [giuspen/cherrytree#355]
**Description:**
I'm working on a java clipboard companion that formats copied-text from a PDF textbook on the fly.

the companion gets the data from clipboard, performs formatting and highlighting using HTML tags, and then passes the data to the clipboard as an "text/html" transferable object

all the tags I’ve tested so far work, except for the superscript and subscript tags <sup> and <sub>

superscripts/subscripts are also not recognized when copied from websites using a regular web browser (tested chrome and edge)

**Reproduce:**
using a web browser, open a webpage that has superscrpt text
select and copy the text
paste into cherrytree

here is a sample html file that was generated by the companion
(sorry I couldn't upload it as an .html file, please rename the extension)
[sample.txt](https://github.com/giuspen/cherrytree/files/1865425/sample.txt)

**System info:**
Windows 10 Pro 64bit
Cherry Tree 0.38.4

**keywords:**
 clipboard, html, superscript

**Comment by giuspen** [comment]
Hi, can you add one or two links to html pages with superscript and subscript that fail to be pasted properly so that I can test on that?

**Comment by ycnmhd** [comment]
Hi, thanks for your time
sorry but I couldn't find a website on the spot.
you can reproduce the issue by exporting a cherry tree node to HTML, opening the HTML file with a web browser, and copying the text from it to cherry tree

follow up: I wrote a small java program(no gui) that prints all the data flavors contained in the clipboard (HTML, text...)
(source and compiled jar) [cpb.zip](https://github.com/giuspen/cherrytree/files/1866679/cpb.zip)

a copied text from cherrytree uses tags like 'strong', 'em' and 'sup' for bold, italic and superscript respectively, while chrome (and the clipboard companion I’m working on) produces 'b', 'i' and 'sup'
[cherrytree.txt](https://github.com/giuspen/cherrytree/files/1866676/cherrytree.txt)
[javaprogram.txt](https://github.com/giuspen/cherrytree/files/1866677/javaprogram.txt)

I tried to generate html metadata using same tags as cherrytree, but none of them worked (the text was pasted as plain text)
