### ISSUE TITLE
Remember position of last time you visited a node

### ISSUE THREAD

**Issue by alfredoivan** [giuspen/cherrytree#36]
Suppose you are in node "A" , you scroll across the content and you are now in the middle of the page.

Then you exit program.
Then you execute it again, you start up in the same node but not in the same "scrolling" position.

**Comment by giuspen** [comment]
Thank you for the notification I'll reproduce and try to fix

**Comment by giuspen** [comment]
Actually CherryTree restores the position of the cursor and then scrolls to the cursor.
If you click anywhere in the text after the scroll, CherryTree will restore the scrolling position.
Do you think this is an acceptable behaviour or you think this should be changed?

**Comment by alfredoivan** [comment]
My program behaviour is different. Suppose i am on node A on the middle of it writing. Then I close the program, then i open it up again.

After doing so, i am again in node A but the cursor is in the very beginning of the node. Not at the middle as i would expect it to be.
(i'm using CherryTree 0.35.2)

**Comment by giuspen** [comment]
I can see something is not working properly in restoring the cursor
position and consequently the scrollbar, I will fix this soon

**Comment by alfredoivan** [comment]
thanks for your quick replies, anyway it is only a minor bug.
Greetings,

**Comment by txe** [comment]
Couldn't repeat on 0.38.11
