### ISSUE TITLE
Screenshot ability like Windows' Snipping Tool

### ISSUE THREAD

**Issue by DustVoice** [giuspen/cherrytree#362]
I would really love to have a direct Screenshot feature for CherryTree, because the workaround consisting of taking a screenshot, saving it, cutting it out and inserting it in a document, is pretty yank. I have used the Windows Snipping Tool like feature in another project of mine before and it isn't that hard to implement. Could maybe someone point me in the right direction as to where the image data is processed right now? For example when you click on add image? That way I could easily check if it would require a lot of work. Probably not though. As far as I can tell it wouldn't even require additional libraries... Anyways, huge thanks for this awesome piece of software! I can't live without it anymore. I use it to store all the difficult and exceptional IT-Support knowledge I gathered over the years and I use it almost every day for my clients. I also can't think of a single person I haven't recommended this incredible piece of software to. Keep up the great work and a huge amount of love from me. Just thank you for your effort!

**Comment by DustVoice** [comment]
Ok so I have successfully implemented taking a screenshot from a borderless window, which you can resize nevertheless, by ONLY using gtk and pixbuf (currently the file is saved in the main directory). It can be used as a standalone class to call from the main code. The only thing I haven't figured out yet is as to where the pixbuf is normally processed in the application. So for example if I click on "add image" then a file chooser is opened and the image gets inserted into the document. If I could figure out where this gets done, I could implement an add screenshot button where you can select a custom screen portion and press enter to take the screenshot and insert it into the document as an image. If someone could help me with this, supposedly someone who is familiar with the code, I would be really grateful, because I don't have that much freetime. But I will try.

**Comment by DustVoice** [comment]
OK I finally figured everything out by myself. Little bit tricky, but alright. I have completely integrated the screenshot function into the main software, after thoroughly testing it. It is now a new entry after "Insert Image" in the menu. I will now try to build my version of CherryTree for other people to test it. I will then open a pull request, so it will hopefully be integrated. Anyways, I will be using this feature at least for myself. Thanks again for the great software.

**Comment by casainho** [comment]
Great!!! Thank you.

A sexta, 4/05/2018, 20:27, David Holland <notifications@github.com>
escreveu:

**Comment by DustVoice** [comment]
Yeah the only thing is that I don't know how to integrate it into the menu bar. But whatever. Now I'll do some cleanup work, refurbishing my code a little bit, but generally speaking, you could now insert screenshots using Ctrl + Shift + Alt + S (temporarily). After that your screen gets a little bit grey. You can then move the overlay, using the move and resize modes, over the area of your screen that you desire to capture and simply hit RETURN. Then it gets inserted like a normal image. If you want to abort the process you just press ESC. For me this is a huge improvement of my workflow!

**Comment by DustVoice** [comment]
Alright problem solved. It was an old config file, that produced the issue.

**Comment by DustVoice** [comment]
Now it is a fully integrated feature, at least if you're using my version. I'm gonna create a new repo and then open a pull request. I have tested everything thoroughly, so there shouldn't be any bugs. Hopefully Giuseppe will approve. Would love to see it in the software.

**Comment by DustVoice** [comment]
You can try the new feature out under https://github.com/DustVoice/cherrytree/tree/Screenshot

**Comment by DustVoice** [comment]
I created a merge request with the new screenshot feature. I would highly recommend integrating it. There are no conflicts with the current repo. If it isn't part of the plan to merge directly into the master branch, I would suggest creating a new "Experimental" branch for such features, so that people willing to use the features are able to.

**Comment by hexterisk** [comment]
Why wasn't this functionality merged with the master branch? The work on this branch is over 200 commites behind the master branch and I wouldn't want to miss out on the great features you guys built this past year.
