### ISSUE TITLE
Building cherrytree for windows

### ISSUE THREAD

**Issue by DustVoice** [giuspen/cherrytree#366]
Unfortunately I can't seem to succesfully build cherrytree on Windows for Windows. Does one normally build it on Linux? Or is it just my Windows that does fail...

**Comment by giuspen** [comment]
I will try when I have a moment and give feedback and link the build here if successful. I'm using a Windows xp VM for the purpose but I also tried successfully on Win7 in the past. The command is "python setup.py py2exe"

**Comment by DustVoice** [comment]
ok I'm on win 10, so maybe that's the issue. But if you have a Moment and could build it that be great of Course, I will still try another attempt with xp

**Comment by DustVoice** [comment]
Ok so I Setup a new VM with win xp and after finally getting py2exe to install, It ran almost through but I got the following error message:
`error: can't copy 'locale\cs\LC_MESSAGES\cherrytree.mo': doesn't exist or not a regular file`

It would be really kind if you could provide me with a solution to this, if you have encountered this Problem yourself

**Comment by giuspen** [comment]
For this problem just enter directory locale and double click on i18n_po_to_mo.py

**Comment by DustVoice** [comment]
Thank you so much for responding this quick. I really appreciate your work and effort and am really happy that I had the opportunity to contribute to such a great Project.

**Comment by DustVoice** [comment]
Ok unfortunately i now got this error in the cherrytree.exe.log
```
Traceback (most recent call last):
  File "cherrytree", line 78, in <module>
  File "cherrytree", line 49, in f_main
  File "main.pyc", line 22, in <module>
  File "gtk\__init__.pyc", line 30, in <module>
  File "gobject\__init__.pyc", line 26, in <module>
  File "glib\__init__.pyc", line 22, in <module>
  File "glib\_glib.pyc", line 12, in <module>
  File "glib\_glib.pyc", line 10, in __load
ImportError: DLL load failed: Die procedure wasn't found.
```

**Comment by DustVoice** [comment]
But only in the py2exe executable file. not when running it from source. Sorry if I'm kinda annoying you. It would just be great if I can build my own builds and maybe help with some integrations.
