### ISSUE TITLE
Does not import Zim journal

### ISSUE THREAD

**Issue by Signum** [giuspen/cherrytree#369]
I love the feature to import Zim wikis. Zim has worked for me for four years but apparently cannot cope with many documents so I'm going with CherryTree now.
I managed to import almost all documents. However my Zim journal was not imported – it was just skipped. Maybe the problem lies in https://github.com/giuspen/cherrytree/blob/master/modules/imports.py#L787 which does not recurse into Zim structures like Journal/2018/05/21.txt
Not even the "Journal" node is created in CherryTree.
As a workaround I imported the Journal as "text" which worked but obviously I lost all my formatting.

**Comment by frenchiveruti** [comment]
I have the same issue, is there any workaround?

**Comment by giuspen** [comment]
@frenchiveruti can you attach a test document that reproduces the issue or send me privately? Also specify what is not being imported in your test case

**Comment by frenchiveruti** [comment]
Hello giuspen, yes, I can. 
I didn't delete the zim folder and the contents aren't private. 
I've used `Zim 0.73.5` and `CherryTree 0.99.33` respectively.  

In my test space nothing is being imported no matter what I do with the Zim folder, I had some success using markdown and pandoc and then importing with markdown.  
Here's the zip file with my Zim Folder.  
[Introducción-BD.zip](https://github.com/giuspen/cherrytree/files/6313500/Introduccion-BD.zip)

**Comment by frenchiveruti** [comment]
I tried, HTML file 
HTML folder
Zim Folder
Markdown file
Markdown folder

Now I do not remember which of all of them "worked", but one of them worked.

**Comment by kklepper** [comment]
Cannot import Zim according to https://giuspen.com/cherrytreemanual/#_importing

> Select a file or folder to import then click Open.
> 
> In the Who is the parent? menu, select one of the following options:
> 
> The Tree Root - Each imported file is added to a top-level node.
> 
> The Selected Node - Each imported file is added to a child node of the selected node.
>
I can open the Zim directory, but nothing happens. So I look for the `Who is the parent?`-menu item -- where the heck is that? Embarrassing.

**Comment by giuspen** [comment]
I tried the document attached from @frenchiveruti and it imported successfully with the current version.
The manual is discontinued unfortunately, import pointing to the root folder of zim and if it fails you can send me the dtaa privately if you want and I can give it a try.
