### ISSUE TITLE
Monospace Property font is always "Monospace" for Rich Text nodes

### ISSUE THREAD

**Issue by bhutch** [giuspen/cherrytree#372]
Hello,

I'm using CherryTree 0.38.4 on Windows 10.

When toggling the "monospace property" of text in rich text notes, the font is always "monospace" instead of the configured "code font".

To reproduce, choose any font other than "monospace" under Preferences/Fonts for the code font. Highlight some text, and choose "Toggle monospace property of the selected text". The font for this text is always "monospace" (my personal preference would be "Lucida Console").

Is this a bug? Is it otherwise possible to use a typeface other than "monospace" for "monospace property" text?

Thanks!

**Comment by giuspen** [comment]
Hi, at the moment the monospace is merely adding the monospace tag to the font used for the rich text, it is not changing the font to that configured in code font. I cannot improve this personally for now because of many higher priority tasks

**Comment by tomiosdelta** [comment]
Hello!
Can we control the font that appears when the monospace tag is added? There must be somewhere a setting - definition for that font. No need to implement a new feature for that.
Monospace tagging is very useful, especially for notes containing both sentences and code in the same line. You highlight the code part and apply the monospace property.
It would be great if we could control how the code appears in the notes (without having to insert a new codebox for every small part of code).
Thanks

**Comment by giuspen** [comment]
I will have a look if I can quickly add an option to config.cfg (without gui interface) for that but cannot guarantee because the priority is porting to a new library, pygtk2 is already out of latest Debian testing

**Comment by pedroflor** [comment]
Hi @giuspen!
Do you have news for this issue?
Would be great to know where to touch in the code.

**Comment by giuspen** [comment]
OK I'll add the possibility to configure the font for the text tagged monospace

**Comment by pedroflor** [comment]
> OK I'll add the possibility to configure the font for the text tagged monospace

Thank you so much!
