### ISSUE TITLE
Size of the horizontal wrapping

### ISSUE THREAD

**Issue by ours-code** [giuspen/cherrytree#378]
Hello,

Thank you for that note taking app.
I might miss something very obvious but I cannot find the option to set the size of the horizontal wrapping.
Could you point me to it if it is implemented ?

Thank you,

**Comment by giuspen** [comment]
Hi, the horizontal wrapping for the tree nodes names is configurable in the preferences dialog, for the text content it is just the right end of the window

**Comment by ours-code** [comment]
Hello,

The wrapping of the text fails for me (see screenshot attached). 
![wrapping_bug](https://user-images.githubusercontent.com/3473632/42269683-1de2937e-7f7f-11e8-81d1-a34f8510768b.png)

It happens on a windows server 2012 with remote desktop. Both client and server have the same screen resolution. Version of Cherry is 0.38.4.

I am unfamiliar with GTK and I fail to see what goes wrong. Do you have an idea ?

Thank you,

**Comment by giuspen** [comment]
Should be ok in the current git HEAD
