### ISSUE TITLE
CherryTree losing recent edits

### ISSUE THREAD

**Issue by oregonjim** [giuspen/cherrytree#379]
On three occasions in four days, I have added text to an existing node, quit CherryTree, and reopened it to find the added text gone.

I have auto save on quit turned on, as well as save every 5 minutes.  I also manually save with Ctrl+S every time I enter text (old habit).  However, I have not discovered a way to reproduce this behavior reliably.

This is CherryTree 0.38.2 under Linux x86_64.

P.S. What does the "Save and Vacuum" File menu entry do?  I can't seem to find it anywhere in the manual.  The "Execute Code" menu entry is also missing from the manual.

**Comment by giuspen** [comment]
Hi, please use the latest 0.38.4. I will try and release a new 0.38.5 shortly with further fixes.
The manual is discontinued unfortunately, the guy taking care of it doesn't have time for it anymore. 
Save and vacuum is also rebuilding the whole sqlite database. It is worth doing itfrom time to time to optimise size and speed.

**Comment by oregonjim** [comment]
Thanks giuspen.  I'd prefer to stick with my package manager's version, which is currently 0.38.2 under Fedora.  Hopefully they'll push an update soon.
