### ISSUE TITLE
Feature request: allow deletion of recent documents entry

### ISSUE THREAD

**Issue by den0x** [giuspen/cherrytree#382]
Hi,

To second [a topic](https://www.giuspen.com/topic/feature-request-allow-deletion-of-recent-documents-entry/) that was started on the forums, I'd like to request this feature too.

Prior to [this commit](https://github.com/giuspen/cherrytree/commit/bd87df1e572af08be3f4786dc327a2222ae302cf#diff-afce720ab9a03c04130dc32a2c5f31cd) made in October of 2015, a recent document that no longer existed, was deleted automatically from the list. After this commit it is moved to the bottom of the list.

It would be great if a feature could be introduced that allows you to delete an item in the recent documents list, rather than the list continuing to list documents that may no longer exist. For example: by hovering over the item in the recent document list and hitting delete, or a different shortcut, the item could be deleted.

**Comment by giuspen** [comment]
Agree to this and should not take long to implement, I'll try and add this soon

**Comment by den0x** [comment]
@giuspen Any chance to include this small feature soon?

**Comment by giuspen** [comment]
Yes this will be in next minor release shortly

**Comment by omega3** [comment]
@giuspen

Please read comments on this on cherrytree forum:
https://www.giuspen.com/topic/can-i-disable-open-remove-from-list-feature/

**Comment by den0x** [comment]
Thank you!
