### ISSUE TITLE
Type Ahead

### ISSUE THREAD

**Issue by prog20901** [giuspen/cherrytree#383]
It would be great if type-ahead search is implemented like Docfetcher. The recent docfetcher version has type-ahead search

https://sourceforge.net/p/docfetcher/feature-requests/138/

**Comment by giuspen** [comment]
No I cannot work on this now

**Comment by metal450** [comment]
Looks like this has been implemented :) https://github.com/giuspen/cherrytree/pull/2552

**Comment by giuspen** [comment]
That's right, thanks for spotting this @metal450
