### ISSUE TITLE
Unable to Start Blank screen

### ISSUE THREAD

**Issue by MikeStutzzzz** [giuspen/cherrytree#385]
Ubuntu 18.04 Tried enabling app indicators and when restarting the app it just shows a blank white screen. I also tried uninstalling from the software center added your PPA and during install, I see these messages. 

Error in file "/usr/share/applications/org.gnome.font-viewer.desktop": "font/ttf" is an invalid MIME type ("font" is an unregistered media type)
Error in file "/usr/share/applications/org.gnome.font-viewer.desktop": "font/otf" is an invalid MIME type ("font" is an unregistered media type)
![image](https://user-images.githubusercontent.com/28896682/42987030-72d9a684-8bbd-11e8-960c-8adee3f7b0ec.png)

**Comment by giuspen** [comment]
Try Alt+Tab, try rebooting, try remove ~/.cherrytree/config.cfg

**Comment by MikeStutzzzz** [comment]
Removing config.cfg fixed it I will test to see if trying to use the TrayIcon on Ubuntu 18.04 Wayland breaks it again.

**Comment by MikeStutzzzz** [comment]
hmm Tested the App Indicator on the new version no issue not sure what happened the first time.

**Comment by danieljnilson** [comment]
I am having a very similar issue. Ubuntu 18.04. Except I do not see the error messages. I just get the same blank screen as shown in the screen cap, without any ability to load a note file. I can make a separate issue if you want.

**Comment by giuspen** [comment]
Can you try and remove the config.cfg as?

**Comment by danieljnilson** [comment]
I did remove it and the issue remained

**Comment by giuspen** [comment]
If you run from a terminal what do you see printed

**Comment by giuspen** [comment]
Looks like your user does not have write access to home/chrgre01/.config or home/chrgre01/.config/cherrytree

**Comment by ChristofferGreen** [comment]
Hi

Thank you.

Those files do not exist when launching the app. I tried by removing them before launching the app but the same behavior of blank startup window happens.
