### ISSUE TITLE
Zim - Did not import code from code block

### ISSUE THREAD

**Issue by sleepyspider1** [giuspen/cherrytree#386]
Zim has a "code block" you can insert and type code into. It highlights it. But when I imported my zim notebook into cherrytree, all the code blocks were gone and all the code was missing in the document.

**Comment by giuspen** [comment]
Can you send me your zim folder or any folder where I can reproduce the issue?

**Comment by sleepyspider1** [comment]
[TestNoteBook.zip](https://github.com/giuspen/cherrytree/files/2283770/TestNoteBook.zip)

You can see the code if you open up the .txt file. But after import, it just has a "}" for this case.

**Comment by giuspen** [comment]
should be ok now, can you test the latest from git master?
