### ISSUE TITLE
new 0.38.5  version does not start, portable, log attached

### ISSUE THREAD

**Issue by reifwp** [giuspen/cherrytree#387]
Hello Dear Author, new 0.38.5  version does not start, portable, log attached
[cherrytree.exe.log](https://github.com/giuspen/cherrytree/files/2216396/cherrytree.exe.log)

**Comment by reifwp** [comment]
win 10 64

**Comment by giuspen** [comment]
did you download from giuspen.com? is 0.38.4 working instead?
