### ISSUE TITLE
Shortcuts on non-EN keyboards

### ISSUE THREAD

**Issue by mnn** [giuspen/cherrytree#39]
Shortcuts are being interpreted as typed symbols instead of codes of pressed keys on keyboard. This leads to a situation (e.g. with CS keyboard) when pressing `<CTRL>+1` does not behave as `<CTRL>+1` but as `<CTRL>++`. Mapping of symbols on Czech keyboard on a key `1` is `+/1` not `1/!` (EN keyboard). Similar problems will be undoubtedly with many non-EN keyboard layouts.

**Comment by mnn** [comment]
After some digging it seems it's a bug in GTK2. Fuzzy matching of accelerators has apparently priority over key code - who the hell could wrote such thing?! Only way of fixing it I could think of (with my very poor GTK and Python knowledge) is implementing shortcuts rebinding support.

Also note that changing keyboard layout just for CherryTree is not possible when one wants to write notes in other language, so no easy workaround here :/. I probably end up hacking cons.py to Czech accelerators which is very bad solution updating-wise. * sad *

**Comment by mnn** [comment]
So changing values in cons.py did not yield results. I think the bug is in on_key_press_window in core - it should not use already interpreted keyname but scancode. Unfortunately hardware_keycode property of event contains already mapped values (at least on Windows - number changes when I switch kb layouts). I am hopeless.

**Comment by giuspen** [comment]
Hi, what is your os and keyboard layout and what are the broken shortcuts

**Comment by mnn** [comment]
Windows 7 64b, Python 2.7.10, default CS keyboard (QWERTZ). All shortcuts containing a number are wrongly listed, e.g. to trigger a shortcut `ctrl + 1` I have to press `ctrl + shift + 1`, to trigger a shortcut `ctrl + +` I have to press a `ctrl + 1`.

So in the end it is possible to use them, but it's quite cumbersome - e.g. a list is produced by pressing `ctrl + alt + shift + 1`.

Introducing custom key bindings or not using keyboard layout for accelerators would IMO solve this issue.

**Comment by txe** [comment]
Possibly it was related to Gkt2, and fixed in Gtk3
