### ISSUE TITLE
[CT 0.38.5_win32_portable] Portable version not really portable (Error on_window_destroy_event)

### ISSUE THREAD

**Issue by philippHRO** [giuspen/cherrytree#392]
Almost everytime I close my CT window, I'm getting an error dialog pointing me to the error log, where I then find multiple instances of this error:

`Traceback (most recent call last):`
`File "main.pyc", line 105, in on_window_destroy_event`
`File "shutil.pyc", line 239, in rmtree`
`File "shutil.pyc", line 237, in rmtree`
`WindowsError: [Error 3] Can't find path: 'c:\\users\\zachar~1\\appdata\\local\\temp\\tmpi8lfag/*.*'`

So it seems, CT is trying to find something in my user profile. But this is the portable version. So it really shouldn't be doing this, right?

Fortunately, all changes to my CT ctb are saved just fine. It's just this annoying dialog/error. Can you fix this?

**Comment by giuspen** [comment]
Thanks I'll look into this
