### ISSUE TITLE
Background color

### ISSUE THREAD

**Issue by jayypluss** [giuspen/cherrytree#394]
How can I change text editor background color?

**Comment by philippHRO** [comment]
You will find it in _Preferences -> Rich Test_ and _Preferences -> Tree 1_

**Comment by jayypluss** [comment]
Thank you! I don't know why I searched for it for so long and couldn't find it.

**Comment by feltonik** [comment]
@kettenfett I don't know if you still use the app but there are no such options in the preferences

**Comment by giuspen** [comment]
@feltonik you have to look for the preferences dialog tab Theme in the 0.99.x versions
