### ISSUE TITLE
readme.md

### ISSUE THREAD

**Issue by geneorama** [giuspen/cherrytree#397]
This project could benefit from a readme.  Here's a nice [template example](https://gist.github.com/glnds/c4e96429b5f138ced8fbe05e37a22807).  I would suggest at a minimum a project description and basic installation instructions. Perhaps indicate which branches are stable vs. development.

**Comment by siliconninja** [comment]
I agree, especially because the developer (giuspen) is migrating the project to gtkmm, and a readme.md with a notice would help people understand the project's status and why it is that way.

**Comment by MAvoss** [comment]
Thanks i was just looking for this
