### ISSUE TITLE
Error opening notebooks when path contains non-ASCII characters

### ISSUE THREAD

**Issue by guillempado** [giuspen/cherrytree#399]
I'm having problems opening a notebook in Windows 10 when, whether the path to the notebook or the filename itself, contain Unicode but non-ASCII characters. When the path isn't recognized, it just opens a blank notebook. Example:

Case |  Result
------------ | -------------
C:\path\to\notebook.ctd         |   Opens the notebook
C:\learn\català.ctd                  |   Opens a blank notebook
C:\learn\català\grammar.ctd  |   Opens a blank notebook

(The same happens with *.ctb).

**Comment by guillempado** [comment]
Hyperlinking from one notebook to a file, chosing another notebook as that file, does reproduce the bug

**Comment by giuspen** [comment]
should be fixed for future releases

**Comment by txe** [comment]
Fixed in #633
