### ISSUE TITLE
Feature Request: Insert Today's Date should be placed under the level you right-clicked from

### ISSUE THREAD

**Issue by KOM2015** [giuspen/cherrytree#40]
When I right-click on a node and select **Insert Today's Date**, I would like the new node to be under the one I right-clicked.  Instead, it seems to put it at some specific level and I have to move it.  See image. _Sorry, I can't seem to get the image to upload or paste in any way..._
![Uploading node.jpg…]()

**Comment by txe** [comment]
The command behavior won't be change, but for personal use it's quite ease change in the source

**Comment by jdgarner123160** [comment]
Is it it possible to reconsider this? I believe that creating a today's date structure under a current node would be a common if not majority use case. For me I might have dates under something like Home>>Maintenance>>Log. In another spot I might have another date structure in Personal>>Journal. Thank you for the excellent program.

**Comment by giuspen** [comment]
Yes I may support this as it should be a quick change. In the short term though I'm busy implementing a lighter version of the tables, I'm already halfway in the implementation and trying to keep focused on it

**Comment by jdgarner123160** [comment]
Thank you!

**Comment by giuspen** [comment]
will be in upcoming version 0.99.54
