### ISSUE TITLE
Feature Request : Support for Latex Style Math Equations

### ISSUE THREAD

**Issue by abidrahmank** [giuspen/cherrytree#400]
Hello,

Is it possible to add math equations in cherrytree?

Something like this : https://www.mathjax.org/

Regards,
Abid K

**Comment by giuspen** [comment]
Yes but not shortly unless somebody else works on that

**Comment by vastol** [comment]
+1

**Comment by obbardc** [comment]
this would be a really nice feature, maybe use with the libreoffice math editor as its pretty usable IMO?

currently just screenshotting and hoping I don't need to edit them! :-)

**Comment by nm17** [comment]
Still waiting for Latex support... This needs to have a higher priority for devs

**Comment by obbardc** [comment]
> Still waiting for Latex support... This needs to have a higher priority for devs

this is an open-source project, so you are more than welcome to work on the feature yourself or kindly ask the developer to look at a feature request. What you cannot do is demand what the developer works on.

**Comment by residentbrick** [comment]
CherryTree seems to be displaying math in this YouTube video (from 2:00 to 2:15)

Demo of CherryTree
https://www.youtube.com/watch?v=97lAMRrAcF4

as Minghao Liu creates a simple fractional expression and then has it correctly displayed.

The video is without an explanatory audio track or helpful notes.  I tried to duplicate the
effect but I must be overlooking something important.

**Comment by kohrVid** [comment]
> CherryTree seems to be displaying math in this YouTube video (from 2:00 to 2:15)
> 
> Demo of CherryTree
> https://www.youtube.com/watch?v=97lAMRrAcF4
> 
> as Minghao Liu creates a simple fractional expression and then has it correctly displayed.
> 
> The video is without an explanatory audio track or helpful notes. I tried to duplicate the
> effect but I must be overlooking something important.

That video shows a completely different application (they even link to it in the comments section). [The cherrytree in the video](https://github.com/molikto/CherryTree) is written in Scala and this one is written in Python/C++. Personally don't think the UI in the video is as good as giuspen's app but it does appear to support Latex

**Comment by Oisangui** [comment]
So still no support?

**Comment by giuspen** [comment]
I've been working on it in the last days, this will be in the next release

**Comment by MJimitater** [comment]
this would be a serious game-changer!!

**Comment by abidrahmank** [comment]
Just tested it.. Pretty awesome !!! 

![image](https://user-images.githubusercontent.com/678900/163110333-ffb86d97-da21-4714-bd1a-d92a92443c5d.png)
(With dpi set to 200 instead of default 140)

Thank you !!!

**Comment by wgreene310** [comment]
Yes, this is quite impressive!
