### ISSUE TITLE
define css for html export

### ISSUE THREAD

**Issue by demonbob** [giuspen/cherrytree#404]
Hey Guys!

cherrytree has officially become my defacto note and documentation prototyping tool at work and home. I like to export the entire tree's as HTML and set them as my browsers home page. With that said, I would love to be able to specify a stylesheet to use when exporting so I can customize the look for when I distribute the notes to colleagues.

**Comment by giuspen** [comment]
Hi, the current css in use is https://github.com/giuspen/cherrytree/blob/master/glade/styles.css but you can override it by placing a new one with the same name in the config folder (Help--open preferences directory)

**Comment by demonbob** [comment]
Thanks you, i'll review it and close this.
