### ISSUE TITLE
Error - Unable to install cherrytree_0.38.6-0_all.deb. dpkg-deb

### ISSUE THREAD

**Issue by JonnyBekoff** [giuspen/cherrytree#409]
Unable to install cherrytree_0.38.6-0_all.deb. dpkg-deb: error: archive cherrytree_0.38.6-0_all.deb contains not understood data member control.tar.xz, giving up
OS - Ubuntu 12.04, 32bit

**Comment by giuspen** [comment]
are you using the giuspen ppa?

**Comment by JonnyBekoff** [comment]
If I take the file from the PPA repository - the same error and cannot be installed

**Comment by giuspen** [comment]
Of you run ./cherrytree after extracting the tarball it works?

**Comment by JonnyBekoff** [comment]
When you try to install (dpkg-i ./cherrytree_0.38.6-0_all.deb) or unpacking, the same error is issued - dpkg-deb: error: archive './cherrytree_0.38.6-0_all.deb' contains not understood data member control.tar.xz, giving up...

**Comment by giuspen** [comment]
No I mean extract the source code archive, extension .tar.xz then extract the files change directory inside, run with a terminal ./cherrytree

**Comment by JonnyBekoff** [comment]
Sorry, misunderstood ... - Yes, in this case it starts normally

**Comment by JonnyBekoff** [comment]
Tell me, do you post the corrected deb-installer?

**Comment by giuspen** [comment]
I'm sorry Jonny but my free time is limited and 12.04 is too old you should upgrade, furthermore you can make it work from the sources tarball.

**Comment by JonnyBekoff** [comment]
Ok, and thanks for that. Good luck to you in developing and supporting this wonderful program ...
