### ISSUE TITLE
No handling of list indentation levels

### ISSUE THREAD

**Issue by zauberparacelsus** [giuspen/cherrytree#41]
Right now I'm trying out CherryTree as a possible replacement for Zim.  However, I have found two issues with it.

With every rich-text editing app I've tried, when at the front of an item in a bullet list (IE: the caret is before the text, but after the bullet and space), pressing tab will indent the bullet item's level.  CherryTree does not follow this pattern, and instead indents the text while leaving the bullet alone.  In order to indent the list item's level, you need to indent before the bullet.

The second issue is that when you are on a list item's line and press return, the indent level is not preserved.

So, if you had a list like this:
- One
  - Two
    - Three

And then hit return, the indentation level goes back to the first one, instead of matching the indent level of the third item.  So, you would get this:
- One
  - Two
    - Three
- Four

Instead of this:
- One
  - Two
    - Three
    - Four

These are the only main issues I have so far that I find problematic.  Based on other observed quirks (such as line-wrapping behavior), the real issue is that CherryTree doesn't support proper list indentation levels, in which case this report can be treated as a feature/enhancement request.

**Comment by giuspen** [comment]
Hi, a user just made a generous donation to support the development of this
very feature so it is the next thing I'll work on

**Comment by zauberparacelsus** [comment]
Oh, excellent!

**Comment by barraclm** [comment]
Hi - almost 2 years later. Any progress?

**Comment by giuspen** [comment]
This has already been implemented
