### ISSUE TITLE
Tree text becomes invisible in ubuntu cosmic cherrytree 0.38.6 (and default version)

### ISSUE THREAD

**Issue by v217** [giuspen/cherrytree#414]
Unless selected the text in the tree is not visible in ubuntu cosmic. I tried different fonts but the issue remains. Thanks! 
![image](https://user-images.githubusercontent.com/6884591/47221982-fce1d500-d3b5-11e8-8dcb-1e8b8ec3d33f.png)

**Comment by giuspen** [comment]
You can control the colour of foreground and background of the tree in the preferences
