### ISSUE TITLE
CherryTree wrong AppIndicator : blue envelope instead of red cherries

### ISSUE THREAD

**Issue by Saroumane** [giuspen/cherrytree#415]
cherrytree (0.37.6) displays in the appindicator area a blue envelope instead of the expected red cherries (see screenshot)

![cherrytree appindicator](https://user-images.githubusercontent.com/22261137/47418232-fff41100-d779-11e8-9b7c-27f5cc56ea37.png)

CherryTree 0.37.6 on Xubuntu 18.10

**Comment by giuspen** [comment]
That's weird, try to upgrade to latest version, then try from the preferences use normal systray instead of appindicator

**Comment by giuspen** [comment]
Cherrytree has never been updated in the official repositories, only upgrading Ubuntu you will find a newer version. This is also the case of many other apps and often it is the ppa that keeps those apps safe

**Comment by Saroumane** [comment]
It's good actually !
It means you never had critical security breaches to patch. (Ubuntu provides security patches on a daily basis, according to this policy https://wiki.ubuntu.com/Security/Upgrades and my personal experience)
And I can totally wait 6 months (for the next Ubuntu release), to get new features.
I'm done with "beta-testing" new versions :)

Moreover, a PPA can be compromised, and malware pushed to users.
So less repositories used : less risks !
