### ISSUE TITLE
Could not open cherrytree.exe.log

### ISSUE THREAD

**Issue by valentinbesse** [giuspen/cherrytree#416]
Since yesterday I got an error when I launch cherrytree saying cherrytree.exe.log could not be open, [Errno 13] (see attached file). If I click on OK, cherrytree just close.
![cherrytreeproblem](https://user-images.githubusercontent.com/25610131/47484322-b5d36400-d83b-11e8-8f8b-63fbbad87b2d.PNG)

**Comment by philippHRO** [comment]
are you using version 0.38.6?

**Comment by valentinbesse** [comment]
Yes. But on another laptop I'm using 0.38.5 and I have the same issue.

Le 25 octobre 2018 13:07:30 GMT+02:00, philipp <notifications@github.com> a écrit :
>are you using version 0.38.6?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/giuspen/cherrytree/issues/416#issuecomment-433009302

--
Valentin Besse
13, boulevard Lamartine
bât. B, appt. 207
72000 Le Mans
Mobile : +33 6 47 77 64 45
PGP : 0x57F941B1

**Comment by giuspen** [comment]
If you try to 'run as an administrator'? If you download and run the portable version?

**Comment by valentinbesse** [comment]
I tried but I does not work. I get a different message 
![cherrytreeproblem2](https://user-images.githubusercontent.com/25610131/47551121-a28acc00-d901-11e8-8a17-eab845d70412.PNG)
I attached also the 
[cherrytree.exe.log](https://github.com/giuspen/cherrytree/files/2518189/cherrytree.exe.log)

**Comment by giuspen** [comment]
The error says that the xml has a syntax error, you should try to open the backup of your document after renaming removing the tilde. By default cherrytree has three backups (one, two and three saves ago)

**Comment by giuspen** [comment]
Or try to open the cherrytree xml document with an xml editor / parser to fix the issue, I can have a look if you send to me privately by mail

**Comment by valentinbesse** [comment]
Thank you ! I will try to solve it by myself. It's the best way to understand how it works. If I failed I will return to you.

**Comment by TestLove** [comment]
> 谢谢 ！我会尝试自己解决。这是了解其工作方式的最佳方法。如果我失败了，我会回到你身边。

could you please tell me how to solve it?
