### ISSUE TITLE
export as pdf, the picture is blurry

### ISSUE THREAD

**Issue by linpxin** [giuspen/cherrytree#420]
well, I am using cherrytree v0.38.6 in windows10 x64. When I export the cherrytree document as pdf, the picture is blurry. Does it have any options to adjust the quality of picture?

_Sent from my 8692-M02 using [FastHub-Libre](https://github.com/thermatk/FastHub-Libre/)_

**Comment by giuspen** [comment]
There are no options, with the current toolkit in use (pygtk2) this is the best result

**Comment by linpxin** [comment]
that sucks

_Sent from my 8692-M02 using [FastHub-Libre](https://github.com/thermatk/FastHub-Libre/)_

**Comment by bitboy85** [comment]
Seems to be a duplicate of https://github.com/giuspen/cherrytree/issues/119
