### ISSUE TITLE
https://www.giuspen.com/forum/cherrytree-2/

### ISSUE THREAD

**Issue by Acry** [giuspen/cherrytree#421]
Hi Giuseppe!
From time to time I can not create any topic or responses in the WP-Forum.

I tried, Android-Chrome, Linux-Chromium, Windows-Chromium/Edge.
Even making a new Account doesn't help.

If I write something it won't appear, if I do it again it says duplicate.
Sometimes I am ask for a capture, sometimes not.

Any Ideas?

**Comment by giuspen** [comment]
Hi, I don't have time to dedicate to the forum since fully committed to the porting pygtk2 to gtkmm3, use github issues for bugs or new features
