### ISSUE TITLE
In windows, I have a Big Cherrytree document full of nodes, codeplexes, and images. If I tried to create or import a new node the program freezes for 6 seconds, then continues to work. This happens to this CherryTree file only, everytime.

### ISSUE THREAD

**Issue by Eagle6789** [giuspen/cherrytree#422]

**Comment by philippHRO** [comment]
Have you tried the "Save and Vacuum" function?

Are you using one of the password protected file formats ctx/ctz? try to save your document as ctb and see if it helps.

These are just wild guesses, though.

**Comment by Eagle6789** [comment]
> Have you tried the "Save and Vacuum" function?
> 
> Are you using one of the password protected file formats ctx/ctz? try to save your document as ctb and see if it helps.
> 
> These are just wild guesses, though.

It is already a ctb document, not password protected.
Tried "Save and Vacuum, still no effect.

Is any there away to clean & rebuild the document, to restore its smoothness?

**Comment by giuspen** [comment]
The 'Save As' rebuilds it fully from scratch

**Comment by Eagle6789** [comment]
@giuspen 
Did not work 😥, the program continues to freeze for 6-7 seconds every time i try to create a new node.
And **cherrytree.exe.log** does not show anything.

**Comment by 1637664504** [comment]
Ye, I also meet this issue. 
"Save as " xxx.ctb . It's seem ok.

**Comment by Eagle6789** [comment]
@1637664504 Did not work for me.  **What** I did is; I deleted a **node**(contains many sub-nodes) it was very **big** one about the third of the cherry file, now everything work fine there no more **freeze**.
