### ISSUE TITLE
Feature Request: Keyboard Shortcut to toggle To-Do List Item State

### ISSUE THREAD

**Issue by benboeck** [giuspen/cherrytree#438]
Overview:
It would be great if the state of TODO list items could be toggled via keyboard shortcut, e.g. through CTRL+SPACE.

Long:
Thank you for this great application!
Looking for a cross-platform TODO list solution I also checked cherrytree - great idea and features, would love to use it for simple TODO lists, too.
I particularly like the many keyboard bindings but miss an option to toggle the state of to-do list items via keyboard.
Trying to implement it I found todo_list_rotate_status in lists.py which should make it easy to implement the function: if the start of the line is a TODO list character, toggle it. However I don't seem to be able to hack it together in a way that works :/

Thank you,
kind regards

Ben

**Comment by giuspen** [comment]
Makes sense, please test the implementation from git it if you can

**Comment by benboeck** [comment]
Thank you, works like a charm!
All the best for 2019!
Regards, Ben

**Comment by alpererm** [comment]
Hi,

The feature works for the main (unindented) tasks. If I use space or tab to increase the indent and create subtasks, it does not work.

Regards,
Alper

**Comment by giuspen** [comment]
Thanks @alpererm should be ok now
