### ISSUE TITLE
Nested lists?

### ISSUE THREAD

**Issue by erezhdd** [giuspen/cherrytree#44]
Would it be possible to have nested (hierarchical) lists?
I'm not talking about complex 1.2.3 notation, just a simple indent in/out to allow a new list to be created inside an item of an outer list, without breaking the counting or style of either lists.

On a more general note, I love Cherry Tree. IMO, it is by far the best notebook application I have seen on Linux, compared to many others. This is one of the things that keep me motivated in contributing to the community as well, seeing the great products that come out. Keep going strong!

**Comment by giuspen** [comment]
Hi, an user recently made a generous donation to ensure that the nested
lists will make it in the next major release, so it's quite sure that you
will see this soon.

**Comment by txe** [comment]
Closing, was done
