### ISSUE TITLE
Feature Request: allow export without requiring GUI

### ISSUE THREAD

**Issue by manad777** [giuspen/cherrytree#456]
Would it be possible to allow export to work without the GUI dependency without tons of refactoring?

CherryTree's command-line export doesn't run on a headless Ubuntu (16.04) server. That is, Ubuntu without a display. GTK segfaults due to the lack of a display. Here's a paste of the output: https://pastebin.com/raw/QUDxf5hq

Use-case: be able to read my notes remotely with a web browser, in an emergency on other people's computers. This requires being able to export CT docs to HTML. I plan to sync my CT files to my own server, and have a "on upload" triggered script on the server automatically export CT docs to HTML, while serving the HTML directory with nginx. 

On a related note, is it possible to automate the extraction of password-protected CT docs, even with a GUI? Command-line doesn't seem to work on Windows and I can't fire up a desktop Linux VM right now, so I can't test.

**Comment by giuspen** [comment]
See http://manpages.ubuntu.com/manpages/xenial/man1/xvfb-run.1.html

**Comment by manad777** [comment]
Thanks.

**Comment by poleguy** [comment]
This approach works around the problem, thanks! I'm running centos 8, and an export confirms it works:
``mkdir test``
``xvfb-run cherrytree -x test cherrytree.ctb``

However it was hard for me to find this page as it's a closed feature request. Any chance you can change the error message to suggest this fix?

I changed: 
/usr/share/cherrytree/modules/main.py

The first lines now read:

import sys
try:
    import gtk
except:
    print("No DISPLAY available? To do headless export use 'xvfb-run cherrytree -x out_dir filename.ctb'")
    sys.exit()

import gobject

import os
...

**Comment by poleguy** [comment]
I'm also awaiting access to the forums to link this conversation to this solution. No confirmation email yet. https://www.giuspen.com/topic/can-i-export-from-ctd-without-gtk/

**Comment by giuspen** [comment]
@poleguy try this passwordnand change it straight away
M6(zNryB#@)WiyVHvbgecZkx
