### ISSUE TITLE
Feature request: Customizable "Today" node

### ISSUE THREAD

**Issue by markwmuller** [giuspen/cherrytree#461]
I really like the idea of a shortcut to go to Today's node (F8). I think it'd be nice to have two additional features:
1. Modify the nesting format -- for me I have a base node called "Diary", in which I'd like to have the new node inserted, rather than a root node with the year.
2. Have the option to choose weekly/monthly nodes, instead of daily ones. 

Ideally, I'd like to hit "F8", and have CT jump to this week's node, which I have placed in a location in my notes tree that is sensible to me. 

BTW: Very nice tool :)

**Comment by txe** [comment]
You can fix it on your local CT, take a look at #434 for example.

**Comment by markwmuller** [comment]
Thanks, was easy to modify!
