### ISSUE TITLE
(since 0.38.8) pasting Youtube titles into Cherrytree turns them into Chinese

### ISSUE THREAD

**Issue by waynongithub** [giuspen/cherrytree#472]
Hi, 
since upgrading to 0.38.8, Cherrytree regularly - but not always - pastes the titles of youtube videos as Chinese characters.

I checked with three browsers:
firefox 65.0.1 (64bit)
chrome Version 70.0.3538.102 (Official Build) (64-bit)
brave Version 0.60.47 Chromium: 72.0.3626.119 (Official Build) (64-bit)

The results are inconsistent between browsers:

The examples below show how the titles copied from the different browsers paste into Cherrytree.

[https://www.youtube.com/watch?v=UXzW-pZ5sUQ](url)

firefox: QUEEN -  Death On Two Legs live London 1979
brave: QUEEN -  Death On Two Legs live London 1979
chrome: QUEEN -  Death On Two Legs live London 1979

[https://www.youtube.com/watch?v=Kee9Et2j7DA](url)
firefox: 洼瑥⁡瑨灴攭畱癩∽潣瑮湥⵴祴数•潣瑮湥㵴琢硥⽴瑨汭※档牡敳㵴瑵ⵦ∸㰾ㅨ挠慬獳∽楴汴⁥瑳汹ⵥ捳灯⁥瑹ⵤ楶敤ⵯ牰浩牡⵹湩潦爭湥敤敲≲儾敵湥ⴠ䤠眠湡⁴潴戠敲歡映敲㱥栯㸱
brave: Queen - I want to break free
chrome: Queen - I want to break free

[https://www.youtube.com/watch?v=0E2mjJvBKs8&list=OLAK5uy_mhCo-howOxkAEzE_Z2kQKE2CX1R_1BG2E](url)

firefox: Queen - Tenement Funster (Official Lyric Video)
brave and chrome: 洼瑥⁡瑨灴攭畱癩∽潣瑮湥⵴祴数•潣瑮湥㵴琢硥⽴瑨汭※档牡敳㵴瑵ⵦ∸㰾ㅨ挠慬獳∽楴汴⁥瑳汹ⵥ捳灯⁥瑹ⵤ楶敤ⵯ牰浩牡⵹湩潦爭湥敤敲≲猠祴敬∽慭杲湩›瀰㭸瀠摡楤杮›瀰㭸戠牯敤㩲〠硰※慢正牧畯摮›杲⡢㔲ⰵ㈠㔵‬㔲⤵※楤灳慬㩹戠潬正※慭⵸敨杩瑨›⸴爸浥※癯牥汦睯›楨摤湥※潦瑮眭楥桧㩴㐠〰※楬敮栭楥桧㩴㈠㐮敲㭭挠汯牯›慶⡲ⴭ瑹ⵤ楶敤ⵯ牰浩牡⵹湩潦爭湥敤敲⵲楴汴ⵥ潣潬Ⱳ瘠牡⴨礭⵴灳捥琭硥⵴牰浩牡⥹㬩映湯⵴慦業祬›潒潢潴‬牁慩ⱬ猠湡⵳敳楲㭦映湯⵴楳敺›慶⡲ⴭ瑹ⵤ楶敤ⵯ牰浩牡⵹湩潦爭湥敤敲⵲楴汴ⵥ潦瑮猭穩ⱥㄠ㠮敲⥭※潦瑮瘭牡慩瑮氭杩瑡牵獥›潮浲污※潦瑮瘭牡慩瑮挭灡㩳渠牯慭㭬映湯⵴慶楲湡⵴畮敭楲㩣㬠映湯⵴慶楲湡⵴慥瑳愭楳湡›※牴湡晳牯㩭瘠牡⴨礭摴瘭摩潥瀭楲慭祲椭普ⵯ敲摮牥牥琭瑩敬琭慲獮潦浲‬潮敮㬩琠硥⵴桳摡睯›慶⡲ⴭ瑹ⵤ楶敤ⵯ牰浩牡⵹湩潦爭湥敤敲⵲楴汴ⵥ整瑸猭慨潤ⱷ渠湯⥥※潦瑮猭祴敬›潮浲污※敬瑴牥猭慰楣杮›潮浲污※牯桰湡㩳㈠※整瑸愭楬湧›瑳牡㭴琠硥⵴湩敤瑮›瀰㭸琠硥⵴牴湡晳牯㩭渠湯㭥眠楨整猭慰散›潮浲污※楷潤獷›㬲眠牯ⵤ灳捡湩㩧〠硰※眭扥楫⵴整瑸猭牴歯ⵥ楷瑤㩨〠硰※整瑸搭捥牯瑡潩⵮瑳汹㩥椠楮楴污※整瑸搭捥牯瑡潩⵮潣潬㩲椠楮楴污∻㰾瑹昭牯慭瑴摥猭牴湩⁧潦捲ⵥ敤慦汵⵴瑳汹㵥∢挠慬獳∽瑳汹ⵥ捳灯⁥瑹ⵤ楶敤ⵯ牰浩牡⵹湩潦爭湥敤敲≲儾敵湥ⴠ吠湥浥湥⁴畆獮整⁲伨晦捩慩⁬祌楲⁣楖敤⥯⼼瑹昭牯慭瑴摥猭牴湩㹧⼼ㅨ>

So far I've only noticed it with the titles of many, but not all, youtube videos. The description or comments of the videos paste OK. Also no problems with pasting from other nodes in Cherrytree, or content from other applications or websites.

I've also checked pasting into different editors (gedit, atom, LibreOffice Writer), they never paste Chinese.

My workaround is to paste first into a text editor and then copy/paste from the editor into Cherrytree. 

My language is set to English, my keyboard is US, I do not speak/read/write Chinese, so none of my OS or application settings should refer to Chinese character sets. 

Working in Linux Mint 18.3 Mate

**Comment by giuspen** [comment]
When it happens try paste as plain text or Ctrl+Shift+V which equals to past to a plain text editor with no support for rixh text formatting. I'll have a look at your test cases

**Comment by waynongithub** [comment]
Ha, tnx, I hadn't discovered that option yet, and it is definitely faster than my workaround. Tnx!

**Comment by ChrisOfBristol** [comment]
Cut and paste with ^C ^V from a BBC news page results in "Chinese-style characters".
https://www.bbc.co.uk/news/world-asia-china-55364445
CherryTree 0.39.4 on Ubuntu Budgie 20.10.

**Comment by giuspen** [comment]
Please upgrade to latest 0.99.29

**Comment by ChrisOfBristol** [comment]
Mine is a Flatpak, it was the work of a moment to upgrade it through the Ubuntu's Software centre. A quick check suggests that the problem has been fixed.
