### ISSUE TITLE
Feature Question: [Gmail-like] Using notes as labels, ie. notes having multiple parents + Bonus: narrowing search to a subtree, etc.

### ISSUE THREAD

**Issue by deskobj** [giuspen/cherrytree#474]
Hi Guiseppe,

### Introduction ###

I know this is reaching far from the current implementation, since the current design imposes that every note has *at most* one parent. I also realize that there is already the possibility of using links and anchors, so you could argue that this is not adding value, but please bear with me, because I think hierarchies are a thing of the past and labels are the future.

### Question ###

Couldn't every note be considered as an eventual "label" and notes being able to have more than one parent ( ie. appear in multiple places in the hierarchy, including in a default root note called "All Notes" ). 

I think of it a bit like the Gmail labeling and storage systems work, except their labels are "a thing" on their own; it's not emails that are labels to other emails...

Optionally, a note/label called "Orphan Notes" could be implemented.

### Remarks ###

I see a couple benefits to that.

1/ The most obvious one being straight-forward implementation(s) of "views" (ie. show only the notes below a certain note), 1BIS/ search domain (ie. search only notes below a given note, which would make search results more accurate and also faster).

2/ Most of all, stop having headaches about what is the right hierarchy/folder structure, by just having a multiple parents for a given note.

### Additional considerations ###

3/ If successful this feature would probably render "Bookmarks" obsolete.

4/ Anchors and Links to internal notes would still have their own usage though (as a "loose reference" instead of the "strong reference" implied by the new parenting system).

Please note that I am not asking for the feature. I would first like to know your thoughts about it.

Thanks,
Looking forward to hearing from you.

Pino.

**Comment by pinodev** [comment]
PS: Sorry, mixed up my Github accounts. ( in case it happens again PinoDev = deskobj, same person. apologies about any incurred confusion, now and ever ) .

**Comment by giuspen** [comment]
Hi, it is in the wishlist to have multiple nodes pointing to the same content, new features though will have change to be implemented only after and in the new C++/gtk3 version

**Comment by deskobj** [comment]
(y) cool thanks for the info.
