### ISSUE TITLE
Show Iterated Find/Replace Dialog Toggle Does Nothing

### ISSUE THREAD

**Issue by Renrag01** [giuspen/cherrytree#482]
When using the "Replace in Current Node" option, unchecking the "Show Iterated Find/Replace Dialog" checkbox does not prevent the Dialog from displaying after replacing.

**Comment by giuspen** [comment]
Worked for me, please list all the dialog ticks you are using

**Comment by Renrag01** [comment]
Nevermind, I can't seem to get it to do it again.
