### ISSUE TITLE
How do I use tabs in lists?

### ISSUE THREAD

**Issue by arcandio** [giuspen/cherrytree#487]
How do I set CherryTree to use Tabs instead of spaces in lists? I hit the tab key and I get 3 spaces before the bullet, instead of 2, 4, or a tab. I get a normal tab when I hit tab outside of a list in a rich text node, so I just want it to match what it's doing elsewhere, since I'm trying to write a markdown parser for CTD documents.

![image](https://user-images.githubusercontent.com/2172188/56162850-8c95c400-5f92-11e9-8f9f-ebeeb8c181e8.png)

**Comment by giuspen** [comment]
Unfortunately the lists work only with spaces currently
