### ISSUE TITLE
Text Editing Keyboard Commands

### ISSUE THREAD

**Issue by ColeWunderlich** [giuspen/cherrytree#489]
Is there documentation anywhere for the keyboard commands when editing text?

I am looking for things like jump to end of line, jump to beginning of line, jump to next word, ect.

**Comment by tunbridgep** [comment]
Almost all of the keyboard shortcuts for text (bold etc) are listed on the tooltip, and menu items (insert timestamp etc) are listed on the right side of the menu item. Is that what you were asking?

Now I just wish I could use vim keys... ;)
