### ISSUE TITLE
Question about update and suggestions

### ISSUE THREAD

**Issue by alfredoivan** [giuspen/cherrytree#49]
Hi,
i currently have cherrytree 0.35.2 ( and really like the program ! )
And want to update to the latest version, which i think is 0.35.8

How is the recommended way of doing it?
I would suggest if it could be done from the program interface, by entering the form ""Check newer version" , it would ask you if you want to update and so download latest version and auto-install it , it would be great for non-expert linux users.

Additional info:
This is from my terminal:

``` bash
whereis cherrytree
cherrytree: /usr/bin/cherrytree /usr/bin/X11/cherrytree /usr/local/bin/cherrytree /usr/share/cherrytree /usr/share/man/man1/cherrytree.1.gz
```

**Comment by giuspen** [comment]
Hi, it is not simple to directly/personally support all linux distributions.
I recommend upgrading to 0.35.8 since many bugs were fixed.
If you are using any debian derivative like ubuntu or mint just dounload
the .deb and double click to install.

**Comment by EPeterR** [comment]
for openSuSE (13.2) 
1. if not available install **alien** (a perl script to convert packages) by openSuSE one click install 
(https://software.opensuse.org/ymp/utilities/openSUSE_13.2/alien.ymp?base=openSUSE%3A13.2&query=alien)
2. download the current CherryTree *.dep package
3. open a shell
```bash 
your_shell_prompt> cd to/your/download/folder
your_shell_prompt> sudo alien -rc cherrytree_<version>_all.deb
root's password: <enter the password>
cherrytree-<version>.noarch.rpm generated
your_shell_prompt> sudo zypper in cherrytree-<version>.noarch.rpm
```
*[zyppers output in shell snipped]*
Start CherryTree from the main menu and check that the version number has changed.

**Comment by Heart1010** [comment]
Or use the GNOME:APP Repo
1) http://software.opensuse.org/package/cherrytree
2) Click "Show other versions"
3) Click "Show unstable packages" in openSUSE 13.2 section
4) Click "1 Click Install" (on Firefox/Konqueror Browser) to install/add the GNOME:APP Repo
