### ISSUE TITLE
Part of the password exposed

### ISSUE THREAD

**Issue by alpererm** [giuspen/cherrytree#490]
Hi,
I have a password protected cherrytree file. I am using version 0.38.8 on a Linux machine. Whenever I enter the password, a new file is created at the same folder with the cherrytree file. The name of this new file is the last 4 characters of my password. It does not have any extension. The original file type was XML (ctz). I saved it as SQLite (ctx) and tried again. Same thing happens for both.

The contents of the created file are as follows:

> 7-Zip (a) [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,4 CPUs Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz (206A7),ASM,AES-NI)

>Scanning the drive for archives:
1 file, 496098 bytes (485 KiB)

>Extracting archive: /home/karusel/Documents/kalem foto/Bilinc.ctx
--
Path = /home/karusel/Documents/kalem foto/Bilinc.ctx
Type = 7z
Physical Size = 496098
Headers Size = 146
Method = LZMA2:16 7zAES
Solid = -
Blocks = 1

>Everything is Ok

>Size:       1036288
Compressed: 496098

**Comment by giuspen** [comment]
The password protection is achieved via the tool 7za command line binary, part of p7za-full package on Debian based Linux distributions.
I would be very surprised that 7za exposes your password but if that is the case, an issue is to be raised against p7zip.

**Comment by jdsys271** [comment]
> The name of this new file is the last 4 characters of my password

This might be because you were using a special char > 4 chars before > redirecting it to stdout.
i raised a new issue. referenced above.
