### ISSUE TITLE
Monospace font for plain text in codebox 

### ISSUE THREAD

**Issue by akwala** [giuspen/cherrytree#492]
This would be useful for code in a language for which syntax highlighting is not (yet) available. For such code, Plain Text is the only applicable value of the "Type" property of the codebox. I can't think of a use case in which text in a codebox needs to be anything but monospace. If there is use for this text to be non-monospace, then there needs to be an option to make it monospace.

**Comment by giuspen** [comment]
Maybe the plain text inside of the codeboxes should use the configured code font rather than the cinfigured plain text font

**Comment by akwala** [comment]
> Maybe the plain text inside the codeboxes should use the configured code font rather than the configured plain text font

This makes sense. +1
