### ISSUE TITLE
Feature Request: Option to disable automatic list recognition

### ISSUE THREAD

**Issue by chumbalum** [giuspen/cherrytree#500]
Hello,

I often use dash when I make some notes but unfortunately, cherrytree will interpret some dashed stuff as lists and makes simple editing somewhat annoyoing.

For example if you make notes about a table and use dashes in some rows, the following behaviour occurs. In the first example, the list gets intended another level. In the second example, a new list item is added, though it's not intended to have a list there in the first place.

![grafik](https://user-images.githubusercontent.com/486034/57126389-1e704000-6d8d-11e9-8bb8-889ef00220eb.png)

So it would be nice to have an option in the settings to disable the automatic list recognition

**Comment by giuspen** [comment]
I'll have a look, may add the option in the config.cfg file to be edited manually

**Comment by chumbalum** [comment]
Ok, thanks for your reply. Would be a helpful feature

**Comment by giuspen** [comment]
There is a simple solution to this problem.
You can remove the hyphen character "-" from the bullet list characters.
In config.cfg, after ensuring cherrytree is not running, look for:
`chars_listbul = •◇▪-→⇒`
and remove the hyphen or replace it with another character of your choice, save and start cherrytree.

**Comment by chumbalum** [comment]
Hi. Thanks for the hint, it's working :) I'll close this issue
