### ISSUE TITLE
[Feature] - Tag name as link to another tag/file/web page

### ISSUE THREAD

**Issue by SatarisGIT** [giuspen/cherrytree#502]
Hello!

I think about new feature in CT. 

Now - (it is very great feature) you can add link to webpage, file, folder or any branch (optional - to branch with anchor) in any document but cant add this from tag (branch). 

I think thats will be great, when it would be possible to make link on left side bar menu (on branches). 
For example you can make branch name "google.com", and when you click on this - it will open webpage with href = google.com (or add some refs to files to make another cherryTree documents etc)

What do you think about it?

**Comment by giuspen** [comment]
Hi,
It is in the wishlist to have a node which is actually just pointing to another node without duplicating it. Implementing a "link node" as you wish could satisfy that request as well as offering the other link types support.

**Comment by SatarisGIT** [comment]
It will be great, thanks for answer!
