### ISSUE TITLE
Applying text formatting to table raises "No Text is Selected"

### ISSUE THREAD

**Issue by rjkantor** [giuspen/cherrytree#509]
When trying to apply bold, or underline to text in a table a warning dialog is displayed that says "No Text is Selected" and any textual change is reverted back.

**Comment by rjkantor** [comment]
When trying to apply bold, or underline to text in a table a warning dialog is displayed that says "No Text is Selected" and any textual change is reverted back.

**Comment by giuspen** [comment]
Rich text in table cells is not currently supported
