### ISSUE TITLE
PDF export - lacks hyperlinks

### ISSUE THREAD

**Issue by gwojcieszczuk** [giuspen/cherrytree#514]
When exporting to PDF notes containing hyperlinks (e.g. to external websites), none of the hyperlinks are exported as links in PDF file.

For example: if I have link in cherrytree named "search" which points to "https://www.google.com", after exporting such note into PDF, I will only see the word "search" which just plain text.

**Comment by giuspen** [comment]
Unfortunately this feature was missing from the library (gtk2), hopefully they added it in gtk3 or plan to add it in future so the implementation will be trivial. I may also consider using another pdf generator if this won't come available into gtk

**Comment by Onepamopa** [comment]
GTK3 fix for this should already be present in the latest version.

**Comment by daviddoret** [comment]
It would be great to have this feature quickly!

**Comment by txe** [comment]
It was implemented by @ForeverRainbow in #982. Use 0.99.4 C++ version to try it.
