### ISSUE TITLE
[Feature] Lazy loading!

### ISSUE THREAD

**Issue by SatarisGIT** [giuspen/cherrytree#515]
Hello! 

I have suggestion for feature(?) to make!

I'm using cherryTree A LOT. Writing to it mass infos (only text, no any images), and my cherryTree docs contains around 20kb in single file so I must separate some categories in another CT documents. If Im not doing it - saving document that cointains 20kb + data takes around 5-7 seconds. To someone who has ,,ctrl+s" tick when wrote only one dot this is very annoying : P

So, maybe creating some kind of "lazy loading" for large pages will be solution for this? Enabled feature will be store datas in separate files, and load it (and save it) in-time to that single files? Or putting some kind of "dynamic links" to cherryTree doc?

**Comment by tunbridgep** [comment]
In relation to this, I'd love if every save was actually a diff, with full saves being done every X diffs. Not only would this make saving a lot faster, it'd also make for some sort of version control as well.

**Comment by giuspen** [comment]
this is already implemented, just use the SQLite (ctb) instead of the XML (ctd)

**Comment by tunbridgep** [comment]
Yeah that works for me. I'd prefer a folder structure so that it works with
vimwiki and other stuff, but these are definitely good enough for version
control. My apologies, I totally forgot about the other format :o

**Comment by tunbridgep** [comment]
I've been using sqlite and it works fine. I have some large files embedded in my tree and everything loads great, but I'm not sure if embedded files are stored in the same way as notes.

**Comment by SatarisGIT** [comment]
Ah, my fault, SQLite works great, thanks
