### ISSUE TITLE
[Feature Request] Missing Dictionary

### ISSUE THREAD

**Issue by Skarfrael** [giuspen/cherrytree#519]
Hello!

Although I can see that my language is supported, it doesn't seem to be in the list of spell check languages. 

Since asking for it(Greek) to be added would be a bit of an over-specification, I think that the ability to adding custom/external dictionaries in order to be able to use as 'Spell Check Languages' would be a welcome solution to this problem if not more.

**Comment by giuspen** [comment]
you need to install the package hunspell-el
