### ISSUE TITLE
Remove the Formatting in read-only Node

### ISSUE THREAD

**Issue by seityaya** [giuspen/cherrytree#543]
There is a possibility to remove the formatting in read-only nodes! I think it breaks the logic of “Toggle Read Only” function. When I choose any other function, the following error appears: “The Selected Node Is Read Only”. If I click “Remove the Formatting from the Selected text”, this error doesn’t appear, and the formatting is removed. This is unacceptable.

https://www.giuspen.com/topic/remove-the-formatting-in-read-only-node/

**Comment by giuspen** [comment]
fixed thanks

**Comment by seityaya** [comment]
Thanks!
