### ISSUE TITLE
Cannot open password-protected .ctx file

### ISSUE THREAD

**Issue by jacen05** [giuspen/cherrytree#545]
Problem similar but not identical as #426 and #16. 
Create a new CherryTree document, save it as encrypted SQLite file (ctx).
The password contains special characters, but is accepted without further notice.
Cannot reopen it either with CherryTree (wrong password), 7z CLI (wrong password) or any archive manager (wrong password).
I'm using CherryTree 0.38.8 on Linux.
The problem can be reproduced setting the minimal password "$$" (2 characters).

Any solution to access my encrypted notes?

**Comment by giuspen** [comment]
I added the $ as excluded char for current pygtk2 version. All the special chars will be ok/usable in the future gtkmm3 version. If you set the dollar as a password and the command didn't give error it means the dollar was replaced from your shell with a variable whose name is $following_chars so just try to omit in the password all characters from dollar onwards

**Comment by jacen05** [comment]
So the password string is interpreted by the software?

Unfortunately for me, the variable "$$" in bash has a special meaning, it contains the current PID.
As I have no way to know what was the PID of the CherryTry instance at the time I created the password, all I had left was to brute-force it.

For anyone else who is stuck in this situation:
- Download and compile [john-jumbo](https://github.com/magnumripper/JohnTheRipper)
- Use 7z2john.pl (in john/run/) to extract 7z hash: `perl ./john/run/7z2john.pl  ct.ctx > ct_hash_john.txt`
- Use john with hybrid mask: `./john/run/john --mask='?w?d?d?d?d?d' --wordlist=./begin.txt ct_hash_john.txt`

You can also use [7z2hashcat](https://github.com/philsmd/7z2hashcat) and hashcat, but only if file is not too big (hashcat limitation).

Using this method I was able to get my CherryTree notebook back in less than an hour.

**Comment by radegand** [comment]
I think there might still be issues with $ character in password. I come across this issue in 0.39.4 after creating a sqlite password protected file. I'm unable to open the file despite providing correct password.
My password was like secretstring_somedigits$ and I've tried cracking the has with john using both 'secretstring_somedigits$' as well as 'secretstring_somedigits', but no joy.
Does anyone have any pointers what the $ could be translated to?
Oh, and the UI never said anything to me about using the $ character in the passphrase...
Thanks in advance!

**Comment by MrP-cpu** [comment]
> So the password string is interpreted by the software?
> 
> Unfortunately for me, the variable "$$" in bash has a special meaning, it contains the current PID. As I have no way to know what was the PID of the CherryTry instance at the time I created the password, all I had left was to brute-force it.
> 
> For anyone else who is stuck in this situation:
> 
>     * Download and compile [john-jumbo](https://github.com/magnumripper/JohnTheRipper)
> 
>     * Use 7z2john.pl (in john/run/) to extract 7z hash: `perl ./john/run/7z2john.pl  ct.ctx > ct_hash_john.txt`
> 
>     * Use john with hybrid mask: `./john/run/john --mask='?w?d?d?d?d?d' --wordlist=./begin.txt ct_hash_john.txt`
> 
> 
> You can also use [7z2hashcat](https://github.com/philsmd/7z2hashcat) and hashcat, but only if file is not too big (hashcat limitation).
> 
> Using this method I was able to get my CherryTree notebook back in less than an hour.
![2022-01-18_17-08](https://user-images.githubusercontent.com/81713318/150026546-9a844e44-6420-44aa-af02-5cf5f2137f76.png)

hello sir i am getting error of zsh permission denied even though i am through root

**Comment by giuspen** [comment]
The new Gtkmm3 cherrytree (versions 0.99.x+) have no limitation to the characters in the password, this issue is no longer relevant
