### ISSUE TITLE
Compatibility with Debian 10

### ISSUE THREAD

**Issue by tkoeck** [giuspen/cherrytree#556]
Does have problems with Debian 10 aka buster.

**Comment by tenwalls** [comment]
Assume this relates to gtkmm3 compatibility?

**Comment by giuspen** [comment]
https://www.giuspen.com/cherrytree/#downl
NOTE: Debian stable does not have python-gtksourceview2; install the oldstable manually from https://packages.debian.org/stretch/python-gtksourceview2 (new gtkmm3 version coming soon…)

**Comment by vwas2** [comment]
gtk is suppored, but another dependency jumped past buster to bullseye, backport not avail;
https://github.com/giuspen/cherrytree/issues/1035#issuecomment-742790876

**Comment by vwas2** [comment]
buster clone and ./build.sh 
```
CMAKE_BUILD_TYPE=Debug
-- CT_VERSION = 0.99.25
Tests are ON
-- Checking for module 'glibmm-2.4>=2.64'
--   Requested 'glibmm-2.4 >= 2.64' but version of glibmm is 2.58.0
You may find new versions of glibmm at http://www.gtkmm.org/
CMake Error at /usr/share/cmake-3.13/Modules/FindPkgConfig.cmake:452 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.13/Modules/FindPkgConfig.cmake:622 (_pkg_check_modules_internal)
  CMakeLists.txt:101 (pkg_check_modules)


-- Configuring incomplete, errors occurred!
```

**Comment by giuspen** [comment]
The current git code / upcoming 0.99.38 builds on Debian 10 and Ubuntu 18.04
