### ISSUE TITLE
Should switch to Python 3

### ISSUE THREAD

**Issue by Gamb1ts** [giuspen/cherrytree#558]
Python 2.x will no longer be supported by their upstream developers in 2020. Thus Debian developers are actively removing Python 2 support in Debian Testing with the goal of getting rid of Python 2 in Debian 11 (bullseye). Kali is tracking Debian Testing and is thus affected by this.
You should consider to switch cherrytree to Python 3.

**Comment by giuspen** [comment]
Porting is ongoing to gtkmm3

**Comment by marado** [comment]
For reference, this is a duplicate of #405 .
