### ISSUE TITLE
*.ctb write failed - writing to disk

### ISSUE THREAD

**Issue by EmbeddedBacon** [giuspen/cherrytree#559]
Hello,

  I am running CherryTree on MX Linux v18.3.  I have a Synology NAS box that connect/accessed by using the File Manager.  In the address bar the path of the mount is afp://user_name@server.local/Media/MyFiles/CherryTree.

  When attempting to write the database to the path listed above I get the following error message

/run/user/1000/gvfs/afp-volume:host=server.local,user=x,volume=Media/MyFiles/CherryTree/CherryTree.ctb write failed - writing to disk

  I can save the database to my HOME directory then using the File Manager I now can save it to NAS box.  I can even open it from NAS location.  Why can't CherryTree save directory to the NAX box?

Regards,
Mark

**Comment by giuspen** [comment]
The current python2 sqlite implementation is known to have this issue; the future upcoming C++ version should support this. For now if you need to work with the NAS use the xml document type

**Comment by EmbeddedBacon** [comment]
@giuspen , okay, not sure what the "xml document type" is right now, but I will look into it.  Thanks.

**Comment by giuspen** [comment]
@EmbeddedBacon just save as and choose XML instead of Sqlite as document type

**Comment by Mani0386** [comment]
Das Problem habe ich heute nocht, es muss doch eine Möglichkeit geben dieses Problem zu lösen, XML ist als größere Datei viel zu langsam.
