### ISSUE TITLE
Edit >> Insert Special Character: Two capital sigmas, no small sigma

### ISSUE THREAD

**Issue by DiagonalArg** [giuspen/cherrytree#563]
As it says.  Version 0.38.9

Thanks for your work!

**Comment by giuspen** [comment]
If you want to add a missing special character write it here like this: 'a'

**Comment by DiagonalArg** [comment]
Sorry.  Write it where?  I mean, are you telling me that there's some way to add it to the Edit >>> Insert Special Character menu?

**Comment by giuspen** [comment]
No, copy and paste the characters you want info this github issue

**Comment by DiagonalArg** [comment]
You have two of these: Σ

One of them should be this: σ

In other words, change one of the capital sigmas to a small sigma.
