### ISSUE TITLE
Slowdown in certain nodes ?

### ISSUE THREAD

**Issue by Zip-Acna** [giuspen/cherrytree#565]
Hello,

I started using cherrytree not too long ago and I'm noticing some pretty serious slowdowns on nodes, meaning things like just moving the cursor around get pretty slow.
It's not all the nodes, but those with more stuff in them (text, a few screenshots and codeboxes), not really that much though, like the one I'm using now to take notes about a book is about 720 lines of text, 20-25 screenshots and a few codeboxes.

I'm using v37.6 on ubuntu 18.04

Other than that the program is pretty nice, so thanks for that.

**Comment by giuspen** [comment]
Hi, please add cherrytree ppa so you will run the latest version, see giuspen.com/cherrytree for that. Soon the new cherrytree will be much faster anyway being ported from python to C++

**Comment by Zip-Acna** [comment]
> Hi, please add cherrytree ppa so you will run the latest version, see giuspen.com/cherrytree for that. Soon the new cherrytree will be much faster anyway being ported from python to C++

Okay, will try that, thank you.
