### ISSUE TITLE
Prettyprint XML

### ISSUE THREAD

**Issue by phoe** [giuspen/cherrytree#568]
I would like to store my story in a Git repository to track its state over time. For that, I would like to use the XML formatting, but the file resulting from saving the empty story as XML only has one line. I would request for the XML to be pretty-printed (newlines + indentation) on save, so Git can properly recognize changed/added lines in the story.

**Comment by giuspen** [comment]
I'm already pretty printing, what version are you using?

**Comment by phoe** [comment]
Welp. This was an older version from Ubuntu 16.04. I checked on debian sid and you are correct.

Thanks and sorry for the trouble!
