### ISSUE TITLE
Fedora 31 does not ship cheerytree anymore

### ISSUE THREAD

**Issue by asias** [giuspen/cherrytree#581]
After upgrading to fedora 31, I sadly found cheerytree is not provided by fedora 31. It is probably due to pygtksourceview is missing. 

Any suggestions to workaround this?

**Comment by EllieBorden** [comment]
### How to Run Cherrytree in Fedora 31:
1. Install Dependencies 
`sudo dnf install python2 python2-devel pygtk2 p7zip p7zip-plugins`

2. Download pygtksourceview
`wget http://download-ib01.fedoraproject.org/pub/fedora/linux/releases/30/Everything/x86_64/os/Packages/p/pygtksourceview-2.10.1-18.fc29.x86_64.rpm`

3. Install pygtksourceview
`sudo dnf install pygtksourceview-2.10.1-18.fc29.x86_64.rpm`

4. Clone Cherrytree
`git clone https://github.com/giuspen/cherrytree.git`

5. Run Cherrytree 
`./cherrytree/cherrytree`

**Comment by asias** [comment]
I got this: 
```
$ sudo dnf install pygtksourceview-2.10.1-18.fc29.x86_64.rpm
Last metadata expiration check: 11:00:39 ago on Wed 30 Oct 2019 10:08:10 PM CST.
Dependencies resolved.

 Problem: problem with installed package fedora-obsolete-packages-31-34.noarch
  - installed package fedora-obsolete-packages-31-34.noarch obsoletes pygtksourceview < 2.10.1-19 provided by pygtksourceview-2.10.1-18.fc29.x86_64
  - package fedora-obsolete-packages-31-34.noarch obsoletes pygtksourceview < 2.10.1-19 provided by pygtksourceview-2.10.1-18.fc29.x86_64
  - conflicting requests
Nothing to do.
Complete!
```

I have to run:
```
sudo dnf remove fedora-obsolete-packages-31-34.noarch
```
to workaround this.


@EllieBorden Thanks for the tips!

**Comment by funnelfiasco** [comment]
For anyone else who may happen upon this, I have cherrytree available in a COPR repo for Fedora 31: https://copr.fedorainfracloud.org/coprs/bcotton/cherrytree/

**Comment by dodona2** [comment]
thanks a lot!

**Comment by EllieBorden** [comment]
@funnelfiasco 
Thanks for setting this up!
Mind if I reference your repo in Cherrytree's user manual? Will you leave it up until the Gtkmm port is released?

**Comment by funnelfiasco** [comment]
@EllieBorden absolutely! I plan on keeping it actively maintained, since I use Cherrytree on a daily basis.

When I have some time, I'll try to get the future build packaged in the same repo and then bring that into the official repo when it's ready for release.

**Comment by dodona2** [comment]
thanks a lot  funnelfiasco! You made my day!

**Comment by Vik-Geerawor** [comment]
thank you...!
