### ISSUE TITLE
[Feature request] Export to PDF in command-line

### ISSUE THREAD

**Issue by phoe** [giuspen/cherrytree#584]
Currently, CherryTree only seems to be able to export to TXT and HTML from command line:
```
$ cherrytree --help
usage: cherrytree [-h] [-n NODE] [-x EXPORT_TO_HTML_DIR]
                  [-t EXPORT_TO_TXT_DIR] [-w]
                  [filepath]
```
I would like to utilize cherrytree in my CI environment to produce PDFs of my book whenever I update the related Git repository. For that, I would need a command-line API to be able to access the PDF export facility.

**Comment by giuspen** [comment]
I added the option, can you test the latest from GitHub master?

**Comment by phoe** [comment]
Yes, the export works for me on current git master.

An issue is that the exported PDF does not respect the paragraph spacing and inter-line spacing set in CherryTree, but that, I think, is material for another issue.

**Comment by giuspen** [comment]
Yep cannot work on improving the PDF in pygtk2, we'll get back after gtkmm3 porting is done

**Comment by phoe** [comment]
I'll close this one for now, then. Thank you!
