### ISSUE TITLE
[0.38.9] Smart quotes clashes with spellchecking

### ISSUE THREAD

**Issue by phoe** [giuspen/cherrytree#585]
If I allow CherryTree to autoconvert quotes to smart quotes, the first word is then marked by the spellchecker along with the opening quotation mark.

![Zrzut ekranu z 2019-11-05 18-00-08](https://user-images.githubusercontent.com/15045546/68228732-3fdd0d80-fff6-11e9-9d0e-12915750353d.png)

**Comment by letto4135** [comment]
Anyone going to close this one? Was fixed 6 months ago

**Comment by txe** [comment]
I checked pygtk and C++, there is no issue. Thanks for fixing it in pygtk!
