### ISSUE TITLE
Ctrl+C, Ctrl+V issue

### ISSUE THREAD

**Issue by Filyus** [giuspen/cherrytree#586]
Keyboard shortcuts for working with the buffer stop working after several days of using the program. Shortcuts don't work even inside dialog boxes. Only reinstalling the program helps.

OS: Windows 10.
cherrytree: 0.38.9

**Comment by Filyus** [comment]
cherrytree 0.38.11 There is still a problem. Thank god, reinstallation helps.

**Comment by teamplay7** [comment]
Any news? The last version 0.39.4 still has the same problem! :(

**Comment by giuspen** [comment]
Please test our development version 0.99.3 go to https://www.giuspen.com/cherrytree/#downl and scroll down

**Comment by txe** [comment]
Closing, 0.99 doesn't have such issue on win.
Cherrytree 0.38 cannot be fixed because it's caused outdated gtk2,
