### ISSUE TITLE
HiDPI resolution icons too small

### ISSUE THREAD

**Issue by djbajic** [giuspen/cherrytree#589]
Hi, I'm using Linux mint and cinnamon desktop, and I'm having an issue with my high-resolution screen (3840x2160). The icons look extremely small. This seems to be still an issue in Mint in general, but I've managed to get most of my software to have an acceptable icon size. Not Cherrytree though. Do you know what could be the solution and whether this will get fixed at some point? 

Thanks!

**Comment by EllieBorden** [comment]
Not sure if this will completely solve your problem, but in the meantime, you can increase the size of a few elements within Cherrytree. 

- To increase the size of toolbar icons, click View > Increase Toolbar Icon Size.
- To increase the size of text within the treeview, hover over the treeview with your cursor, then hold CTRL and scroll with your mouse wheel. 
  - This works for text within the editor too if you hover over the editor.
- To increase the size of embedded file icons, edit the 'Edit > Preferences > Rich Text  > Embedded File Icon Size' setting.

**Comment by djbajic** [comment]
cool, thats pretty much enough to be able to work!
