### ISSUE TITLE
At a random moment in time, changes since the last save are lost and the program 'flicks' to a different place in text or node.

### ISSUE THREAD

**Issue by p9malino26** [giuspen/cherrytree#597]
### Description of issue and how to reproduce

Hi,

I have enjoyed using CherryTree for a few months now but there is an issue which really bogs me: I open a document CherryTree, make some edits and after a random amount of time (~7 minutes), the changes that I have made since the last save of the file are lost and the editor goes to a completely different, random place in my project (sometimes the same node that I was in before, sometimes a different node). This keeps repeatedly happening and I cannot press CTRL-Z to undo the effect and this sometimes causes me to lose a lot of work and I am heavily reliant on this program for using it to to work on my notes for university because apart from this issue, I really love it.

### Platform details

Operating system: Manjaro Linux 18.1.3 (Juhraya), XFCE desktop
Kernel: 5.3.11-1-MANJARO
Python2 version: 2.7.12

### Additional information

* The same thing happens on my other Chromebook laptop, running exactly the same operating system, kernel and Python version.
* This program depends on GTK Sourceview, which I've had to install from the AUR.

**Comment by giuspen** [comment]
Please try and disable "Reload After External Update to CT* File" preferences, tab miscellaneous http://giuspen.com/cherrytreemanual/#_miscellaneous_5

**Comment by giuspen** [comment]
related to #602
