### ISSUE TITLE
Index tree in html output does not work as expected

### ISSUE THREAD

**Issue by vivasteve** [giuspen/cherrytree#599]
Hello Giuseppe, I am using cherrytree to build a family tree - it works really well to produce a page about each person and to arrange pages in a tree. Now I would like to export as html for sharing with others. html export works very well (0.38.9 on manjaro) except for one thing - the index on the html pages is a bit buggy:
- the tree is always expanded
- if you scroll down the tree and click an item low down, the content appears in the right pane as expected, but the tree scrolls back to the top again  - would be great if the tree stayed put like it does in cherrytree

ps great that a small style sheet is produced, for tweaking styles

**Comment by txe** [comment]
Second part was done in #636
@ksmukta, can you consider fixing the first part as well?

**Comment by ksmukta** [comment]
Sure, will do it this weekend.

**Comment by txe** [comment]
Great, thanks!

**Comment by ksmukta** [comment]
First part done in #648 
Now the tree is exported in collapsed form and user can expand/collapse nodes like in cherrytree.

**Comment by vivasteve** [comment]
just updated to latest master ... behaviour is strange - first part is definitely fixed
but now body text appears in a small frame
if I click expand button it just toggles between + and - symbol, but no expand/collapse happens ...

![image](https://user-images.githubusercontent.com/19339496/75081207-424a7f80-5573-11ea-9a57-51c08e7fc18e.png)

tried in firefox and vivaldi

**Comment by ksmukta** [comment]
Hi @vivasteve try to delete older styles.css file from your cherrytree config folder. Does it resolve the styling issue?

**Comment by txe** [comment]
Hmm, it's inconvenient. So, it looks like the code should replace the old css in a cherrytree config folder when it is not changed by user.  To find out if it is the same or not, we can calculate hash (crc32/md5) of the file and compare the result with a reference hash.

**Comment by vivasteve** [comment]
@ksmukta YES! issue is resolved - I guess the old styles.css in .config/cherrytree was combining with the styles.css in git-cherrytree. Now it works perfectly - thanks, beautiful work! I think the problem won't happen for someone who only uses latest stable version - thanks for the great work - this will be really useful for me

**Comment by ksmukta** [comment]
@txe 
Is this kind of thing handled in upgrades? Like if we upgrade cherrytree(on next version release), will it replace the older files with new files?

**Comment by txe** [comment]
Although, I'm still thinking about the user changed css. We will not  know if it's based on the new or old css. To fix it, we can rename the css file like version 2. So the modus operandi will be:
- use a new file name and use it html
- remove an old css from config folder if it's unchanged
- give users a warning that their old css is old and not working

**Comment by txe** [comment]
Or a simpler solution: just use a new css name and don't bother with the old one.

**Comment by txe** [comment]
> @txe
> Is this kind of thing handled in upgrades? Like if we upgrade cherrytree(on next version release), will it replace the older files with new files?

Installer will not replace files in user config folder, the code handles [this](https://github.com/giuspen/cherrytree/blob/21c8e645572ac756af512cea39fba82b391d48c5/modules/exports.py#L593).

**Comment by vivasteve** [comment]
Thanks all for taking care of this

**Comment by vivasteve** [comment]
@ksmukta YES! issue is resolved - I guess the old styles.css in .config/cherrytree was combining with the styles.css in git-cherrytree. Now it works perfectly - thanks, beautiful work! I think the problem won't happen for someone who only uses latest stable version - thanks for the great work - this will be really useful for me

**Comment by giuspen** [comment]
Thanks @txe @ksmukta I'll rename the .CSS before the release
