### ISSUE TITLE
Image handling in PDF export - blurry jpg/png

### ISSUE THREAD

**Issue by kiweegie** [giuspen/cherrytree#60]
I've noticed that images in nodes when exported to PDF format show quite blurry. I normally use PNG format in nodes due to the screencapture apps I use under both Linux (Shutter) and Windows (Screenpresso).

As a test I downloaded a test image in .bmp, .gif, .jpg and .png format, added to a test node and then exported to PDF.

The .gif and .bmp images came out quite clear. The .jpg and .png images came out blurry. Is this expected behaviour? Should I default to saving my screengrabs in .gif/.bmp?

The image clarity within the node itself is absolutely fine. Also exporting to html results in perfect image quality.

regards, Kiweegie.

**Comment by h4k4t4k** [comment]
I, too, have experienced this issue.  I use screenshots extensively in CherryTree.  It seems to be related to the width, or perhaps overall size of the image.  I use gnome-screenshot and just copy the captures from the clipboard into CherryTree.  If the screenshot is the full width of my display, then the resulting export's resolution is decreased to the point that text is illegible.  I did verify that it doesn't matter whether the image is copied from the clipboard or saved as a png and then inserted.

Thank you for this awesome application.  Your hard work is very much appreciated.
Kind regards,
H4k4t4k

**Comment by jalmeida** [comment]
I have experienced same "problem" when exporting to PDF.  I tried other workaround as to print directly to PDF and to export to HTML and then print into PDF, but they are not working as expected. 

Thank you for this great application, it's something i use daily.
