### ISSUE TITLE
[Feature-Request] add copy format functionality?

### ISSUE THREAD

**Issue by waynongithub** [giuspen/cherrytree#600]
Hi, I haven't found a way to copy formatting in Cherrytree like one does with the brush icon in most word processors. With F7 i can copy/paste the last applied formatting, but not the entire formatting of the selected text.
Thus, to copy the formatting of a blue, bold, italic text I have to first copy blue, then copy bold, then copy italic. 
Would it be possible to add "copy formatting" so I can copy blue, bold, italic in one go? Or if the functionality already exist, can you show where it is, because I can't seem to find it (in 0.38.8)?
Thanks
And thanks for cherrytree!

**Comment by LachlanB96** [comment]
Seems like a bug with copying rich text.
Maybe a work around you could use is <control> + D
This duplicates the row, and the formatting within. Sorry I couldnt find a better solution. I'll look into the code :)

**Comment by waynongithub** [comment]
Hi, 
I don't think there's a bug, copying rich text works fine! When I copy a bold, blue, italic text, it will paste as a bold, blue, italic text, no problem there. But what I cannot do is copy bold, blue, italic text and paste only the formatting to another text to make it bold, blue, italic. Like you said, I have to copy the original text, paste it, then edit the pasted text.
There doesn't seem to be a bug in F7 either, it does exactly what it says it will do: it copies only the last formatting to a new text. So when I make a text bold, blue, italic, using F7 will only apply italic formatting to the new text, it will not apply the blue and bold formatting. The functionality that I was suggesting is the ability to copy the entire formatting, just like the brush-icon does in word processors: select a bold, blue, italic text > click the brush icon > select some other text > now the new text is also bold, blue, italic, not just italic.

**Comment by 00011100** [comment]
Just came in here to check up on this request. I too would love to see a _copy format_ button! 

Honestly this is the only thing that I can think of that this application is truly missing. The F7 for last format action is great, but sometimes you need to hop around and copy. It makes the workflow much faster!

**Comment by giuspen** [comment]
Will be in 0.99.31
