### ISSUE TITLE
[bug] Jumping cursor if the ctb is saved on a network drive

### ISSUE THREAD

**Issue by BurtGummer** [giuspen/cherrytree#602]
Hello,

I save a new .ctb-file on a Windows network drive, mounted as letter X:. Its a new created, almost empty file. I have create this tree and "test4" is open/aktive:

- test1
- test2
- test3
- test4

then I wait some seconds and the cursor (the aktive/open tree) jump to a other tree, for example "test1". And if I not save the changes on "test4", the changes never saved. 

I have enabled and disabled autosave, no change and I'm the only user who open the file.

I have no idea how I can locate the problem. Any ideas?

System is Windows 10 (1809) and CherryTree 0.38.9.

And I have a other .ctb-file on my local harddrive, the problem does not exist there.

**Comment by giuspen** [comment]
preferences dialog, tab miscellaneous, disable "reload after external update to ct* file" - I'll change this to be disabled by default rather than enabled by default

**Comment by BurtGummer** [comment]
Hello Giuseppe,

thank you very very much!
