### ISSUE TITLE
38.10 breaks printing

### ISSUE THREAD

**Issue by walktown** [giuspen/cherrytree#605]
Was running 38.9 and upgraded to 38.10 and <File><Print> no longer works properly. No dialog pops up and when I exit cherrytree, an error dialog tells me to look in cherrytree.exe.log.

Traceback (most recent call last):
  File "core.pyc", line 2234, in export_print
TypeError: 'gtk.Action' object has no attribute '__getitem__'

38.9 still works. My environment is Windows Pro (7 and 10) and the portable version of cherrytree.

**Comment by giuspen** [comment]
I will check soon...

**Comment by giuspen** [comment]
Released 0.38.11 thanks
