### ISSUE TITLE
"search for new version" is a dead button

### ISSUE THREAD

**Issue by MJimitater** [giuspen/cherrytree#613]
Clicking on _Help_ -> _search for new version_ doesn't do anything.

**Comment by giuspen** [comment]
It's not very intuitive but if there is a new version there will be an info dialog, otherwise there is just a message in the status bar

**Comment by MJimitater** [comment]
Oh yes, now I get it! Thanks :)

Btw, I love your diligent work, I use CherryTree every day!
Im grateful how you and @txe pushed forward so much quality work! Actually I wrote @txe an email asking where he is, because I loved his contributions!

**Comment by giuspen** [comment]
I agree, @txe has been doing an incredible work
