### ISSUE TITLE
[feature request] middle mouse button paste

### ISSUE THREAD

**Issue by Groberen** [giuspen/cherrytree#618]
On Linux OS, it would be great if CT supported text paste by mouse middle-click (standard Linux).

**Comment by singularis-mzf** [comment]
I'm using CherryTree 0.38.8 (downloaded as deb-package from [web](https://www.giuspen.com/cherrytree/) on Ubuntu 18.04 and it already supports it, even when I select a text in the node I can paste it to another place in the same node. (It works only on text; pictures get ignored, but for them you can use regular clipboard Ctrl+C/Ctrl+V.)

**Comment by giuspen** [comment]
Worksfor me too on 0.38.11 mint cinnamon latest

**Comment by Groberen** [comment]
Ok, strange. I use 0.38.9 on Fedora 31 Desktop (Chinnamon installed afterwards) and I can't get it to work.

**Comment by txe** [comment]
In my case, middle mouse button paste doesn't work for CT 0.38 if the text is copied from the same node. If the text is from another program, there is no issue.
0.38 is obsolete, 0.99 (testing) doesn't have this issue, so closing.
