### ISSUE TITLE
Two bugs for the CherryTree portable version

### ISSUE THREAD

**Issue by epikgit** [giuspen/cherrytree#64]
I download the cherrytree_0.35.10_win32_portable.7z version, unpack it and create the empty file config.cfg inside the bin folder.

1) I execute the cherrytree.exe and in my Win10 machine an error popup.
In a Windows 8.1 machine nothing goes wrong.

2) Since I'm using CherryTree in a portable mode why when I close it, the process dbus-daemon.exe doesn't quit? It breaks the portability because I can't move the CherryTree main folder or detach my USB.

**Comment by giuspen** [comment]
Hello, yes you're right I should take daemon.exe down in the portable
version. I was not aware that windows 10 does not support windows xp
applications (actually cherrytree windows version is currently built for
xp) would you be available to test a version built for win7 to run properly
on win10?

**Comment by epikgit** [comment]
Sure I can, but I think that the problem is slightly different.
As I can read from the log the config.cfg doesn't contain a required header or something similar (I can't remember precisely because I have not the log in this moment).
It seems that the program during start up can't write its settings inside the config.cfg and consequently can't read them.

**Comment by giuspen** [comment]
Ok so it seems that there is no write access to config.cfg ... Were you
using cherrytree in portable mode on win10 with the config.cfg local to the
portable folder?

**Comment by epikgit** [comment]
You are right, it's a security issue.
I created config.cfg in elevated mode because my Explorer replacement always works in this mode.
Now, regardless the mode I run CherryTree, it doens't write its setting into the file. 
It can't successfully succeed in writing the settings not even if I run CT in elevated mode, that is odd.

This is the, now useless, log message:

Traceback (most recent call last):
  File "cherrytree", line 70, in <module>
  File "cherrytree", line 48, in f_main
  File "main.pyc", line 219, in main
  File "main.pyc", line 64, in __init__
  File "main.pyc", line 69, in window_open_new
  File "core.pyc", line 70, in __init__
  File "config.pyc", line 90, in config_file_load
  File "ConfigParser.pyc", line 305, in read
  File "ConfigParser.pyc", line 512, in _read
ConfigParser.MissingSectionHeaderError: File contains no section headers.
file: D:\Misc\Temp\cherrytree_0.35.10_win32_portable\bin\config.cfg, line: 1
'\xef\xbb\xbf'

If I can propose an improvement, don't take for sure that CT is able to write into the configuration file and, just in case, give a more exhaustive and user friendly message.

Do you think that this two issues could be solved with the next version?
Have you got a planned releasing date?

Thanks.

**Comment by giuspen** [comment]
Hi, I can make cherrytree survive the failure in reading/writing the
config.cfg but it's a pain to have cherrytree that all the times loses the
settings.
It would be great if you could run cherrytree from the python source code
as described in http://www.giuspen.com/cherrytree/#dev and tell me if it
works and, if not, what exact error you get on the terminal.

**Comment by epikgit** [comment]
Hi Giuseppe.
I've just downloaded and installed the 0.36.3 version of cherrytree and unfortunately the config.cfg bugs I previously reported is still here... but this time I have the solution.
I create the empty config.cfg file in UTF-8 and your application needs the ANSI version.
I don't know why your application absolutely needs the ANSI format but since you can't be sure what will be the encoding of an user create file, you should check it before trying to write something or you can create a system able to write the file in whatever encoding.
Let us know.

Ciao

**Comment by giuspen** [comment]
Hi there,
Unfortunately I've tried to generate the config.cfg in utf-8 and other encodings without being able to reproduce the issue.
Please send me a config.cfg that reproduces the issue for you. I'm not sure you can attach anything here, anyway you can find my email in cherrytree help--about dialog.
Can you also try in more than a windows installation to see if it is easily reproducible?
Cheers,
Giuseppe.

**Comment by txe** [comment]
The issue is not related to C++ version.
