### ISSUE TITLE
[Feature Request] linking to exiting notes

### ISSUE THREAD

**Issue by quesada** [giuspen/cherrytree#640]
Is there any way to get a unique id for a note? and link to it? This is very common in wikis/other notetakers. See zim, trillium.

**Comment by txe** [comment]
Something like [this](http://giuspen.com/cherrytreemanual/#_links)?

**Comment by benjithereborn** [comment]
i guess he men that he could link a howl Node

**Comment by txe** [comment]
Resolved by #944
