### ISSUE TITLE
alt-up alt-down line with strikethrough

### ISSUE THREAD

**Issue by ezagent** [giuspen/cherrytree#65]
Cherrytree 0.35.10
Ubuntu 15.04

When I reposition a line with strikethrough text using alt-up or alt-down strikethrough is applied arbirtrarily to passing lines. If I place a dash at the beginning of the line it is not affected. This does not alter all lines. It is an arbitrary bug, but it means I can't use strikethrough to indicate completion of a list item, then move the item to the bottom of a list without it affecting other lines in the process.

The dash at the beginning of the lines in my list is a workaround.

**Comment by giuspen** [comment]
I could not see the problem, please send me a cherrytree document as
example and tell me exactly what to do to reproduce the issue

**Comment by ezagent** [comment]
Can't do that. Only have one doc and it has data that I'm not going to
share. Sorry.

**Comment by giuspen** [comment]
No I'm sorry I explained badly, I don't want your private document but that
you create a new one-node document with the minimal data sufficient to
reproduce the issue. Cheers.

**Comment by ezagent** [comment]
I've attached screenshots. My notes are in the screenshots. My system is
Ubuntu 15.04, i7 yada yada.

--
Mike Collins
email: fastmoves@gmail.com
cell:* 617.299.Mike* | 6172996453
FREE Wordpress websites: bostonwebcrew.com

**Comment by ezagent** [comment]
from: Mike Collins
email: fastmoves@gmail.com
cell: 617.299.Mike | 6172996453
FREE Wordpress websites: bostonwebcrew.com
FYI: workaround remedies gmail signature hiding

I'm attaching a screenshot of text that triggers a bug in the version
released today. Maybe it's the special characters I'm using, but when I
Alt-Up on the bottom line the Year portion of the date picks up the H1
formatting.

**Comment by Bystroushaak** [comment]
![optimised](https://cloud.githubusercontent.com/assets/227282/10377558/3a7cd984-6e04-11e5-801a-b0ba011ab4a4.gif)

**Comment by Bystroushaak** [comment]
Here is the file: http://kitakitsune.org/bhole/asd.ctd

**Comment by Bystroushaak** [comment]
I have the same problem and not only with striked text, but with links too.

**Comment by Bystroushaak** [comment]
Also I think, that it may be related to #23, which also breaks the formating of surrounding elements.

**Comment by Bystroushaak** [comment]
I've sent you a donation. I know that it is not much and that it gives me no right to ask you to fix this bug, but I am really using this feature (and undo) a lot and it breaks my workflow.

**Comment by giuspen** [comment]
Please test the following version 0.35.11+r1650 and let me know if the bug is fixed
http://www.giuspen.com/software/cherrytree-0.35.11+r1650.tar.xz
http://www.giuspen.com/software/cherrytree_0.35.11+r1650-1_all.deb
http://www.giuspen.com/software/cherrytree_0.35.11+r1650_setup.exe
http://www.giuspen.com/software/cherrytree_0.35.11+r1650_win32_portable.7z

**Comment by Bystroushaak** [comment]
Nope, the bug is still present. I am using linux mint

    Linux 6horses 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ezagent** [comment]
![dash-no-dash](https://cloud.githubusercontent.com/assets/3991943/10411654/9bd120a0-6f3a-11e5-9d59-39ca20b2306b.png)

Same. When I Alt-Up the H1 text it works with the dash before the line with the date. Without the dash the year acquires H1 formatting (it breaks).

**Comment by giuspen** [comment]
Silly me.
Please test the following version 0.35.11+r1651 and let me know if the bug is fixed.
http://www.giuspen.com/software/cherrytree-0.35.11+r1651.tar.xz
http://www.giuspen.com/software/cherrytree_0.35.11+r1651-1_all.deb
http://www.giuspen.com/software/cherrytree_0.35.11+r1651_setup.exe
http://www.giuspen.com/software/cherrytree_0.35.11+r1651_win32_portable.7z

**Comment by ezagent** [comment]
The Alt-Up H1 test I tried above now passes. Thank you. Issue appears to be resolved.

**Comment by Bystroushaak** [comment]
It seems to be working correctly now. Thanks.

**Comment by Bystroushaak** [comment]
I think this issue may be closed now.
