### ISSUE TITLE
Question regarding 'Today's node'

### ISSUE THREAD

**Issue by Skarfrael** [giuspen/cherrytree#652]
Hello! 

OS: Manjaro - KDE Plasma

I am a non-native English speaker, so other than English I also have Greek in my system. More specifically:

- I have 2 keyboard layouts (1 eng-US and 1 el-GR) 

- and my locale is English for Display Language and Greek for Formats and time zone. 

When I click on to create 'today's node', month and day are written in Greek while I expected to be in English (or in the language that is in my active keyboard layout at the time). 

Is this a bug or expected behavior? 
Any tips to workaround it?

Cheers!

**Comment by txe** [comment]
It is expected, the locale for date formatting is taken from Formats which in your case is Greek.
You can change code to use another locale. On path `/usr/share/cherrytree/modules/core.py`, find and replace `def node_date`

```python
def node_date(self, *args):
    """Insert Date Node in Tree"""
    saved = locale.setlocale(locale.LC_TIME)
    locale.setlocale(locale.LC_TIME, "C")
    curr_time = time.time()
    now_year = support.get_timestamp_str("%Y", curr_time)
    now_month = support.get_timestamp_str("%B", curr_time)
    now_day = support.get_timestamp_str(self.journal_day_format, curr_time)
    locale.setlocale(locale.LC_TIME, saved)
    
    self.node_child_exist_or_create(None, now_year)
    self.node_child_exist_or_create(self.curr_tree_iter, now_month)
    self.node_child_exist_or_create(self.curr_tree_iter, now_day)
```

**Comment by Skarfrael** [comment]
Thanks for the helpful answer @txe! Temporarily setting locale time format to default is an interesting approach. 

Afaic, detecting the current layout (and use that instead of locale) seems to be system dependent, so I couldn't think of a simple and cross-platform way to do it. Do you think it could be added, though, or even worth being worked on?

Also a minor question: How will updating the app in the future affect the changes in the `core.py` file?

**Comment by txe** [comment]
Adding detecting the current layout is not too hard although tricky on Linux, [for example](https://stackoverflow.com/questions/18954645/detect-keyboard-layout-in-nix-in-python/18972262#18972262), where instead of `xkblayout-state` can be some other program.
On the other hand, I've never seen that UI behaves differently based on a current layout. I'm pretty sure, it's inconvenient for common users.
After the app update, you will have to apply changes again.

**Comment by Skarfrael** [comment]
I see. 
Well, I came with the idea since it's a more dynamic solution to the situation I described in the post.
Of course I am not talking for the entire UI, only for the "today's" node's title, since in reality it's just a shortcut for creating manually a node with a date title.
