### ISSUE TITLE
C++ version

### ISSUE THREAD

**Issue by benjithereborn** [giuspen/cherrytree#654]
When will the C++ version will be out of the beta state or ad least has the same function as the python one.

**Comment by giuspen** [comment]
I will do what I can to get the first release out in the summer, some features may be inhibited though and implemented later on. Probably the imports from various other note taking apps will come afterwards - I'm considering having the old python code of those imports running into the C++ version, that may speed that up.

**Comment by benjithereborn** [comment]
Nice keep up the great work!
