### ISSUE TITLE
[Feature Request] Stay inside CodeBox after creation

### ISSUE THREAD

**Issue by szambonurek** [giuspen/cherrytree#655]
How to reproduce:
Select some code, press `ctrl+alt+c` or menu Edit/Insert CodeBox.
Now cursor is outside CodeBox, it would be nice if it stays inside.
Why?
Now if I want to change something inside after creation or resize CodeBox using `ctrl+,` or `ctrl+.` I have to grab mouse and click inside CodeBox.

**Comment by giuspen** [comment]
Hi @szambonurek there is a combination of keys to move the cursor in and out the codebox, I will check shortly and get back to you

**Comment by giuspen** [comment]
Ctrl+Space is the way to move the cursor out of the codebox and in if the cursor is just before the codebox

**Comment by szambonurek** [comment]
@giuspen thx for answer, unfortunately this won't work in my example, because after codebox creation cursor is after codebox so ctrl+space won't work.

**Comment by giuspen** [comment]
That's right, so you press left arrow and then Ctrl+Space and have the cursor in the codebox

**Comment by txe** [comment]
Hi @giuspen I can add that Ctrl+Space will also work after a codebox, it will look pretty natural.

**Comment by giuspen** [comment]
Hi @txe that would cause an issue in case there are two codeboxes in line one after the other without spaces

**Comment by txe** [comment]
Of, if to speak about the user case, if user hold Ctrl during creating/edit codebox (Ctrl+OK/Enter) then a codebox gets the focus?

**Comment by giuspen** [comment]
We can also just put the focus always in as originally asked and see if anyone complains, who uses the mouse won't care and who uses the keyboard is a Ctrl+Space away from the previous behaviour
