### ISSUE TITLE
all backups deleted

### ISSUE THREAD

**Issue by bash64** [giuspen/cherrytree#66]
I am using cherrytree to write a book.
I normally keep up to 6 backups of my notes at any given time on 6 different drives.
CherryTree has been acting funny lately.
It would not open notes or the notes were blank.
So I go to a backup  and get my file.
I edit for 2hrs and save.

Now, all of my notes are gone.
Each backup copy is 12.3k when the file is normally 1.6mb in size.
Apparently, CherryTree wrote out zero data to my saves, effectively deleting them, even though I could see and edit my full notes on screen.
Believing it was working I used 'save as' to write out to all my backups.
This is devastating.
If I had not exported all my notes to HTML and PDF just recently my entire 6 months worth of book writing would be gone!

I now have to recover all my notes very tediously by copy and pasting out of the PDF back to CherryTree.

If anyone else has had this issue let me know.

CherryTree 0.32.0

Linux Mint 17.2 64bit Cinnamon Desktop

**Comment by bash64** [comment]
P.S. I also started getting a 'write to file failed' no matter which backup I tried to save to right before I realized something was terribly wrong.

**Comment by giuspen** [comment]
I'm sad and sorry to hear this, the problem here is that you have been
using an outdated version while the up to date version is 0.35.10 including
tons of important bugfixes.

**Comment by bash64** [comment]
Well, this is the latest update in the linux mint repo.
Is there a PPA that I can use to get the latest copy or do I have to use git?

**Comment by bash64** [comment]
I went with a PPA. I have 35.0 now.

**Comment by bash64** [comment]
Give me an email and I will send you a copy of my migration book for Windows users switching to Linux Mint. It is quite helpful whether your a windows user or not and pertains to Ubuntu also.

**Comment by bash64** [comment]
Is there anyway to export cherrytree to ePub?

**Comment by giuspen** [comment]
Hi, you can find my personal email in cherrytree help--about dialog, I'm a
long time linux user though :)
The export to ePub is not available yet, maybe in future I will find time
to personally implement it or somebody else will contribute to the code.

**Comment by einsdurchnull** [comment]
Today, i had the same issue. All my notes are gone. Even my backup on USB was overwritten. It is 12KB in size now. :( Before, I had many times the "write to disk failed"-error. I would bypass the error by saving to a new file, but this time the "write to disk failed"-error kept popping up. I couldnt even save to another partition. So there seems to be a serious bug.

I'm using v0.38.6 on Windows 10

**Comment by orange888** [comment]
How to backup cherrytree's notes?

**Comment by srcox86** [comment]
Today I have had the same issue described by @einsdurchnull . I first got around the issue by saving to another file, but eventually the program would no longer let me do that. After restarting Cherrytree and re-opening my file, everything was gone. Additionally, all the backup files were wiped out. I'm using Cherrytree v38.8 on Kali 2018.3 (Debian 4.17). 

I have a cloud-based backup from yesterday but have lost all the work I have done since then. This is extremely frustrating as there was a lot of documentation and screenshots in the file. I'm hesitant to restore the back-up and keep using Cherrytree because I don't want to lose my work again.

**Comment by txe** [comment]
Closing, current version rewrites backups only after successful saving
