### ISSUE TITLE
List stops being utilized when cherrytree loses mouse focus

### ISSUE THREAD

**Issue by Skarfrael** [giuspen/cherrytree#660]
Hello.

When you want to add a list in your notes, changing line using the Return key and keeping the list format, stops working if the cherrytree window loses focus (e.g. if we move to another application and return).

Afaic, hitting the Return key when being in a list row/line, the new line should always start with the list bullet/number type of the previous line.

**Comment by txe** [comment]
What cherrytree version do you use?

**Comment by Skarfrael** [comment]
> Hi! What cherrytree version and OS do you use?

0.38.11

**Comment by txe** [comment]
Actually, I cannot repeat this issue, and, knowing how the code works, I cannot imagine how this bug can happen. 
But there is another bug #647, also related to losing the focus, maybe there is a connection between them, so can you try it?

**Comment by singularis-mzf** [comment]
Maybe I discover something. I'm using CherryTree 0.38.8 on Ubuntu Studio 18.04.4 (but was able to reproduce the behaviour on 0.38.11 as well) and I found that if I press regular Enter, list bullet is generated on the new line, but if I press Enter on the numeric part of keyboard, the next line never becomes a list item automatically. It does not depend on window focus for me. (I use an external keyboard, not a notebook-one and my desktop environment is Xfce on Xorg.) Could not this be the source of this problem? Maybe CherryTree should react to the numeric-keyboard-Enter the same way as to the main one.

**Comment by giuspen** [comment]
The numeric keyboard enter/return has probably another key name, cherrytree is only checking for the default one, I'll see if I can find the numeric one and map it to do the same

**Comment by Skarfrael** [comment]
Upgrading the system today (to Manjaro 19 Kyria) seems to have resovled it. It seems it's not cherrytree specific bug. Having said these I'll close the issue to keep things tidy. 

Note: I also moved back to kernel 4.19.106-1 from 5.4.22-1. Also I forgot to mention in the post that I am using the KDE flavor.
