### ISSUE TITLE
Search Crashing Causes Nothing To Save After Event...

### ISSUE THREAD

**Issue by wHYnOsAVE** [giuspen/cherrytree#664]
Loved the program, it's great for highlighting, organizing your work etc... I say loved because...

There's a nice bug that happens when you do a "Find In All Nodes Search" (possibly in other search cases as well).

It crashes, and lands on a random node, not one with the word in it. (That's the only way you know it's crashed). It would be great to have an error message come up saying something then, because if you choose to continue to work on anymore nodes adding and saving you will get a great surprise when you exit. The error message you would have enjoyed to have before suddenly shows up making and saving to a log file. It's great it saves that, because I truly don't know what I'd do without this info.

Hopefully it's useful to you...

Traceback (most recent call last):
  File "core.pyc", line 3249, in find_in_all_nodes
  File "findreplace.pyc", line 475, in find_in_all_nodes
  File "findreplace.pyc", line 787, in parse_given_node_content
  File "findreplace.pyc", line 746, in parse_node_content_iter
RuntimeError: returned character can not be represented in 16-bit unicode

The best part is although it saves this gibberish, every other thing that you have typed and saved into the other nodes after your search error has actually not been saved at all, you get this nice second surprise when you open it up again in CherryTree.

**Comment by giuspen** [comment]
Is it systematic? Can you send me your document and tell me exactly how to reproduce?

**Comment by Stefan-mcp** [comment]
ouch - this sounds familiar - im using it for exam notes and it tortured me with a crash the other day. 
its a great tool (thanks author) and you kinda rely on it, then when it crashes...just ouch.

Were you working on a share (virtualbox or real) or some form of removable storage when this happened? it may be linked to another bug / issue that i raised a few days back and is now hopefully fixed.  

finally - check the hidden files whereever your document was. cherrytree makes temp files with ~, ~~, ~~~ type pattern.  they're hidden my default but each one is a snapshop of the document as youve been working on it. i dont know how often they are made - but you may be able to recover some of your data by looking for them and opening the most recent one

**Comment by txe** [comment]
No, the problem is with a UTF-16 symbol in a node text (it can be even invisible) and not related to how data is kept.
The message "RuntimeError: returned character can not be represented in 16-bit unicode" was helpful and helped me find the same issue in another gtk/python project.
I suppose, the problem happens on Windows, with Segue UI font, with "U+1F5F9 🗹 BALLOT BOX WITH BOLD CHECK" symbol at the beginning of the text (at least how I could repeat it), so I can fix it.

PS: also, I recall there was another issue when the configuration dialog couldn't open because of that symbol.
