### ISSUE TITLE
Not working in ArcoLinux i3

### ISSUE THREAD

**Issue by poetician** [giuspen/cherrytree#669]
Hi,

Running the latest kernel and everything's updated. When I try to load CherryTree from a terminal this is what I get: (cherrytree:1092288): Gtk-WARNING **: 21:44:35.075: Unable to locate theme engine in module_path: "murrine".

Need anything more from my end?

peace

**Comment by txe** [comment]
Hi, AFAIK, cherrytree should start OK with that warning. Do you see the main window?
To remove the warning try to install 32bit version of murrine engine, like lib32-gtk-engine-murrine.

**Comment by txe** [comment]
To add, if you don't see the main window, check the system tray, it can be minimized.

**Comment by txe** [comment]
I suppose the solution was sufficient, I'm closing this issue
