### ISSUE TITLE
Zim import uses too much memory

### ISSUE THREAD

**Issue by 0ion9** [giuspen/cherrytree#67]
I have an existing Zim wiki, 26mb size on-disk in total, with 
- 3280+ articles whose content totals 5.9mb
- 137 images totalling 20mb
- Pretty moderate level of markup (1-5 headings/article, maybe some bold or italic), with a moderate amount of links (0-5, average 0.3 / article).

I just attempted to import this into CherryTree. When I started up cherrytree, it was using 79mb of memory (as reported in the RES column in `top`). When I killed it 15 minutes later because it was getting too large, it was using _3gb_ of memory and the import process still hadn't completed.

This huge memory use is far out of proportion with the amount of data being imported. It seems to me there must be some massive inefficiency there.

cherrytree: 0.35.10
pygtksourceview2 :  2.10.1
python2-dbus :  1.2.0
desktop-file-utils :  0.22
python2-pyenchant :  1.6.6
p7zip :  9.38.1

OS: Arch Linux x86_64

**Comment by txe** [comment]
Fixed in C++ version
