### ISSUE TITLE
I use cherrytree on Ubuntu 16.04,and find a bug 

### ISSUE THREAD

**Issue by FishInWave** [giuspen/cherrytree#670]
My OS: Ubuntu 16.04
When I set Python2.7 as default , cherrytree 0.38.9 could be used normally ; but when I set Python3.5.2 as default, it just couldn't run as usual.
When I click a .ctd file，my cursor just change to the type like something is loading.
And if I reset Python2.7 as default,it just fine.
I don't know how to use cherrytree when I want my default python version is 3.5+

**Comment by txe** [comment]
Hi
Cherrytree uses python2 for work in spite of what default python is, 2 or 3.
So the question is do you remove python2 from the system when you make python3 default?
If not, then try to run `python2` in the terminal, it should show version 2.7 (or something like that).

**Comment by txe** [comment]
Closing, no data to resolve it
