### ISSUE TITLE
Show Node path in tooltip of Last Visited Nodes

### ISSUE THREAD

**Issue by mocsa** [giuspen/cherrytree#674]
In my Node tree I have Nodes for several years and each has a child called "Events". Looks like this:

```
2018
|-- Events
2019
|-- Events
2020
|-- Events
```

On the left of the Node Name Header I see the "Last Visited Nodes". In my case they all display "Events". I cannot see which year they belong to.

If I hover my mouse over the "Last Visited Nodes", a tooltip is already displayed which shows the full name of the Node.

My suggestion: Please extend the tooltip with the path of the Node. In my case the extended tooltip would be `2019/Events`.

**Comment by giuspen** [comment]
@golimarrrr this was implemented but I realised a couple of days ago that it was broken and fixed it https://github.com/giuspen/cherrytree/commit/a2748035684d02deacfd1e300e420d5c1c8f6a16 - now the tooltip shows the full path.
