### ISSUE TITLE
Font/Visual Render problem on line "border"

### ISSUE THREAD

**Issue by Chuhtra** [giuspen/cherrytree#676]
Hello, 

I would like to point out a possible visual/font bug. I am on Manjaro Linux, with cherrytree 0.39.0 and some non-system fonts. Namely, atm I am using Nunito font in cherrytree.

The issue is in letters like 'g' or 'y' or 'p' that has "tails" that exceed their strict line limits. It seems to be triggered by the active line (grey).

 It can be shown below: 

Appearence where everything seems ok:
![image](https://user-images.githubusercontent.com/40795688/76355113-55ec3900-631c-11ea-967d-a62019ee752c.png)

Appearence if I type (e.g. 3 g's):
![image](https://user-images.githubusercontent.com/40795688/76355460-01958900-631d-11ea-8e43-3fa9bd968e15.png)

Appearence if I delete the 3 g's:
![image](https://user-images.githubusercontent.com/40795688/76355533-22f67500-631d-11ea-8a0f-54640bb4c9df.png)

The problem isn't always solved if the active line moves away (see first line), although it goes with it (not shown in the below picture):
![image](https://user-images.githubusercontent.com/40795688/76355686-6bae2e00-631d-11ea-9998-f36c27e741ca.png)

(Sorry for not using printscrn, it's just that pressing it can't capture the issue. Some kind of reset is happening probably due to the focus being lost from the cherrytree window)

**Comment by txe** [comment]
Hi,
Yeah, the cursor and highlighting is a few pixels higher then it should be.
I tried that font and the text look fine, although if it was repeated, I wouldn't know what to do with it. For me, it looks like gtk glitch, did you try to reboot the system just in case?

**Comment by txe** [comment]
Or it can be a broken font cache, you can try to rebuild it.

**Comment by Skarfrael** [comment]
Yeah rebooting didn't seem to solve it. I also tried to rebuild the font cache (`fc-cache -f -v`) with reboot also didn't seem to do anything :/ 

It doesn't seem to be consistent. Some nodes have it, other's don't, and in those who do not all lines seem to be affected.

Any other ideas to try are welcome

**Comment by txe** [comment]
Closing, I'm pretty sure it was a bug in either gtk2 or cairo.
