### ISSUE TITLE
Problem with opening another note on Ubuntu 16.04 using Cherrytree 0.39.0

### ISSUE THREAD

**Issue by szambonurek** [giuspen/cherrytree#677]
Problem doesn't occur with Cherrytree 0.38.11.
Installed using deb packages:
cherrytree_0.38.11-0_all.deb
cherrytree_0.39.0-0_all.deb

I have many notes, ex.NoteA.ctb, NoteB.ctb, NoteC.ctb
When I double click NoteA.ctb it opens.
When I double click NoteB.ctb when NoteA is opened, instead of NoteB new empty instance of Cherrytree is opened. So now I have 2 instances opened: NoteA and empty.
When I double click NoteC.ctb nothing happens.

In Cherrytree 0.38.11 all 3 notes are opened in 3 instances, as expected.

**Comment by txe** [comment]
I see where is the problem, I'll make a fix soon.
