### ISSUE TITLE
Feature Request: Clear foreground/background color

### ISSUE THREAD

**Issue by jcsanyi** [giuspen/cherrytree#678]
Once a foreground or background color has been set on a section of text, it's impossible to clear that color without setting a different color (or using clear-all formatting, which isn't ideal because it makes more work to re-apply other styling). 

Setting the color to the same as the default color (foreground/background) *appears* to work, but doesn't actually - it keeps the formatting in the text, and if the default color is ever changed the text is still stuck with the old color.

It would be nice if there were a None or Remove option in the color dialog - similar to the "Automatic" option in LibreOffice, for example.

**Comment by txe** [comment]
Fixed in 0.99 version
