### ISSUE TITLE
How can I recover a deleted node?

### ISSUE THREAD

**Issue by afonsomatos** [giuspen/cherrytree#685]
How do I undo a node deletion?

**Comment by txe** [comment]
There is no such a thing. But 
- if you didn't save changes, then just close a document without saving.
- if you saved changes, then the previous state of document was saved in a backup (files with ~). Remove ~ from a file name, open the backup, export the node as a Cherrytree document, open the current document, import the document with the node.

**Comment by afonsomatos** [comment]
There should be an option for this though. It's too much of an hassle to do all of that.

**Comment by txe** [comment]
I agree, there are future requests (e.g. #505) about it, though almost all new future requests are postponed until gtkmm3 version.
