### ISSUE TITLE
Very, very, very long node creation

### ISSUE THREAD

**Issue by MrSplinterRat** [giuspen/cherrytree#686]
In a file with several thousand nodes, a new one is created for a very long time (15-25 seconds or more).
For verification, a test file with a large number of empty nodes was created.
The problem is reproduced on it.

Test file name: 0_Root_50.ctb (868k size, 5555 nodes)
Shared link: https://drive.google.com/file/d/1uvA6hGq86Squ3x5OEU8V2zHaWzF0ijY6/view?usp=sharing

**Comment by txe** [comment]
Hi, what cherrytree version do you use? I don't have this issue with 0.39.

**Comment by MrSplinterRat** [comment]
> Hi, what cherrytree version do you use? I don't have this issue with 0.39.

Checked in 0.38.9, 0.39.1 - there is a problem.
How many nodes are in your file? (Tree -> Tree info)?
I have now - 5922.
If you have significantly less - it is not surprising that the problem does not occur.
Please check on my test file using the link from Google Drive - there are 5555 nodes.
The problem will be reproduced on it, I just checked.

**Comment by txe** [comment]
I used your file for the test and check on my laptop and in virtual machine, no problem, the delay is 3 seconds max.

**Comment by MrSplinterRat** [comment]
> I used your file for the test and checked on my laptop and in a virtual machine, no problem, the delay is 3 seconds max.

My cpuinfo:

===
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 158
model name	: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
stepping	: 9
microcode	: 0xca
cpu MHz		: 900.009
cache size	: 6144 KB
physical id	: 0
siblings	: 8
core id		: 0
cpu cores	: 4
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr
sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology
nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1
sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb
invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2
smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts
hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
bogomips	: 5599.85
clflush size	: 64
cache_alignment : 64
address sizes	: 39 bits physical, 48 bits virtual
===

On test file: time of node insertion is 13 sec.

According to my observations (I did not collect strict statistics, empirical observations), the time of adding new node grows at least in proportion to the square of the current number of nodes. On a small number of nodes, I also did not feel any problems.

**Comment by MrSplinterRat** [comment]
> I used your file for the test and checked on my laptop and in a virtual machine, no problem, the delay is 3 seconds max.

My cpuinfo:

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 158
model name	: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
stepping	: 9
microcode	: 0xca
cpu MHz		: 900.009
cache size	: 6144 KB
physical id	: 0
siblings	: 8
core id		: 0
cpu cores	: 4
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr
sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology
nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1
sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb
invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2
smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts
hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
bogomips	: 5599.85
clflush size	: 64
cache_alignment : 64
address sizes	: 39 bits physical, 48 bits virtual
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

On test file: time of node insertion is 13 sec.

According to my observations (I did not collect strict statistics, empirical observations), the time of adding new node grows at least in proportion to the square of the current number of nodes. On a small number of nodes, I also did not feel any problems.

**Comment by txe** [comment]
You are right about square proportion, I saw that behavior before, but it was fixed in 0.39. So, I'm surprised that 0.38.9 and 0.39.1 are the same for you.

**Comment by txe** [comment]
If you have linux and installed cherrytree by a packet manager, you can easy try the developer version. Clone the repository and to start the program, `cd cherrytree` and `python2 cherrytree`

**Comment by MrSplinterRat** [comment]
> If you have linux and installed cherrytree by a packet manager, you can easily try the developer version. Clone the repository and to start the program, `cd cherrytree` and `python2 cherrytree`

I downloaded the latest version from GitHub, made additional measurements and got strange results.

- - -
Time of one node adding

Test - my test file (0_Root.ctb)
Work - my real work file (5924 nodes)
27.03.20 - version from Git


|Cherry | Test | Work | 
|---|---|---|
| 0.38.11 | 13 | 15 | 
| 0.39.1 | 3 | 197 | 
| 27.03.20 | 1.5 | 198 | 


Unfortunately, I have to admit that my test file at the moment cannot demonstrate the problem.
And my work file is filled with private data, and I can not send it.
I will try to make a more representative test file so that it can reproduce my situation.

**Comment by txe** [comment]
Wow, 197 seconds, how come it got so worse?!

**Comment by MrSplinterRat** [comment]
> Wow, 197 seconds, how come it got so worse?!

I saw the Russian text in your repository, so - сам не знаю с какой радости. Но это перебор. 

I'm not an English native speaker, so I have to use google translate (

**Comment by MrSplinterRat** [comment]
> Wow, 197 seconds, how come it got so worse?!

In any case, I am absolutely sure that something is wrong with the algorithm for adding new node. And this cannot be solved by rewriting from Python to C ++, as the author is going to do - if he will leave the algorithm the same. The problem is that it does not play on my test file, and I can not send the real working file. I’ll think about how to get around this situation.

**Comment by txe** [comment]
Если только текст содержит конфиденциальную информацию (не картинки), то я могу дать тебе версию, которая изменит текст, названия нод и т.д. На это потребуется день или два.

**Comment by MrSplinterRat** [comment]
Спасибо! У меня там вообще практически нет картинок. Может, и совсем нет. Я думал написать скриптец, который заменит звёздочками названия нод и их текст - чтобы только длины совпадали - тогда скорее всего проблема воспроизведётся. Но уж больно слаб я в Питоне ) 
Мы профилировали эту проблему с коллегами - там жуть вылазила, какая-то многомиллионная отрисовка в цикле в глубине. Я забыл, каким профайлером. Но то, что моя проблема воспроизводима на других машинах - это 100%.

-- то я могу дать тебе версию, которая изменит текст, названия нод и т.д.

Если можешь, напиши просто скрипт, который делает по sqlite-базе то, что я описал выше - тупо меняет имена и тела узлов на аналогичной длины строки из звёздочек, например. Что-то мне подсказывает, что больше двух страниц этот скрипт вряд ли займёт)

**Comment by MrSplinterRat** [comment]
Ситуация правда идиотская. Я работаю с большими потоками информации по 12ч в сутки, и всё букмарчу. Сколько аутлайнеров перебрал - ничего удобнее Черри не нашёл. Подходит во всём, кроме этой мелочи. Когда создаёшь в течение дня сотни узлов, на каждый ждать по полминуты (на работе медленная машина) - начинает грызть мысль о написании аутлайнера с нуля.

**Comment by txe** [comment]
Try [this script](https://gist.github.com/txe/0c73157f5d35d134e72ff15c99ce34c3)

**Comment by MrSplinterRat** [comment]
Спасибо большое! Получилось!

Проблема воспроизводится.

Я немного поменял скрипт:
``` python
return re.sub(r'\w', '*', text)
``` 
на 
``` python
return re.sub(r'.', '*', text)
```
\- теперь чистится всё. Файл открывается и работает.


Ссылка на полученный файл:
https://drive.google.com/open?id=1O-9Brvo8RoIsx5qkj_-FGew0WOhoXEnP
C_Star.7z
340k, extracted 6.3M

Snap - снапшот ЧерриТри с ГитХаба на момент 2020.03.28 21.23 - сегодняшний вечер

| Version | Time |
|---|---|
| 0.38.11 | 16.5 |
| Snap | 211 |
