### ISSUE TITLE
Use normal quotes

### ISSUE THREAD

**Issue by Y4kuzi** [giuspen/cherrytree#688]
How can I use normal quotes(' and ") in CherryTree 0.39.1 for Windows?
Disabling Smart Quotes did not work, I also tried to change the config.cfg but that didn't work either.
I enjoy using this notekeeping app but the abnormal quotes are really annoying.

**Comment by txe** [comment]
Hmm, just checked on Win10, portable 0.39.1, with an old config (and after removing one).
Turned off `Enable Smart Quotes Auto Replacement` works as should, stopping converting quotes. The code is pretty simple there, I cannot see how it can be broken.

**Comment by Y4kuzi** [comment]
Same issue with cherrytree_0.39.1_win32_portable. Unpacked it, made an empty config.cfg in the bin directory, opened the app, went to preferences and unchecked Enable Smart Quotes Auto Replacement. It still uses the weird quotes.

**Comment by txe** [comment]
Just to be clear.
You type one quote, then second and after that they are replaced by weird looking quotes. Or the first one is already weird looking? Do you use US International Keyboard (layout)?

**Comment by Y4kuzi** [comment]
My keyboard layout is set as NLD, which is my language.
I tried switching to US, just to test, and now the quotes are normal.
However, quotes now appear "instantly" after I press them, which isn't what I want.
Normally after I press on a quote key, it will wait for further input before displaying the quote. This is how I want it and should not change.
Any way to make it work with non-US keyboard layouts?

**Comment by txe** [comment]
Yeah, it looks like this issue and #427 are the same. I checked a few pygtk2 programs and they all have that problem when such layouts are used and gtk engine just inserts odd quotes.

But `Enable Smart Quotes Auto Replacement` gave me an idea that these symbols can just be replaced with the right ones. I'll make the fix soon.

**Comment by txe** [comment]
BTW, could you add "wrong" quotes here to be sure which one to replace?
