### ISSUE TITLE
Wrong "." processing in "Replace in Nodes Names" (RegExp mode)

### ISSUE THREAD

**Issue by MrSplinterRat** [giuspen/cherrytree#689]
In "Regular expression" mode:
metacharacter "." works correctly in the "Replace in Node Content" operation,
but it’s wrong - in the operation "Replace in Nodes Names": it is treated as a symbol ".", not as a metacharacter, and only "." is replaced. The remaining characters in nodes names remain unchanged.

**Comment by txe** [comment]
Thanks, you're right, regex in "Replace in Nodes Names" just doesn't work
