### ISSUE TITLE
HTML export, headers with misspelled words become chopped

### ISSUE THREAD

**Issue by ejtaal** [giuspen/cherrytree#69]
In CherryTree 0.35.10 on Ubuntu 14.04.2:

I typed a line of text "Lord of the Root boot2root VM", then made it h1, then exported it to HTML. However it comes out as
`<h1>Lord of the Root</h1>`
`<h1>boot2root</h1>`
`<h1>VM</h1>`

This only happens when spell check is enabled. When it is disabled, I get the expected:

`<h1>Lord of the Root boot2root VM</h1>`

Note that boot2root and VM are "misspelled" according to the spell check, so it seems this triggers the chopped up `<h1>` line. Hope this is enough info to squash this little buglet and hanks for making a great program :)

**Comment by giuspen** [comment]
Yes should be fixed in the current github version thank you
