### ISSUE TITLE
Adding new node takes 50 (!) seconds

### ISSUE THREAD

**Issue by sm8ps** [giuspen/cherrytree#691]
First off, thanks a lot for this very useful and also very stable software, @giuspen! It has served me well as a knowledge base for years now. Over time quite a lot of information has accumulated and my database is at 6.6 MB now. There are ~1200 nodes of which 50 are bigger than 10 kB with 70 kB maximum. I do not think this is overwhelming but Cherrytree has lately begun to chew hard on it.

Since a few weeks the inserting of any new node takes about 50 (!) seconds. During that time, Cherrytree freezes and one CPU core is running at near hundred percent. The action does terminate however and the software runs normally after that. Deleting a node is instantaneous.

I have not been able to do much debugging other than running Cherrytree from the command line:
```
sel node id=1243, seq=2
sel node id=865, seq=6
pending_edit_db_node_buff 865
sel node id=865, seq=6
pending_new_db_node 1244
pending_edit_db_node_hier 1244
sel node id=1244, seq=3
write node content, node_id 865 , write_dict {'upd': True, 'buff': True, 'hier': False, 'child': False, 'prop': False}
write node content, node_id 1244 , write_dict {'upd': False, 'buff': True, 'hier': True, 'child': False, 'prop': True}
win destroy: runn_win found with id 0
```

Checking with SQliteBrowser shows that node 865 is the father node into which I want to insert the new one and 1244 is the new one; 1243 was just the node shown initially which happened to be the last one created.

Does that make any sense? I have seen #686 and #687 but I do not speak Russian and I am not sure if max_node_id() applies to my case with only 1200 nodes.

Thanks in advance for your consideration!

**Comment by txe** [comment]
I'm pretty sure #687 fixes your issue, can you try code from github?

**Comment by sm8ps** [comment]
Sure thing you were right! The current code from Github/master does fix the issue. I should have tried before raising this issue but I did not realize that at the time. 

Many thanks for your quick response and -- as I said before -- for this nifty piece of software!

**Comment by txe** [comment]
Thanks for using the program :thumbsup:
