### ISSUE TITLE
"Insert Today's Node" behavior

### ISSUE THREAD

**Issue by MrSplinterRat** [giuspen/cherrytree#693]
At least up to version 0.38.11, the “Insert Today's Node” command, if a node with a name consisting of the current year’s digit (now 2020) was active, Today’s Node was created inside the current node. Now (0.39.1) Today's Node is always created at the root of the tree. From my point of view, this significantly degrades usability and forces the user to take many unnecessary actions to move the node to where the user wanted to place it. In other words, the correct behavior has been changed to the wrong one.

I would like to know if such a change was a conscious decision or an accidental result of a change in the code? 
If conscious, then what is the reason?

Thanks.

**Comment by txe** [comment]
Did I get it right, instead of creating /`2020`/`March`/`29 Sun`, it creates /`28 Sun`?

**Comment by txe** [comment]
I cannot reproduce the issue. Maybe it depends on a document, can you give me  a ctb file to reproduce the issue?

**Comment by MrSplinterRat** [comment]
> Did I get it right, instead of creating /`2020`/`March`/`29 Sun`, it creates /`29 Sun`?

No)

E.g. my current node: /Programming/Lang/Rust/_byDate/2020

It creates /2020/March/29 Sun (at root) instead of creating /Programming/Lang/Rust/_byDate/2020/March/29 Sun , 
as it was in ver. 0.38.11 and earlier

**Comment by MrSplinterRat** [comment]
> I cannot reproduce the issue. Maybe it depends on a document, can you give me a ctb file to reproduce the issue?

My version - today's from GitHub.
Problem is reproduced in any my file.
To reproduce it,
1) create node with title '2020' _not_ at the root level, but as a child of any other node - and stay on this node ('2020')
2) press F8
You will get a node /2020/March/29 Sun _at_root_, but not at /Node/Subnode1/Subnode2/.../2020, as it was earlier

**Comment by MrSplinterRat** [comment]
> I cannot reproduce the issue. Maybe it depends on a document, can you give me a ctb file to reproduce the issue?

I reproduced this issue in a new, empty file

1) Add node: 111
2) Add sibling: 222
3) Add sibling: 333
4) Add sibling: 2020
I am now in /111/222/333/2020
5) F8
I have /111/222/333/2020 and /2020/March/29 Sun

**Comment by txe** [comment]
OK, I got your point. According to the online help:
> Insert Today’s Node - Creates a top-level node with a title set to the current year, a subnode of the current month, and a third-level node of the current day of the month and week.

Behavior like 
> If a node with a name consisting of the current year’s digit (now 2020) was active, Today’s Node was created inside the current node. 

was definitely is unintentional. I'm not sure if the current behavior should be changed.
For yourself, if you can use this code:

```python
    def node_date(self, *args):
        """Insert Date Node in Tree"""
        curr_time = time.time()
        now_year = support.get_timestamp_str("%Y", curr_time)
        now_month = support.get_timestamp_str("%B", curr_time)
        now_day = support.get_timestamp_str(self.journal_day_format, curr_time)
        list_before_start = list(self.state_machine.visited_nodes_list)
        if self.curr_tree_iter:
            if self.treestore[self.curr_tree_iter][1] != now_year:
                self.node_child_exist_or_create(None, now_year)
        self.node_child_exist_or_create(self.curr_tree_iter, now_month)
        self.state_machine.visited_nodes_list = list_before_start
        self.node_child_exist_or_create(self.curr_tree_iter, now_day)
```

**Comment by MrSplinterRat** [comment]
Thank you very much, this works, and that is exactly what I need.
