### ISSUE TITLE
Convert to Python 3

### ISSUE THREAD

**Issue by xmunoz** [giuspen/cherrytree#694]
Python 2 is officially [EOL](https://www.python.org/doc/sunset-python-2/). cherrytree should be converted to use Python 3 instead.

**Comment by giuspen** [comment]
The future of cherrytree is C++

**Comment by xmunoz** [comment]
What is the timeline for moving the rest of this code base to C++? Would you be willing to review and merge a PR that replaces Python 2 with Python 3? Since cherrytree is widely used by security professionals, I would hope that the software powering it is actively maintained and also secure.

**Comment by giuspen** [comment]
The python binding for Gtk3 is incomplete. The Gtkmm3 first version will be around summer I reckon
