### ISSUE TITLE
Bug: Links become broken when importing one cherrytree document into another

### ISSUE THREAD

**Issue by anmej** [giuspen/cherrytree#70]
I created a cherrytree file with a few nodes, then created another cherrytree file containing 1 node with a subnode, with links one to other. Then I imported the second file into the first. After the import, the links no longer point to the original nodes, but to nodes of the first file.

CherryTree 0.35.10 on windows.

**Comment by giuspen** [comment]
Please test the build 0.38.1+4:
http://www.giuspen.com/software/cherrytree_0.38.1+4_setup.exe
http://www.giuspen.com/software/cherrytree_0.38.1+4_win32_portable.7z
http://www.giuspen.com/software/cherrytree_0.38.1+4-1_all.deb

**Comment by anmej** [comment]
The bugs appears to be fixed in 0.38.3

Thanks!
