### ISSUE TITLE
Paste a table from Excel with a "header row"

### ISSUE THREAD

**Issue by gnzgo** [giuspen/cherrytree#702]
Hello,

It would be nice to have the option, when pasting some cells/rows that you copied from Excel, to be asked if you want to use the first row as the "headers" row, instead of pasting everything into a new table, leaving the headers empty (with "click me" on them), and forcing you to copy the headers by hand and then delete the first row.

An alternative to being "asked" when pasting Excel content could be, for example, being able to select the top-most row of the table, and presenting a right-click-menu option of "Use this row as column headers" or similar.

Thanks for considering it.

**Comment by txe** [comment]
It is done in C++ version, also there are commands to move or removed rows including a header row.
