### ISSUE TITLE
Feature Request: Duplicate Node

### ISSUE THREAD

**Issue by anmej** [giuspen/cherrytree#71]
Sometimes, a group of nodes needs to be based on a common template. In such a case, it is convenient to simply duplicate a previous node under the same parent to create a new mode. Currently in CT, you need first to create a new node, then copy all text in the node you want duplicated and paste it manually. A **Duplicate Node** (and maybe also **Copy Node**/**Paste Node**) command in Node menu will be very convenient. 

PS. You are doing a great job with cherrytree. I really like your work.

**Comment by giuspen** [comment]
This is a well node need, I will add this capability in future

**Comment by frobby** [comment]
(using cherrytree 0.36.0 release candidate) 
The new node duplication feature (Ctrl+Shift+D) is duplicating the selected node itself, but the copied node does not contain any of the original node's subnodes.
Please can you make it able to duplicate a group / tree of nodes? Thank you!

**Comment by giuspen** [comment]
Hi frobby, I'm not sure I will be able to include the subnodes copy in 0.36.0, if not I will take care soon anyway

**Comment by anmej** [comment]
Closing issue: feature is implemented

**Comment by kevthehermit** [comment]
I See this is closed suggesting it is implemented. Im using 0.38.0. If i Duplicate Node it does not carry all the sub nodes with it. 

At the moment im exporting my template and importing it when i need it. 

Or am i missing something.
