### ISSUE TITLE
Cannot close new documents that are non-empty

### ISSUE THREAD

**Issue by fabriziobertocci** [giuspen/cherrytree#720]
Create a new instance, then create a node. 
Now try to close Cherrytree, it asks you to save the document, without giving you an option NOT to save it:
- Close the doc
- Choose storage type have only two options: Cancel (go back to the document) and OK (proceed to file selection).
- Pressing OK opens the system's file selector and that too have two options: Cancel (go back to the document) and OK, save the file.

There is no way to discard the document

**Comment by txe** [comment]
It is fixes in C++ version (soon be released), the warning message has a discard option.
