### ISSUE TITLE
Can't install on Linux Mint

### ISSUE THREAD

**Issue by rizz861** [giuspen/cherrytree#722]
Linux Mint 19.3
Linux version 5.3.0-46-generic (buildd@lcy01-amd64-013) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #38~18.04.1-Ubuntu SMP Tue Mar 31 04:17:56 UTC 2020

Ive tried installing with the software manager and also this way.
    sudo add-apt-repository ppa:giuspen/ppa
    sudo apt-get update
    sudo apt-get install cherrytree

The program installs, however when I launch it, I get the waiting icon for a little bit and then it crashes.  I'm a noob to linux, so I'm not sure where to begin.  Thanks in advance!!!

**Comment by rizz861** [comment]
I just tried another note app(Zim) and it does the exact same thing.  As a test I also downloaded a random pc of software to see if its everything failing but that program worked fine.

**Comment by txe** [comment]
OK, I install Mint soon, and then can say why it doesn't work

**Comment by txe** [comment]
In my case, everything is working, so could you run `cherrytree` in console and paste the results here?

**Comment by rizz861** [comment]
File "/usr/bin/cherrytree", line 72
    print "cherrytree [filepath [-n nodename] [-x export_to_html_dir] [-t export_to_txt_dir] [-p export_to_pdf_path] [-w]]"
                                                                                                                          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("cherrytree [filepath [-n nodename] [-x export_to_html_dir] [-t export_to_txt_dir] [-p export_to_pdf_path] [-w]]")?
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 145, in apport_excepthook
    os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640), 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_cherrytree.1001.crash'

Original exception was:
  File "/usr/bin/cherrytree", line 72
    print "cherrytree [filepath [-n nodename] [-x export_to_html_dir] [-t export_to_txt_dir] [-p export_to_pdf_path] [-w]]"
                                                                                                                          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("cherrytree [filepath [-n nodename] [-x export_to_html_dir] [-t export_to_txt_dir] [-p export_to_pdf_path] [-w]]")?

**Comment by txe** [comment]
You don't have python2.
- uninstall cherrytree
- install python 2.7
```
sudo apt install python2.7 python-pip
```
- install cherrytree

**Comment by rizz861** [comment]
I did what you said and this is what i get now.  

File "/usr/bin/cherrytree", line 66
    print "cherrytree [filepath [-n nodename][-x export_to_html_dir]]"
                                                                     ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("cherrytree [filepath [-n nodename][-x export_to_html_dir]]")?
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 145, in apport_excepthook
    os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640), 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_cherrytree.1001.crash'

Original exception was:
  File "/usr/bin/cherrytree", line 66
    print "cherrytree [filepath [-n nodename][-x export_to_html_dir]]"
                                                                     ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("cherrytree [filepath [-n nodename][-x export_to_html_dir]]")?

Also, i thought I  had it before i did this bc when i ran this command, this is what I got.

:~$ ls -ls /usr/bin/python*
   0 lrwxrwxrwx 1 root root       7 Mar 14 21:27 /usr/bin/python -> python3
   0 lrwxrwxrwx 1 root root       9 Mar 11 12:12 /usr/bin/python2 -> python2.7
3552 -rwxr-xr-x 1 root root 3637096 Nov  7 05:07 /usr/bin/python2.7
   0 lrwxrwxrwx 1 root root       9 Mar 11 12:12 /usr/bin/python3 -> python3.6
4424 -rwxr-xr-x 2 root root 4526456 Nov  7 05:44 /usr/bin/python3.6
4424 -rwxr-xr-x 2 root root 4526456 Nov  7 05:44 /usr/bin/python3.6m
   0 lrwxrwxrwx 1 root root      10 Mar 11 12:12 /usr/bin/python3m -> python3.6m

**Comment by txe** [comment]
Hmm, it is odd:
- at the beginning of cherrytree file, there is `#!/usr/bin/env python2` to use python2.
- your `ls` shows that you have python2 symlink
But for some reason, python3 is still used.
You can try to run `python2 /usr/bin/cherrytree` as a work-around

**Comment by rizz861** [comment]
python2 /usr/bin/cherrytree made it work!

**Comment by txe** [comment]
For some reason `/usr/bin/env` in your case doesn't work.
Can you try `/usr/bin/env python2` and see what the result is? Maybe you need to read about it on specialized resources.

**Comment by rizz861** [comment]
~$ /usr/bin/env python2
Python 2.7.17 (default, Nov  7 2019, 10:07:09) 
[GCC 7.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by txe** [comment]
Well, then I have no idea (

**Comment by mm47** [comment]
That's very, very odd. I also have Mint 19.3 and have installed from the deb package without any issues and I didn't need the ppa. And I also have Zim installed this way without any issues. Maybe your system is not up-to-date? 

Before anything, open your Terminal and type:
sudo apt-get --purge remove cherrytree
Then, it will ask Yes / No, type "y".
Then type:
sudo apt-get autoremove
It will ask Yes / No, type "y".

This will remove the cherrytree version installed on your system and also clean any dependencies there are NOT being used. So no worries.

Next, in the software manager, type Python and check if you have installed two Python versions (2.7 and 3). 
![Captura de tela_2020-04-19_01-27-56](https://user-images.githubusercontent.com/28028426/79679597-822d8c00-81dd-11ea-9bce-e17c7e98ad68.png)
![Captura de tela_2020-04-19_01-26-25](https://user-images.githubusercontent.com/28028426/79679598-85c11300-81dd-11ea-841b-3ced7f4b26ad.png)
![Captura de tela_2020-04-19_01-28-25](https://user-images.githubusercontent.com/28028426/79679599-89549a00-81dd-11ea-9c8a-c61dfeb9d698.png)
![Captura de tela_2020-04-19_01-27-03](https://user-images.githubusercontent.com/28028426/79679602-8d80b780-81dd-11ea-8ca0-baefa7dd6556.png)

If not, then install these pythons from the software manager. Then download the CherryTree deb package from the official website:
https://www.giuspen.com/cherrytree/#downl
Download the "cherrytree_0.39.2-0_all.deb", double click it and let Gdebi do its magic. It will handle any dependencies on its own, you'll have only to click OK and type your password.

Also, you must have internet connection so Gdebi can download the dependencies.

**Comment by txe** [comment]
Another user has the same issue, turns out he has `python` alias for `python3`. Maybe it's a reason here too.
