### ISSUE TITLE
 Feature request: allow deletion of recent documents entry 

### ISSUE THREAD

**Issue by ChrisOfBristol** [giuspen/cherrytree#724]
I have read the threads associated with the original thread with this title. They do not address the problem. "File>Recent Documents" shows a longer and longer list of deleted files!

In other applications which I have used, if a file has been deleted, if I later try to open it from the "File>Recent Documents" list, I am informed that it no longer exists and the entry in the list is removed. That's simple, requires, no effort and has no disadvantages. I would suggest that CherryTree should do the same.

Great application, the presentation is much more professional than the one I was using previously.

**Comment by txe** [comment]
Hi, thanks, it really should be that way.

**Comment by giuspen** [comment]
Actually it used to be that way but I received complaints from somebody that tried to open a recent file from a location that was simply not mounted at the moment and he didn't want the recent item to be deleted

**Comment by txe** [comment]
I see, good to know

**Comment by ChrisOfBristol** [comment]
> somebody that tried to open a recent file from a location that was simply not mounted
a) I think that the vast majority of users would want the standard dialogue with the Recent Documents list and might find an alternative dialogue difficult and inconvenient. Which is why the vast majority of applications use this standard dialogue.
b) The percentage of people who will have more than one disk mountable is very small, those people have installed extra disks and mounted them on previous occasions and should have the nous to work out why the file has gone from the list and be more careful about disk mounting in future.

I'm with the majority even though I have 3 disks!

**Comment by txe** [comment]
I'd say, such situation (a missing document) is quite rare and there is no need to overthink the solution.
A simple dialog with a message 'File 'file name' doesn't exist. Delete the link?' and buttons Yes(default)\No will cover all possible wishes.

BTW, I just checked, different programs behave differently in this situation, Notepad++ asked to create a new file, LibreOffice did just nothing (even didn't remove a link from Recent Documents).

**Comment by giuspen** [comment]
A dialogue would be a good solution but I would rather do it in the Gtkmm3 version than the current Pygtk2

**Comment by ChrisOfBristol** [comment]
It depends on how you use CT, I experimented with it to start with so 
have a few test files which will be on the list for ever now.

I also use several different CT files temporarily and they will also 
hang around on the list when I've finished with them.

I agree that different programs act differently LO doesn't delete it, 
gedit does etc. I would want to follow the best.

Yes/No would be an improvement.

Chris

**Comment by giuspen** [comment]
There is a menu item "Delete" at the end of the recent documents, have you
tried to use it to delete the recent documents you no longer want in the
list?

**Comment by ChrisOfBristol** [comment]
No there ain't :)

I'm on CherryTree 0.37.6

You must be using a different version. That also explains some of the 
mysterious comments I have read.

Chris

**Comment by giuspen** [comment]
Ok so if you upgrade to the latest version you will see that your needs are
already satisfied ;)

**Comment by txe** [comment]
I thought a bit about a dialog which asks to remove a link to file or not, and actually I don't like that idea because it makes users to think hard which button to press. 
So my solution is to show a special icon if file is missing and it prevents users from clicking on it. If they want to remove it, they have a command for that in menu.

**Comment by giuspen** [comment]
I like it! A different icon also in the botton submenu item to delete the broken link would ease even more the process of cleanup!

**Comment by txe** [comment]
Ok, I'll add
