### ISSUE TITLE
Won't install on Ubuntu 20.04 beta

### ISSUE THREAD

**Issue by ChrisOfBristol** [giuspen/cherrytree#725]
I can't install CherryTree on Ubuntu 20.04 beta, it's complaining about unmet dependencies.
Obviously since the OS is a beta the problem may be with Ubuntu. However, I expect you like to be ahead of the game, and this could be a forewarning of a problem to come. I am wary of Snaps (and a previous Ubuntu offering of CT was an old one which gave me a problem), so I didn't use the Snap from "Ubuntu Software", I used the deb from this site.

> Unable to install cherrytree:
> The following packages have unmet dependencies:
(Doesn't list any.)

![ct](https://user-images.githubusercontent.com/20310498/79056750-65c7a780-7c51-11ea-934a-90eaffb1f6ad.png)

**Comment by ChrisOfBristol** [comment]
An attempt to install it from a terminal resulted in the following, missing dependencies are listed:

> chris@desktop:~$ sudo dpkg -i Downloads/software/cherrytree_0.39.2-0_all.deb > t
> dpkg: dependency problems prevent configuration of cherrytree:
>  cherrytree depends on python-dbus; however:
>   Package python-dbus is not installed.
>  cherrytree depends on python-enchant; however:
>   Package python-enchant is not installed.
>  cherrytree depends on python-chardet; however:
>   Package python-chardet is not installed.
>  cherrytree depends on **python-gtk2** (>= 2.16); however:
>   **Package python-gtk2 is not installed.**
>  cherrytree depends on python-gtksourceview2; however:
>   Package python-gtksourceview2 is not installed.
> 
> dpkg: error processing package cherrytree (--install):
>  dependency problems - leaving unconfigured
> Errors were encountered while processing:
>  cherrytree
> 
The mention of python-gtk2 leads me to make a wild guess that CT might depend on Python2 which might have been dropped in Ubuntu 20.04.

**Comment by txe** [comment]
Hi, I took a look at ubuntu 20 and  though it is still possible to install `python2`, there is no `python-gtk2`. For now, you can try `cherrytree` from snap until the Gtk3 version release.
