### ISSUE TITLE
[Feature Request] Access filepath to CT file hosting CodeBox

### ISSUE THREAD

**Issue by datavectors** [giuspen/cherrytree#730]
Previously I posted on the CherryTree forum but it is plagued with spam.  I will use this now to post ideas.

I have used CT for some years and it is tightly knitted into my workflow.  I have built up a motley collection of *.ctd files which I parse as XML files.  I now plan to consolidate these many unstructured files.

On the matter of searching content (see for example [recent posts on using tags]( https://github.com/giuspen/cherrytree/issues/726)  ) I would like to embed some CodeBox apps to run various operations in each CT file.  For example I want to parse the CT *.ctd content in each file and communicate with external apps such as an XML database.

I need to find the absolute path to each CT file which hosts each CodeBox. This filepath will be used in CodeBox.

My first thought was to place the CT filepath in an environment var. However I sometimes have multiple CT sessions open so that idea will not work.

Thus I have a feature request to make this absolute filepath as a CT session variable accessible by CodeBox (while recognising that there might be multiple sessions open).

Meanwhile I searched through /usr/share/cherrytree/modules to look for the best spot to pickup this filepath.

I managed to import logging and use that but I see that the exec_run.py code is run in ~/tmp/ folder.

Where in the CT code can I dump the filepath to the CT session?

**Comment by txe** [comment]
If you are not afraid to change the code, then there is a simple solution:
You need to change in `core.py` function `def exec_code(self, *args)`:
For example, if you use in a codebox a variable `{CT_PATH}`, then in `def exec_code` you can add
```python
ct_file_path = os.path.join(self.file_dir, self.file_name)
code_val = code_val.replace("{CT_PATH}", ct_file_path)
```

**Comment by txe** [comment]
I suppose, the solution was satisfying, so I'm closing it
