### ISSUE TITLE
Python 3 syntax highlighting is incomplete

### ISSUE THREAD

**Issue by yixinBC** [giuspen/cherrytree#732]
Python 3 syntax highlighting is incomplete: def, for, yield and other keywords may be lack of highlighting
Version is cherrytree_0.39.2_win32_portable
and my language is Chinese
when I used cherrytree for making notes for python,I found that problem,but when I chose python,syntax highlighting worked very well
![bug1](https://user-images.githubusercontent.com/61578883/79414363-ffd67980-7fdc-11ea-9a92-b958188b03f6.PNG)
![bug2](https://user-images.githubusercontent.com/61578883/79414368-0238d380-7fdd-11ea-9fac-d8d2aef3e911.PNG)

**Comment by txe** [comment]
Right, for some reason,  this and previous version of python3.lang don't work, I suppose, gtk2 sourceviewer is too old. But they work in C++ version which will be released soon.

You can use python2 syntax highlighting for now, and in Preferences, setup python2 command line to run python3

**Comment by txe** [comment]
The python3 syntax works fine in C++ version (soon be released), so I'm closing the issue
