### ISSUE TITLE
execute CodeBox causes xterm to run but CherryTree freezes until xterm close

### ISSUE THREAD

**Issue by datavectors** [giuspen/cherrytree#734]
Is it possible to run python3 (or other languages) scripts embedded in CodeBox so that CherryTree continues to run (without freezing) after xterm runs the CodeBox command? CherryTree will only continue when I close the xterm session.I am in Ubuntu. Otherwise the executed command works.

**Comment by txe** [comment]
Yeap, Edit->Preferences: tab "Plain Text and Code", change terminal command by adding "&" at the end.

**Comment by datavectors** [comment]
Thank you. That was easy. Now is it possible to run a number of CodeBox's and see the history of output of all commands in the terminal (I might use a different terminal such as gnome-terminal).

**Comment by txe** [comment]
You are welcome!
