### ISSUE TITLE
Problem while opening any file , The buttons in  file dialog box gets enlarged .

### ISSUE THREAD

**Issue by AshKumar06** [giuspen/cherrytree#736]
Everytime i try top open a new file the file dialog box opens but the buttons are enlarged and the icons become small & The button click doesnt works.
https://drive.google.com/open?id=1Hb5-OIXSKyX0mQ5j6zLvpCVZPEJoPWMR

**Comment by txe** [comment]
Hi, this dialog is a standard Gtk2 open-file dialog. So, I suppose, you have a problem either with Gtk theme or icon pack.

**Comment by AshKumar06** [comment]
Removed every extra icon packs and themes , reset to default theme and icon. It worked. Thanks.
