### ISSUE TITLE
small characters

### ISSUE THREAD

**Issue by malypetu** [giuspen/cherrytree#739]
Just want to report I'm getting small characters on each node and I have to go one by one and  fix each of them:

select all (ctrl + a)
ctrl + 1
ctrl + 1 again

Then is back to normal. 

Is there any way to fix this?

**Comment by txe** [comment]
What version do you use? Can you delete(or rename) the config file (Help -> Open Pref directory) to see if the issue is resolved?

**Comment by txe** [comment]
New created nodes also have that issue?

**Comment by malypetu** [comment]
Yes new nodes start with same problem. Also if I backup entire tree and
then a fresh start plus restore, it comes back again

**Comment by txe** [comment]
Well, you didn't say what version do you have.

**Comment by malypetu** [comment]
latest off them all just updated few days ago

**Comment by txe** [comment]
OK, it's very unusual.
To fix it, I need to reproduce the issue. Can you create a node with some text and with that issue, export it, and send it to me?

**Comment by malypetu** [comment]
I will, it's a bit late here in down under mate, so I'll send it to you
tomorrow morning. Cheers

**Comment by giuspen** [comment]
Could also be a (known) hidpi issue that will disappear as we deploy the new Gtk3 version

**Comment by txe** [comment]
It might, but with an example I can check tags in text buffer.

**Comment by malypetu** [comment]
Hi there
All problems solved,  all I did was to delete (rename just in case) the
config file (Help/open preference directory) and start Cherrytree
(V 0.39.2) again and all was solved.
I have created a new node and subnode and it is working fine.  One thing I
notice, old nodes were changed to a really large font, but I can revert
back to a normal font without issues.
Thanks for your help, I report back if I found any issues.
Cheers


*Amaro Roach, MIT*Senior IT Specialist



*¯¯¯¯¯**¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯**¯*
[image: Skype] Maly.petu

Please consider the environment before printing this e-mail!
Get your own email signature
<https://www.wisestamp.com/signature-in-email?utm_source=promotion&utm_medium=signature&utm_campaign=get_your_own&srcid=5193119737839616>
