### ISSUE TITLE
Arabic ligatures broken with color formatting

### ISSUE THREAD

**Issue by chenyee100** [giuspen/cherrytree#740]
Steps to reproduce:
- Type in cherrytree with Arabic language.
- Apply Formatting (Text Color Foreground or Text Color Foreground) for any letter with ligatures.
Actual Result:
- The specified letter color formatting is applied but the ligatures are broken.
![image](https://user-images.githubusercontent.com/45915529/79797079-8a590900-834e-11ea-8bcb-ffc2f3675fff.png)

Expected Result:
- The specified letter color formatting is applied with correct ligatures. (Example below from MS Word)
![image](https://user-images.githubusercontent.com/45915529/79797181-ba081100-834e-11ea-8864-54a5d8887da9.png)

**Comment by giuspen** [comment]
Please wait for the upcoming Gtk3 version and report if it still has the issue
