### ISSUE TITLE
Is there a way to add a sort of minimal customization to the color/style of h1,h2,h3 elements ?

### ISSUE THREAD

**Issue by chrixxxx** [giuspen/cherrytree#753]
I know I can modify the text color wherever I want with the text formatting options..  but what I need would be a sort of "consistency" with the visual style of the documents, a way to differentiate visually some parts of the document using its elements such as h1, h2, h3..  that applies to every document I create and if I change the element style/color that change would automatically reflect to every part of the document using it.

For example: h2 being ALWAYS a bit darker than h1..  and h3 being ALWAYS another color or italic.. 

And by the way, if that should be possibile, I would like to have more "headers" available (.h4 and .h5 at least) to this purpose.

**Comment by txe** [comment]
Yes, the sourceview (a component to show text) supports themes and it allows to change colors, backgrounds, font styles for tags.
I have plans to add ability to chose a theme as well as to customize it. It shouldn't be hard (e.g. gedit implemented it as a plugin), however I will work on it after the first release C++ version.

**Comment by crogonint** [comment]
I was just thinking that all of this would combine VERY nicely with my idea for a template document as I mentioned in https://github.com/giuspen/cherrytree/issues/1231

**Comment by tom-i** [comment]
This feature I would like a lot.. :-)

**Comment by giuspen** [comment]
This will be in upcoming 0.99.34. Three new headings h4,h5,h6 have been added and all the headings plus the 'small' can be customised in several properties.
