### ISSUE TITLE
[snap] changing theme does not work

### ISSUE THREAD

**Issue by hellsworth** [giuspen/cherrytree#755]
The theme can be changed in cherrytree by either the UI:

`Edit -> Preferences -> Plain Text and Code -> Style Scheme`

Or directly in the `~/snap/cherrytree/current/.config/cherrytree/config.cfg` file.

After restarting the cherrytree snap, we see that the new style scheme is listed in both the config file and the UI but the theme is not applied for some reason.

**Comment by giuspen** [comment]
Hi @hellsworth I do not see the issue on 18.04 native installation, I'll see later if I can reproduce on the snap and I'll see what tools I have to debug there, I confess it's the first time

**Comment by hellsworth** [comment]
Yeah this is snap only. This is something that was reported to me and I reproduced the issue but will need to fix it later..

Is it ok if I put snap only issues here? If you use issue labels, we could create a snap one.

**Comment by giuspen** [comment]
Sure @hellsworth you are welcome to report the snap issues here, just mention that it is snap only in the description 😉

**Comment by txe** [comment]
The snap version, actually, works OK.
I suppose, it's just unclear for users what that option does.

`Plain Text and Code` -> `Style Scheme`  changes a theme of  a plain text node and a codebox.
Usually, users create a rich text node and naturally don't see the difference when that option is changed. 

To change a rich node theme, they need to use `Rich Text` -> `Theme`

**Comment by giuspen** [comment]
I just tried on my 20.04 cinnamon and confirm what @txe just said, it is working OK.

**Comment by hellsworth** [comment]
> Sure @hellsworth you are welcome to report the snap issues here, just mention that it is snap only in the description wink

Ah sorry. I thought that adding [snap] to the title would have done that.. but being more clear is always better :)

**Comment by hellsworth** [comment]
Ok the user that initially reported this to me confirmed the rich text theme is really what they're after and it works fine, so closing this bug.

**Comment by giuspen** [comment]
I didn't get from [snap] maybe [snap only] would have done anyway now I know, thanks for your work @hellsworth ! ☺️

**Comment by hellsworth** [comment]
ah ok i'll use [snap only] in the future then. thank YOU for my personally favorite app :) Happy to contribute in any way i can.
