### ISSUE TITLE
Dependency missing cherrytree_0.39.2-0_all.deb under Lubuntu 20.04 LTS

### ISSUE THREAD

**Issue by ptitjoz** [giuspen/cherrytree#758]
Hello,
I can't get Cherrytree on Lubuntu 20.04 LTS anymore.

```
$ gdebi cherrytree_0.39.2-0_all.deb 
Reading package lists... Done
Building dependency tree        
Reading state information... Done
Reading state information... Done
Ce paquet ne peut pas être installé
Dependency is not satisfiable: python-enchant

```
Regards

**Comment by txe** [comment]
#749

**Comment by rexlevin** [comment]
i also have this problem, and can not install it by -f arguement.
can you provide appimage or snap?

**Comment by txe** [comment]
Currently, snap is the only solution for Ubuntu 20. Any issue with snaps is better to be ask on snap forum like https://forum.snapcraft.io/t/, they are more qualified than we in this case.

**Comment by rexlevin** [comment]
> Currently, snap is the only solution for Ubuntu 20. Any issue with snaps is better to be ask on snap forum like https://forum.snapcraft.io/t/, they are more qualified than we in this case.

thanks

**Comment by Hillsie** [comment]
Seems this solution does not open my previous documents. Snap version cannot see any nodes.

**Comment by giuspen** [comment]
probably is just looking for config.cfg in a different location so it was reset. try to file--open the document rather than relying on cherrytree to remember its location

**Comment by rexlevin** [comment]
> probably is just looking for config.cfg in a different location so it was reset. try to file--open the document rather than relying on cherrytree to remember its location

when I use `sudo snap connect cherrytree:removable-media :removable-media`, it remind`error: snap "cherrytree" has no plug named "removable-media"`

you need modify your snapcraft.yaml in snap ball, you defined slot and plug in this file.
contrast notable or sublime-text, no need defined this, or and more slot-plug in it.

sorry, I am not from a English-speaking country, my english is not very good, i hope it is clear

**Comment by giuspen** [comment]
Hi @rexlevin thanks for the notification, @hellsworth is this something you can help us with?

**Comment by hellsworth** [comment]
> Currently, snap is the only solution for Ubuntu 20. Any issue with snaps is better to be ask on snap forum like https://forum.snapcraft.io/t/, they are more qualified than we in this case.

@txe feel free to ping me if a snap question comes up. I'm always happy to help and don't necessarily watch the cherrytree issues :)

**Comment by hellsworth** [comment]
> Hi @rexlevin thanks for the notification, @hellsworth is this something you can help us with?

Actually adding the removable-media plug is a really good idea! Let me test this first but a PR is to come..

**Comment by txe** [comment]
Hi @hellsworth, ok, it's good to know!

**Comment by giuspen** [comment]
BTW we have also a flatpak now, https://www.giuspen.com/software/cherrytree-0.39.3.x86_64.flatpak and soon available in flathub but has some limitations: no python-dbus, no python-enchant and python-chardet => no centralised multiple instances, no spell check

**Comment by ptitjoz** [comment]
Hi everone
now I have this message :
![cherrytree_screen01](https://user-images.githubusercontent.com/43905501/81782191-ba34a000-94f9-11ea-9d21-8dd88b0e032c.jpg)

**Comment by ptitjoz** [comment]
For the moment, and if it helps anyone, the roundabout way to use cherrytree is to use WIN...

**Comment by txe** [comment]
@ptitjoz , you need to install freedesktop runtime
```
flatpak install flathub org.freedesktop.Platform//19.08
```
Maybe, cherrytree flatpak misses a dependency of it

**Comment by giuspen** [comment]
See https://flatpak.org/setup/ an use the flatpak from https://flathub.org/apps/details/com.giuspen.cherrytree

**Comment by ptitjoz** [comment]
> See https://flatpak.org/setup/ an use the flatpak from https://flathub.org/apps/details/com.giuspen.cherrytree

Hello
I followed the procedure and it works. Thank you very much!
Is the spell-check going to work again? 
Have a nice day

**Comment by giuspen** [comment]
For the spell check it depends how many additional packages I have to seek and build into the flatpak, I will make an attempt but cannot spend too much on it because the priority is the future Gtkmm3 version
