### ISSUE TITLE
Cherrytree and Mac (python2)

### ISSUE THREAD

**Issue by Shizzlebix** [giuspen/cherrytree#762]
Hi There! The support for Python2 was dropped on january 20.

So also the Homebrew-Support for Python2

now my cherrytree doesnt work anymore :(

**Comment by txe** [comment]
Well, time to use gentoo!
To be serious, gtk3 C++ version is coming, if gtk3 works on Mac then I don't see any reason why cherrytree won't work also.

**Comment by Shizzlebix** [comment]
wll i love gentoo and on my own notebooks and servers are overall gentoo but at my work notbook is mac os so i must use mac os

**Comment by Shizzlebix** [comment]
i have try build "future" by myself.

`cmake ../future
Traceback (most recent call last):
  File "/Users/dkovacs/cherrytree/future/scripts/gresource_to_c.py", line 9, in <module>
    from lxml import etree
ModuleNotFoundError: No module named 'lxml'
-- Configuring done
CMake Error at src/ct/CMakeLists.txt:57 (add_executable):
  Cannot find source file:

    icons.gresource.cc

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at src/ct/CMakeLists.txt:57 (add_executable):
  No SOURCES given to target: cherrytree


CMake Generate step failed.  Build files cannot be regenerated correctly.`

**Comment by giuspen** [comment]
You have to install python3-lxml

**Comment by Shizzlebix** [comment]
thanks giuspen... i hope you and your family are healthly....

brew search python3-lxml
No formula or cask found for "python3-lxml"
there is no packet named so :(

brew search lxml
==> Formulae
html-xml-utils ✔

**Comment by giuspen** [comment]
We're fine thanks :)
Try
brew search python-lxml

**Comment by giuspen** [comment]
Otherwise, if you have python 3 installed try:
pip install python-lxml

**Comment by Shizzlebix** [comment]
for other people with mac `curl https://bootstrap.pypa.io/get-pip.py -o ~/Downloads/get-pip.py`
then install lxml
`pip3 install lxml`

now cmake seems nice ... 

but make ...

`1 error generated.
make[2]: *** [src/7za/CMakeFiles/7za_static.dir/CPP/7zip/Crypto/RandGen.cpp.o] Error 1
make[1]: *** [src/7za/CMakeFiles/7za_static.dir/all] Error 2
make: *** [all] Error 2`

**Comment by txe** [comment]
Hi @Shizzlebix, 
I added building and installing for macos, though it wasn't tested much.
Read future/README.md how to do it.

**Comment by jackgca** [comment]
> Hi @Shizzlebix,
> I added building and installing for macos, though it wasn't tested much.
> Read future/README.md how to do it.

I followed the instructions and got it to work after install the most recent Command Line Tools from here: https://developer.apple.com/download/more/

**Comment by txe** [comment]
So, your issue was that you didn't have apple llvm compiler installed, right?
Thanks, I will reflect this in README.

**Comment by jackgca** [comment]
> So, your issue was that you didn't have apple llvm compiler installed, right?
> Thanks, I will reflect this in README.

Yes, this was the error I got when building:

`xml/HTMLparser.h:15:10: fatal error:
        'libxml/xmlversion.g' file not found`

No issues with building after I installed the Command Line Tools. I'm on MacOS Catalina by the way. CherryTree runs fine, although I've run into some bugs that I'll start documenting.

**Comment by txe** [comment]
Hmm, for me it looks like `make` didn't see libxml.
I'm looking forward to seeing this bug list )

**Comment by Shizzlebix** [comment]
many thanks for you work but the problem is the same :(
In file included from /Users/dkovacs/cherrytree/future/src/ct/ct_clipboard.cc:30:
In file included from /Users/dkovacs/cherrytree/future/src/ct/ct_imports.h:28:
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/libxml2/libxml/HTMLparser.h:15:10: fatal error: 'libxml/xmlversion.h' file not found
#include <libxml/xmlversion.h>
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.

all packages i checked with you readme and they are all was installed before

**Comment by Shizzlebix** [comment]
Many thanks for your work... we are sure you can find this problem

**Comment by txe** [comment]
Hi @Shizzlebix 
I probably fixed it, could you update source and do `cmake` and `make` commands?

**Comment by Shizzlebix** [comment]
yeaah what a nice work ... now it is also in german if i choose this :)

Thank you..

**Comment by txe** [comment]
Good!
Few commands are not implemented yet, but it should work ok.
If you have any issues or comments, don't hesitate to write it, I'll try to fix them.

**Comment by kencu** [comment]
FYI, this works now to install the python version:
```
sudo port -v install cherrytree
```
If you don't already have an X11 server installed (Like XQuartz.app, for example) you'll need one:
```
sudo port -v -N install xorg-server
```

**Comment by kencu** [comment]
the python2 version of CherryTree on MacPorts runs on every macOS system from 10.4 PPC to Catalina, and there are no plans to remove python27 support from MacPorts.

When the c++ version of CherryTree is ready, we'll offer that as well for those who prefer it.
