### ISSUE TITLE
Disable cpputest?

### ISSUE THREAD

**Issue by funnelfiasco** [giuspen/cherrytree#763]
I'm working on packaging the future version for Fedora 32 (the loss of Python 2 packages is turning maintaining my [COPR repo](https://copr.fedorainfracloud.org/coprs/bcotton/cherrytree/) into more of a burden that I'd like). I have a working build locally, but is it possible to optionally disable the need for cpputest so that I don't have to package that first?

**Comment by giuspen** [comment]
Hi @funnelfiasco cpputest is needed to build but not to run, so it must definitely not be something you have to package

**Comment by funnelfiasco** [comment]
Is it possible to build without cpputest?

**Comment by giuspen** [comment]
I'll try and decouple the unit tests and let you know.

**Comment by txe** [comment]
To turn off tests, use `cmake -DBUILD_TESTING=OFF`

**Comment by funnelfiasco** [comment]
Thanks, I just ran a build without the cpputest dependency it worked as expected. I appreciate the effort!
