### ISSUE TITLE
Password special char issue

### ISSUE THREAD

**Issue by jdsys271** [giuspen/cherrytree#764]
I believe when setting a password the char > causes an issue whereby the program is then redirecting half the output to a log file which also names the log file the rest of the password after the > sign.

I believe this is what the user in this issue https://github.com/giuspen/cherrytree/issues/490 is referring to.

Please reproduce by creating a new ctx file and setting a password of `283ts83yrn23h8>34hc78cyh` to see what i mean.

This has been ongoing since version 0.38.6 as far as i know.

I tested this on version 0.39.1 on Ubuntu via terminal `./cherrytree-0.39.1/cherrytree`

**Comment by txe** [comment]
You are right, thanks!
I'll put fix ASAP

**Comment by jdsys271** [comment]
@txe is there a possibility to actually allow the use of < > without issues?

**Comment by txe** [comment]
it's just for pygtk version, c++ version doesn't have such limitations and will be released soon
