### ISSUE TITLE
Fedora 32 installation Error

### ISSUE THREAD

**Issue by overnxt** [giuspen/cherrytree#766]
Error: 
 Problem: conflicting requests
  - nothing provides python2-appindicator needed by cherrytree-0.38.10-1.fc32.noarch

**Comment by giuspen** [comment]
https://snapcraft.io/cherrytree new Gtkmm3 version coming soon

**Comment by sklages** [comment]
Well ... when do you think the Gtkmm3 version is in beta so we can try it? 

I just updated to Fedora 32 and cannot use Cherrytree anymore (which I need). I installed it though via snap as recommended, but I got:

![image](https://user-images.githubusercontent.com/1837422/80684572-28bf3a00-8ac6-11ea-83b8-aa92151be66b.png)

So font rendering is hmm, broken here? This is standard GNOME desktop. Any idea?

Any chance to provide a `flatpak` package? 

thanks,
Sven

**Comment by txe** [comment]
can it help you?
https://copr.fedorainfracloud.org/coprs/bcotton/cherrytree/

**Comment by sklages** [comment]
Well, this is from where I always installed cherrytree, with current Fedora 32 it leads to https://www.reddit.com/r/Fedora/comments/g9w8h2/cherry_tree_cannot_be_installed_on_fedora_32/

https://snapcraft.io/cherrytree has been recommended by the developer while waiting for the new version :-) 

Fedora 32 is my working system .. this means I have to (temporarely) switch to another app if there is no solution :-(

**Comment by giuspen** [comment]
python2-appindicator is not essential, can be removed from rpm dependencies. I may have a look to the flatpak you may contact the snap maintainer for support with the snap

**Comment by funnelfiasco** [comment]
Good news! I've packaged `cherrytree-future` in that COPR repo. It intentionally does not obsolete the cherrytree package, because I want to make this an explicit decision for the user. But I'm using it and it works well. If you encounter any package issues, you can file a bug in my [GitHub repo](https://github.com/funnelfiasco/copr-cherrytree/issues).

**Comment by sklages** [comment]
Works like a charm, thanks!

Is this some kind of beta of the Gtkmm3 version? It's looks a bit different (icons) and has the version number 0.01 ...

**Comment by giuspen** [comment]
@sklages it is more of an alpha be careful and not feature complete yet, about the version number I need to discuss with @txe

**Comment by hellsworth** [comment]
Regarding fonts with snaps on fedora and arch systems, there is [a known issue with libfontconfig with snaps on these systems](https://forum.snapcraft.io/t/snapped-app-not-loading-fonts-on-fedora-and-arch/12484). This is something that some of us have been pushing to fix with snaps but in the meantime, this will remain an inconvenience (so sorry about that).

@giuspen we could try to make a flatpak (fontconfig works fine there). If you have time/interest and want to give it a shot, looking at the [glimpse flatpak metadata](https://github.com/glimpse-editor/Glimpse/blob/dev-g210/build-aux/flatpak/org.glimpse_editor.Glimpse.json) is a good example. I've been meaning to do this for some time but just haven't gotten to it yet :)

**Comment by txe** [comment]
Actually, there is more-or-less working flatpak from #346. The manifest can be used to put cherrytree in flathub, and updated for the last version cherrytree, it will take about 5 minutes.

Yesterday, I tried to build that flatpak myself, if worked ok, though I don't like the default gtk theme there.

**Comment by hellsworth** [comment]
Ah that's wonderful! Good job :)

**Comment by txe** [comment]
Well, all credits to @rszibele

**Comment by giuspen** [comment]
I created https://www.giuspen.com/software/CherryTree-0.39.3.x86_64.flatpak also linked from https://www.giuspen.com/cherrytree/#downl - trying to have it in flathub but it is missing a file at the moment https://github.com/flathub/flathub/pull/1484#pullrequestreview-404635973
Note that this package has NO python-dbus, python-enchant and python-chardet => no centralised multiple instances, no spell check
