### ISSUE TITLE
Cherrytree won't open

### ISSUE THREAD

**Issue by MJimitater** [giuspen/cherrytree#767]
From one day to the next, I can't open CT anymore. When I click on it, the cursor turns to the spinning ball for 5 seconds, but then nothing happens. 
Rebooting and Re-installing (.deb) CT didn't help. 
Never experienced this before. What am I missing?

Im on Ubuntu 19.10 with CherryTree v. 0.39.2.

P.S. Huge credit to @txe and @giuspen for outstanding work!

**EDIT:** I installed the snap package and then CT worked again! 
Not sure how and why this all happend, so I'll leave this issue open.

**Comment by txe** [comment]
I could suggest to run cherrytree in console to see if it would give some errors/warnings.
Now, with reinstalled app, it's harder to do. Anyway, c++ version is coming soon

**Comment by MJimitater** [comment]
I was curious and checked the terminal after all, if I can help making CT better, then I will:

```
$ cherrytree
  File "/bin/cherrytree", line 105
    print "cherrytree [filepath [-n nodename] [-x export_to_html_dir] [-t export_to_txt_dir] [-p export_to_pdf_path] [-w]]"
                                                                                                                          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("cherrytree [filepath [-n nodename] [-x export_to_html_dir] [-t export_to_txt_dir] [-p export_to_pdf_path] [-w]]")?
```

**Comment by txe** [comment]
well, the same story in #722

**Comment by MJimitater** [comment]
Oh yes, that rings a bell: I was fed up always writing `python3`, so I created an alias for it and called it simply `python`. That might be reason. Thanks @txe !

**Comment by txe** [comment]
You are welcome!
