### ISSUE TITLE
None of the text formatting shortcuts work while using Kurdish keyboard layout

### ISSUE THREAD

**Issue by TimmSkiller** [giuspen/cherrytree#768]
Hi. 
I'm using an Kurdish (Iraq, Arabic-Latin) keyboard layout to write in cherrytree. Issue is: None of the keyboard shortcuts for text formatting work while using it. Example: CTRL + B (to make text bold), etc. This works perfectly in English, but not in Kurdish. I always have to press the buttons on the top toolbar to format the text.
Not even stuff like CTRL + A works to highlight text.
Cherrytree: 0.39.2
OS: Linux Mint 19.3

**Comment by txe** [comment]
The latest cherrytree is 019.2?
What layout do you use? because I just tried Arabic(AZERTY) and shortcuts work fine.

**Comment by TimmSkiller** [comment]
Not sure if this is bad or something, but the version info shows I'm using version 0.39.2. 
Sorry, I actually messed up in my original post. I'm actually using Kurdish (Arabic-Latin), which is an RTL script. It seems to work normally with normal Arabic (not AZERTY) as well, but not with Kurdish. This is kinda strange as they are both very similar and RTL.

**Comment by txe** [comment]
You right about the version, my mistake

**Comment by txe** [comment]
Well, that layout doesn't work. And I checked it in other gtk2/gtk3 apps (doesn't work at all), qt5 (odd behavior on some shortcuts), only vscode works ok.
I don't think it's going to be fixed. I see some more Kurdish layouts there (at least on Arch), they look ok.

**Comment by TimmSkiller** [comment]
Seems like that particular layout isn't supported well. The same layout on Windows works perfectly. I will look into the other Kurdish keyboard layouts. Thanks anyway.
