### ISSUE TITLE
cherrytree 0.0.1 future: Focus not working correctly? Shortcuts are applied to wrong window.

### ISSUE THREAD

**Issue by sklages** [giuspen/cherrytree#772]
When editing the content of a node, all keyboard shortcuts are applied to the tree window.

E.g. I am writing some text and want to delete a char with DEL, then cherrytree asks me if I am sure that I want to delete the node.

Or using SHIFT-ARROW-LRUP inside notes results in funnily moving notes ... (usually used for marking text).

When removing or altering those keyboard shortcuts, it works just fine.

E.g. removing DEL from shortcut list (by selecting "no keyboard shortcut"), I can still use DEL when tree window has the focus for removing notes. And it works just as intended when editing text ..

Notes cannot be moved by mouse, is this intentional behaviour?

Fedora 32, GNOME 3.36.1, Cherrytree 0.0.1

**Comment by txe** [comment]
I'll fix shortcuts ASAP.
Not moving by drag and drop is not intentional, it will be fixed.
Thanks for issues.

**Comment by txe** [comment]
There is some issues with shortcuts, as temporary workaround, some shortcuts (like with arrows) will work only in the tree window.

I added drag and drop for nodes

**Comment by txe** [comment]
Thanks for testing!
