### ISSUE TITLE
cherrytree-future slow loading

### ISSUE THREAD

**Issue by dodona2** [giuspen/cherrytree#774]
cherrytree-future needs several minutes starting. However cherrytree-python was much faster with the same big database. I suspect something wrong with the data loading and parsing algorithm.

**Comment by txe** [comment]
Hi, what file type do you use?

**Comment by dodona2** [comment]
ct.ctd: XML 1.0 document, UTF-8 Unicode text, with very long lines

**Comment by txe** [comment]
Ок, I suppose, you don't want to show the file even to @giuspen.
In menu, Tree -> Tree Info, can you make a screenshot of that dialog?

**Comment by dodona2** [comment]
Tree -> Tree Info doesn't do anything.
There are 3 databases including the cherrytree manual.

**Comment by txe** [comment]
Sorry, I meant Tree Info in python version.

**Comment by txe** [comment]
Are you saying, cherrytree-future opens the manual too slow?

**Comment by txe** [comment]
Ok, I imported the manual a few times to make the file big and now it opens slow, I'm going to fix.

**Comment by dodona2** [comment]
I mean that I imported the manual in the database.  The database is 3.5 mb big.

Thank you for fixing the problem.

Beside this or that menu entry doesn't do anything there are codebox property conversion errors, as it converts a 22px high to 42 px codebox. 

However its a alpha release, and i support the move to c++ as I feel that cherrybox, which once was small and fast, became so powerful that it drives python beyond its ends.

**Comment by txe** [comment]
It fixes slow opening, but now you have slow saving :)
I will keep working on it, also I'll take a look at the codebox issue.

Thanks for testing!

**Comment by dodona2** [comment]
_dnf info cherrytree-future_ 
announces a 'available package', ie. the update, beside the installed package. However same version number as the already installed package, A dnf upgrade or update doesn't do anything. I never saw something like that.

Last metadata expiration check: 0:07:24 ago on Sun 03 May 2020 08:16:03 PM CEST.
**Installed Packages**
Name         : cherrytree-future
Version      : 0.0.1.20200427git7a26f27
Release      : 2.fc32
Architecture : x86_64
Size         : 4.1 M
Source       : cherrytree-future-0.0.1.20200427git7a26f27-2.fc32.src.rpm
Repository   : @System
From repo    : copr:copr.fedorainfracloud.org:bcotton:cherrytree
Summary      : Hierarchical note taking application
URL          : http://www.giuspen.com/cherrytree/
License      : GPLv3+
Description  : CherryTree is a hierarchical note taking application, featuring rich text and
             : syntax highlighting, storing all the data (including images) in a single XML
             : file with extension ".ctd".

**Available Packages**
Name         : cherrytree-future
Version      : 0.0.1.20200427git7a26f27
Release      : 2.fc32
Architecture : src
Size         : 10 M
Source       : None
Repository   : copr:copr.fedorainfracloud.org:bcotton:cherrytree
Summary      : Hierarchical note taking application
URL          : http://www.giuspen.com/cherrytree/
License      : GPLv3+
Description  : CherryTree is a hierarchical note taking application, featuring rich text and
             : syntax highlighting, storing all the data (including images) in a single XML
             : file with extension ".ctd".

**Comment by txe** [comment]
git7a26f27 is 5 days ago commit

**Comment by dodona2** [comment]
so your updated version unfortunately isn't available via dnf.
I would like to continue testing.

**Comment by txe** [comment]
dfn version is @funnelfiasco initiative. His github repo:
https://github.com/funnelfiasco/copr-cherrytree/issues

You can ask him to update the package.

**Comment by dodona2** [comment]
done.
See: https://github.com/funnelfiasco/copr-cherrytree/issues/13

**Comment by txe** [comment]
I fixed codebox min height and slow saving

**Comment by dodona2** [comment]
**many thanks!!!**
Test it as soon as its available via dnf.

**Comment by dodona2** [comment]
Today I had some crashes. However I can't reproduce them. If I can then I report another issue 4 sure.
