### ISSUE TITLE
Node titles not displaying correctly

### ISSUE THREAD

**Issue by MidnightSeer** [giuspen/cherrytree#780]
Don't know what happened, but opened up cherrytree one day and BAM, illegible (the titles are in English):

![image](https://user-images.githubusercontent.com/21272239/80927948-2c291e80-8d6f-11ea-9332-0a9596518d4c.png)
I tried closing and re-opening a few times, nothing worked.

CherryTree 0.38.8
Software from debian apt (kali)

**Comment by txe** [comment]
Hi,
0.38.8 is quite old version, try to install 0.39.3 from https://www.giuspen.com/cherrytree/#downl
Also, you can try to remove (or rename to recover it later back) config file: `~/.config/cherrytree/config.cfg`
It's possible, you have issues with system fonts, can you try to change them?

**Comment by MidnightSeer** [comment]
This worked!  Strange.
`mv ~/.config/cherrytree/config.cfg ~/.config/cherrytree/config.cfg.old`

I feel stupid for not trying this!  Thank you so much.

**Comment by txe** [comment]
Actually, I have no idea why it worked, but you are welcome
