### ISSUE TITLE
Feature request: expand/collapse selected node

### ISSUE THREAD

**Issue by datavectors** [giuspen/cherrytree#784]
Currently we have ...

View > Expand All Nodes
View > Collapse All Nodes

My request is to add a new option ..

View > Expand Selected Node
View > Collapse Selected Node

This is where a particular node might have deep nesting and it is useful to selectively apply local expand/collapse rather than a global expand/collapse

**Comment by txe** [comment]
I suppose, Expand Selected Node will expand not just node, but all its children.

**Comment by txe** [comment]
Fixed in #897, expanding\collapsing all children of node can be done by wheel clicking
