### ISSUE TITLE
save and vacuum - file list item on kde but not gnome

### ISSUE THREAD

**Issue by hellsworth** [giuspen/cherrytree#786]
Possibly snap only, I'm not sure..

If I install the cherrytree snap from the stable channel (currently 0.39.2) on ubuntu (so gnome based), then the file menu *does not show* "Save and Vacuum" but if I install the very same snap version on kubuntu (so kde based), the file menu *does show* this "Save and Vacuum" item.

I see that it's a [workaround for a bug](https://www.giuspen.com/topic/save-and-vacuum/) but it should either be present on the snaps on both desktops or it should be absent from both.

**Comment by txe** [comment]
Hi, FYI, this option appears only when the current file type is sqlite, and  this option is hidden for xml type.
Are you sure you tested on the same file type?

**Comment by hellsworth** [comment]
I didn't test on any particular file. On both the ubuntu and kubuntu systems, I just launched cherrytree from the desktop icon and then went to the file menu. So does just launching cherrytree open a default file type? If so, what would cause this default file type to vary between sqlite and xml?

**Comment by giuspen** [comment]
Basically that menu item makes sense only if a sqlite type document is currently opened, so you have to open (or create) a CTB or a CTX

**Comment by hellsworth** [comment]
so but if a document isn't opened... then why does this item appear on one system when not the other? I have no idea where this difference comes from, whether the item makes sense to be there at all or not.

**Comment by giuspen** [comment]
It is strange but should not cause any issues because as soon as the user opens one type of document the right menu items will show

**Comment by hellsworth** [comment]
Ok i tested a bit more.. 

If a new instance is created and the most recently used file was a ctd or ctz, then you do not see this vacuum option. If you then make some change and save it as a ctb or ctx, then you do see this option. This behavior is consistent across ubuntu and kubuntu. So just the previously loaded file type is stored. If there hasn't been a filed opened yet because it's a fresh system and fresh install of the snap, then the default is to list the menu item as if a ctb or ctx was loaded previously.

like you said, it's really a non-issue so i'm closing it. Thanks @giuspen @txe for the clarity.

**Comment by giuspen** [comment]
Thanks @hellsworth !
