### ISSUE TITLE
Show "Recently Used" nodes on tree

### ISSUE THREAD

**Issue by abidrahmank** [giuspen/cherrytree#796]
Is it possible to add a "Recently Used" section on the tree panel on left side?

As the tree becomes very big, it will be highly productive to have recently/mostly used "N nodes" to be shown separately in the tree panel.

**Comment by txe** [comment]
I've got a question, how many nodes should be there?

**Comment by giuspen** [comment]
Hi @txe if you are going to implement this I would advise make it configurable with a default of something like 10, and this could be a persistence of the history of the last N visited nodes that already exists

**Comment by txe** [comment]
Actually, I wasn't going to do it. There are already buttons for recent nodes, also there are bookmarks. Adding one more section in the tree panel just take valuable place and I don't see much improvement by that.

**Comment by abidrahmank** [comment]
Bookmarks is more closer to what I was looking. Recent nodes buttons goes away when I close the session. So closing the issue.

Thank you guys !!!
