### ISSUE TITLE
Feature request: show XPath of any CT node

### ISSUE THREAD

**Issue by datavectors** [giuspen/cherrytree#799]
CT features can be extended even further when integrated with other tools in a tool chain.
For example a CT XML document can be pushed as a "collection" to a NOSQL database and queried on line.
To this end it would help to grab the XPath of any open CT node.
Perhaps in Tree > Tree Info ?  Show XPath.

For users using CT SQL version possibly also show the SQL path to allow building SQL queries to an online SQL server.?

**Comment by txe** [comment]
well, it's a rather specific option and it's already a lot of different options in menu. 

I can add a flag in config.cfg without showing it in the pref dialog. And then it's true, I can output xpath for the selected node in console. If it's ok, can you give an example of xpath you would like to see?

**Comment by txe** [comment]
Or there is other way. You often use codeboxes to script stuff; Maybe for you it would be more useful to have a variable in codebox which will return xpath of the current node? What do you say?

**Comment by datavectors** [comment]
**@txe** Sorry, I missed your reply. I refer in the parallel "pandoc thread" to linking CT with eXist-db and that was the context of my interest. I am going to close this request since it might cloud other issues in hand.  I can in fact parse node exports to derive xpath. And xpath is only be needed when accessing a CherryTree xml document as a pseudo XML database. Since I'm now moving towards CherryTree being a smart client to a fully fledged XML database (eXist-db) we can drop this feature request.  Thanks.

**Comment by txe** [comment]
Ok, thanks
