### ISSUE TITLE
Bug: Nested TODO ☐

### ISSUE THREAD

**Issue by Bystroushaak** [giuspen/cherrytree#80]
Can you please fix the behavior of nested todo ☐ lists?

It does strange things when you press the tab (it does indent the ☐, but only with 3 spaces, despite I use tabs and have tab indentation in settings), doesn't work with auto-indentation (nested ☐ is not created), and most importantly, you can't check the nested ☐ (cherrytree doesn't recognize them as todo boxes, but as a character).

I am using a long lists of nested todo ☐, and I have to manually copy the ☐/☑/☒ characters, which is not the best user experience.

![snimek obrazovky- poznamky ctd - -home-bystrousak-plocha-c0d3z-prace-wa-kat - cherrytree 0 35 11](https://cloud.githubusercontent.com/assets/227282/11167116/a3a2512e-8b54-11e5-901f-6cd38bf07455.png)

**Comment by Bystroushaak** [comment]
I have the ``cherrytree_0.35.11+r1706-1_all.deb`` version.

**Comment by giuspen** [comment]
Hi Bystroushaak, thank you for the bug notification and thanks again for supporting the project.
I fixed this problem please try http://www.giuspen.com/software/cherrytree_0.35.11+r1710-1_all.deb and let me know if the problem is fixed.

**Comment by giuspen** [comment]
Sorry I forgot, about the spaces even if you use tabs, that is expected and mandatory because that's how I recognise the lists and also the multiple lines in a list element (shift+enter).
Maybe it would have been better if I would have used a single tab character for the lists rather than 3 spaces but now it's done, to support two different list indentation characters would require a good effort and I don't know if it's worth the time spent

**Comment by Bystroushaak** [comment]
It seems to be working now. Thanks.

I have no problem with 3 spaces, except that it is such a random value. Could you change it to indentation level (eg. 4 spaces, when 4 space indentation is set?). If not, no problem, I can live with 3 spaces indentation.

**Comment by giuspen** [comment]
The problem in changing the number of spaces of the lists now is that people with old 3 spaces lists will find them broken. In future I'll rather consider supporting the tab as main list indentation and the 3 spaces as a legacy, but proposing the tab for new lists.

**Comment by Bystroushaak** [comment]
Now I noticed, that all list buttons work kinda strange and not at all when you have indented text or blank line.

**Comment by giuspen** [comment]
Please describe exactly how to reproduce the problem

**Comment by Bystroushaak** [comment]
![optimised](https://cloud.githubusercontent.com/assets/227282/11171053/4dc84546-8be6-11e5-9f93-f8ad9f16c10d.gif)

**Comment by Bystroushaak** [comment]
Here is the file http://kitakitsune.org/bhole/example.ctd

Try to make a list from "analýza textu".

**Comment by giuspen** [comment]
Thank you I understood the problem.
Please try http://www.giuspen.com/software/cherrytree_0.35.11+r1712-1_all.deb and let me know if the problem is fixed.

**Comment by Bystroushaak** [comment]
Works fine now. Thanks!
