### ISSUE TITLE
Copy+Paste code does not keep formt

### ISSUE THREAD

**Issue by rw3iss** [giuspen/cherrytree#804]
New cherry user here. 
I installed, made new note, tried simple cope of some JS code from VSCode into CherryTree, and it does not seem to wrap some of the lines (preferences have auto-wrap and indentation on), resulting in unreadable code.

Is there anyway to get Cherry to respect the incoming format/line endings, etc?

**Comment by txe** [comment]
Can you make a screenshot of the result? otherwise it is unclear.
In my case, when I copy/paste some code lines from vscode, these lines are inserted as one line, without splitting. Though, indention and wrapping work fine.

**Comment by rw3iss** [comment]
> Can you make a screenshot of the result? otherwise it is unclear.
> In my case, when I copy/paste some code lines from vscode, these lines are inserted as one line, without splitting. Though, indention and wrapping work fine.

That's basically what's happening.. if I copy a bunch of lines, they are inserted as one line into cherry, without proper wrapping.
Here's a screenshot.

https://imgur.com/a/IyUbRNk

**Comment by txe** [comment]
In the clipboard, data can be represented in different formats, such as plain text, html and etc. Cherrytree relies on `<br>` tag in html as a line breaker, but vscode uses `<div>` tag for that.

Right now, you can use `Paste as Plain Text`, and text will be OK although it will lose coloring. To fix coloring, you can also use codebox with js syntax highlighting (maybe everyone does this and thus no complains).

I'll fix this paste issue on weekends.

**Comment by rw3iss** [comment]
Cool, thank works, thanks... would be nice of the codebox had some resizeable handles, or one in the lower right corner... no one really knows how big it should be to contain some amount of text, just best guess... but easier to just insert, paste, resize with this interface...

**Comment by txe** [comment]
Good catch, I'll try to figure out how to add a resize grip. Additionally, there are keyboard shortcuts to change width/height, you can see them on the menu popup.

**Comment by txe** [comment]
Wow, one weekend took a whole month.
About a resize grip, there is another issue about it, so closing this
