### ISSUE TITLE
Every node stored in own file

### ISSUE THREAD

**Issue by mul787** [giuspen/cherrytree#806]
My database file has a size of 25mb and increases very quickly. The storing time increases corresponding. Furthermore I have the feeling, that cherrytree hangs more often for short time with big database files.
My idea is, that every node is stored in an own database file. Either a master file includes the file structure or the structure of an tree is stored in subfolder structure on file system level.
The benefit is, storing time decreases, because only changed nodes have be stored.

**Comment by giuspen** [comment]
Are you using the SQLite storage or XML?

**Comment by mul787** [comment]
I use the SQLite storage. I just tried the XML storage, but the storage time in this case is much more slower.

Hardware:
My computer is an Intel i7-6300 with 16GB RAM and the file is stored on internal SSD. So I think, it can't be because of it.

**Comment by txe** [comment]
I can say that splitting a file won't help with slow saving, it's already quite optimized for sqlite and the issue lays somewhere else. Can you make a screenshot of Tree Info (menu Tree -> Tree Info)?

**Comment by giuspen** [comment]
Also try File --> Save and Vacuum if it helps

**Comment by mul787** [comment]
![grafik](https://user-images.githubusercontent.com/65442117/82118835-01c95f00-977a-11ea-9edc-fb81435e684b.png)

Thats my current tree statistics

**Comment by mul787** [comment]
I use cherrytree as diary and insert many picutures

**Comment by mul787** [comment]
I will try this file on an other computer

**Comment by txe** [comment]
Do you use bookmarks?
Also, let's make a few small experiments:
- change a text in one of nodes, save
- add a image in one of nodes, save
- add a node (no need for text or image), save

These savings are same slow or there is a difference?

**Comment by mul787** [comment]
No, I'm not using bookmarks.

I have tried the experments, suggested by you and I see a context between storage time and the content of a node. If I create a node only with text, the storage time is fast. If I store one image, it's a little bit slower, but okay. But if I create or change a node, with many images, storage time increases by count (and size I think) of images in this node.

I guess like you that a split into more files will not solve the "problem". Questionable whether you can do anything at all.

By the way, it's weekend. Many thanks for very fast response, but enjoy you free time ;)

**Comment by datavectors** [comment]
> The benefit is, storing time decreases, because only changed nodes have be stored.

Perhaps the principle of rsync or rdiff might be used? That is, save nodes only if changes have been made?

**Comment by giuspen** [comment]
With SQLite It Is saving only the nodes that changed but if you have a node with 10 images and add an eleventh it is still rewriting all 11

**Comment by txe** [comment]
> That is, save nodes only if changes have been made?

Actually, it does that way.

@mul787, did you try 'Save and Vacuum'? 
Also, you can try C++ version (see future/README.md), but it's just for the test, not everyday using, so make a backup of the file before trying. If the issue still presents, I will try to reproduce the issue to fix it.

**Comment by mul787** [comment]
Yes, I use "Save and Vaccum" from time to time. But it downsizes the file only. I have never seen a correlation to storing time.

I also would like to say, that SQLite stores only the changed notes. Thats what I see, through the little experiments. But if I create or change a large node (node with many images) it takes time. We narrowed the reason down. For me is this issue resolved. The reason isn't cherrytree, it's SQLite and I think there is no way to speed up the storing time. 

Many thanks for your quick reaction and the maintenance of cherrytree!
