### ISSUE TITLE
Cherrytree stuck when trying to open node/brunch

### ISSUE THREAD

**Issue by vla7** [giuspen/cherrytree#812]
Hello.
When trying open node which contents next script https://scrpics.info/t/12b35429b6.txt, created in unknown previous version Cherrytree - program is freeze.

Linux E7470 5.4.0-28-generic #32-Ubuntu SMP Wed Apr 22 17:40:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Ubuntu 20.04 LTS
CherryTree 0.39.3 native (not snap).

**Comment by giuspen** [comment]
Hi, what syntax do you have and what document type are you using?

**Comment by vla7** [comment]
Syntax hilighting - sh.
Problem the same in both file document types, ctb and ctd.
Deleted all another nodes, left only problematic node bak_vds.rdiff and exported to xml/ctd.
Take a look, please https://scrpics.info/t/12b35429b6.txt

**Comment by vla7** [comment]
Tryed to clean this node content with text editor and then open in Cherrytree - work fine.
And now my Cherrytree work fine and not freeze on node "bak_vds.rdiff" even in my old original database. Hmm.. maybe it was some broken cache or something?

**Comment by txe** [comment]
I wonder how could you install native cherrytree on ubuntu 20 with missing python libs there?
Also, does freeze program show high cpu load?

**Comment by vla7** [comment]
> I wonder how could you install native cherrytree on ubuntu 20 with missing python libs there?
I have downloaded and installed missing packets
libappindicator1_0.4.92-4_amd64.deb
python-appindicator_0.4.92-4_amd64.deb
python-enchant_1.6.7-1_all.deb
python-gtk2_2.24.0-5.1_amd64.deb
python-gtksourceview2_2.10.1-3_amd64.deb
> Also, did freeze program show high cpu load?
Yep, something about 25 percent load of Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz

**Comment by txe** [comment]
Ah, ok
Still, it would be hard to fix the issue without reproducing it.

**Comment by giuspen** [comment]
Молодец @vla7 could you share the links to the deb packages you downloaded manually in order to have 0.19.3 running natively on 20.04 so that I will add this to the download section?

**Comment by vla7** [comment]
Here is deb packets, that needs to install Cherrytree nativey on Ubunru 20.04 x64
[cherrytree.zip](https://github.com/giuspen/cherrytree/files/4644609/cherrytree.zip)

**Comment by giuspen** [comment]
Thanks @vla7 I was hoping for URLs but appreciate your help anyway 😉

**Comment by vla7** [comment]
http://ftp.debian.org/debian/pool/main/liba/libappindicator/python-appindicator_0.4.92-4_amd64.deb
http://ftp.debian.org/debian/pool/main/liba/libappindicator/libappindicator1_0.4.92-4_amd64.deb
http://ftp.debian.org/debian/pool/main/p/pygtk/python-gtk2_2.24.0-5.1_amd64.deb
http://ftp.debian.org/debian/pool/main/p/pyenchant/python-enchant_1.6.7-1_all.deb
http://ftp.debian.org/debian/pool/main/p/pygtksourceview/python-gtksourceview2_2.10.1-3_amd64.deb
Here it is :innocent:

**Comment by giuspen** [comment]
Super! Thanks @vla7 😉

**Comment by txe** [comment]
Closing cause it's not possible to reproduce the issue
