### ISSUE TITLE
CherryTree crashes after computer wakes from sleep

### ISSUE THREAD

**Issue by gitbrake** [giuspen/cherrytree#818]
Version: 0.39.3
OS: Windows 10 Pro

As the title suggests, if I log back into my machine after the computer goes to sleep Cherry Tree crashes and I need to restart.

I'm wildly guessing it has something to do with the way Windows deals with screens/windows during sleep with DisplayPort monitors (i.e. not well).

**Comment by giuspen** [comment]
Are you using an SQLite or XML document type?

**Comment by gitbrake** [comment]
SQLite, Password Protected

**Comment by giuspen** [comment]
Can you try XML, password protected and see if it happens again?

**Comment by gitbrake** [comment]
It doesn't seem to have with an XML passworded file.

Is this something fixable with SQLite? The XML file seems to be a lot slower to save.

**Comment by giuspen** [comment]
We will be able to fix this in the Gtkmm3 version but probably not in the current Pygtk2. I can give you a version to try this issue on soon but note that it is still unstable.

**Comment by gitbrake** [comment]
Happy to test it out. I've just logged back in, it it looks like the same thing has happened with the XML, password protected file too.

**Comment by gitbrake** [comment]
I believe I've fixed the issue. Deleting inactive Monitors in Device Manager fixed the issue.

For those having a similar issue:

Open Device Manager
View > Show hidden devices
Uninstall and grayed out Monitors.

Now the issue doesn't occur.
