### ISSUE TITLE
Spell-check underlining persists after making corrections

### ISSUE THREAD

**Issue by philogit** [giuspen/cherrytree#82]
How to reproduce the error:
- Enable spell-check.
- Type a misspelled word inside a rich-text node.
- Press space to leave the word.
- The misspelled word is now underlined in red.
- Continue typing.
- Return to the misspelled word and correct its spelling.
- Move the cursor away from the word.
- **Problem here =>** The red underline remains when it should have been removed.
- Return to the word and place a space at the end.
- The red underline now disappears.

Visual example of the process:
![example](https://cloud.githubusercontent.com/assets/12819820/11197730/49099c7e-8c74-11e5-880f-3048b0455016.gif)

**Comment by txe** [comment]
Closing, there is no such issue on Gtk3 version
