### ISSUE TITLE
snap: All the letters are squares

### ISSUE THREAD

**Issue by steveno** [giuspen/cherrytree#820]
I installed cherrytree through the snap store on Ubuntu 20.04

![image](https://user-images.githubusercontent.com/116258/82498687-6a884280-9abe-11ea-853d-2f0d8ef4a78f.png)

**Comment by giuspen** [comment]
You can either try https://flathub.org/apps/details/com.giuspen.cherrytree or there is a way to install the native package documented at https://github.com/giuspen/cherrytree/issues/812 that I have not had time to test myself though

**Comment by steveno** [comment]
Looks like it's a known issue: https://github.com/giuspen/cherrytree/issues/766#issuecomment-622447089
