### ISSUE TITLE
CheeryTree Wordpress SPAM filter

### ISSUE THREAD

**Issue by WeberAlex** [giuspen/cherrytree#821]
I did not receive a confirmation email after signing-in on your CherryTree WordPress forum, but I could change my password. As a result, the SPAM filer kicks in every time and there is no contact form on the forum. Can you help with this issue?

[https://i.paste.pics/92H5H.png](url)

**Comment by giuspen** [comment]
I'm sorry the forum is a mess with more spam then real content and same for the users, I'll have to reset everything unfortunately

**Comment by WeberAlex** [comment]
Let me ask here, on Windows 10 the font size of the menus and the preferences are tiny. Any chance to have a setting to increase the font size of the GUI in the same way we can increase the toolbar icons?

Screenshot: https://paste.pics/8YUMN

**Comment by giuspen** [comment]
In the upcoming Gtkmm3 version the problem should go, if not we'll sort it out. You can try at the bottom of the download section of the cherrytree homepage you find version 0.99.0 that is meant only for testing so be careful backup your data before trying it

**Comment by WeberAlex** [comment]
Indeed it does. Thanks. When will it be ported to the stable version?

**Comment by giuspen** [comment]
Difficult to say but should be one or two months
