### ISSUE TITLE
[Feature request] Edit > Insert Iframe

### ISSUE THREAD

**Issue by datavectors** [giuspen/cherrytree#831]
Edit > Insert Iframe

So for example the issue (further below) about improved tables format could be solved by referring to Google Sheets table through iframe? Or linking to a ShinyApp?

**Comment by txe** [comment]
I'm not sure if it's possible because gtksourceview is not related to any browser or html engine.
Also, I cannot recall any gtk app having such functional. If you know any one, it would be helpful.

**Comment by datavectors** [comment]
I was reading here ..

https://expressionengine.stackexchange.com/questions/38940/can-i-put-markup-inside-an-iframe-tag-in-a-rich-text-field

**Comment by txe** [comment]
Yes, I understand that, but that is for web based apps (Electron, WebKit, etc). `Gtksourceview` we use is just a text editor, and, for example, web links are fakes, they just look like that and we have to deal with clicking on them and their behavior. 
There is no way to just add iframe and it will work, there is no iframe here or any similar.
