### ISSUE TITLE
C++ missing bookmark icon in treelist

### ISSUE THREAD

**Issue by mahdi1234** [giuspen/cherrytree#834]
0.39 has bookmark icon
![bookmark_tree_list](https://user-images.githubusercontent.com/1097047/82740446-55b6e380-9d38-11ea-9215-f1723e4de916.png)
0.99 doesn't
![bookmark_tree_list_new](https://user-images.githubusercontent.com/1097047/82740447-5bacc480-9d38-11ea-8c46-98fb0d82eec9.png)

**Comment by txe** [comment]
Hi
There is a scrollbar at the bottom of the tree panel. If you scroll to the right, do you see the icon? Can you make that node read-only and see if this icon is there too?

**Comment by mahdi1234** [comment]
Ah, you're right, it's just that scrollbar is really tiny and in older version it somehow fit the size (or wrapped, I cannot verify anymore on gentoo, on Win machine I can see with 0.39 with much more narrow view, first image here).

**Comment by txe** [comment]
You're also right, text wrapping in tree doesn't work. I'll take a look.

**Comment by txe** [comment]
Hi,  I tried to fix wrapping titles in TreeView, but it's broken and the bug in bugzilla is not going to be fixed. Gnome may introduce a new control in Gtk4 to fix the issue.
