### ISSUE TITLE
C++ arrow keys in search results 100% CPU usage

### ISSUE THREAD

**Issue by mahdi1234** [giuspen/cherrytree#835]
Latest C++ build

- CTRL + T for something which returns more than few results
- DOWN key with one second timeout

= everything's ok

- CTRL + T for something which returns more than few results
- hold DOWN key

= CPU hogs 100% and have to kill app (I recall similar bug years ago)

Linux/gentoo. Not sure I can add some debug log for this?

**Comment by ForeverRainbow** [comment]
I cannot reproduce this, just tested it with 243 results on Fedora 32 (latest build), if I hold it down the UI starts noticeably lagging and one of my cores will start going up to around 40-80%, but I do not at any point get a complete UI freeze.

My specs:
- i5-3320M
- 8gb ram
- Fedora 32

**Comment by txe** [comment]
I confirm the issue at least on release (use not search but search in Node names as mentioned in the issue). I'll take a look.

**Comment by txe** [comment]
Thanks for the issue,
I fixed it and if you know how to update from the source, you can do it.

**Comment by mahdi1234** [comment]
Confirmed, fixed in 49b53b24d2c49ea812aae09decb90d29f7478543 cheers.
