### ISSUE TITLE
gtkmm3/C++: Html Paste Bug

### ISSUE THREAD

**Issue by metal450** [giuspen/cherrytree#836]
It seems like HTML paste isn't quite working yet. Here's a screenshot: https://lnk2.tk/snaps/2020-05-24_10.52.36.png

The source text is on the left, and you can see the result of pasting into the old app, & the new gtkmm3 app. Pasting into gtkmm3 results in that "header text" at the top, & many extra newlines throughout (including some mid-line splits).

**Comment by txe** [comment]
Hi, I cannot open the given link, can you upload the image somewhere else?

**Comment by metal450** [comment]
Strange - does the link work for you now? It's possible the firewall might ave been blocking connections from Russia.

In any case, here it is directly via Github :)

![2020-05-24_10 52 36](https://user-images.githubusercontent.com/1877409/82798340-3fd71a80-9e2d-11ea-8b80-ebe322522437.png)

**Comment by txe** [comment]
Yeah, it might be a reason. Thanks, I could reproduce the bug.

**Comment by metal450** [comment]
I changed the firewall, can you get to the original screenshot link now?

**Comment by txe** [comment]
Yes

**Comment by metal450** [comment]
Perfect :)

**Comment by txe** [comment]
Thanks for the issue, you can update the app from the source (if you know how)

**Comment by metal450** [comment]
I don't know how, I used the exe giuspen provided here: https://www.giuspen.com/software/cherrytree_0.99.0_win64_portable.7z

**Comment by giuspen** [comment]
I will create another snapshot later and report it here

**Comment by giuspen** [comment]
I will keep updating the packages without all the time updating the version, look at the the timestamp I will update just before the dev packages, links available at the end of section https://www.giuspen.com/cherrytree/#downl

**Comment by metal450** [comment]
Great!  This build is much better - on a cursory test, just 2 more issues remain:

* Justification is lost (center or right)
* Sizes mostly work, but while text that's "moderately small" pastes as small, text that's "even smaller" pastes as normal again.

Here's a screenshot to illustrate (see text small vs text tiny): https://lnk2.tk/snaps/2020-05-25_12.01.46.png
