### ISSUE TITLE
Toggling formatting Header{1,2,3} only affects first character instead of whole paragraph

### ISSUE THREAD

**Issue by sm8ps** [giuspen/cherrytree#84]
This used to work up until a few months ago. (Sorry to be so unprecise! I do recall that it worked without a flaw until then because I use it regularly.)
Steps to reproduce: Click anywhere into a paragraph and mark it as Header1. Do so again.
Expected result: Paragraph should be formatted as regular text.
Effective outcome: Only the first letter of that paragraph is formatted as regular text; the rest remains Header1.
Comment: This behaviour seems to persist for any styles except for bold, italic, underlined, strike-out and fixed-with
Importance: Since there is no command to format a paragraph as regular text, one cannot revert from having selected any such style other than "toggling" the style for each letter one-by-one.

I use CherryTree every day and it has proven highly valuable for collecting any type of notes. Thank you for this excellent piece of software!

**Comment by giuspen** [comment]
Hi, I can see the problem, I'll fix soon.
You can use Remove Formatting Shift+Ctrl+R to remove all the formatting
from selected text.
Regards,
Giuseppe.

**Comment by giuspen** [comment]
The fix was faster than I expect. Would you be available to test this fix?
If yes what package you need? (what is your operative system?)

**Comment by sm8ps** [comment]
Am 28.11.2015 um 23:45 schrieb Giuseppe:
> The fix was faster than I expect. Would you be available to test this fix?
> If yes what package you need? (what is your operative system?)

Many thanks for getting to this issue so quickly! I can test on Ubuntu 
12.04 (preferred) or 14.04.

Cheers!
Stefan Müller, Switzerland

**Comment by giuspen** [comment]
Hello Stefan, please try
http://www.giuspen.com/software/cherrytree_0.36.0+r1725-1_all.deb and let
me know if it works properly now.
Cheers,
Giuseppe.

**Comment by sm8ps** [comment]
I am happy to say that the above version fixes the issue. Looking forward to using the updated release on my production machine. Happy note taking!
Cheers!
Stefan
