### ISSUE TITLE
C++ repeated search doesn't select node when exactly one entry

### ISSUE THREAD

**Issue by mahdi1234** [giuspen/cherrytree#842]
with 49b53b24d2c49ea812aae09decb90d29f7478543

- CTRL+SHIFT+F
- type some text which returns exactly one result

Node containing text correctly selected

- Escape to close search dialog
- click with mouse on some different node in tree list
- CTRL+SHIFT+F
- type same text as before

This time node is not selected. One has to search for different text and only then original search works once again.

**Comment by txe** [comment]
Thanks for the issue!
