### ISSUE TITLE
C++: Corrupted File

### ISSUE THREAD

**Issue by metal450** [giuspen/cherrytree#846]
I was going back and forth testing between the C++ & Python versions, and at one point, I stopped being able to load the ctb file in the old Python version.  When I launch, it tells me to view the log file, which shows:

Traceback (most recent call last):
  File "core.pyc", line 3120, in on_node_changed
  File "core.pyc", line 3234, in get_textbuffer_from_tree_iter
  File "ctdb.pyc", line 489, in read_db_node_content
sqlite3.OperationalError: Could not decode to UTF-8 column 'txt' with text '<?xml version="1.0" encoding="UTF-8"?>
<node><rich_text justification="left"></rich_text><rich_text>
</rich_text><rich_text background="#00ff00" wei
Traceback (most recent call last):
  File "cherrytree", line 114, in <module>
  File "cherrytree", line 79, in f_main
  File "main.pyc", line 257, in main
  File "main.pyc", line 89, in __init__
  File "main.pyc", line 94, in window_open_new
  File "core.pyc", line 255, in __init__
  File "core.pyc", line 1542, in file_startup_load
  File "config.pyc", line 816, in set_tree_path_and_cursor_pos
AttributeError: 'NoneType' object has no attribute 'place_cursor'

At the same time, I became unable to view one of the nodes in the C++ version, which immediately crashes when clicking that node.  I'm assuming that node got corrupted by the new version, & neither version was able to deal with the corrupted data.

**Comment by ForeverRainbow** [comment]
Do you have the ctb file still?

**Comment by metal450** [comment]
Unfortunately not.

**Comment by txe** [comment]
I can guess that it maybe related to the previous issue when command `List->Set/Unset ToDo List` generated garbage and that saved garbage breaks the parser or something like that. Actually, I'm going to check this idea.

@metal450, if you will have such file again and for some reason it cannot be provided, we can give you a specially prepared build to diagnose the issue.

**Comment by metal450** [comment]
Sure, will let you know if it happens again. I have had the C++ version crash quite a few times, my thought was that perhaps it crashed while trying to write the database or something, leaving it in a partially-written state. Just an un-educated guess, tho.

**Comment by txe** [comment]
Hmm,
maybe you can guess/remember what you did before it crashed on saving such as copy\paste, moving nodes, etc?

**Comment by metal450** [comment]
Definitely not moving nodes.  It was likely one of two possible things: playing with the application preferences, or migrating my data from OneNote (which would specifically mean: pasting text, then manually adjusting formatting to fix discrepancies, and/or inserting file attachments).

(Note though that I've temporarily paused moving over my data as I wasn't able to figure out a solution for #849, which I realized was causing me to lose context on a decent portion of my notes)

**Comment by txe** [comment]
I suppose we still cannot reproduce this issue, so closing

**Comment by metal450** [comment]
Fair enough, I'll follow up if it happens again.
