### ISSUE TITLE
C++ ToDo List Inserts Garbled Text

### ISSUE THREAD

**Issue by metal450** [giuspen/cherrytree#847]
In the new C++ version: if you select a few lines, & do "List->Set/Unset ToDo List," it inserts some garbled text before the first line (& the list isn't generated).  Screenshot: https://lnk2.tk/snaps/2020-05-25_22.19.16.png

**Comment by txe** [comment]
Probably, @ForeverRainbow fixed it in his last PR (not committed yet)

**Comment by ForeverRainbow** [comment]
Yep this should now be fixed

**Comment by txe** [comment]
I'll test it lately to be sure

**Comment by txe** [comment]
The issue looks to be fixed, so closing it
