### ISSUE TITLE
C++: Spell Check Not Available

### ISSUE THREAD

**Issue by metal450** [giuspen/cherrytree#848]
In the new C++ version (on Windows), Spell Check is not available: if you enable it via the options, there's nothing available under "Spell Check Language" dropdown, & the text content isn't spell-checked. Perhaps the dictionary was just forgotten in the bundle?

**Comment by txe** [comment]
@giuspen , msys2 has only de, en, es, fr, ru. Do we need more (I can try to copy dictionaries from linux) and if yes, which ones?

**Comment by giuspen** [comment]
@txe I will look at this issue before releasing the next msys2 archive I will verify that the languages that we support have a dictionary installed

**Comment by metal450** [comment]
Just gave this a look.  There are some languages there now, but English is missing.  Screenshot: https://lnk2.tk/snaps/2020-06-17_15.50.03.png

**Comment by giuspen** [comment]
thanks @metal450 I'll look at this when preparing upcoming 0.99.2
