### ISSUE TITLE
[Feature request] Extract text from embedded images

### ISSUE THREAD

**Issue by datavectors** [giuspen/cherrytree#852]
My workflow places screen snapshots into CT nodes.

It would be very useful when right clicking on any embedded image to trigger a script which extracts text from image and copies text into clipboard.  The text can then be pasted.
In Ubuntu tesseract might be used for OCR.

[After thought] Since a number of these filed feature requests might not be of interest to every CT user I now wonder if it might be better to introduce optional plugins perhaps in Python.  Many apps allow community developed optional plugins and this would take the pressure off CT developers to implement feature requests.

**Comment by datavectors** [comment]
After some practical testing I realise that I can embed a link below any imagebox or codebox and call external automation scripts to operate on the box.  This offers a great deal of flexibility and does not require new features to be added to CherryTree.

**Comment by txe** [comment]
Good, I also had an idea, like having a script which monitors some folder, and any image dropped there will be converted to clipboard test.

**Comment by datavectors** [comment]
I guess this might be the point to suggest another integration.
I found that [ripgrep-all](https://github.com/phiresky/ripgrep-all) is an incredibly useful tool which extends ripgrep to scan multiple file types. Now one use of this is to quickly scan through many CherryTree files (xml and sqlite) scattered throughout my /home folder for example.

One search might be .... rga "hello" ~/ | grep .ctd

another might be ... rga "hello|world" ~/     

which uses regex in the search.  I can use the adapters to scan images.

I am using this with CherryTree for different workflows.

**Comment by martinakos** [comment]
Check this [https://github.com/giuspen/cherrytree/issues/2831#issuecomment-5352993460](https://github.com/giuspen/cherrytree/issues/2831#issuecomment-5352993460)
