### ISSUE TITLE
Cherry Tree Freezing up on Save of Large Notes

### ISSUE THREAD

**Issue by DiagonalArg** [giuspen/cherrytree#854]
I'm using Cherrytree for class notes taken from videos.  My notes include lots of screen-shots.  When a note gets big, the time to save gets very long, during which Cherrytree freezes up.  Then, I find myself setting preferences to save it less and less frequently.

1) Is it possible that this can somehow be done in the background so I am not blocked during the save?

2) Is it possible to have the setting in preferences based not just on time, but on the size of changes or the number of changes in the note since the last save?  So just off the top of my head, something like this:

```
if (note size has changed by X bytes)
or (>= Y characters have been typed)
or (>= T time has passed)
then (save)
```

**Comment by ForeverRainbow** [comment]
Possibly related (The multi-threading part really): #837

**Comment by txe** [comment]
@DiagonalArg, can you say what how many screenshots generally are in one node and their sizes (width/height)? It's to be sure the fix is good for your situation.

**Comment by DiagonalArg** [comment]
@FroeverRainbow - yes, that appears right.  My backend is also SQLite.

@txe - It would be hard to count, so I won't try now, but the freezes grow as the note gets longer.  I'm at perhaps 20 seconds now.

**Comment by txe** [comment]
Ok, I'm now taking a look at what is going on there. Tomorrow will be a fix for C++. 
What cherrytree version and OS do you use?

**Comment by DiagonalArg** [comment]
Ubuntu 16.04.  
CherryTree 0.39.3

Thanks for your work!

**Comment by DiagonalArg** [comment]
Ok, so what I did was export to HTML and then look at the product.
The .html file is 91K
The ./EmbeddedFiles directory has 1 member, size 1.8MB
The ./images directory has 185 members
The total size of ./images is 21MB

This file was already producing noticeable delays at 1/3 the size.  And I've had this problem before but just lived with it.

**Comment by txe** [comment]
Hi @DiagonalArg, I added an improvement which can help with your issue.
If you use code from github, you already can try it.
