### ISSUE TITLE
config.cfg gets massive and causes long startup time

### ISSUE THREAD

**Issue by ForeverRainbow** [giuspen/cherrytree#861]
Hi
So this is a weird issue I noticed while testing importing. Opening and closing lots of files without saving seems to accelerate (or maybe cause) this. 

My config.cfg is getting filled with special characters, doing `cat config.cfg` gives me a page of `☒☐☑☒☐☑`. I think this is possibly related to #838 - either fallout from fixing the pointer arithmetic or something off because of expecting a pointer. 

I am uploading my config file along with this: Beware it will crash your text editor (even vim struggles, vscode seems to handle it more or less fine though). This isn't a massive issue since I can always just delete the config file but it is causing start-up times of +10 seconds and seems to grow exponentially.

[config.cfg.txt](https://github.com/giuspen/cherrytree/files/4704219/config.cfg.txt)

**Comment by txe** [comment]
Yeah, these row pointers just kill me. I suppose, we need find way to remove pointers, so such issues never come up.

**Comment by mahdi1234** [comment]
Faced strange performance issues since yesterday with latest C++ and then noticed this one, same culprit.
