### ISSUE TITLE
C++ MD import complex URLs broken 

### ISSUE THREAD

**Issue by mahdi1234** [giuspen/cherrytree#864]
with 8cb978e

- import attached md file (had to zip it for github

Some complex URL are broken after import.

![md_import_urls](https://user-images.githubusercontent.com/1097047/83338778-03853d80-a2b7-11ea-8814-50f0cd0c28f2.png)
)

[File.zip](https://github.com/giuspen/cherrytree/files/4706446/File.zip)

**Comment by ForeverRainbow** [comment]
This should be an easy enough fix, thanks for spotting it!
