### ISSUE TITLE
C++ crash importing MD file

### ISSUE THREAD

**Issue by mahdi1234** [giuspen/cherrytree#865]
with 8cb978e

More or less every other MD file import crashes app. Sometimes few times in a row, sometimes it does import few times ok.
```
getdents64(13, /* 127 entries */, 32768) = 4944
openat(AT_FDCWD, "/home/mahdi/Downloads/File.md", O_RDONLY) = 18
read(18, "# File\n\n### Section\n\nsomething\n\n"..., 8191) = 1488
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0xffffffffffffffe8} ---
+++ killed by SIGSEGV +++
Segmentation fault
```
Attaching file, but it doesn't matter the content.
[File.zip](https://github.com/giuspen/cherrytree/files/4706466/File.zip)

**Comment by ForeverRainbow** [comment]
Hmm, I cannot reproduce this. Testing that file I am getting no crashes - the parser is getting very confused about brackets within link text which I will have to fix but other than that it is fine.

When testing the markdown importing I must have imported 15-20 (maybe more) markdown files so this is really weird, I will have a look into this tomorrow

**Comment by mahdi1234** [comment]
Might be somewhat related to how "fresh" book is, I could somewhat repeat it with

- Run new instance of CT
- add any node and save
- import couple times file and it crashes

the other book which was crashing for me yesterday doesn't crash anymore (and it has now some 30 nodes), really strange.

**Comment by ForeverRainbow** [comment]
It is really strange, is this happening with any other imports? Like if you try plaintext importing on `File.md` does it still crash? 

I still cannot reproduce this but I suspect it may have something to do with the way the md importer reads it data directly from a `std::ifstream` rather than buffering it with a stringstream

**Comment by txe** [comment]
Maybe it's another issue, but I can reproduce segm. fault by importing from the given md file then importing from md folder.

**Comment by ForeverRainbow** [comment]
@txe Yep I can reproduce it by doing that too, thanks!

**Comment by mahdi1234** [comment]
Cool, yep I've seen both from file and from folder, will give it a go once the one you can reproduce is fixed.

**Comment by ForeverRainbow** [comment]
:facepalm: Ok I think I know the cause of this issue. I have captured `this` within a function-static lambda. Which of course means that `this` becomes invalid when importing a different file

**Comment by mahdi1234** [comment]
Looks really great, no crashes anymore.

**Comment by txe** [comment]
Cool, thanks a lot for testing!
