### ISSUE TITLE
C++ MD import URL imported as H2 text size

### ISSUE THREAD

**Issue by mahdi1234** [giuspen/cherrytree#869]
with 33f4bc15647452e4718a950ed81a49267f39e073

Import attached File2.zip (extract first) as markdown

One URL is somewhat bigger, I assume it's wrongly assigned H2, but don't know really why.

![File2](https://user-images.githubusercontent.com/1097047/83353937-79d08100-a345-11ea-9149-0d77063cf8fb.png)
[File2.zip](https://github.com/giuspen/cherrytree/files/4707721/File2.zip)

**Comment by ForeverRainbow** [comment]
That is... weird. I am currently improving the parser so as to make it easier to implement text formatting using markdown so I shall see if this issue still exists (I suspect it will since the parsing logic is mostly unchanged), thanks for noticing it
