### ISSUE TITLE
[Feature request] Duplicate node tree

### ISSUE THREAD

**Issue by datavectors** [giuspen/cherrytree#872]
I am duplicating some node trees and unless I am missing a trick I cannot duplicate the sub-nodes (the sub tree structure) under a selected node. Only the parent node is duplicated.

At Tree > Duplicate Node i suggest another option Duplicate Node and Sub Nodes (the full depth)..

**Comment by datavectors** [comment]
I think I can close this request (at least for my purpose) since I see that I can export a sub tree of nodes and reuse those again.

Nodes > Nodes Export > export to CherryTree Document. And I can then import from CherryTree File.

**Comment by txe** [comment]
I've added a command to duplicate node with subnodes
