### ISSUE TITLE
garbled chinese character when display language is Japanese

### ISSUE THREAD

**Issue by freezewind** [giuspen/cherrytree#88]
![3063-32216-choose-display-language](https://cloud.githubusercontent.com/assets/3954389/12012868/991ec0ae-acbd-11e5-97a1-b273bd448733.png)
The node name shows garbled chinese character when windows display language is Japanese
![text](https://cloud.githubusercontent.com/assets/3954389/12012850/f023b6bc-acbc-11e5-8023-a847e20c7a96.jpg)
Also if I set the cherrytree language to zh_CN, the UI such as node properties, preferences will show garbled chinese character.
![preferences](https://cloud.githubusercontent.com/assets/3954389/12012877/dc724b82-acbd-11e5-904a-a184697a3137.jpg)

**Comment by freezewind** [comment]
Find a problem from the forums that may be related with this case.
http://www.giuspen.com/topic/proper-japanese-input-for-windows/

**Comment by piyo-gh** [comment]
I think you can solve this problem by using **pango.aliases**.

For example, I'm using Windows 10 in Japanese and default system font is **Yu Gothic UI**.
By default, many chinese characters are broken.

So, I made a file `cherrytree_portable\etc\pango\pango.aliases` and wrote a line below in it.

```
"yu gothic ui" = "yu gothic ui,microsoft jhenghei,microsoft yahei"
```

Now, I can see all chinese characters.
 ( By default, there is no **pango** folder, you need to make it in **etc** folder and make **pango.aliases** in it. )

![2](https://cloud.githubusercontent.com/assets/18474085/15034149/97a7ea9c-12ad-11e6-9d02-73f0841623a7.png)

This trick also can be used for note fonts.
I'm using **Meiryo** for RTF node and **RobotoJ Mono** for text node.
I added these lines in **pango.aliases** to show symbols and emoji.

```
meiryo = "meiryo,segoe ui,segoe ui emoji,segoe ui symbol"
"robotoj mono" = "robotoj mono,segoe ui,segoe ui emoji,segoe ui symbol"
```

Ok, you are using Windows 7, maybe default system font is **Meiryo**. 
The code below might hopefully solve your problem. 

```
meiryo = "yu gothic ui,microsoft jhenghei,microsoft yahei"
```

You might also have interest in this blog article written in Japanese.    
[GTK+ メニュー 日本語 文字化け 直し方](http://deztec.jp/x/10/faireal/d50708.xml)

**Comment by freezewind** [comment]
Thank you,I solve this problem by using pango.aliases.
始めまして、私は中国人ですけど、
日本のアニメが大好きだから、
日本語を勉強しています。
最近、日本語のゲームやプログラムを使うために日本語のWIN7を使い始めました。
ですから、piyo-ghの言う通りにしたら、問題が解決した。
ありがとうございました。
