### ISSUE TITLE
C++: symbol autoreplacement seems not to work

### ISSUE THREAD

**Issue by ynoxia** [giuspen/cherrytree#882]
Hi all,

C++ version in Fedora 32.

Automatic symbol replacement feature seems not to work. This is the test flow:

- Settings: Enable Symbol Auto Replacement option enabled

- In node: insert the sequence of characters to be replaced with the symbol (for example: (C)

- result: the sequence of characters is deleted from node, and no symbol is inserted

👍

**Comment by txe** [comment]
Hi, it was fixed recently.
 I suppose, fedora package is not updated yet, you can ask about it [here](https://github.com/funnelfiasco/copr-cherrytree)

**Comment by ynoxia** [comment]
Thank you @txe 👍

I didn't know there was this slight non-alignment.

If I independently build the C ++ version directly from this GIT channel following the instructions, is this version usable like that of copr fedora repo?

**Comment by txe** [comment]
It should be

**Comment by ynoxia** [comment]
OK. I'll try and check this issue.
