### ISSUE TITLE
Updating to gtk+3 and Python3

### ISSUE THREAD

**Issue by scsijon** [giuspen/cherrytree#885]
Just wondering, since both Python2 (2.7) and gtk+ (2.x) are now considered by their  sources as depreciated and since v4 for both are in the pipeline (a lot of code has been written while in lockdown so things will look like appearing earlier than planned), how far your up to porting to versions 3 of both.

**Comment by txe** [comment]
Code is already ported to C++/Gtk3.
It still under testing, but 0.99 version for linux/win can be downloaded from [https://www.giuspen.com/cherrytree/](https://www.giuspen.com/cherrytree/)
or can be built according cherrytree/future/README.md

**Comment by scsijon** [comment]
ok, sorry for the slow response, lockdown has caused all sorts of problems, I will give it a go and see what happens
