### ISSUE TITLE
[snap] copy image from browser

### ISSUE THREAD

**Issue by txe** [giuspen/cherrytree#887]
Hi @hellsworth , cherrytree uses `urllib2` python package for downloading images from the internet. For example, when users copy text with images from the browser and insert them into a note, instead of image links, cherrytree downloads images to paste them.

So, I see snap is missing `urllib2` python package, can it be added?
And does snap need network privileges or something like that?

**Comment by hellsworth** [comment]
You're absolutely right. I verified that adding both `python3-urllib3` package and `network` plug were needed for the picture to pasted in with text, rather than the url. So I've opened #893

**Comment by txe** [comment]
That's great!
I wonder when the ubuntu snap will be updated, so I can say users it is fixed?

**Comment by hellsworth** [comment]
The fix is in the stable cherrytree snap now.

**Comment by giuspen** [comment]
Cool thanks
