### ISSUE TITLE
Ver 0.39.3 has issues with zooming (ctrl+mouse wheel). wont release zoom after releasing ctrl key

### ISSUE THREAD

**Issue by sceptre357** [giuspen/cherrytree#889]
also ctrl+touchpad up/down results in cherrytree locked into zoom adjust mode and wont release. Only option is to restart the application every time you need to change the zoom ratio. 

OS: Debian and LinuxMint DE
DE: Cinnamon 4.4.8

**Comment by txe** [comment]
Thanks for the issue, I checked it on my system and couldn't reproduce.
On the other hand there is C++/Gtk3 version which may not have such issue.
It is still in testing, but the package can be taken from https://www.giuspen.com/cherrytree/#downl  (scroll down until you find 0.99.1)

**Comment by sceptre357** [comment]
i have 4 different systems all have the same issue. i have downloaded the deb package directly from   https://www.giuspen.com/software/cherrytree_0.39.3-0_all.deb

all the systems are running Debian 10 or LMDE 4 and have the same problem. they all have the latest distro updates and have the issue with not releasing the zoom control after its initiated. it happens either from ctrl+touchpad scroll or ctrl+mouse wheel up/down

**Comment by txe** [comment]
I couldn't install 0.39.3 deb and its dependencies on LMDE 4 (), but cherrytree flatpak installed by Software Manager works just fine.

**Comment by sceptre357** [comment]
Debian and LMDE only need one have one dependency you have to manually install, its located here.
http://archive.ubuntu.com/ubuntu/pool/universe/p/pygtksourceview/python-gtksourceview2_2.10.1-3_amd64.deb

**Comment by txe** [comment]
Ok, I can reproduce it.
The issue is caused by keyboard settings, to be exact, by XKB rules. When you press `Control` button, we get `Control` signal; when you release this `Control` button,  we get `ISO_Prev_Group` instead of `Control`. No surprise that the program works wrongly in such conditions. A lot of other programs suffer from this bug for more than 10 years.

FIY, you can see these rules by:
```
xmodmap -pke | grep Control
```

I could fixed it by changing options in `Keyboard` -> `Layouts` -> `Options` -> 'Switching to another layout' -> select `Alt+Space`
Maybe other options can also fix this bug.

**Comment by giuspen** [comment]
@txe can we capture ISO_Prev_Group as well as valid Control release?

**Comment by txe** [comment]
No, `ISO_Prev_Group` means to change keyboard layout and can be caused by any keyboard combinations (Capslock, Alt or Alt + Space, for example).

**Comment by txe** [comment]
Funny that for some reason, flatpak version doesn't have this problem in Mint. Maybe it uses its own XKB rules there.

**Comment by giuspen** [comment]
But we could capture ISO_Prev_Group just to exit the Control held down?

**Comment by txe** [comment]
Well, we can do it, I don't think it can broke anything.

**Comment by txe** [comment]
You do it? there's also `ISO_Next_Group`

**Comment by giuspen** [comment]
I can do it but I'll need your help to test it unless you tell me your trick to reproduce

**Comment by giuspen** [comment]
It would be easier if you can do it on both the pygtk2 and gtkmm3 version :)

**Comment by txe** [comment]
OK, I'll do

**Comment by giuspen** [comment]
Thanks!

**Comment by giuspen** [comment]
I will release a new minor pygtk2 version as well soon since there are few bits and pieces accumulated

**Comment by sceptre357** [comment]
I could fixed it by changing options as you suggested however it still scrolls while it changes the font size making it pretty difficult to see the size you want to select.

**Comment by txe** [comment]
I'll take a look
