### ISSUE TITLE
Wrong month entry when using F8

### ISSUE THREAD

**Issue by Fixer-007** [giuspen/cherrytree#89]
When I press F8, it makes a new “date” entry with wrong month, for example: 2015 / ѳ / 08. It gives no month at all with February or other month. And I’m not sure what this Greek symbol “ѳ” means either…

OS: Windows 7 SP1 64bit
Program language is English
System language is Ukrainian
I'm using portable version of cherrytree 0.36.1 from portableapps.

**Comment by giuspen** [comment]
I should have fixed this. Are you available to try a development version and report whether the problem appears again or not?

**Comment by Fixer-007** [comment]
I can try development version. Where I can download it for windows?

**Comment by giuspen** [comment]
Please try
http://www.giuspen.com/software/cherrytree_0.36.3+r1758_win32_portable.7z

**Comment by Fixer-007** [comment]
Bug looks fixed for me :)

:+1:

**Comment by giuspen** [comment]
Thank you!

**Comment by Fixer-007** [comment]
This issue can be closed.
