### ISSUE TITLE
[Feature request] Import codebox from a library of codebox snippets

### ISSUE THREAD

**Issue by datavectors** [giuspen/cherrytree#892]
Increasingly I am using codeboxes to run various CT operations.  It would be helpful to import codeboxes from a custom library (path to snippets library defined in preferences). Currently codebox can be saved to text file and retrieved from text file but the codebox properties have to be reset manually.

To give one example I run a codebox snippet to scour through my entire manifest of CherryTree documents, searching for keywords inside each document. This goes beyond the CherryTree local tree search feature.  This approach I use also works on both xml and sqlite files. Then I can search for keywords in all CherryTree documents.  I filter out backups (although they could be scanned if required).  All in one codebox snippet.  We might then share such codebox snippets in a community codebox snippets repo.

I can give examples of such snippets I use.

**Comment by txe** [comment]
Hi, it can be useful. If we improve codebox's clipboard copy/paste, it will cover the current issue. So, it would be easy to copy codebox in some format (text,xml,html) in another editor or file. And when this information is copied back, cherrytree will recognize data and insert codebox.
I don't think there is need for a custom import file and things like that in this case.

What do you think?

We can leave the old copy format the same, and add a new option for the new format.
You can suggest a format, e.g. text format may be like this:
```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
codebox
syntax=python
width=100
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

some code

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by datavectors** [comment]
Yes adding metadata (like yaml as in pandoc) would work fine.  For example in codebox I am currently using ripgrep to scan through all CherryTree documents for keywords. And I have many to search.

**Comment by txe** [comment]
@giuspen , I'm going to add
- an option in pref dialog, "New Codebox Clipboard Format"
- using codebox xml format for copy/paste

Is it OK? maybe you have some suggestion?

**Comment by datavectors** [comment]
Please see my later added edits on using yaml as header.

**Comment by txe** [comment]
> Yes adding metadata (like yaml as in pandoc or ansible) would work fine.

Can you give an example of how codebox format with yaml can look?

**Comment by datavectors** [comment]
See one example of using yaml file here in pandoc - [example 37 at bottom of page](https://pandoc.org/demos.html).
But much shorter yaml snippets can be used as headers to files such as codebox files.

**Comment by giuspen** [comment]
@txe if the new copy/paste format has additional info and is not worsening the readability of the code in the codebox, we may avoid the additional config option and just use the new one, then in case of users complaining we may instead give the option

**Comment by txe** [comment]
> @giuspen , For the syntax I would use an existing format, not proprietary.

Meaning, not to use yaml?

@datavectors , I actually don't see much reasoning to use yaml. I'd like to avoid adding a new parsing library (here, yaml) if it can be avoided. and I don't see how yaml can be more helpful with ripgrep than just a simple text format mention before.

**Comment by giuspen** [comment]
@txe with proprietary I meant text with a syntax made up from us. I would rather use something like yaml or JSON, a standard syntax

**Comment by datavectors** [comment]
Note: [yaml is an open format](https://en.wikipedia.org/wiki/List_of_open_formats) - not proprietary.  But codeboxes can be used without adding yaml so I for one will not mind if it is not used. In codebox content I can just refer to a yaml file as in pandoc example.

**Comment by txe** [comment]
Ok, then as a yaml example:
```yaml
codebox:
    syntax: python
    width: 100
    source: "some code"
```
@giuspen , @datavectors , Is it good?

**Comment by datavectors** [comment]
My vote is that it looks good. Variables such as height, style (as in preferences) might be added so that different codeboxes can be used rather than a global style.

**Comment by giuspen** [comment]
@txe ok for me thanks! I agree with you in trying to avoid building up dependencies but you can still parse it "manually" for now and in future if we find a lightweight library available also in msys2 we can use it :)

**Comment by giuspen** [comment]
I see both libyaml in C and libyaml-cpp are also in msys2

**Comment by ForeverRainbow** [comment]
A note on this, markdown has code boxes as part of its syntax so that could be an option as an alternative syntax for pasting if the markdown parser can be made to understand codeboxes (or it is sent through pandoc). Only issue is it would only give the highlight language and contents, not anything like width so that would have to be auto calculated or something

**Comment by txe** [comment]
well, markdown is a syntax language, and using it is not much difference than using plain text I suggested earlier.

**Comment by txe** [comment]
@datavectors , I made a pull request, you can read more in #894
