### ISSUE TITLE
BUG：sqlite3.OperationalError: unable to open database file

### ISSUE THREAD

**Issue by helloyan** [giuspen/cherrytree#90]
I have two win10 pc，one can run and the other can't，the error is ： sqlite3.OperationalError: unable to open database file，i use portable version，the install become the same

**Comment by helloyan** [comment]
I found the problem，the path of cherrytree.exe **Can't** contains blankspace OR non-ascii character

**Comment by giuspen** [comment]
Hi, are you using .ctx or .ctb?

**Comment by Eternity512** [comment]
Downloaded portable version. Launched... Error.
OS W7
Screenshot-> http://i.imgur.com/p1Yblvr.png

**Comment by Eternity512** [comment]
The problem is solved. It is necessary that the path to the program and the path to the database were in English.

**Comment by helloyan** [comment]
@Eternity512 you are right
@giuspen ctb

**Comment by warepilot** [comment]
Hello, I'm affraid I've had the same problem.
### Steps ###
Try to open a *.ctx file having non english characters in its name.
### Error ###
The password inputbox will close and the file won't load.
### Versions ###
0.37.6 on a Mint 2019
### Tested ###
The file will load only using english characters, even if you use spaces in its name.
### Questions ###
Have this something to do with locale configuration and charsets?
Is it a limitation on the password or decryptor program?

**Comment by giuspen** [comment]
@warepilot this will work fine in future gtkmm3 based version

**Comment by txe** [comment]
I checked on Win10 and Linux, the issue is resolved
