### ISSUE TITLE
compile failture on Mac

### ISSUE THREAD

**Issue by nutianlab** [giuspen/cherrytree#901]
cherrytree/future/src/ct/ct_actions_import.cc:234:24: error: 
      constructor inherited by 'CtZimImportHandler' from base class 'CtParser'
      is implicitly deleted
    CtZimImportHandler handler(_pCtMainWin->get_ct_config());
                       ^
cherrytree/future/src/ct/ct_imports.h:424:51: note: 
      constructor inherited by 'CtZimImportHandler' is implicitly deleted
      because base class 'CtTextParser' has a deleted corresponding constructor
class CtZimImportHandler: public CtImportHandler, public CtTextParser

**Comment by ForeverRainbow** [comment]
hmm, interesting I shall look into it. I assume you are using clang?

**Comment by nutianlab** [comment]
> hmm, interesting I shall look into it. I assume you are using clang?

Um, you are right.

-----

gcc -v
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.3 (clang-1103.0.32.62)
Target: x86_64-apple-darwin19.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Comment by nutianlab** [comment]
checkout latest,but still cann't compile.

cherrytree/future/src/ct/ct_import_zim_handler.cc:43:29: error: no viable constructor or deduction guide for deduction of template
      arguments of 'shared_ptr'
            std::shared_ptr file = CtImportHandler::_new_import_file(fpath, current_depth);

**Comment by giuspen** [comment]
@ForeverRainbow could you have a look at this?

**Comment by txe** [comment]
@nutianlab, it should work now

**Comment by nutianlab** [comment]
@txe @giuspen Thank you for your good co-operation and  efforts, now successful. 
happy weekend guys.
