### ISSUE TITLE
Set/unset numbered list just adds 1. to every line

### ISSUE THREAD

**Issue by auduner** [giuspen/cherrytree#91]
This used to work fine, but now i just get:
1. line
1. nextline
1. thirdline

Linux mint, CherryTree 0.36.3

**Comment by giuspen** [comment]
Please go with a real example and describe what keys you press

**Comment by auduner** [comment]
OK. I have a note that looks like this:

line
aoig
argaggg
aaaaaegge
aerg
aerg
arg
agr
arg


I select all and go to the format menu, and select "Set/unset numbered list" (or the shortcut ctrl+alt+2)

Result:

1. line
1. aoig
1. argaggg
1. aaaaaegge
1. aerg
1. aerg
1. arg
1. agr
1. arg



Linux Mint 17 Qiana 64bit
CherryTree 0.36.3

I have a different version of mint and cherrytree on my laptop, and there is no such problem there.

Audun

**Comment by giuspen** [comment]
I should have fixed the bug. Are you available to try the fix?

**Comment by auduner** [comment]
Wow, that was quick. Yes I would to try the fix. I'm kind of a noob, so I hope you can give easy instructions. I don't mind fiddling around a bit though.

**Comment by giuspen** [comment]
Hi, please download and install
http://www.giuspen.com/software/cherrytree_0.36.3+r1758-2_all.deb

**Comment by auduner** [comment]
Thanks. Yes, that fixed the problem! Numbered list is working correctly.

**Comment by giuspen** [comment]
Thank you!
