### ISSUE TITLE
Enable system tray docking on GNOME >= 3.26 doesn't work properly

### ISSUE THREAD

**Issue by ForeverRainbow** [giuspen/cherrytree#926]
GNOME removed status icons in 3.26, which means that if you are running a version of GNOME >= 3.26 the "Enable system tray docking" option will cause cherrytree to effectively go zombie and "Start Minimized in the system tray" will visually do nothing, requiring the config file to be deleted before cherrytree will start properly.

Since enabling options which prevent you from opening the app is generally not a good idea, I think that there should at least be a warning if this option is enabled on a system running a version of gnome without status icons.

**Comment by giuspen** [comment]
This issue exists also with the current Pygtk2 version, not only with GNOME but other linux desktops, maybe there is a way to know that the system tray is not supported in the current desktop and grey out the checkbox in that case leaving appindicator as only option.

**Comment by ForeverRainbow** [comment]
Looks like [gtk_status_icon_is_embedded](https://developer.gnome.org/gtk3/stable/GtkStatusIcon.html#gtk-status-icon-is-embedded) can be used to check for the existence of a system tray, the deprecated warning is just for using it for notifications I think

**Comment by ForeverRainbow** [comment]
Also you can use extensions to bring back the gnome tray so completely disabling this might also not be the best but :woman_shrugging: 

I am assuming there is no way to replicate the status icon functionality with `GNotification` (since it looks to be only dismiss-able notifications)

**Comment by txe** [comment]
Was resolved by #941

**Comment by ForeverRainbow** [comment]
@txe This wasn't resolved in the python version though, #941 only patches the C++ version

**Comment by txe** [comment]
it's OK. I think the C++ ver. is more or less ready to be a replacement for pygtk.
