### ISSUE TITLE
C++ Windows: Toolbar Editor Button Icons

### ISSUE THREAD

**Issue by metal450** [giuspen/cherrytree#929]
Minor: Under Preferences->Toolbar, on Windows, the 3 buttons along the right of that dialog have broken icons (Add, Remove, Reset To Default)

**Comment by txe** [comment]
@giuspen , some icons from Gtk::Stock don't work on win, so I replaced them by ct_.svg. But there is no for file (Gtk::Stock::FILE).
Can you add svg for it?

**Comment by giuspen** [comment]
@txe certainly thanks!

**Comment by giuspen** [comment]
@txe just pushed
