### ISSUE TITLE
C++ Windows Shows Double Slash

### ISSUE THREAD

**Issue by metal450** [giuspen/cherrytree#930]
Very minor graphical glitch: on Windows, the first slash in the path (shown in the titlebar) is doubled.

Screenshot: https://lnk2.tk/snaps/2020-06-17_15.54.33.png

**Comment by txe** [comment]
The issues was that double backslashes didn't converted back to single backslashes.
After fixing, config.cfg withl old file paths will still show double backslashes, so users have to themselves to remove old paths one way or another.
