### ISSUE TITLE
C++ Paste Formatting Bugs

### ISSUE THREAD

**Issue by metal450** [giuspen/cherrytree#931]
Two issues when pasting formatted text:

* Sizes mostly work, but while text that's "moderately small" pastes as small, text that's "even smaller" pastes as normal again.
* Justification is lost (center or right)

Here's a screenshot to illustrate (see text small vs text tiny): https://lnk2.tk/snaps/2020-05-25_12.01.46.png

**Comment by ForeverRainbow** [comment]
So is h1 pasting as h2? Or just h1 being small? I can't really tell from the picture but it looks like its pasting as h2

**Comment by txe** [comment]
The issue with 
```
if (font_size > 7 && font_size < 11)
    _add_tag_style(CtConst::TAG_SCALE, CtConst::TAG_PROP_VAL_SMALL);
```
is that it skips size less 8 and makes such text normal instead of small

**Comment by ForeverRainbow** [comment]
@txe That seems a weird condition for making small text, wonder why > 7 was/is needed?

**Comment by ForeverRainbow** [comment]
@txe That seems a weird condition for small text, why > 7 but < 11? Is that the cutoff for small text font-size?

**Comment by txe** [comment]
I know it doesn't make sense :)

**Comment by txe** [comment]
@ForeverRainbow , are you going to fix it?

**Comment by ForeverRainbow** [comment]
@txe I am working on `CtFileSystem` rn

**Comment by txe** [comment]
Text size is also fixed
