### ISSUE TITLE
[Feature Request] Add an option to disable ligatures

### ISSUE THREAD

**Issue by Thmyris** [giuspen/cherrytree#939]
This one is mainly about preference of looks and copy&paste convenience. When I copy some rich text from a CT node and paste it to somewhere else, in some cases the ligatures carry over. I then have to go ahead and manually fix characters that were combined into ligatures or changed to fancier versions. ~~(This is especially painful for copy&pasting bash code, but then again I shouldn't be using rich text nodes for that so I can't really complain.)~~
There's a feature in CT in Preferences -> Text -> "Enable Smart Quotes and Auto Replacement" that you can untick to disable ligatures for quotes. If that feature was extended to all characters that would be amazing. Regardless thanks for working on cherrytree and have an awesome year.

**Comment by txe** [comment]
Well, I not sure that cherrytree is guilty in such behavior. There is no reason to change the text copied in clipboard, you can make sure by using any clipboard manager, e.g. CopyQ. I think the destination programs change the pasted text.

Can you give an example of text, and there I can copy/paste it to see the issue?

**Comment by Thmyris** [comment]
A very simple example is this "=>". When I type it out in CT it molds together, but if you copy paste it here in the comment box it becomes "=>" again so not much of a problem here. The problem arises when you press 'space' after the mold occurs, it becomes a smaller 1-char-sized-arrow that if I copy/paste here looks like this: "⇒". Same thing happens with "->" which turns into "→", "*" turns into "•", "<>" turns into "◇" and so on.

**Comment by txe** [comment]
I'm sorry, I'm really confused by your comment. What does mold mean in this case? And
> if you copy paste it here in the comment box

Here is on github's comment box or CT codebox?
 
There are some rules in CT which converts symbols into one symbol, it doesn't matter if you type those symbols or paste them. 
If you don't want such behavior you either can untick the related options or change the node type from Rich Text to something else. 

The one issue I noticed is that text in codebox can be converted too (at least in C++ version), maybe you mean this?.  I don't think it's right and it should be possible to turn off. What do you think @giuspen ?

**Comment by giuspen** [comment]
@txe you are right such smart auto replacements should not happen in the code, only exception the plain text

**Comment by Thmyris** [comment]
I'm sorry I made this all confusing for you. I'm bad at explaining stuff. I'll start over and try to explain it better.

I'm only using rich text & plain text nodes. No code boxes, no Automatic Syntax Highlighting nodes are being used. I shouldn't have brought up code in the first place as this isn't about code. Basically I was asking for an option to disable ligatures completely. To stop the transformation of these 2 separate characters(=>):
![image](https://user-images.githubusercontent.com/14177706/85117646-12587380-b217-11ea-9045-875a1eef8835.png)
into this combined look: 
![image](https://user-images.githubusercontent.com/14177706/85116967-0324f600-b216-11ea-9bdb-3dd6b765dd46.png)
This is what I meant by molding together. I guess I should've written "binding together" instead. Also this is only half ligature transformation. The full ligature transformation converts multiple characters into 1 symbol. This is still 2 characters long, as you can see, I can select the right half of it:
![image](https://user-images.githubusercontent.com/14177706/85117153-539c5380-b216-11ea-93ce-fb75f1696f43.png)
The full transformation occurs after typing the => characters and then pressing space. When you do that the 2 characters combine into a 1 character long symbol. That's the symbol on line 2. It also becomes smaller to fit the 1 char space.
![image](https://user-images.githubusercontent.com/14177706/85117246-7890c680-b216-11ea-9474-4c27f8614789.png)
I can also copy that symbol from CT and paste it here on github and it's still 1 character: ⇒ . It doesn't transform back to its original => form.
The point of the post was to request an option to stop getting this combined look. An option that stops both half and full ligature transformations. That makes everything look originally as it is typed, with no binding together.

> There are some rules in CT which converts symbols into one symbol, it doesn't matter if you type those symbols or paste them.

Yes! To be able to change those rules is what I am after. I am a newbie programmer so I couldn't find where to look for in the code base. But if you guys could point me in the right direction I'd be happy to have a look.
> If you don't want such behavior you either can untick the related options or change the node type from Rich Text to something else.

I couldn't find the related options. The only thing I could find was unticking this option which disables ligatures for only , and " symbols.
![image](https://user-images.githubusercontent.com/14177706/85116822-ce18a380-b215-11ea-89b8-21d5ccc5f93f.png)
It stops them from turning into fancier versions.
![image](https://user-images.githubusercontent.com/14177706/85119376-901d7e80-b219-11ea-828a-0af95ad584dd.png)


Also this might be caused by the font I'm using which is "Fira Code Retina". If that's the case I'm very sorry I bothered you with this. Feel free to close the issue without further comments if you like.

Again sorry for the misunderstanding, I hope I was able to clear things up with this comment. Regardless have an awesome year you two.

**Comment by ForeverRainbow** [comment]
@Thmyris Your use of "ligature" confused me :p, had to look it up. 

So to be clear, you want to be able to transform auto-replaced characters back into the originals when copying text to the clipboard? There are a few issues with this I can think of 

1. Currently auto-replaced text is simply replaced by a unicode character, so `=>` becomes a unicode arrow, `*` a unicode bullet, etc. The problem with transforming those back when copying is identifying which ones were auto-replaced and which were inserted "manually" by the user
2. Why? I don't really see any reason for doing this tbh, if you want to _stop_ the auto-replacement in the first place you can untick "Enable Symbol Auto Replacement" in `preferences -> text`
3. If you want to get plain ASCII symbols/combinations from unicode characters, there probably exists a converter somewhere or write your own with some basic python/scripting, however that is outside of what cherrytree is meant to do

**Comment by txe** [comment]
@Thmyris , thanks , now I see your point.
When you uncheck "Enable Smart Quotes Auto Replacement", CT stop doing any fancy job with symbols. So, I am sure you can blame `Fira Code Retina` for it. (check README on https://github.com/tonsky/FiraCode). To turn of such behavior, you can try `Fira Mono`

**Comment by Thmyris** [comment]
@txe You are right, switching to `Fira Mono` or other fonts fixed the problem. But only partially. Take a look:
![image](https://user-images.githubusercontent.com/14177706/85133658-04b0e700-b233-11ea-8d07-738fef6b3e8c.png)
Even though "Enable Smart Quotes Auto Replacement" is unchecked in the settings, CT still converts the characters into symbols if those characters are the first thing to be typed in the line. If you type them later in the line it doesn't convert. I tried about 10 different fonts, all of which had the same behaviour. This is a font named `Z003`.
![image](https://user-images.githubusercontent.com/14177706/85134729-e0eea080-b234-11ea-9376-e3e34fc9b954.png)

 This happens on both rich text and plain text nodes but not on code nodes. I tried restarting CT in between changing any setting.

**Comment by txe** [comment]
What CT version do you use?

**Comment by Thmyris** [comment]
0.38.8

**Comment by txe** [comment]
The last version is 0.39.3. Can you update your version? You can find more info on https://www.giuspen.com/cherrytree/#downl

**Comment by Thmyris** [comment]
Can confirm the issue https://github.com/giuspen/cherrytree/issues/939#issuecomment-646623291 brings up does occur on 0.39.3

**Comment by txe** [comment]
Thanks, I'll take a look

**Comment by Thmyris** [comment]
@txe No don't bother, damn it, I forgot to disable the options about auto replacements after reinstalling. When you untick them https://github.com/giuspen/cherrytree/issues/939#issuecomment-646623291 is instantly fixed as well. Thank you so much for the help and sorry about causing all this fuss because of my own blunders. I'll close the issue as there is no issue left here.
Have a nice day everyone!

**Comment by txe** [comment]
Thanks! :)

**Comment by txe** [comment]
@giuspen , you wrote
> @txe you are right such smart auto replacements should not happen in the code, only exception may be the plain text

I checked, it works as you write

**Comment by giuspen** [comment]
@txe ok so we're good with that
