### ISSUE TITLE
C++ Bug: Adding Toolbar Separator

### ISSUE THREAD

**Issue by metal450** [giuspen/cherrytree#948]
In the C++ version on Windows, if you use Preferences->Toolbar to add a new separator, it appears to work  - but then when you quit & restart CherryTree, it has disappeared.  i.e. the change is reflected in the editor UI, but never on the application's main UI (even after quit & restart).

**Comment by txe** [comment]
Thanks for the issue, fixed.
Also, toolbar changes will be shown in real time without the app restart.
