### ISSUE TITLE
C++: Text vertical alignment of node names

### ISSUE THREAD

**Issue by metal450** [giuspen/cherrytree#949]
Minor graphical bug to report with the latest C++ alpha on Windows: the vertical alignment of the text showing node names is inconsistent in the node list.  Here's a screenshot: https://lnk2.tk/snaps/2020-06-21_11.55.38.png

i.e. relative to the cherry icon, some of the names are center-aligned (as expected), and others seem to be top-aligned.

**Comment by txe** [comment]
Did you try it on 0.99.2?

**Comment by metal450** [comment]
Yup, that's the version I'm currently testing

**Comment by txe** [comment]
It's really odd. There was a bug that 'Tree Nodes Names Wrapping Width' caused such issue (in Gtk3 wrapping in TreePanel doesn't work), so I had to turn off this option. Given that,  it cannot be your case.

I tried to create the same nodes and they looked normal. So I'm out of ideas. Can you give your config.cfg (you can remove any sensitive data from it) ?

**Comment by metal450** [comment]
Attached.

[config.zip](https://github.com/giuspen/cherrytree/files/4815011/config.zip)

**Comment by txe** [comment]
No, it didn't help.
Can you set `Tree Nodes Names Wrapping Width` to 500 and restart the app?

**Comment by metal450** [comment]
Same appearance (I had it set to 200 before, but 500 looks identical)

**Comment by txe** [comment]
@guispen, when you have spare time, can you try to reproduce the issue?

**Comment by giuspen** [comment]
Sure @txe I'll also try and reproduce in the next days, it's really odd, I have not seen it so far running in msys2 I would have noticed straight away.
Actually it looks like there is a newline at the end of the node name for some nodes, @metal450 have you entered the nodes names manually or pasted from somewhere? If you try and remove the trailing part of the node name what happens?

**Comment by metal450** [comment]
You got it!! No idea how you noticed that - yes, they were pasted from OneNote, and yes, it looks like there's an "invisible" newline character.  If I edit each name & press backspace once, nothing appears to have changed in the Edit Node dialog, but once I click OK, it fixes the alignment.

So perhaps the general fix would be to just do a "trim whitespace" on the node name after editing node properties :)

**Comment by txe** [comment]
good catch, @giuspen !

**Comment by giuspen** [comment]
great! :)

**Comment by txe** [comment]
Fixed, thanks for the issue!
