### ISSUE TITLE
CRITICAL: I cant buy you a coffee

### ISSUE THREAD

**Issue by chppppp** [giuspen/cherrytree#951]
Hi @giuspen!! I just got an email on an issue I am tracking on your project and saw you have 378 open issues!!! Holy guacamole! 

Your editor is wildly popular with OSCP students and more. I personally dont want to dive into the mountain of posted issues here (whether they are all legit or not is another issue ;D) but I would love to be able to support your project other than the bitcoin donate link on your website. 

I hope you consider Patreon, Buymeacoffee, or similar donation sites. I would love to help ease the pain of your project by just fucking giving you money  :) 

Thanks for your project, it is a gift to the community, and thank you for your time and dedication.

**Comment by giuspen** [comment]
hi @chppppp thanks for your colored feedback ;)

**Comment by steveno** [comment]
@giuspen On a serious note, have you considered signing up for GitHub sponsors?

https://help.github.com/en/github/supporting-the-open-source-community-with-github-sponsors/about-github-sponsors

**Comment by giuspen** [comment]
I'll have a look thanks @steveno

**Comment by eternaltyro** [comment]
I would love to pay for this (excellent) program too: preferably via Liberapay or Opencollective
