### ISSUE TITLE
sql backend - 10MB attachment size limitation

### ISSUE THREAD

**Issue by DiagonalArg** [giuspen/cherrytree#952]
Is there a fundamental reason for attachments to be limited to 10MB using the sql backend?  Is using XML a work-around?

If there is no fundamental reason, can it be changed?

**Comment by txe** [comment]
Looks like a work-around. Instead of forbidding, we can give a warning of exceeding the limit and ask if they want to continue. So users still control the db size in case if it's important.

**Comment by giuspen** [comment]
It was meant to limit the size of the embedded files especially for the XML but @txe is right, we should change to a warning message instead and theoretically the warning could have different thresholds according to XML or SQLite where larger files are better handled.

**Comment by DiagonalArg** [comment]
So my related question then is, the more I use CT, the more I realize that much of the time I really don't want a filesystem.  What I want is a database of notes that operate as glue and throughout which my files are embedded.  The filesize impediment was one problem I have come up against, but if that restriction is loosened, do you see others?

**Comment by txe** [comment]
I honestly don't know, but maybe I'm used to

**Comment by giuspen** [comment]
These embedded files are not edited in place, when you open them you are actually copying to a temporary location from the dB to the filesystem, opening with the external application, editing and then copying the modified version from the filesystem temporary location back to the database. This obviously is not as efficient as just having a file on the filesystem.

**Comment by ForeverRainbow** [comment]
@giuspen maybe images could be cached then? So store the image path (or the path for it to go to) and then do a check when viewing images whether the image already exists in that path, if it does open it, if not copy to it and then open it. In fact it doesnt even need to be stored with the image, could just be a predefined path with the of the image appended or something

**Comment by giuspen** [comment]
@ForeverRainbow what you are proposing is a new separate mode or an improvement of the current implementation? Remember that the document could be encrypted and especially in that case we are not meant to leave stuff in clear out on the filesystem

**Comment by ForeverRainbow** [comment]
@giuspen Improvement, so that the file doesnt have to be decoded and reencoded each time. Also if its encrypted then it can be bundled as part of the encrypted archive right? Can't be kept on the filesystem like an unencrypted one but still faster just to unpack it with the database/xml file than to encode and decode it on demand

**Comment by txe** [comment]
@DiagonalArg, are you ok with my comment, or some more work should be done?

**Comment by DiagonalArg** [comment]
@txe - you mean of a warning?  Yes, that's fine.

I am not sure I understand the issues about caching that @ForeverRainbow is discussing; but any speedup, sounds good to me!  :)

@giuspen mentions that the limit was mainly for XML.  That  too confuses me.  I know HTML, and so somehow I would have thought the XML would link to external files, but I guess attached files are stored as some binary encoding within the XML?

In any case, that's just curiosity.  The warning is fine, thanks.  You guys are great.  This is the most responsive project I've seen on github, and I report lots of bugs!

**Comment by txe** [comment]
Thanks @DiagonalArg

**Comment by txe** [comment]
I'm sorry, I couldn't figure out why the question about the limit was raised because I thought there was an option in Preference dialog to change the limit. Turns out this option is hidden, it can be change by editing `config.cfg`, the options is `embfile_max_size`.

**Comment by DiagonalArg** [comment]
Ah, ok!  TY.
