### ISSUE TITLE
CherryTree stopped saving.

### ISSUE THREAD

**Issue by gitbrake** [giuspen/cherrytree#955]
So after restarting CherryTree for the first time in a few days, I've just found that it had not actually saved a thing for 4 days despite manual and auto saves, and the presence of files with dates indicating saves just before restarting CherryTree.

This is on Windows 10 x64, CherryTree 0.39.3. I'm assuming I've just lost a good 24 hours worth of work - but if there's some log or some way I can debug this so it doesn't happen to other people, I'm happy to help out, but to say I'm annoyed right now would be a pretty big understatement.

The files are encrypted sql files (.ctx).

**Comment by giuspen** [comment]
Hi @gitbrake I'm sorry to hear that, if you write anything to a node, Ctrl+S, close cherrytree, reopen cherrytree can you see the saved data at all or you keep seeing the original data before the last edit?

**Comment by gitbrake** [comment]
Unfortunately not. Looking back through the backups (and cloud backups) indicates the file size (along with the ~, ~~, and ~~~ backups) also hadn’t changed in days. 

Looks like for whatever reason the SQLite database was not syncing. :(

**Comment by ForeverRainbow** [comment]
@gitbrake Yes I think this is a known issue with the python version. The database is not checked for corruption before saving or backing up and commit errors are silently ignore (afaik, I haven't really worked with the python version). The C++ version has fixed this in #943 but it is still being tested so if you want to use that version make manual backups of your data and save regularly

**Comment by txe** [comment]
@gitbrake, you need to check if the file is corrupted or not.

The file itself is an sqlite database. You can open it by [sqlitebrowser](https://sqlitebrowser.org/).
After opening the file, execute a command there:
```
PRAGMA integrity_check;
```
If it doesn't return "OK", then the file is broken and should be recovered. You can read more about recovery in [this article](https://techblog.dorogin.com/sqliteexception-database-disk-image-is-malformed-77e59d547c50)

**Comment by ForeverRainbow** [comment]
@txe The file is encrypted though, it uses 7z right? So they should be able to extract it with the 7z application?

**Comment by txe** [comment]
Ah, didn't notice.
But you're right, the file can extracted by 7z.

**Comment by gitbrake** [comment]
Yeah correct, you can just extract with 7z/open with sqlite3. I'd opened the file prior to this post to do this, but hadn't checked the integrity.

The main .ctx file and the backups and all returned OK.

For the sake of the experiment, I dumped all INSERTs to disk and reimported as per the linked article from @txe, but none of the newer content was there.

Really seems that it just wasn't committing/syncing.

Thanks for the ideas though.

**Comment by gitbrake** [comment]
Interestingly, I can't save my current file as an xml file.

I receive a <file location> write failed - tree to xml.

**Comment by txe** [comment]
Can you try to open and resave by C++ version (0.99.2)? You can find it on https://www.giuspen.com/cherrytree/#downl

**Comment by gitbrake** [comment]
Yep - it saves as XML from 0.99.2. 

Testing the re-saved XML file in 0.39.4 and it opened, but then ran into the same problem with saving.

**Comment by txe** [comment]
Well, maybe it throw some exceptions during saving.
if you start CT from cmd, then it will output the exception and callstack.

**Comment by gitbrake** [comment]
I opened up the original sqlite file in 0.99.2 and it crashes too.

[2020-06-24 19:11:36.362] [GTK Logger] [info]
unhandled exception (type std::exception) in signal handler:
what: Document not well-formed.
Line 1709, column 22 (fatal):
PCDATA invalid Char value 1

Looks like it was where I had pasted some output from Immunity Debugger. This doesn't seem to be an issue in the 0.39.4 branch (the file opens without crashing), but I wonder now whether this was some of the cause of the initial issue.

...
00149E70   FFFFFFFF  ├┐├┐├┐├┐
00149E74   0042E7C0  ├Ç├ºB.  
00149E78   008F2A60  `*┬Å.  
</rich_text><rich_text weight="heavy">00149E7C   0014AB00  .┬½.  </rich_text><rich_text>
00149E80   00422F50  P/B.  
00149E84   00000001  ...
00149E88   008F2A60  `*┬Å.  
LIne 1709: **00149E8C   00000000  ....**
00149E90   008F2A60  `*┬Å.  
00149E94   0052F2D8  ├ÿ├▓R.
00149E98   00422580  Γé¼%B.  


0041F23E</rich_text></node>

**Comment by txe** [comment]
Can you upload that output from Immunity Debugger, so I can try it on my machine?

**Comment by gitbrake** [comment]
And in response to your question around exceptions during saving.

Traceback (most recent call last):
  File "core.pyc", line 1606, in file_save
  File "core.pyc", line 1729, in file_write
  File "machines.pyc", line 325, in treestore_to_dom
  File "xml\dom\minidom.pyc", line 61, in toprettyxml
  File "StringIO.pyc", line 271, in getvalue
MemoryError
Traceback (most recent call last):
  File "core.pyc", line 3771, in on_window_delete_event
  File "core.pyc", line 3748, in quit_application
  File "core.pyc", line 3755, in quit_application_totally
  File "core.pyc", line 3782, in check_unsaved
  File "core.pyc", line 1606, in file_save
  File "core.pyc", line 1729, in file_write
  File "machines.pyc", line 325, in treestore_to_dom
  File "xml\dom\minidom.pyc", line 61, in toprettyxml
  File "StringIO.pyc", line 271, in getvalue
MemoryError

**Comment by gitbrake** [comment]
[node.txt](https://github.com/giuspen/cherrytree/files/4824464/node.txt)

This is the Immunity Debugger output. The errant character is on Line 6. (assuming this is 0x01 from the exception above).

**Comment by txe** [comment]
No, it works ok. Did you copy/paste it from the console output? Can you copy from the node instead? Or even open the xml file in an editor and copy the node from there.

**Comment by gitbrake** [comment]
See attached. test.ctb was created in 0.39.4, while test2.ctb was created in 0.99.2 (by copy/pasting the text from node.txt from Notepad++).

[Character Test CTBs.zip](https://github.com/giuspen/cherrytree/files/4824643/Character.Test.CTBs.zip)

Both open fine in 0.39.4, but both crash 0.99.2 when you click on the 'Test' node.

**Comment by txe** [comment]
Thanks, the given files show the issue, I'll fix it

**Comment by txe** [comment]
Fixed, thanks for the issue!
