### ISSUE TITLE
copy/paste of web page content can crash cherrytree

### ISSUE THREAD

**Issue by gahisee** [giuspen/cherrytree#958]
from time to time, i copy some portion of web pages and paste into cherrytree.
if the content is all text, it seems to succeed.
however if it contains images, paste will likely crash cherrytree.  it simply closes.

i am currently enjoying v0.99.1.
please let me know if i need to gather more data but this should be readily reproducible.

**Comment by ForeverRainbow** [comment]
@txe I noticed an error message when the link for an image couldn't be found/decoded recently. Possibly 0.99.1 is missing a catch which was added later? (Or this could be completely unrelated ofc)

**Comment by mahdi1234** [comment]
If it helps I'm able to repro with https://joinmobilizon.org/en/faq/ and this text (copy from webpage so it's rich)

> What is Mobilizon?
> 
> It’s software that, once installed on a server, will create a website where people can create events, similar to Facebook events or MeetUp.
> 
> Installing Mobilizon will allow communities to free themselves from the services of tech giants by creating their own event platform. This installation (called “instance“) can easily interconnect with others like it, thanks to a decentralised federation protocol.

**Comment by ForeverRainbow** [comment]
If you can reproduce this can you run cherrytree from the commandline and post the output?

Also @txe maybe now is the time to add a log file(s)?

**Comment by txe** [comment]
@gahisee I'll take care of it, thanks
@mahdi1234 , thanks for the example, it'll be useful
@ForeverRainbow , right

**Comment by gahisee** [comment]
great! that was a quick fix.
is there a new 0.99.2 available for download?

**Comment by giuspen** [comment]
I'm going to package a new version 0.99.3 in the weekend

**Comment by gahisee** [comment]
it's fixed! thank you!
