### ISSUE TITLE
C++ CTRL+Z after paste jumps to strange positions

### ISSUE THREAD

**Issue by mahdi1234** [giuspen/cherrytree#961]
Latest build on gentoo

- have some node with text over multiple screens and scroll somewhere down/bottom
- paste any text
- CTRL+Z

it does some strange refresh of whole screen

- click somewhere else
- past same or other text
- CTRL+Z

now pointer moves to the place where original text was placed

- repeat pasting at random locations and then undo with CTRL+Z

it sometimes jumps back to the original position, sometimes just does weird screen refresh/scroll

**Comment by metal450** [comment]
I'm experiencing strange "jumps" when undoing even if not right after a paste (on Windows, lastest C++ master built from source).  i.e. sometimes I will have highlit some text, changed formatting, then undo - and the window jumps all the way back to the top.  Happens frequently.

**Comment by metal450** [comment]
Note: you can actually undo, redo, undo, redo, and it jumps around unpredictably - i.e. even undoing & redoing the same action back & forth doesn't jump to "predictable" strange places.  I was trying to see if I could figure out a pattern for where it's jumping...but it doesn't even seem to follow a pattern, that I can tell.

**Comment by txe** [comment]
Fixed. But if it is not, please reopen the issue.
