### ISSUE TITLE
[0.99.2,win64] Custom Background and Text Colors not working

### ISSUE THREAD

**Issue by kettenfett** [giuspen/cherrytree#968]
The settings for Custom Background and Text Colors in the "Rich Text" Tab are not being applied. Instead, I'm getting a white Background. Even after restarting CT.

Monospace is working.
Color Settings in Tab "Tree 1" also work.

![grafik](https://user-images.githubusercontent.com/23098362/85926307-e8e6ba00-b89e-11ea-82a7-573a03e2bcf7.png)

**Comment by txe** [comment]
Hi, thanks for the issue.
It's known, you can read about it in #896
