### ISSUE TITLE
Feature Request: Use ccache to improve re-compile times

### ISSUE THREAD

**Issue by cmorgenstern** [giuspen/cherrytree#970]
I am very excited about the port to C++/GTKmm, and I would like to thank the developers for all their amazing work they have done on the project so far.

I am one of the co-maintainers of [cherrytree](https://aur.archlinux.org/packages/cherrytree/) in the Arch Linux User Repository ([AUR](https://aur.archlinux.org/)) and I have been doing a lot of builds using the C++/GTKmm port in preparation for packaging it once it's a bit more stable. Since the compile time is definitely longer compared to the current stable Python2 version, I was wondering if you would be willing to include instructions for using [ccache](https://ccache.dev/) to help speed up re-compile times?

I believe this could be accomplished by adding something like the following to the C++/GTKmm port `CMakeLists.txt` (example borrowed from [here](https://raw.githubusercontent.com/strawberrymusicplayer/strawberry/master/CMakeLists.txt)):

```
find_program(CCACHE_EXECUTABLE NAMES ccache)
if (CCACHE_EXECUTABLE)
  message(STATUS "ccache found: will be used for compilation and linkage")
  SET_PROPERTY(GLOBAL PROPERTY RULE_LAUNCH_COMPILE ${CCACHE_EXECUTABLE})
  SET_PROPERTY(GLOBAL PROPERTY RULE_LAUNCH_LINK ${CCACHE_EXECUTABLE})
endif ()
```

Thank you for your consideration.

**Comment by txe** [comment]
Hi, why not use `-DCMAKE_CXX_COMPILER_LAUNCHER=ccache` ?

**Comment by ForeverRainbow** [comment]
Isn't the usual way to use ccache to symlink it as gcc? That or point `CXX` and `CC` to it.

**Comment by cmorgenstern** [comment]
My apologies - looks like the clean chroot I have been using to run test builds was not explicitly making ccache available to the cherrytree build. I've fixed the issue locally.

I assumed the ccache instructions I referenced in my first post were a necessary prerequisite because a couple of other cmake projects I have been building in this clean chroot use them. I guess you could still include these in the C++/GTKmm port, but it's functionally a no-op, since ccache should ideally be made available via symlink/environment variable locally as you both correctly pointed out.

**Comment by kencu** [comment]
Just chiming in unasked, but on MacPorts we do prefer to have ccache used only if we configure it to be used (we have global and local build settings to do this) rather than have software builds seek out ccache on their own and use it if found. Reproducible builds and all that. Back down my hole now. :>

**Comment by txe** [comment]
Well, then we leave it as is
