### ISSUE TITLE
"Virus" in Cherry file detected by Defender seems to break the file

### ISSUE THREAD

**Issue by ricardojoserf** [giuspen/cherrytree#972]
Hi, during a project I created a Cherrytree file and added some code which was detected by Windows Defender as a virus (troojan more exactly). Opening the file as administrator a log file is generated with this content:

```
Traceback (most recent call last):
  File "core.pyc", line 1744, in file_open
  File "core.pyc", line 1794, in filepath_open
  File "core.pyc", line 2002, in file_load
  File "ctdb.pyc", line 642, in read_db_full
sqlite3.DatabaseError: file is encrypted or is not a database
Traceback (most recent call last):
  File "core.pyc", line 1744, in file_open
  File "core.pyc", line 1794, in filepath_open
  File "core.pyc", line 2002, in file_load
  File "ctdb.pyc", line 642, in read_db_full
sqlite3.DatabaseError: file is encrypted or is not a database
```

I do not know if there is anything I could do to recover this file; never, never had Defender detected something in any of my Chrrey files and now this happens xDD

**Comment by txe** [comment]
Well, it's not cherreytree issue obviously. You can turn off the defender to open the file to remove bad data from it. Or put the file in the directory which the defender won't check.

**Comment by ricardojoserf** [comment]
Thanks for the feedback @txe . I have been using Cherrytree for years and this is the first time that happened to me! I could solve it anyways, just thought it should be noted. Thank you for closing the issue!

**Comment by azharbajened** [comment]
> 
> 
> Thanks for the feedback @txe . I have been using Cherrytree for years and this is the first time that happened to me! I could solve it anyways, just thought it should be noted. Thank you for closing the issue!

hii bro, do you solve this issue ?

**Comment by ricardojoserf** [comment]
Hi @azharbajened , I think I restored the files deleted by Windows Defender (I found it by googling) and disabled it again but now using registry keys. Also when you get the cherry file again, create a password protected zip in case this happens, that is what I did just in case ;) And I stopped using Cherrytree to store things like amsi bypasses and that kind of stuff hahaha
