### ISSUE TITLE
Cherrytree snap package all text are rectangles

### ISSUE THREAD

**Issue by arensonzz** [giuspen/cherrytree#974]
Hello,
I'm using ubuntu 20.04, tried both stable and edge snap packages. The problem is all text in application appear as rectangles (added a screenshot). I tried changing font in preferences but when i click to another font, application immediately closes. How can I solve this problem?
Thank you.

![cherrytree-font](https://user-images.githubusercontent.com/56973411/86252529-04fa9c00-bbbc-11ea-97af-03edc2a2d0b1.png)

**Comment by giuspen** [comment]
Either use the flatpak package or try the development version 0.99.3 scroll below the stable in the download section

**Comment by arensonzz** [comment]
> Either use the flatpak package or try the development version 0.99.3 scroll below the stable in the download section

Flatpak package works for me. Thank you for your quick reply.
