### ISSUE TITLE
Client crashes after attempt to attach image which was coppied to buffer in browser

### ISSUE THREAD

**Issue by eugene-yakimenko** [giuspen/cherrytree#978]
Trying to attache  image from firefox brom buffer, after that it sticks and crashes. Attachment from local file system work perfectly. Previously it worked in Kubuntu 19.10.
P.S. Kubuntu 20.04.

**Comment by giuspen** [comment]
Hi, what cherrytree version

**Comment by eugene-yakimenko** [comment]
Hi,
Oh sorry forgot.
[image: image.png]
will try to update as i seen you put out new ver on 29 jun

чт, 2 июл. 2020 г. в 22:34, Giuseppe Penone <notifications@github.com>:

**Comment by eugene-yakimenko** [comment]
seems it works in new version

пт, 3 июл. 2020 г. в 12:11, Yakimenko Eugene <yakimenkoev@gmail.com>:

**Comment by giuspen** [comment]
Ok cheers will close this then
