### ISSUE TITLE
[Bug] Double clicking a node's expand icon(+) causes another selected node to expand

### ISSUE THREAD

**Issue by Thmyris** [giuspen/cherrytree#987]
**Version:**
CherryTree 0.39.4

**Tested on:**
Windows 7 SP1
Kali Linux 2020.1b XFCE

**Steps to reproduce:**

1) We have 2 nodes that has some subnodes under them. Both nodes are collapsed.
2) Select the 1st node in tree view by clicking on it once (making it turn blue on default theme).
3) Move mouse to the 2nd node's expand icon (+)
4) Double click to quickly expand and collapse that node's subnodes.

**Expected Behaviour:**
Only the 2nd node should expand and collapse as we double click it's expand icon(+).

**What happens instead:**
2nd node expands and collapses correctly however the 1st node also expands. 

Youtube video(At first I click slowly to demonstrate the bug doesn't occur when you don't double click quickly):
https://youtu.be/I4Jfex2DqyQ

Note: This bug also occurs if the 1st node is expanded from the start.

**Comment by txe** [comment]
Thanks for the issue, fixed!

**Comment by Thmyris** [comment]
I thought this was an edge case bug with a very low priority yet you fixed it! You rock man!
