### ISSUE TITLE
build future on mac

### ISSUE THREAD

**Issue by Shizzlebix** [giuspen/cherrytree#994]
Hey there,

if i build the future on mac so that i can use it like yet... there comes the follow error @make 

`[ 82%] Building CXX object src/ct/CMakeFiles/cherrytree_shared.dir/ct_actions_edit.cc.o
In file included from /cherrytree/future/src/ct/ct_actions_edit.cc:22:
In file included from /cherrytree/future/src/ct/ct_actions.h:26:
In file included from /cherrytree/future/src/ct/ct_dialogs.h:27:
In file included from /cherrytree/future/src/ct/ct_filesystem.h:26:
/cherrytree/future/src/ct/ct_splittable.h:108:5: error: exception specification of explicitly defaulted move constructor
      does not match the calculated one
    CtSplittable(CtSplittable&&) noexcept = default;
    ^
/cherrytree/future/src/ct/ct_config.h:102:49: note: in instantiation of template class 'CtSplittable<Glib::ustring,
      std::__1::vector<Glib::ustring, std::__1::allocator<Glib::ustring> > (*)(const Glib::ustring &)>' requested here
    CtStringSplittable                          specialChars{CtConst::SPECIAL_CHARS_DEFAULT};
                                                ^
1 error generated.
make[2]: *** [src/ct/CMakeFiles/cherrytree_shared.dir/ct_actions_edit.cc.o] Error 1
make[1]: *** [src/ct/CMakeFiles/cherrytree_shared.dir/all] Error 2
make: *** [all] Error 2`

**Comment by ForeverRainbow** [comment]
I'll look into it, in the meantime #982 is the most recent I can find which built sucessfully on mac (checkout commit ff09b10977ec2184631b4a224ce6394074f213a7). Does that build sucessfully for you?

**Comment by ForeverRainbow** [comment]
I cannot reproduce this, I am guessing it is something specific to mac although it is strange that it should only be an issue now and that #982 and previouse ones built fine although `CtSplittable` and related havn't been touched since it was introduced (#838) afaik.

Be interested to know if you can build #982

**Comment by txe** [comment]
Hi, I can build the current source in Travis and vm with Catalina .
What are your macos and clang versions?
